### ISSUE TITLE
Plugin/Mod compatibility issue report

### ISSUE THREAD

**Issue by IzzelAliz** [IzzelAliz/Arclight#10]

**Comment by IzzelAliz** [comment]
https://paste.ubuntu.com/p/znjbzjrFZ4/
simplefarming cactus block, maybe we need a system similar to sponge's cause.

**Comment by KonjacCool** [comment]
https://paste.ubuntu.com/p/rpXr9TTQ3C/
开启的时候出现文本中问题！

**Comment by IzzelAliz** [comment]
> 
> 
> https://paste.ubuntu.com/p/rpXr9TTQ3C/
> 开启的时候出现文本中问题！

已经在最近的几次提交中修复，请在构建站下载最新版

**Comment by KonjacCool** [comment]
https://paste.ubuntu.com/p/SzBhxQkFkG/
1.15.2最新构架（#107）运行 QuantumRPG v5.0.10 出现文本中错误。
（感谢开发大佬辛苦修复）

**Comment by IzzelAliz** [comment]
> 
> 
> https://paste.ubuntu.com/p/SzBhxQkFkG/
> 1.15.2最新构架（#107）运行 QuantumRPG v5.0.10 出现文本中错误。
> （感谢开发大佬辛苦修复）

这个挺麻烦的，之后会修

**Comment by KonjacCool** [comment]
https://paste.ubuntu.com/p/fd6YKKZwhh/
这个貌似和QRPG问题差不多用的插件是AttributePlus2.20
https://paste.ubuntu.com/p/BWxfSw4ypb/
这个好像是检查更新强制终止了
（辛苦开发大佬了）

**Comment by IzzelAliz** [comment]
> 
> 
> https://paste.ubuntu.com/p/fd6YKKZwhh/
> 这个貌似和QRPG问题差不多用的插件是AttributePlus2.20
> https://paste.ubuntu.com/p/BWxfSw4ypb/
> 这个好像是检查更新强制终止了
> （辛苦开发大佬了）

与我无关，这是网络连接问题
