### ISSUE TITLE
加载 Patcher 时发生错误

### ISSUE THREAD

**Issue by anime801** [IzzelAliz/Arclight#100]
我正在运行
Arclight [arclight-forge-1.15-1.0.16-SNAPSHOT]

你确认这是最新版吗 [是]

mod 还没有安装

你确认所有插件都已更新至对应版本 [是]

Java [版本]
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

操作系统 [windows7 x64 ]

错误描述
插件基本都启动正常了……  但是这次是加载插件时直接提示的错误…… 无法知道是哪个插件造成的
这个情况非常奇怪，我一个一个插件安装 ， 一个插件一个插件的启动～然后就会碰上这个问题，之前用1015的版本会直接提示前面安装的几乎所有插件都无法读取，群内海螺大佬给出了升级服务端的建议，现在升级了最新的1016快照版，我还是一个一个插件进行安装，前面都没问题，在我以为不会再有问题的时候突然发现，这个加载插件时错误的一大段信息又出现了，即使我删掉了刚刚安装的几个插件  都无法解决这个问题，无奈我只能再次把插件都删掉，再一个一个的安装……
现在我又白折腾了一天 ……  求大佬们救救我吧。
报错信息
[错误日志]

https://paste.ubuntu.com/p/hYg7jgjYfZ/

这是晚些时候的错误报告
https://paste.ubuntu.com/p/M8dX3fxWJ9/

这份报告更厉害……  之前没有出错的 DisplayShops 插件  莫名其妙的出现了错误…… 重新下载安装都不行。

**Comment by IzzelAliz** [comment]
[DisplayShops] Vault was either unable to be found or an economy plugin was missing. Disabling...
