### ISSUE TITLE
使用机械动力及Kotlin for Forge两个mod时无法启动Arclight

### ISSUE THREAD

**Issue by OkaSode** [IzzelAliz/Arclight#1008]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

Arclight-1.19.2-1.0.2

### Java 版本 | 操作系统

Windows 11（开发机）Windows Server 2012R2（生产环境） | 均为同版本 jdk 17

### 相关 Mod/插件 的名称及版本

```raw
kotlinforforge-3.11.0-all.jar
create-1.19.2-0.5.1.b.jar
```

### 错误描述

在使用Kotlin Forge支持库时可能误将forge内置的语言库jar识别为模组以寻找mods.toml未果，无法启动Arclight。
forge版本手动升级为1.19.2-43.2.14，无效
使用最小安装法（仅启用有关mod），无效
切换不同的环境和操作系统（Win11和WS2012R2），无效
重新安装Arclight和Forge，无效

### 复现步骤

安装机械动力1.19.2最新版及其前置Kotlin for Forge
正常参数启动服务端

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/11690043/latest.log)

**Comment by IzzelAliz** [comment]
路径不要有中文

**Comment by OkaSode** [comment]
谢谢，将会按照给出的方法重新操作

**Comment by OkaSode** [comment]
经检查，发现存在2个问题，但都已解决
1 中文路径（已解决）
2 部分模组冲突（已禁用部分模组）
非常感谢，Arclight已成功运行。
