### ISSUE TITLE
[1.18 Suggestion] Forge update

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#1012]
An update to forge 40.2.4 since some mods such as Create mod now needs at least that version

**Comment by ElFumao420** [comment]
> An update to forge 40.2.4 since some mods such as Create mod now needs at least that version

yes please

**Comment by Shybella** [comment]
<img width="343" alt="image" src="https://github.com/IzzelAliz/Arclight/assets/4436776/3b726ce5-7ed7-433e-9423-65ee448d15df">

You can update it manually, its simple to do.

**Comment by muriplz** [comment]
yes, I know how to do it, but it's not the same as updating arclight. There could be issues this way. I'm currently using 40.2.4, but I'd like this version to be supported by arclight directly.
