### ISSUE TITLE
[1.19.2] 发光效果失效

### ISSUE THREAD

**Issue by Dr-WeiAL** [IzzelAliz/Arclight#1021]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.2-1.0.2-4a870b30

### Java 版本 | 操作系统

系统：Windows 10，Java：openjdk version "17.0.4" 2022-07-19

### 相关 Mod/插件 的名称及版本

```raw
无任何模组和插件
```

### 错误描述

![image](https://github.com/IzzelAliz/Arclight/assets/47446553/0d695b58-2d99-4e99-87cf-3d8439e23d50)
实体边缘不会发光，也无法透过墙观察到

### 复现步骤

1.给实体赋予发光状态效果

**Comment by xiao-en-5970** [comment]
咋解决阿，困扰好久了
