### ISSUE TITLE
[1.19.2] 监守者索敌异常

### ISSUE THREAD

**Issue by Dr-WeiAL** [IzzelAliz/Arclight#1022]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.2-1.0.2-4a870b30

### Java 版本 | 操作系统

系统：Windows 10，Java：openjdk version "17.0.4" 2022-07-19

### 相关 Mod/插件 的名称及版本

```raw
无任何模组和插件
```

### 错误描述

监守者在锁定目标后会永久锁定该目标
也就是说就算把目标杀死后仍然会锁定这个目标，并尝试释放声波攻击，但因为目标已经死亡，所以释放失败
![image](https://github.com/IzzelAliz/Arclight/assets/47446553/13f144ef-b526-4a15-a9b0-71aa4856f7c8)

在锁定玩家的时候，把玩家杀死后仍然会以这个玩家为目标，不会攻击旁边的其他人，就算其他人在攻击监守者也不会切换索敌

### 复现步骤

1.生成监守者
2.监守者攻击某个实体
3.就会永久锁定这个实体

**Comment by IzzelAliz** [comment]
在 #1049 修复
