### ISSUE TITLE
[1.18.2]参照FAQ升级Forge版本后无法启动服务器

### ISSUE THREAD

**Issue by SharwOrange** [IzzelAliz/Arclight#1031]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.8.jar

### Java 版本 | 操作系统

Windows10 22H2 19045.3086 ; java version "17.0.3.1" 2022-04-22 LTS

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

按照FAQ中将自带的Forge 40.1.80替换到Forge 40.2.9后无法启动
Forge是在https://files.minecraftforge.net/下载的
安装无报错
安装后将1.18.2-40.1.80文件夹中的unix_args.txt和win_args.txt替换到1.18.2-40.2.9文件夹中
1.18.2-40.2.9文件夹改名为1.18.2-40.1.80
forge-1.18.2-40.2.9-server.jar改为forge-1.18.2-40.1.80-server.jar
forge-1.18.2-40.2.9-universal.jar改为forge-1.18.2-40.1.80-universal.jar
运行start.bat报错

### 复现步骤

从https://files.minecraftforge.net/下载forge-1.18.2-40.2.9-installer.jar

安装40.2.9的Forge

安装后将1.18.2-40.1.80文件夹中的unix_args.txt和win_args.txt替换到1.18.2-40.2.9文件夹中
1.18.2-40.2.9文件夹改名为1.18.2-40.1.80
forge-1.18.2-40.2.9-server.jar改为forge-1.18.2-40.1.80-server.jar
forge-1.18.2-40.2.9-universal.jar改为forge-1.18.2-40.1.80-universal.jar

运行start.bat报错

### 报错信息

[debug.log](https://github.com/IzzelAliz/Arclight/files/11994346/debug.log)

**Comment by Shybella** [comment]
The debug log does not print the error, however can confirm 40.2.9 isn't working either, 40.2.4 is the latest that works.

**Comment by SharwOrange** [comment]
ok,thanks you
it's working
