### ISSUE TITLE
bossshop 插件遇到问题

### ISSUE THREAD

**Issue by anime801** [IzzelAliz/Arclight#104]
输入插件商城命令时出现
“试图执行该命令时出现意外错误”
鼠标指针提示  unhandled exception executing command 'bs' in plugin bossshoppro v2.0.8
输入完整的bossshop  命令  依然提示意外错误
后台只有输入提示    没见到大段的错误报告
issued server command:/bs  
issued server command:/bossshop

**Comment by IzzelAliz** [comment]
你没装 Vault
