### ISSUE TITLE
[Sorry,1.19.2] 根据FAQ更换forge后mod依旧无法运行

### ISSUE THREAD

**Issue by fenlincao** [IzzelAliz/Arclight#1041]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.2

### Java 版本 | 操作系统

java version "17.0.7" 2023-04-18 LTS；Windows11 专业版 21H2

### 相关 Mod/插件 的名称及版本

```raw
forge mod：
Forgematica/Litematica-Forge  即全息蓝图   version：0.1.5-mc1.19.2
MaFgLib/MaLiLib-Forge  即全息蓝图前置    version：0.1.6-mc1.19.2
```

### 错误描述

当我将mod装在forge端43.2.6中时，正常运行，但当mod装在forge端43.2.11时，却无法正常运行，而当我将mod装在arclight端1.0.2（即forge43.2.11）时，无法正常运行，但当我更换完forge版本后（换为43.2.6）arclight端依旧无法正常运行，我猜想可能是我更换forge的方法不正确或者是arclight端的本身问题或者是此mod的问题，关于我更换forge的具体步骤我会在下面的复现步骤中详细说明
很抱歉因为1.19.2打扰您，再次感谢！

补充：有一个很奇怪的现象，当我在forge端43.2.6运行全息蓝图时，服务端无需前置（正如mcmod上对此前置所作的说明：客户端需装, 服务端无效）但当我在forge端43.2.11运行时，第一次报错说需要前置，但在加入前置后依旧报错（此次报错原因不详，但并非因为前置），同样，当我将全息蓝图加入arclight端时，无论是否更换forge，情况都一样，第一次报错说需要前置，加入后依旧报错。

### 复现步骤

1.安装arclight端
2.下载forge43.2.6
3.将forge43.2.6 server安装到arclight端文件夹
4.在\libraries\net\minecraftforge\forge中将43.2.11文件夹中的unix_args、win_args替换到43.2.6文件夹
5.将forge-1.19.2-43.2.6-server重命名为forge-1.19.2-43.2.11-server
6.将forge-1.19.2-43.2.6-universal重命名为forge-1.19.2-43.2.11-universal
7.删除43.2.11文件夹，将43.2.6文件夹重命名为43.2.11
8.启动arclight端，成功
9.加入全息蓝图，再次启动，报错！

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/12064780/latest.log)

**Comment by IzzelAliz** [comment]
使用最新构建
