### ISSUE TITLE
[1.20] Crash when using Soul fire'd Mod

### ISSUE THREAD

**Issue by Talan67** [IzzelAliz/Arclight#1050]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.0-SNAPSHOT-4ddc3aa

### OS & Java versions

java version "17.0.1" 2021-10-19 LTS

### Plugins and Mods

```raw
Soul fire'd
```

### Description

The Server should start up as normal and not Crash.

### Step to reproduce

1. Install Soul fire'd

2. Crash

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/12134191/latest.log)

**Comment by IzzelAliz** [comment]
Fixed in c33e775a.
