### ISSUE TITLE
failing to build gradle 

### ISSUE THREAD

**Issue by Paradis4432** [IzzelAliz/Arclight#1051]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.16 https://github.com/IzzelAliz/Arclight/tree/1.16

### OS & Java versions

Win 64

### Plugins and Mods

```raw
none
```

### Description

failing to build gradle 
https://paste.md-5.net/icejobofap.shell

### Step to reproduce
download everything acording to guide 

### Logs
https://paste.md-5.net/ewuqexicul.shell

**Comment by Shmeeb** [comment]
Also getting this same error

**Comment by IzzelAliz** [comment]
Use gradlew instead of gradle when building, this will use corrent gradle version.
