### ISSUE TITLE
[1.18.2] Epicfight EnderDragon spawn out of bounds 

### ISSUE THREAD

**Issue by Shybella** [IzzelAliz/Arclight#1059]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2 - 1.0.8

### OS & Java versions

Windows Server 2022

### Plugins and Mods

```raw
- Dawncraft modpack (latest)
```
### Description

When going to the end for the first time, ender dragon spawn event causes a index out of bounds crash.

### Step to reproduce

1. Install Dawncraft Modpack
2. Teleport to the end

### Logs

Log: https://pastebin.com/raw/XvqH0USk

https://github.com/Yesssssman/epicfightmod/tree/1.18.2/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/dawn-craft

**Comment by IzzelAliz** [comment]
Fixed in [473aa47](https://github.com/IzzelAliz/Arclight/commit/473aa47edbb063aaebb26f32b0879a459084c0e6).

**Comment by Shybella** [comment]
confirmed solved
