### ISSUE TITLE
[1.20.1,Trails] Corrosive Sculk Crash on Start up

### ISSUE THREAD

**Issue by Talan67** [IzzelAliz/Arclight#1060]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.0

### OS & Java versions

java version "17.0.1" 2021-10-19 LTS

### Plugins and Mods

```raw
corrosivesculk-1.20.1-1.0
```

### Description

The server should not crash on start up, I reported the issue to the mod author but they said that It has nothing to do with their mod and may just be arclight having weird errors.

### Step to reproduce

1. Install corrosivesculk-1.20.1-1.0

2. Crash on Start up

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/12253542/latest.log)

**Comment by IzzelAliz** [comment]
Is this truely "unable to reproduce in Forge"? I see no reason this is on Arclight side.

**Comment by Talan67** [comment]
Was not an Arclight Issue and has been resolved, sorry for causing stress.
