### ISSUE TITLE
Memory leak in ChunkManager mixin

### ISSUE THREAD

**Issue by Paradis4432** [IzzelAliz/Arclight#1061]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.16

### OS & Java versions

openjdk version "11.0.16.1" 2022-08-12 OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)

### Plugins and Mods

```raw
https://paste.md-5.net/aguzogehus.css
```

### Description

seems like chunk manager is taking too much space, with just 90 players online, this is from MAT:

5 instances of «net.minecraft.world.server.ChunkManager», loaded by «cpw.mods.modlauncher.TransformingClassLoader @ 0x2434b0050» occupy 686,032,640 (14.97%) bytes. 

Biggest instances:
•net.minecraft.world.server.ChunkManager @ 0x275a08890 - 307,828,104 (6.72%) bytes. 
•net.minecraft.world.server.ChunkManager @ 0x29a2ecc28 - 184,622,336 (4.03%) bytes. 
•net.minecraft.world.server.ChunkManager @ 0x284f1d638 - 69,917,704 (1.53%) bytes. 
•net.minecraft.world.server.ChunkManager @ 0x292c73f90 - 64,507,432 (1.41%) bytes. 
•net.minecraft.world.server.ChunkManager @ 0x28b1feb30 - 59,157,064 (1.29%) bytes. 

These instances are referenced from one instance of «net.minecraft.server.dedicated.DedicatedServer», loaded by «cpw.mods.modlauncher.TransformingClassLoader @ 0x2434b0050», which occupies 2,209,184 (0.05%) bytes.

Keywords
net.minecraft.world.server.ChunkManager
cpw.mods.modlauncher.TransformingClassLoader @ 0x2434b0050
net.minecraft.server.dedicated.DedicatedServer

![image](https://github.com/IzzelAliz/Arclight/assets/49301263/87a59ac1-b812-42d2-b2f1-e8e667a96e60)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/9fb53833-4cdd-49ba-9c5c-f5e4b0f05a4e)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/6debaa79-3323-4689-8a1d-2de622f0315c)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/ef67dfb8-09fe-4eea-b3b2-2d9cdf2950e9)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/b4400e8d-2239-4e7f-8776-6b7bffe39923)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/6dffda51-4840-4ad4-9f54-fe7f33f97803)
server console handler paste: https://paste.md-5.net/yorohikosu.sql

[latestRay.txt](https://github.com/IzzelAliz/Arclight/files/12255376/latestRay.txt)

### Step to reproduce

it seems like normal players in the wild just cause this leak, cant reproduce in local host

**Comment by IzzelAliz** [comment]
What if, a normal server having 5 loaded world and can take that much of ram, is not called a leak?
