### ISSUE TITLE
Memory leak in ChunkManager mixin

### ISSUE THREAD

**Issue by Paradis4432** [IzzelAliz/Arclight#1062]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.16

### OS & Java versions

openjdk version "11.0.16.1" 2022-08-12 OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)

### Plugins and Mods

```raw
https://paste.md-5.net/aguzogehus.css
```

### **random chunks are force loaded, making the server accumulate instance of the following over time even when the same or less players are online, the server runs fine with 90 players and over time it starts to decay until it crashes:**

long[ ]
byte[ ]
hashmap$ node
com.pixelmonmod.pixelmon.battles.attacks.Attack
hashmap
object[ ]
hashmap$ node[ ]
com.pixelmonmod.pixelmon.battles.controller.participants.PixelmonWrapper
arraylist
int[]
com.pixelmonmod.pixelmon.api.pokemon.Pokemon
string
biome[]
LongOpenHashSet
LinkedHashMap$ Entry
com.pixelmonmod.pixelmon.api.pokemon.stats.BattleStats
ca.spottedleaf.starlight.common.light.SWMRNibbleArray
net.minecraft.pathfinding.PathPoint []
java.util.HashSet
com.pixelmonmod.pixelmon.api.pokemon.stats.BonusStats
com.pixelmonmod.pixelmon.api.pokemon.stats.IVStore
com.pixelmonmod.pixelmon.api.pokemon.stats.PermanentStats

**there are 9 worlds loaded, not 5**

![Pasted image 20230803153528](https://github.com/IzzelAliz/Arclight/assets/49301263/99d5211d-66c9-4044-a123-d5581195efef)

seems like chunk manager is taking too much space, with just 90 players online, this is from MAT:

5 instances of «net.minecraft.world.server.ChunkManager», loaded by «cpw.mods.modlauncher.TransformingClassLoader @ 0x2434b0050» occupy 686,032,640 (14.97%) bytes.

Biggest instances:
•net.minecraft.world.server.ChunkManager @ 0x275a08890 - 307,828,104 (6.72%) bytes.
•net.minecraft.world.server.ChunkManager @ 0x29a2ecc28 - 184,622,336 (4.03%) bytes.
•net.minecraft.world.server.ChunkManager @ 0x284f1d638 - 69,917,704 (1.53%) bytes.
•net.minecraft.world.server.ChunkManager @ 0x292c73f90 - 64,507,432 (1.41%) bytes.
•net.minecraft.world.server.ChunkManager @ 0x28b1feb30 - 59,157,064 (1.29%) bytes.

These instances are referenced from one instance of «net.minecraft.server.dedicated.DedicatedServer», loaded by «cpw.mods.modlauncher.TransformingClassLoader @ 0x2434b0050», which occupies 2,209,184 (0.05%) bytes.

Keywords
net.minecraft.world.server.ChunkManager
cpw.mods.modlauncher.TransformingClassLoader @ 0x2434b0050
net.minecraft.server.dedicated.DedicatedServer

![image](https://github.com/IzzelAliz/Arclight/assets/49301263/7187dba0-1206-4afc-9862-1eef0e087630)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/55fccaad-0e03-45b1-bdda-a6900d228c68)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/d1bc4871-9bdf-4a1e-9848-8f0c3b1d2724)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/0b96221a-cf59-4341-9533-9e5134cd762b)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/2e5aeffa-22f1-4f93-b215-380b71b8b821)
![image](https://github.com/IzzelAliz/Arclight/assets/49301263/3a7e5fb5-c94f-4007-a5e2-5a177277bdd8)

server console handler paste: https://paste.md-5.net/yorohikosu.sql

### Step to reproduce

it seems like normal players in the wild just cause this leak, cant reproduce in local host

**Comment by Shybella** [comment]
I don't see a memory leak here

See if this resolves your problems: https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading

**Comment by Paradis4432** [comment]
another thing i forgot to mention is that if we dont delete all chunks.dat and all data folder the server lags really bad after restart, its like it carries the leak over, looking at the server itself it seems like it has forced chunks 
![Pasted image 20230803153528](https://github.com/IzzelAliz/Arclight/assets/49301263/b53821d2-8d8b-4bbb-973f-1502e8ed946a)

**Comment by IzzelAliz** [comment]
The presence of big object instance is not a memory leak. You are using random words referring memory use is high. 90 players in 9 worlds loaded in ONE minecraft instance is good enough to me.
