### ISSUE TITLE
WorldBorder不显示

### ISSUE THREAD

**Issue by 3186418613** [IzzelAliz/Arclight#1064]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.16.5-1.0.25-SNAPSHOT

### Java 版本 | 操作系统

系统:Windows11 Java:openjdk version "17.0.8" 2023-07-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

原版指令/worldborder set 10
不显示边界

### 复现步骤

输入指令/worldborder set 10

### 报错信息

无

**Comment by IzzelAliz** [comment]
1.16.5 不再支持
