### ISSUE TITLE
[Bug] FAWE Compatibility 1.20.1

### ISSUE THREAD

**Issue by iPanic-Dev** [IzzelAliz/Arclight#1066]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.0

### OS & Java versions

Ubuntu 22.0.4 / Java 17.0.8

### Plugins and Mods

```raw
minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
 mods_folder extendedslabs-1.20.1-3.0.1.jar : extendedslabs (3.0.1) - 1
 mods_folder dynview-1.20.1-3.9.jar : dynview (2.3) - 1
 mods_folder Dynmap-3.6-forge-1.20.jar : dynmap (3.6-899) - 1
 mods_folder connectivity-1.20.1-4.4.jar : connectivity (1.20.1-4.4) - 1
 mods_folder spark-1.10.42-forge.jar : spark (1.10.42) - 1
 minecraft forge-1.20.1-47.1.1-universal.jar : forge (47.1.1) - 1
 mods_folder DynmapBlockScan-3.6-beta-1-forge-1.20.jar : dynmapblockscan (3.6-beta-1-250) - 1
 mods_folder starlight-1.1.2+forge.1cda73c.jar : starlight (1.1.2+forge.1cda73c) - 1
 arclight arclight-1.20.1-1.0.0-053d747.jar : arclight (1.20.1-1.0.0-053d747) - 1
--
LuckPerms, FastAsyncWorldEdit (WorldEdit), Essentials, PlaceholderAPI, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, GSit, ProtocolLib, DiscordSRV, BKCommonLib, CoreProtect, GriefDefender
```

### Description

Running any commands with FAWE (I did a //pos1 and //pos2 for this) spams the console with errors, and while FAWE reports to be fine in chat, no operations are completed.

### Step to reproduce

1. Setup Arclight 1.20.1
2. Install latest FAWE jar
3. Attempt to do an edit

### Logs

https://pastebin.com/AzfEYnD7

**Comment by IzzelAliz** [comment]
Seems FAWE is going Paper only which Arclight is not supported yet.
