### ISSUE TITLE
[1.18.2] Arclight - Bukkit and Forge

### ISSUE THREAD

**Issue by slavarer** [IzzelAliz/Arclight#1067]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.8-e80a33d2

### OS & Java versions

Debian11 x64 Java: openjdk version "17.0.7"

### Plugins and Mods

```raw
Plugins: Towny, TownyChat
Mod: TerraFirmaCraft
```

### Description

See, in TerraFirmaCraft, there's alcohol that, once consumed, is supposed to change messages from players, like "Hello world!" to "Hlle wrld!" or something like that.
So, the problem is that Arclight puts bukkit event before forge, and the Townychat chat format disappears when alcohol is consumed - because the Terrafirmacraft event comes last.
Is it possible to fix this in the near future?

**Comment by IzzelAliz** [comment]
1.18.2 is no longer supported.
