### ISSUE TITLE
arclight-1.19.4-1.0.5多世界插件MV无法生成世界

### ISSUE THREAD

**Issue by HaoNan0618** [IzzelAliz/Arclight#1068]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.4-1.0.5-857c13d6

### Java 版本 | 操作系统

"17.0.7" 2023-04-18 LTS | Windows10

### 相关 Mod/插件 的名称及版本

```raw
Multiverse-Core-4.3.1.jar
```

### 错误描述

使用最新版本arclight-forge-1.19.4-1.0.5，在使用多世界/mv create出现错误
在其他issues发现1.20版本相似问题，但没有在网上其他地方找到有关此版本问题

使用导入世界命令正常
重新安装服务端只添加Multiverse-Core依然有此问题

### 复现步骤

/mv create xxx normal

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/12314928/latest.log)

**Comment by IzzelAliz** [comment]
1.19.4 不再支持
