### ISSUE TITLE
[1.18.2]Index out of bounds coppergolem

### ISSUE THREAD

**Issue by Shybella** [IzzelAliz/Arclight#1069]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2 - 1.0.9

### OS & Java versions

Windows Server 2022

### Plugins and Mods

```raw
Dawncraft
```

### Description

Crash with copper golems

### Step to reproduce

1. Install Dawncraft + Arclight
2. Spawn a couple copper golems.

### Logs

https://pastebin.com/raw/ekxHKB49

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/dawn-craft

**Comment by Shybella** [comment]
https://pastebin.com/raw/TpfRg1k3

**Comment by IzzelAliz** [comment]
1.18.2 is no longer supported.
