### ISSUE TITLE
MV import and cleanroom dont work

### ISSUE THREAD

**Issue by Maar10tech** [IzzelAliz/Arclight#107]
### I am running

* **Arclight** [VERSION] 

* **This is the latest development version** [Y]

* **Java** [1.8] 

* **Operating System** [DIFFERENT]

* **Plugins** 
mv, cleanroomgenerator

* **Mods** 
* tested also without

### Description

I have a problem with MV core: when I try to create a CleanroomGenerator world it creates a classic world and when I try to import worlds like Skyblock they are empty.
I tried the steps on a normal spigot server and it works fine, so I think it has to do with the forge generator (because normally in spigot the standard worlds are world/world_nether/world_the_end, and in arclight it's like forge with word and subfolders dim1/dim-1)
Probably that's also why the server stucks on preparing other worlds when keepsSpawnInMemory is set to true.

**Reproducible in Spigot** [N]

### Logs

[ERROR LOG]

ArclightLog:https://pastebin.com/9YED2psR
normalSpigot:https://pastebin.com/5asA1jFx

**Comment by Maar10tech** [comment]
A few test showed that the worlds seeds are correct and the maps are imported like they were created, but all things that were built previously are gone. So a created map based on a flat world is then a flat world without anything...

**Comment by Maar10tech** [comment]
Problem was that the import map creates subfolder 
ARCLIGHT minecraft\oWorlds\spawn\dimensions\minecraft\oworlds\spawn\region
instead of using existend region files in:
ARCLIGHT minecraft\oWorlds\spawn\region

So I copy them manually to fix it and that worked great.  So import such maps is also a workaround for creating empty worlds.

It's not quiet fixed and needs a lot manually changes, but you can get it to work with a workaround. 

Would be nice to make that easier in future versions.

Great work!!

**Comment by IzzelAliz** [comment]
Please have a test with latest dev version
