### ISSUE TITLE
Mixin failed to apply [1.20.1]

### ISSUE THREAD

**Issue by Xplodin** [IzzelAliz/Arclight#1076]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.20.1-1.0.1-6562f32

### OS & Java versions

ubuntu 18.04 java 17

### Plugins and Mods

```raw
atm9 .54
```

### Description

crashes on boot

### Step to reproduce

install atm9
remove clientside mods: colorhearts, legendarytooltips, oculus, rubidium+addons

change arc forge to .1.3

sorry to keep this short, but its all accurate

### Logs

https://gist.github.com/Xplodin/9bb62e14ef48019a207805383078d270

**Comment by znowfox** [comment]
yeah but i think you should remove modernfix above all else.

**Comment by Xplodin** [comment]
log without modernfix active:
https://gist.github.com/Xplodin/3213be625d5a04a5a2782a421ab61f18

**Comment by znowfox** [comment]
and now throw away apotheosis, win !
ehe.

**Comment by IzzelAliz** [comment]
Latest ATM9 can run with latest Arclight.
