### ISSUE TITLE
Arclight breaks mapping

### ISSUE THREAD

**Issue by xknat** [IzzelAliz/Arclight#1077]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.19.2-1.0.1-055c6cd

### OS & Java versions

17

### Plugins and Mods

```raw
SkinsRestorer v15
```

### Description

SkinsRestorer is not able to use [Arclight](https://github.com/IzzelAliz/Arclight) mappings 
Did you guys break mappings?
Will you be able to fix this in order for us (SkinsRestorer) to support Archlight?
Thanks

### Step to reproduce

1. Install SkinsRestorer on Archlight

**Comment by xknat** [comment]
![image](https://github.com/IzzelAliz/Arclight/assets/10220139/bd0d4b82-de37-461b-9483-39df8e663017)

**Comment by IzzelAliz** [comment]
I believe there's something wrong with your mapping. Maybe you should do seperate remap on 1.19 and 1.19.2.

![图片](https://github.com/IzzelAliz/Arclight/assets/21029868/5244435c-92bb-4d92-a791-fdd7902906bd)

**Comment by xknat** [comment]
> I believe there's something wrong with your mapping. Maybe you should do seperate remap on 1.19 and 1.19.2.
> 
> ![图片](https://user-images.githubusercontent.com/21029868/262047943-5244435c-92bb-4d92-a791-fdd7902906bd.png)

We do: https://github.com/SkinsRestorer/SkinsRestorerX/blob/4c64fbd6c4ab5edb72f8f2e47214bfe188d9a9b3/mappings/mc-1-19/src/main/java/net/skinsrestorer/mappings/mapping1_19/Mapping1_19.java#L113

**Comment by IzzelAliz** [comment]
> > I believe there's something wrong with your mapping. Maybe you should do seperate remap on 1.19 and 1.19.2.
> > ![图片](https://user-images.githubusercontent.com/21029868/262047943-5244435c-92bb-4d92-a791-fdd7902906bd.png)
> 
> We do: https://github.com/SkinsRestorer/SkinsRestorerX/blob/4c64fbd6c4ab5edb72f8f2e47214bfe188d9a9b3/mappings/mc-1-19/src/main/java/net/skinsrestorer/mappings/mapping1_19/Mapping1_19.java#L113

https://github.com/SkinsRestorer/SkinsRestorerX/blob/4c64fbd6c4ab5edb72f8f2e47214bfe188d9a9b3/mappings/mc-1-19/build.gradle.kts#L3C22-L3C26

No you don't.

**Comment by PalanKa8** [comment]
Arclight is Spigot?

**Comment by xknat** [comment]
Can be closed, fixed by https://github.com/SkinsRestorer/SkinsRestorerX/commit/c86df1e23e63b87f137e2210a2f85bf642b81dfb
