### ISSUE TITLE
1.20.1 Residence插件打开GUI出现错误

### ISSUE THREAD

**Issue by HaoNan0618** [IzzelAliz/Arclight#1084]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.0-053d747

### Java 版本 | 操作系统

"17.0.7" 2023-04-18 LTS | Windows10

### 相关 Mod/插件 的名称及版本

```raw
CMILib1.4.0.1.jar
Residence5.1.2.0.jar
```

### 错误描述

我已经多次升级或回退插件版本，均无法解决问题

创建领地后，打开领地GUI界面，控制台会出现错误，使用GUI调整领地内权限，会出现相同错误
错误似乎来自CMILib提供的GUI功能？

### 复现步骤

/res set

### 报错信息
https://paste.fastmirror.net/?e85682ea0f09ec51#2qhusHGVBRSHSdANQxssKpZK7D7h1gDnaqsoj9xUQHDF

https://paste.ubuntu.com/p/jfWRqM8y44/

[latest.log](https://github.com/IzzelAliz/Arclight/files/12467764/latest.log)

**Comment by IzzelAliz** [comment]
无法复现，我用的当前最新的 residence，你可以更新试试看
