### ISSUE TITLE
Arclight服务端1.18.2  forge版本太低的问题

### ISSUE THREAD

**Issue by trgh311** [IzzelAliz/Arclight#1085]
......我在安装服务器的mod时发现开发者在Arclight的forge版本太低
没法正常安装启动
我想您是否可以更新一下Arclight1.18.2的forge版本以解决这个问题
【ERROR]: Missing mandatory dependencies: forge

**Comment by Illusion2-1** [comment]
1.0.9的release好像已经到40.2.10了吧？
c743dbdb58b6067130a5f2ff13b8abbcc8bf7888
