### ISSUE TITLE
[1.20.1] TAB plugin incompatible

### ISSUE THREAD

**Issue by GsTio86** [IzzelAliz/Arclight#1087]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Arclight-forge-1.20.1-1.0.1-SNAPSHOT

### OS & Java versions

Windows11   Java 17.0.6

### Plugins and Mods

```raw
Plugins (45): LuckPerms, VoidGen, PacketWhitelistNbt, PlaceholderAPI, CMILib, HuskSync, ConsoleSpamFix, LoneLibs, ProtocolLib, DeluxeTags, ItemsAdderBackup, OreRegenerator, TAB, Vault, DecentHolograms, CinematicStudio, PlayerPoints, Multiverse-Core, TradeMe, FastAsyncWorldEdit (WorldEdit), DiscordSRV, ShowItem, GlobalMarketPlus, fake-block, WorldGuard, ShopGUIPlus, ShopGUIPlus-SellGUI, Denizen, ChatControlRed, GriefDefender, GDHooks, BetonQuest, CMI, PixelmonEconomyBridge, Citizens, Shopkeepers, CMIEInjector, GTExtras, BetonMons, ItemsAdder, BetonQuestItemsAdder, DeluxeMenus, AdvancedCrates, SCore, ExecutableItems


Mod List:
• minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
• mods_folder BattleLogScraper-Forge-1.5.0-1.20.1.jar : battlelogscraper (1.5.0) - 1
• mods_folder netherportalfix-forge-1.20-13.0.0.jar : netherportalfix (13.0.0) - 1
• mods_folder limitedchunks-1.20.1-3.8.jar : limitedchunks (1.8) - 1
• mods_folder ferritecore-6.0.0-forge.jar : ferritecore (6.0.0) - 1
• mods_folder cupboard-1.20.1-1.8.jar : cupboard (1.20.1-1.8) - 1
• mods_folder balm-forge-1.20-7.0.7.jar : balm (7.0.7) - 1
• JarInJar Client Reset Packet-0.0.6.jar : clientresetpacket (0.0.6) - 1
• arclight arclight-1.20.1-1.0.1-SNAPSHOT-4aa8d3e5.jar : arclight (1.20.1-1.0.1-SNAPSHOT-4aa8d3e5) - 1
• mods_folder nbtedit-1.20.1-4.4.1-release-forge.jar : nbtedit (1.20.1-4.4.1-release) - 1
• minecraft forge-1.20.1-47.1.44-universal.jar : forge (47.1.44) - 1
• mods_folder PokeRemoval-Forge-2.1.0.jar : pokeremoval (2.1.0) - 1
• mods_folder deuf-1.20.1-1.3.jar : deuf (1.20.1-1.3) - 1
• mods_folder Pixelmon-1.20.1-9.2.1-server.jar : pixelmon (9.2.1) - 2
```

### Description

裝了 [TAB.v4.0.3](https://github.com/NEZNAMY/TAB/releases/) 沒辦法正確載入
之前在 1.16.5 的 Arclight上可以正常運作，換成 1.20.1的版本就沒法了

### Step to reproduce

https://github.com/NEZNAMY/TAB

### Logs

https://pastebin.com/Yi1yPxEL

**Comment by DonorKrovi** [comment]
try delete pixelmonmod and start server

**Comment by GsTio86** [comment]
> try delete pixelmonmod and start server

It still doesn't work, I even removed all mods and plug-ins
The developer of TAB is saying that this is a mapping issue with Arclight

**Comment by GsTio86** [comment]
Add error message
https://pastebin.com/raw/fEAjs2sx
![image](https://github.com/IzzelAliz/Arclight/assets/74390539/f26113c4-12f9-4520-b142-b0fbd15b66e8)

**Comment by DonorKrovi** [comment]
The plugin TAB is trying to access a method in the **net.minecraft.network.syncher.DataWatcher** class
It expects this class to have only one method with a return type of void and parameters of type **net.minecraft.network.syncher.EntityDataAccessor**
However, it found two methods in the class, which doesn't match its expectations
