### ISSUE TITLE
[Update] Forge 47.1.46

### ISSUE THREAD

**Issue by TheRealM18** [IzzelAliz/Arclight#1096]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

trials-1.0.1

### OS & Java versions

17.0.8

### Plugins and Mods

```raw
This is so you can run Pixelmon Reforged
```

### Description

This is needed for current version of Pixelmon Reforged

### Step to reproduce

1. Install Pixelmon Reforged... Crash

**Comment by Ap4uuk** [comment]
@TheRealM18 
As you installed forge 47.1.46 on archlight 1.20.1, it refuses to launch for me if I replace Forge with eurosia higher than 47.1.19.?

**Comment by IzzelAliz** [comment]
Use latest dev build
