### ISSUE TITLE
水桶与熔岩桶不能倒出液体

### ISSUE THREAD

**Issue by anime801** [IzzelAliz/Arclight#110]
我正在运行

 Arclight** [版本] arclight-forge-1.15-1.0.16-SNAPSHOT 
你确认这是最新版吗** [是]
 
* **Java** [版本] 
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
* **操作系统**
windows 7  64

* **插件列表** 

没有安装插件
没有安装模组
纯净的arclight端

错误描述
我不敢妄下判断，只是想解决我现在遭遇的问题。
开服后   本地测试 安装了forge31.2.47 的纯净客户端
进入游戏后 无法将水桶里的水  熔岩桶里的岩浆  倒于地面  树木草皮 都不行  任何实体的方块
我不清楚这个是因为我的问题引起，还是服务端的问题造成的。

更新问题描述： 我使用了正版纯洁的客户端   在安装forge31.2.47 与无forge下均出现此问题。
使用paper-1.15.2-391  正版客户端和盗版端均能正常使用水桶与熔岩桶

然后我把海螺端的版本换成了 arclight-forge-1.15-1.0.15   水桶和熔岩正常生效了。

70%的可能性问题是出在arclight-forge-1.15-1.0.16-SNAPSHOT 上
***********************************************************************************
我以为可以暂时性使用arclight-forge-1.15-1.0.15版本解决我的问题的时候…… 
重新安装好了模组和插件的服务端后台又出现大部分插件无法读取的错误，1.0.15的老毛病……如果你还记得，我在群里也提过。

现在看来我只能等待新的服务端版本出来了。

下面贴出 log  和 debug文件的地址

**log: [https://paste.ubuntu.com/p/PVBgt6mKXG/](url)**
**debug:  [https://paste.ubuntu.com/p/gQ77SXH3gt/](url)**

希望对解决问题有所帮助～  感谢！

**Comment by yonghenglunhui** [comment]
诶，我刚刚遇到这问题了，刚好在群里看到兄弟提了一手。
补充一下我发现的情况，可以对着实体放置下来，比如说可以对着一头猪放置一桶水，但放下来的水不会流动。无报错信息。

**Comment by anime801** [comment]
……放置在生物身上 只是显示bug  根本没有放出水来……  你把倒空的桶扔到地上  他就又是装水或熔岩的桶了

yonghenglunhui <notifications@github.com> 于2021年1月1日周五 下午10:00写道：
