### ISSUE TITLE
[1.20.1] Citizens NPC 沒立刻顯示

### ISSUE THREAD

**Issue by GsTio86** [IzzelAliz/Arclight#1100]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.1-c3fc1d3

### Java 版本 | 操作系统

Windows11  Java 17.0.6

### 相关 Mod/插件 的名称及版本

```raw
Plugins (3): ProtocolLib , Citizens, Denizen

Mod List:
• minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
• minecraft forge-1.20.1-47.1.1-universal.jar : forge (47.1.1) - 1
• arclight arclight-1.20.1-1.0.1-c3fc1d3.jar : arclight (1.20.1-1.0.1-c3fc1d3) - 1
```

### 错误描述

我用Citizens創建了一個NPC，但它沒有立即出現。 我需要再次登入伺服器才能出現。
如果是已經建立的NPC，只有在附近登入才會顯示。 如果距離太遠，則不會顯示。
有時候登入NPC也不會顯示，還要再一次重登

安裝插件:
[ProtocolLib 5.1.0#668](https://ci.dmulloy2.net/job/ProtocolLib/668/) 
[Citizens](https://ci.citizensnpcs.co/job/Citizens2/3205/)
[Denizen](https://ci.citizensnpcs.co/job/Denizen/1796/)

演示 : https://gyazo.com/891a78aa53376574ebc9b675b1d0e8b9

### 复现步骤

1. 執行 /npc create <name>  創建NPC
2. 如果沒有立即看到NPC代表你成功了

**Comment by zoe-may** [comment]
相同的问题，请问请问得到解决了吗？

**Comment by haha44444** [comment]
服务端版本arclight-1.20.1-1.0.5-1a8925b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) 
此bug仍可以复现

**Comment by zoe-may** [comment]
请问问题是解决了吗？
