### ISSUE TITLE
Immersive Armors Crash 1.18.2

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#1102]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.9-7a0a1946

### OS & Java versions

Java 17

### Plugins and Mods

```raw
https://www.curseforge.com/minecraft/mc-mods/immersive-armors
```

### Description

Server boots up then crashes, report listed below

### Step to reproduce

1. Install & run arclight
2. Install immersive amours mod
3. Run the Server

### Logs

https://pastebin.com/DB8CkBeu

**Comment by IzzelAliz** [comment]
1.18.2 is no longer supported.
