### ISSUE TITLE
[1.16.5] 使用WorldEdit插件时出现java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null报错

### ISSUE THREAD

**Issue by mFallW1nd** [IzzelAliz/Arclight#1103]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-SNAPSHOT-759a3fd5

### Java 版本 | 操作系统

Ubuntu Server 20.04 x64, Java: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)

### 相关 Mod/插件 的名称及版本

```raw
[21:47:08] [Server thread/INFO] [Console/]: Plugins (1): WorldEdit

[21:47:33] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List: 
• minecraft forge-1.16.5-36.2.26-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.2.26-universal.jar : forge (36.2.26) - 1
• arclight arclight-1.16.5-1.0.24.jar : arclight (1.16.5-1.0.24-SNAPSHOT-759a3fd5) - 1
```

### 错误描述

使用最新版WorldEdit插件时出现如下图所示报错（图片传不上来，改了后缀），无法正常使用。
[picture.png.md](https://github.com/IzzelAliz/Arclight/files/12693664/picture.png.md)

### 复现步骤

1.从https://dev.bukkit.org/projects/worldedit/files下载插件最新版WorldEdit 7.2.15 (1.16.5 - 1.20.1).jar
2.装好插件
3.进入服务器木斧选择两个点
4.输入//set dirt

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/12693630/latest.log)

**Comment by IzzelAliz** [comment]
安装 patcher
