### ISSUE TITLE
[1.18.2]安装CustomNPC后 熔炉熔炼产物无法堆叠

### ISSUE THREAD

**Issue by SpencerDoom** [IzzelAliz/Arclight#1106]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.9

### Java 版本 | 操作系统

windows10 x64,java:openjdk version "17.0.3"

### 相关 Mod/插件 的名称及版本

```raw
CustomNPCs-1.18.2.20230803snapshot
```

### 错误描述

使用 熔炉/高炉/烟熏炉熔炼物品时产物无法堆叠，而且原材料不会消耗，取出产物后可以继续熔炼物品，但依然无法堆叠
燃料正常消耗

### 复现步骤

1、安装CustomNPC

2、使用熔炉熔炼物品

3、等待第二个物品熔炼

3、取出产物后可以正常熔炼出新的产物

**Comment by jianglan1225** [comment]
我也发现了这个问题

**Comment by jianglan1225** [comment]
我也发现了这个问题

**Comment by Kuon8660** [comment]
在arclight-1.18.2-1.0.9-7a0a1946上，使用dungeons_gear-1.18.2-4.0.2-beta.jar也会导致这个问题

**Comment by Memory-Yzf** [comment]
无法堆叠不是服务端的问题是自定义NPC模组的问题，会添加tag{}标签，模组摆烂从1.16.5开始就有了一直不修

**Comment by IzzelAliz** [comment]
1.18.2 is no longer supported.
