### ISSUE TITLE
[1.18.2]神化Apotheosis铁砧附魔无法突破原版上限

### ISSUE THREAD

**Issue by Kuon8660** [IzzelAliz/Arclight#1108]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.9-7a0a1946

### Java 版本 | 操作系统

系统：Windows server 2019 java：openjdk version "17.0.8" 2023-07-18

### 相关 Mod/插件 的名称及版本

```raw
Plugins (0): 
Mod List: 
Apotheosis-1.18.2-5.8.1.jar
Placebo-1.18.2-6.6.7.jar
```

### 错误描述

在铁砧上对装备使用超过原版等级的附魔书会降级成原版最高等级
例：【钻石剑】+【锋利IX附魔书】=【钻石剑：锋利V】
正常应该是获得【钻石剑：锋利IX】

装备在附魔台上可以附魔超过原版等级的附魔，但在铁砧上不行，铁砧不会影响已有附魔，相同附魔影响
例：【钻石剑：锋利IX，耐久IV】+【耐久IV附魔书】=【钻石剑：锋利IX，耐久III】
正常应该获得【钻石剑：锋利IX，耐久V】

forge端和mohist端都可以正常使用，希望能修复一下这个bug

### 复现步骤

1. 安装神化及其前置
2. 启动服务端
3. 使用客户端进入游戏
4. 对武器在铁砧上使用锋利IX附魔书
5. 武器获得锋利V附魔

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/12724760/latest.log)

**Comment by IzzelAliz** [comment]
1.18.2 不再支持
