### ISSUE TITLE
Plugins disabled

### ISSUE THREAD

**Issue by DarkFlopp** [IzzelAliz/Arclight#1110]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.16.5

### OS & Java versions

idk

### Plugins and Mods

```raw
Plugins (4): 
SkinsRestorer
, 
WorldEdit
, 
Essentials
, 
LoginSecurity

Mod List: 
• minecraft forge-1.16.5-36.2.39-server.jar : minecraft (1.16.5) - 1
• mods_folder CustomNPCs-1.16.5.20220515.jar : customnpcs (1.16.5.20220515) - 1
• mods_folder sophisticatedbackpacks-1.16.5-3.15.20.755.jar : sophisticatedbackpacks (1.16.5-3.15.20.755) - 1
• mods_folder BiomesOPlenty-1.16.5-13.1.0.488-universal.jar : biomesoplenty (1.16.5-13.1.0.488) - 1
• mods_folder jei-1.16.5-7.8.0.1009.jar : jei (7.8.0.1009) - 1
• arclight arclight.jar : arclight (1.16.5-1.0.25-SNAPSHOT-695f9360) - 1
• mods_folder MegaMeteors+1.2.7+[1.16.5].jar : megameteors (1.2.7) - 1
• mods_folder Enderium 1.1.2.jar : enderium (1.1.2) - 1
• maven_libs forge-1.16.5-36.2.39-universal.jar : forge (36.2.39) - 1
• mods_folder appleskin-forge-mc1.16.x-2.4.0.jar : appleskin (2.4.0+mc1.16.4) - 1
• mods_folder Aquaculture-1.16.5-2.1.23.jar : aquaculture (1.16.5-2.1.23) - 1
• mods_folder dummmmmmy-1.16.5-1.3.3.jar : dummmmmmy (1.3.0) - 1
• mods_folder Xaeros_Minimap_23.8.0_Forge_1.16.5.jar : xaerominimap (23.8.0) - 1
• mods_folder corpse-1.16.5-1.0.6.jar : corpse (1.16.5-1.0.6) - 1
• mods_folder [1.16.5] SecurityCraft v1.9.7.1.jar : securitycraft (v1.9.7.1) - 1
```

### Description

When i add a plugin it puts its disabled, can anyone help? im on aternos

### Step to reproduce

i can use 3 plugins like skin restorer, world edit and Loginsecurity

### Logs

<html>
<body>

[28Sep2023 18:08:26.142] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
--
279 | org.bukkit.command.CommandException: Cannot execute command 'loginsecurity:login' in plugin LoginSecurity v3.2.1 - plugin is disabled.
280 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-695f9360]
281 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-695f9360]
282 | at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-695f9360]
283 | at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandlerMixin.java:2547) ~[?:?]
284 | at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandlerMixin.java:2397) ~[?:?]
285 | at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:36) ~[?:?]
286 | at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:9) ~[?:?]
287 | at net.minecraft.network.PacketThreadUtil.md579386$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
288 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
289 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
290 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
291 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
292 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
293 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
294 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]

295 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
296 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
297 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?]
298 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921) ~[?:?]
299 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
300 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]

</body>
</html>

### Server pack link (Optional)

No

**Comment by IzzelAliz** [comment]
1.16.5 is no longer supported.

**Comment by ghost** [comment]
Why? I have the same problem...
