### ISSUE TITLE
[1.18.2]crash mod immersive-armors

### ISSUE THREAD

**Issue by joaoespanhol** [IzzelAliz/Arclight#1112]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge
- [X] all plugins and mods are up to date

### Arclight version

arclight-forge-1.18.2-1.0.9.jar

### OS & Java versions

ubuntu 22.04

### Plugins and Mods

```raw
https://www.curseforge.com/minecraft/mc-mods/immersive-armors
```

### Description

start server is crasher

### Logs

https://mclo.gs/ybWg7SP

### Modpack link (Optional)

https://github.com/Renwyi/modpack/releases/download/HSMP/HSMP.zip

**Comment by IzzelAliz** [comment]
1.18.2 is no longer supported.
