### ISSUE TITLE
1.20.1 Can you please update all modpacks require minimum 47.1.47

### ISSUE THREAD

**Issue by xXjojojXx** [IzzelAliz/Arclight#1114]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

47.2.1

### OS & Java versions

Windows 11

### Plugins and Mods

```raw
Can you please update all modpacks require minimum 47.1.47
```

### Description

 n

### Step to reproduce

 n

### Logs

 n

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

**Comment by xXjojojXx** [comment]
and sorry if I have to open a ticket for this, but unfortunately it's not addressed in the discord. Many people have the problem that they can't update, as was the case in my case. As soon as I do that, the server just starts a continuous loop or the world is shown as damaged and it doesn't start

**Comment by Guaiguaijun** [comment]
You could down load Arclight supported with Forge 47.2.0 from **Action** section above
