### ISSUE TITLE
[1.20.1] （简单测试可复现）Trials f347f85 与better combat模组不兼容

### ISSUE THREAD

**Issue by ColdTearsYY** [IzzelAliz/Arclight#1115]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.2-SNAPSHOT-f347f85

### Java 版本 | 操作系统

系统：win10，java：graalvm-ee-java17-22.1.0

### 相关 Mod/插件 的名称及版本

```raw
没有插件【截图：https://article.biliimg.com/bfs/article/a4afbf733d0d5e9223e10a0c728a37a3227036471.png】
模组只有
bettercombat-forge-1.7.4+1.20.1
和它的两个前置模组：
cloth-config-11.1.106-forge
player-animation-lib-forge-1.0.2-rc1+1.20
```

### 错误描述

目测是mixin相关的错误导致无法启动

### 复现步骤

1.安装arclight和模组
2.开启服务器
3.报错

### 报错信息

https://paste.ubuntu.com/p/gr6Z7BY96R/

**Comment by HighPingInk** [comment]
遇见相同问题，目前版本的arclight似乎与最新的bettercombat不兼容
cloth前置其他模组运行良好，只有bettercombat出现报错导致开不了
