### ISSUE TITLE
Arclight crashes with certain mods.

### ISSUE THREAD

**Issue by HEofOttoman** [IzzelAliz/Arclight#1119]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.20.1 (1061 - 47.2.0)

### OS & Java versions

OS: Windows 11, Java 17

### Plugins and Mods

```raw
Mods folder:
architectury-9.1.12-forge.jar
bettercombat-forge-1.7.2+1.20.1.jar
bettervillage-forge-1.20.1-3.1.0.jar
cloth-config-11.1.106-forge.jar
cloth-config-12.0.109-forge.jar
cristellib-1.1.1-forge.jar
cristellib-1.1.3-forge.jar
ctov-3.3.2.jar
dungeons-and-taverns-v2.1.4.jar
DungeonsArise-1.20.1-2.1.56.1-beta.jar
explorify-v1.3.0-mc1.20u1.20.1.jar
immersive_armors-1.6.1+1.20.1-forge.jar
libraryferret-forge-1.20.1-4.0.0.jar
mob-captains-v2.1.2.jar (Datapack)
player-animation-lib-forge-1.0.2-rc1+1.20.jar
repurposed_structures-7.0.0+1.20-forge.jar
Rex's-AdditionalStructures-1.20.x-(v.4.1.2).jar
ShieldExpansion-1.20.1-1.1.6a.jar
simplyswords-forge-1.51.0-1.20.1.jar
simplyswords-forge-1.51.4-1.20.1.jar
Stellarity-v2-0e.jar (Datapack)
Towns-and-Towers-1.11-Fabric+Forge.jar
ultris-v5.6.9b.jar (Datapack)
vanilla-refresh-1.4.16h.jar (Datapack)
Datapacks : 
1. True ending
2. Spellbound weapons
```

### Description

What should happen : The server works with no issue
What did happen : The server crashes.

The server crashes when it starts. It doesn't say anything in the log that it crashed but it ends abruptly. I have tested this with only the 2 mods with mixin warnings and it works perfectly.

### Step to reproduce

1. Make a server on Aternos with the modlist.
2. Start the server.
3. See if it crashes.

### Logs

https://mclo.gs/pIGaAxm

**Comment by Ap4uuk** [comment]
@HEofOttoman 
You have duplicate mods of different versions. remove them and check operation

**Comment by IzzelAliz** [comment]
Why you are having same mods with different versions?

**Comment by HEofOttoman** [comment]
> Why you are having same mods with different versions?

huh
I guess i never noticed it. Thanks and i'll try again

**Comment by HEofOttoman** [comment]
new crashlog: https://mclo.gs/f9N6UgH
The issue persisted.
Modlist:
architectury-9.1.12-forge.jar
bettercombat-forge-1.7.2+1.20.1.jar
bettervillage-forge-1.20.1-3.1.0.jar
cloth-config-12.0.109-forge.jar
cristellib-1.1.3-forge.jar
ctov-3.3.2.jar
dungeons-and-taverns-v2.1.4.jar
DungeonsArise-1.20.1-2.1.56.1-beta.jar
explorify-v1.3.0-mc1.20u1.20.1.jar
immersive_armors-1.6.1+1.20.1-forge.jar
libraryferret-forge-1.20.1-4.0.0.jar
mob-captains-v2.1.2.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
repurposed_structures-7.0.0+1.20-forge.jar
Rex's-AdditionalStructures-1.20.x-(v.4.1.2).jar
ShieldExpansion-1.20.1-1.1.6a.jar
simplyswords-forge-1.51.4-1.20.1.jar
Stellarity-v2-0e.jar
Towns-and-Towers-1.11-Fabric+Forge.jar
ultris-v5.6.9b.jar
[vanilla-refresh-1.4.16h.jar](https://aternos.org/files/mods#)

**Comment by Wdits** [comment]
remove better combat and you will be fine

**Comment by HEofOttoman** [comment]
> remove better combat and you will be fine

hmmm. I am trying to migrate the world anyway because of this issue.
