### ISSUE TITLE
[1.18.2] CUSTOM NPCS - Error NBT and Stack

### ISSUE THREAD

**Issue by JavierLobosS** [IzzelAliz/Arclight#1120]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2-1.0.9

### OS & Java versions

windows10 x64,java:openjdk version "17.0.3"

### Plugins and Mods

```raw
CustomNpcs-1.18.2.20231009snapshot
```

### Description

there is an issue with NBT data, which makes it impossible for some items to stack. For instance, when I put a stack of iron in a furnace, it doesn't stack after smelting. You need to remove the iron to get it to smelt again. Moreover, when I take an iron ingot from creative mode, it doesn't stack with the ones that were previously smelted.

### Step to reproduce

1. Install CustomNPC.
2. Use the furnace to smelt items.
3. Wait for the second item to smelt.
4. After removing the product, you can smelt a new one normally.

### Server pack link (Optional)

https://cdn.discordapp.com/attachments/423946043395407882/1161038425047191633/CustomNPCs-1.18.2.20231009snapshot.jar?ex=654012cb&is=652d9dcb&hm=3177d69e08c295007400ee8d00f96a5a7f810280fe9a892e969f9cea83805c77&

**Comment by IzzelAliz** [comment]
1.18 is no longer supported.

**Comment by chocheger** [comment]
same problem in 1.19.2
