### ISSUE TITLE
Some minor issues 一些小问题

### ISSUE THREAD

**Issue by Sichongzou** [IzzelAliz/Arclight#1121]
Hello, I am new to using Arclight and I do not have much experience in server hosting.I am currently trying to use the arclight-forge-1.20.1-1.0.1 version.I have some questions about server operation.
First of all, I didn't find any automatic saving options in server.properties. The storage I know only stores once after I stop the server using the stop command.  If my server is shut down due to force majeure during the running process, will my data be lost directly?Do I need to load some plugins to help it?
Then, it's about dropped items.The servers I previously ran had some plugins to regularly clear dropped items.I don't know if Arclight will automatically do this for me, and if so, I would like to know how often it will do it.
Perhaps my questions are clearly documented in a certain document, but I have not found a link to the relevant document on Github.

您好，我初次使用 Arclight 而且我的开服经验不是非常充足。我正在尝试使用arclight-forge-1.20.1-1.0.1 版本。我对服务器运行方面有点疑问。
首先是 我没有在server.properties中找到任何自动保存的选项，我所知道的存储只会在我使用stop指令停止服务器后存储一次，如果我的服务器在运行过程中出于不可抗力关闭了，我的数据是否会直接丢失。我是不是需要加载一些插件来帮助它。
然后，是关于掉落物方面。我之前开的服务器都是有一些插件来定时清除掉落物。我不知道 Arclight 是否会自动帮我完成这部分工作，如果有，我想知道它的频率是多少。
也许我的这些问题在某个文档上有清楚的记载，但是我并没有在Github上找到相关的文档链接。

**Comment by IzzelAliz** [comment]
This game has builtin item despawn and auto saving.

https://minecraft.wiki/w/Item_(entity)#Despawning
https://minecraft.wiki/w/Commands/save
