### ISSUE TITLE
Forge Version Used

### ISSUE THREAD

**Issue by wop0911** [IzzelAliz/Arclight#1122]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

N/A yet

### OS & Java versions

Java 17

### Plugins and Mods

```raw
Pixelmon-1.20.2-9.2.4-universal
```

### Description

I am prepping for 1.20.2 migration, and I noticed that in your prep for 1.20.2, you are using Forge 48.0.4. Please note that many mods as well as the one we are using are currently using the latest. I just wanted to double-tap to see if this would cause any known issues if we attempt to change the Forge version as indicated through https://github.com/IzzelAliz/Arclight/wiki/FAQ. Or if there is any way to suggest that you have a build with the latest. Haven't played with this stuff very much, so just let me know.

**Comment by IzzelAliz** [comment]
Updated in latest build.
