### ISSUE TITLE
arclight 1.18.2  FastAsyncWorldEdit插件 与 ConquestReforge模组 兼容问题

### ISSUE THREAD

**Issue by shayubb777** [IzzelAliz/Arclight#1123]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.9

### Java 版本 | 操作系统

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
mod:ConquestReforge
https://legacy.curseforge.com/minecraft/mc-mods/conquest-reforged/files/all?filter-status=1&filter-game-version=2020709689%3A7498
plugin：FAWE
https://www.spigotmc.org/resources/fastasyncworldedit.13932/
```

### 错误描述

FAWE生成的方块不正确，并且每次生成的方块都有光影丢失的情况

### 复现步骤

安装ConquestReforge和FAWE
进入服务器 
木斧左键(第一点)右键(第二点)选两个点
//wea  ->   //set 1        
生成的方块都是错乱的
但是如果用worldedit则不会有这个问题

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/13063988/latest.log)

**Comment by IzzelAliz** [comment]
1.18 已经不再支持
