### ISSUE TITLE
Crash when player dies

### ISSUE THREAD

**Issue by FrauZj** [IzzelAliz/Arclight#1127]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [x] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.2

### OS & Java versions

windows 10; jdk-17

### Plugins and Mods

```raw
mods
alloyed-1.19.2-v1.5a
alloyedguns-1.1.0-1.19.2
cgm-forge-1.19.2-1.3.7
create-1.19.2-0.5.1.e
createbigcannons-forge-1.19.2-0.5.3-nightly-ef2a0d6
create-stuff-additions1.19.2_v2.0.4a
FarmersDelight-1.19.2-1.2.3
framework-forge-1.19.2-0.6.16
voicechat-forge-1.19.2-2.4.27
Steam_Rails-1.5.1+forge-mc1.19.2
plugins
AuthMe-5.6.0-beta2
Dynmap-3.7-beta-2-spigot
EssentialsX-2.21.0-dev+19-3eceec8
EssentialsXChat-2.21.0-dev+19-3eceec8
EssentialsXSpawn-2.21.0-dev+19-3eceec8
KillRewards-1.0.7
Konquest-1.1.0
LuckPerms-Bukkit-5.4.106
ProtocolLib
Vault
ServerBackup-2.9.7
SkinsRestorer
worldedit-bukkit-7.2.17
worldguard-bukkit-7.0.8-dist
```

### Description

If someone dies (sometimes) server crashes/kicks player out of the server

### Step to reproduce

1.Join
2.Die
3.Server crash

**Comment by FrauZj** [comment]
crash report 
[crash-2023-11-01_19.16.38-server.txt](https://github.com/IzzelAliz/Arclight/files/13230921/crash-2023-11-01_19.16.38-server.txt)

**Comment by IzzelAliz** [comment]
This is already fixed in latest dev build.
