### ISSUE TITLE
Bukkit 的 InventoryMoveItemEvent 在 Arclight-1.18.2-1.0.9 上不抛出

### ISSUE THREAD

**Issue by G-JLING** [IzzelAliz/Arclight#1131]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.9-7a0a194

### Java 版本 | 操作系统

系统: macOS Sonoma 14.0, java version "17.0.3.1" 2022-04-22 LTS

### 相关 Mod/插件 的名称及版本

```raw
一个我自己写的插件，仅用于监听 InventoryMoveItemEvent。其应该在该事件抛出时打印日志，但在 Arclight 上没有。
```

### 错误描述

一个我自己写的插件，仅用于监听 InventoryMoveItemEvent。其应该在该事件抛出时打印日志，但在 Arclight 上没有。

### 复现步骤

编写一个简单的插件，并加入相关监听代码，例如：

 @EventHandler
    public void onInventoryMoveItem(InventoryMoveItemEvent event) {
        InventoryHolder sourceHolder = event.getSource().getHolder();
        InventoryHolder destHolder = event.getDestination().getHolder();

        if (sourceHolder instanceof Hopper) {
            logHopperEvent("输入", (Hopper) sourceHolder, event);
        }

        if (destHolder instanceof Hopper) {
            logHopperEvent("输出", (Hopper) destHolder, event);
        }
    }

    private void logHopperEvent(String type, Hopper hopper, InventoryMoveItemEvent event) {
        String itemName = event.getItem().getType().name();
        String hopperLocation = hopper.getLocation().toString();
        Bukkit.getLogger().info("有一个漏斗正在 " + type + ": " + itemName + " 于世界 " + hopperLocation);
    }

放入插件文件夹，然后启动 Arclight。随意搭建一个漏斗传输结构，将任意物品丢入漏斗中，控制台无日志。

**Comment by IzzelAliz** [comment]
1.18 已经不再支持
