### ISSUE TITLE
[1.16.5] hasItemMeta() not working as intended

### ISSUE THREAD

**Issue by vaniron** [IzzelAliz/Arclight#1134]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.0.25

### OS & Java versions

Ubuntu 22.04.03, java 11

### Plugins and Mods

```raw
BanItem
```

### Description

hasItemMeta() (bukkit api) is not properly implemented and causes server to freeze

for example used in https://github.com/Andross96/BanItem/blob/master/BanItemPlugin/src/main/java/fr/andross/banitem/items/BannedItem.java line 57 causing server freeze

**Comment by IzzelAliz** [comment]
1.16.5 is no longer supported.
