### ISSUE TITLE
绿色图书的合成表功能失效   还有船没法放置在地上或水里  

### ISSUE THREAD

**Issue by anime801** [IzzelAliz/Arclight#114]
服务端版本 arclight-forge-1.15-1.0.16-SNAPSHOT
没有装插件
没有装模组
win7 64
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

问题描述：
合成表是空的，船没法放置……
补充一下  paper-1.15.2-391  空端开服测试   功能全部正常。
log 和 debug 地址

debug : https://paste.ubuntu.com/p/gKQGPy3s3C/
log: https://paste.ubuntu.com/p/kPS2ZyYKvM/

**Comment by IzzelAliz** [comment]
Duplicate #112
