### ISSUE TITLE
Possible false positive, don't let me download

### ISSUE THREAD

**Issue by thefrogline** [IzzelAliz/Arclight#1141]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.0.9

### OS & Java versions

java version 17 - windows 10

### Plugins and Mods

```raw
none
```

### Description

Hello, lately I've been getting a Trojan error when trying to download the forge arclight, both with windows defender (after its latest update) and bit defender (I used this to see the exact path), every time I try to do something, it is automatically deleted, I know I could set it as ignored, but I don't know if there is a way to fix it, assuming it is a false positive

### Step to reproduce

1.- install archlight 1.18.2-1.0.9 
2.- install server files
3.- auto detect virus and delete

### Logs

![image](https://github.com/IzzelAliz/Arclight/assets/76601496/36041cd8-654b-4d63-a53b-1dbc3ab1c0de)

**Comment by IzzelAliz** [comment]
We can't do nothing with your AV. You should probably report it false positive yourself.
