### ISSUE TITLE
[1.19.2] Mixin conflict with mod "Apotheosis"

### ISSUE THREAD

**Issue by mocksonline** [IzzelAliz/Arclight#1150]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.2-1.0.3-cfdf69de

### Java 版本 | 操作系统

OpenJDK 64-Bit Server VM Microsoft-32931 (build 17.0.3+7-LTS, mixed mode, sharing), running on Microsoft windows 22H2 (22621.2428)

### 相关 Mod/插件 的名称及版本

```raw
Placebo-1.19.2-7.3.4.jar
Patchouli-1.19.2-77.jar
Apotheosis-1.19.2-6.4.1.jar
```

### 错误描述

单独和mod "Apotheosis"运行无法启动服务端。
Mixin冲突。我查看了记录发现有过修补，但是仍然冲突。

### 复现步骤

1: 安装所示mods
2: 无启动项启动arclight入口程序
3: Mixin conflict

### 报错信息

https://pastebin.com/FnEkZRQJ
简要信息:
`[main/ERROR] [mixin/]: Critical injection failure: LVT in net/minecraft/world/entity/monster/Slime::m_142687_(Lnet/minecraft/world/entity/Entity$RemovalReason;)V has incompatible changes at opcode 244 in callback apotheosis.mixins.json:SlimeMixin->@Inject::apoth_markMovable(Lnet/minecraft/world/entity/Entity$RemovalReason;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ILnet/minecraft/network/chat/Component;ZFIIIFFLnet/minecraft/world/entity/monster/Slime;)V.
 Expected: [I, Lnet/minecraft/network/chat/Component;, Z, F, I, I, I, F, F, Lnet/minecraft/world/entity/monster/Slime;]
    Found: [I, Lnet/minecraft/network/chat/Component;, Z, F, I, I, Lorg/bukkit/event/entity/SlimeSplitEvent;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/world/entity/LivingEntity;]
Available: [I, Lnet/minecraft/network/chat/Component;, Z, F, I, I, Lorg/bukkit/event/entity/SlimeSplitEvent;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/world/entity/LivingEntity;]`

**Comment by z3nth10n** [comment]
Where can I download the build jar from this commit?
