### ISSUE TITLE
Cannot invoke [...] because "superClass" is null

### ISSUE THREAD

**Issue by Thspooks** [IzzelAliz/Arclight#1155]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.20.1 1.0.2 

### OS & Java versions

java version "1.8.0_333" Java(TM) SE Runtime Environment (build 1.8.0_333-b02) Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

### Plugins and Mods

```raw
https://pastebin.com/MLfY0eKb
(idk how to get servermodlist, so i give clientside modlist, ofc clientside mods such as embeddium and others is removed on server)
```

### Description

Wanted to update my server to 1.20.1 from 1.19.2, i revamped my modpack and decided to use Sinytra connector just for fun. I decided to keep all old configs of plugins so i dont have to remake everything. idk what else to say, i included modlist and logs so i think its all? but ill provide more info if i missed something 
https://pastebin.com/aiQKeR6N the crash itself

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/13649337/latest.log)

**Comment by Roshag** [comment]
Trials 1.0.2, same issue. With or without Connector. 
[latest.log](https://github.com/IzzelAliz/Arclight/files/13849668/latest.log)

**Comment by Roshag** [comment]
Farmer's Delight seems to be the reason. And that's not Arclight's issue - same error happens on Magma

**Comment by Thspooks** [comment]
Sadly its not farmers delight causing it for me. ive long deleted this mod, and its still crashing bc of "arclight$worldInit". I already swapped to a different hybrid anyway and it works flawlessly compared to arclight

**Comment by GelidaAvis** [comment]
What other hybrid are you using??

**Comment by Thspooks** [comment]
> What other hybrid are you using??

Magma and Mohist on 1.20.1. I ended up using mohist, because its suprisingly pretty compatible on 1.20.1.

**Comment by Thspooks** [comment]
when fixed version will be released?
