### ISSUE TITLE
SOMETIMES ITEMS CANT STACK, FURNANCE CANT STACK ITEMS

### ISSUE THREAD

**Issue by chocheger** [IzzelAliz/Arclight#1159]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.19.2-1.0.2

### OS & Java versions

java version 17.0.8 by Microsoft; OS Windows 10 arch amd64 version 10.0

### Plugins and Mods

```raw
Big list
```

### Description

Sometimes items cant stack
In furnace after smelting one item the second one can't stack but the fuel still consuming

**Comment by kongtou20070406** [comment]
Well, did you fix it?

**Comment by IzzelAliz** [comment]
Please test the dev builds and see if it is fixed.

**Comment by kongtou20070406** [comment]
> 请测试开发版本，看看它是否已修复。

Is there a fix for 1.18.2?
