### ISSUE TITLE
Error receiving packet 56 when teleporting

### ISSUE THREAD

**Issue by MehdiPG** [IzzelAliz/Arclight#1171]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.10-033f7507

### OS & Java versions

OS: Windows 11 x64 Java: Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)

### Plugins and Mods

```raw
Only immersive portals is related to this bug.
```

### Description

The problem is that when using any teleportation method (commands, mod items, etc...) with immersive portals mod installed, the server kicks the player with this error: Error receiving packet 56
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because "dimension" is null.

I reported this to immersive portals team and they sended me here.

I have tried removing all mods and plugins from the server and leaving only immersive portals, but the problem continues. I leave the error text [here](https://pastebin.com/raw/uDGUdxQz)

### Step to reproduce

1. Add immersive portals mod
2. Join game and use any teleport method

### Logs

https://mclo.gs/fKWGbEG

**Comment by IzzelAliz** [comment]
1.18.2 is no longer supported.
