### ISSUE TITLE
Exception in server tick loop with pixelmon

### ISSUE THREAD

**Issue by byrra** [IzzelAliz/Arclight#1172]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Net/1.0.1

### OS & Java versions

Debian11 Java17

### Plugins and Mods

```raw
Pixelmon Reforged 1.20.2 9.2.6
```

### Description

Server is running fine, after entering a battle with a pixelmon the server crashes with Exception in server tick loop 

### Step to reproduce

1. install Arclight
2. add Pixelmon mod
3. start server
4. enter a battle with the R button

### Logs

https://paste.ubuntu.com/p/DDmtNJTsYB/

**Comment by IzzelAliz** [comment]
This should report to pixelmon side I guess. commons-compress is not included in minecraft server.
