### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qq851411536** [IzzelAliz/Arclight#1173]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.2-730181a4

### Java 版本 | 操作系统

系统：Windows Server 2022 Datacenter 21H2，Java:openjdk version "18.0.1" 2022-04-19

### 相关 Mod/插件 的名称及版本

```raw
jei-1.20.1-forge-15.2.0.27
waystones-forge-1.20-14.1.3
Cobblemon-forge-1.4.1+1.20.1
Jade-1.20.1-forge-11.7.1
balm-forge-1.20.1-7.2.1
cobblemonintegrations-1.20.1-1.0.4
cobblemon-spawn-notification-1.4-forge-1.1.0
kotlinforforge-4.10.0-all
```

### 错误描述

开服后提示该报错

### 报错信息

![QQ图片20240103120000](https://github.com/IzzelAliz/Arclight/assets/28604766/5c369b64-e6ff-411e-b19f-7125324f9131)

**Comment by IzzelAliz** [comment]
自己二分报给对应mod作者
