### ISSUE TITLE
安装ItemPhysic后服务器无法正常启动

### ISSUE THREAD

**Issue by lajxw** [IzzelAliz/Arclight#119]
### 我正在运行

* **Arclight** [arclight-1.16.4-1.0.11-SNAPSHOT-093932b] 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** [11] 

* **操作系统** [windows10 20H2]

* **插件列表** 

无插件

* **Mod 列表** 

![image](https://user-images.githubusercontent.com/46254113/103901701-70599380-5134-11eb-84e2-73ea4c3f80ce.png)

### 错误描述

安装ItemPhysic后服务器无法正常启动

### 重现步骤

1. 安装 ItemPhysic及前置CreativeCore
2. 启动服务器后 崩溃

**可在 Forge 复现** [纯Forge可正常运行]

**可在 Spigot 复现** [无关]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/r9BBHTdTdR/

edit:ItemPhysic https://github.com/CreativeMD/ItemPhysic

**Comment by IzzelAliz** [comment]
已知问题，请阅FAQ
