### ISSUE TITLE
[1.18.2] Bug Error when getting up

### ISSUE THREAD

**Issue by MaxKuz67** [IzzelAliz/Arclight#1190]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Arclight-1.18-1.0.10

### OS & Java versions

17

### Plugins and Mods

```raw
Create
```

### Description

In Fashion Create you can build trains and put seats in them. When getting up from the seat, it teleports outside the boundaries of the train (to the very top) how to fix this? On a regular forge there is no this error

**Comment by IzzelAliz** [comment]
1.18.2 is no longer supported.
