### ISSUE TITLE
1.18.2与Clockwork不兼容

### ISSUE THREAD

**Issue by Misaka2298** [IzzelAliz/Arclight#1191]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.10-033f7507

### Java 版本 | 操作系统

系统：Windows11专业版64bit，Java:Zulu17.46.19-ca-jdk17.0.9-win_x64

### 相关 Mod/插件 的名称及版本

```raw
clockwork-forge-0.0.1-alpha350ee73315
```

### 错误描述

启动时报错Clockwork: Create x Valkyrien Skies (vs_clockwork) has failed to load correctly
在客户端（1.18.2，Forge40.2.14）可以正常启动

此mod可以让机械动力和瓦尔基里：天空两个mod互相兼容，做出载具飞机一类的东西，在国内知名度较高，具体可以在B站搜索“clockwork”或观看up@洛笙子夜喵的视频（因为知名度较高）

### 复现步骤

1.从下面的链接下载复现用压缩包（本来想放自己的alist站，结果DNS被腾讯ban了，换成对象存储了）
2.启动“启动！.bat”（压缩包内自带java，需要把bat里的java.exe路径重新换成你这边的绝对路径）
3.然后就崩溃力（悲

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/13965668/latest.log)

### 复现用压缩包下载链接(可选)

https://linshi-1309490855.cos.ap-nanjing.myqcloud.com/FDT_Minecraft_Arclight.zip

**Comment by Misaka2298** [comment]
latest.log打不开的话可以看这个
https://paste.fastmirror.net/?1af032a064cc06d2#8kFimZiRZ54Q5Ptq9fYhfJhgfvkhgRQUpMZD5g4C1P7z

**Comment by IzzelAliz** [comment]
1.18.2 不再支持
