### ISSUE TITLE
Please make a Arclight version with 47.2.18 Forge version

### ISSUE THREAD

**Issue by hgnhn** [IzzelAliz/Arclight#1192]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.2-730181a4

### OS & Java versions

Java 17

### Plugins and Mods

```raw
.
```

### Description

My modpack only supports 47.2.18 Forge version, i've tried changing forge version with the faq method but after i start the server the files reverted back. I've tried downloading the entire file to local and change it then upload it back. Same result

**Comment by IzzelAliz** [comment]
Try the latest.
