### ISSUE TITLE
[1.20.1] SoL: Valheim Edition, Can't Eat food

### ISSUE THREAD

**Issue by Talan67** [IzzelAliz/Arclight#1193]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.1

### OS & Java versions

java version "17.0.1" 2021-10-19 LTS

### Plugins and Mods

```raw
Spice of Life: Valheim Edition
Cloth Config
Architectury API
```

### Description

With the Mods listed installed on an Arclight server, I cannot eat food. This is because SoL: Valheim Editon changes the way the food system works. Typically loading into Singleplayer everything functions properly with no issues, only on an Arclight server there is a conflict with the mod in some way.

### Step to reproduce

1. Install mods listed on Client and Server
2. Join Server
3. Try to eat food
4. Nothing... (excluding golden apples, rotten flesh and the like)

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/13983348/latest.log)
[debug.log](https://github.com/IzzelAliz/Arclight/files/13983349/debug.log)

**Comment by mechanick229** [comment]
I can't eat the eternal steak made of mod artifacts
