### ISSUE TITLE
PlayerUseUnknownEntityEvent Paper Error

### ISSUE THREAD

**Issue by rafucuk** [IzzelAliz/Arclight#1197]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.3

### OS & Java versions

openjdk version "17.0.9" 2023-10-17 OS:Ubuntu

### Plugins and Mods

```raw
Modelengine 4
```

### Description

Modelengine 4 uses paper method called 
com.destroystokyo.paper.event.player.PlayerUseUnknownEntityEvent;

**Comment by rafucuk** [comment]
![image](https://github.com/IzzelAliz/Arclight/assets/33981808/c8abcc0f-0574-4574-8381-09117f11f744)

**Comment by rafucuk** [comment]
in 4.0.5 it is same, in modelengine discord they say they will maintain paper not spigot so any patch for this?

**Comment by 303404Hi** [comment]
I don't know whether you can see this reply, but I wrote a patch for this.
It has been tested on Arclight 1.20.1-1.0.6

[ModelEngineSpigotFix.zip](https://github.com/user-attachments/files/25182878/ModelEngineSpigotFix.zip)
