### ISSUE TITLE
1.0.3 won't even install

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#1200]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.0.3

### OS & Java versions

Java 17

### Plugins and Mods

```raw
Not relevant
```

### Description

Won't install

### Step to reproduce

Try to install 1.0.3 Arclight Trials

### Logs

https://paste.ee/p/YskT2

**Comment by IzzelAliz** [comment]
Try `echo '127.0.0.1 bmclapi2.bangbang93.com' | sudo tee -a /etc/hosts` if you have access to shell and rerun install.

**Comment by IzzelAliz** [comment]
Update to latest.
