### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by Shisuiicaro** [IzzelAliz/Arclight#1201]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-common-1.0.4-SNAPSHOT.jar

### OS & Java versions

Java 17

### Plugins and Mods

```raw
Zelthoriai smp modpack
no plugins
```

### Description

When a try to start the server, dosent start and give me this error: 
java -Xms128M -Xmx24576M -Dterminal.jline=false -Dterminal.ansi=true -jar arclight-common-1.0.4-SNAPSHOT.jar
no main manifest attribute, in arclight-common-1.0.4-SNAPSHOT.jar

**Comment by IzzelAliz** [comment]
You are launching with wrong file. Use arclight-forge-<version>.jar/
