### ISSUE TITLE
Mine and Slash Mod inconpatible with ArcLight

### ISSUE THREAD

**Issue by Meidde** [IzzelAliz/Arclight#1211]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.4

### OS & Java versions

Java 17

### Plugins and Mods

```raw
Mods:
Mine and Slash
Library of Exile
Curios
Epic Fight
===================
Plugins:
Essentials
NLogin
```

### Description

In the Mine and Slash mod, to improve equipment or implement the status system on equipment, it is necessary to drag the refinement item onto the armor/weapon, as if you were applying such an item, but with ArcLight this function simply does not work, I spoke with The owner of Mine and Slash said it's Arclight's fault, and I actually tested it in Mohistmc and pure Forge and it works normally.
And this function IS VERY IMPORTANT for the Mod and also for my server, considering that it is impossible to refine or improve your armor without this status application

### Step to reproduce

1 - Get a Weapon Soul from Mine and Slash
2 - Choose a weapon compatible with the Soul, for example, the soul of a sword, apply it to the sword
3 - Drag the soul onto the sword inside a Gear Station or outside it can work by clicking with shift + click in the inventory on top of the soul

### Logs

This error don't create logs

**Comment by RobertSkalko** [comment]
Does arclight do anything with ItemStackedOnOtherEvent from forge?

Nvm figured it out, it completely overrides doClick method in https://github.com/IzzelAliz/Arclight/blob/3a2ad8aeae8fa4faecbc68fd40119441437b218d/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/world/inventory/AbstractContainerMenuMixin.java#L128

**Comment by Meidde** [comment]
> Does arclight do anything with ItemStackedOnOtherEvent from forge?
> 
> Nvm figured it out, it completely overrides doClick method in
> 
> https://github.com/IzzelAliz/Arclight/blob/3a2ad8aeae8fa4faecbc68fd40119441437b218d/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/world/inventory/AbstractContainerMenuMixin.java#L128

You can help me with this? i'm beginner in modify jars files, and this feature is very important for Mine and Slash :(

**Comment by Meidde** [comment]
> Does arclight do anything with ItemStackedOnOtherEvent from forge?
> 
> Nvm figured it out, it completely overrides doClick method in
> 
> https://github.com/IzzelAliz/Arclight/blob/3a2ad8aeae8fa4faecbc68fd40119441437b218d/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/world/inventory/AbstractContainerMenuMixin.java#L128

Has a solution or are you really just talking to Arclight Dev?

**Comment by RobertSkalko** [comment]
I just pointed out the problem to arclight. Forge uses a hook in doclick method, but it seems arclight overrides the entire method, meaning the event i use for item clicks doesn't work. That's what i assume is happening. If yes, up to arclight to fix it, they can call forge's event manually or not override the method

**Comment by IzzelAliz** [comment]
Never noticed there's a forge call here..... will fix later.
