### ISSUE TITLE
Lithium fabric causes server crash

### ISSUE THREAD

**Issue by L0rdLogan** [IzzelAliz/Arclight#1229]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.20.4-1.0.3-SNAPSHOT

### OS & Java versions

Windows, Java 17

### Plugins and Mods

```raw
Plugins (6): LuckPerms, Vault, WorldEdit, WorldGuard, CoreProtect, GriefPrevention

Mods:
appleskin-fabric-mc1.20.3-2.5.1
cloth-config-13.0.121-fabric
continuity-3.0.0-beta.4+1.20.2
expandedstorage-12.0.1-fabric
fabric-api-0.96.1+1.20.4
fabric-language-kotlin-1.10.17+kotlin.1.9.22
indium-1.0.30+mc1.20.4
nether-chest-mc1.20.3-5.2
notenoughanimations-fabric-1.7.1-mc1.20.4
sodium-fabric-0.5.8+mc1.20.4
starlight-1.1.3+fabric.f5dcd1a
```

### Description

Having Lithium mod installed on the server, causes a crash

### Step to reproduce

1. Install Lithium - lithium-fabric-mc1.20.4-0.12.1

### Logs

https://mclo.gs/jGjaDfU

**Comment by L0rdLogan** [comment]
Also there is no "/fabric mods" equivalent of /forge mods

**Comment by 5ur3z** [comment]
This is a forge hybrid, if I remember correctly

**Comment by IzzelAliz** [comment]
> Also there is no "/fabric mods" equivalent of /forge mods

Fabric mods are dumped every startup.
