### ISSUE TITLE
mv 多世界 无法新建/无法读取新建世界

### ISSUE THREAD

**Issue by lajxw** [IzzelAliz/Arclight#123]
### 我正在运行

* **Arclight** [arclight-1.16.4-1.0.11-SNAPSHOT-03401a4] 
最近几个构建都试过了 问题一样* 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [版本] 

* **操作系统** [windows10 & windows server 2013 均测试]

* **插件列表** 
Multiverse-Core-4.2.2.jar
* **Mod 列表** 
无模组

### 错误描述

无法新建世界

部分情况下可以新建世界 但是重启后无法读取新建的世界

### 重现步骤

1. 安装 Multiverse-Core
2. 输入指令 mv create test normal

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
无错误日志

log:https://paste.ubuntu.com/p/XXQKdHNNbC/
debug:https://paste.ubuntu.com/p/Qr3z7m4CDM/

**Comment by lpj15** [comment]
https://paste.ubuntu.com/p/Qr3z7m4CDM/
