### ISSUE TITLE
Plugins folder missing???

### ISSUE THREAD

**Issue by Manidarean5** [IzzelAliz/Arclight#1239]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.20.1-1.04

### OS & Java versions

Windows 11

### Plugins and Mods

```raw
No mods, no plugins
```

### Description

When I install the server, the plugins folder is missing. Where i install plugins?

**Comment by Kotori0629** [comment]
Did you run run.bat/run.sh? execute `java -jar arclight.jar`

**Comment by Manidarean5** [comment]
Yes

**Comment by L0rdLogan** [comment]
Manually create the plugins folder in the root directory?

**Comment by Manidarean5** [comment]
I already do that. I install 3 times the servers but the servers nevera create the plugins fólder, when i create manually the plugins fólder, nothing happens

**Comment by Shybella** [comment]
You should never have to create the plugins folder. You're doing something wrong or your host doesn't support Arclight.

**Comment by Manidarean5** [comment]
My host IS my pc 💀

**Comment by VodaCode-Official** [comment]
same

**Comment by VodaCode-Official** [comment]
Can i still help? 
[Manidarean5](https://github.com/Manidarean5)

**Comment by Manidarean5** [comment]
Yeah! You can! The problema still here

**Comment by VodaCode-Official** [comment]
[Manidarean5](https://github.com/Manidarean5)
So you need to do this in the terminal IN YOUR MAP “MC server” :

`java -jar arclight.jar nogui `
 ———————-☝️—-☝️
To whatever you got as the file name form the downloads files(I renamed the file to “server.jar”).
Then you wait till you need to change the eula and change that to true.
Then open the terminal in your map “MC server” and do this again:

`java -jar arclight.jar nogui `

And then you have a running server and you plugins file.
Thank me later.

do this 👀if you have seen it pls
And this if it works 👍
Greetings kaiden

**Comment by VodaCode-Official** [comment]
[Manidarean5](https://github.com/Manidarean5)

**Comment by Manidarean5** [comment]
Thank u, i'll try It later

**Comment by 3red7torch5** [comment]
So you need to do this in the terminal IN YOUR MAP “MC server”

What do you mean "in your map"? Having the same issue with plugins folder

**Comment by VodaCode-Official** [comment]
3red7torch5

The map were you server is located

**Comment by Salutatorian** [comment]
recreate a text runarc.bat (or any name of it) as long as it has a .bat at the end. type this in the .bat folder "java -jar (name of your jar).jar nogui" ofc without the quotation marks. then it should open a terminal and the plugin folder will pop out

**Comment by angelof-exe** [comment]
I'm having this issue too, I downloaded the Whisper/1.0.4 version and recreated a new start.bat file with this command 

`java -jar arclight.jar`

the server start but there is no plugins folder

**Comment by VodaCode-Official** [comment]
[angelof-exe](https://github.com/angelof-exe)

Here is the fix for your plugins folder, if you have any problems please contact me 

So you need to do this in the terminal IN YOUR MAP “MC server” :
  `java -jar arclight.jar nogui`(I like to remove nogui                                                    
—————☝️—-☝️                nogui, bc I use the gui)                                                         


Change that to whatever you got as the file name form the downloads files 
(I renamed the **file** to “server.jar”).
Then you wait till you need to change the eula and change that to true.
Then open the terminal in your map “MC server” and do this again:

 `java -jar ……. .jar nogui`

And then you have a running server and you plugins file.

do this 👀if you have seen it pls
And this if it works 👍
Greetings kaiden

**Comment by qyl27** [comment]
Are you running arclight jar in a folder with restricted permissions?  
Or you should publish the log file in the `logs` dir.  
For example, the root of `C:` in windows, needs administrators to create dir or files.

**Comment by VodaCode-Official** [comment]
> Are you running arclight jar in a folder with restricted permissions?
> Or you should publish the log file in the `logs` dir.
> For example, the root of `C:` in windows, needs administrators to create dir or files.

That is not/can not be the problem

**Comment by fero545** [comment]
> [angelof-exe](https://github.com/angelof-exe)
> 
> Here is the fix for your plugins folder, if you have any problems please contact me
> 
> So you need to do this in the terminal IN YOUR MAP “MC server” : `java -jar arclight.jar nogui`(I like to remove nogui —————☝️—-☝️ nogui, bc I use the gui)
> 
> Change that to whatever you got as the file name form the downloads files (I renamed the **file** to “server.jar”). Then you wait till you need to change the eula and change that to true. Then open the terminal in your map “MC server” and do this again:
> 
> `java -jar ……. .jar nogui`
> 
> And then you have a running server and you plugins file.
> 
> do this 👀if you have seen it pls And this if it works 👍 Greetings kaiden

didnt work !

**Comment by VodaCode-Official** [comment]
[fero545](https://github.com/fero545)

I will link a YouTube video…
