### ISSUE TITLE
Arclight Fabric + C2ME Crash

### ISSUE THREAD

**Issue by ImDefiant** [IzzelAliz/Arclight#1240]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.4-1.0.3-SNAPSHOT-6472dea

### OS & Java versions

Windows 10 Pro , Temurin JDK 19.0.2+7

### Plugins and Mods

```raw
fabric-api 0.96.4+1.20.4
C2ME 0.2.0+alpha.11.58
```

### Description

C2ME aims to improve chunk generation performance by allowing the server to use multiple cpu cores in parallel.

### Step to reproduce

1: Install C2ME in mods folder.
2: run server

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/14426513/latest.log)

**Comment by Paulem79** [comment]
Same error using Arclight 1.0.3-SNAPSHOT on Debian 12 with java 17

**Comment by kitovoi111** [comment]
Don't use Arclight, garbage core. Use ketting.

**Comment by IzzelAliz** [comment]
> Don't use Arclight, garbage core. Use ketting.

very polite of you
