### ISSUE TITLE
Arclight forge doesnt work - installer has to be updated

### ISSUE THREAD

**Issue by imtrochi** [IzzelAliz/Arclight#1241]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.4 (all versions)

### OS & Java versions

java version "19.0.1" 2022-10-18 Java(TM) SE Runtime Environment (build 19.0.1+10-21) Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

### Plugins and Mods

```raw
no mods specific
```

### Description

Forge was working badly, it didn't open or download anything, instead it responded with a log that explained the error. Forge already solved this and now it works perfectly, but you have to reinstall the forge on your page. However, Arclight has not been updated yet, the forge file it downloads is old and does not have the fix. Please update it.

### Step to reproduce

1. Install the arclight
2. Run it

### Logs

27.02 20:56:27 [Consola] Starting server!
27.02 20:56:27 [Consola] Loaded config for "Arclight 1.20.1"
27.02 20:56:27 [Consola] Updating eula.txt file
27.02 20:56:28 [Server] INFO Downloading missing libraries ...
27.02 20:56:28 [Server] INFO Downloading mc version manifest...
27.02 20:56:28 [Server] INFO Downloaded forge-1.20.1-47.1.1-installer.jar
27.02 20:56:28 [Server] INFO Failed to download manifest from https://download.mcbbs.net
27.02 20:56:28 [Server] INFO javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching download.mcbbs.net found.
27.02 20:56:31 [Server] INFO Minecraft version: 1.20.1, server: 84194a2f286ef7c14ed7ce0090dba59902951553, mappings: 0b4dba049482496c507b2387a73a913230ebbd76
27.02 20:56:31 [Server] INFO Processing forge installer...
27.02 20:56:31 [Server] INFO Downloaded libraries/net/minecraft/server/1.20.1/server-1.20.1.jar
27.02 20:56:32 [Server] INFO Forge installation is starting, please wait... 
27.02 20:56:32 [Server] INFO JVM info: Oracle Corporation - 17 - 17+35-2724
27.02 20:56:32 [Server] INFO java.net.preferIPv4Stack=true
27.02 20:56:32 [Server] INFO Current Time: 27/02/2024 20:56:32
27.02 20:56:32 [Server] INFO Host: files.minecraftforge.net [51.79.83.165]
27.02 20:56:32 [Server] INFO Host: maven.minecraftforge.net [51.79.83.165]
27.02 20:56:32 [Server] INFO Host: libraries.minecraft.net [13.107.246.33, 13.107.213.33]
27.02 20:56:32 [Server] INFO Host: launchermeta.mojang.com [13.107.246.33, 13.107.213.33]
27.02 20:56:32 [Server] INFO Host: piston-meta.mojang.com [13.107.246.33, 13.107.213.33]
27.02 20:56:32 [Server] INFO java.net.UnknownHostException: authserver.mojang.com: Name or service not known
27.02 20:56:32 [Server] INFO at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
27.02 20:56:32 [Server] INFO at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
27.02 20:56:32 [Server] INFO at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
27.02 20:56:32 [Server] INFO at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
27.02 20:56:32 [Server] INFO at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
27.02 20:56:32 [Server] INFO at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
27.02 20:56:32 [Server] INFO at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
27.02 20:56:32 [Server] INFO at net.minecraftforge.installer.DownloadUtils.getIps(DownloadUtils.java:290)
27.02 20:56:32 [Server] INFO at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
27.02 20:56:32 [Server] INFO Exception in thread "main" 
27.02 20:56:32 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "net.minecraftforge.installer.DownloadUtils.getIps(String)" is null
27.02 20:56:32 [Server] INFO at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
27.02 20:56:32 [Server] INFO java.nio.file.NoSuchFileException: libraries/net/minecraftforge/forge/1.20.1-47.1.1/unix_args.txt
27.02 20:56:32 [Server] INFO at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
27.02 20:56:32 [Server] INFO at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
27.02 20:56:32 [Server] INFO at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
27.02 20:56:32 [Server] INFO at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
27.02 20:56:32 [Server] INFO at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
27.02 20:56:32 [Server] INFO at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
27.02 20:56:32 [Server] INFO at java.base/java.nio.file.Files.lines(Files.java:4132)
27.02 20:56:32 [Server] INFO at java.base/java.nio.file.Files.lines(Files.java:4227)
27.02 20:56:32 [Server] INFO at io.izzel.arclight.forgeinstaller.ForgeInstaller.classpath(ForgeInstaller.java:323)
27.02 20:56:32 [Server] INFO at io.izzel.arclight.forgeinstaller.ForgeInstaller.applicationInstall(ForgeInstaller.java:108)
27.02 20:56:32 [Server] INFO at io.izzel.arclight.boot.application.Main_Forge.forgeInstall(Main_Forge.java:41)
27.02 20:56:32 [Server] INFO at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:19)
27.02 20:56:32 [Server] INFO at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
27.02 20:56:32 [Server] INFO Fail to launch Arclight.
27.02 20:56:32 [Consola] Server shut down (starting)
27.02 20:56:32 [Consola] Restarting crashed server in 5 seconds
27.02 20:56:32 [Consola] Looks like a crash, check the server console. Return value: 255
27.02 20:56:32 [Consola] Server stopped
27.02 20:56:34 [Consola] Received stop command
27.02 20:56:34 [Consola] Server stopped

**Comment by stanlystark** [comment]
same issue

**Comment by IzzelAliz** [comment]
You are not using the version arclight-forge-1.20.1-1.0.4 you claimed.

**Comment by imtrochi** [comment]
> You are not using the version arclight-forge-1.20.1-1.0.4 you claimed.

I used both arclight-forge-1.20.1-1.0.4 and arclight-forge-1.20.1-1.0.3, its the same thing, same issue, its not about the installer, happen with all installers

**Comment by IzzelAliz** [comment]
Do you have internet connection on your server? You can run Arclight on your local machine and upload all generated files to your server.

**Comment by BepEdwin** [comment]
I Have the same issue and I try with diferent installers and all have the same problem, And I Try in my local machine and in the server

![image](https://github.com/IzzelAliz/Arclight/assets/35816612/bf2ea18c-cc14-44a3-bd80-ffe997e75031)

**Comment by imtrochi** [comment]
> Do you have internet connection on your server? You can run Arclight on your local machine and upload all generated files to your server.

Yes, i tried that, but at the time i run the server with all files generated, it starts to generate another version of forge and finish with that log. There is any chance that i can force the run.bat on the server?

**Comment by IzzelAliz** [comment]
alright mojang is down. just wait.

**Comment by BepEdwin** [comment]
I checked out Forge discord yesterday and they said something about that Mojang changed their domain?

**Comment by imtrochi** [comment]
> Owner

Ok, yesterday I talked to Forge and they said that it was fixed, so they told me to talk with Arclight

**Comment by imtrochi** [comment]
> I checked out Forge discord yesterday and they said something about that Mojang changed their domain?

Yeah, but it was already fixed, forge new downloads work perfect, so i suppose that Arclight installers has to be uptaded. That was forge told to me yesterday

**Comment by BepEdwin** [comment]
Yes because yesterday I try it with Mohist and it works, obviously i want use Arclight because i like it more!

**Comment by IzzelAliz** [comment]
Yes. Run `echo "127.0.0.1 authserver.mojang.com" | sudo tee -a /etc/hosts` on your linux server or add `127.0.0.1 authserver.mojang.com` to your hosts file. I'll update installer later.

**Comment by imtrochi** [comment]
> Sí. Ejecútelo `echo "127.0.0.1 authserver.mojang.com" | sudo tee -a /etc/hosts`en su servidor Linux o agréguelo `127.0.0.1 authserver.mojang.com`a su archivo de hosts. Actualizaré el instalador más tarde.

Ok, thanks bro!

**Comment by imtrochi** [comment]
> Yes. Run `echo "127.0.0.1 authserver.mojang.com" | sudo tee -a /etc/hosts` on your linux server or add `127.0.0.1 authserver.mojang.com` to your hosts file. I'll update installer later.

I tried and still doesnt work. But its okay, i wait till you update the installer

**Comment by IzzelAliz** [comment]
You can download the installer yourself and install it yourself. Arclight will recognise forge as installed.

**Comment by imtrochi** [comment]
i am doing the server with a remote sv, and it recognise that forge has to be install, even if it is already installed so i dont know what to do

**Comment by imtrochi** [comment]
I saw the updates you made and they work perfectly locally. I have a remote server and when I put the arclight there the forge 47.1.1 is generated, I don't know why. I have already tried to create the server separately and put the files there but it still does not work, the server tries to create forge 47.1.1. The only solution I can think of is a version of Arclight that generates forge 47.1.1 in version 1.20.1 with the fix, does it exist?

**Comment by IzzelAliz** [comment]
If you want a older forge version, install it yourself and use old arclight builds.

**Comment by imtrochi** [comment]
Ok, im gonna try

**Comment by imtrochi** [comment]
Same issue that before, apparently it generates the forge version 47.1.1 without the fix, can you fix the version of arclight-forge-1.20.1-1.0.1 please? I just buy and the next day happen all this forge stuff.

**Comment by Shybella** [comment]
> Same issue that before, apparently it generates the forge version 47.1.1 without the fix, can you fix the version of arclight-forge-1.20.1-1.0.1 please? I just buy and the next day happen all this forge stuff.

You can change the forge version yourself, look in discord there is plenty of guides.
