### ISSUE TITLE
1.20.1 无法显示发光效果

### ISSUE THREAD

**Issue by Star-Jirachi** [IzzelAliz/Arclight#1244]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.5-1a8925b

### Java 版本 | 操作系统

windows 10 zulu17.46.19-ca-jdk17.0.9-win_x64

### 相关 Mod/插件 的名称及版本

```raw
mod：神化及其前置

插件：无
```

### 错误描述

服务器内所有发光效果失效，例如原版的发光效果，和神化的BOSS发光效果。

将所有mod和插件删掉，原版的发光效果也没有。

在单人、forge服、纯插件服测试正常。

**Comment by TuziXyz** [comment]
这个问题有修复嘛？？我boss想要发光没办法。
