### ISSUE TITLE
无法使用LWC插件

### ISSUE THREAD

**Issue by Re-Aqest** [IzzelAliz/Arclight#1245]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.20.1-1.0.5

### Java 版本 | 操作系统

Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
https://www.spigotmc.org/resources/lwc-extended.69551/
无法使用 LWC Extended 2.3.2
```

### 错误描述

放箱子到地上就报错

### 报错信息

https://netcut.cn/1hnv0up4n

**Comment by IzzelAliz** [comment]
无法复现
