### ISSUE TITLE
UltimateTimber 插件兼容问题

### ISSUE THREAD

**Issue by Re-Aqest** [IzzelAliz/Arclight#1249]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

1.20.1 05

### Java 版本 | 操作系统

java version "19.0.1" 2022-10-18

### 相关 Mod/插件 的名称及版本

```raw
UltimateTimber 3.0
https://craftaro.com/marketplace/product/ultimatetimber.18
```

### 错误描述

砍树服务器出现大规模报错 并且崩服

### 复现步骤

安装插件 然后进行砍树

### 报错信息

https://paste.fastmirror.net/?50370b149b88b351#7P8FGN8FpMcaRX6mdBPX9U61qdkN3YPSn1KJKiZcYiS

**Comment by IzzelAliz** [comment]
无法复现
