### ISSUE TITLE
Server crash fail to launch the server

### ISSUE THREAD

**Issue by JAISHAKTHI2310** [IzzelAliz/Arclight#1250]
Pls solve the 
![Screenshot_2024-03-04-15-07-43-686_com android chrome](https://github.com/IzzelAliz/Arclight/assets/159930176/9b1dad04-4451-4943-9c93-7fddc421cea5)
![Screenshot_2024-03-04-15-07-57-656_com android chrome]

**Comment by JAISHAKTHI2310** [comment]
![Screenshot_2024-03-04-15-07-57-656_com android chrome](https://github.com/IzzelAliz/Arclight/assets/159930176/c28f847c-6b25-4efa-a034-162ef15eab9e)

Here is the another photo

**Comment by IzzelAliz** [comment]
Use a latest dev build.

**Comment by JAISHAKTHI2310** [comment]
Ok thanks
