### ISSUE TITLE
Crash on mob death

### ISSUE THREAD

**Issue by Reforged-Network** [IzzelAliz/Arclight#1252]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.4-1.0.3-SNAPSHOT-ba03152

### OS & Java versions

Java Version: 17.0.10, Eclipse Adoptium

### Plugins and Mods

```raw
https://mclo.gs/GY8vJZ1
```

### Description

Server crash on mob death
https://mclo.gs/GY8vJZ1

### Logs

https://mclo.gs/GY8vJZ1

**Comment by Reforged-Network** [comment]
This is reproduced without any mods or datapacks on a fresh install of arclight-fabric

**Comment by IzzelAliz** [comment]
This should be fixed in latest build.
