### ISSUE TITLE
[Bug/Crash?] Restart Script or Restart Mods/Plugins won't work - WINCH & CONT

### ISSUE THREAD

**Issue by guivnf** [IzzelAliz/Arclight#1256]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 arclight-forge-1.20.1-1.0.4

### OS & Java versions

Windows 10 & Windows Server 2022 - Java 17.0.5

### Plugins and Mods

```raw
[Shutdowner](https://www.curseforge.com/minecraft/mc-mods/shutdowner)
OR
[UltimateAutoRestart](https://www.curseforge.com/minecraft/bukkit-plugins/ultimateautorestart-only-autorestart-plugin-you-will-ever-need)
OR
[Auto Restart](https://www.curseforge.com/minecraft/mc-mods/auto-restart)

None work
```

### Description

Basically the issue consists of trying to use any auto restart mod or plugin, to allow the server to restart at set times. I've tried over 5 different restart mods/plugins and none work, all of them seem to fail and result on the same error... From my reserach, it seems that Spigot's restart system is conflicting with these mods and somehow it makes the server just hang until manually closed with task manager or if i terminate the batch job...

Thing is, it's really odd that this issue started happening only now, since it used to work just fine 2-3 days ago. It only started happening after i added 1 mod, called [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge), and even after removing it, clearing the world, configs and any file it may have generated, as well for other mods, it still seems to be causing this issue...

Mind that i've tried updating arclight to it's newest version too, and it also didn't work, so even a clean installation of arclight didn't solve my problem...

### Step to reproduce

1. Add any of the mentioned mods
2 . Start server
3. execute /restart in server's command prompt or GUI
4. get server timeout/death unloading messages(basically infinite saving of dimensions, proceeded with an error spam)

### Logs

[debug.log](https://github.com/IzzelAliz/Arclight/files/14518487/debug.log) - Error is not shown in Latest.log, tho i'll attach it just in case...
[latest.log](https://github.com/IzzelAliz/Arclight/files/14518488/latest.log)

In this case i was using Shutdowner, it differs a little bit from other restart mods as if the server is left hanging for more than X ammount of seconds it'll terminate the server. So when it says Detected server hanging, shutting down - it's trying to forcibly terminate the server because it detected it's not going anywhere...

### Server pack link (Optional)

No mods required, as i've tested it only with the mentioned mods, and zero other mods aside from those. So it's an issue with arclight or spigot rather than a mod incompatibility...

**Comment by IzzelAliz** [comment]
This is likely to be a bug in upstream projects (jline). You can fix it yourself by using Linux servers,

**Comment by guivnf** [comment]
> This is likely to be a bug in upstream projects (jline). You can fix it yourself by using Linux servers,

Damn, very weird that it started to only have issues now, maybe if i schedule some pending updates on my windows server it might fix it?

**Comment by guivnf** [comment]
Ok so i did update my windows server, and it did nothing lol...

**Comment by guivnf** [comment]
Hey saw that you've made a release with the changes fixing this issue on 1.20.4, wanted to know if they'll be reverted back to 1.20.1 some time soon - https://github.com/IzzelAliz/Arclight/releases/tag/Whisper%2F1.0.3

**Comment by gugu1710m** [comment]
Hey saw that you've made a release with the changes fixing this issue on 1.20.4, wanted to know if they'll be reverted back to 1.16.5 some time soon - https://github.com/IzzelAliz/Arclight/releases/tag/Whisper%2F1.0.3

**Comment by guivnf** [comment]
> Hey saw that you've made a release with the changes fixing this issue on 1.20.4, wanted to know if they'll be reverted back to 1.16.5 some time soon - https://github.com/IzzelAliz/Arclight/releases/tag/Whisper%2F1.0.3

why did you duplicate my post...
