### ISSUE TITLE
The folder for plugins does not appear. 

### ISSUE THREAD

**Issue by KubeLex** [IzzelAliz/Arclight#1264]
Started the core, but the plugins did not appear, help what to do(

**Comment by qyl27** [comment]
Any log?  
Or have you confirmed which jar you have launched?

**Comment by KubeLex** [comment]
[latest.log](https://github.com/IzzelAliz/Arclight/files/14591739/latest.log)
Here are the logs, help please
@qyl27

**Comment by qyl27** [comment]
No Arclight logo is shown on this log.  Please confirm you have used `arclight.jar` but not `start.sh` (the forge launcher without arclight).

**Comment by KubeLex** [comment]
[2024-03-14-1.log](https://github.com/IzzelAliz/Arclight/files/14596375/2024-03-14-1.log)
Here are the new logs, I definitely launched it through archlight.
@qyl27

**Comment by qyl27** [comment]
Ok, it seems this log is incomplete. The server has not launched. Did you terminate the process?  
Try it again?

**Comment by KubeLex** [comment]
I tried it again, got the same log
@qyl27

**Comment by qyl27** [comment]
Well, you will check your server to find out why the process was terminated.

**Comment by KubeLex** [comment]
I've tried to do the same thing on the local server, the startup string too, and it's just because of it that the kernel doesn't start completely, you know what you can do?

**Comment by qyl27** [comment]
Maybe related to your system, but I couldn't provide further help for that. That is NOT an Arclight issue.

**Comment by KubeLex** [comment]
I've already figured it out, thank you more) 
Now I have a different problem.
