### ISSUE TITLE
Incomprehensible error

### ISSUE THREAD

**Issue by KubeLex** [IzzelAliz/Arclight#1274]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.0.5 | 1.20.1

### OS & Java versions

openjdk version "17.0.10" 2024-01-16

### Plugins and Mods

```raw
Create
Create Tracks
```

### Description

Error
java.lang.module.ResolutionException. Modules createtrackmap and org.fusesource.jansi export package org.fusesource.jansi to module chalk

### Step to reproduce

1. Put core
2. Clicked Run
3. Error

### Logs

https://logs.hosting-minecraft.pro/haqucotopu

**Comment by Darth23** [comment]
u have creeperoverhaul mod??

**Comment by IzzelAliz** [comment]
Ask the author of createtrackmap to use jarinjar when packing mods. They shade a whole bunch of dependencies used by Arclight.
