### ISSUE TITLE
AoA trophies crashes the server

### ISSUE THREAD

**Issue by Nebula240** [IzzelAliz/Arclight#128]
### I am running

Arclight 1.15.2 release 1.0.16

* **This is the latest development version** Yep

-Java 1.8.0_252, Private Build

* **Operating System**Linux (amd64) version 4.15.0-76-generic

* **Plugins** `Plugins (17): LuckPerms, PlaceholderAPI, AmkMcAuth, EasyWhitelist, IllegalStack, Vault, MySkin, ProtocolLib, WorldEdit, PlayerKits, Essentials, AdvancedTabOverlay, HolographicDisplays, ChatManager, WorldGuard, DiscordSRV, BanItem`

* **Mods** `SaveMyStronghold-1.15.2-1.0.1.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.1 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		torchslabmod-1.15.2_v1.7.0.jar Torch Slab Mod {torchslabmod@1.7.0 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		AoA3-3.4.4-1.15.2.jar Advent of Ascension {aoa3@3.4.4 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		debug-tools-1.0-SNAPSHOT.jar Debug Tools {debug-tools@NONE DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		teamsmod-1.15.2-R2-hotfix-2.jar Teams {teamsmod@1.15.2-R2-hotfix DONE}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		colytra-FORGE-1.15.2-3.0.jar Colytra {colytra@FORGE-1.15.2-3.0 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		ForgeEndertech-1.15.2-6.0.4.0-build.0044.jar Forge Endertech {forgeendertech@6.0.4.0 DONE}
		Clumps-5.0.2.6.jar Clumps {clumps@5.0.2.6 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		AdHooks-1.15.2-5.1.0.0-build.0046.jar Advanced Hook Launchers {adhooks@5.1.0.0 DONE}
		randompatches-1.15.2-1.22.1.1.jar RandomPatches {randompatches@1.15.2-1.22.1.1 DONE}
		iceandfire-2.1.0-1.15.2.jar Ice and Fire {iceandfire@2.0.3-1.15.2 DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		forge-1.15.2-31.2.47-universal.jar Forge {forge@31.2.47 DONE}
		scuba-gear-1.15.2-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		dash-1.15.2-1.0.1.jar Dash {dash@1.0.1 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		forge-1.15.2-31.2.47-server.jar Minecraft {minecraft@1.15.2 DONE}
		swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		fairylights-3.0.14-1.15.2.jar Fairy Lights {fairylights@3.0.14 DONE}
		astikorcarts-1.15.2-1.0.4.jar AstikorCarts {astikorcarts@1.0.4 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Artifacts-1.15.2-2.5.1.jar Artifacts {artifacts@1.15.2-2.5.1 DONE}
		SpartanShields-1.15.2-2.1.0.jar Spartan Shields {spartanshields@2.1.0 DONE}
		MaterialMaster-v1.3.1-1.15.2.jar MaterialMaster {materialmaster@1.3.1 DONE}
		leap-1.15.2-1.0.1.jar Leap {leap@1.0.1 DONE}
		levelhearts-1.15.2-2.2.0.jar LevelHearts {levelhearts@2.2.0 DONE}
		FastWorkbench-1.15.2-3.1.1.jar FastWorkbench {fastbench@3.1.1 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		[1.15.2]+SecurityCraft+v1.8.17.jar SecurityCraft {securitycraft@v1.8.17 DONE}
		backpacked-1.7.0-1.15.2.jar Backpacked {backpacked@1.7.0 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		custom.jar Arclight Mod {arclight@1.15.2-1.0.16-3161ba4 DONE}
		byg-1.0.11.jar Oh The Biomes You'll Go {byg@1.0.11 DONE}
		Aquaculture-1.15.2-2.0.23.jar Aquaculture 2 {aquaculture@1.15.2-2.0.23 DONE}
		FriendlyFire-1.15.2-4.0.2.jar FriendlyFire {friendlyfire@4.0.2 DONE}
		BetterBurning-1.15.2-1.3.4.jar BetterBurning {betterburning@1.3.4 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
		step-1.15.2-1.0.3.jar Step {step@1.0.3 DONE}
		ExtendedNetherBackport-1.15.2-Beta-4.3.2.jar Extended Nether Backport {extendednether@4.3.2 DONE}`

### Description

When aoa trophies are broken the server will crash

### Step to reproduce

1. Place a trohpy then break it
2. Crash

**Reproducible in Forge** Doesnt happen in forge

### Logs

[ERROR LOG]

https://paste.ubuntu.com/p/PB2JxKfBpH/
https://paste.ubuntu.com/p/FJVmVgz7fh/

**Comment by IzzelAliz** [comment]
This is not an Arclight problem and you should report to AoA developers.
