### ISSUE TITLE
BKCommonLib插件无法运行

### ISSUE THREAD

**Issue by New-Wheat** [IzzelAliz/Arclight#129]
### 我正在运行

* **Arclight** [arclight-1.15.2-1.0.17-SNAPSHOT-601ad19] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_271] 

* **操作系统** [Windows 10 20H2]

* **插件列表** 
BKCommonLib.jar
* **Mod 列表** 
无

### 错误描述
启动后有一坨报错，然后就被disable了

### 重现步骤

1. 安装 xxx

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/VQrp4v2G3w/

**Comment by IzzelAliz** [comment]
请使用 BKCommonLib 的最新构建再次测试，理论上这不算 Arclight 的问题，应该向该插件开发者汇报

**Comment by New-Wheat** [comment]
> 请使用 BKCommonLib 的最新构建再次测试，理论上这不算 Arclight 的问题，应该向该插件开发者汇报

最新的构建也这样

**Comment by IzzelAliz** [comment]
https://github.com/bergerhealer/BKCommonLib/issues/105#issuecomment-767781728

作者已经修复

**Comment by New-Wheat** [comment]
> [bergerhealer/BKCommonLib#105 (comment)](https://github.com/bergerhealer/BKCommonLib/issues/105#issuecomment-767781728)
> 
> 作者已经修复

谢谢
