### ISSUE TITLE
1.20.4 neoforge启动失败

### ISSUE THREAD

**Issue by YDHusky** [IzzelAliz/Arclight#1293]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-neoforge-1.20.4-1.0.3-13f0d63

### Java 版本 | 操作系统

系统: Windows, openjdk version "17.0.10" 2024-01-16 LTS

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

启动生成地图时候报错

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/14786761/latest.log)
[crash-2024-03-28_16.54.21-server.txt](https://github.com/IzzelAliz/Arclight/files/14786762/crash-2024-03-28_16.54.21-server.txt)

**Comment by IzzelAliz** [comment]
Duplicate of #1269 .
