### ISSUE TITLE
End gateway crash

### ISSUE THREAD

**Issue by lethargistic** [IzzelAliz/Arclight#1304]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.4-1.0.3-13f0d63

### OS & Java versions

JRE 17, java -version doesn't work in Apollo console

### Plugins and Mods

```raw
Almost certain issue isn't related to these, read below.

Plugins (9): CoreProtect, LuckPerms, AuthMe, SkinsRestorer, ProtectedDebugStick, AdvancedBan, BlueMap, spark, DiscordSRV

running Fabric,
Lithium, FerriteCore, Anti-Xray
```

### Description

Moved my server from Purpur to Arclight, when players started entering the nether we realized the dimensions were new, I suppose Arclight stores dimensions as in vanilla in the world folder unlike Paper which does so in other folders, and it wasn't an issue, ended up swapping the thing out and everything is functional, but end gateways crash the server on entry.

Any good way to fix this?

### Step to reproduce

Install Arclight to previously Purpur server, move dimensions inside the world folder, join the game, go to the end, go to an end gateway, get disconnected.

### Logs

https://paste.ubuntu.com/p/txRWSsnVWb/
^ crash log
https://paste.ubuntu.com/p/97Yh7Nr56t/
^ latest log

**Comment by IzzelAliz** [comment]
This is fixed in latest build.
