### ISSUE TITLE
Neoforge

### ISSUE THREAD

**Issue by Mathildeuh** [IzzelAliz/Arclight#1309]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Whisper/1.0.3

### OS & Java versions

Debian 12 - Java17 also on Windows - Java17

### Plugins and Mods

```raw
Nothing
```

### Description

The server doesn't want to start 

### Step to reproduce

Just "Java -jar arclight.jar nogui" agree the eula and crash...

### Logs

logs: https://paste.ubuntu.com/p/JdwJmDp6VZ/
crash report: https://paste.ubuntu.com/p/B2wxMYN6Q6/

**Comment by IzzelAliz** [comment]
This is fixed in latest build.
