### ISSUE TITLE
TrMenu无法使用

### ISSUE THREAD

**Issue by nainiu233** [IzzelAliz/Arclight#131]
### 我正在运行

* **Arclight** [arclight-1.16.4-1.0.12-SNAPSHOT-3b0e2bd] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [8] 

* **操作系统** [windows 10]

* **插件列表** 
![image](https://user-images.githubusercontent.com/36364025/104836345-45b3cb80-58e8-11eb-813c-c90d7bd141ae.png)

* **Mod 列表** 
无 mod

### 错误描述

TrMenu无法正常在服务器上工作

### 重现步骤

1. 安装 TrMenu
2. 开启服务器.

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/j9QRX76qj5/

**Comment by JeskaiJet** [comment]
你好，我刚刚使用最新构建的Arclight和最新源码编译的TrMenu成功启动了服务端，并且TabooLib和TrMenu都成功加载。你可以再试一遍。
日志：https://paste.ubuntu.com/p/t94HD3WqJS/

**Comment by IzzelAliz** [comment]
文件损坏了，/libs/TabooLibs.jar 删了重下吧
