### ISSUE TITLE
[1.16.5 Feature] setBoundingBox (custom entity hitbox)

### ISSUE THREAD

**Issue by ShahzadM04** [IzzelAliz/Arclight#1310]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9

### OS & Java versions

Java 17

### Plugins and Mods

```raw
ItemsAdder, LoneLibs
```

### Description

- Same issue as here, fix can be find here: https://github.com/MohistMC/Mohist/issues/2821

Hello, I've seen another issue similar to what I am experiencing here: https://github.com/MohistMC/Mohist/issues/2821 , this has been fixed for Mohist, but not here 

As from the issue reported on MohistMC:
Add the method I mentioned to have support for custom hitbox on entities, I am using items adder and use models created in blockbench and when creating a bone with custom hitbox. Errors appear due to the nonexistence of this method. prevents custom hitbox creation.

Solution:
add the Method: void net.minecraft.entity.Entity.setBoundingBox(net.minecraft.util.math.AxisAlignedBB)

### Step to reproduce

https://itemsadder.devs.beer/plugin-usage/adding-content/mobs/advanced-method/hitbox

### Logs

https://paste.helpch.at/udizeluzah.rb

**Comment by IzzelAliz** [comment]
1.16.5 is no longer being supported. You can still make a PR to fix this though.
