### ISSUE TITLE
bukkit插件使用ConsoleSender进行dispatchCommand无法执行effect指令

### ISSUE THREAD

**Issue by Akegarasu** [IzzelAliz/Arclight#132]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.11] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_271] 

* **操作系统** [win10]

* **插件列表** 
MiniMOTD, ClearEntity, SignCommand, ElevatorSigns, GroupManager, PlaceholderAPI, PlugMan, AutoBroadcastLite, SignWarper, ProtocolLib, CratesLottery, InventoryRollback, SignEdit, LiteSignIn, AdvancedCleaner, VoxelSniper, PFWorlds, LoginBoxSss, TrashBin, Vault, Lores, JavaScriptLibrary, Essentials, ResourceWorld, Admin-GUI, AtMe, QuickShop, QSGUI, FastAsyncWorldEdit (WorldEdit), PlayerTitle, EssentialsProtect, EssentialsAntiBuild, CoreProtect

* **Mod 列表** 

### 错误描述

在自己编写的bukkit插件中，使用ConsoleSender无法执行effect指令，具体操作如下重现步骤
effect give和effect clear均测试无法使用

尝试在paper相同插件的服务端测试正常运行

### 重现步骤

private final ConsoleCommandSender commandExecuter = Bukkit.getServer().getConsoleSender();
String cmdToExec = "effect give akiba_aki minecraft:invisibility 3600 1"
Bukkit.getServer().dispatchCommand(commandExecuter, cmdToExec);

**可在 Forge 复现** [未测试]

**可在 Spigot 复现** [否] 注：paper端可正常使用

### 报错信息

[错误日志]
[m[0m[21:17:04] [Server thread/INFO] [Console/]: Unknown command. Type "/help" for help.

**Comment by StarchierOrb** [comment]
好像原版指令都用不了
