### ISSUE TITLE
单挑插件报错：单挑中死亡的玩家会卡死

### ISSUE THREAD

**Issue by JeskaiJet** [IzzelAliz/Arclight#133]
### 我正在运行

* **Arclight** [ arclight-1.16.5-1.0.12-SNAPSHOT-f0b4f82] 

* **你确认这是最新版吗** [是，因为是从最新构建版本下载的]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [openjdk version "11.0.9.1" 2020-11-04] 

* **操作系统** [ubuntu 20.04]

* **插件列表** 
Dantiao V2.2.6
* **Mod 列表** 
无

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

单挑插件在加载和运行过程中均无任何报错，但是在决斗中出现玩家死亡后控制台出现报错，并且死亡的玩家在复活后卡死（无法移动，无法发言，无法使用命令），在使用/kill命令再次杀死该玩家后出现第二次报错，随后一切恢复正常。

### 重现步骤

1. 安装 单挑 [下载](https://www.mcbbs.net/forum.php?mod=viewthread&tid=818429&extra=page%3D1%26filter%3Dsortid%26sortid%3D7)
2. 进入服务器后 玩家A与玩家B发起决斗请求 
3. 进入决斗 任意一方死亡后 复活后将被传送出竞技场并卡死

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志](https://paste.ubuntu.com/p/2M4PwkKKpT/)

**Comment by IzzelAliz** [comment]
与 #130 重复

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by JeskaiJet** [comment]
经测试没有修复，玩家死亡后依然报错，但是使用/kill命令复活后不再有新报错。
[报错](https://paste.ubuntu.com/p/7z3GmNtnNS/)
报错内容和之前一样

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by JeskaiJet** [comment]
没有修复，报错依旧相同。
怀疑可能是插件本身的问题？我尝试其他同类插件，在玩家死后没有问题出现。

**Comment by IzzelAliz** [comment]
那你试试在 spigot 1.16.5 会不会复现

**Comment by JeskaiJet** [comment]
spigot 1.16.5测试结果：一切正常
Arclight最新构建，只安装Dantiao仍然可以复现问题，但是诡异的是没有任何报错。
[日志](https://paste.ubuntu.com/p/YgFZPhN5JH/)
可以从图片中看出，第一次死亡后复活卡死，仍然可以看到之前的自己(ChokiJ)。
![QQ图片20210130172916](https://user-images.githubusercontent.com/10975080/106352854-46555480-6321-11eb-9a7a-62ca1b6a051c.png)

**Comment by IzzelAliz** [comment]
这个复活是插件自动复活是吗

**Comment by JeskaiJet** [comment]
不是，要自己点一下复活。
复活之前画面还会一直抖动。

**Comment by Liangbai2333** [comment]
> 这个复活是插件自动复活是吗

我也有这个错误，简略的翻了一下他的源码，是自动复活的(Player.Spigot#respawn)，并且我的另一个MOD也会报出找不到玩家实体的错误。（1.0.13仍有，1.0.14-SNAPSHOT未测试）

**Comment by Liangbai2333** [comment]
> > 这个复活是插件自动复活是吗
> 
> 我也有这个错误，简略的翻了一下他的源码，是自动复活的(Player.Spigot#respawn)，并且我的另一个MOD也会报出找不到玩家实体的错误。（1.0.13中仍有，1.0.14-SNAPSHOT未测试）
