### ISSUE TITLE
Can you make a server with boath Forge And Fabric?

### ISSUE THREAD

**Issue by HelloWorldCoder-China** [IzzelAliz/Arclight#1334]

**Comment by heipiao233** [comment]
Just use Sinytra Connector.

**Comment by IzzelAliz** [comment]
Use Sinytra Connector

**Comment by Shisuiicaro** [comment]
I tried to, but my game crashes in 1.20.1

**Comment by heipiao233** [comment]
Then you should open another issue to report this bug.

**Comment by HelloWorldCoder-China** [comment]
> Use Sinytra Connector

社么鬼？
Can you speak Chinese?

**Comment by heipiao233** [comment]
用信雅互联
https://www.mcmod.cn/class/11627.html
https://modrinth.com/mod/connector

**Comment by HelloWorldCoder-China** [comment]
> 用信雅互联 https://www.mcmod.cn/class/11627.html https://modrinth.com/mod/connector

谢谢
