### ISSUE TITLE
Architectury API无法加载

### ISSUE THREAD

**Issue by Little100** [IzzelAliz/Arclight#1335]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [x] 不可在 Forge 复现

### Arclight 版本

arclight-fabric-1.20.4-1.0.3-13f0d63.jar

### Java 版本 | 操作系统

系统Windows11 JDK17

### 相关 Mod/插件 的名称及版本

```raw
只有Fabric API和Architectury API
```

### 错误描述

无论是FabricLoader0.15.6或者更高的版本(0.15.10除外,无法加载)都不能正常加载Architectury API 低版本也不行

### 报错信息

https://paste.ubuntu.com/p/q6Wp2R3B8D/

**Comment by IzzelAliz** [comment]
可以试下升级你的 architectury 到 11.1.17 呢

这个mod在我的测试环境里的

**Comment by Little100** [comment]
> 可以试下升级你的 architectury 到 11.1.17 呢
> 
> 这个mod在我的测试环境里的

我使用了11.1.17版本的architectury api 其他的什么都没改变 还是会崩溃直接提示我[15:49:51 ERROR] [FabricLoader]: Minecraft has crashed!

**Comment by IzzelAliz** [comment]
用最新构建

**Comment by Little100** [comment]
Architectury API最新构建就是11.1.17 无论是什么版本的Architectury API我都无法启动 都会直接崩溃掉

**Comment by IzzelAliz** [comment]
用 arclight 最新构建

**Comment by Little100** [comment]
我确定是最新构建[Whisper/1.0.3]
我也手动更改过Fabric Loader的版本 但是都没有用

**Comment by onelittlechildawa** [comment]
> 我确定是最新构建[Whisper/1.0.3] 我也手动更改过Fabric Loader的版本 但是都没有用

你得在 Actions 里下载

**Comment by Little100** [comment]
> > 我确定是最新构建[Whisper/1.0.3] 我也手动更改过Fabric Loader的版本 但是都没有用
> 
> 你得在 Actions 里下载

好的 我尝试

**Comment by Little100** [comment]
他起作用了 感谢
