### ISSUE TITLE
开启ip转发无法跨服。

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#134]
### 我正在运行 arclight-1.16.5-1.0.12-SNAPSHOT-cfc83f9        构建日期 2021-01-24 16:34:59

* **你确认这是最新版吗**      是

* **你确认所有Mod都安装了依赖**   未安装mod

* **你确认所有插件都已更新至对应版本** 未安装插件 

* **Java** [版本] jre8u231 x64

* **操作系统** windows server 2019

* **插件列表** 无

* **Mod 列表** 无

### 错误描述

bungeecord跨服，使用的原版bungeecord 已在config开启ip转发 。
在spigot.yml中开启bungeecord:true 之后无法跨服跳转，加入服务器提示：If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

使用的bungeecord是最新版本。另：使用Waterfall 最新版并且开启forge支持问题依旧。

### 报错信息

无任何报错 

-->

**Comment by IzzelAliz** [comment]
Arclight(Forge1.13+) 暂时不支持 bc，请阅 FAQ
