### ISSUE TITLE
加载通用机械发电机附属出错，还有很多附属都无法加载

### ISSUE THREAD

**Issue by 3269199948** [IzzelAliz/Arclight#135]
### 我正在运行

* **Arclight** arclight-forge-1.16-1.0.11 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [jdk1.8.0_271] 

* **操作系统** [windown10]

* **插件列表** [无]

* **Mod 列表** [Mekanism-1.16.4-10.0.18.445 , MekanismGenerators-1.16.4-10.0.18.445]

### 错误描述

服务器启动时出错，具体请看错误报告

### 重现步骤

1. 直接将通用机械拖入服务器mods
2. 此时正常启动，再将通用机械发电机拖入服务器mods列表，启动崩溃

**可在 Forge 复现** [是]

**可在 Spigot 复现** [否]

### 报错信息
https://paste.ubuntu.com/p/f7SVBFW8xV/

**Comment by IzzelAliz** [comment]
因为你装了两个 mek
