### ISSUE TITLE
与YggdrasilOfficialProxy冲突，服务端可以启动，但是会炸掉除了ess之外所有插件

### ISSUE THREAD

**Issue by Huaxidesu** [IzzelAliz/Arclight#136]
YggdrasilOfficialProxy与螺端同时启动会导致除了ess外的插件不加载
服务端：螺端1.15-1.0.17
冲突项目：https://github.com/YggdrasilOfficialProxy/YggdrasilOfficialProxy
@Karlatemp

**Comment by IzzelAliz** [comment]
其依赖的authlib injector版本过低

可以通过添加参数 `-Djava.util.logging.manager=io.izzel.arclight.common.mod.util.log.ArclightLazyLogManager` 解决
