### ISSUE TITLE
Is it going to have Minecraft 1.19.2 Forge 43.3.5?

### ISSUE THREAD

**Issue by schuuulz** [IzzelAliz/Arclight#1372]
i have a modpack but, only works on forge 43.3.5. And i would like to run some plugins too....

Is it going to have Minecraft 1.19.2 Forge 43.3.5?

**Comment by Tr3yWay996** [comment]
I honestly don't even think the dev does anything to 1.19.2 even tho it's the most used version

**Comment by qyl27** [comment]
Yes, we do not have enough manpower to maintain every version, but PR is always welcome.

**Comment by Tr3yWay996** [comment]
> Yes, we do not have enough manpower to maintain every version, but PR is always welcome.

And i totally understand that, but is it hard for us to update the forge version ? Maybe we can idk

**Comment by qyl27** [comment]
> > Yes, we do not have enough manpower to maintain every version, but PR is always welcome.
> 
> And i totally understand that, but is it hard for us to update the forge version ? Maybe we can idk

The main work is testing and confirming it works, changing outdated API usage, updating the version needs just changing the versions in `build.gradle`.  
You can refer https://github.com/IzzelAliz/Arclight/commit/40eb59560626ccb05384a7d41998ec12a7354ab6 .

**Comment by qyl27** [comment]
Updated to 43.4.4.

**Comment by Tr3yWay996** [comment]
> Updated to 43.4.4.

Does this mean we can now download the updated version and that mods needing this forge version will work?

**Comment by qyl27** [comment]
> > Updated to 43.4.4.
> 
> Does this mean we can now download the updated version and that mods needing this forge version will work?

Yes, you can download it on our GitHub actions page.  
https://github.com/IzzelAliz/Arclight/actions/runs/11378076757

**Comment by Tr3yWay996** [comment]
> > > Updated to 43.4.4.
> > 
> > 
> > Does this mean we can now download the updated version and that mods needing this forge version will work?
> 
> Yes, you can download it on our GitHub actions page. https://github.com/IzzelAliz/Arclight/actions/runs/11378076757

Doesnt work with Essential, made an new issue about it rn
