### ISSUE TITLE
1.20.4 - Respawn Issue WITH Potion Effects When You Die

### ISSUE THREAD

**Issue by RawrMaoster** [IzzelAliz/Arclight#1374]
I have done every kind of fresh install so i dont know what the issue is.

So with a fresh install of forge and arklight untouched and first run in mind this is the issue with no modifications of any kind.

/kill and just dieing in general is perfectly fine.

But when you do /effect or drink potions you cannot respawn, It sits you in limbo no moving and sometimes allows you to break blocks around you frozen in place and when you relog your in the same spot alive and can play as normal.

Removing the effects of potions by any means allows you to do successfully.

Essentially if you die in lava your stuck in a death loop.

- **https://pastebin.com/PJqp9P5d**

This is what console spits out.

Let me know if you need any more information.

Keep in mind this is on a FRESH install of forge and arklight.

- **forge-1.20.4-49.0.31-installer.jar
- arclight-forge-1.20.4-1.0.3-13f0d63.jar**

**Comment by martasskv5** [comment]
I got the same thing, but with fabric 1.20.4
