### ISSUE TITLE
[ERROR CONSOLE] ShoulderSurfing + Third Person Shooting: Zero

### ISSUE THREAD

**Issue by DaDiGui** [IzzelAliz/Arclight#1377]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.5-1a8925b

### OS & Java versions

java version "22.0.1" 2024-04-16

### Plugins and Mods

```raw
Plugins (9): LuckPerms, Vault, PlaceholderAPI, ProtocolLib, Citizens, SkinsRestorer, ClothesPlus, ConditionalEvents, CommandPanels

• minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
• mods_folder tacz-1.20.1-1.0.1-release.jar : tacz (1.0.1) - 1
• minecraft forge-1.20.1-47.2.20-universal.jar : forge (47.2.20) - 1
• mods_folder ShoulderSurfing-Forge-1.20.1-4.1.1.jar : shouldersurfing (1.20.1-4.1.1) - 1
• mods_folder tp_shooting-1.20.1-5.0.0.jar : tp_shooting (1.20.1-5.0.0) - 1
• mods_folder HitFeedback-1.20.1-1.1.2-forge.jar : hit_feedback (1.20.1-1.1.2) - 1
• mods_folder architectury-9.2.14-forge.jar : architectury (9.2.14) - 1
• mods_folder lradd-1.20.1-0.2.1.jar : lradd (0.2.1) - 1
• arclight arclight-1.20.1-1.0.5-1a8925b.jar : arclight (1.20.1-1.0.5-1a8925b) - 1
```

### Description

The two mods work correctly ingame, they do their purpose which is to add a 3 person camera and to be able to switch between 1 and 3 person. Those errors in console I don't know if it's Arclight's fault or I would have to report it in their respective mods.

### Logs

LOG: https://mclo.gs/WfsHXIv

**Comment by IzzelAliz** [comment]
Report to their developer.

**Comment by ChloePrime** [comment]
Both mods are CLIENT ONLY
and should not be installed on dedicated servers
