### ISSUE TITLE
Arclight ships Antlr 4.9.1, making it impossible to use Antlr 4.13 in plugins

### ISSUE THREAD

**Issue by burdoto** [IzzelAliz/Arclight#1379]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.5-1a8925b

### OS & Java versions

archlinux 6.6.3-arch1-1 & openjdk 17.0.9 2023-10-17

### Plugins and Mods

```raw
Only one custom Plugin; No mods
```

### Description

Arclight seems to be shipping a version of antlr; which will then take precendence over any custom versions shipped in custom shadowjar plugins; making it impossible to use a different Antlr version than 4.9.1

**Comment by IzzelAliz** [comment]
Arclight do not ship antlr, it's Forge.

**Comment by burdoto** [comment]
i see; are you aware why it does? do you think there's a way to circumvent this dependency for mods? trying to use hibernate 6, which depends on antlr 4.13, but 4.9.1 from forge takes precendence over mod classes

**Comment by burdoto** [comment]
From [Minecraft Forge Discord](https://discordapp.com/channels/1129059589325852724/1129069883813007360/1251648807238631455), i was informed that this dependency was redundant and removed in modern versions.
