### ISSUE TITLE
Plugin folder not creating

### ISSUE THREAD

**Issue by imtrochi** [IzzelAliz/Arclight#1384]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.4 (all versions)

### OS & Java versions

java version "19.0.1" 2022-10-18 Java(TM) SE Runtime Environment (build 19.0.1+10-21) Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

### Plugins and Mods

```raw
none
```

### Description

I run a server in arclight 1.20.1 1.0.4 , forge 49.1.0 and generate everything except the plugins folder. And if i create it, it doesnt work. What can i do?

### Step to reproduce

1. install arclight
2. run arclight

### Logs

none

**Comment by ZappyCrawdad** [comment]
you did fixed?

**Comment by imtrochi** [comment]
> you did fixed?

yep
https://discord.com/channels/711137270052421653/1253468545967460374

**Comment by ZappyCrawdad** [comment]
how you can fixed?

**Comment by qyl27** [comment]
Couldn't reproduce.  
Ensure you have launched `archlight.jar` but not the forge `run.bat`.
