### ISSUE TITLE
Update required of arclight-forge-1.20.1-1.0.5.jar

### ISSUE THREAD

**Issue by ErythroCraft** [IzzelAliz/Arclight#1386]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.5

### OS & Java versions

openjdk version "17.0.11" 2024-04-16 OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9) OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode

### Plugins and Mods

```raw
no mods installed
```

### Description

Hello.

Can you create an update of forge loader to latest recommended 1.20.1-forge-47.3.0 ?

This will fix many bugs and issues

THX

### Step to reproduce

normal installation but found unexpected forge version

### Logs

is not required for this issue

**Comment by ErythroCraft** [comment]
![Screenshot 2024-06-21 103432](https://github.com/IzzelAliz/Arclight/assets/76217862/b25879dd-fa93-45d5-910f-761330588c12)

**Comment by ErythroCraft** [comment]
_**And there no plugin folder after installation**_ on zhis found the mistake and create a fix.

However, the issue of the Forge version remains.

**Comment by imtrochi** [comment]
same issue

**Comment by BaiTian6641** [comment]
There is a quick way for this issue
clone the arclight repo trials branch, change the forge version in the build.gradle
then follow the instruction here: https://wiki.izzel.io/s/arclight-docs/doc/contributing-0m2U2kEyC2

**Comment by snowleopardd** [comment]
same issue

**Comment by ErythroCraft** [comment]
Sorry @BaiTian6641, but I know what the error is. 
Right now I have to wait for the owner. Then I can tell him what's wrong.
