### ISSUE TITLE
Aquaculture 2[水产养殖2]海王恩惠宝箱右键不出货，空无一物

### ISSUE THREAD

**Issue by Huaxidesu** [IzzelAliz/Arclight#139]
服务端版本：螺端1.15-1.0.17
问题模组：Aquaculture 2[Aquaculture 2](https://www.mcmod.cn/class/281.html) 
钓上来的[海王恩惠](https://www.mcmod.cn/item/154828.html) 宝箱，在物品栏可以用模组看见里面的nbt数据（很多东西），但是放到地上打开却空无一物
使用纯forge端模组正常运行，海王恩惠宝箱打开后里面有物品

**Comment by IzzelAliz** [comment]
在最新版中修复
