### ISSUE TITLE
Arclight Fabric 1.21 error at startup 

### ISSUE THREAD

**Issue by SrEvelio** [IzzelAliz/Arclight#1395]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-39364b3

### OS & Java versions

OS: Windows 11 / Linux, Java: 21.0.3

### Plugins and Mods

```raw
No mods or plugins
```

### Description

Well let's see, when trying to start arclight in its fabric version 1.21, the server does not open, with or without mods, I tried from Linux and Windows 11 and it did not work at all.

### Step to reproduce

1. Install arclight-fabric-1.21-1.0.0
2. Starts the server

### Logs

[latest.log](https://github.com/user-attachments/files/16034163/latest.log)

**Comment by Hazender** [comment]
the same thing for me but with neoforge, I add my crashlog
[latest.log](https://github.com/user-attachments/files/16034368/latest.log)

**Comment by Arctrometa** [comment]
same thing for me, Arclight 1.21 Fabric. [No mods/plugins]
Crashlog below.
[latest.log](https://github.com/user-attachments/files/16034532/latest.log)

**Comment by Xgabi86** [comment]
same, Arclight 1.21 Fabric. [No mods/plugins]
[latest.log](https://github.com/user-attachments/files/16035988/latest.log)

**Comment by HongyiHank** [comment]
the same (no mods or plugins)[latest.log](https://github.com/user-attachments/files/16038345/latest.log)

**Comment by haydenlau** [comment]
same , 1.21 arclight fabric(no mod and plugins)
[latest.log](https://github.com/user-attachments/files/16038577/latest.log)

**Comment by IzzelAliz** [comment]
Fixed in latest build.

**Comment by TikaTIGER2009** [comment]
dont work 1.21 arclight fabric

**Comment by TikaTIGER2009** [comment]
> Исправлено в последней сборке.

where can I find the corrected file
