### ISSUE TITLE
When I join and die the server throws errors

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#1406]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

FeudalKings/1.0.0-SNAPSHOT (Fabric)

### OS & Java versions

Windows 10 Iot LTSC, JDK 21

### Plugins and Mods

```raw
Plugins (3): TAB, Essentials, GSit
Mods (3): Carpet, WorldEdit, EasyWhitelist
```

### Description

The chat also refuses to work, with the error "Chat is disabled in the client settings"

### Logs

Pastebin : https://paste.ubuntu.com/p/C9J85Vxw5C/

**Comment by luoxiawuchen** [comment]
> ### I have confirmed that ...
> * [x]  Arclight is up to date
> * [x]  all dependencies are installed
> * [x]  all plugins and mods are up to date
> * [x]  unable to reproduce in Spigot
> * [x]  unable to reproduce in Forge
> 
> ### Arclight version
> FeudalKings/1.0.0-SNAPSHOT (Fabric)
> 
> ### OS & Java versions
> Windows 10 Iot LTSC, JDK 21
> 
> ### Plugins and Mods
> ```
> Plugins (3): TAB, Essentials, GSit
> Mods (3): Carpet, WorldEdit, EasyWhitelist
> ```
> 
> ### Description
> The chat also refuses to work, with the error "Chat is disabled in the client settings"
> 
> ### Step to reproduce
> _No response_
> 
> ### Logs
> Pastebin : https://paste.ubuntu.com/p/C9J85Vxw5C/
> 
> ### Server pack link (Optional)
> _No response_

https://github.com/IzzelAliz/Arclight/issues/1398
Had the same issue before, and you can try the latest build that might fix it

https://github.com/IzzelAliz/Arclight/actions

**Comment by ghost** [comment]
> > ### I have confirmed that ...
> > 
> > * [x]   Arclight is up to date
> > * [x]   all dependencies are installed
> > * [x]   all plugins and mods are up to date
> > * [x]   unable to reproduce in Spigot
> > * [x]   unable to reproduce in Forge
> > 
> > ### Arclight version
> > FeudalKings/1.0.0-SNAPSHOT (Fabric)
> > ### OS & Java versions
> > Windows 10 Iot LTSC, JDK 21
> > ### Plugins and Mods
> > ```
> > Plugins (3): TAB, Essentials, GSit
> > Mods (3): Carpet, WorldEdit, EasyWhitelist
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Description
> > The chat also refuses to work, with the error "Chat is disabled in the client settings"
> > ### Step to reproduce
> > _No response_
> > ### Logs
> > Pastebin : https://paste.ubuntu.com/p/C9J85Vxw5C/
> > ### Server pack link (Optional)
> > _No response_
> 
> #1398 Had the same issue before, and you can try the latest build that might fix it
> 
> https://github.com/IzzelAliz/Arclight/actions

Thank you! Most of the problems are gone, but unfortunately after death the chat still doesn’t work :(
