### ISSUE TITLE
java.lang.IllegalStateException: Invalid version: 1.0.0

### ISSUE THREAD

**Issue by Netscape7** [IzzelAliz/Arclight#1410]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-c47e085

### OS & Java versions

 java version 21.0.3 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0

### Plugins and Mods

```raw
Plugins (3): MechanicsCore, ProtocolLib, WeaponMechanics
```

### Description

WeaponMechanics and MecanicsCore do not work with Arclight. When run, they give the errors java.lang.NoClassDefFoundError: Could not initialize class me.deecaad.core.utils.ReflectionUtil and java.lang.IllegalStateException: Invalid version: 1.0.0.
Paper 1.21 does not have this issue and loads correctly.

### Logs

[latest.log](https://github.com/user-attachments/files/16107676/latest.log)

**Comment by IzzelAliz** [comment]
This is MecanicsCore parse Arclight version as MC version, which cannot be fixed on our side. Report to their developers.

p.s. Arclight version string: `arclight-1.21-1.0.0-SNAPSHOT-ee68f941 (MC: 1.21)`.
