### ISSUE TITLE
API Does not show 1.21

### ISSUE THREAD

**Issue by 0x7d8** [IzzelAliz/Arclight#1412]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.21

### OS & Java versions

-

### Plugins and Mods

```raw
-
```

### Description

https://files.hypoglycemia.icu/v1/files/arclight/minecraft does not have version 1.21 listed
https://files.hypoglycemia.icu/v1/files/arclight/branches shows it

### Step to reproduce

Go to https://files.hypoglycemia.icu/v1/files/arclight/minecraft

**Comment by IzzelAliz** [comment]
Fixed.
