### ISSUE TITLE
Lithium doesen't work

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#1414]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-c47e085 - fabric

### OS & Java versions

Windows 10 Iot LTSC, JDK 21

### Plugins and Mods

```raw
Plugins: CoreProtect, Essentials, PlaceholderAPI, AFKPlus, Clans, TAB, GSit, AFKPlusPAPI, WorldsColor
Mods : Status, Fabric API, Lithium
```

### Description

Lithium doesen't work

### Logs

https://paste.ubuntu.com/p/nMXMp9KK63/

**Comment by Elyas2024** [comment]
yeah, most optimization mods dont work on arclight. i tried it too and the same thing happend to me

**Comment by qyl27** [comment]
We haven't supported lithium or the other many optimization mods.

**Comment by ghost** [comment]
But why then does version 1.20.4 of Fabric support these mod?

**Comment by qyl27** [comment]
> But why then does version 1.20.4 of Fabric support these mod?

It works just by accident, fix Lithium has low priority in our plan, but PR is welcome.  
This issue can remain open until we are supported.

**Comment by ghost** [comment]
I found a solution to fix this error, in lithium.properties you need to write mixin.ai=false, and then lithium starts without problems, and c2me is fixed in the same way

**Comment by qyl27** [comment]
Thank you a lot!

**Comment by ghost** [comment]
Can I create a github page with patched Archlight mods?

**Comment by qyl27** [comment]
> Can I create a github page with patched Archlight mods?

Sure, we are glad to see that, a page with some tips either in our GitHub discussion or in a repo is good.
