### ISSUE TITLE
FeudalKings 与格雷科技不兼容 【请求升级Neoforge】

### ISSUE THREAD

**Issue by windy664** [IzzelAliz/Arclight#1415]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-neoforge-1.21-1.0.0-SNAPSHOT

### Java 版本 | 操作系统

Java 21

### 相关 Mod/插件 的名称及版本

```raw
[前置]configuration-neoforge-1.21-2.3.0.jar
[前置][格雷科技]ldlib-neoforge-1.21-1.0.26.a.jar
[格雷科技现代版] gtceu-1.21-1.3.1.jar
```

### 错误描述
从日志来看，发生了一个 java.lang.RuntimeException 异常，并且有一条涉及 java.lang.reflect.InvocationTargetException 的错误信息。这通常意味着在反射调用过程中发生了异常，导致了任务的延迟或失败。

以下是逐行日志分析：

[09:46:18.997]: Datafixer 的优化操作完成，耗时 51 毫秒。
[09:46:19.770]: Minecraft 认证服务初始化，设置了会话和服务主机的环境变量。
[09:46:19.871]: 警告信息，指出资源包的 URL 使用了意外的 schema，这可能与路径编码或不兼容的 URL 格式有关。
[09:46:19.877]: GregTechCEu 模组开始注册地牢战利品。
[09:46:19.994]: Minecraft 服务器发现了新的数据包并自动加载。
[09:46:21.943]: 发生 java.lang.RuntimeException 异常，具体原因是反射调用过程中出现的 java.lang.reflect.InvocationTargetException。
异常堆栈跟踪显示问题出现在 LaunchServiceHandlerDecorator 的 launch 方法中，而这个方法被 LaunchServiceHandler 调用，最终导致了启动器（Launcher）的运行失败。

可能的解决方案
检查资源路径: 确保所有资源路径正确且没有编码问题（如 %20 替代空格等）。
更新模组和启动器: 确保所有模组、资源包和启动器都是最新版本，避免因版本不兼容导致的反射调用问题。
调试反射调用: 如果有自定义代码使用反射，请检查反射调用是否正确，确保目标方法或类存在且可以正常访问。
日志细节分析: 查看更详细的日志信息，特别是 java.lang.reflect.InvocationTargetException 的根本原因，可以帮助确定是哪一部分代码导致了反射调用失败。

**感觉好像是NeoForge版本太低了**

### 复现步骤
下载好arc，装格雷

_No response_

### 报错
https://pastebin.com/S3eEzCVk

[debug.log](https://github.com/user-attachments/files/16200508/debug.log)
信息

_No response_

**Comment by qyl27** [comment]
现已迁移至1.21.1
