### ISSUE TITLE
forward-permission doesen't work

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#1419]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

FeudalKings/1.0.0-SNAPSHOT (Fabric)

### OS & Java versions

Windows 10 Iot LTSC, JDK 21

### Plugins and Mods

```raw
Plugins (15): CoreProtect, LuckPerms, Essentials, RealTimePlugin, PlaceholderAPI, AFKPlus, BedrockArmorstands, AntiDisconnectSpam, TAB, spark, GSit, AFKPlusPAPI, WorldsColor, Clans, FakeCreative
```

### Description

Maybe I don’t understand something, but LuckPerms does not display permissions from Fabric mods
(I tested on WorldEdit)

**Comment by qyl27** [comment]
The Fabric ecosystem has no unified permission management system, if you install the fabric mod version of LuckPerms, you can't manage the permissions from other mods also which didn't use the permission provided by LuckPerms.
