### ISSUE TITLE
服务器时不时崩溃

### ISSUE THREAD

**Issue by TCwater** [IzzelAliz/Arclight#142]
### 我正在运行的时候出现崩溃

* **Arclight** [版本] 

* **你确认这是最新版吗** [是/否，因为___]

大概是，为群文件下载是1.0.2
* **你确认所有Mod都安装了依赖** [是/否]

* **你确认所有插件都已更新至对应版本** [是/否]

* **Java** [版本] 

* **操作系统** [名称+版本]

* **插件列表** 

* **Mod 列表** 

### 错误描述
昨天晚上开始出现崩溃，24小时内插件mod无变化

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

运行中时不时？或许和某个区域有关？

**可在 Forge 复现** [是/否] 不知道

**可在 Spigot 复现** [是/否] 不知道

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/7g254YjCGq/

**Comment by IzzelAliz** [comment]
请检查 ultitools 的 home 指令

**Comment by IzzelAliz** [comment]
无法复现
