### ISSUE TITLE
【诸王 Fabric 1.21】死亡复活后出现问题

### ISSUE THREAD

**Issue by Music0Kirby** [IzzelAliz/Arclight#1424]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.21-1.0.0-SNAPSHOT-b3349e9

### Java 版本 | 操作系统

Windows10 x64, Java: JDK 21 (21.0.2)

### 相关 Mod/插件 的名称及版本

```raw
未安装
```

### 错误描述
死掉会后原地重生，但是无法和任何东西交互，也无法使用指令和聊天等
如果使用/kill指令后会出现“试图执行该命令时出现意外错误”
退出服务器后再进入会显示联机超时（必须删掉玩家数据才可以）
如果服务器重启再进入的话就会从执行指令后重复上述问题

### 复现步骤

安装arclight-1.21-1.0.0-SNAPSHOT-b3349e9
在服务器内自杀
复现成功

此外使用/kill会弹出“试图执行该命令时出现意外错误”

### 报错信息

[latest.log](https://github.com/user-attachments/files/16323324/latest.log)

**Comment by qyl27** [comment]
Fixed by https://github.com/IzzelAliz/Arclight/commit/c47e085172036e12fea7abc51ea1274a86bbbf76 .
