### ISSUE TITLE
部分mod物品在物品栏里移动后会丢失nbt数据。

### ISSUE THREAD

**Issue by FierceManul** [IzzelAliz/Arclight#143]
### 我正在运行

arclight-1.16.5-1.0.12-SNAPSHOT-bcf3f33

* **Java** [11] 

* **插件列表** 
* LuckPerms, Halo_RT, PluginManager, CMILib, eBackup, ProtocolLib, AntiSeedCracker, CoreProtect, WorldEdit, DeluxeTags, AllMusic, PlaceholderAPI, spark, GHolo, Vault, CMI, MiaoChat, Residence, AuthMe, ResProtection, QuickShop

* **Mod 列表** 
? mods_folder endportalrecipe_1.16.4-2.1.jar : endportalrecipe (2.1) - 1
? mods_folder woot-1.16.4-1.0.3.0.jar : woot (1.16.4-1.0.3.0) - 1
? mods_folder jei-1.16.4-7.6.1.65.jar : jei (7.6.1.65) - 1
? mods_folder ChineseWorkshop-1.16.3-3.2.0.jar : chineseworkshop (3.2.0) - 1
? mods_folder Kiwi-1.16.3-3.4.1.jar : kiwi (3.4.1) - 1
? mods_folder Mekanism-1.16.4-10.0.18.445.jar : mekanism (10.0.18) - 1
? mods_folder mcw-windows-1.0.2-mc1.16.4.jar : mcwwindows (1.0.2) - 1
? mods_folder caelus-forge-1.16.4-2.1.0.2.jar : caelus (1.16.4-2.1.0.2) - 1
? mods_folder rsgauges-1.16.4-1.2.6.jar : rsgauges (1.2.6) - 1
? mods_folder pitg-1.16.3-1.4.1.jar : pitg (1.16.3-1.4.1) - 1
? mods_folder Waystones_1.16.3-7.3.1.jar : waystones (7.3.1) - 1
? mods_folder ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar : forgeendertech (7.0.9.0) - 1
? mods_folder AdFinders-1.16.4-5.0.4.0-build.0027.jar : adfinders (5.0.4.0) - 1
? mods_folder Clumps-6.0.0.13.jar : clumps (6.0.0.13) - 1
? mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
? mods_folder Placebo-1.16.3-4.3.3.jar : placebo (4.3.3) - 1
? mods_folder dankstorage-3.14.jar : dankstorage (3.14) - 1
? mods_folder AdHooks-1.16.4-6.1.2.0-build.0027.jar : adhooks (6.1.2.0) - 1
? mods_folder engineerstools-1.16.4-1.1.2.jar : engineerstools (1.1.2) - 1
? mods_folder DungeonCrawl-1.16.3-2.2.4.jar : dungeoncrawl (2.2.4) - 1
? mods_folder Bookshelf-1.16.4-9.3.18.jar : bookshelf (9.3.18) - 1
? mods_folder buildinggadgets-1.16.4-3.7.3.jar : buildinggadgets (3.7.3) - 1
? mods_folder simpleplanes-1.16.3-3.2.0.3.jar : simpleplanes (1.16.3-3.2.0.3) - 1
? mods_folder ForgivingVoid_1.16.3-5.2.0.jar : forgivingvoid (5.2.0) - 1
? mods_folder mcw-doors-1.0.1fix-mc1.16.4.jar : mcwdoors (1.0.1) - 1
? mods_folder LightingWand-1.16.4-1.7.3.jar : lightingwand (1.7.3) - 1
? mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
? mods_folder [已修改]mapperbase-1.16.4-2.3.0.0.jar : mapperbase (1.16.4-2.3.0.0) - 1
? mods_folder MekanismGenerators-1.16.4-10.0.18.445.jar : mekanismgenerators (10.0.18) - 1
? mods_folder dismountentity_1.16.4-1.2.jar : dismountentity (1.2) - 1
? mods_folder mininggadgets-1.7.1.jar : mininggadgets (1.7.1) - 1
? mods_folder ImmersivePetroleum-1.16.4-3.1.0-2.jar : immersivepetroleum (3.1.0-2) - 1
? maven_libs forge-1.16.5-36.0.1-universal.jar : forge (36.0.1) - 1
? mods_folder PassthroughSigns-1.16.4-2.3.7.jar : passthroughsigns (1.16.4-2.3.7) - 1
? mods_folder absentbydesign-1.16.4-1.3.1.jar : absentbydesign (1.16.4-1.3.1) - 1
? mods_folder conduitsprdrowned_1.16.4-1.1.jar : conduitsprdrowned (1.1) - 1
? minecraft forge-1.16.5-36.0.1-server.jar : minecraft (1.16.5) - 1
? mods_folder mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
? mods_folder repurposed_structures-1.16.4-2.3.3.jar : repurposed_structures (1.16.4-2.3.3) - 1
? mods_folder embellishcraft-1.16.4-3.3.0.0.jar : embellishcraft (1.16.4-3.3.0.0) - 1
? mods_folder ToolBelt-1.16.3-1.15.2.jar : toolbelt (1.15.2) - 1
? mods_folder ImmersiveEngineering-1.16.4-4.1.2-129.jar : immersiveengineering (1.16.4-4.1.2-129) - 1
? mods_folder BiomesOPlenty-1.16.4-13.0.0.427-universal.jar : biomesoplenty (1.16.4-13.0.0.427) - 1
? mods_folder MekanismAdditions-1.16.4-10.0.18.445.jar : mekanismadditions (10.0.18) - 1
? mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
? mods_folder pamhc2crops-1.16.3-1.0.1.jar : pamhc2crops (version) - 1
? mods_folder mcw-trapdors-1.0.0-mc1.16.4.jar : mcwtrpdoors (1.0.0) - 1
? mods_folder forbidden_arcanus-1.16.4-1.0.0.jar : forbidden_arcanus (1.16.4-1.0.0) - 1
? mods_folder AdLods-1.16.4-4.1.3.0-build.0034.jar : adlods (4.1.3.0) - 1
? mods_folder structure_safe_java_eleven-1.0.jar : structure_safe_java_eleven (1.0) - 1
? mods_folder movingelevators-1.2.31a-mc1.16.4.jar : movingelevators (1.2.31a) - 1
? mods_folder towers_of_the_wild-1.16.4-2.0.1.jar : towers_of_the_wild (1.16.4-2.0.1) - 1
? mods_folder simplylight-1.16.4-1.1.1.jar : simplylight (1.16.4-1.1.1) - 1
? mods_folder Botania-1.16.4-410.jar : botania (1.16.4-410) - 1
? mods_folder easy_villagers-1.16.4-1.1.20.jar : easy_villagers (1.16.4-1.1.20) - 1
? mods_folder curios-forge-1.16.4-4.0.3.3.jar : curios (1.16.4-4.0.3.3) - 1
? mods_folder Patchouli-1.16.4-48.jar : patchouli (1.16.4-48) - 1
? mods_folder pamhc2foodcore-1.16.3-1.0.0.jar : pamhc2foodcore (version) - 1
? mods_folder collective-1.16.4-1.53.jar : collective (1.53) - 1
? mods_folder cyclepaintings_1.16.4-1.4.jar : cyclepaintings (1.4) - 1
? mods_folder AutoRegLib-1.6-47.jar : autoreglib (1.6-47) - 1
? mods_folder Quark-r2.4-291.jar : quark (r2.4-291) - 1
? mods_folder Apotheosis-1.16.3-4.4.1.jar : apotheosis (4.4.1) - 1
? mods_folder StorageDrawers-1.16.3-8.2.1.jar : storagedrawers (8.2.1) - 1
? mods_folder Fertilization_1.16.3-5.2.0.jar : fertilization (5.2.0) - 1
? mods_folder EnigmaticLegacy-2.10.3.jar : enigmaticlegacy (2.10.3) - 1
? mods_folder TheAbyss+2.0.0+1.16.4.jar : theabyss (2.0.0) - 1
? mods_folder MekanismTools-1.16.4-10.0.18.445.jar : mekanismtools (10.0.18) - 1
? mods_folder mcws-roofs-2.0.0-mc1.16.4.jar : mcwroofs (2.0.0) - 1
? mods_folder furniture-7.0.0-pre19-1.16.3.jar : cfm (7.0.0-pre19) - 1
? mods_folder engineersdecor-1.16.4-1.1.5.jar : engineersdecor (1.1.5) - 1
? mods_folder curiouselytra-forge-1.16.3-4.0.0.1.jar : curiouselytra (1.16.3-4.0.0.1) - 1
? mods_folder mcw-furniture-2.0.0-mc1.16.4.jar : mcwfurnitures (2.0.0) - 1
>? arclight server.jar : arclight (1.16.5-1.0.12-SNAPSHOT-bcf3f33) - 1
? mods_folder forge-1.16.4-geckolib-3.0.0.jar : geckolib3 (3.0.0) - 1
? mods_folder ars_nouveau-1.16.4-1.11.2.jar : ars_nouveau (1.11.2) - 1

### 错误描述

夸克的古卷（储存附魔），简易村民（所有方块），woot的生物控制器，在物品栏里点一下，或者移动，都会丢失nbt数据，变成一个空内容方块（物品）。后台没有输出。

**可在 Forge 复现** [否]

### 报错信息

[错误日志]

<details><pre>
打不开
</pre></details>

[debug-5.log.gz](https://github.com/IzzelAliz/Arclight/files/5893574/debug-5.log.gz)
[2021-01-29-6.log.gz](https://github.com/IzzelAliz/Arclight/files/5893575/2021-01-29-6.log.gz)

-->

**Comment by Akegarasu** [comment]
冰与火mod的龙吟号角移动也会丢失nbt数据

**Comment by FierceManul** [comment]
还有沉浸工程的手持矿钻。

**Comment by FierceManul** [comment]
不知道这对你有没有帮助，我把他们的nbt get出来了。
![屏幕截图(543)](https://user-images.githubusercontent.com/64459019/106389626-3754cc00-641f-11eb-8702-52d4589c9b39.png)
![屏幕截图(544)](https://user-images.githubusercontent.com/64459019/106389627-39b72600-641f-11eb-92b1-2f6490072fcb.png)
![屏幕截图(545)](https://user-images.githubusercontent.com/64459019/106389628-39b72600-641f-11eb-9f72-e133e52a9ab4.png)
![屏幕截图(546)](https://user-images.githubusercontent.com/64459019/106389629-3a4fbc80-641f-11eb-8136-eb9c69aed5cf.png)

**Comment by IzzelAliz** [comment]
使用以下配置无法复现，请二分找出导致的模组或插件

```
pl
[14:58:00] [Server thread/INFO] [Console/]: Plugins (5): CoreProtect, LuckPerms, GriefDefender, Essentials, ProtocolLib
forge mods
[14:58:01] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List: 
• minecraft forge-1.16.5-36.0.14-server.jar : minecraft (1.16.5) - 1
• mods_folder structurize-0.13.113-ALPHA-universal.jar : structurize (0.13.113-ALPHA) - 1
• maven_libs forge-1.16.5-36.0.14-universal.jar : forge (36.0.14) - 1
• mods_folder ImmersiveEngineering-1.16.5-4.2.0-130.jar : immersiveengineering (1.16.5-4.2.0-130) - 1
• mods_folder minecolonies-0.13.584-ALPHA-universal.jar : minecolonies (0.13.584-ALPHA) - 1
• arclight arclight-forge-1.16-1.0.14-SNAPSHOT.jar : arclight (1.16.5-1.0.13-SNAPSHOT-efc4df3) - 1
```

**Comment by a575780861** [comment]
@IzzelAliz  可以复现此BUG. 最容易复现bug的mod是夸克mod,刚刚测试复现过程如下
使用纯净服务器.版本:arclight-forge-1.16-1.0.14-SNAPSHOT.jar
只安装夸克mod和它的支持库:
Quark.jar  版本:r2.4-304
AutoRegLib.jar  版本:1.6-47
进入游戏后. 给与OP权限. 更改模式为创造模式. 从物品栏中搜索  古卷 物品. 将任意古卷取出放入物品栏. 然后在物品栏中任意移动几次后会发现 古卷变为了空白, 即NBT丢失. 
并且同时服务器报出一个 WARN:Can't keep up! Is the server overloaded? Running 2360ms or 47 ticks behind
之后再从任何地方拿取古卷物品都会变成没有NBT标签的空白物品.
除此之外没有任何其他错误报出.

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by Liangbai2333** [comment]
MOD的NBT数据还是无法保存，放进物品栏后经常性的丢失，有时又不会丢失。`

MOD部分代码如下: 
```
@Override
  public CompoundNBT getShareTag(ItemStack stack) {
    CompoundNBT shareTag = stack.getTag();
    if (shareTag == null) {
      shareTag = new CompoundNBT();
    }
    CompoundNBT storageTag = stack.getCapability(ModCapabilities.STORAGE)
        .map(IStorage::serializeNBT)
        .orElse(null);
    if (storageTag != null && !storageTag.isEmpty()) {
      shareTag.put("storage", storageTag);
    }
    return shareTag;
  }

  @Override
  public void readShareTag(ItemStack stack, @Nullable CompoundNBT nbt) {
    if (nbt != null && nbt.contains("storage", Constants.NBT.TAG_COMPOUND)) {
      stack.getCapability(ModCapabilities.STORAGE)
          .ifPresent(gun -> gun.deserializeNBT(nbt.getCompound("storage")));
    }
    super.readShareTag(stack, nbt);
  }
```

**Comment by Akegarasu** [comment]
测试冰与火的龙吟号角已修复 41a7033

**Comment by IzzelAliz** [comment]
> 
> 
> MOD的NBT数据还是无法保存，放进物品栏后经常性的丢失，有时又不会丢失。`
> 
> MOD部分代码如下:
> 
> ```
> @Override
>   public CompoundNBT getShareTag(ItemStack stack) {
>     CompoundNBT shareTag = stack.getTag();
>     if (shareTag == null) {
>       shareTag = new CompoundNBT();
>     }
>     CompoundNBT storageTag = stack.getCapability(ModCapabilities.STORAGE)
>         .map(IStorage::serializeNBT)
>         .orElse(null);
>     if (storageTag != null && !storageTag.isEmpty()) {
>       shareTag.put("storage", storageTag);
>     }
>     return shareTag;
>   }
> 
>   @Override
>   public void readShareTag(ItemStack stack, @Nullable CompoundNBT nbt) {
>     if (nbt != null && nbt.contains("storage", Constants.NBT.TAG_COMPOUND)) {
>       stack.getCapability(ModCapabilities.STORAGE)
>           .ifPresent(gun -> gun.deserializeNBT(nbt.getCompound("storage")));
>     }
>     super.readShareTag(stack, nbt);
>   }
> ```

你说的这些和这个问题没有关联。什么 mod，怎么复现

**Comment by Liangbai2333** [comment]
> > MOD的NBT数据还是无法保存，放进物品栏后经常性的丢失，有时又不会丢失。`
> > MOD部分代码如下:
> > ```
> > @Override
> >   public CompoundNBT getShareTag(ItemStack stack) {
> >     CompoundNBT shareTag = stack.getTag();
> >     if (shareTag == null) {
> >       shareTag = new CompoundNBT();
> >     }
> >     CompoundNBT storageTag = stack.getCapability(ModCapabilities.STORAGE)
> >         .map(IStorage::serializeNBT)
> >         .orElse(null);
> >     if (storageTag != null && !storageTag.isEmpty()) {
> >       shareTag.put("storage", storageTag);
> >     }
> >     return shareTag;
> >   }
> > 
> >   @Override
> >   public void readShareTag(ItemStack stack, @Nullable CompoundNBT nbt) {
> >     if (nbt != null && nbt.contains("storage", Constants.NBT.TAG_COMPOUND)) {
> >       stack.getCapability(ModCapabilities.STORAGE)
> >           .ifPresent(gun -> gun.deserializeNBT(nbt.getCompound("storage")));
> >     }
> >     super.readShareTag(stack, nbt);
> >   }
> > ```
> 
> 你说的这些和这个问题没有关联。什么 mod，怎么复现

MOD: Crafting-Dead(<https://github.com/nexusnode/crafting-dead>)，将物品放入这个MOD的背心内，再拿出放到物品栏随意移动几次，其中的存储物品的NBT数据就会消失。（单人模式下没有这个问题）

**Comment by a575780861** [comment]
经过测试  arclight-1.16.5-1.0.14-SNAPSHOT-41a7033
夸克MOD中的 古卷问题已经修复. 并且同时 水产养殖2 mod中海王的恩赐宝箱的问题也修复了. 

测试了其他可能跟NBT系统有关的BUG.

单独安装 沉浸工程mod
ImmersiveEngineering 版本: 1.16.5-4.2.0-131
Patchouli 版本: 1.16.4-48

使用 工程师装配台 装配 采矿机械钻
分别安装组件:大型燃料缸,压缩空气罐,高级润滑系统
到这里是没什么问题的. 但是继续安装 铁质钻头 或 任意皮肤的话,所有的配件都会丢失.

还发现了一个其他的问题. 可能不跟NBT系统有关. 应该是实体相关的问题. 一并反馈了吧.
单独安装 通用机械Mod
Mekanism
MekanismTools
MekanismGenerators
MekanismAdditions
版本:1.16.5-10.0.19.446

使用充电站将 机器人放出后. 一旦机器人受到攻击. 机器人便无法继续使用. 右键点击时无法打开GUI. 而且也没有AI. 但是受重力影响.
之前机器人还有一个问题. 打开GUI之后点击维修按钮的话 服务器会崩溃. 但是现在不会了. 我在想会不会也是同样跟NBT有关.

**Comment by IzzelAliz** [comment]
> 
> 
> > > MOD的NBT数据还是无法保存，放进物品栏后经常性的丢失，有时又不会丢失。`
> > > MOD部分代码如下:
> > > ```
> > > @Override
> > >   public CompoundNBT getShareTag(ItemStack stack) {
> > >     CompoundNBT shareTag = stack.getTag();
> > >     if (shareTag == null) {
> > >       shareTag = new CompoundNBT();
> > >     }
> > >     CompoundNBT storageTag = stack.getCapability(ModCapabilities.STORAGE)
> > >         .map(IStorage::serializeNBT)
> > >         .orElse(null);
> > >     if (storageTag != null && !storageTag.isEmpty()) {
> > >       shareTag.put("storage", storageTag);
> > >     }
> > >     return shareTag;
> > >   }
> > > 
> > >   @Override
> > >   public void readShareTag(ItemStack stack, @Nullable CompoundNBT nbt) {
> > >     if (nbt != null && nbt.contains("storage", Constants.NBT.TAG_COMPOUND)) {
> > >       stack.getCapability(ModCapabilities.STORAGE)
> > >           .ifPresent(gun -> gun.deserializeNBT(nbt.getCompound("storage")));
> > >     }
> > >     super.readShareTag(stack, nbt);
> > >   }
> > > ```
> > 
> > 
> > 你说的这些和这个问题没有关联。什么 mod，怎么复现
> 
> MOD: Crafting-Dead(https://github.com/nexusnode/crafting-dead)，将物品放入这个MOD的背心内，再拿出放到物品栏随意移动几次，其中的存储物品的NBT数据就会消失。（单人模式下没有这个问题）

我用 quark 的古卷和沉浸工程的钻头试了一下，无法复现

**Comment by IzzelAliz** [comment]
> 
> 
> 经过测试 arclight-1.16.5-1.0.14-SNAPSHOT-41a7033
> 夸克MOD中的 古卷问题已经修复. 并且同时 水产养殖2 mod中海王的恩赐宝箱的问题也修复了.
> 
> 测试了其他可能跟NBT系统有关的BUG.
> 
> 单独安装 沉浸工程mod
> ImmersiveEngineering 版本: 1.16.5-4.2.0-131
> Patchouli 版本: 1.16.4-48
> 
> 使用 工程师装配台 装配 采矿机械钻
> 分别安装组件:大型燃料缸,压缩空气罐,高级润滑系统
> 到这里是没什么问题的. 但是继续安装 铁质钻头 或 任意皮肤的话,所有的配件都会丢失.
> 
> 还发现了一个其他的问题. 可能不跟NBT系统有关. 应该是实体相关的问题. 一并反馈了吧.
> 单独安装 通用机械Mod
> Mekanism
> MekanismTools
> MekanismGenerators
> MekanismAdditions
> 版本:1.16.5-10.0.19.446
> 
> 使用充电站将 机器人放出后. 一旦机器人受到攻击. 机器人便无法继续使用. 右键点击时无法打开GUI. 而且也没有AI. 但是受重力影响.
> 之前机器人还有一个问题. 打开GUI之后点击维修按钮的话 服务器会崩溃. 但是现在不会了. 我在想会不会也是同样跟NBT有关.

那个装钻头丢配件的，我试了一下配件还在，应该是显示同步问题

**Comment by Liangbai2333** [comment]
> > > > MOD的NBT数据还是无法保存，放进物品栏后经常性的丢失，有时又不会丢失。`
> > > > MOD部分代码如下:
> > > > ```
> > > > @Override
> > > >   public CompoundNBT getShareTag(ItemStack stack) {
> > > >     CompoundNBT shareTag = stack.getTag();
> > > >     if (shareTag == null) {
> > > >       shareTag = new CompoundNBT();
> > > >     }
> > > >     CompoundNBT storageTag = stack.getCapability(ModCapabilities.STORAGE)
> > > >         .map(IStorage::serializeNBT)
> > > >         .orElse(null);
> > > >     if (storageTag != null && !storageTag.isEmpty()) {
> > > >       shareTag.put("storage", storageTag);
> > > >     }
> > > >     return shareTag;
> > > >   }
> > > > 
> > > >   @Override
> > > >   public void readShareTag(ItemStack stack, @Nullable CompoundNBT nbt) {
> > > >     if (nbt != null && nbt.contains("storage", Constants.NBT.TAG_COMPOUND)) {
> > > >       stack.getCapability(ModCapabilities.STORAGE)
> > > >           .ifPresent(gun -> gun.deserializeNBT(nbt.getCompound("storage")));
> > > >     }
> > > >     super.readShareTag(stack, nbt);
> > > >   }
> > > > ```
> > > 
> > > 
> > > 你说的这些和这个问题没有关联。什么 mod，怎么复现
> > 
> > 
> > MOD: Crafting-Dead([https://github.com/nexusnode/crafting-dead)，将物品放入这个MOD的背心内，再拿出放到物品栏随意移动几次，其中的存储物品的NBT数据就会消失。（单人模式下没有这个问题）](https://github.com/nexusnode/crafting-dead)%EF%BC%8C%E5%B0%86%E7%89%A9%E5%93%81%E6%94%BE%E5%85%A5%E8%BF%99%E4%B8%AAMOD%E7%9A%84%E8%83%8C%E5%BF%83%E5%86%85%EF%BC%8C%E5%86%8D%E6%8B%BF%E5%87%BA%E6%94%BE%E5%88%B0%E7%89%A9%E5%93%81%E6%A0%8F%E9%9A%8F%E6%84%8F%E7%A7%BB%E5%8A%A8%E5%87%A0%E6%AC%A1%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%84%E5%AD%98%E5%82%A8%E7%89%A9%E5%93%81%E7%9A%84NBT%E6%95%B0%E6%8D%AE%E5%B0%B1%E4%BC%9A%E6%B6%88%E5%A4%B1%E3%80%82%EF%BC%88%E5%8D%95%E4%BA%BA%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%B2%A1%E6%9C%89%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%89)
> 
> 我用 quark 的古卷和沉浸工程的钻头试了一下，无法复现

我使用的是2.18 19点构建的版本，这个MOD中所有使用NBT存储物品(share tag?)数据的都可以复现。

**Comment by IzzelAliz** [comment]
在最新版中修复。

如果仍能复现请二分找出导致的mod/插件
