### ISSUE TITLE
Mixin错误

### ISSUE THREAD

**Issue by LinRanAstra** [IzzelAliz/Arclight#1433]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.21-1.0.0-SNAPSHOT-b3349e9

### Java 版本 | 操作系统

系统：win11 23H2 java：openjdk version "21.0.3.0.3" 2024-04-16

### 相关 Mod/插件 的名称及版本

```raw
fabric-api-0.100.1+1.21.jar
MagicLib-mc1.21.0-fabric-0.8.576-stable.jar
fabric-carpet-1.21-1.4.147+v240613.jar
```

### 错误描述

可能是Mixin相关的问题，我并不是专业的开发者，并不确定

### 复现步骤

1. 使用arclight-fabric-1.21-1.0.0-SNAPSHOT版本
2. 安装：
fabric-api-0.100.1+1.21.jar
MagicLib-mc1.21.0-fabric-0.8.576-stable.jar
fabric-carpet-1.21-1.4.147+v240613.jar
3个fabric mod
3.启动服务器

### 报错信息

https://mclo.gs/kjuRlAn

**Comment by qyl27** [comment]
日志显示此问题和 carpet-tis-addition 模组有关，而非 Arclight
