### ISSUE TITLE
[Request] Please update Neoforge

### ISSUE THREAD

**Issue by TheRealM18** [IzzelAliz/Arclight#1443]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21-1.0.0-SNAPSHOT

### OS & Java versions

OS: Linux Java 21

### Plugins and Mods

```raw
none
```

### Description

Could you update the neoforge to 148 or later, as time of this statement that was the highest.

**Comment by qyl27** [comment]
Fixed.
