### ISSUE TITLE
服务器崩溃

### ISSUE THREAD

**Issue by 3269199948** [IzzelAliz/Arclight#145]
### 我正在运行

* **Arclight** arclight-forge-1.16-1.0.11

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [jdk 1.8.0_271] 

* **操作系统** [Centos7.5]

* **插件列表** leanroomGenerator, LuckPerms, PlaceholderAPI, HolographicDisplays, Vault, Multiverse-Core, LagAssist, WorldEdit, ChestCommands, Essentials, EssentialsProtect, EssentialsChat, TAB, EssentialsSpawn, WorldGuard, CoreProtect, WorldEditSUI, Residence, BanItem, AuthMe

* **Mod 列表** minecraft forge-1.16.4-35.1.29-server.jar : minecraft (1.16.4) - 1
• mods_folder [mod][工业先锋]industrial-foregoing-1.16.4-3.2.8.2-6b5c95b.jar : industrialforegoing (3.2.8.2) - 1
• mods_folder [mod][集成动力前置]CyclopsCore-1.16.4-1.11.0.jar : cyclopscore (1.11.0) - 1
• mods_folder [mod][集成动力前置]CommonCapabilities-1.16.4-2.5.5.jar : commoncapabilities (2.5.5) - 1
• mods_folder [mod][星辉魔法]astralsorcery-1.16.4-1.13.9.jar : astralsorcery (1.16.4-1.13.9) - 1
• mods_folder [mod][工业先锋前置]titanium-1.16.4-3.2.5.jar : titanium (3.2.5) - 1
• mods_folder [mod][沉浸工程]ImmersiveEngineering-1.16.4-4.1.2-129.jar : immersiveengineering (1.16.4-4.1.2-129) - 1
• mods_folder [mod][环境科技前置]valkyrielib-1.16.4-3.0.6.1.jar : valkyrielib (3.0.6.1) - 1
• mods_folder [mod][皮肤]CustomSkinLoader_Forge-14.13-SNAPSHOT-199.jar : customskinloader (14.13-SNAPSHOT-199) - 1
• mods_folder jei-1.16.4-7.6.1.65.jar : jei (7.6.1.65) - 1
• mods_folder [mod][植物魔法]Botania-1.16.4-411.jar : botania (1.16.4-411) - 1
• mods_folder [mod][通用机械]Mekanism-1.16.4-10.0.19.446.jar : mekanism (10.0.19) - 1
• mods_folder [mod][环境科技前置]envirocore-1.16.4-3.0.6.0.jar : envirocore (3.0.6.0) - 1
• mods_folder [mod][星辉魔法-植物魔法前置]curios-forge-1.16.4-4.0.3.5.jar : curios (1.16.4-4.0.3.5) - 1
• mods_folder [mod][帕秋莉手册-植物魔法前置]Patchouli-1.16.4-48.jar : patchouli (1.16.4-48) - 1
• mods_folder [mod][集成动力]IntegratedDynamics-1.16.4-1.4.0.jar : integrateddynamics (1.4.0) - 2
• mods_folder [mod][环境科技]envirotech-1.16.4-3.0.6.1.jar : envirotech (3.0.6.0) - 1
• mods_folder [mod][应用能源2]appliedenergistics2-8.1.0.jar : appliedenergistics2 (8.1.0) - 1
• mods_folder [mod][储物抽屉]StorageDrawers-1.16.3-8.2.1.jar : storagedrawers (8.2.1) - 1
• mods_folder [mod][集成管道]IntegratedTunnels-1.16.4-1.6.16.jar : integratedtunnels (1.6.16) - 2
• mods_folder [mod][建筑小帮手充电]charginggadgets-1.3.0.jar : charginggadgets (1.3.0) - 1
• mods_folder [mod][建筑小帮手]buildinggadgets-1.16.4-3.7.3.jar : buildinggadgets (3.7.3) - 1
• mods_folder [mod][吸血鬼-血族传说]Vampirism-1.16.4-1.7.3.jar : vampirism (1.7.3) - 2
• mods_folder [mod][吸血鬼联动]VampirismIntegrations-1.16.4-1.5.0.jar : vampirism_integrations (1.5.0) - 1
• mods_folder [mod][星辉魔法前置]observerlib-1.16.4-1.5.1.jar : observerlib (1.16.4-1.5.1) - 1
• mods_folder [mod][合成前置]JEITweaker-1.16.5-1.0.1.11.jar : jeitweaker (1.0.1.11) - 1
• arclight arclight-forge-1.16-1.0.11.jar : arclight (1.16.4-1.0.11-daf16fd) - 1
• mods_folder [mod][合成]CraftTweaker-1.16.5-7.1.0.108.jar : crafttweaker (7.1.0.108) - 1
• mods_folder [mod][沉浸原油]ImmersivePetroleum-1.16.4-3.1.0-2.jar : immersivepetroleum (3.1.0-2) - 1
• maven_libs forge-1.16.4-35.1.29-universal.jar : forge (35.1.29) - 1
• mods_folder [mod][CoFH核心-热力革新前置]cofh_core-1.16.3-1.1.6.jar : cofh_core (1.1.6) - 1
• mods_folder [mod][热力基本-热力革新前置]thermal_foundation-1.16.3-1.1.6.jar : thermal (1.1.6) - 1
• mods_folder [mod][热力革新]thermal_innovation-1.16.3-1.1.7.jar : thermal_innovation (1.1.7) - 1
• mods_folder [mod][血魔法2]BloodMagic-1.16.3-3.0.6-11.jar : bloodmagic (1.16.3-3.0.6-11) - 1
• mods_folder [mod][精致存储]refinedstorage-1.9.11.jar : refinedstorage (1.9.11) - 1
• mods_folder [mod][动态环绕]DynamicSurroundings-1.16.4-4.0.3.5.jar : dsurround (1.16.4-4.0.3.5) - 4

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 猜测，数字矿机，但作者已修复这个问题

**可在 Forge 复现** [是]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
https://pastebin.com/DYh1P4na

**Comment by IzzelAliz** [comment]
请更新

**Comment by 3269199948** [comment]
> 请更新

更新mod吗

**Comment by IzzelAliz** [comment]
Arclight，不然是啥呢，更到最新的构建

1.16.5 可以加载 1.16.4 的 mod，客户端也是通用的

**Comment by 3269199948** [comment]
> Arclight，不然是啥呢，更到最新的构建
> 
> 1.16.5 可以加载 1.16.4 的 mod，客户端也是通用的

谢谢，还有个问题，PlotSquaredv5 也不行（至少在）arclight-forge-1.16-1.0.11不行

**Comment by IzzelAliz** [comment]
> 
> 
> > Arclight，不然是啥呢，更到最新的构建
> > 1.16.5 可以加载 1.16.4 的 mod，客户端也是通用的
> 
> 谢谢，还有个问题，PlotSquaredv5 也不行（至少在）arclight-forge-1.16-1.0.11不行

开新的 issue 说

**Comment by 3269199948** [comment]
> > > Arclight，不然是啥呢，更到最新的构建
> > > 1.16.5 可以加载 1.16.4 的 mod，客户端也是通用的
> > 
> > 
> > 谢谢，还有个问题，PlotSquaredv5 也不行（至少在）arclight-forge-1.16-1.0.11不行
> 
> 开新的 issue 说

好的我先用新版试试
