### ISSUE TITLE
Archlight fails to launch 1.21.1

### ISSUE THREAD

**Issue by LabsZero** [IzzelAliz/Arclight#1453]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

OS: Windows 11 JDK21.0.4

### Plugins and Mods

```raw
None
```

### Description

When attempting to launch the Arclight server, the server fails to start due to an InvalidInjectionException in the CropBlockMixin.

### Step to reproduce
Launch archlight let it download files and see errors.
_No response_

### Logs

[latest.log](https://github.com/user-attachments/files/16581192/latest.log)

**Comment by qyl27** [comment]
Fixed by c1c0349 .
