### ISSUE TITLE
植物生长时被mod监听会抛出Exception caught during firing event: null

### ISSUE THREAD

**Issue by FierceManul** [IzzelAliz/Arclight#146]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.12-SNAPSHOT-bcf3f33] 

* **你确认所有Mod都安装了依赖** [是]

* **Java** [1.8.0_271]

* **操作系统** [win10 1903]

* **插件列表**
空

* **Mod 列表** 
? mods_folder endportalrecipe_1.16.4-2.1.jar : endportalrecipe (2.1) - 1
? mods_folder woot-1.16.4-1.0.3.0.jar : woot (1.16.4-1.0.3.0) - 1
? mods_folder jei-1.16.4-7.6.1.65.jar : jei (7.6.1.65) - 1
? mods_folder ChineseWorkshop-1.16.3-3.2.0.jar : chineseworkshop (3.2.0) - 1
? mods_folder Kiwi-1.16.3-3.4.1.jar : kiwi (3.4.1) - 1
? mods_folder Mekanism-1.16.4-10.0.18.445.jar : mekanism (10.0.18) - 1
? mods_folder mcw-windows-1.0.2-mc1.16.4.jar : mcwwindows (1.0.2) - 1
? mods_folder caelus-forge-1.16.4-2.1.0.2.jar : caelus (1.16.4-2.1.0.2) - 1
? mods_folder rsgauges-1.16.4-1.2.6.jar : rsgauges (1.2.6) - 1
? mods_folder pitg-1.16.3-1.4.1.jar : pitg (1.16.3-1.4.1) - 1
? mods_folder Waystones_1.16.3-7.3.1.jar : waystones (7.3.1) - 1
? mods_folder ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar : forgeendertech (7.0.9.0) - 1
? mods_folder AdFinders-1.16.4-5.0.4.0-build.0027.jar : adfinders (5.0.4.0) - 1
? mods_folder Clumps-6.0.0.13.jar : clumps (6.0.0.13) - 1
? mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
? mods_folder Placebo-1.16.3-4.3.3.jar : placebo (4.3.3) - 1
? mods_folder dankstorage-3.14.jar : dankstorage (3.14) - 1
? mods_folder AdHooks-1.16.4-6.1.2.0-build.0027.jar : adhooks (6.1.2.0) - 1
? mods_folder engineerstools-1.16.4-1.1.2.jar : engineerstools (1.1.2) - 1
? mods_folder DungeonCrawl-1.16.3-2.2.4.jar : dungeoncrawl (2.2.4) - 1
? mods_folder Bookshelf-1.16.4-9.3.18.jar : bookshelf (9.3.18) - 1
? mods_folder buildinggadgets-1.16.4-3.7.3.jar : buildinggadgets (3.7.3) - 1
? mods_folder simpleplanes-1.16.3-3.2.0.3.jar : simpleplanes (1.16.3-3.2.0.3) - 1
? mods_folder ForgivingVoid_1.16.3-5.2.0.jar : forgivingvoid (5.2.0) - 1
? mods_folder mcw-doors-1.0.1fix-mc1.16.4.jar : mcwdoors (1.0.1) - 1
? mods_folder LightingWand-1.16.4-1.7.3.jar : lightingwand (1.7.3) - 1
? mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
? mods_folder [已修改]mapperbase-1.16.4-2.3.0.0.jar : mapperbase (1.16.4-2.3.0.0) - 1
? mods_folder MekanismGenerators-1.16.4-10.0.18.445.jar : mekanismgenerators (10.0.18) - 1
? mods_folder dismountentity_1.16.4-1.2.jar : dismountentity (1.2) - 1
? mods_folder mininggadgets-1.7.1.jar : mininggadgets (1.7.1) - 1
? mods_folder ImmersivePetroleum-1.16.4-3.1.0-2.jar : immersivepetroleum (3.1.0-2) - 1
? maven_libs forge-1.16.5-36.0.1-universal.jar : forge (36.0.1) - 1
? mods_folder PassthroughSigns-1.16.4-2.3.7.jar : passthroughsigns (1.16.4-2.3.7) - 1
? mods_folder absentbydesign-1.16.4-1.3.1.jar : absentbydesign (1.16.4-1.3.1) - 1
? mods_folder conduitsprdrowned_1.16.4-1.1.jar : conduitsprdrowned (1.1) - 1
? minecraft forge-1.16.5-36.0.1-server.jar : minecraft (1.16.5) - 1
? mods_folder mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
? mods_folder repurposed_structures-1.16.4-2.3.3.jar : repurposed_structures (1.16.4-2.3.3) - 1
? mods_folder embellishcraft-1.16.4-3.3.0.0.jar : embellishcraft (1.16.4-3.3.0.0) - 1
? mods_folder ToolBelt-1.16.3-1.15.2.jar : toolbelt (1.15.2) - 1
? mods_folder ImmersiveEngineering-1.16.4-4.1.2-129.jar : immersiveengineering (1.16.4-4.1.2-129) - 1
? mods_folder BiomesOPlenty-1.16.4-13.0.0.427-universal.jar : biomesoplenty (1.16.4-13.0.0.427) - 1
? mods_folder MekanismAdditions-1.16.4-10.0.18.445.jar : mekanismadditions (10.0.18) - 1
? mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
? mods_folder pamhc2crops-1.16.3-1.0.1.jar : pamhc2crops (version) - 1
? mods_folder mcw-trapdors-1.0.0-mc1.16.4.jar : mcwtrpdoors (1.0.0) - 1
? mods_folder forbidden_arcanus-1.16.4-1.0.0.jar : forbidden_arcanus (1.16.4-1.0.0) - 1
? mods_folder AdLods-1.16.4-4.1.3.0-build.0034.jar : adlods (4.1.3.0) - 1
? mods_folder structure_safe_java_eleven-1.0.jar : structure_safe_java_eleven (1.0) - 1
? mods_folder movingelevators-1.2.31a-mc1.16.4.jar : movingelevators (1.2.31a) - 1
? mods_folder towers_of_the_wild-1.16.4-2.0.1.jar : towers_of_the_wild (1.16.4-2.0.1) - 1
? mods_folder simplylight-1.16.4-1.1.1.jar : simplylight (1.16.4-1.1.1) - 1
? mods_folder Botania-1.16.4-410.jar : botania (1.16.4-410) - 1
? mods_folder easy_villagers-1.16.4-1.1.20.jar : easy_villagers (1.16.4-1.1.20) - 1
? mods_folder curios-forge-1.16.4-4.0.3.3.jar : curios (1.16.4-4.0.3.3) - 1
? mods_folder Patchouli-1.16.4-48.jar : patchouli (1.16.4-48) - 1
? mods_folder pamhc2foodcore-1.16.3-1.0.0.jar : pamhc2foodcore (version) - 1
? mods_folder collective-1.16.4-1.53.jar : collective (1.53) - 1
? mods_folder cyclepaintings_1.16.4-1.4.jar : cyclepaintings (1.4) - 1
? mods_folder AutoRegLib-1.6-47.jar : autoreglib (1.6-47) - 1
? mods_folder Quark-r2.4-291.jar : quark (r2.4-291) - 1
? mods_folder Apotheosis-1.16.3-4.4.1.jar : apotheosis (4.4.1) - 1
? mods_folder StorageDrawers-1.16.3-8.2.1.jar : storagedrawers (8.2.1) - 1
? mods_folder Fertilization_1.16.3-5.2.0.jar : fertilization (5.2.0) - 1
? mods_folder EnigmaticLegacy-2.10.3.jar : enigmaticlegacy (2.10.3) - 1
? mods_folder TheAbyss+2.0.0+1.16.4.jar : theabyss (2.0.0) - 1
? mods_folder MekanismTools-1.16.4-10.0.18.445.jar : mekanismtools (10.0.18) - 1
? mods_folder mcws-roofs-2.0.0-mc1.16.4.jar : mcwroofs (2.0.0) - 1
? mods_folder furniture-7.0.0-pre19-1.16.3.jar : cfm (7.0.0-pre19) - 1
? mods_folder engineersdecor-1.16.4-1.1.5.jar : engineersdecor (1.1.5) - 1
? mods_folder curiouselytra-forge-1.16.3-4.0.0.1.jar : curiouselytra (1.16.3-4.0.0.1) - 1
? mods_folder mcw-furniture-2.0.0-mc1.16.4.jar : mcwfurnitures (2.0.0) - 1
? arclight server.jar : arclight (1.16.5-1.0.12-SNAPSHOT-bcf3f33) - 1
? mods_folder forge-1.16.4-geckolib-3.0.0.jar : geckolib3 (3.0.0) - 1
? mods_folder ars_nouveau-1.16.4-1.11.2.jar : ars_nouveau (1.11.2) - 1

### 错误描述

ars 这个 mod 的 法力凝聚器 会检测检测附近农作物生长时产生魔力，当农作物生长时会抛出异常并崩服。
经过测试，单人和forge服不会蹦，arc服去掉所有插件会蹦。

### 重现步骤

进入服务器后，放置法力凝聚器。
在周围种农作物。
农作物生长后，崩溃。

**可在 Forge 复现** [否]
**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

latest.log
https://paste.ubuntu.com/p/H8z6sKp7HW/

Crash Report
https://paste.ubuntu.com/p/pn6nggvp5B/

[debug.log](https://github.com/IzzelAliz/Arclight/files/5899314/debug.log)

**Comment by IzzelAliz** [comment]
请报告给mod作者

我认为纯 forge 端仍然会出现该问题，你可能需要测试植物魔法的田园康乃馨自然生长。如果你测试之后仍然发现纯 forge 端无法复现，请再来回复。
