### ISSUE TITLE
How to use plugins in Fabric 1.21 version?

### ISSUE THREAD

**Issue by pil0lo** [IzzelAliz/Arclight#1462]
### I have confirmed that ...

- [X] Arclight is up to date
- [ ] all dependencies are installed
- [X] all plugins and mods are up to date
- [ ] unable to reproduce in Spigot
- [ ] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21-1.0.0-SNAPSHOT / arclight-fabric-1.21-1.0.0-SNAPSHOT

### OS & Java versions

java version "22.0.1" 2024-04-16 Java(TM) SE Runtime Environment (build 22.0.1+8-16) Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

### Plugins and Mods

```raw
arclight-fabric-1.21-1.0.0-SNAPSHOT
arclight-neoforge-1.21-1.0.0-SNAPSHOT
Fabric-API-1.21
```

### Description

Someone said that if you put this mod in, you can use plugins in Fabric.
Is that right???
If you can use plugins, how do you use them??
Even if you put the mod in, it doesn't seem to be recognized?
This is Fabric version 1.21.
![1](https://github.com/user-attachments/assets/5585af0b-1eee-479c-bd14-5da8e37f7cf2)

**Comment by qyl27** [comment]
You should use arclight-fabric.jar as same as the fabric-server-launch.jar.
