### ISSUE TITLE
实体出现错误

### ISSUE THREAD

**Issue by appleLPG** [IzzelAliz/Arclight#1468]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.21.1-1.0.0-SNAPSHOT-c1c0349

### Java 版本 | 操作系统

21.0.3

### 相关 Mod/插件 的名称及版本

```raw
没有
```

### 错误描述

实体无法交互,无法穿过碰撞箱,kill @e无法杀死任何实体，该bug实体包括玩家本身

### 复现步骤

正常进入游戏就触发

### 报错信息

没有报错

**Comment by wuweidmw** [comment]
我也遇到了，neoforge的

**Comment by qyl27** [comment]
先修了伤害问题，推挤的问题正在调查，而且发现1.21时候就是坏的（
