### ISSUE TITLE
The hunger doesn't work

### ISSUE THREAD

**Issue by Wladi122** [IzzelAliz/Arclight#1469]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

java version "22.0.2" 2024-07-16 Java(TM) SE Runtime Environment (build 22.0.2+9-70) Java HotSpot(TM) 64-Bit Server VM (build 22.0.2+9-70, mixed mode, sharing)

### Plugins and Mods

```raw
none
```

### Description

no matter how much you eat, the hunger bar doesn't increase

**Comment by Laurentzius** [comment]
Same problem

**Comment by ghost** [comment]
I have an unusual way of solving the problem, but it will not suit everyone.
You can install this mod: https://modrinth.com/mod/nohunger
It removes the hunger bar, and it seems like XP is restored by any food
