### ISSUE TITLE
1.21 Fabric server closes immediately

### ISSUE THREAD

**Issue by pil0lo** [IzzelAliz/Arclight#1470]
### I have confirmed that ...

- [X] Arclight is up to date
- [ ] all dependencies are installed
- [ ] all plugins and mods are up to date
- [ ] unable to reproduce in Spigot
- [ ] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21-1.0.0-SNAPSHOT

### OS & Java versions

java version "22.0.1" 2024-04-16 Java(TM) SE Runtime Environment (build 22.0.1+8-16) Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

### Plugins and Mods

```raw
No plugins, no mods
```

### Description

Even when I remove all mods and plugins and do not install anything, when I open the server, an error message pops up and the server closes immediately without opening.

### Logs

[latest.log](https://github.com/user-attachments/files/16782507/latest.log)

**Comment by qyl27** [comment]
Please have a try with the newest build for 1.21.1 in GitHub Actions.
