### ISSUE TITLE
1.19.2 ver forge 3.3.8 >> 3.4.0+

### ISSUE THREAD

**Issue by Draiit12** [IzzelAliz/Arclight#1472]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

forge 1.19.2 43.3.8

### OS & Java versions

java17~19

### Plugins and Mods

```raw
Epicfight+Customnpc
```

### Description

You must use this latest mode.
But it is not supported because the Forge version is low. Please..
I need your help.
If you solve it, I will love you forever.

**Comment by Tr3yWay996** [comment]
So?

**Comment by qyl27** [comment]
Duplicated of #1372
