### ISSUE TITLE
Handling character death

### ISSUE THREAD

**Issue by Gadifane** [IzzelAliz/Arclight#1473]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-b3349e9

### OS & Java versions

openjdk version "22.0.2" 2024-07-16 OpenJDK Runtime Environment Temurin-22.0.2+9 (build 22.0.2+9) OpenJDK 64-Bit Server VM Temurin-22.0.2+9 (build 22.0.2+9, mixed mode, sharing)

### Plugins and Mods

```raw
none
```

### Description

When a character dies, the server has huge issues. The character respawns, but it unable to affect the world. When they log out, they typically can't join back in..

### Step to reproduce

1. Character death
2. Respawn

### Logs

[latest.log](https://github.com/user-attachments/files/16801824/latest.log)

**Comment by Laurentzius** [comment]
![image](https://github.com/user-attachments/assets/a384a54a-ee58-4e22-adb6-086cb715d6eb)
![image](https://github.com/user-attachments/assets/becc8a42-8e2a-4555-bf46-405e93339112)
Same problem

**Comment by ItsRedCreeper** [comment]
Same problem too

**Comment by Stormcruzerlore** [comment]
i  thought this was an issue with a mod or plugin conflict so   made a fresh  server with no mods or plugins and yea same issue  game is not playable  with this bug also i was on 1.21 with my arclight install  garbbed the latest on the github at the time of posting ths comment

**Comment by chaseyrt** [comment]
![image](https://github.com/user-attachments/assets/5174523e-51eb-4cb1-bb40-5ac212f07bc0)

Also having this error. The first line seems to be the issue. I'm _assuming_ it's trying and failing to call the player spawn/respawn class.
[https://maven.fabricmc.net/docs/yarn-1.17-rc1+build.1/net/minecraft/network/packet/c2s/play/ClientStatusC2SPacket.Mode.html](url)

**Comment by qyl27** [comment]
Outdated version.  
It was already fixed on Jul 2, 2024 by c47e085.  
You have 5 versions behind.  
The newest version of the active branch is always in GitHub Actions.
