### ISSUE TITLE
0 clear instructions on installation and implementation...

### ISSUE THREAD

**Issue by johnwvin** [IzzelAliz/Arclight#1474]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT

### OS & Java versions

ubuntu

### Plugins and Mods

```raw
zero instructions on how to implement this...
```

### Description

you should have detailed steps on what to do.. install neoforge first and then arclight in the same directory? just place arclight jar in mods folder and create plugin folder? install arclight in folder inside mods folder? what am i supposed to do with your jar file to use forge mods and bukkit plugins together? install arclight and then neoforge inside of arclight dir? or the arclight mods folder?

**Comment by Laurentzius** [comment]
install arclight and rename to server.jar and start your server
it's all

**Comment by johnwvin** [comment]
Ok I was curious why the installation gave me a forge installer.

**Comment by johnwvin** [comment]
Also no plugin folder was created.
