### ISSUE TITLE
can't startup server

### ISSUE THREAD

**Issue by Mvkweb** [IzzelAliz/Arclight#1480]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Trials/1.0.3

### OS & Java versions

Ubuntu 22 & java 21

### Plugins and Mods

```raw
none since i can't even start the server by default.
```

### Description

so im trying to run the server with pterodactyl i uploaded the jar and it just does not wanna launch.

### Logs

https://hastebin.com/share/arutafiwez.php

**Comment by qyl27** [comment]
It was caused by the Forge Installer not being able to resolve `authserver.mojang.com`, that's a problem with your network connection, please try to install Forge `1.20.1-47.2.16` manually and launch Archlight.
