### ISSUE TITLE
启动为模组的维度创建符号链接配置报错

### ISSUE THREAD

**Issue by vicuna-main** [IzzelAliz/Arclight#1481]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-neoforge-1.21.1-1.0.0-SNAPSHOT.jar

### Java 版本 | 操作系统

系统：Windows 11 专业工作站版 23H2 x64 Java：openjdk version "21.0.4" 2024-07-16 LTS

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

开启功能后，控制台红色报错。

### 复现步骤

1.设置symlink-world为true
2.启动服务器

### 报错信息

[latest.log](https://github.com/user-attachments/files/16987867/latest.log)

**Comment by qyl27** [comment]
请在调整服务器配置前仔细阅读注释和文档。  
https://github.com/IzzelAliz/Arclight/wiki/World-Symlink#%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%B2%A1%E6%9C%89%E6%89%80%E9%9C%80%E7%9A%84%E7%89%B9%E6%9D%83
