### ISSUE TITLE
Where do I get fabric 1.21 ver only?

### ISSUE THREAD

**Issue by pil0lo** [IzzelAliz/Arclight#1486]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.21

### OS & Java versions

win

### Plugins and Mods

```raw
next
```

### Description

Where do I get version 1.21 for fabric? I can't see it.

**Comment by qyl27** [comment]
We have a download badge to redirect to the download page in our README, please read it before asking.
