### ISSUE TITLE
README Where exactly do I download it?

### ISSUE THREAD

**Issue by pil0lo** [IzzelAliz/Arclight#1489]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

arclight-fabric-1.21.1-1.0.0-SNAPSHOT

### Plugins and Mods

```raw
arclight-fabric-1.21.1-1.0.0-SNAPSHOT
```

### Description

You keep pressing quit.
Can you at least give me a link instead of downloading from README??
I think I entered it correctly, but I can't see it.
I entered it with 1.21 written on it?

![1](https://github.com/user-attachments/assets/60525ddc-b61f-4848-883d-056b859a7dfd)
![2](https://github.com/user-attachments/assets/ee7e1659-43d5-4e8f-9ab8-15c618ab30d8)
![3](https://github.com/user-attachments/assets/dd6d32b2-2890-4427-a89a-dc771b66e3bf)

**Comment by qyl27** [comment]
Look at the calendar symbol in the actions list page, the top line is the latest.  
And you can still reply a closed issue, but not a new issue. :(

**Comment by pil0lo** [comment]
I can't find it even if I look for it.
Where exactly should I look for it?
Isn't it supposed to go to the place where the photo was uploaded?
1.21 Fabric No matter what I do, I just get an error.

**Comment by qyl27** [comment]
I don't understand why you can't see the first line in https://github.com/IzzelAliz/Arclight/actions?query=branch%3AFeudalKings.  
<img width="762" alt="1" src="https://github.com/user-attachments/assets/4f360ba1-aef7-4a1f-8de8-e4d9dbaaf2de">

**Comment by pil0lo** [comment]
1.21.1 Are you talking about Fabric?? If you run it with the mod installed, an error message will pop up and it won't run.

If you run it by attaching the previously installed mod, an error message will appear and it will not run.

Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCaptureWARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future releaseWARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future releaseWARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future releaseWARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future releaseWARN StatusConsoleListener Advanced terminal features are not available in this environment12:03:32 | Loading Minecraft 1.21.1 Arclight arclight-1.21.1-1.0.0-SNAPSHOT-b04cca7 with Fabric Loader 0.16.2[m12:03:33 | Mod resolution failed[m12:03:33 | Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED animal_feeding_trough 1.1.1+1.21 {depends minecraft @ [1.21]}, ROOT_FORCELOAD_SINGLE animal_feeding_trough 1.1.1+1.21][m12:03:33 | Reason: [HARD_DEP animal_feeding_trough 1.1.1+1.21 {depends minecraft @ [1.21]}, HARD_DEP ante 1.2 {depends minecraft @ [1.21]}, HARD_DEP better_craftables 1.6.0 {depends minecraft @ [1.21]}, HARD_DEP entityculling 1.6.6 {depends minecraft @ [1.21]}, HARD_DEP expore 1.21-0.1 {depends minecraft @ [1.21]}, HARD_DEP forgeconfigapiport 21.0.8 {depends minecraft @ [1.21]}, HARD_DEP lithium 0.12.7 {depends minecraft @ [1.21]}, HARD_DEP mine-spawners 1.0 {depends minecraft @ [1.21]}, HARD_DEP more_babies 2.0.0 {depends minecraft @ [1.21]}, HARD_DEP tiered 1.0.2 {depends minecraft @ [1.21]}]12:03:33 | SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, libipn, modmenu, fabric-screen-api-v1, fabric-renderer-indigo, commandkeys, no_nether_portal_overlay, worldplaytime, merchantmarkers, fabric-rendering-v0, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, tradeuses, healthindicatortxf, fabric-model-loading-api-v1, iris, inventoryhud, indium, fabric-client-tags-api-v1, inventoryprofilesnext, enhancedblockentities, autoclicker-fabric, fabric-blockrenderlayer-v1, sodium, fabric-renderer-registries-v1, cat_jam, holdthatchunk, nvidium]12:03:33 | Fix: add [], remove [], replace [[minecraft 1.21.1] -> add:minecraft 1.21 ([[1.21,1.21]])][m12:03:33 | Incompatible mods found!net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with version 1.21.
More details:
	 - Mod 'Animal Feeding Trough' (animal_feeding_trough) 1.1.1+1.21 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Anvil Never Too Expensive' (ante) 1.2 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Better Craftables' (better_craftables) 1.6.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'EntityCulling' (entityculling) 1.6.6 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'ExpOre' (expore) 1.21-0.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Forge Config API Port' (forgeconfigapiport) 21.0.8 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Lithium' (lithium) 0.12.7 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'mine-spawners' (mine-spawners) 1.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'More Babies' (more_babies) 2.0.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Reforged' (tiered) 1.0.2 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.2.jar:?]
	at io.izzel.arclight.boot.fabric.application.Main_Fabric.main(Main_Fabric.java:33) [arclight-fabric-1.21.1-1.0.0-SNAPSHOT.jar:arclight-1.21.1-1.0.0-SNAPSHOT-b04cca7]
	at io.izzel.arclight.server.Launcher.main(Launcher.java:39) [arclight-fabric-1.21.1-1.0.0-SNAPSHOT.jar:arclight-1.21.1-1.0.0-SNAPSHOT-b04cca7]
[m

**Comment by qyl27** [comment]
Some fabric mods set their Minecraft version as `~1.21`, but 1.21 and 1.21.1 are compatible but they are overlooked, that is the issue of mods but not Arclight.  
Btw, NeoForge has an extra mark for that, but Fabric hasn't.  

You'd better to check updates of your mods.  
After my search on modrinth, I believe you have not updated for at least a month.

**Comment by pil0lo** [comment]
Even if I just put in a few mods, it immediately becomes an error..
I think I should just give up.
I tried to try again, but I keep getting errors...
There are too many mods, so it seems like I won't be able to catch all the errors..
