### ISSUE TITLE
Beacon crash server

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#1490]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 arclight-1.21.1-1.0.0-SNAPSHOT-2f61580

### OS & Java versions

JDK 21

### Plugins and Mods

```raw
Plugins (13): PL-Hide, PlaceholderAPI, ProjectKorra, spark, GSit, ViaVersion, BendingGUI, WorldsColor, Chatty, SkinsRestorer, Essentials, PlasmoVoice, TAB
Mods: (0)
```

### Description

Beacon crash server

### Logs

https://paste.ubuntu.com/p/rvv9Tn8YmP/

**Comment by Juan-MZ** [comment]
Greetings, the fix is available in 1.20.4?
