### ISSUE TITLE
Whisper/1.0.4 - Fabric 1.21 wrong fabric loader version issue

### ISSUE THREAD

**Issue by NicKnack819** [IzzelAliz/Arclight#1500]
Trying To boot a server using Structurify and Getting [Errors for wrong fabric loader version](https://mclo.gs/JME2XjE). which seems similar to the issue found below:

### Discussed in https://github.com/IzzelAliz/Arclight/discussions/1458

<div type='discussions-op-text'>

<sup>Originally posted by **Piopaw250168** August 18, 2024</sup>
Does it use Fabric Loader newer than 0.15.6? Some of mods I want to install on server require fabric version 0.15.11. Is it possible to have Aright with that fabric loader version?</div>

**Comment by qyl27** [comment]
Yes, it should be updated, but we currently lack the manpower to perform some maintenance.  
PR is welcome.

**Comment by NicKnack819** [comment]
> Yes, it should be updated, but we currently lack the manpower to perform some maintenance. PR is welcome.

Noticed I used the wrong version name as I sent the log from when I ended up trying the [FeudalKings](https://github.com/IzzelAliz/Arclight/releases/tag/FeudalKings%2F1.0.0-SNAPSHOT) for 1.21 after struggling with [Whisper](https://github.com/IzzelAliz/Arclight/releases/tag/Whisper%2F1.0.4) which had the same problem, I had already cleared the old logs out due to file space limitations... However while I'm not sure if it would work as a valid workaround but was eventually able to force it to retrieve and use the proper fabric loader version... 
If it helps anyone here's how I did this for the Feudal Kings version:
 1. Open/Unzip the jar's archive using a tool like 7-Zip (I just opened it since trying to rezip a jar was pain last time I tried it...)
 2. Copy the `installer.json` file from the `META-INF` directory to separate safe directory on your system
 3. Open it with something like Visual Studio Code.
    - Pro Tip: Using Visual Studio Code you can press `Alt Z` to enable the line wrap option to not have the single very lengthy line of code
 4. Find the part with the value of `"fabricLoader":"0.15.11"`
 5. Change the version part to the one you require like in my example: `"fabricLoader":"0.16.5"`
    -  Important Note: _Almost_ certain versions will need to be **_Higher_** then `0.15.11`, haven't tested lower versions but normally using latest is usually the best choice...
 6. Save the new copy of `installer.json` somewhere separate from the original copy incase something breaks
 7. Drag the new copy of `installer.json` into the `META-INF` directory and click confirm when prompted to overwrite the old one
 8. Make sure the archive has taken the newly changed file and then put the newly configured Arclight jar in your server directory 
 9. Finally set Server to use the newly configured Arclight file and Launch
 
Server should now use the newly set version with mostly no issues but as this is not full fix you never know... But it seems to work for me at this point in time. I will share details on any issues that arise with this method on my end though

**Comment by qyl27** [comment]
Yes, thank you for your information, it should work in most situations.  
Most mods didn't use the new features in newer fabric versions, it was just from the template.  
Btw, I have updated the loaders' version in d0dda85 .
