### ISSUE TITLE
Server works fine, still have some error messages

### ISSUE THREAD

**Issue by Hevnravn** [IzzelAliz/Arclight#1510]
### Discussed in https://github.com/IzzelAliz/Arclight/discussions/1509

<div type='discussions-op-text'>

<sup>Originally posted by **Hevnravn** October  2, 2024</sup>
Hi, I need some help fixing those errors. Here's a report of ChatGPT after the log analysis:

It seems that the log file contains some characters that are not supported by utf-8 encoding. I'm going to try reading the file using a different encoding to avoid this error.

​

In the log file you provided, it can be seen that the server is using Arclight version 1.20.1 with several mods. Here are some initial details that stand out:

Warnings about missing mods.toml files:
Some mod files, such as fmlcore-1.20.1-47.2.20.jar and javafmllanguage-1.20.1-47.2.20.jar, are showing warnings about missing mods.toml file. This could affect the proper functioning of mods.

Warnings about mixin reference maps:
Problems are reported when trying to load refmap.json files for several mods (handcrafted, SeedDelight, apexcore). While it is mentioned that this can be ignored in development environments, some mods may not be working as expected.

Loading multiple mods:
A significant list of mods are being loaded, such as biomesoplenty, botanypots, aquaculture, among others. Some mods may not be fully compatible with each other or the server version.

For further analysis, I will focus on looking for critical errors or severe warnings later in the log. I will review more lines to identify other possible issues.

​

Upon further review of the Minecraft server log file, I have found a few issues that might be relevant:

Additional warnings about missing "refmap" files:
Mods such as chiselsandbits and deeperdarker show similar warnings as seen above, indicating that certain reference files (refmap.json) cannot be loaded.

Classes not found:
The server shows several warnings related to missing classes:
PhantomRenderer (associated with the deeperdarker mod).
TargetFinder (associated with the bettercombat mod).

This suggests that these mods might have compatibility issues or errors in their configuration.

Possible causes of the issues:

Missing or corrupted mods: Some important mods or files might be corrupted or not installed correctly.
Incompatibility between mods: The large number of mods loaded could be causing conflicts, especially if some are not fully compatible with the server version.

Recommended next steps:

Check the installation of the mentioned mods (deeperdarker, bettercombat, etc.) and make sure they are complete and compatible with the version of Minecraft and Forge you are using.
Check mod dependencies: Some mods may require additional plugins that have not been loaded correctly.
Try temporarily disabling some mods to see if the server runs without errors and thus identify possible conflicts.

If you have other specific details of the server behavior, I can give you further recommendations.

​</div>

**Comment by qyl27** [comment]
Invalid issue, please provide logs and mod/plugin list.

**Comment by Hevnravn** [comment]
Mod List:
- aiimprovements 0.5.2
	- aquaculture 2.5.2
	- architectury 9.2.14
	- arclight 1.20.1-1.0.5-1a8925b
	- armorstatues 8.0.6
		|-- puzzlesaccessapi 8.0.7
		\-- puzzlesapi 8.1.4
	- attributefix 21.0.4
	- beautify 2.0.2
	- better_weaponry 1.0.0
	- biomesoplenty 18.0.0.592
	- bookshelf 20.2.13
	- botanypots 13.0.39
	- botanytrees 9.0.17
	- caelus 3.2.0+1.20.1
	- carryon 2.1.2.7
	- chillout 1.0.0
	- chiselsandbits 1.4.148
		\-- scena 1.0.103
	- chunksending 1.20.1-2.8
	- citadel 2.6.0
	- cloth_config 11.1.136
	- combatroll 1.3.3+1.20.1
	- commonnetworking 1.0.5-1.20.1
	- connectivity 1.20.1-5.6
	- crafttweaker 14.0.43
	- creativecore 2.12.15
	- cupboard 1.20.1-2.7
	- curios 5.10.0+1.20.1
	- daily_rewards 5.3.0
	- days_in_the_middle_ages 0.0.5
	- deeperdarker 1.3.2
	- difficult_caves 1.0.0
	- divine_weaponry 1.6.0
	- doggytalents 1.18.32
	- dragonitegear 0.2.0
	- dynview 2.3
	- epicfight 20.9.2
	- fallingleaves 2.1.0
	- fallingtree 4.3.4
	- fantasyfurniture 9.0.0
		|-- apexcore 10.0.0
		\-- commonality 7.0.0
	- farmersdelight 1.20.1-1.2.4
	- farsight_view 1.20.1-3.7
	- ferritecore 6.0.1
	- forge 47.2.20
	- framework 0.7.8
	- galosphere 1.20.1-1.4.1
	- geckolib 4.4.9
	- handcrafted 3.0.6
	- hookshot 1.20.1-1.0
	- icarus 2.10.0
		\-- mixinextras 0.3.5
	- iceandfire 2.1.13-1.20.1
	- impactful 20.8.3
	- inventorysorter 23.0.1
	- inwitched 2.5
	- itemproductionlib 1.0.2a
	- justleveling 1.7
	- leavesbegone 8.0.0
	- letmedespawn 1.3.2b
	- logprot 1.4
	- lootr 0.7.34.87
	- mca 7.5.19+1.20.1
	- mcwbridges 3.0.0
	- mcwdoors 1.1.1
	- mighty_mail 1.1.2
	- minecraft 1.20.1
	- modernfix 5.19.4+mc1.20.1
	- mythicmounts 20.1-7.4.2-forge
	- noseenotick 2.0.0-build.9999
	- nutritionalbalance 1.20-5.1.3
	- patchouli 1.20.1-84-FORGE
	- playeranimator 1.0.2-rc1+1.20
	- puzzleslib 8.1.23
	- realmrpg_skeletons 1.0.3
	- realtimemod 1.8.0
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.29
	- revampedpiles 0.3.0
	- seeddelight 1.20.1-0.1
	- sereneseasons 9.0.0.46
	- simple_weapons 1.4.4
	- simplebackups 1.20.1-3.1.7
	- simplecorinthium 1.2.2
	- simpleshops 1.2.2
	- skilltree 0.6.14a
	- slotmachinemod 1.1.5
	- smoothchunk 1.20.1-3.6
	- snuffles 1.0.7
	- structureessentials 1.20.1-3.4
	- sword_soaring 20.1.11.11
	- takesapillage 1.0.3
	- terrablender 3.0.1.7
	- theabyss 1.0.0
	- tia 1.20-1.1
	- tipsmod 12.1.8
	- tlskincape 1.32
	- travelersbackpack 9.1.16
	- unilib 1.0.2
	- variantvanillablocks 1.3.6
	- weaponmaster_ydm 4.2.3
	- wom 20.1.8.5.2
	- zillagersweararmor 1.20.1-1.4.0
	
	Plugins:
	Citizens-2.0.35-b3577
	CoreProtect-22.4
	EssentialsX-2.21.0-dev+115-6157668
	MarriageMaster
	OreAnnouncer-2.8.5
	Shopkeepers-2.19.0
	worldedit-bukkit-7.2.17
	worldguard-bukkit-7.0.9-dist
	WorldGuardExtraFlags
	
	
	
	Log:
[latest.log](https://github.com/user-attachments/files/17219327/latest.log)
