### ISSUE TITLE
[ 1.21.1 - Neoforge ]  无法正常跨世界

### ISSUE THREAD

**Issue by windy664** [IzzelAliz/Arclight#1512]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-neoforge-1.21.1-1.0.0-SNAPSHOT

### OS & Java versions

Java21

### Plugins and Mods

```raw
CMI MV
```

### Description

放一个地狱门，传送过去右键，或挖掘等动作均不正常

使用插件传送到其他维度也是 ，右键之后会恢复主世界的方块，即玩家无论如何传送实际上是在主世界上的

**Comment by luoxiawuchen** [comment]
https://github.com/IzzelAliz/Arclight/issues/1403
https://github.com/IzzelAliz/Arclight/issues/1452
以上两个issuse和当前这个应该可以归类为同一个bug，不仅限于neo，fabric存在相同问题

**Comment by windy664** [comment]
最新测试 : 原版传送无问题，但是就插件和mod的跨界传送有有问题。
![Uploading 49a182da9f69a286dac8b774c91ca8fd.png…]()
如图为 从地狱传送到earth世界并聊天，但显示还在地狱

**Comment by blank038** [comment]
看起来像是受到这段代码影响？移除后调试不会复现此问题。
https://github.com/IzzelAliz/Arclight/blob/35bf457aef2586d1c7a54c592bcfb590243ab6e9/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/server/management/PlayerListMixin.java#L268-L272

**Comment by qyl27** [comment]
> 看起来像是受到这段代码影响？移除后调试不会复现此问题。
> 
> https://github.com/IzzelAliz/Arclight/blob/35bf457aef2586d1c7a54c592bcfb590243ab6e9/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/server/management/PlayerListMixin.java#L268-L272

Thanks a lot.
