### ISSUE TITLE
C2ME Error

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#1523]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21.1-1.0.0-SNAPSHOT-d0dda85

### OS & Java versions

JDK 21

### Plugins and Mods

```raw
Plugins (13): LuckPerms, SurvivalInvisiframes, Essentials, PL-Hide, PlaceholderAPI, AFKPlus, AntiDisconnectSpam, TAB, spark, GSit, ChatEx, AFKPlusPAPI, WorldsColor
Mods: Only optimization and generation wold
```

### Description

C2ME Error
I remember you wrote that archlight does not support optimizing mods, but without them, unfortunately, it is impossible to use fabric; more than 10 players cannot be launched on the server.

### Logs

https://paste.ubuntu.com/p/HKgq89kQ83/

**Comment by qyl27** [comment]
Arclight has no promise in working with optimization mods, we can try to make it compatible, but low priority.  
If you want to host a modded server, a powerful machine is important.

**Comment by qyl27** [comment]
Maybe same issue with #1496

**Comment by ghost** [comment]
Yes, I have already figured out this problem
