### ISSUE TITLE
Implementation to forge 47.3.0

### ISSUE THREAD

**Issue by ProyectISBO2024** [IzzelAliz/Arclight#1526]
Hey i want to suggest the update of forge 47.2.20 to forge 47.3.0, that's because a lot of new mods require the most recent but stable version, and thats not the one who arclight is using, atleast not on 1.20.1.

i hope that could be possible and a sooner or bit later change.

**Comment by qyl27** [comment]
Yes, it should be updated, but we now lack the manpower to maintain every version, PR is always welcome!

**Comment by qyl27** [comment]
Updated to 47.3.11.

**Comment by bbobbogi** [comment]
When I tested with this commit, the following issues reappeared.

#1014 #1015

@qyl27

**Comment by qyl27** [comment]
> When I tested with this commit, the following issues reappeared.
> 
> #1014 #1015
> 
> @qyl27

Ah, yes, sorry for my mistake. A new fix commited.
