### ISSUE TITLE
Arclight fabric loader out of date

### ISSUE THREAD

**Issue by nulllexx** [IzzelAliz/Arclight#1528]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-b3349e9

### OS & Java versions

exaroton

### Plugins and Mods

```raw
Architectury-API-Mod-Fabric-1.21.jar


cloth-config-15.0.140-fabric.jar


CreativeCore_FABRIC_v2.12.9_mc1.21.jar


fabric-api-0.102.0+1.21.jar


FallingTree-1.21-1.21.0.8.jar


framework-fabric-1.21-0.9.0.jar


jei-1.21.1-fabric-19.20.0.241.jar


refurbished_furniture-fabric-1.21-1.0.6.jar


replaymod-1.21-2.6.19.jar


voicechat-fabric-1.21.1-2.5.23.jar


waterframes-FABRIC-mc1.21-v2.0.12a.jar


watermedia-2.0.74.jar
```

### Description

Fabric loader on Feudal Kings is too old, is there a way to change it? Itis 0.5.11 and I need 0.16.5

### Step to reproduce

1. Start the server
2. It will crash

### Logs

https://mclo.gs/9VDl8MY

**Comment by qyl27** [comment]
Have you really confirmed that **Arclight is up to date**?  
The newest version is 97e6107.
