### ISSUE TITLE
The server enters my commands incorrectly, and the console freezes periodically

### ISSUE THREAD

**Issue by Just-ElC** [IzzelAliz/Arclight#1530]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 arclight-1.21.1-1.0.0-SNAPSHOT (Last)

### OS & Java versions

JDK 21 | Windows 11 IoT LTSC 24H2

### Plugins and Mods

```raw
Plugins (16): LuckPerms, SurvivalInvisiframes, PL-Hide, PlaceholderAPI, AntiDisconnectSpam, spark, GSit, WorldsColor, F3NPerm, PlayerEconomy, Vault, Essentials, AFKPlus, TAB, ChatEx, AFKPlusPAPI
```

### Description

The server enters my commands incorrectly, and the console freezes periodically
No errors are displayed, this problem is solved when I refresh the window, but after switching layouts, this problem returns

**Comment by qyl27** [comment]
Did the console enter selection mode when it froze?  
I guess you are facing the same problem as this https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10 .

**Comment by Just-ElC** [comment]
Yes, thx
