### ISSUE TITLE
[CRASH] The server crashes when Ghast mob is loaded in.

### ISSUE THREAD

**Issue by cptDeeJay** [IzzelAliz/Arclight#1531]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21.1-1.0.0-SNAPSHOT-97e6107 (Fabric)

### OS & Java versions

CasaOS [Crafty] (Debian) java version 21.0.3

### Plugins and Mods

```raw
Plugins (0+3 disabled): 
CrisTreeCapitator.jar.disable
Discord- Linker-3.5.1 jar.disable
sleep-most-5.5.1 jar.disable

Mods (0):
```

### Description

It has been found that on Arclight 1.21.1 [Feudal Kings] ( [97e6107](https://github.com/IzzelAliz/Arclight/commit/97e61073f18d109c847eb31c250a10c9c8e63403) ), in the Nether, when ghast mob is loaded the title crashes. Please note that the crash did not occured when the Player with no items in their inventory loaded the chunk, however the issue was  any player that has any item in their inventory enters/loads the chunk with affected mob.

Please note that provided information are based on story of one of the Players and observations of the logs and replay footage from the server. 

### Step to reproduce

1. Run arclight-1.21.1-1.0.0-SNAPSHOT-[97e6107](https://github.com/IzzelAliz/Arclight/commit/97e61073f18d109c847eb31c250a10c9c8e63403) (Fabric).
2. Proceed to The Nether.
3. Find the Ghast mob.
4. Let the Ghast shoot you with the Fireball.
5. Observe the issue.

### Logs

[log.txt](https://github.com/user-attachments/files/17421502/log.txt)
[crash-2024-10-17_18.42.24-server.txt](https://github.com/user-attachments/files/17421507/crash-2024-10-17_18.42.24-server.txt)

**Comment by gdadamx** [comment]
Can confirm it happens on Neoforge too
