### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by emincanortakoy** [IzzelAliz/Arclight#1533]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-b3349e9

### OS & Java versions

java version "22.0.2" 2024-07-16 Java(TM) SE Runtime Environment (build 22.0.2+9-70) Java HotSpot(TM) 64-Bit Server VM (build 22.0.2+9-70, mixed mode, sharing)

### Plugins and Mods

```raw
Plugins: SkinsRestorer, skRayFall, Skript, TitleManager
Mods: Fabric Api, GeckoLib, Vic's Point Blank, Simple Voice Chat
```

### Description

When I died and respawn in my server I can't use commands, breaking-placing blocks....etc. After that If I log-off from server I can't join to server anymore. I should do all of them and when I log-off from server I have to join to server again.

### Step to reproduce

1-) download Fabric Api, GeckoLib, Vic's Point Blank, Simple Voice Chat mods to server.
2-) download SkinsRestorer, skRayFall, Skript, TitleManager plugins to server
3-) join to server and give op to yourself
4-) kill yourself somehow in game

### Logs

https://paste.ubuntu.com/p/HDySHcQJMY/

**Comment by qyl27** [comment]
Please really confirm that **Arclight is up to date** , b3349e9 has 21 versions behind.
