### ISSUE TITLE
Can't get 1.21.1 started at all

### ISSUE THREAD

**Issue by L0rdLogan** [IzzelAliz/Arclight#1534]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.21.1 - 1.0.0 snapshot

### OS & Java versions

Openjdk 22, Debian 12

### Plugins and Mods

```raw
fabric-api-0.106.0+1.21.1.jar
```

### Description

Server will not launch - even with just fabric api installed, nothing else

### Step to reproduce

1. build server
2. install fabric api

### Logs

https://mclo.gs/bUiV6B1

**Comment by L0rdLogan** [comment]
never mind, used an older fabric api - issue sorted with: fabric-api-0.102.0+1.21.1.jar

Old loader version is used in arclight: 0.15.11

**Comment by UnusualNick** [comment]
> never mind, used an older fabric api - issue sorted with: fabric-api-0.102.0+1.21.1.jar
> 
> Old loader version is used in arclight: 0.15.11

How did you chose fabric loader version?

**Comment by qyl27** [comment]
We have already updated the loader version to 0.16.5 in d0dda8526c25054b854b161818a5706c11b3369d in last month.
