### ISSUE TITLE
(Some) Custom Entities do not work with itemsadder

### ISSUE THREAD

**Issue by virtualspan** [IzzelAliz/Arclight#1537]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-fabric-1.21.1-1.0.0-SNAPSHOT-0d31387

### OS & Java versions

OS: Arch Linux x64, Java: openjdk 21.0.5 2024-10-15

### Plugins and Mods

```raw
(Plugins) ItemsAdder_4.0.3.jar, LoneLibs.jar, ProtocolLib.jar
```

### Description

Edit: This only applies to some entities
When you try to place a custom entity, such as a Go-kart, it does not appear in game, and entity's that are expected to be mountable, are not and do not mount. However the entity does appear to be placed (but invisible) as when you left click on the entity, it plays the same sound as when you hit an armor stand or a boat (might be a different sound depending on the entity), and it also does not break the block underneath. And the block on which the invisible Go-kart was placed in Arclight, could not be broken and seemed to be bugged when you took that same server and just replaced the server jar with Spigot.

Arclight: (The Go-kart is supposed to be placed)
![241106_21h48m28s_screenshot](https://github.com/user-attachments/assets/1c87ee26-998f-4583-8f2d-fa2a2291d30b)

Spigot:
![241106_22h16m20s_screenshot](https://github.com/user-attachments/assets/5e0daecc-b638-40ec-845b-6afad8fefd3f)

### Step to reproduce

1. Set up a server with Arclight version 1.21 (commit [0d31387](https://github.com/IzzelAliz/Arclight/actions/runs/11652522775)
2. Install the plugins ItemsAdder and its dependencies (LoneLibs and ProtocolLib)
3. Install the [ItemsAdder OtherPack](https://github.com/ItemsAdder/OtherPacks/releases/tag/2.0.3)
4. Enter `/ia` in game (as operator) and click on vehicles then select a Go-kart
5. Try to place the Go-kart

### Logs

[latest.log](https://github.com/user-attachments/files/17646537/latest.log)

**Comment by qyl27** [comment]
I haven't bought the ItemAdder, could you try out the c326299?

**Comment by virtualspan** [comment]
I still have the same issue in game, but based on my own (limited) analysis of the new log, I can see that this has fixed it partially, as the error
`Server threadEx[06Nov2024 22:40:38.219] [Server thread/ERROR] [Minecraft/]: [ItemsAdder] [m[0;31;1mFailed to lock player movements.[m
` 
is no longer present in server console.
New Log: [latest.log](https://github.com/user-attachments/files/17656405/latest.log)

**Comment by virtualspan** [comment]
I might be wrong about the title... While the Go-karts still do not work, this custom entity that I made does work. So I'm a bit confused to say the least.
[This is a video of the custom entity using commit c3818c5 on Arclight](https://youtu.be/_AdcFUcYVxQ)

Edit: This was summoned using the `/iaentity` command and not placed like a block if that helps by any chance.

**Comment by virtualspan** [comment]
I confirmed that the issue isn't related to mounting because I made the custom entity mountable and it works.

**Comment by virtualspan** [comment]
> I still have the same issue in game, but based on my own (limited) analysis of the new log, I can see that this has fixed it partially, as the error `Server threadEx[06Nov2024 22:40:38.219] [Server thread/ERROR] [Minecraft/]: [ItemsAdder] �[m�[0;31;1mFailed to lock player movements.�[m ` is no longer present in server console. New Log: [latest.log](https://github.com/user-attachments/files/17656405/latest.log)

Also the 'WARN' message in console (and in the log provided) only appears when trying to place a Go-kart, and it appears multiple times if I try to place it multiple times, I think that's the only issue waiting to be resolved now.

**Comment by qyl27** [comment]
Ok, now please try 5ba275c .

**Comment by virtualspan** [comment]
Thank you for helping **so much** and this **did fix the issue**.

I'm sorry to bother you again but there is another similar issue which I thought I'd add that only occurs when you are currently mounting an entity and that entity dies, it causes an error in console/log and skips the death animation in game, and I thought this should be fixed.
Log: [latest.log](https://github.com/user-attachments/files/17674344/latest.log)
Edit: The new issue mentioned in this comment has moved to https://github.com/IzzelAliz/Arclight/issues/1543

**Comment by qyl27** [comment]
Yes, it might be a bug, I'll check it later.  
btw, we are recommand to open another issue although they are simlar.
