### ISSUE TITLE
在1.20.1中使用FastLogin插件报错 NoSuchMethodError...getRawAddress()

### ISSUE THREAD

**Issue by ciisaichan** [IzzelAliz/Arclight#1539]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.20.1-1.0.6-SNAPSHOT-bdaa405

### Java 版本 | 操作系统

系统：Ubuntu 20.04.6 LTS，Java：openjdk version "17.0.13" 2024-10-15

### 相关 Mod/插件 的名称及版本

```raw
FastLoginBukkit: 1.12-SNAPSHOT-4dd6b9a
AuthMeReloaded: v5.6.0
ProtocolLib: v5.3.0
```

### 错误描述

FastLogin插件是一个可以让离线模式的服务器进行正版验证，并对接各类登录插件（例如AuthMe）实现自动登录的功能
我尝试将1.19.2的arclight迁移到1.20.1时此插件就发生了错误，导致无法进行自动登录（在1.19.2中能正常运行）

以及FastLogin的issues中也有提及，回答是服务端缺少相关功能：
https://github.com/games647/FastLogin/issues/1159

### 复现步骤

1. 安装FastLogin插件以及依赖（AuthMe、ProtocolLib）
2. 将服务端设置为离线模式（online-mode=false）
3. 启动服务器
4. 使用正版账号进入服务器

### 报错信息

https://paste.ubuntu.com/p/H3fw3QkXtF/

### 复现用压缩包下载链接(可选)

https://tmp.link/f/672b905058cfe

**Comment by qyl27** [comment]
好像对craftbukkit的inner class remap有点问题，CraftPlayer#spigot里面用的还是bukkit的表，一直影响到了现在的版本，1.21.1也能复现，抄送 @IzzelAliz

**Comment by qyl27** [comment]
尝试 cea9b0a

**Comment by ciisaichan** [comment]
> 尝试 [cea9b0a](https://github.com/IzzelAliz/Arclight/commit/cea9b0a3097b0ff90d9844e1c31aababac603dad)

![image](https://github.com/user-attachments/assets/fd08b2f2-6e98-406c-b736-e89e67170c6e)
看起来没问题了,感谢w
