### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.net.SocketAddress net.minecraft.server.network.ServerGamePacketListenerImpl.getRawAddress()'

### ISSUE THREAD

**Issue by AKGA0019** [IzzelAliz/Arclight#1541]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Arclight-neoforge-1.21.1-1.0.0-SNAPSHOT-c3818c5

### OS & Java versions

Running on Revivenode Hosting & Java version 21

### Plugins and Mods

```raw
FastLogin
Authme
Protocal lib
```

### Description

FastLogin:
Expected:
When a premium user joins the server it should login automatically.
 
Observed:
The premium user has to issue the login command manually.

### Step to reproduce

AuthmeReloaded
1. Install Authme
2. Join the game
3. Register 
4. Leave the game

FastLogin
1. Install FastLogin
2. Join the game
3. do /login <password>
4. do /premium twice
5. Rejoin

### Logs

https://paste.ubuntu.com/p/C9mqTkJTCx/

**Comment by qyl27** [comment]
Please try out cc875d1

**Comment by AKGA0019** [comment]
Thankyou its fixed now.
