### ISSUE TITLE
ItemsAdder: No entity death animation when it is currently mounted.

### ISSUE THREAD

**Issue by virtualspan** [IzzelAliz/Arclight#1543]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21.1-1.0.0-SNAPSHOT-a4fc8e0

### OS & Java versions

OS: Arch Linux x64, Java: openjdk 21.0.5 2024-10-15

### Plugins and Mods

```raw
(Plugins) ItemsAdder_4.0.3.jar, LoneLibs.jar, ProtocolLib.jar
```

### Description

This only occurs when you are currently mounting an entity and that entity dies, it causes an error in console/log and skips the death animation in game, and I thought this should be fixed.

I also noticed there randomly being warnings in other logs but it seems to be stemming from the same underlying issue of `"$$0" is null` so it should get also get fixed when this does.

### Step to reproduce

1. Set up a server with Arclight version 1.21 with commit [a4fc8e0
](https://github.com/IzzelAliz/Arclight/actions/runs/11736585364)
2. Install the plugins ItemsAdder and its dependencies (LoneLibs and ProtocolLib)
3. Put a mountable entity in `plugins/ItemsAdder/contents` folder [such as the one I made](https://www.mediafire.com/file/26kq5eogmerycev/Extract+and+paste+containing+folder.zip/file)
4. Summon the entity (You can summon mine with `/iaentity summon crimson_monstrosity:crimson_monstrosity`)
5. Summon any hostile entities (such as a Zombie) that will attack the previous entity
6. Mount the entity you first summoned
7. Wait for the hostile entity to kill the entity you are mounted
8. Have the death animation skipped and an error in server console.

### Logs

[latest.log](https://github.com/user-attachments/files/17674344/latest.log)

**Comment by qyl27** [comment]
We couldn't debug this issue because the error seems be introduced in ItemsAdder, and it is not open-source, how about to report to them?  
If needed, you can tell them these:  
We think the problem lies in `itemsadder.m.xj.a(SourceFile:88)`, they have passed a null as Entity into `ClipContext#<init>(Vec3, Vec3, Block, Fluid, Entity)`.
