### ISSUE TITLE
[Crash] Crash occurs during the Raid in Trial Chamber

### ISSUE THREAD

**Issue by cptDeeJay** [IzzelAliz/Arclight#1546]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21.1-1.0.0-SNAPSHOT-3ac72c8

### OS & Java versions

CasaOS [Crafty] (Debian) java version 21.0.3

### Plugins and Mods

```raw
Plugins (2): CrisTreeCapitator, sleep-most
Mod List: server-1.21.1-20240808.144430-srg.jar : minecraft (1.21.1) - 1 [locator: production server provider +net.neoforged:neoforge:21.1.64:server] neoforge-21.1.64-universal.jar : neoforge (21.1.64) - 1 [locator: PathBasedLocator[name=neoforge, paths=[libraries/net/neoforged/neoforge/21.1.64/neoforge-21.1.64-universal.jar]], reader: mod manifest] arclight-1.21.1-1.0.0-SNAPSHOT-3ac72c8.jar : arclight (1.0.0-SNAPSHOT+3ac72c8) - 1 [locator: arclight, reader: mod manifest]
```

### Description

It has been reported that on Arclight 1.21.1 [Feudal Kings] [3ac72c8 ](https://github.com/IzzelAliz/Arclight/actions/runs/11763241987) the server crashes during the Trial Raid. Please note that provided information are based on story of one of the Players as since then no Player is able to join the server without crashing it. 

### Step to reproduce

1. Run arclight-1.21.1-1.0.0-SNAPSHOT- [3ac72c8](https://github.com/IzzelAliz/Arclight/actions/runs/11763241987)
2. Proceed to the Trial Chamber.
3. Observe the issue.

### Logs

[debug.log](https://github.com/user-attachments/files/17692569/debug.log)

**Comment by qyl27** [comment]
Fixed in https://github.com/IzzelAliz/Arclight/commit/4b290e26cdc3d33f1573b87f5768c3b7e9c2ce0d
