### ISSUE TITLE
Wind Generator Vanishes When Added to Inventory

### ISSUE THREAD

**Issue by LabsZero** [IzzelAliz/Arclight#1547]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21.1-1.0.0-SNAPSHOT-3ac72c8

### OS & Java versions

OS: Windows 11 jdk-21.0.5.11

### Plugins and Mods

```raw
MekanismTools-1.21.1-10.7.7.64.jar
Mekanism-1.21.1-10.7.7.64.jar
MekanismGenerators-1.21.1-10.7.7.64.jar
```

### Description

When you attempt to craft a MekanismGenerators Wind Generator, it appears correctly in the crafting table. However, as soon as you transfer it to your inventory, it disappears and triggers an error message in the console.

### Step to reproduce

1. Install Arclight Neoforge.
2. Install the specified versions of the Mekanism mod.
3. Craft a Wind Generator.
4. Check the console after adding it to your inventory.

### Logs

https://pastebin.com/LS2LZnsP
Password: YdWV5MiZQN

**Comment by qyl27** [comment]
Please tryout ab1e5d2eba758556f969e88d5f5f6967ee18f5f4 fixed or not.

**Comment by LabsZero** [comment]
Sure will do today and I will report back

**Comment by LabsZero** [comment]
Can confirm your able to add the affected item to your inventory. Thanks for fixing
