### ISSUE TITLE
Bc和瀑布端跨服报错

### ISSUE THREAD

**Issue by Huaxidesu** [IzzelAliz/Arclight#156]
服务端arclight-forge-1.15-1.0.17
BC：
waterfall-1.16-395
BungeeCord272
相关配置
IP转发为 开
BC支持为 开
跨服时显示
[Netty Server IO #6/INFO] [n.m.f.s.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.

**Comment by IzzelAliz** [comment]
不支持 bc，详见 FAQ
