### ISSUE TITLE
NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "location" is null

### ISSUE THREAD

**Issue by gqrshy** [IzzelAliz/Arclight#1563]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21-1.0.0-SNAPSHOT-b3349e9

### OS & Java versions

Windows11 home（latest）

### Plugins and Mods

```raw
mods
crossstitch-0.1.6.jar
mpds-1.21-2.1.0.jar
FabricProxy-Lite-2.9.0.jar

plugin
Vault-1.7.4.jar
AxAuctions-1.14.0.jar

proxy
Velocity3.4.0
```

### Description

I log into the arclight server via velocity and enter the server.
Then, I don't see any other mobs, and I don't get the “You died!” screen that should appear when a player dies. And it respawns on its own.
Sorry if arclight does not support proxy servers like velocity.

### Logs

https://mclo.gs/uAvFTAT

**Comment by SunnyTeater** [comment]
First Steps you could try: 

-Download the latest Arclight build from: 
https://github.com/IzzelAliz/Arclight/actions

(yours from 2024-06-29 03:46:12)

-Remove WorldEdit
I can see it in your logs as a mod

	- worldedit 7.3.8+6939-7d32b45
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   \-- fabric-networking-api-v1 4.2.0+ab7edbacd1

-let the server create a new world with a diffrent name and see if the error still exist.

**Comment by gqrshy** [comment]
I updated and it cured the problem!
I was under the mistaken impression that if I downloaded it from releases, it would be the latest version. Thanks a lot.

**Comment by qyl27** [comment]
Ah, yes, for the active branches, releases might be a few versions out of date. The actions page has the newest build.
