### ISSUE TITLE
无法正常加载fast minecart模组

### ISSUE THREAD

**Issue by RF8xRF8** [IzzelAliz/Arclight#1574]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

Farbic 58f4200

### Java 版本 | 操作系统

jdk21 winserver2016

### 相关 Mod/插件 的名称及版本

```raw
https://modrinth.com/mod/fast-minecart
```

### 错误描述

一个令矿车可以加速运行的小模组 加了他服务器就跑不起来了（
希望可以修一下

### 复现步骤

加入模组并启动服务器

### 报错信息

https://pastebin.com/KKS4AYcB

**Comment by qyl27** [comment]
测一下 9fce044？
sigh这个模组的实现太暴力了（

**Comment by RF8xRF8** [comment]
> 测一下 9fce044？
> 
> sigh这个模组的实现太暴力了（

直接调tick了是吧hh

**Comment by qyl27** [comment]
主要是在tick里调用tick，这么操作反正我是没想过（
