### ISSUE TITLE
[1.21]vanilla /restart command issue

### ISSUE THREAD

**Issue by gqrshy** [IzzelAliz/Arclight#1579]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 arclight-1.21.1-1.0.0-SNAPSHOT-1db479a

### OS & Java versions

Windows11 home（latest）

### Plugins and Mods

```raw
plugin
AdvancedPortals, SimpleAutoRestart, PlaceholderAPI, NoteBlockAPI, packetevents, GSit, HuskSync, Vault, ServersNPC, ProCasino, PicoJobs, Vegas, AxAuctions, AdvancedEnderchest, Roulette, BoomBox, FunGames, RedisEconomy, EconomyShopGUI-Premium, AxTrade

mod
journeymap-fabric-1.21.1-6.0.0-beta.31
RoughlyEnoughProfessions-fabric-1.21.1-4.0.3
architectury-13.0.8-fabric
RoughlyEnoughItems-16.0.788-fabric
fabric-api-0.110.0+1.21.1
Cobblemon-fabric-1.6.0+1.21.1-main-d3ae4cd
proxycommand reloaded
advancementdisable-fabric-1.0.1+1.21
voicechat-fabric-1.21.1-2.5.26
FabricProxy-Lite-2.9.0
worldedit-mod-7.3.8
cloth-config-15.0.140-fabric
```

### Description

When I use the vanilla /restart command, it stops at the world save log and will not restart.

[21:17:01 INFO]: Saving players
[21:17:01 INFO]: *** lost connection: Server closed
[21:17:01 INFO]: *** left the game.
[21:17:01 INFO]: Saving worlds
[21:17:01 INFO]: Saving chunks for level 'ServerLevel[lobby]'/minecraft:overworld
[21:17:01 INFO]: Saving chunks for level 'ServerLevel[lobby/DIM-1]'/minecraft:the_nether
[21:17:01 INFO]: Saving chunks for level 'ServerLevel[lobby/DIM1]'/minecraft:the_end
>

If this command does not work, the AutoRestart plugin will not work either.
Is there some alternative command?
Anyway, thank you for developing arclight even though you must be busy.

### Step to reproduce

1. type /restart on console/ingame.

2. cant restart

### Logs

https://mclo.gs/ZBoeJHY

**Comment by qyl27** [comment]
When did Vanilla add the `/restart` command? I haven't found it in my game.
