### ISSUE TITLE
Ess插件/kick无法正常使用

### ISSUE THREAD

**Issue by RF8xRF8** [IzzelAliz/Arclight#1581]
### 请确认您已完成以下几件事

- [ ] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

1db479a

### Java 版本 | 操作系统

jdk21 winserver2016

### 相关 Mod/插件 的名称及版本

```raw
EssentialsX 2.21.0-dev+143-b560bbd
```

### 错误描述

/kick后无效果 服务端报错

### 复现步骤

/kick后即可复现 （时好时坏但大概率坏）

### 报错信息

https://mclo.gs/dKd4B3c
第10行开始

**Comment by qyl27** [comment]
我记得我之前修过一次这个问题了，然后我刚才用arclight最新版本6e887d4和essentials 2.21.0-dev+150-e1091d8测试了10次都没问题，要不再试试更新一下插件，或者把你用的服务端整合包发上来，也有可能是其他的插件导致的问题，就需要进一步调查

**Comment by RF8xRF8** [comment]
> 我记得我之前修过一次这个问题了，然后我刚才用arclight最新版本6e887d4和essentials 2.21.0-dev+150-e1091d8测试了10次都没问题，要不再试试更新一下插件，或者把你用的服务端整合包发上来，也有可能是其他的插件导致的问题，就需要进一步调查

这个问题目前是偶发的我也不知道确切的复现条件err 我新版本排查一下能复现就再开一个吧😂

**Comment by qyl27** [comment]
其实是可以在原有问题上回复的，这样也方便追踪来着（
