### ISSUE TITLE
服务器玩家传送/多世界传送BUG

### ISSUE THREAD

**Issue by SnivyJ** [IzzelAliz/Arclight#159]
### 我正在运行

* **Arclight** arclight-forge-1.16-1.0.12.jar

* **你确认这是最新版吗** 是，因为1.0.13不是正式版

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** 11.0.10

* **操作系统** Windows Server 2019 Ver1809

* **插件列表** 
* Plugins (32): FarmControl, SimpleProtect, LuckPerms, TagSomeone, SAML, PlaceholderAPI, DeluxeCommands, DeluxeJoin, ColorSource, AntiCreep, tpLogin, WallJump, ProtocolLib, HolyGroupCommand, AdvancedCleaner, ImageOnMap, StopJoinMessage, DeathMessages, Yum, ProtectItemFrame, Vault, eBackup, EntityTrackerFixer, MiaoChat, Essentials, EpicRename, ColorMOTD, Nicky, EssentialsProtect, DeluxeMenus, ItemJoin, EssentialsSpawn

* **Mod 列表** 
• minecraft forge-1.16.5-36.0.1-server.jar : minecraft (1.16.5) - 1
• mods_folder 00 18 mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
• mods_folder 00 12 FarmersDelight-1.16.3-0.2.4b.jar : farmersdelight (1.16.3-0.2.4b) - 1
• mods_folder 03 01 Dynmap-3.1-SNAPSHOT-forge-1.16.4.jar : dynmap (3.1-SNAPSHOT-444) - 1
• mods_folder 00 11 torchmaster-2.3.5-alpha.jar : torchmaster (2.3.5-alpha) - 1
• mods_folder 00 02 ImmersiveEngineering-1.16.4-4.1.2-129.jar : immersiveengineering (1.16.4-4.1.2-129) - 1
• mods_folder 00 04 spiders-2.0-1.16.4-1.0.4.jar : spiderstpo (1.0.4) - 1
• mods_folder 00 21 mining_dimension-1.16.4-1.0.3.jar : mining_dimension (1.16.4-1.0.3) - 1
• mods_folder 01 03 jei-1.16.4-7.6.0.55.jar : jei (7.6.0.55) - 1
• mods_folder 00 19 refinedpipes-0.5.jar : refinedpipes (0.5) - 1
• mods_folder 02 24 FallingTree-Forge-1.16.4-2.10.0.jar : falling_tree (2.10.0) - 1
• mods_folder 00 06 simplefarming-1.16.4-1.3.5.jar : simplefarming (1.16.4-1.3.5) - 1
• mods_folder 00 15 ChickenChunks-1.16.4-2.7.0.85-universal.jar : chickenchunks (2.7.0.85) - 1
• mods_folder 00 14 fishingreal-1.16.3-1.0.0.jar : fishingreal (1.0.0) - 1
• mods_folder 01 00 jeiintegration_1.16.3-6.0.0.8.jar : jeiintegration (6.0.0.8) - 1
• mods_folder 00 13 torohealth-1.16.4-forge-4.jar : torohealth (NONE) - 1
• mods_folder 00 01 create-mc1.16.3_v0.3c.jar : create (mc1.16.3_v0.3c) - 1
• mods_folder 00 17 glassential-forge-1.16.4-1.1.5.jar : glassential (1.1.5) - 1
• mods_folder 00 22 Placebo-1.16.4-4.4.1.jar : placebo (4.4.1) - 1
• mods_folder 01 04 JustEnoughCharacters-1.16.4-4.1.4.jar : jecharacters (4.1.4) - 1
• mods_folder 02 13 Bookshelf-1.16.4-9.0.2.jar : bookshelf (9.0.2) - 1
• mods_folder 00 22.1 Wither-Skeleton-Tweaks-1.16.4-5.3.0.jar : wstweaks (5.3.0) - 1
• mods_folder 02 03 worldedit-forge-mc1.16.3-7.2.0-dist.jar : worldedit (7.2.0+a51fa43) - 1
• mods_folder 00 16 mcws-roofs-2.0.0-mc1.16.4.jar : mcwroofs (2.0.0) - 1
• mods_folder 02 21 AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder 02 18 Hwyla-forge-1.10.11-B78_1.16.2.jar : waila (1.10.11-B78_1.16.2) - 1
• arclight arclight-forge-1.16-1.0.12.jar : arclight (1.16.5-1.0.12-30c1219) - 1
• mods_folder 00 20 modular-routers-1.16.4-7.3.0-47.jar : modularrouters (1.16.4-7.3.0-47) - 1
• mods_folder 01 02 JustEnoughResources-1.16.3-0.12.0.102.jar : jeresources (0.12.0.102) - 1
• maven_libs forge-1.16.5-36.0.1-universal.jar : forge (36.0.1) - 1
• mods_folder 00 05 Aquaculture-1.16.4-2.1.11.jar : aquaculture (1.16.4-2.1.11) - 1
• mods_folder 00 15.1 CodeChickenLib-1.16.4-3.5.1.408-universal.jar : codechickenlib (3.5.1.408) - 1
• mods_folder 00 08 chiselsandbits-0.2.9-RELEASE.jar : chiselsandbits (NONE) - 1
• mods_folder 00 10 ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1

### 错误描述

1.服务器玩家使用/home /warp /tpa 等传送指令进入地狱/末地，会进入虚空状态，无法输入指令/聊天
后台报错 ： https://paste.ubuntu.com/p/JY6kbKGdQd/
2.处于虚空状态的玩家再次进入服务器，通过传送门的方式进入末地/地狱 会掉线
客户端报错：Internet Server Error
3.再次进入服务器的玩家离开游戏，服务器崩溃。
后台报错：https://paste.ubuntu.com/p/cSzDRVcjgj/
Crash：https://paste.ubuntu.com/p/bz5BcfMkfd/

### 重现步骤

1. 服务器玩家使用/home /warp /tpa 等传送指令进入地狱/末地，未知条件卡入虚空
2. 处于虚空状态的玩家再次进入服务器，通过传送门的方式进入末地/地狱
3. 处于已经处于BUG状态的玩家离开服务器，服务器崩溃

**可在 Forge 复现** 否

**Comment by IzzelAliz** [comment]
无法复现
