### ISSUE TITLE
[1.20.1] Stopping server breaks Arclight

### ISSUE THREAD

**Issue by Rijen147** [IzzelAliz/Arclight#1593]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.20.1-1.0.5

### OS & Java versions

Java 21

### Plugins and Mods

```raw
https://imgur.com/a/XeyGetT
```

### Description

Switched from Mohist to Arclight cause of end of Mohist support. Loaded first time correctly, mostly all was working, until I restarted the server. Server didn't want to start Arclight, starting just Forge instead. I've recovered using a backup, tried more older versions of Arclight, it didn't even install.
(screenshot, error accures when you try to shutdown the server after first boot)

[!chrome_C8eg8PKFqI](https://github.com/user-attachments/assets/e976c82c-9041-49f4-b7e6-73081aef2820)

### Step to reproduce

1. Install Arclight with same files as mine
2. Reboot the server ones
3. Arclight brokes, boots only Forge

### Logs

[installer_stripped.jar.txt](https://github.com/user-attachments/files/18212688/installer_stripped.jar.txt)
[latest.txt](https://github.com/user-attachments/files/18212706/latest.txt)
[debug.txt](https://github.com/user-attachments/files/18212707/debug.txt)

**Comment by Rijen147** [comment]
fixed by changing starting file with no forge compability (on the hosting service)

**Comment by qyl27** [comment]
The forge in modern versions, launches with a text file containing command-line arguments.  
It is different from legacy or Bukkit-series servers. Our jar will install and launch forge, some server hosting services might mis-detect it. So simply disable forge compatibility and launch arclight.jar

**Comment by qyl27** [comment]
I will close this issue because it wasn't a code-related bug with Arclight. You can still give feedback.
