### ISSUE TITLE
玩家无法用床保存出生点

### ISSUE THREAD

**Issue by Night-Aurora** [IzzelAliz/Arclight#160]
### 我正在运行 
* **Arclight** [arclight-1.16.5-1.0.12-30c1219] 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** [是/否]

* **Java** [1.8.0_281] 

* **操作系统** [windows10+1909]

* **插件列表** 

* **Mod 列表** 

### 错误描述
玩家无法用床保存重生点
白天玩家单击床保存出生点无用
睡觉保存出生点重启服务器后失效

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

**可在 Forge 复现** 是

**可在 Spigot 复现** 是

### 报错信息

[错误日志]

**Comment by hanbings** [comment]
Rua~ 写了个小插件可以恢复床和重生锚保存重生点 仅1.16.x可用

[artifact.zip](https://github.com/IzzelAliz/Arclight/files/6383347/artifact.zip)
