### ISSUE TITLE
加入沉浸式传送门开服载入世界卡住

### ISSUE THREAD

**Issue by Night-Aurora** [IzzelAliz/Arclight#163]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.12-30c1219] 

* **你确认这是最新版吗** [是，因为___]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_281] 

* **操作系统** [Window10]

* **插件列表** 

* **Mod 列表** 
 immersive-portals-0.14-mc1.16.4-forge.jar : immersive_portals (0.14) - 1

### 错误描述
加入沉浸式传送门服务器在开服载入世界的时候会卡住

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装  immersive-portals （https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge/files）
2. 等待载入世界

**可在 Forge 复现** [是]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

**Comment by IzzelAliz** [comment]
请提供 thread dump 信息

如果是 Windows 系统并使用 cmd，对着控制台按下 Ctrl+Break 即可

如果不是，请安装 jdk 并使用 jstack 命令，具体可以百度

**Comment by Night-Aurora** [comment]
https://pastebin.com/1a5T7pin
