### ISSUE TITLE
1.16.5 机械动力自动化机器偶尔造成严重卡顿

### ISSUE THREAD

**Issue by Light-FD** [IzzelAliz/Arclight#166]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.13-ab2ab51] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [版本] 
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
* **操作系统** [名称+版本]
Windows 10 server 2019
* **插件列表** 
Plugins (3): CoreProtect, PermissionsEx, WhiteList
* **Mod 列表** 
[更多生物群系]BiomesOPlenty.jar : biomesoplenty (1.16.4-13.0.0.431) - 1
[更多门]mcw-doors.jar : mcwdoors (1.0.2) - 1
[合金扩展-前置]architectury.jar : architectury (1.5.112) - 1
mcw-furniture-2.0.1-mc1.16.5.jar : mcwfurnitures (2.0.1) - 1
[合成搜索]jei.jar : jei (7.6.1.71) - 1
[植物魔法]Botania-1.16.4-411.jar : botania (1.16.4-411) - 1
[植魔前置]curios-forge-1.16.5-4.0.4.0.jar : curios (1.16.5-4.0.4.0) - 1
[下界合金扩展]netherite-plus-mod.jar : netherite_plus (1.3.17-1.16.5) - 1
[植魔前置]Patchouli-1.16.4-50.jar : patchouli (1.16.4-50) - 1
**[机械动力]create-mc1.16.3_v0.3e.jar : create (mc1.16.3_v0.3e) - 1**
[凿子]chiselsandbits-0.2.10-RELEASE.jar : chiselsandbits (NONE) - 1
[更好的末地]betterend.jar : betterendforge (1.16.4-1.4.1) - 1
[小地图]Xaeros_Minimap.jar : xaerominimap (21.3.0) - 1
[传送石]Waystones_1.16.3-7.3.1.jar : waystones (7.3.1) - 1
[环绕音效]DynamicSurroundings.jar : dsurround (1.16.4-4.0.3.9) - 4
[更多箱子]ironchest.jar : ironchest (1.16.4-11.2.10) - 1
TravelersBackpack-1.16.4-5.3.8.jar : travelersbackpack (5.3.8) - 1
[储存抽屉]StorageDrawers-1.16.3-8.2.2.jar : storagedrawers (8.2.2) - 1

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤
疑似造成卡顿模组: [机械动力]create(https://www.mcmod.cn/class/2021.html)
进入服务器后使用该模组的【风车轴承、旋转底盘、风帆框架、机械手、动力锯、动力收割机】
分别搭造一个自动农场和自动树场并启动后，偶发卡顿现象(瞬间降tps至2(forge)并持续一段时间)

**可在 Forge 复现** [否_未在forge下复现卡顿情况]

**可在 Spigot 复现** [否_非插件相关问题]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/PzT8v5Kb2f/
[latest (1).log](https://github.com/IzzelAliz/Arclight/files/5988607/latest.1.log)

**Comment by IzzelAliz** [comment]
卡顿你不用 spark 跑一跑吗

有个参数 only-ticks-over 记得加上

**Comment by Light-FD** [comment]
明天去跑一下试试

**Comment by Light-FD** [comment]
https://spark.lucko.me/#QO7vunJ366
only-ticks-over 怎么加..没用过spark
这个卡顿有时候会让服务器tps直接降到1.5(/forge tps)

**Comment by Light-FD** [comment]
顺便再附一段机器开启时的报错
https://paste.ubuntu.com/p/SvBtzpDhDK/

**Comment by IzzelAliz** [comment]
看起来和我完全无关，应该是 create 的问题

**Comment by Light-FD** [comment]
那我去那边开issue了
