### ISSUE TITLE
服务器生成地图到100%就卡住

### ISSUE THREAD

**Issue by cathats** [IzzelAliz/Arclight#169]
版本1.0.14
加载到地图100%就卡住不动了，cpu占用此时4%，不像是继续加载的样子
崩服后就这样子了。
 [debug](https://paste.ubuntu.com/p/sSNsvHqJDY/)
[log](https://paste.ubuntu.com/p/MZSmDRQWmf/)
[crash](https://paste.ubuntu.com/p/9FnkGYWxCj/)

**Comment by IzzelAliz** [comment]
请向 StatuesMod 开发者反馈该问题
