### ISSUE TITLE
服务器删除mod后进入报Failed to synchronize registry data from server.

### ISSUE THREAD

**Issue by EulaZ** [IzzelAliz/Arclight#170]
### 我正在运行

* **Arclight** 1.16.5-1.0.13-ab2ab51 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **Java** 11 

### 错误描述

服务器删除mod后，玩家进入服务器提示Failed to synchronize registry data from server, closing connection.
数据不同步，应该是forge中间版本的bug。

### 重现步骤

1. 安装任意有新增物品/方块的mod
2. 进入服务器生成地图，放置物品/方块后删除服务器内该mod
3. 客户端删除mod后登入失败，提示Failed to synchronize registry data from server, closing connection.

**Comment by victorbetoni** [comment]
Try downloading NBTExplorer (available on GitHub) and open all the worlds level.dat file in it, then delete the folder named "fml" in each file and upload it to the server. Worked for me. Dont forget to shutdown the server while you do this.

**Comment by cathats** [comment]
简单粗暴的解决办法：同步客户端和服务端的forge版本，亲测有效。

**Comment by IzzelAliz** [comment]
请提供客户端的 debug.log

**Comment by EulaZ** [comment]
[debug-4.log](https://github.com/IzzelAliz/Arclight/files/6105626/debug-4.log)
integratedtunnels是已经在服务端上删除的mod
