### ISSUE TITLE
Signs content aren't being saved

### ISSUE THREAD

**Issue by victorbetoni** [IzzelAliz/Arclight#173]
### I am running

* **Arclight** 1.0.13

* **This is the latest development version** [Y]

* **Java** [1.8.0]

* **Operating System** Ubuntu 16

* **Plugins** Plugins (36): LuckPerms, CommandExpress, UnloadSpawnChunks, RTP, PlugMan, SimpleGUI, Generators, ProtocolLib, AdvancedPortals, SpigotPing, HideJoinLeaveMessages, SkinsRestorer, Universes, PL-Hide, AdvancedNMotd, Vault, ManterEXP, WorldEdit, MachinaEconomy, Essentials, TeamCraft, AdvancedBan, PlotSquared, HolographicDisplays, SafeTrade, WorldGuard, SimpleClans, UltimateChat, LockettePro, EssentialsChat, EssentialsAntiBuild, TAB, EssentialsSpawn, CraftX1, AuthMe, ActionHealth

* **Mods** 
• minecraft forge-1.16.5-36.0.14-server.jar : minecraft (1.16.5) - 1
• mods_folder betteranimalsplus-1.16.4-10.1.0.jar : betteranimalsplus (10.1.0) - 1
• mods_folder ImmersiveEngineering-1.16.5-4.2.0-130.jar : immersiveengineering (1.16.5-4.2.0-130) - 1
• mods_folder mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder mcw-doors-1.0.2-mc1.16.5.jar : mcwdoors (1.0.2) - 1
• mods_folder furniture-7.0.0-pre19-1.16.3.jar : cfm (7.0.0-pre19) - 1
• mods_folder mcw-furniture-2.0.1-mc1.16.5.jar : mcwfurnitures (2.0.1) - 1
• mods_folder MekanismGenerators-1.16.4-10.0.19.446.jar : mekanismgenerators (10.0.19) - 1
• mods_folder crafting-dead-core-1.16.4-1.2.7-alpha.jar : craftingdead (1.2.7-alpha) - 1
• arclight arclight-forge-1.16-1.0.13.jar : arclight (1.16.5-1.0.13-ab2ab51) - 1
• mods_folder charm-forge-1.16.4-2.2.2.jar : charm (2.2.2) - 1
• mods_folder Mekanism-1.16.4-10.0.19.446.jar : mekanism (10.0.19) - 1
• mods_folder mcw-windows-1.0.2-mc1.16.4.jar : mcwwindows (1.0.2) - 1
• maven_libs forge-1.16.5-36.0.14-universal.jar : forge (36.0.14) - 1
• mods_folder VendingMachine-1.16.2-1.0.0.3.jar : vm (1.0.0.3) - 1
• mods_folder charmonium-forge-1.16.4-2.2.2.jar : charmonium (2.2.1) - 1
• mods_folder armacraft-1.0.jar : armacraft (1.0) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.1.jar : pamhc2foodcore (version) - 1
• mods_folder DynamicSurroundings-1.16.4-4.0.3.5 (1).jar : dsurround (1.16.4-4.0.3.5) - 4
• mods_folder XaerosWorldMap_1.11.10_Forge_1.16.5.jar : xaeroworldmap (1.11.10) - 1
• mods_folder [1.16.4]+SecurityCraft+v1.8.20.2.jar : securitycraft (v1.8.20.2) - 1
• mods_folder TravelersBackpack-1.16.4-5.3.8.jar : travelersbackpack (5.3.8) - 1

### Description

This bug happens every time you write something in a sign and logout or teleport to another world. When  you go back to the sign, it's empty.

### Step to reproduce

1. Place a sign and write something
2. Logout or teleport to another world
3. Go back to the sign and see that it's empty.

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

### Logs

[ERROR LOG]

The console does not show any error, however every time I place a sign and click in "Done" the console displays
> [Server thread/WARN] [minecraft/ServerPlayNetHandler]: Player threadly just tried to change non-editable sign

**Comment by IzzelAliz** [comment]
Cannot reproduce in clean environment.
