### ISSUE TITLE
创世神mod加载不正常

### ISSUE THREAD

**Issue by TCwater** [IzzelAliz/Arclight#174]
### 我正在运行

* **Arclight-1.16.5-1.0.14-3408941
 [版本] 
Arclight-1.16.5-1.0.14-3408941
* **你确认这是最新版吗** []

是，因为是群文件下载
* **你确认所有Mod都安装了依赖** [是/否]
是
* **你确认所有插件都已更新至对应版本** [是/否]

是
* **Java** [版本] 
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
* **操作系统** [名称+版本]
Windows Sever 2016 Dacenter
* **插件列表** 
CoreProtect, MiniMOTD, GeneralDataCoreV6, FastLogin, SAML, GroupManager, VillagerOptimiser, ClearLag, WildCardIPBan, PublicBin, PlugMan, BetterEnchantBook, EasyBackup, ConsoleSpamFix, DisableAI, BanItem, Vault, RecordQuery, OhTheWorld, Essentials, AutoMessager, Shopkeepers, PlayerTitle, ChestCommands, EssentialsProtect, EssentialsChat, EssentialsSpawn
* **Mod 列表** 
• minecraft forge-1.16.5-36.0.42-server.jar : minecraft (1.16.5) - 1
• mods_folder [干净利落]cleancut-mc1.16-2.2-forge.jar : cleancut (2.2) - 1
• mods_folder [TOP高亮显示]theoneprobe-1.16-3.0.7.jar : theoneprobe (1.16-3.0.7) - 1
• mods_folder [生活调味料-马铃薯版]solpotato-1.16.X-1.1.0.jar : solpotato (1.16.X-1.1.0) - 1
• mods_folder [沉浸工程]ImmersiveEngineering-1.16.4-4.1.2-129.jar : immersiveengineering (1.16.4-4.1.2-129) - 1
• mods_folder [美人鱼尾巴]mermaidtail-1.4.jar : mermaidtail (1.16.4-1.4.0) - 1
• mods_folder [巨人]giantspawn_1.16.5-2.2.jar : giantspawn (2.2) - 1
• mods_folder debug-tools-2.0-SNAPSHOT.jar : debug-tools (NONE) - 1
• mods_folder [JEI]jei-1.16.4-7.6.0.58.jar : jei (7.6.0.58) - 1
• mods_folder [属性修复]AttributeFix-1.16.4-9.0.2.jar : attributefix (9.0.2) - 1
• mods_folder [小狗天才]DoggyTalents-1.16.4-2.0.1.3.jar : doggytalents (2.0.1.3) - 1
• mods_folder [简单背包]simplybackpacks-1.16.3-1.4.13.jar : simplybackpacks (1.16.3-1.4.13) - 1
• mods_folder [性能查询]spark-forge.jar : spark (1.4.3) - 1
• mods_folder [机械动力]create-mc1.16.3_v0.3e.jar : create (mc1.16.3_v0.3e) - 1
• mods_folder [更多信息显示]LagMeter-1.3.4.jar : lagmeter (1.3.3) - 1
• mods_folder [帕秋莉手册]Patchouli-1.16.4-48.jar : patchouli (1.16.4-48) - 1
• mods_folder [叶间穿行]PassableFoliage-1.16.4-2.2.0.jar : passablefoliage (2.2.0) - 1
• mods_folder [传送石碑]Waystones_1.16.3-7.3.1.jar : waystones (7.3.1) - 1
• mods_folder [无限交易前置]collective-1.16.5-1.66.jar : collective (1.66) - 1
• mods_folder [合成冲突消除]polymorph-forge-1.16.4-0.22.jar : polymorph (1.16.4-0.22) - 1
• mods_folder [生物群系指南针]NaturesCompass-1.16.4-1.8.6.jar : naturescompass (1.16.4-1.8.6) - 1
• mods_folder [旅行者背包]TravelersBackpack-1.16.4-5.3.1.jar : travelersbackpack (5.3.1) - 1
• mods_folder [席地而坐]sit-1.16.2-v1.3.jar : sit (v1.3) - 1
• mods_folder [储物抽屉]StorageDrawers-1.16.3-8.2.1.jar : storagedrawers (8.2.1) - 1
• mods_folder [FTBGUI]ftb-gui-library-1604.1.1.26.jar : ftbguilibrary (1604.1.1.26) - 1
• mods_folder [冠军]champions-forge-1.16.4-2.0.0.2.jar : champions (1.16.4-2.0.0.2) - 1
• mods_folder [烹饪锅]CrockPot-1.16.3-1.3.3-release.jar : crockpot (1.3.3-release) - 1
• mods_folder [创世神]worldedit-mod-7.2.3.jar : worldedit (7.2.3+5680-135941e) - 1
• mods_folder [迷你刷怪塔]TinyMobFarm-1.16.4-1.1.1.jar : tinymobfarm (1.1.1) - 1
• mods_folder [简单飞机]simpleplanes-1.16.3-3.2.0.3.jar : simpleplanes (1.16.3-3.2.0.3) - 1
• mods_folder [围火无怪]nhacampfire_1.16.4-3.0.jar : nhacampfire (3.0) - 1
• mods_folder [落选生物]outvoted-1.16.5-1.1.2.jar : outvoted (1.1.2) - 1
• mods_folder [睡眠投票]Morpheus-1.16.4-4.2.68.jar : morpheus (4.2.68) - 1
• mods_folder [工程师的装饰]engineersdecor-1.16.4-1.1.7.jar : engineersdecor (1.1.7) - 1
• mods_folder [更多的生物群系]voyage-1.16.4-1.0.3.jar : voyage (1.0.3) - 1
• arclight arclight-forge-1.16-1.0.14.jar : arclight (1.16.5-1.0.14-3408941) - 1
• mods_folder [月亮事件]enhancedcelestials-1.0.1-1.16.4.jar : enhancedcelestials (1.0.1-1.16.4) - 1
• mods_folder [遍历]traverse-1.16.4-0.4.3.8.jar : traverse (1.16.4-0.4.3.8) - 1
• mods_folder [哦，你会去的生物群落]byg-1.1.6.jar : byg (1.1.6) - 1
• mods_folder [沉浸原油]ImmersivePetroleum-1.16.4-3.1.0-2.jar : immersivepetroleum (3.1.0-2) - 1
• mods_folder [FTB组队]ftb-teams-1604.1.0.13.jar : ftbteams (1604.1.0.13) - 1
• mods_folder [FTB区块]ftb-chunks-1604.2.2.57.jar : ftbchunks (1604.2.2.57) - 1
• maven_libs forge-1.16.5-36.0.42-universal.jar : forge (36.0.42) - 1
• mods_folder [Psi]Psi+1.16-88.jar : psi (1.16-88) - 1
• mods_folder [匍匐前进]goprone-1.16.4-1.3.5.jar : goprone (1.16.4-1.3.5) - 1
• mods_folder [无限交易]infinitetrading_1.16.5-1.3.jar : infinitetrading (1.3) - 1
• mods_folder [原版补充]supplementaries-1.16.5-0.9.24b.jar : supplementaries (1.16.5-0.9.24b) - 1
• mods_folder [落选生物前置]geckolib-forge-1.16.5-3.0.13.jar : geckolib3 (3.0.13) - 1
• mods_folder [下届合金升级]Upgraded+Netherite+1.16.4+-+1.8.0.jar : upgradednetherite (1.7.0) - 1
### 错误描述
服务器从升级到Arclight1.013正式版开始创世神插件指令不能正常使用

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [是/否]
不知道

**可在 Spigot 复现** [是/否]
不知道
### 报错信息
无报错
[错误日志]
https://paste.ubuntu.com/p/CDZHzpb8Hr/

**Comment by Edel-Lilies** [comment]
我也遇到了,使用指令則會提示//wand之類為未知指令,Forge端無問題

**Comment by CornWorld** [comment]
我也遇到了 并且创世神插件也不大正常

**Comment by JeskaiJet** [comment]
我之前也有过测试：
如果只使用WE插件：无法操作mod方块，操作涉及到mod方块时有概率崩服
如果只使用WE MOD：无法使用WorldGuard以及其他依赖WE的插件
如果WE插件和MOD一起使用：操作涉及到mod方块时有概率崩服

**Comment by TCwater** [comment]
> 我也遇到了,使用指令則會提示//wand之類為未知指令,Forge端無問題

1.0.13测试版还没有这个问题，从1.0.13正式版就出现了这个问题
