### ISSUE TITLE
Broken command arguments

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#175]
### I am running

* **Arclight** 1.16.5-1.0.14 

* **This is the latest development version** [Y]

<details>
  <summary>Click to expand</summary>

* **Java** 15.0.2+7 JRE 

* **Operating System** Debian 10

* **Plugins**  LuckPerms, SkinsRestorer, UberEnchant, Chunky, VillagerOptimiser, spark, Vault, ConsoleSpamFix, ProtocolLib, FastAsyncWorldEdit (WorldEdit), Essentials, EssentialsChat, TAB, IllegalStack, EssentialsSpawn, WorldGuard, BanItem, AuthMe, CoreProtect, LWC, FarmControl

* **Mods** 
• minecraft forge-1.16.5-36.0.42-server.jar : minecraft (1.16.5) - 1
• mods_folder mcw-bridges-1.0.5-mc1.16.5-4.jar : mcwbridges (1.0.5) - 1
• mods_folder decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder eternalwinter-1.3.jar : eternalwinter (1.3) - 1
• mods_folder buildersaddition-1.16.4-20210214a.jar : buildersaddition (1.16.4-20210214a) - 1
• mods_folder BiomesOPlenty-1.16.4-13.0.0.421-universal.jar : biomesoplenty (1.16.4-13.0.0.418) - 1
• mods_folder FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
• mods_folder CoronaMask-1.16.4-v1.jar : corona_mask (1.0.0) - 1
• mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
• mods_folder starlight-0.0.3.jar : starlight (0.0.3) - 1
• mods_folder mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder dungeons_plus-1.16.4-1.1.2.jar : dungeons_plus (1.1.2) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
• arclight arclight-forge-1.16-1.0.14.jar : arclight (1.16.5-1.0.14-3408941) - 1
• mods_folder trashcans-1.0.6a-mc1.16.4.jar : trashcans (1.0.6a) - 1
• mods_folder FallingTree-Forge-1.16.5-2.10.0.jar : falling_tree (2.10.0) - 1
• maven_libs forge-1.16.5-36.0.42-universal.jar : forge (36.0.42) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.1.jar : pamhc2foodcore (version) - 1
• mods_folder structure_gel-1.16.4-1.7.5.jar : structure_gel (1.7.5) - 1
• mods_folder FastWorkbench-1.16.4-4.5.0.jar : fastbench (4.5.0) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.2.jar : cookingforblockheads (9.2.2) - 1
• mods_folder christmasfestivity-1.3.6-1.16.4.jar : christmasfestivity (1.3.6-1.16.4) - 1
• mods_folder Placebo-1.16.4-4.4.1.jar : placebo (4.4.1) - 1</details>

### Description

Command block no longer suggests any arguments that are related to finding players. If you type them in command block the command will be issued but players won't be found. There's no error logs from the server side.

### Steps to reproduce

Make a command block and use any of those arguments: @a @p @s
It won't be suggested and players won't be found
https://cdn.discordapp.com/attachments/745711105296564265/813403571826589716/unknown.png

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

**Comment by IzzelAliz** [comment]
Because plugin registered these commands and plugins usually do not handle target selectors.

You can use `minecraft:ban @p` instead.
