### ISSUE TITLE
[FEATURE REQ] Lithium compatibility or integration

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#176]
Is it feasible to have at least some of Lithium enhancements applied natively? We've seen a major TPS boost on our server that has come at the cost of stability. Current Forge fork is Mixin based and conflicts with some of Arclight functions like: 

`Method overwrite conflict for func_219790_a in mixins.arclight.impl.optimization.1_16.json:ClassInheritanceMultiMapMixin, previously written by me.jellysquid.mods.lithium.mixin.collections.entity_filtering.TypeFilterableListMixin`
`Method overwrite conflict for func_75774_a in mixins.arclight.impl.optimization.stream.1_16.json:GoalSelectorMixin, previously written by me.jellysquid.mods.lithium.mixin.ai.goal.GoalSelectorMixin`

For example:

Logon crash that we couldn't reproduce
[crash-2021-02-22_16.02.06-server.txt](https://github.com/IzzelAliz/Arclight/files/6022383/crash-2021-02-22_16.02.06-server.txt)
[2021-02-22-3.log](https://github.com/IzzelAliz/Arclight/files/6022394/2021-02-22-3.log)
[debug-3.log](https://github.com/IzzelAliz/Arclight/files/6022400/debug-3.log)

Even more command block misbehavior
[2021-02-22-2.log](https://github.com/IzzelAliz/Arclight/files/6022417/2021-02-22-2.log)
[debug-2.log](https://github.com/IzzelAliz/Arclight/files/6022418/debug-2.log)

It would be great if Lithium optimizations could be applied on Arclight or used by default. There are actually 2 forks of Lithium that can be tested as a Forge mod:

The one I've tested
https://github.com/Pannoniae/sodium-forge/issues/10#issuecomment-778675303
And another one
https://github.com/jamierocks/lithium-forge

**Comment by Dum4G** [comment]
The fork from jamierocks didn't cause any issues for me with 1.0.13-ddbb4265 build, so I can recommend it I guess.

**Comment by ghost** [comment]
Arclight - In essence, this is a vanilla server, but patched twice - first by Forge, then by Arclight with his implementation of Bakkit. In this regard, performance will have to be drawn from mods.

So the work of this mod is very important for servers...

Since even the PERFOMANT alternative is forcibly locked in Arclight

Although the author of Perfomant has fixed all the critical bugs in recent updates, I think so.
