### ISSUE TITLE
"Brigadier" command list data regression (LuckPerms)

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#181]
### I am running

* **Arclight** 1.16.5-1.0.14 

* **This is the latest development version** [N]

### Description

Making this issue just to memorize a known problem and it's temp workaround.

### Workaround

Set register-command-list-data to false in LP config

**Comment by IzzelAliz** [comment]
Cannot reproduce. Maybe you are using your own fork that drops this fix.

**Comment by Dum4G** [comment]
I failed to compile my fork back then, it was reprodusible on Arclight 1.16.5-1.0.14 with LuckPerms-Bukkit-5.2.76 as long as you try to execute some command like lp editor. Will retest again

**Comment by Dum4G** [comment]
Nvm, proved myself wrong
