### ISSUE TITLE
请兼容mcMMO。

### ISSUE THREAD

**Issue by wkurumi** [IzzelAliz/Arclight#185]
### 我正在运行arclight-1.16.5-1.0.14-3408941

* **Arclight** [版本] 

* **你确认这是最新版吗** [是/否，因为___]否，最新1.0.15也没修复

* **你确认所有Mod都安装了依赖** [是/否]是

* **你确认所有插件都已更新至对应版本** [是/否]是

* **Java** [版本] java version 1.8.0_281 by Oracle Corporation

* **操作系统** [名称+版本]windows10家庭版

* **插件列表**  LuckPerms, RandomParachute, PlaceholderAPI, PublicBin, CMILib, SnowkSpigotFixer, spark, ArmorStand-Limiter, BetterEnchantBook, TabooLib5, Patch4, ProtocolLib, CratesLottery, React, ShulkerBoxFixer, LiveRecorder, mcMMO, NBTAPI, Vault, ReviveMe, Mczf, PvpManagement, ContinuousKill, KillEntityActivity, CMI, MoneyDrop, ServerSafetyManagement, LockettePro, CMIEInjector, UltimateClaims, BanIt, OfferAReward, MPoints, BossShopPro

* **Mod 列表**  minecraft forge-1.16.5-36.0.42-server.jar : minecraft (1.16.5) - 1
• mods_folder cityblocks-1.16.5-1.4.2.jar : cityblocks (1.4.2) - 1
• mods_folder Ping-1.16.4-1.6.9.jar : ping (1.16.4-1.6.9) - 1
• mods_folder ImmersiveEngineering-1.16.5-4.2.1-131.jar : immersiveengineering (1.16.5-4.2.1-131) - 1
• mods_folder crafting-dead-core-1.16.5-1.3.0-alpha.jar : craftingdead (1.3.0-alpha) - 1
• mods_folder jei-1.16.4-7.6.1.71 .jar : jei (7.6.1.71) - 1
• mods_folder Botania-1.16.4-411.jar : botania (1.16.4-411) - 1
• mods_folder car-1.16.4-1.0.5.jar : car (1.16.4-1.0.5) - 1
• mods_folder Guide-API-VP-1.16.4-2.2.1.jar : guideapi-vp (2.2.1) - 1
• mods_folder curios-forge-1.16.5-4.0.4.0.jar : curios (1.16.5-4.0.4.0) - 1
• mods_folder SpartanShields-1.16.4-2.1.1.jar : spartanshields (2.1.1) - 1
• mods_folder Patchouli-1.16.4-50.jar : patchouli (1.16.4-50) - 1
• mods_folder Waystones_1.16.3-7.3.1.jar : waystones (7.3.1) - 1
• mods_folder TravelersBackpack-1.16.4-5.3.8.jar : travelersbackpack (5.3.8) - 1
• mods_folder hcdservercore-1.16.5-1.2.3.jar : hcdservercore (1.2.3) - 1
• mods_folder lostcities-1.16-4.0.6-alpha.jar : lostcities (1.16-4.0.6-alpha) - 1
• mods_folder 深渊2+1.8.5+1.16.5.jar : theabyss (1.8.5) - 1
• mods_folder Vampirism-1.16.4-1.7.6 .jar : vampirism (1.7.6) - 2
• arclight arclight.jar : arclight (1.16.5-1.0.14-3408941) - 1
• mods_folder VampiresNeedUmbrellas-1.16.4-1.1.jar : vampiresneedumbrellas (1.1) - 1
• mods_folder ImmersivePetroleum-1.16.4-3.1.0-2.jar : immersivepetroleum (3.1.0-2) - 1
• maven_libs forge-1.16.5-36.0.42-universal.jar : forge (36.0.42) - 1
• mods_folder betterendforge-1.16.4-1.5.0.jar : betterendforge (1.16.4-1.5.0) - 1
• mods_folder EnderMail-1.16.5-1.2.0.jar : endermail (1.16.5-1.2.0) - 1
• mods_folder emotecraft-0.12.4_for_MC1.16.2+.jar : emotecraft (0.12.4) - 1
• mods_folder corpse-1.16.5-1.0.0.jar : corpse (1.16.5-1.0.0) - 1

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [是/否]否

**可在 Spigot 复现** [是/否]否

### 报错信息

[错误日志]https://paste.ubuntu.com/p/5s5zZFdpS2/

**Comment by wkurumi** [comment]
https://paste.ubuntu.com/p/5s5zZFdpS2/

**Comment by IzzelAliz** [comment]
日志能发全吗

**Comment by wkurumi** [comment]
> 日志能发全吗

https://paste.ubuntu.com/p/2HKDvkHzT2/  这是完整的一次启动

**Comment by IzzelAliz** [comment]
与 #168 重复
