### ISSUE TITLE
跳伞随机传送RandomParachute-1.2报错

### ISSUE THREAD

**Issue by wkurumi** [IzzelAliz/Arclight#186]
### 我正在运行arclight-1.16.5-1.0.15-SNAPSHOT-6c17585

* **Arclight** [版本] 

* **你确认这是最新版吗** [是/否，因为___]否

* **你确认所有Mod都安装了依赖** [是/否]是

* **你确认所有插件都已更新至对应版本** [是/否]是

* **Java** [版本] java version 1.8.0_281

* **操作系统** [名称+版本]windows10家庭版

* **插件列表** RandomParachute-1.2.jar，PlaceholderAPI-2.10.9.jar

* **Mod 列表** 

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装RandomParachute-1.2.jar
2. 进入服务器后 /rp
3. 报错

**可在 Forge 复现** [是/否]否

**可在 Spigot 复现** [是/否]否

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/ptfDJfBS3N/

**Comment by IzzelAliz** [comment]
请报给插件作者
