### ISSUE TITLE
LibsDisguises not working.

### ISSUE THREAD

**Issue by NightScale5755** [IzzelAliz/Arclight#187]
### I am running

* **Arclight** [VERSION] 
    Version arclight-1.16.5-1.0.15-SNAPSHOT-242055d
* **This is the latest development version** [Y/N, because ___]

Yes
* **Java** [VERSION] 
java version "1.8.0_281"
* **Operating System** [NAME & VERSION]
Windows 10. Version, idk. But it's recent.
* **Plugins** 
LibsDisguises-10.0.24-Premium.jar
ProtocolLib 4.6.0
* **Mods** 
None.

### Description

So, I encountered the following issue, decided to try a fresh install. With ONLY LibsDisguises and Protocollib installed. It persists
### Step to reproduce

1. Install Arclight
2. Install LibsDisguises premium and Protocollib
3. Start the server

**Reproducible in Forge** [Y/N]
No. Mainly because it's plugin related

**Reproducible in Spigot** [Y/N]
Doubtful.
### Logs

[ERROR LOG]

https://paste.ubuntu.com/p/HZNYz6x5HK/

**Comment by IzzelAliz** [comment]
This can be easily fixed by their plugin developer. I guess you can report this to them, and if they show no interest in fixing this I would like to help.

**Comment by NightScale5755** [comment]
https://github.com/libraryaddict/LibsDisguises/issues/431
This pretty much sums up why I didn't go to them first.

**Comment by IzzelAliz** [comment]
Alright I'll do this myself.

**Comment by NightScale5755** [comment]
thanks.

**Comment by IzzelAliz** [comment]
Further problems show and they are not possibly fixed on my side. You need to ask LibDisguises dev for help. They can easily fix this.

**Comment by NightScale5755** [comment]
Hmm.. I'm 90% sure that the LibsDisguises team will not offer support... 
I do know team Mohist has a fork, but it's for 1.12.2, and doesn't work anymore. Can't you just fork LibsDisguises?
Close this if no. I'll understand.

**Comment by IzzelAliz** [comment]
Well LibDisguise works now with tons of console spam(more with more mods). If you have great tolerance it would be fine.

**Comment by NightScale5755** [comment]
ok. I'll give it a whirl and get back to you. Thanks for not immediately flagging it as a wontfix like most people do with these kinds of things.

**Comment by NightScale5755** [comment]
Hmm. No dice. I probably should've said this from the get-go, but Libsdiguises enables, sure. But it bugs out. The commands can be used, but they don't do anything. No errors. No logs. Nothing.

**Comment by IzzelAliz** [comment]
![图片](https://user-images.githubusercontent.com/21029868/110197736-8a8bc580-7e88-11eb-8110-e8ebc30f3348.png)

Works on my machine. Maybe you need to update ProtocolLib.

**Comment by NightScale5755** [comment]
hmm.. Fair. I'll see if it's a mod conflict and get back to you.

**Comment by NightScale5755** [comment]
ok. So. After some extensive testing, the conflict seems to derive from mods that add a world type. I.e. BiomesOPlenty, Terraforged, perhaps others. I personally, can easily find alternatives. But you should probably put a warning in the readme about world types causing plugin issues, (They did in 1.12.2), unless you're able to fix it? If this is good enough though, feel free to close the issue. Thanks so much for the help!

**Comment by segg21** [comment]
@NightScale5755 curious to know, does having a custom level break most plugins? Very interesting, in-fact I may remove these mods from my server as I’m unaware. I’ve just now discovered this, something like Mohist? I was using Magma during 1.12, but want to update. Is this recommended?!

Thanks!

**Comment by NightScale5755** [comment]
oh. So in 1.12.2, using both Magma and Mohist, I found that custom world types broke SkinsRestorer. You'd be able to see other people's skins, but not your own. That's just one example.

**Comment by segg21** [comment]
> oh. So in 1.12.2, using both Magma and Mohist, I found that custom world types broke SkinsRestorer. You'd be able to see other people's skins, but not your own. That's just one example.

Sorry, to be clear I'm moving away from 1.12 to 1.16. Would you prefer Arch, being more stable than Mohist? (Magma doesn't support 1.16 yet)

**Comment by NightScale5755** [comment]
ah. I was just giving an example as to how custom world types tend to break things. As for stability? Yeah. Mohist is doing their best. But ArcLight's better imo.
