### ISSUE TITLE
[1.16.5]重生点失效

### ISSUE THREAD

**Issue by Light-FD** [IzzelAliz/Arclight#188]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.14-3408941]

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [Java 11] 

* **操作系统** [Windows 10]

* **插件列表**
无
* **Mod 列表**
无

### 错误描述
玩家只能保存一次重生点
玩家用任何方式(床、重生錨、/spawnpoint指令) 设置重生点
死亡后，第一次正常在设定的重生点复活，然后重生点失效(用spawnpoint指令还能听到重生錨失效的音效)
第二次复活就在世界重生点了
### 重现步骤
同错误描述
**可在 Forge 复现** [否_用相同客户端未能在单机实现]

**可在 Spigot 复现** [否]

### 报错信息
无报错

**Comment by IzzelAliz** [comment]
与 #160 重复
