### ISSUE TITLE
书与笔用不了

### ISSUE THREAD

**Issue by Light-FD** [IzzelAliz/Arclight#191]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.14-3408941] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [Java 11]

* **操作系统** [WIndows 10]

* **插件列表**
无
* **Mod 列表**
无

### 错误描述
书与笔无法编辑，尝试保存时被踢出服务器

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息
![`5{U}01AGA_ })}WL1 8W4Q](https://user-images.githubusercontent.com/72667062/110181125-15979c00-7e46-11eb-9d34-eb16095860be.png)
实际上并不是他描述的编辑过快，我试过输入一个字，然后挂了10分钟再保存也一样
### 重现步骤

1. 安装 Arclight 1.0.14
2. 进入服务器
3. 获取书与笔(指令/give @s minecraft:writable_book)
4. 打开并输入任意字符
5. 保存

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

> [06:28:22] [Server thread/INFO] [minecraft/DedicatedServer]: Light join the game
> [06:28:22] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Light lost connection: Book edited too quickly!
> [06:28:22] [Server thread/INFO] [minecraft/DedicatedServer]: Light left the game
> [06:28:22] [Server thread/WARN] [minecraft/NetworkManager]: handleDisconnection() called twice
>

**Comment by IzzelAliz** [comment]
与 #157 重复
