### ISSUE TITLE
更新部分mod後啟動服務器崩潰,而新世界或Forge無此問題

### ISSUE THREAD

**Issue by Edel-Lilies** [IzzelAliz/Arclight#194]
### 我正在运行

* **Arclight** [1.16-1.0.15R] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0.281] 

* **操作系统** [win10]

* **插件列表** 

* **Mod 列表** 

### 错误描述
更新部分mod後服務器啟動崩潰
創建新世界則不會出現該問題
Forge端啟動也無問題

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1.更新了一部分mod
2.啟動服務器後崩潰
3. ....

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
[latest.log](https://github.com/IzzelAliz/Arclight/files/6096575/latest.log)
[crash-2021-03-07_14.05.12-server.txt](https://github.com/IzzelAliz/Arclight/files/6096577/crash-2021-03-07_14.05.12-server.txt)

**Comment by IzzelAliz** [comment]
请测试最新版是否修复

**Comment by Edel-Lilies** [comment]
已修復,感謝
