### ISSUE TITLE
PlayerInteractEvent being called twice

### ISSUE THREAD

**Issue by victorbetoni** [IzzelAliz/Arclight#198]
### I am running

* **Arclight** 1.0.15

* **This is the latest development version** [Y]

* **Java** 15.0.1

* **Operating System** Ubuntu 16

* **Plugins** None

* **Mods** None

### Description

The PlayerInteractEvent is always being called twice. I tested 9 or 10 more events and none had the same problem. Apparently this only happens with this specific event. I tested this in a clean environment, with no mods or plugins, I just put a plugin which has only one listener for this event, and even when I just click with the right or left button, the event is listened twice.

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

**Comment by IzzelAliz** [comment]
That is intended, one for main hand and one for off hand. Spigot has same behaviour.

**Comment by victorbetoni** [comment]
Oh, sorry, I'm used to develop for lower versions as 1.6 and 1.8. Two hands is something new for me
