### ISSUE TITLE
意志坚定不兼容服务端

### ISSUE THREAD

**Issue by PoseidonLi0514** [IzzelAliz/Arclight#202]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.15-7963742] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_281] 

* **操作系统** [win10+1909]

* **插件列表** CoreProtect, LagAssist, LuckPerms, OreTeleport, PlaceholderAPI, VillagerOptimiser, MiaoBoard, GSit, Vault, ConsoleSpamFix, eBackup, LaggRemover, Essentials, EssentialsProtect, React, EssentialsChat, EssentialsAntiBuild, QuickShop, EssentialsSpawn, BetterSleeping3, AuthMe

* **Mod 列表** 

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [否]

**可在 Spigot 复现** [是/否]

### 报错信息

[https://paste.ubuntu.com/p/TDD3sVfcjw/]

**Comment by IzzelAliz** [comment]
无法修复，请反馈至作者

https://github.com/Glitchfiend/ToughAsNails/issues/681
