### ISSUE TITLE
Denizen not working

### ISSUE THREAD

**Issue by Matthysse** [IzzelAliz/Arclight#204]
### I am running

* **Arclight** arclight-forge-1.16-1.0.16-SNAPSHOT

* **Java** 11

* **Plugins** Citizens, Essentials X, FastAsyncWorldEdit, SuperChairs, WorldGuard, Denizen

* **Mods** Adorn,Alexmobs,builderadditions,camera,citadel,exoticbirds,extlights,kotlinforforge,lithium,Mantle,notenoughcreativity,obfuscate,starlight,vehicle-mod

### Description

The Denizen plugin doesn't work, no error, and it is in green in the plugins menu, but the commands just do nothing with nothing in the logs or console, and other commands that are added to citizens like /npc sit don't work too.

### Step to reproduce

1. Do /denizen, see that nothing appears

**Comment by segg21** [comment]
Do you have premium Citizens? Cause I don't think the old one works. 

Also, Citizens soft depends on [Vault](https://www.spigotmc.org/resources/vault.34315/). I suggest also installing.

**Comment by Matthysse** [comment]
Citizens is only chargeable on Spigot, you can get the updated version on their Jenkins for free. Citizens itself works with ArcLight, it's really Denizen that doesn't work.

I already have Vault.
