### ISSUE TITLE
无法将事件PlayerInteractEvent传递给UltimateClaims v1.5.0

### ISSUE THREAD

**Issue by wkurumi** [IzzelAliz/Arclight#205]
### 我正在运行arclight-1.16.5-1.0.16-SNAPSHOT-1dffda9

* **Arclight** [版本] 

* **你确认这是最新版吗** [是/否，因为___]是

* **你确认所有Mod都安装了依赖** [是/否]是

* **你确认所有插件都已更新至对应版本** [是/否]是

* **Java** [版本] java8-281

* **操作系统** [名称+版本]Windows10

* **插件列表** UltimateClaims v1.5.0

* **Mod 列表** 植物魔法

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [是/否]否

**可在 Spigot 复现** [是/否]否

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/bdJNPpvJDM/

**Comment by IzzelAliz** [comment]
请去掉 OmitStackTraceInFastThrow 启动参数重新测试
