### ISSUE TITLE
Items NBT data being reseted.

### ISSUE THREAD

**Issue by victorbetoni** [IzzelAliz/Arclight#206]
### I am running

* **Arclight** [1.0.16]

* **This is the latest development version** [Y]

* **Java** [1.8]

* **Operating System** Windows 10

* **Plugins** No plugins.

* **Mods** CraftingDead and TravelersBackpack

### Description

When you quickly move an ItemStack that holds NBT data through the slots of an inventory, the ItemStack will have its NBT tags reset. Sometimes it is not necessary to move quickly, just placing it in another slot can cause it to lose data. You can see me reproducing this bug: https://youtu.be/QSjO57kpqb0 

I used the CraftingDead and TravelersBackpack mods to reproduce this bug. If you pay attention to the gun's ammo, you will notice that they reset when the gun is moved quickly from slot to slot. Btw, I tested this on singleplayer just to make sure it's not a mod related issue.

### Step to reproduce

1. Get any item which holds any nbt data.
2. Start moving it quickly in your inventory

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

-->

**Comment by Arzio** [comment]
Update: It seems the problem could only be present in an ArcLight environment, as we (me and OP) tried to reproduce the problem in a Multiplayer LAN world (without ArcLight) without success.

**Comment by IzzelAliz** [comment]
What if removing the TravelersBackpack mod

**Comment by victorbetoni** [comment]
Still happens
