### ISSUE TITLE
KemonoCraft(动物朋友)模组加载崩溃

### ISSUE THREAD

**Issue by MineAurora** [IzzelAliz/Arclight#211]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.17-SNAPSHOT-c6c38b0] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [jdk1.8.0_281] 

* **操作系统** [win10_19042]

* **插件列表** 

* **Mod 列表** 
KemonoCraft-1.16.4-0.3.16.jar

### 错误描述

Arclight服务端加载崩溃,纯forge端下加载正常.

### 重现步骤

1. 安装 KemonoCraft-1.16.4-0.3.16.jar
2. 启动服务端后崩溃

**可在 Forge 复现** [否]

### 报错信息

[https://paste.ubuntu.com/p/3tKzzkwkTn/]

**Comment by IzzelAliz** [comment]
该 Mod 混淆无法提供修复
