### ISSUE TITLE
无法加载TrChat

### ISSUE THREAD

**Issue by 3269199948** [IzzelAliz/Arclight#216]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.16] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8] 

* **操作系统** [centos7.5]

* **插件列表** no

* **Mod 列表** no

### 错误描述

无法加载

### 重现步骤

1. 将trchat放入plugins中
2. 加载报错

**可在 Forge 复现** [是/否]

**可在 Spigot 复现** [是/否]

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/FnzdMXx39g/

**Comment by IzzelAliz** [comment]
请联系 TrChat 开发者升级 TabooLib Loader 版本
