### ISSUE TITLE
不兼容的插件

### ISSUE THREAD

**Issue by 3269199948** [IzzelAliz/Arclight#220]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.16] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_281] 

* **操作系统** [centos7.5]

* **插件列表** LuckPerms, PlaceholderAPI, SpringAround, CMILib, TAB-BukkitBridge, Vault, ProtocolLib, Multiverse-Core, WorldEdit, VentureChat, ChestCommands, WorldEditSUI, CMI, CoreProtect, CMIEInjector, QuickShop

* **Mod 列表** [09:50:33] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List: 
• minecraft forge-1.16.5-36.1.0-server.jar : minecraft (1.16.5) - 1
• mods_folder [mod][围火无怪]nohostilesaroundcampfire_1.16.5-3.3.jar : nohostilesaroundcampfire (3.3) - 1
• mods_folder [mod][超多生物群系]BiomesOPlenty-1.16.4-13.0.0.431-universal.jar : biomesoplenty (1.16.4-13.0.0.431) - 1
• mods_folder [mod][Macaw的屋顶]mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder [mod][FTB Ranks]ftb-ranks-1604.1.1.11.jar : ftbranks (1604.1.1.11) - 1
• mods_folder [mod][FTB前置]architectury-1.10.138-forge.jar : architectury (1.10.138) - 1
• mods_folder [mod][FTB前置]ftb-gui-library-1605.2.1.41-forge.jar : ftbguilibrary (1605.2.1.41) - 1
• mods_folder [mod][皮肤]CustomSkinLoader_Forge-14.13-SNAPSHOT-199.jar : customskinloader (14.13-SNAPSHOT-199) - 1
• mods_folder [mod][JEI物品管理器]jei-1.16.4-7.6.1.71.jar : jei (7.6.1.71) - 1
• arclight arclight-forge-1.16-1.0.16.jar : arclight (1.16.5-1.0.16-6f9c10a) - 1
• mods_folder [mod][末地扩展前置]abnormals_core-1.16.5-3.1.1.jar : abnormals_core (3.1.1) - 1
• mods_folder [mod][末地扩展]endergetic-1.16.4-3.0.0.jar : endergetic (3.0.0) - 1
• mods_folder [mod][FTB Chunks]ftb-chunks-1605.2.3-build.75.jar : ftbchunks (1605.2.3-build.75) - 1
• maven_libs forge-1.16.5-36.1.0-universal.jar : forge (36.1.0) - 1
• mods_folder [mod][经典状态条]classicbar-4.0.1-1.16.3.jar : classicbar (4.0.1-1.16.3) - 1
• mods_folder [mod][篝火前置]collective-1.16.5-2.25.jar : collective (2.25) - 1
• mods_folder [mod][治愈营火]healingcampfire_1.16.5-3.2.jar : healingcampfire (3.2) - 1
• mods_folder [mod][墓碑]gravestone-1.16.5-1.0.1.jar : gravestone (1.16.5-1.0.1) - 1
• mods_folder [mod][动态环绕]DynamicSurroundings-1.16.4-4.0.3.12.jar : dsurround (1.16.4-4.0.3.12) - 4
• mods_folder [mod][冰火传说前置]citadel-1.6.2.jar : citadel (1.6.2) - 1
• mods_folder [mod][冰火传说]iceandfire-2.1.6-1.16.4.jar : iceandfire (2.1.6-1.16.4) - 1
• mods_folder [mod][旅行者背包]TravelersBackpack-1.16.4-5.3.8.jar : travelersbackpack (5.3.8) - 1
> 

BC使用的是lightfall，登陆服用的是Paper，子服用的是Arclight

### 错误描述
当我在服务端中使用VentureChat插件时，这一切正常，当我使用lightfall跳转到特定服务器，并且按照插件配置BC模式
服务器玩家不能说话了，关闭BC模式时，一切正常

注：这里的BC模式指的是插件的BC模式

### 重现步骤

1. 安装 VentureChat
2. 进入服务器后，打开聊天栏聊天，一切正常
3. 进入VentureChat配置文件，找到channels下的Global，找到bungeecord将其设置为true，重载插件或重启服务器
4. 打开聊天啦，发现无法说话

注：其他非Arclight服务端中没有此问题，例：Cat，Paper，Spigot

---------------------------------------------------------------------------------------------------------------------------------
1.1.第二个问题，tab插件https://www.mcbbs.net/forum.php?mod=viewthread&tid=802303
2.1将其安装在lightfall中，子服安装TAB-BukkitBridge（一个用于同步当前服务器变量的东西）
3.1在lightfall的tab配置文件中随便写一个变量，要求每一个子服都能使用该变量（例如：LuckPerms的称号）
4.1重启服务器，首先进入登陆服务器，发现tab中的称号没有任何问题，然后进入子服，登陆服的称号任然存在tab中，并未变成当前服务器的称号

注：跳转到其他非Arclight服务端中没有此问题，例：Cat，Paper，Spigot

**可在 Forge 复现** [/否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

以前两个问题没有任何错误日志
-->

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by 3269199948** [comment]
> 请测试是否修复

将Arclight更改为1.17，lightfall改为actions中最新版，依旧出现该问题

**Comment by IzzelAliz** [comment]
你测试最新的构建版本，在 appveyor 下载2021年4月28日 11:39，3269199948 ***@***.***>写道：



请测试是否修复



将Arclight更改为1.17，lightfall改为actions中最新版，依旧出现该问题

**Comment by 3269199948** [comment]
> 你测试最新的构建版本，在 appveyor 下载2021年4月28日 11:39，3269199948 ***@***.***>写道： 请测试是否修复 将Arclight更改为1.17，lightfall改为actions中最新版，依旧出现该问题 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

修复啦，爱你哟，么么哒
