### ISSUE TITLE
关于 Better End 使用永恒传送门回到主世界，不加载地形bug

### ISSUE THREAD

**Issue by OcrSu** [IzzelAliz/Arclight#222]
### 我正在运行

* **Arclight** arclight-forge-1.16-1.0.17-SNAPSHOT.jar 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖**是

* **你确认所有插件都已更新至对应版本**是

* **Java**1.8.0 281 

* **操作系统**Windows Server 2019 Standard

* **插件列表**LuckPerms,BkTeleport,EntitytrackerFixer,Chunky,VillagerOptimiser 

* **Mod 列表**
* 仅加载Better End Mod Bug也会出现
* ? mods_folder 【玩家垃圾桶】TrashSlot_1.16.3-12.2.1.jar : trashslot (12.2.1) - 1
? mods_folder 【下界传送门修复】NetherPortalFix_1.16.3-7.2.1.jar : netherportalfix (7.2.1) - 1
? mods_folder 【JEA】JustEnoughAdvancements-1.16.4-0.1.1.jar : jea (1.16.4-0.1.1) - 1
? mods_folder 【物品管理器】jei-1.16.5-7.6.1.75.jar : jei (7.6.1.75) - 1
? mods_folder 【属性修复】AttributeFix-1.16.5-10.1.2.jar : attributefix (10.1.2) - 1
? mods_folder 【碧海新生 前置】abnormals_core-1.16.5-3.1.1.jar : abnormals_core (3.1.1) - 1
? mods_folder 【指路石】Waystones_1.16.5-7.4.0.jar : waystones (7.4.0) - 1
? mods_folder 【地球地图】TerraForged-1.16.4-0.2.9 (1).jar : terraforged (0.2.9) - 1
? mods_folder 【经验球优化】Clumps-6.0.0.17.jar : clumps (6.0.0.17) - 1
? mods_folder 【懒人厨房】CookingForBlockheads_1.16.5-9.3.1.jar : cookingforblockheads (9.3.1) - 1
? mods_folder 【优化前置】Placebo-1.16.4-4.4.1.jar : placebo (4.4.1) - 1
? mods_folder 【怪物药水效果】configurablemobpotioneffects_1.16.5-1.2.jar : configurablemobpotioneffects (1.2) - 1
? mods_folder 【前置】LibX-1.16.3-1.0.27.jar : libx (1.16.3-1.0.27) - 1
? mods_folder 【自然环境】environmental-1.16.5-1.0.0.jar : environmental (1.0.0) - 1
? mods_folder 【前置】u_team_core-1.16.5-3.2.0.193.jar : uteamcore (3.2.0.193) - 1
? mods_folder 【星光】starlight-forge-1.0.0-RC1-1.16.5.jar : starlight (1.0.0-RC1) - 1
? mods_folder 【雪魔法】SnowRealMagic-1.16.3-2.2.2.jar : snowrealmagic (2.2.2) - 1
? mods_folder 【前置】Kiwi-1.16.5-3.4.2.jar : kiwi (3.4.2) - 1
? mods_folder 【如果我是DJ】MCDJ-1.16.2-1.16.3-2.1.1.jar : mcdj (2.1) - 1
? mods_folder 【聊天头像】chat_heads_forge-0.2.0.jar : chat_heads (0.2.0) - 1
? maven_libs forge-1.16.5-36.1.0-universal.jar : forge (36.1.0) - 1
? mods_folder 【拓展】supplementaries-1.16.5-0.11.0b.jar : supplementaries (1.16.5-0.11.0) - 1
? mods_folder 【更好的末地】betterendforge-1.16.4-1.5.1.jar : betterendforge (1.16.4-1.5.1) - 1
? mods_folder 【更多箱子】ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1
? mods_folder 【古式地图】antiqueatlas-5.4.4-forge.jar : antiqueatlas (5.4.4-forge) - 1
? mods_folder 【地牢】Dungeonsarise1.16.5-1.2.68a-HF.jar : dungeons_arise (1.2.68a) - 1
? minecraft forge-1.16.5-36.1.0-server.jar : minecraft (1.16.5) - 1
? mods_folder 【碧海新生】upgrade_aquatic-1.16.5-3.1.0.jar : upgrade_aquatic (3.1.0) - 1
? mods_folder 【信标交流】Ping-1.16.4-1.6.9.jar : ping (1.16.4-1.6.9) - 1
? mods_folder 【有用的铁路】useful_railroads-1.16.5-1.4.6.36.jar : usefulrailroads (1.4.6.36) - 1
? mods_folder 【下界】EndRemastered-R36.jar : endrem (1.16.3) - 1
? mods_folder 【死亡坐标】DeathFinder-v1.3-1.16.2.jar : deathfinder (1.3) - 1
? mods_folder 【冰冻之下】rare-ice-0.2.2.jar : rare-ice (version) - 1
? mods_folder 【背包API】curios-forge-1.16.5-4.0.5.0.jar : curios (1.16.5-4.0.5.0) - 1
? mods_folder 【规则】sisser-1.7.jar : sisser (1.7) - 1
? mods_folder 【帕秋莎】Patchouli-1.16.4-50.jar : patchouli (1.16.4-50) - 1
? mods_folder 【前置】collective-1.16.5-2.25.jar : collective (2.25) - 1
? mods_folder 【寻找画】cyclepaintings_1.16.5-1.6.jar : cyclepaintings (1.6) - 1
? mods_folder 【工作台优化】FastWorkbench-1.16.4-4.5.1.jar : fastbench (4.5.1) - 1
? mods_folder 【背包】backpacked-1.9.0-1.16.3.jar : backpacked (1.9.0) - 1
? mods_folder 【建筑】buildersaddition-1.16.4-20210214a.jar : buildersaddition (1.16.4-20210214a) - 1
? mods_folder 【熔炉优化】FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
? mods_folder 【前置】architectury-1.10.139-forge.jar : architectury (1.10.139) - 1
? mods_folder 【前置】item-filters-1605.2.4-build.30-forge.jar : itemfilters (1605.2.4-build.30) - 1
? mods_folder 【前置】ftb-gui-library-1605.2.1.41-forge.jar : ftbguilibrary (1605.2.1.41) - 1
? mods_folder 【FTB团队】ftb-teams-1604.1.0.16-forge.jar : ftbteams (1604.1.0.16) - 1
? mods_folder 【圈地】ftb-chunks-1605.2.3-build.75.jar : ftbchunks (1605.2.3-build.75) - 1
? mods_folder 【FTB任务】ftb-quests-1605.2.1-build.39-forge.jar : ftbquests (1605.2.1-build.39) - 1
? mods_folder 【现代化UI】ModernUI-1.16.5-2.4.9.84-universal.jar : modernui (2.4.9.84) - 1
? mods_folder 【前置】cloth-config-4.11.18-forge.jar : cloth-config (4.11.18) - 1
? arclight arclight-forge-1.16-1.0.17-SNAPSHOT.jar : arclight (1.16.5-1.0.17-SNAPSHOT-c6c38b0) - 1
? mods_folder 【快速工作台】fastbenchminusreplacement-1.3.jar : fastbenchminusreplacement (1.3) - 1
? mods_folder 【装备展示】CosmeticArmorReworked-1.16.5-v1b.jar : cosmeticarmorreworked (1.16.5-v1b) - 1
? mods_folder 【脚手架掉落优化】scaffoldingdropsnearby_1.16.5-1.3.jar : scaffoldingdropsnearby (1.3) - 1
? mods_folder 【末影邮箱】EnderMail-1.16.5-1.2.0.jar : endermail (1.16.5-1.2.0) - 1 

### 错误描述
使用mod传送门回到主世界，不加载地形

### 重现步骤
在仅安装Better End的前提下
在末地中找到Eternal Portal（https://www.mcmod.cn/item/404927.html）永恒传送门，并激活，然后进入传送门
之后玩家界面便卡在加载地形中（可以听到主世界的环境音）
注：我尝试后台kill玩家，然后看到主世界的地形了（不完整，不可以操控）具体长这样http://i1.fuimg.com/735568/b1187eccc532538d.png

**可在 Forge 复现** 是

**可在 Spigot 复现** 否

### 报错信息

[错误日志]

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by ghost** [comment]
> 请测试是否修复

fix done
