### ISSUE TITLE
Movecraft Incompatibility

### ISSUE THREAD

**Issue by MystefMC** [IzzelAliz/Arclight#223]
### I am running arclight-1.15.2-1.0.3-SNAPSHOT-9455d03

* **Arclight** [VERSION] 

* **This is the latest development version** [**Y**/N, because it is latest on website]

* **Java** [VERSION] 
Java not the problem
* **Operating System** [NAME & VERSION]
Windows 10
* **Plugins** 
Movecraft, EssentialsX, PermissionsEx, WorldGuard
* **Mods** 
N/A none 

### Description
After extensive testing, me and a Movecraft developer friend, came to the conclusion that Movecraft is not supported by ArcLight, we replicated exactly everything in Spigot, plugins only and it worked perfectly. Everything kind of works in Arclight, the commands work perfectly, but the problem is the core function of the plugin, the craft doesn't move at all. The way the crafts function are is that basically a block moves (it's really hard to explain so here is a youtube video with some movecraft craft battles) But yeah, this function of the plugin doesn't work at all in Arclight which is really weird. I went over the crash files and everything just really confusing tbh I'm really stumped on this one

### Step to reproduce

1. Install something
2. ....
3. ....

**Reproducible in Forge** [Y/N]

**Reproducible in Spigot** [**Y**/N]

### Logs

[ERROR LOG]

[latest.log](https://github.com/IzzelAliz/Arclight/files/6251795/latest.log)

**Comment by timi137137** [comment]
hummm，first i need say sorry，it takes so long to get back to you. second，maybe you can tell me plugins version? or you can packing plugins upload to google drive/mega  give me download?I'll test it as soon as possible

**Comment by ccorp2002** [comment]
@timi137137 Sorry about the ping, but I get the same thing with the plugin, here is the github link of what they're likely using

https://github.com/eirikh1996/Movecraft

**Comment by ccorp2002** [comment]
> @timi137137 Sorry about the ping, but I get the same thing with the plugin, here is the github link of what they're likely using
> 
> https://github.com/eirikh1996/Movecraft

It is something to do with the:
 https://github.com/eirikh1996/Movecraft/blob/master/modules/v1_16_R3/src/main/java/net/countercraft/movecraft/compat/v1_16_R3/IWorldHandler.java -Class and NMS, so if you could figure out how one would get around that issue, it would be of huge importance to the wider Movecraft community as a whole.

**Comment by timi137137** [comment]
> > @timi137137 Sorry about the ping, but I get the same thing with the plugin, here is the github link of what they're likely using
> 
> > 
> 
> > https://github.com/eirikh1996/Movecraft
> 
> 
> 
> It is something to do with the:
> 
>  https://github.com/eirikh1996/Movecraft/blob/master/modules/v1_16_R3/src/main/java/net/countercraft/movecraft/compat/v1_16_R3/IWorldHandler.java -Class and NMS, so if you could figure out how one would get around that issue, it would be of huge importance to the wider Movecraft community as a whole.

OK,i get it.
