### ISSUE TITLE
MySQL Error when connecting

### ISSUE THREAD

**Issue by denireilly** [IzzelAliz/Arclight#226]
I am running  arclight-forge-1.16-1.0.16.jar

* **Java**
openjdk version "11.0.11-ea" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1)
OpenJDK 64-Bit Server VM (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1, mixed mode, sharing)

* **Operating System** 
Ubuntu 1.16

* **Plugins** 
Plugins (28): AnimationLib, HealthBar, GroupManager, AutoBroadcast, BuycraftX, BanManager, ProtocolLib, TCDRspawn, VoxelSniper, TCDUtils, TCD-CORE, TCDProxy, CommandCooldown, TCDSpawn, UltimateBossBar, Vault, HideStream, WorldEdit, Essentials, HolographicDisplays, WorldGuard, Citizens, EssentialsProtect, EssentialsChat, AntiVPN, CommandNPC, EssentialsSpawn, CoreProtect

* **Mods** 
Mod List: 
06.04 17:45:00 [Server] INFO • minecraft forge-1.16.5-36.1.0-server.jar : minecraft (1.16.5) - 1
06.04 17:45:00 [Server] INFO • mods_folder voice_chat-1.16.5-0.2.0.5-SNAPSHOT.jar : voicechat (0.2.0.5-SNAPSHOT) - 1
06.04 17:45:00 [Server] INFO • mods_folder betteranimalsplus-1.16.4-10.1.0.jar : betteranimalsplus (10.1.0) - 1
06.04 17:45:00 [Server] INFO • mods_folder ImmersiveEngineering-1.16.5-4.2.4-134.jar : immersiveengineering (1.16.5-4.2.4-134) - 1
06.04 17:45:00 [Server] INFO • mods_folder u_team_core-1.16.5-3.2.0.193.jar : uteamcore (3.2.0.193) - 1
06.04 17:45:00 [Server] INFO • mods_folder mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
06.04 17:45:00 [Server] INFO • mods_folder mcw-doors-1.0.2-mc1.16.5.jar : mcwdoors (1.0.2) - 1
06.04 17:45:00 [Server] INFO • mods_folder cfm-7.0.0-pre19-mc1.16.3.jar : cfm (7.0.0-pre19) - 1
06.04 17:45:00 [Server] INFO • mods_folder mcw-furniture-2.0.1-mc1.16.5.jar : mcwfurnitures (2.0.1) - 1
06.04 17:45:00 [Server] INFO • mods_folder MekanismGenerators-1.16.5-10.0.21.448.jar : mekanismgenerators (10.0.21) - 1
06.04 17:45:00 [Server] INFO • mods_folder crafting-dead-core-1.16.4-1.2.7-alpha.jar : craftingdead (1.2.7-alpha) - 1
06.04 17:45:00 [Server] INFO • mods_folder jei-1.16.4-7.6.1.71.jar : jei (7.6.1.71) - 1
06.04 17:45:00 [Server] INFO • arclight arclight-forge-1.16-1.0.16.jar : arclight (1.16.5-1.0.16-6f9c10a) - 1
06.04 17:45:00 [Server] INFO • mods_folder Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
06.04 17:45:00 [Server] INFO • mods_folder mcw-windows-1.0.2-mc1.16.4.jar : mcwwindows (1.0.2) - 1
06.04 17:45:00 [Server] INFO • maven_libs forge-1.16.5-36.1.0-universal.jar : forge (36.1.0) - 1
06.04 17:45:00 [Server] INFO • mods_folder AppleSkin-mc1.16.2-forge-1.0.14.jar : appleskin (1.0.14) - 1
06.04 17:45:00 [Server] INFO • mods_folder VendingMachine-1.16.2-1.0.0.4.jar : vm (1.0.0.4) - 1
06.04 17:45:00 [Server] INFO • mods_folder pamhc2foodcore-1.16.3-1.0.2.jar : pamhc2foodcore (version) - 1
06.04 17:45:00 [Server] INFO • mods_folder DynamicSurroundings-1.16.4-4.0.3.12.jar : dsurround (1.16.4-4.0.3.12) - 4
06.04 17:45:00 [Server] INFO • mods_folder XaerosWorldMap_1.12.2_Forge_1.16.5.jar : xaeroworldmap (1.12.2) - 1
06.04 17:45:00 [Server] INFO • mods_folder corpse-1.16.4-1.0.6.jar : corpse (1.16.4-1.0.6) - 1
06.04 17:45:00 [Server] INFO • mods_folder [1.16.5]+SecurityCraft+v1.8.21.1.jar : securitycraft (v1.8.21.1) - 1
06.04 17:45:00 [Server] INFO • mods_folder TravelersBackpack-1.16.4-5.3.8.jar : travelersbackpack (5.3.8) - 1
06.04 17:45:00 [Server] INFO • mods_folder hcdservercore-1.2.0.jar : hcdservercore (1.2.0) - 1

### Description
So we have a few plugins that are connecting to a local hosted mysql database, and they used to be able to connect back in version arclight-forge-1.16-1.0.13.jar, but we recently upgraded to the latest at the time and none of the plugins can load

### Step to reproduce

1. install a plugin that can use mysql
2. run the server 

**Reproducible in Forge** well worked in arclight-forge-1.16-1.0.13.jar

**Reproducible in Spigot** well worked in arclight-forge-1.16-1.0.13.jar

### Logs

https://paste.ubuntu.com/p/hYQSx8WhSw/

**Comment by denireilly** [comment]
06.04 18:00:41 [Server] Server thread/ERROR Error occurred while enabling TCD-CORE v1.0 (Is it up to date?)
06.04 18:00:41 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
06.04 18:00:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:453) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:classloading}
06.04 18:00:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:181) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:classloading}
06.04 18:00:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:172) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:classloading}
06.04 18:00:41 [Server] INFO at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:117) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:classloading,re:mixin,re:mixin}
06.04 18:00:41 [Server] INFO at dev.kgtech.eddy.core.modules.Module.registerRepeatingTask(Module.java:67) ~[?:?] {re:classloading,re:classloading,re:classloading}
06.04 18:00:41 [Server] INFO at dev.kgtech.eddy.core.modules.modules.stats.StatsModule.onEnable(StatsModule.java:40) ~[?:?] {re:classloading,re:classloading,re:classloading}
06.04 18:00:41 [Server] INFO at dev.kgtech.eddy.core.modules.Module.enable(Module.java:25) ~[?:?] {re:classloading,re:classloading,re:classloading}
06.04 18:00:41 [Server] INFO at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[?:?] {}
06.04 18:00:41 [Server] INFO at dev.kgtech.eddy.core.modules.ModuleManager.enableAll(ModuleManager.java:37) ~[?:?] {re:classloading,re:classloading,re:classloading}
06.04 18:00:41 [Server] INFO at dev.kgtech.eddy.core.CorePlugin.onEnable(CorePlugin.java:38) ~[?:?] {re:classloading,re:classloading,re:classloading}
06.04 18:00:41 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
06.04 18:00:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:351) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A,re:mixin}
06.04 18:00:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:classloading,re:mixin}
06.04 18:00:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:493) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin,re:mixin}
06.04 18:00:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:407) ~[arclight:arclight-1.16.5-1.0.17-SNAPSHOT-f31f8ec] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin,re:mixin}
06.04 18:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.handler$zpo000$arclight$enablePlugins(MinecraftServerMixin.java:1977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 18:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 18:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 18:00:41 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
06.04 18:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 18:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
06.04 18:00:41 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?] {}

**Comment by IzzelAliz** [comment]
This is not caused by Arclight. Please recheck your plugin configuration.
