### ISSUE TITLE
Tinkers Construct casting process and blocks broken

### ISSUE THREAD

**Issue by Evolution0** [IzzelAliz/Arclight#227]
### I am running

* **Arclight** 1.0.16 

* **This is the latest development version** [Y/N, because ___]

No, will test next, just discovered the snapshot builds.

Update: Tested latest snapshot, no difference.

* **Java** 1.8.0_282 

* **Operating System** Windows 10 Pro x64 version 20H2

* **Plugins** 
  * ClearLag
  * LuckPerms
  * NoDestructoCreeper
  * Vault
  * Economy
  * Companies
  * ChestShop
  * EssentialsX
  * MysqlEconomyBank
  * EssentialsChat
  * JobsReborn

* **Mods** 

  - advancedperipherals-0.4b.jar
  - AkashicTome-1.4-16.jar
  - appliedenergistics2-8.2.0.jar
  - architectury-1.10.139-forge.jar
  - autooredictconv-1.16.4-16.1.8.jar
  - AutoRegLib-1.6-47.jar
  - BetterCaves-Forge-1.16.4-1.1.1.jar
  - BetterMineshafts-Forge-1.16.4-2.0.3.jar
  - BiomesOPlenty-1.16.4-13.0.0.432-universal.jar
  - BloodMagic-1.16.4-3.1.0-15.jar
  - Bookshelf-1.16.5-10.0.7.jar
  - carryon-1.16.5-1.15.3.13.jar
  - cc-tweaked-1.16.4-1.95.3.jar
  - Clumps-6.0.0.17.jar
  - cofh_core-1.16.4-1.2.1.jar
  - CraftingTweaks_1.16.3-12.2.0.jar
  - curios-forge-1.16.5-4.0.5.0.jar
  - CyclopsCore-1.16.5-1.11.5.jar
  - DarkUtilities-1.16.5-8.0.3.jar
  - DynamicSurroundings-1.16.4-4.0.4.1.jar
  - EssentialsXChat-2.19.0-dev+101-0668e4c.jar
  - EvilCraft-1.16.5-1.1.1.jar
  - ExtremeReactors2-1.16.4-2.0.23.jar
  - FallingTree-Forge-1.16.5-2.11.0.jar
  - FastFurnace-1.16.4-4.4.0.jar
  - FastWorkbench-1.16.4-4.5.1.jar
  - ftb-backups-2.1.1.6.jar
  - ftb-chunks-1605.2.3-build.75.jar
  - ftb-gui-library-1605.2.1.41-forge.jar
  - ftb-teams-1604.1.0.16-forge.jar
  - geckolib-forge-1.16.5-3.0.19.jar
  - GodlyVampirism-1.16.4-1.0.1.jar
  - Hwyla-forge-1.10.11-B78_1.16.2.jar
  - industrial-foregoing-1.16.5-3.2.10.2-d316328.jar
  - industrial-foregoing-1.16.5-3.2.11-55cb112.jar
  - ironchest-1.16.4-11.2.10.jar
  - jei-1.16.5-7.6.1.75.jar
  - JustEnoughResources-1.16.3-0.12.0.100.jar
  - mahoutsukai-1.16.5-v1.28.3.jar
  - mana-and-artifice-1.3.0.2.jar
  - Mantle-1.16.5-1.6.79.jar
  - mcw-bridges-1.0.5-mc1.16.5-4.jar
  - mcw-doors-1.0.2-mc1.16.5.jar
  - mcw-roofs-2.0.1-mc1.16.5-4.jar
  - mcw-windows-1.0.3-mc1.16.5.jar
  - mdecore-1.16.4-16.1.0.jar
  - Mekanism-1.16.5-10.0.21.448.jar
  - MekanismAdditions-1.16.5-10.0.21.448.jar
  - MekanismGenerators-1.16.5-10.0.21.448.jar
  - MekanismTools-1.16.5-10.0.21.448.jar
  - morered-1.16.5-2.1.0.2.jar
  - Patchouli-1.16.4-50.jar
  - Placebo-1.16.4-4.4.1.jar
  - Psi+1.16-92.jar
  - psipherals-1.4.0.jar
  - Quark-r2.4-309.jar
  - randompatches-2.4.4-forge.jar
  - RapidLeafDecay-1.16.5-1.0.0.jar
  - Runelic-1.16.5-7.0.1.jar
  - TConstruct-1.16.5-3.0.2.78.jar
  - thermal_cultivation-1.16.4-1.2.0.jar
  - thermal_dyenamics-1.16.4-1.0.0.jar
  - thermal_expansion-1.16.4-1.2.0.jar
  - thermal_foundation-1.16.4-1.2.0.jar
  - thermal_innovation-1.16.4-1.2.0.jar
  - thermal_locomotion-1.16.4-1.2.0.jar
  - titanium-1.16.5-3.2.8.jar
  - tombstone-1.16-6.3.3.jar
  - TravelersBackpack-1.16.5-5.4.0.jar
  - VampiresNeedUmbrellas-1.16.4-1.1.jar
  - Vampirism-1.16.4-1.7.8.jar
  - VampirismIntegrations-1.16.4-1.5.0.jar
  - WailaHarvestability-mc1.16.x-forge-1.1.14.jar
  - walljump-forge-1.16.4-1.3.7.jar
  - WAWLA-1.16.5-8.0.1.jar
  - YungsApi-1.16.4-Forge-6.jar
  - ZeroCore2-1.16.4-2.0.21.jar

### Description

When attempting to create a Smeltery Controller via placing a Seared Heater into a Casting Basin and pouring Molten Copper into it after the cooling animation plays it seems to have created the Smeltery Controller based on the texture of the block within the basin however you cannot remove this block from the basin.

### Step to reproduce

1. Install latest stable Forge for 1.16.5
2. Install Tinkers Construct 1.16.5-3.0.2.78
3. Install latest Mantle
4. Generate a world
5. Place a Seared Heater
6. Place a Seared Melter on top of it
7. Place a Seared Faucet on the right side of the Seared Melter
8. Place a Casting Basin under the Seared Faucet
9. Place some coal into the Seared Heater
10. Place 3 Copper Ore into the Seared Melter
11. Wait for the Copper Ore to melt
12. Place a Seared Heater into the Casting Basin
13. Right-Click the Seared Faucet
14. Wait for the fade to brown animation to finish on the Seared Heater

**Reproducible in Forge** [Y/N]
No.

### Logs

[ERROR LOG]
[debug.log](https://github.com/IzzelAliz/Arclight/files/6280872/debug.log)

See [my issue here on Tinkers Construct's Issues tracker](https://github.com/SlimeKnights/TinkersConstruct/issues/4319) for additional info, testing, and screenshots.

Update: Added debug.log

**Comment by IzzelAliz** [comment]
Please test with latest build.
