### ISSUE TITLE
Aquaculture 2 无法获取 海王恩惠 内的物品

### ISSUE THREAD

**Issue by RealSeek** [IzzelAliz/Arclight#228]
### 我正在运行

* **Arclight** [版本] 
arclight-forge-1.16-1.0.17-SNAPSHOT.jar
* **你确认这是最新版吗** [是/否，因为___]

是
* **你确认所有Mod都安装了依赖** [是/否]
是
* **你确认所有插件都已更新至对应版本** [是/否]

是
* **Java** [版本] 
graalvm-ce-java11
* **操作系统** [名称+版本]
windows server 2019
* **插件列表** 
PlaceholderAPI, HyperSleep, OverallGamerule, VillagerOptimiser, BanItem, LimitPillagers, AmazingBot, GSit, Vault, Lores, LaggRemover, ProtocolLib, Essentials, EssentialsProtect, EssentialsChat, GroupManager, EssentialsSpawn, AuthMe, AMWhiteList
* **Mod 列表** 
 mods_folder good-nights-sleep-1.16.5-1.2.14.jar : good_nights_sleep (1.2.14) - 1
• mods_folder pamhc2trees-1.16.3-1.0.0.jar : pamhc2trees (1.0.0) - 1
• mods_folder BiomesOPlenty-1.16.4-13.0.0.432-universal.jar : biomesoplenty (1.16.4-13.0.0.432) - 1
• mods_folder projectvibrantjourneys-1.16.5-3.0.0BETA4.jar : projectvibrantjourneys (1.16.5-3.0.0BETA4) - 1
• mods_folder starlight-forge-0.0.3.jar : starlight (0.0.3) - 1
• mods_folder pamhc2crops-1.16.3-1.0.1.jar : pamhc2crops (version) - 1
• mods_folder jei-1.16.4-7.6.1.65.jar : jei (7.6.1.65) - 1
• arclight arclight-forge-1.16-1.0.16.jar : arclight (1.16.5-1.0.16-6f9c10a) - 1
• mods_folder abnormals_core-1.16.5-3.1.1.jar : abnormals_core (3.1.1) - 1
• mods_folder endergetic-1.16.4-3.0.0.jar : endergetic (3.0.0) - 1
• mods_folder pamhc2foodextended-1.16.3-1.0.1.jar : pamhc2foodextended (version) - 1
• maven_libs forge-1.16.5-36.1.0-universal.jar : forge (36.1.0) - 1
• mods_folder Aquaculture-1.16.5-2.1.16.jar : aquaculture (1.16.5-2.1.16) - 1
• mods_folder create-mc1.16.3_v0.3e.jar : create (mc1.16.3_v0.3e) - 1
• mods_folder SubWild-1.16.5-1.1.2.jar : subwild (1.1.2) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.2.jar : pamhc2foodcore (version) - 1
• mods_folder DynamicSurroundings-1.16.4-4.0.4.1.jar : dsurround (1.16.4-4.0.4.1) - 4
• mods_folder CookingForBlockheads_1.16.5-9.3.1.jar : cookingforblockheads (9.3.1) - 1
• mods_folder dungeonsarise1.16.5-1.2.68a-HF.jar : dungeons_arise (1.2.68a) - 1

### 错误描述
在单人模式 有概率钓出mod的箱子 从箱子里开出 水产养殖2(Aquaculture 2) 的装备和锭 
在服务端中 水产养殖2(Aquaculture 2) 无法通过mod钓上来的箱子获取 mod的锭和装备
(在服务器内 钓出来的箱子内没有物品)

在cf询问过mod作者 
作者给我的回答(作者原话)：
> I assume you're using a Forge/Bukkit hybrid server, which would be your problem.

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 水产养殖2(Aquaculture 2)
2. 进入服务器后 使用mod钓竿钓鱼
3. 当钓出 mod物品:'海王恩惠' 后 箱子内无战利品

**可在 Forge 复现** [是/否]
否

**可在 Spigot 复现** [是/否]

### 报错信息
无
[错误日志]

**Comment by IzzelAliz** [comment]
https://github.com/IzzelAliz/Arclight/issues/143 有用户反馈已经修复，请测试 1.0.16 与最新构建

**Comment by LittleHed** [comment]
Arclight 1.0.17 单模组测试 仍然复现

**Comment by IzzelAliz** [comment]
请使用最新构建测试
