### ISSUE TITLE
FastWorkbench compatibility issue.

### ISSUE THREAD

**Issue by fatea-k** [IzzelAliz/Arclight#23]
https://paste.ubuntu.com/p/GVt3mrWVVH/
1.15.2版本下发生的问题，虽然不知道是什么导致的，如果能解决掉，非常感激

**Comment by IzzelAliz** [comment]
FastWorkbench 与本端不兼容

**Comment by IzzelAliz** [comment]
Fixed in https://github.com/Shadows-of-Fire/FastWorkbench/commit/d27e2b869474d17e1ccef8728916bf3d7f37c813
