### ISSUE TITLE
MOD创建的传送门，实体碰撞必崩

### ISSUE THREAD

**Issue by 864063334** [IzzelAliz/Arclight#233]
### 我正在运行

* **Arclight** [最新] 

* **你确认这是最新版吗** [是，因为___]

* **你确认所有Mod都安装了依赖** [是/否]

* **你确认所有插件都已更新至对应版本** [是]

Java** [11] 

操作系统** [winserver209]

插件列表** 

Mod 列表
暮色，或者虚无，或者沉浸，任意一个，或者其他

### 错误描述

请尽可能详细。对于描述，请假设开发者不知道 mod 是干什么的。
     使用任意mod创建的指定传送门，实体碰撞，必崩
     目前已经测试过三个MOD创建的传送门
     沉浸也会，只要是MOD创建的传送门，都会崩

### 重现步骤

1. 安装 xxx
2. 进入服务器后 使用实体到MOD创建的传送门，或者射箭到传送门
3. 崩服

**Comment by vitechliu** [comment]
确实，刚装了虚无3，崩了3次。确认了下是我把僵尸推进去瞬间崩的。
贴个[crash report](https://gist.github.com/liuzirui1122/a41147ae5e7a23e6e259d293bb796da9)
