### ISSUE TITLE
可能是improvedmobs问题？

### ISSUE THREAD

**Issue by MrShellad** [IzzelAliz/Arclight#236]
### 我正在运行Arclight version arclight-1.16.5-1.0.17-SNAPSHOT

* **Arclight** [版本] 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖**是

* **你确认所有插件都已更新至对应版本**是

* **Java** [版本] 
Java8
* **操作系统** [名称+版本]
windows10
* **插件列表** 

* **Mod 列表** 

### 重现步骤

进入游戏无论生成怪物可以轻松复现

**可在 Forge 复现** [是/否]

**可在 Spigot 复现** [是/否]

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/qpfX6cjwM6/

**Comment by IzzelAliz** [comment]
作者已经修复，请自行构建或者等待新版本发布
