### ISSUE TITLE
ess，jei装上后可以使用作弊模式，玩家无OP，没法使用作弊指令

### ISSUE THREAD

**Issue by PoseidonLi0514** [IzzelAliz/Arclight#237]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.17-831b37b] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_281] 

* **操作系统** [win10 20h2]

* **插件列表** 
* Essentials

* **Mod 列表** 
* • minecraft forge-1.16.5-36.1.4-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.1.4-universal.jar : forge (36.1.4) - 1
• mods_folder jei-1.16.5-7.6.4.86.jar : jei (7.6.4.86) - 1
• arclight arclight-forge-1.16-1.0.17.jar : arclight (1.16.5-1.0.17-831b37b) - 1

### 错误描述
如果服务端装了ess（只有一个本体）和jei，客户端也装只装jei进服务端的情况下，并且那个玩家不是OP，没法使用任何作弊命令，可以开jei的作弊模式拿取物品

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 jei ，ess
2. 进入服务器后 jei开启作弊模式
3. 玩家不是OP，没有任何作弊权限的前提下可以拿取物品

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

latest.log[https://paste.ubuntu.com/p/nrKrBXYf3y/]

**Comment by 1103958779** [comment]
这个问题我在mohist服务器端核心上也出现过，我是通过删除jei解决的，怀疑是jei的问题

**Comment by heipiao233** [comment]
ess插件重写了gamemode等命令，使用ess的权限系统而非原版的，可能导致jei误以为有权限执行。

**Comment by PoseidonLi0514** [comment]
换CMI可以解决这个问题

**Comment by josephtarbit** [comment]
What is CMI? (I'm having this problem too)

**Comment by PoseidonLi0514** [comment]
It is a plugin that can replace ESS and works very well.But it costs 15
euros to buy.

Joseph Tarbit ***@***.***> 于2021年7月30日周五 下午10:47写道：
