### ISSUE TITLE
Fix 1.15.2

### ISSUE THREAD

**Issue by Tealwen** [IzzelAliz/Arclight#244]
Hello,

I noticed that you had fixed the problem of the kick when we edit a book and that of citizien in the versions of Arclight in 1.16 would it be possible to fix them also in 1.15.2 I know that it takes your time, but since it is working that this version is still active would it be possible ?

Cordially,

Tealwen

**Comment by timi137137** [comment]
before #157 fixed this problem for 1.16,now fixed to 1.15.2。Need wait merge
