### ISSUE TITLE
Incompatibility with C2ME

### ISSUE THREAD

**Issue by Matthysse** [IzzelAliz/Arclight#246]
Hello!

Here is a simple incompatibility with the C2ME mod that optimizes the chunk loading
Here is the crash that I get at the start of the server : https://pastebin.com/X0tjeJ2m

Here is a link to the project: https://github.com/YatopiaMC/C2ME-forge

**Comment by Dum4G** [comment]
I strongly suggest you to not to use anything that comes from YatopiaMC. They're still releasing improper async patches into production that cause data corruptions

**Comment by Matthysse** [comment]
They say it's not for production use, so I know the risks. I put it on a normal forge modded server, and it works really great, improves the performances by a lot. What do you mean with data corruption? Did you experienced that yourself?

**Comment by Matthysse** [comment]
And I think I will close the issue as I think I found the problem (edit, yep found the problem, edit2: oh it still crashes)

**Comment by Dum4G** [comment]
> What do you mean with data corruption? Did you experienced that yourself?

You may loose your world or players data. That's according to Tuinity devs from which Yatopia is borrowing plenty of patches

**Comment by Matthysse** [comment]
They say themself that users should do backups, and I have an automatic backup system. But for now and with countless restarts, I never encountered anything bad

**Comment by Matthysse** [comment]
Here is the new crash: https://pastebin.com/09LgghPu

**Comment by ghost** [comment]
it's not for Fabric?
