### ISSUE TITLE
cannot be used worldedit 

### ISSUE THREAD

**Issue by hearxs** [IzzelAliz/Arclight#249]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.17-831b37b] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [java version "11" 2018-09-25] 

* **操作系统** [win+1909]

* **插件列表** 
worldedit-bukkit-7.2.5-dist
Multiverse-Core-4.2.2

* **Mod 列表** 
无

### 错误描述
1.16 无法使用

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. 使用复制功能，报错

**可在 Forge 复现** [是]

**可在 Spigot 复现** [是]

### 报错信息

[错误日志]

**Comment by IzzelAliz** [comment]
与 #214 重复
