### ISSUE TITLE
创造模式无法拿取物品

### ISSUE THREAD

**Issue by MrShellad** [IzzelAliz/Arclight#250]
### 我正在运行
arclight-1.16.5-1.0.18-SNAPSHOT-10f6e37
* **Arclight** [版本] 

* **你确认这是最新版吗**
是

* **你确认所有Mod都安装了依赖** [是/否]
是
* **你确认所有插件都已更新至对应版本** [是/否]

是
* **Java** [版本] 
Java11
* **操作系统** [名称+版本]
 Windows 10
* **插件列表** 
Chunkmaster1.4.2
InfernalMobs
minimotd-2.0.2
TAB2.8.10
TimeManager1.5.0
UltraTitle
* **Mod 列表** 
模组列表https://paste.ubuntu.com/p/dRkBBtCrJ5/

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

正常启动游戏后,开启创造模式部分物品无法获取,库存有贴图,实际无法使用或者放置.拿取物品时,从服务端后台可以看到[net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null错误

**可在 Forge 复现** [是/否]
否

**可在 Spigot 复现** [是/否]
是
### 报错信息
[net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null错误
[错误日志]

https://paste.ubuntu.com/p/XqdpThmFvY/

**Comment by IzzelAliz** [comment]
请使用最新构建测试
