### ISSUE TITLE
匠魂3 浇筑盆无法使用

### ISSUE THREAD

**Issue by LittleHed** [IzzelAliz/Arclight#251]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.18-SNAPSHOT-10f6e37]

* **你确认这是最新版吗** [是]
* **你确认所有Mod都安装了依赖** [是]
* **你确认所有插件都已更新至对应版本** [是]
* **Java** [11]
* **操作系统** [Windows 10]
* **插件列表** 
无
* **Mod 列表** 
匠魂3(https://www.mcmod.cn/class/3725.html)
地幔(https://www.mcmod.cn/class/329.html)

### 错误描述
相同情况，采用mcmod下评论:
液体金属浇铸进浇筑盆/浇筑台后无法取出（无论是焦黑加热器→冶炼控制器，铸金属方块，全部成形后无法取出，破坏也不掉落；无论使用什么铸模如果则会浇铸成空白模具，且也无法取出）
如果手持任何物品右键空的浇铸台或浇铸盆会损失物品，暂不清楚是什么原因

使用原版指令data get block之后，发现放了物品进去的浇筑盆没有物品数据
![3PT~C@BCKY8DX7PK%@`{L~Q](https://user-images.githubusercontent.com/58099834/116640849-0fcdbb00-a99e-11eb-9114-a5140edf8b8c.png)

### 重现步骤

1. 安装 Arclight 最新构建版本(arclight-1.16.5-1.0.18-SNAPSHOT-10f6e37)
2. 客户端安装上述模组以及汉化资源包(https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases)
3. 进入服务器后找到匠魂创造页面，拿出浇筑盆以及焦黑砖块(搭建冶炼炉)
4. 在冶炼炉内放入矿物，熔炼后导出至浇筑盆

**可在 Forge 复现** [否]
Forge 36.1.4 单机以及官方端未能复现

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
未发现报错

**Comment by IzzelAliz** [comment]
请使用最新构建测试

**Comment by LittleHed** [comment]
问题未复现

**Comment by timi137137** [comment]
> 问题未复现

所以算是修复了(

**Comment by IzzelAliz** [comment]
请使用最新构建测试

**Comment by LittleHed** [comment]
测试能正常放进浇筑盆了
