### ISSUE TITLE
服务器崩溃

### ISSUE THREAD

**Issue by JackMeds** [IzzelAliz/Arclight#254]
* **Arclight** [版本] 
arclight-forge-1.16-1.0.18-SNAPSHOT
* **你确认这是最新版吗** [是/否，因为___]
是

* **Java** [版本] 
java 11

* **Mod 列表** 
atm6sky 整合包
https://www.curseforge.com/minecraft/modpacks/all-the-mods-6-to-the-sky-atm6s

### 重现步骤

冰与火玩家打mod的龙，崩服

**可在 Forge 复现** [是/否]
否

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/gGPpWzZ6sk/
-->

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/116820221-71607600-aba6-11eb-80b2-4aae4b103218.png)
未发现问题
