### ISSUE TITLE
无法破坏方块。破坏了在次放置其他方块 就会重新变成木桶

### ISSUE THREAD

**Issue by cdcp998** [IzzelAliz/Arclight#256]
![2021-05-06_01 10 17](https://user-images.githubusercontent.com/1726165/117757030-db85b480-b251-11eb-91fb-26d94484ec82.png)

### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.18-SNAPSHOT-d9463a5] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** []

* **Java** [java version "1.8.0_251"] 

* **操作系统** [Windows10]

* **插件列表** 
Plugins (10): LoginManager, LightAPI, PlaceholderAPI, UserLogin, monster, ProtocolLib, TabListPro, HAProxyDetector, spark, DangerousCaves
[m
* **Mod 列表** 
? mods_folder -[夸克] [附属] QuarkOddities-1.16.3.jar : quarkoddities (1.16.3) - 1
? mods_folder UnionLib-1.16.5-3.3.2.jar : unionlib (3.3.2) - 1
? mods_folder -[潘马斯农场的树木] Pamhc2trees-1.16.3-1.0.1.jar : pamhc2trees (1.0.1) - 1
? mods_folder =[JEI] Jei-1.16.4-7.6.1.65.jar : jei (7.6.1.65) - 1
? mods_folder -[捕鱼器] Fishtraps-0.1.3.jar : fishtraps (1.16.5-0.1.3) - 1
? mods_folder -[洞穴扩展] BetterCaves-Forge-1.16.4-1.1.1.jar : bettercaves (1.16.4-1.1.1) - 1
? mods_folder -[创造] Create-mc1.16.5_v0.3.1c.jar : create (mc1.16.5_v0.3.1c+151) - 1
? mods_folder ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar : forgeendertech (7.1.0.0) - 1
? mods_folder -[传送石碑] Waystones_1.16.5-7.4.0.jar : waystones (7.4.0) - 1
? mods_folder Placebo-1.16.4-4.4.2.jar : placebo (4.4.2) - 1
? mods_folder citadel-1.6.2.jar : citadel (1.6.2) - 1
? mods_folder -[旅行者背包] TravelersBackpack-1.16.5-5.4.1.jar : travelersbackpack (5.4.1) - 1
? mods_folder YungsApi-1.16.4-Forge-6.jar : yungsapi (1.16.4-Forge-6) - 1
? mods_folder -[抓钩] AdHooks-1.16.4-6.1.4.0-build.0110.jar : adhooks (6.1.4.0) - 1
? mods_folder -[冠军怪物] Champions-forge-1.16.5-2.0.1.5.jar : champions (1.16.5-2.0.1.5) - 1
? mods_folder -[动物扩展] Betteranimalsplus-1.16.5-10.2.0.jar : betteranimalsplus (10.2.0) - 1
? mods_folder -[圣遗物] Reliquary-1.16.5-1.3.5.1098.jar : xreliquary (1.16.5-1.3.5.1098) - 1
? mods_folder -[精致背包] Sophisticatedbackpacks-1.16.4-2.4.0.259.jar : sophisticatedbackpacks (property(class java.lang.String, provider(?))) - 1
? mods_folder -[神化] Apotheosis-1.16.4-4.5.2.jar : apotheosis (4.5.2) - 1
? mods_folder iChunUtil-1.16.5-10.2.0.jar : ichunutil (10.2.0) - 1
? mods_folder dynviewdist-1.9.jar : dynview (1.8) - 1
? maven_libs forge-1.16.5-36.1.4-universal.jar : forge (36.1.4) - 1
? mods_folder -[丢失的小饰品] LostTrinkets-1.16.5-0.1.27 [前置Lolipop].jar : losttrinkets (0.1.27) - 1
? mods_folder -[大量装饰方块] Supplementaries-1.16.5-0.12.1.jar : supplementaries (1.16.5-0.12.1) - 1
? mods_folder -[塞尔达地图] Antiqueatlas-5.4.4-forge.jar : antiqueatlas (5.4.4-forge) - 1
? mods_folder -[地牢浮现之时] dungeonsarise1.16.5-1.2.68a-HF.jar : dungeons_arise (1.2.68a) - 1
? minecraft forge-1.16.5-36.1.4-server.jar : minecraft (1.16.5) - 1
? mods_folder TenshiLib-1.16.3-1.3.0.jar : tenshilib (1.16.3-1.3.0) - 1
? mods_folder -[魔法艺术] Mana-and-artifice-1.3.0.2.jar : mana-and-artifice (1.3.0.2) - 1
? mods_folder Lollipop-1.16.5-3.2.9.jar : lollipop (3.2.9) - 1
? mods_folder -[潘马斯农场的种子] Pamhc2crops-1.16.3-1.0.2.jar : pamhc2crops (version) - 1
? mods_folder -[旷野之塔] Towers_of_the_wild-1.16.4-2.0.1.jar : towers_of_the_wild (1.16.4-2.0.1) - 1
? mods_folder -[马车] astikorcarts-1.16.5-1.1.1.jar : astikorcarts (1.1.1) - 1
? mods_folder spark-forge.jar : spark (1.5.2) - 1
? mods_folder -[潘马斯农场的食物] Pamhc2foodextended-1.16.3-1.0.2.jar : pamhc2foodextended (version) - 1
? mods_folder -[随机附魔] Randomenchants-4.0.6.jar : randomenchants (4.0.6) - 1
? mods_folder curios-forge-1.16.5-4.0.5.1.jar : curios (1.16.5-4.0.5.1) - 1
? mods_folder -[小神器] Artifacts-1.16.5-2.8.4.jar : artifacts (1.16.5-2.8.4) - 1
? mods_folder -[遗物] Relics-0.1.13.jar : relics (0.1.13) - 1
? mods_folder Patchouli-1.16.4-50.jar : patchouli (1.16.4-50) - 1
? mods_folder Mantle-1.16.5-1.6.92.jar : mantle (1.6.92) - 1
? mods_folder -[灵感] Inspirations-1.16.5-1.2.2.jar : inspirations (1.2.2) - 1
? mods_folder -[老鼠] Rats-7.1.1-1.16.5.jar : rats (7.1.1) - 1
? mods_folder -[老鼠] [扩展] ratlantis-1.0.0-1.16.3.jar : ratlantis (1.0.0-1.16.3) - 1
? mods_folder -[潘马斯农场的核心] pamhc2foodcore-1.16.3-1.0.2.jar : pamhc2foodcore (version) - 1
? mods_folder -[工作台性能优化] FastWorkbench-1.16.4-4.5.1.jar : fastbench (4.5.1) - 1
? mods_folder AutoRegLib-1.6-47.jar : autoreglib (1.6-47) - 1
? mods_folder -[时间之瓶] time-in-a-bottle-1.1.0.jar : tiab (1.1.0) - 1
? mods_folder -[复活队友] HardcoreRevival_1.16.3-5.2.0.jar : hardcorerevival (5.2.0) - 1
? mods_folder -[生存] Survive-1.16.5-3.2.2.jar : survive (1.16.5-3.2.2) - 1
? mods_folder -[要塞扩展] BetterStrongholds-1.16.4-1.0.1.jar : betterstrongholds (1.16.4-1.0.1) - 1
? mods_folder -[墓碑] Tombstone-1.16-6.3.4.jar : tombstone (6.3.4) - 1
? mods_folder -[夸克] Quark-r2.4-311.jar : quark (r2.4-311) - 1
? mods_folder -[ABC播放器] Clef-1.16.5-10.0.2.jar : clef (10.0.2) - 1
? mods_folder -[全收集检查] travelers_index-1.16.4-1.0.2.jar : travelers_index (1.16.4-1.0.2) - 1
? mods_folder -[熔炉性能优化] FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
? mods_folder -[苹果皮] AppleSkin-mc1.16.2-forge-1.0.14.jar : appleskin (1.0.14) - 1
? mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
? mods_folder -[胡萝卜调味料] solcarrot-1.16.3-1.9.10.jar : solcarrot (1.16.3-1.9.10) - 1
>? arclight arclight.jar : arclight (1.16.5-1.0.18-SNAPSHOT-d9463a5) - 1
? mods_folder -[水产养殖2] Aquaculture-1.16.5-2.1.18.jar : aquaculture (1.16.5-2.1.18) - 1
? mods_folder -[你会去的环境] byg-1.2.jar : byg (1.2) - 1
? mods_folder +[怪物调整] improvedmobs-1.16.4-1.7.6 [前置TenshiLib].jar : improvedmobs (1.16.4-1.7.6) - 1
? mods_folder -[雕凿工艺] Chiselsandbits-0.3.4-RELEASE.jar : chiselsandbits (NONE) - 1
? mods_folder -[矿井扩展] BetterMineshafts-Forge-1.16.4-2.0.3.jar : bettermineshafts (1.16.4-2.0.3) - 1
? mods_folder geckolib-forge-1.16.5-3.0.31.jar : geckolib3 (3.0.31) - 1
? mods_folder -[新生魔艺] Ars_nouveau-1.16.4-1.15.1.jar : ars_nouveau (1.15.1) - 1

### 错误描述

无法破坏方块。破坏后再次放置方块就会变化成前面被破坏的方块

### 重现步骤

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/54QFrhcJc6/

![2021-05-06_01 10 19](https://user-images.githubusercontent.com/1726165/117181594-fe563a00-ae07-11eb-9726-ece95ef1538b.png)
![2021-05-06_01 11 49](https://user-images.githubusercontent.com/1726165/117181656-0f9f4680-ae08-11eb-8bca-f7b597c9c734.png)
![2021-05-06_01 10 17](https://user-images.githubusercontent.com/1726165/117757057-e7717680-b251-11eb-88ae-377824ad8f7f.png)

**Comment by IzzelAliz** [comment]
说实话没看懂，另外请二分一下你的mod/插件列表，太多了
