### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by cdcp998** [IzzelAliz/Arclight#257]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.18-SNAPSHOT-9236c34] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [Java Version: 11.0.11, Oracle Corporation] 

* **操作系统** [Windows 10 (amd64) version 10.0]

  

* **插件列表** 

* **Mod 列表** 

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤
莫名其妙

 

**可在 Forge 复现** [是/否]

**可在 Spigot 复现** [是/否]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/rBvkCqryzJ/

**Comment by timi137137** [comment]
提供的信息过少，无法处理

**Comment by timi137137** [comment]
与本仓库另一个issue重复 #254 
此BUG已被 官方 https://github.com/Alex-the-666/Rats/pull/564 解决 你可以试试使用1.16.2版本运行。
