### ISSUE TITLE
1.15 some BUG in 1.0.3

### ISSUE THREAD

**Issue by yonghenglunhui** [IzzelAliz/Arclight#26]
https://paste.ubuntu.com/p/YhrC2znKBD/
没错，咳咳，我又来了，上面这个是其中一个有崩溃日志的BUG..
另外，上次的那个机械动力的漏斗不会崩服了，但是无法正常工作了...物品无法被吸进去，且打开与其相邻的容器服务端就会卡住，卡住后只能强制关闭服务端...

**Comment by IzzelAliz** [comment]
卡住后能否等待60秒给出打印的所有日志

**Comment by yonghenglunhui** [comment]
> 卡住后能否等待60秒给出打印的所有日志

不好意思啊！我刚刚测试了一下，用原版的容器是没问题的。不过我使用更多箱子mod里面的箱子时就不行了，有一条这样的报错，https://paste.ubuntu.com/p/ZvwM6ppZ4N/

**Comment by IzzelAliz** [comment]
> 
> 
> > 卡住后能否等待60秒给出打印的所有日志
> 
> 不好意思啊！我刚刚测试了一下，用原版的容器是没问题的。不过我使用更多箱子mod里面的箱子时就不行了，有一条这样的报错，https://paste.ubuntu.com/p/ZvwM6ppZ4N/

这不像是我的问题，能做个 forge 端的测试吗

**Comment by yonghenglunhui** [comment]
> > > 卡住后能否等待60秒给出打印的所有日志
> > 
> > 
> > 不好意思啊！我刚刚测试了一下，用原版的容器是没问题的。不过我使用更多箱子mod里面的箱子时就不行了，有一条这样的报错，https://paste.ubuntu.com/p/ZvwM6ppZ4N/
> 
> 这不像是我的问题，能做个 forge 端的测试吗

forge-1.15.2-31.2.30同模组测试下木有这个情况...

**Comment by IzzelAliz** [comment]
@yonghenglunhui 请提供此报告 (https://paste.ubuntu.com/p/ZvwM6ppZ4N/) 的 `debug.log`

**Comment by yonghenglunhui** [comment]
> @yonghenglunhui 请提供此报告 (https://paste.ubuntu.com/p/ZvwM6ppZ4N/) 的 `debug.log`

呃呃呃(⊙﹏⊙)刚刚想着尽快把日志弄再忙其他的，顺手测试了一下群里发的1.0.3...发现一些小问题。
1.一些mod的方块错乱了(模拟殖民地，自然灵气，更多箱子等等）一些是正常的（机械动力和植物魔法正常）
2.有一个奇怪的实体报错，minecraft:hopper // net.minecraft.tileentity.HopperTileEntity，在日志里有详细的
这个是debug.log→https://c-t.work/s/006e668f9dc341

**Comment by IzzelAliz** [comment]
可能在 https://github.com/IzzelAliz/Arclight/commit/b07abd4cd77c00ad5d47d818076afaa39e8b24af 修复了，可以测试一遍吗

**Comment by yonghenglunhui** [comment]
> 漏斗卡住的问题可能在 [b07abd4](https://github.com/IzzelAliz/Arclight/commit/b07abd4cd77c00ad5d47d818076afaa39e8b24af) 修复了，可以测试一遍吗

在测试中，目前还没遇到问题~

**Comment by yonghenglunhui** [comment]
> 漏斗卡住的问题可能在 [b07abd4](https://github.com/IzzelAliz/Arclight/commit/b07abd4cd77c00ad5d47d818076afaa39e8b24af) 修复了，可以测试一遍吗

emmmm出问题了，崩溃报告：https://paste.ubuntu.com/p/BhhDGB93VK/
debug.log：https://cowtransfer.com/s/c37f16606d0043
