### ISSUE TITLE
Dupe bug with inventories

### ISSUE THREAD

**Issue by liampearson96** [IzzelAliz/Arclight#265]
### I am running

arclight-forge-1.16-1.0.18

Pretty sure i am running the latest version

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

Linux, ubuntu

Plugins (27): FarmControl, LuckPerms, ClearLag, spark, WorldBorder, Votifier, ProtocolLib, BanItem, CraftingStore, Vault, ServerListPlus, MyCommand, ChestShop, Chunky, Essentials, Jobs, GriefDefender, HolographicDisplays, UltimateChat, DiscordSRV, SuperbVote, EssentialsSpawn, CratesPlus, TheNewEconomy, SalaryManager, CSGO-CratesPlus, Plan

Mod List: 
• mods_folder supermartijn642configlib-1.0.5a-mc1.16.jar : supermartijn642configlib (1.0.5a) - 1
• mods_folder simplemagnets-1.1.2-mc1.16.5.jar : simplemagnets (1.1.2) - 1
• mods_folder refinedpipes-0.5.jar : refinedpipes (0.5) - 1
• mods_folder IntegratedTerminals-1.16.5-1.2.2.jar : integratedterminals (1.2.2) - 2
• mods_folder JAVD-2.5.45+mc-1.16.5.jar : javd (2.5.45+mc-1.16.5) - 1
• mods_folder mcw-windows-1.0.3-mc1.16.5.jar : mcwwindows (1.0.3) - 1
• mods_folder modnametooltip_1.16.2-1.15.0.jar : modnametooltip (1.15.0) - 1
• mods_folder CTM-MC1.16.1-1.1.2.6.jar : ctm (MC1.16.1-1.1.2.6) - 1
• mods_folder ReAuth-1.16-Forge-3.9.3.jar : reauth (3.9.3) - 1
• mods_folder YungsApi-1.16.4-Forge-6.jar : yungsapi (1.16.4-Forge-6) - 1
• mods_folder Powah-1.16.5-2.3.16.jar : powah (2.3.16) - 1
• mods_folder rangedpumps-0.8.2.jar : rangedpumps (0.8.2) - 1
• mods_folder Shrink-1.16.4-1.0.7.jar : shrink (1.0.7) - 1
• mods_folder reliquary-1.16.5-1.3.5.1096.jar : xreliquary (1.16.5-1.3.5.1096) - 1
• mods_folder randompatches-2.4.4-forge.jar : randompatches (2.4.4-forge) - 1
• mods_folder Morpheus-1.16.5-4.2.70.jar : morpheus (4.2.70) - 1
• mods_folder JustEnoughResources-1.16.4-0.12.0.109.jar : jeresources (0.12.0.109) - 1
• mods_folder emojiful-1.16.4-2.1.4.jar : emojiful (1.16.4-2.1.4) - 1
• mods_folder refinedstorage-1.9.12.jar : refinedstorage (1.9.12) - 1
• mods_folder betterendforge-1.16.4-1.5.1.jar : betterendforge (1.16.4-1.5.1) - 1
• mods_folder corpse-1.16.5-1.0.1.jar : corpse (1.16.5-1.0.1) - 1
• mods_folder industrial-foregoing-1.16.5-3.2.11-55cb112.jar : industrialforegoing (3.2.11) - 1
• mods_folder torchmaster-2.3.6.jar : torchmaster (2.3.6) - 1
• mods_folder TipTheScales-1.16.5-3.0.0.11.jar : tipthescales (3.0.0.11) - 1
• mods_folder simplyutilities-1.16.4-0.3.0.jar : simplyutilities (1.16.4-0.3.0) - 1
• mods_folder mcw-trapdoors-1.0.2-mc1.16.5.jar : mcwtrpdoors (1.0.2) - 1
• mods_folder supermartijn642corelib-1.0.1-mc1.16.5.jar : supermartijn642corelib (1.0.1) - 1
• mods_folder Botania-1.16.4-414.jar : botania (1.16.4-414) - 1
• mods_folder SpawnerFix-1.16.2-1.0.0.2.jar : sf (1.0.0.2) - 1
• mods_folder JustARaftMod-1.16.3-1.1.3.jar : justaraftmod (1.1.3) - 1
• mods_folder portality-1.16.4-3.2.1.jar : portality (3.2.1) - 1
• mods_folder curios-forge-1.16.5-4.0.5.1.jar : curios (1.16.5-4.0.5.1) - 1
• mods_folder ExtraStorage-1.16.4-1.3.1.jar : extrastorage (1.3.1) - 1
• mods_folder mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder wormhole-1.1.6-mc1.16.5.jar : wormhole (1.1.6) - 1
• mods_folder furniture-7.0.0-pre19-1.16.3.jar : cfm (7.0.0-pre19) - 1
• mods_folder observerlib-1.16.4-1.5.1.jar : observerlib (1.16.4-1.5.1) - 1
• mods_folder cloth-config-4.11.19-forge.jar : cloth-config (4.11.19) - 1
• mods_folder FastLeafDecay-v25.jar : fastleafdecay (v25) - 1
• mods_folder CodeChickenLib-1.16.4-3.5.1.408-universal.jar : codechickenlib (3.5.1.408) - 1
• mods_folder BetterMineshafts-Forge-1.16.4-2.0.3.jar : bettermineshafts (1.16.4-2.0.3) - 1
• mods_folder SimpleDiscordRichPresence-1.16.4-1.3.5.jar : sdrp (1.16.4-1.3.5) - 1
• mods_folder geckolib-forge-1.16.5-3.0.30.jar : geckolib3 (3.0.30) - 1
• mods_folder ftb-janitor-1604.1.1.19.jar : ftbjanitor (1604.1.1.19) - 1
• mods_folder SimplyJetpacks2-1.16.5-2.6.7.1.jar : simplyjetpacks (1.16.5-2.6.7.1) - 1
• mods_folder woot-1.16.5-1.0.5.0.jar : woot (1.16.5-1.0.5.0) - 1
• mods_folder jei-1.16.5-7.6.4.86.jar : jei (7.6.4.86) - 1
• mods_folder tesseract-1.0.18-mc1.16.4.jar : tesseract (1.0.18) - 1
• mods_folder seals-1.16.3-2.1.0.jar : seals (2.1.0) - 1
• mods_folder Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
• mods_folder shutupexperimentalsettings-1.0.3.jar : shutupexperimentalsettings (1.0.3) - 1
• mods_folder NaturesCompass-1.16.5-1.8.6.jar : naturescompass (1.16.5-1.8.6) - 1
• mods_folder LibX-1.16.3-1.0.39.jar : libx (1.16.3-1.0.39) - 1
• mods_folder FarmingForBlockheads_1.16.3-7.3.0.jar : farmingforblockheads (7.3.0) - 1
• mods_folder pneumaticcraft-repressurized-1.16.5-2.11.4-170.jar : pneumaticcraft (1.16.5-2.11.4-170) - 1
• mods_folder PackingTape-1.16.3-0.10.0.jar : packingtape (0.10.0) - 1
• mods_folder ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1
• mods_folder MythicBotany-1.16.3-1.2.12.jar : mythicbotany (1.16.3-1.2.12) - 1
• mods_folder IntegratedCrafting-1.16.5-1.0.13.jar : integratedcrafting (1.0.13) - 1
• mods_folder ZeroCore2-1.16.4-2.0.21.jar : zerocore (1.16.4-2.0.21) - 1
• minecraft forge-1.16.5-36.1.4-server.jar : minecraft (1.16.5) - 1
• mods_folder theoneprobe-1.16-3.0.7.jar : theoneprobe (1.16-3.0.7) - 1
• mods_folder MouseTweaks-2.14-mc1.16.2.jar : mousetweaks (2.14) - 1
• mods_folder ImmersiveEngineering-1.16.5-4.2.4-134.jar : immersiveengineering (1.16.5-4.2.4-134) - 1
• mods_folder jeiintegration_1.16.5-7.0.1.15.jar : jeiintegration (7.0.1.15) - 1
• mods_folder Mantle-1.16.5-1.6.92.jar : mantle (1.6.92) - 1
• mods_folder IntegratedDynamics-1.16.5-1.7.2.jar : integrateddynamics (1.7.2) - 2
• mods_folder integratednbt-1.16.4-1.4.2.jar : integratednbt (version) - 1
• mods_folder itemcollectors-1.0.11-mc1.16.5.jar : itemcollectors (1.0.11) - 1
• mods_folder ftb-backups-2.1.1.6.jar : ftbbackups (2.1.1.6) - 1
• mods_folder serverconfigupdater-1.3.jar : serverconfigupdater (1.3) - 1
• mods_folder JustEnoughProfessions-1.16.5-1.2.1.jar : justenoughprofessions (1.2.1) - 1
• mods_folder AutoRegLib-1.6-47.jar : autoreglib (1.6-47) - 1
• mods_folder lanterncolors-1.16.3-2.1.1.jar : lanterncolors (1.16.2-2.1.1) - 1
• mods_folder harvest-1.16.3-1.0.3.jar : harvest (1.0.3) - 1
• mods_folder FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
• mods_folder byg-1.1.14.jar : byg (1.1.14) - 1
• mods_folder extremeSoundMuffler-3.9_Forge-1.16.5.jar : extremesoundmuffler (3.9_forge-1.16.5) - 1
• mods_folder CosmeticArmorReworked-1.16.5-v1b.jar : cosmeticarmorreworked (1.16.5-v1b) - 1
• mods_folder DefaultOptions_1.16.3-12.2.0.jar : defaultoptions (12.2.0) - 1
• mods_folder rsrequestify-1.16.3-2.0.1.jar : rsrequestify (2.0.1) - 1
• mods_folder CyclopsCore-1.16.5-1.11.5.jar : cyclopscore (1.11.5) - 1
• mods_folder astralsorcery-1.16.4-1.13.9.jar : astralsorcery (1.16.4-1.13.9) - 1
• mods_folder JustEnoughCalculation-1.16.5-3.6.4.jar : jecalculation (3.6.4) - 1
• mods_folder pocketstorage-1.16.3-0.7.6.jar : pocketstorage (1.16.3-0.7.6) - 1
• mods_folder KleeSlabs_1.16.5-9.2.1.jar : kleeslabs (9.2.1) - 1
• mods_folder rsgauges-1.16.4-1.2.8.jar : rsgauges (1.2.8) - 1
• mods_folder gildedarmor-1.16.5-1.0.4.jar : gildedarmor (1.0.4) - 1
• mods_folder findme-1.16.3-2.1.0.0.jar : findme (NONE) - 1
• mods_folder glassential-forge-1.16.5-1.1.6.jar : glassential (1.1.6) - 1
• mods_folder TerraForged-1.16.4-0.2.9 (1).jar : terraforged (0.2.9) - 1
• mods_folder CookingForBlockheads_1.16.5-9.3.1.jar : cookingforblockheads (9.3.1) - 1
• mods_folder Controlling-7.0.0.14.jar : controlling (7.0.0.14) - 1
• mods_folder Placebo-1.16.4-4.4.1.jar : placebo (4.4.1) - 1
• mods_folder citadel-1.6.2.jar : citadel (1.6.2) - 1
• mods_folder alexsmobs-1.9.0.jar : alexsmobs (1.9.0) - 1
• mods_folder culinaryconstruct-forge-1.16.5-4.0.0.6.jar : culinaryconstruct (1.16.5-4.0.0.6) - 1
• mods_folder Bookshelf-1.16.5-10.0.7.jar : bookshelf (10.0.7) - 1
• mods_folder DarkUtilities-1.16.5-8.0.3.jar : darkutils (8.0.3) - 1
• mods_folder BotanyPots-1.16.5-7.0.15.jar : botanypots (7.0.15) - 1
• mods_folder BotanyTrees-1.16.5-3.0.2.jar : botanytrees (3.0.2) - 1
• mods_folder MysteryMilk-1.16.5-5.0.1.jar : mysterymilk (5.0.1) - 1
• mods_folder buildinggadgets-1.16.5-3.8.0.jar : buildinggadgets (3.8.0) - 1
• maven_libs forge-1.16.5-36.1.4-universal.jar : forge (36.1.4) - 1
• mods_folder cofh_core-1.16.4-1.2.1.jar : cofh_core (1.2.1) - 1
• mods_folder thermal_foundation-1.16.4-1.2.0.jar : thermal (1.2.0) - 1
• mods_folder thermal_innovation-1.16.4-1.2.0.jar : thermal_innovation (1.2.0) - 1
• mods_folder thermal_locomotion-1.16.4-1.2.0.jar : thermal_locomotion (1.2.0) - 1
• mods_folder Psi 1.16-93.jar : psi (1.16-92) - 1
• mods_folder AppleSkin-mc1.16.2-forge-1.0.14.jar : appleskin (1.0.14) - 1
• mods_folder Waddles-1.16.5-0.8.12.jar : waddles (1.16.5-0.8.12) - 1
• mods_folder mcw-doors-1.0.2-mc1.16.5.jar : mcwdoors (1.0.2) - 1
• mods_folder MekanismGenerators-1.16.5-10.0.21.448.jar : mekanismgenerators (10.0.21) - 1
• mods_folder XNetGases-1.16.5-2.2.6.jar : xnetgases (2.2.6) - 1
• mods_folder Podium-1.16.3-1.0.0.jar : podium (1.0.0) - 1
• mods_folder LostTrinkets-1.16.5-0.1.27.jar : losttrinkets (0.1.27) - 1
• mods_folder absentbydesign-1.16.5-1.4.1.jar : absentbydesign (1.16.5-1.4.1) - 1
• mods_folder quartz-chests-1603.1.0.8.jar : quartzchests (1603.1.0.8) - 1
• mods_folder PrettyPipes-1.9.3.jar : prettypipes (1.9.3) - 1
• mods_folder JAMD-1.1.9-beta+mc-1.16.5.jar : jamd (1.1.9-beta+mc-1.16.5) - 1
• mods_folder chocolate-1.3.0-1.16.4.jar : chocolate (1.3.0-1.16.4) - 1
• mods_folder mcw-bridges-1.0.5-mc1.16.5-4.jar : mcwbridges (1.0.5) - 1
• mods_folder FarmersDelight-1.16.3-0.4.1.jar : farmersdelight (1.16.3-0.4.1) - 1
• mods_folder entangled-1.2.12-mc1.16.5.jar : entangled (1.2.12) - 1
• mods_folder CommonCapabilities-1.16.5-2.6.0.jar : commoncapabilities (2.6.0) - 1
• mods_folder valkyrielib-1.16.5-3.0.8.0.jar : valkyrielib (1.16.5-3.0.8.0) - 1
• mods_folder envirocore-1.16.5-3.0.8.0.jar : envirocore (1.16.5-3.0.8.0) - 1
• mods_folder envirotech-1.16.5-3.0.8.0.jar : envirotech (1.16.5-3.0.8.0) - 1
• mods_folder Lollipop-1.16.5-3.2.9.jar : lollipop (3.2.9) - 1
• mods_folder ftb-ranks-1604.1.1.11.jar : ftbranks (1604.1.1.11) - 1
• mods_folder simplylight-1.16.4-1.1.2.jar : simplylight (1.16.4-1.1.2) - 1
• mods_folder jousting-1.16.5-v1.0.3.jar : jousting (1.16.5-v1.0.3) - 1
• mods_folder simplybackpacks-1.16.3-1.4.13.jar : simplybackpacks (1.16.3-1.4.13) - 1
• mods_folder Patchouli-1.16.4-50.jar : patchouli (1.16.4-50) - 1
• mods_folder ars_nouveau-1.16.4-1.13.2.jar : ars_nouveau (1.13.2) - 1
• mods_folder collective-1.16.5-2.25.jar : collective (2.25) - 1
• mods_folder doomangelring-1.16.4-1.0.0.jar : doomangelring (1.0.0) - 1
• mods_folder blockcarpentry-1.16-0.3.5b.jar : blockcarpentry (1.16-0.3.5b) - 1
• mods_folder thermal_expansion-1.16.4-1.2.0.jar : thermal_expansion (1.2.0) - 1
• mods_folder IntegratedTunnels-1.16.5-1.7.1.jar : integratedtunnels (1.7.1) - 2
• mods_folder elevatorid-1.16.5-1.7.13.jar : elevatorid (1.16.5-1.7.13) - 1
• mods_folder Runelic-1.16.5-7.0.1.jar : runelic (7.0.1) - 1
• mods_folder MekanismTools-1.16.5-10.0.21.448.jar : mekanismtools (10.0.21) - 1
• mods_folder architectury-1.11.144-forge.jar : architectury (1.11.144) - 1
• mods_folder bambooeverything-1.16.5-1.0.0-forge.jar : bambooeverything (1.0.0) - 1
• mods_folder ftb-gui-library-1605.2.1.41-forge.jar : ftbguilibrary (1605.2.1.41) - 1
• mods_folder ftb-teams-1604.1.0.16-forge.jar : ftbteams (1604.1.0.16) - 1
• mods_folder cc-tweaked-1.16.4-1.95.3.jar : computercraft (1.95.3) - 1
• mods_folder ExtremeReactors2-1.16.4-2.0.23.jar : bigreactors (1.16.4-2.0.23) - 1
• mods_folder light-overlay-5.8.0.jar : lightoverlay (5.8.0) - 1
• mods_folder trashcans-1.0.9-mc1.16.5.jar : trashcans (1.0.9) - 1
• mods_folder The_Undergarden-1.16.5-0.4.5.jar : undergarden (0.4.5) - 1
• mods_folder enchantwithmob-1.16.5-1.3.4.jar : enchantwithmob (1.16.5-1.3.4) - 1
• mods_folder bwncr-1.16.4-3.9.16.jar : bwncr (1.16.4-3.9.16) - 1
• mods_folder QuantumStorage-1.16.4-5.3.0.jar : quantumstorage (5.3.0Alpha5) - 1
• mods_folder Cyclic-1.16.5-1.2.7.jar : cyclic (1.16.5-1.2.7) - 1
• mods_folder BetterAdvancements-1.16.5-0.1.0.105.jar : betteradvancements (0.1.0.105) - 1
• mods_folder inventorysorter-1.16.1-18.1.0.jar : inventorysorter (18.1.0) - 1
• mods_folder rhino-1.7.13-build.23.jar : rhino (1.7.13-build.23) - 1
• mods_folder kubejs-1605.3.6-build.179-forge.jar : kubejs (1605.3.6-build.179) - 1
• mods_folder kubejs-thermal-1605.1.1.6.jar : kubejs_thermal (1605.1.1.6) - 1
• mods_folder kubejs-immersive-engineering-1604.1.0.12.jar : kubejs_immersive_engineering (1604.1.0.12) - 1
• mods_folder kubejs-mekanism-1604.1.1.6.jar : kubejs_mekanism (1604.1.1.6) - 1
• mods_folder kubejs-ui-1605.1.3-build.4-forge.jar : kubejs_ui (1605.1.3-build.4) - 1
• mods_folder Cucumber-1.16.4-4.1.9.jar : cucumber (4.1.9) - 1
• mods_folder TrashSlot_1.16.3-12.2.1.jar : trashslot (12.2.1) - 1
• mods_folder flatbedrock-1.16.4-1.1.6.jar : flatbedrock (1.16.4-1.1.6) - 1
• mods_folder snad-1.0.5-1.16.5.jar : snad (1.0.5) - 1
• mods_folder GooglyEyes-1.16.5-10.2.0.jar : googlyeyes (10.2.0) - 1
• mods_folder debug-tools-2.0-SNAPSHOT.jar : debug-tools (NONE) - 1
• mods_folder justmobheads_1.16.5-4.0.jar : justmobheads (4.0) - 1
• mods_folder ensorcellation-1.16.4-1.2.0.jar : ensorcellation (1.2.0) - 1
• mods_folder create-mc1.16.5_v0.3.1c.jar : create (mc1.16.5_v0.3.1c+151) - 1
• mods_folder kubejs-create-1604.1.0.4.jar : kubejs_create (1604.1.0.4) - 1
• mods_folder Waystones_1.16.5-7.4.0.jar : waystones (7.4.0) - 1
• mods_folder goldenhopper-1.1.1-1.16.3.jar : goldenhopper (1.1.1) - 1
• mods_folder Clumps-6.0.0.21.jar : clumps (6.0.0.21) - 1
• mods_folder comforts-forge-1.16.4-4.0.1.0.jar : comforts (1.16.4-4.0.1.0) - 1
• mods_folder appliedenergistics2-8.3.0-alpha.3.jar : appliedenergistics2 (8.3.0-alpha.3) - 1
• mods_folder SimpleStorageNetwork-1.16.5-1.3.5.jar : storagenetwork (1.16.5-1.3.5) - 1
• mods_folder framedcompactdrawers-1.16-2.2.0.jar : framedcompactdrawers (1.16-2.2.0) - 1
• mods_folder gardentools-1.16.5-1.1.1.jar : gardentools (1.16.5-1.1.1) - 1
• mods_folder decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder DungeonCrawl-1.16.3-2.2.4.jar : dungeoncrawl (2.2.4) - 1
• mods_folder charginggadgets-1.3.0.jar : charginggadgets (1.3.0) - 1
• mods_folder mcjtylib-1.16-5.0.19.jar : mcjtylib (1.16-5.0.19) - 1
• mods_folder rftoolsbase-1.16-2.0.10.jar : rftoolsbase (1.16-2.0.10) - 1
• mods_folder xnet-1.16-3.0.11.jar : xnet (1.16-3.0.11) - 1
• mods_folder rftoolspower-1.16-3.0.8.jar : rftoolspower (1.16-3.0.8) - 1
• mods_folder rftoolsstorage-1.16-2.0.11.jar : rftoolsstorage (1.16-2.0.11) - 1
• mods_folder rftoolscontrol-1.16-4.0.8.jar : rftoolscontrol (1.16-4.0.8) - 1
• mods_folder restrictions-1.16-3.0.3.jar : restrictions (1.16-3.0.3) - 1
• mods_folder mahoutsukai-1.16.5-v1.29.1.jar : mahoutsukai (1.16.5-v1.29.1) - 1
• mods_folder Toast-Control-1.16.4-4.3.1.jar : toastcontrol (4.3.1) - 1
• mods_folder iChunUtil-1.16.5-10.2.0.jar : ichunutil (10.2.0) - 1
• mods_folder mininggadgets-1.7.5.jar : mininggadgets (1.7.5) - 1
• mods_folder entitydetectors-1.16.4-1.1.0.1.jar : entitydetectors (1.1.0.1) - 1
• mods_folder EnderStorage-1.16.4-2.7.1.166-universal.jar : enderstorage (2.7.1.166) - 1
• mods_folder ftb-chunks-1605.2.3-build.75.jar : ftbchunks (1605.2.3-build.75) - 1
• mods_folder PartyParrots-1.16.3-1.1.0.jar : partyparrots (1.1.0) - 1
• mods_folder BloodMagic-1.16.4-3.1.0-15.jar : bloodmagic (1.16.4-3.1.0-15) - 1
• mods_folder kubejs-blood-magic-1604.1.0.4.jar : kubejs_blood_magic (1604.1.0.4) - 1
• mods_folder scuba-gear-1.16.5-1.0.3.jar : scuba_gear (1.0.3) - 1
• mods_folder recipebuffers-2.1.jar : recipebuffers (2.1) - 1
• mods_folder immersiveposts-1.16.5-4.0.0.jar : immersiveposts (4.0.0) - 1
• mods_folder MysticalAgriculture-1.16.4-4.1.7.jar : mysticalagriculture (4.1.7) - 1
• mods_folder MysticalAgradditions-1.16.4-4.1.5.jar : mysticalagradditions (4.1.5) - 1
• mods_folder CraftingTweaks_1.16.3-12.2.0.jar : craftingtweaks (12.2.0) - 1
• mods_folder rftoolsutility-1.16-3.0.25.jar : rftoolsutility (1.16-3.0.25) - 1
• mods_folder EnchantmentDescriptions-1.16.5-7.0.7.jar : enchdesc (7.0.7) - 1
• mods_folder swingthroughgrass-1.16.4-1.5.3.jar : swingthroughgrass (1.16.4-1.5.3) - 1
• mods_folder titanium-1.16.5-3.2.8.2.jar : titanium (3.2.8.2) - 1
• mods_folder movingelevators-1.2.33-mc1.16.5.jar : movingelevators (1.2.33) - 1
• mods_folder archers_paradox-1.16.4-1.2.0.jar : archers_paradox (1.2.0) - 1
• mods_folder towers_of_the_wild-1.16.4-2.0.1.jar : towers_of_the_wild (1.16.4-2.0.1) - 1
• mods_folder Krate-1.16.5-0.1.4.jar : krate (0.1.4) - 1
• mods_folder justplayerheads_1.16.5-1.6.jar : justplayerheads (1.6) - 1
• mods_folder Quark-r2.4-310.jar : quark (r2.4-310) - 1
• mods_folder FastWorkbench-1.16.4-4.5.1.jar : fastbench (4.5.1) - 1
• mods_folder StorageDrawers-1.16.3-8.2.2.jar : storagedrawers (8.2.2) - 1
• mods_folder FluxNetworks-1.16.5-6.1.6.11.jar : fluxnetworks (1.16.5-6.1.6.11) - 1
• mods_folder Statues-1.16.5-0.1.6.7.jar : statues (0.1.6.7) - 1
• mods_folder hunterillager-1.16.4-1.2.2.jar : hunterillager (1.16.4-1.2.2) - 1
• mods_folder Transport-1.16.5-3.6.0.jar : transport (3.6.0) - 1
• mods_folder ferritecore-2.0.4-forge.jar : ferritecore (2.0.4) - 1
• mods_folder ice_ice_baby-1.16.4-3.0.1.jar : ice_ice_baby (3.0.1) - 1
• mods_folder MineTogether-1.16.4-4.1.6RC8.jar : minetogether (1.16.4-4.1.6RC8) - 1
• mods_folder moredragoneggs-1.4.jar : moredragoneggs (1.4) - 1
• arclight arclight-forge-1.16-1.0.18.jar : arclight (1.16.5-1.0.18-32d233f) - 1
• mods_folder modular-routers-1.16.5-7.4.0-55.jar : modularrouters (task ':jar' property 'archiveVersion') - 1
• mods_folder refinedstorageaddons-0.7.2.jar : refinedstorageaddons (0.7.2) - 1
• mods_folder chiselsandbits-0.3.4-RELEASE.jar : chiselsandbits (NONE) - 1

### Description

We have an issue on 1.16.5 where any inventory/ item with an inventory can be used to dupe items. This happens when the backpack/bag ect is used to collect items automatically. We cannot recreate this issue on a normal forge server.

### Step to reproduce

https://user-images.githubusercontent.com/11605270/118159894-82ff1480-b415-11eb-8a80-06f2384f3410.mp4

 https://www.feed-the-beast.com/modpack/ftb_endeavour

**Reproducible in Forge** [Y/N] N

### Logs

[ERROR LOG]

**Comment by liampearson96** [comment]
I believe whatever this issue is, is also causing XP to be duplicated upon pickup.

**Comment by DatRatVS** [comment]
> I believe whatever this issue is, is also causing XP to be duplicated upon pickup.

No, Clumps is causing the XP dupe. (Already tried on Mohist)

**Comment by liampearson96** [comment]
@DatRatVS i see, thanks!

Any update on this?

**Comment by DatRatVS** [comment]
Only trying to see if it is fixed, but, they updated Clumps quite a bit of times since that

**Comment by IzzelAliz** [comment]
This is still relevant.

**Comment by IzzelAliz** [comment]
Please test this in latest dev build to see if this is fixed.

**Comment by liampearson96** [comment]
Hello @IzzelAliz. I have downloaded the latest arclight from https://ci.appveyor.com/project/IzzelAliz/arclight-16/build/artifacts however the issue still persists.

Thanks

**Comment by Dns-q** [comment]
This is still an issue. Tested with only Archlight and SimplyBackpacks.

forge-1.16.5-36.2.26
arclight-forge-1.16-1.0.22
simplybackpacks-1.16.5-2.0.2-build.30

**Comment by IzzelAliz** [comment]
This should be fixed in latest dev.

Due to code changes in item pick, users are encouraged to have further tests on item pickup related functions.

**Comment by IzzelAliz** [comment]
Close this since no further input.
