### ISSUE TITLE
1.16.5 白门的奇异附魔：苦痛长河 无法正常使用铁砧附魔

### ISSUE THREAD

**Issue by MarbleGateKeeper** [IzzelAliz/Arclight#267]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.18-32d233f]

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [8] 

* **操作系统** [Windows 10 20H2]

* **插件列表** 
* 无任何插件

* **Mod 列表** 
* [白门的奇异附魔：苦痛长河 beta-0.2.0/0.2.1](https://www.curseforge.com/minecraft/mc-mods/marblegates-exotic-enchantment-flowing-agony/)

### 错误描述

任何装备+附魔书放进铁砧后，附魔经验要求变为1，同时无法正常取出附魔装备。
同时后台产生巨量报错。

该Bug在这个Issue被提交：[在arclight-forge-1.16-1.0.18.jar 服务器上使用导致铁砧不能附魔](https://github.com/MarbleGateKeeper/FlowingAgony/issues/1)

### 重现步骤

1. 白门的奇异附魔：[苦痛长河 beta-0.2.0/0.2.1](https://www.curseforge.com/minecraft/mc-mods/marblegates-exotic-enchantment-flowing-agony/files/3305568)

2. 进入服务器后取出任意一件装备和附魔书，用铁砧附魔

**复现用压缩包下载链接**
[Onedrive](https://1drv.ms/u/s!AvzebKAdh0yDhT_OQqVCpjcEAs_k?e=vCF0mg)

**可在 Forge 复现** [否]

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/mhxH7R6JNX/

**Comment by IzzelAliz** [comment]
Fixed in 68ddb4a6b722e66a3d6d5066fb557a3903becbc1
