### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Sidoupiar** [IzzelAliz/Arclight#27]
不知道是暮色的问题还是端的问题
[crash-2020-07-21_09.22.25-server.txt](https://github.com/IzzelAliz/Arclight/files/4950787/crash-2020-07-21_09.22.25-server.txt)
[2020-07-21-1.log](https://github.com/IzzelAliz/Arclight/files/4950789/2020-07-21-1.log)

**Comment by IzzelAliz** [comment]
反正不是端的问题
