### ISSUE TITLE
服务器重启后，玩家无法拾取重启之前的掉落物

### ISSUE THREAD

**Issue by AeXiaohu** [IzzelAliz/Arclight#272]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.18-32d233f] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [15.0.1 与 1.8.0_291] 

* **操作系统** [Windows 10 企业版 20H2 19042.985]

  

* **插件列表** 
无

* **Mod 列表** 
无

### 错误描述

服务器重启后，玩家无法拾取重启之前的掉落物，但是这些掉落物可以被漏斗接住并拿出来

### 重现步骤

1. 进入服务器后往地上扔东西

2. 服务端输入 stop ，然后再启动服务器

3. 再次进入服务器后之前扔在地上的掉落物会捡不起来

-->

**Comment by IzzelAliz** [comment]
无法复现
