### ISSUE TITLE
KemonoCraft Mod 开服崩溃

### ISSUE THREAD

**Issue by July7th** [IzzelAliz/Arclight#275]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.18] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [java version "1.8.0_211"] 

* **操作系统** [windows/windows server 2012]

  

* **插件列表** No 

* **Mod 列表** KemonoCraft 

### 错误描述

只安装 KemonoCraft Mod 的情况下同样开服崩溃 此Mod无需前置即可正常运行
叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 开服崩溃

 

**可在 Forge 复现** [否]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/77g87KNqCy/

**Comment by IzzelAliz** [comment]
与 #211 重复
