### ISSUE TITLE
服务器优化选项导致服务器崩溃

### ISSUE THREAD

**Issue by sheng-ri** [IzzelAliz/Arclight#277]
* **Arclight** arclight-1.16.5-1.0.19-SNAPSHOT-19d2ba1

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** [版本] 
16.0.1

* **操作系统** [名称+版本] Windows Server 2012

  

* **插件列表** 
PlugMan v2.1.7 com.rylinaux.plugman.PlugMan [rylinaux], spark v1.4.3 me.lucko.spark.bukkit.BukkitSparkPlugin [Luck, sk89q], MCdataMining v1.0 com.snowk.mcdm.mcdm [], ServerListPlus v3.4.8 net.minecrell.serverlistplus.bukkit.BukkitPlugin [Minecrell <https://github.com/Minecrell>]
* **Mod 列表** 
	forge-1.16.5-36.1.24-server.jar     
		YungsApi-1.16.4-Forge-6.jar   
		QuarkOddities-1.16.3.jar  
		worldedit-forge-mc1.16.3-7.2.2-dist.jar   
		arclight-forge-1.16-1.0.19-SNAPSHOT.jar      
		abnormals_core-1.16.5-3.1.1.jar               
		buzzier_bees-1.16.5-3.0.1.jar              
		berry_good-1.16.5-4.1.1.jar            
		atmospheric-1.16.5-3.1.0.jar       
		forge-1.16.5-36.1.24-universal.jar          
		upgrade_aquatic-1.16.5-3.1.0.jar             
		supplementaries-1.16.5-0.12.2.jar    
		savageandravage-1.16.5-3.1.0.jar         
		BetterMineshafts-Forge-1.16.4-2.0.3.jar          
		BetterCaves-Forge-1.16.4-1.1.2.jar             
		neapolitan-1.16.5-2.1.0.jar                    
		autumnity-1.16.5-2.1.1.jar                  
		AutoRegLib-1.6-49.jar                  
		Quark-r2.4-298.jar 

### 错误描述
optimization {
    # 关闭用于升级存档数据的 DataFixerUpper 系统
    # 这将可能加快启动速度和地图加载速度，并减少 80-200mb 的内存占用
    # Arclight 及其开发者不对任何数据丢失或损害负责
    # 请不要在生产环境中使用
    disable-data-fixer=true
}
此选项描述为用于升级存档数据,
但在设置为false后，使用快捷键交换主手和副手物品时崩溃
1、此为错误
2、配置文件描述错误
设置为true时，会显示
[19:37:45] [Server thread/INFO] [STDERR/]: [org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy:<clinit>:257]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
同时也要求插件api-verison都在1.13

### 重现步骤

1. optimization.disable-data-fixer=true

2. 进入服务器后手持物品，交换主手副手物品

 

**可在 Forge 复现** 否

**可在 Spigot 复现** 否

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/CdsrXrpg3c/

**Comment by IzzelAliz** [comment]
那你不要用啊？

**Comment by sheng-ri** [comment]
> 那你不要用啊？

啊这，我知道用这个选项需要承担风险，
只是觉得描述不大符合，交了个Issue.
