### ISSUE TITLE
无法安装KemonoCraft-1.16.4-0.3.18的模组

### ISSUE THREAD

**Issue by 3439798258** [IzzelAliz/Arclight#282]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.19-SNAPSHOT-19d2ba1c] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [没有插件]

* **Java** [openjdk11] 

* **操作系统** [winserver2019]

  

* **插件列表** 
* 无

* **Mod 列表** 
* [兽娘]KemonoCraft-1.16.4-0.3.18

### 错误描述

加了此mod之后无法启动，核心不兼容

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 无任何插件和其他模组

2. 安装此模组后，启动，直接崩溃

3. ....

 

**可在 Forge 复现** [是]

**可在 Spigot 复现** [无插件]

### 报错信息

[错误日志]

**Comment by 3439798258** [comment]
日记：忘记传了https://paste.ubuntu.com/p/jYCgMRrCd6/

**Comment by timi137137** [comment]
问题无法解决，能在其他端重现。出现问题在于mod不知道用了什么奇怪的东西导致forge事件总线的ASMHandler注入不了(?

**Comment by IzzelAliz** [comment]
与 #211 重复
