### ISSUE TITLE
java.lang.NoSuchFieldError: COMMAND

### ISSUE THREAD

**Issue by ArtemKuchin** [IzzelAliz/Arclight#289]
Running with one forge mod
betterendforge-1.16.54-1.6.0.jar
and plugins:
worldedit
worldguard

Connect from minecraft forge 1.16.5

log file:
[latest.log](https://github.com/IzzelAliz/Arclight/files/6604994/latest.log)

i can even play for 15 seconds and then server crashes

**Comment by IzzelAliz** [comment]
Update to latest dev build.

**Comment by ArtemKuchin** [comment]
Where do i get lastest DEV BUILD? Of for latest dev i need to build it from sources?
