### ISSUE TITLE
Commands from mods don't exist

### ISSUE THREAD

**Issue by Bennyboy1695** [IzzelAliz/Arclight#291]
### I am running

* **Arclight** [arclight-1.16.5-1.0.18-32d233f] 

* **Java** [1.8_251] 

* **Operating System** [Windows 10]

  

* **Plugins** 
Plugins (4): LuckPerms, Vault, CommandTest (Just runs a dispatch command method to test ommands), GriefDefender

* **Mods** 
Mod List: 
• minecraft forge-1.16.5-36.1.4-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.1.4-universal.jar : forge (36.1.4) - 1
• mods_folder easy_villagers-1.16.5-1.0.4.jar : easy_villagers (1.16.5-1.0.4) - 1
• mods_folder UsefulCommands-3.8-all.jar : usefulcommands (1.0.0) - 1
• arclight arclight.jar : arclight (1.16.5-1.0.18-32d233f) - 1

### Description

Commands added by mods (like my private mod usefulcommands) become unknown commands (Bukkits version) when attempting to run ingame or from console.
Bukkit commands all work fine. 

### Step to reproduce

1. Install a mod that adds commands
2. Attempt to run said mods commands
3. Get Bukkits unknown command error

**Comment by Bennyboy1695** [comment]
Also just tried with the latest commit build and it was the same issue. However when ingame minecraft does tab the commands so its not the commands not existing just arclight not forwarding them it seems

**Comment by IzzelAliz** [comment]
Can you give me a snippet of the code where you registered your commands?

**Comment by Bennyboy1695** [comment]
Main Class: 
    @SubscribeEvent(priority = EventPriority.LOWEST)    public void onServerStarting(FMLServerStartingEvent event) {        plugin = this;        
getLogger().info("Initializing...");        
configManager = new Configuration(this);        
configManager.loadCore();        
configManager.loadMessages();
        CommandDispatcher&lt;CommandSource&gt; dispatcher = ServerLifecycleHooks.getCurrentServer().getCommandManager().getDispatcher();        
new ReloadCommand(this).register(dispatcher);        
new DiscordCommand(this).register(dispatcher);
        }

DiscordCommand Class:
    
public void register(CommandDispatcher&lt;CommandSource&gt; dispatcher) {        dispatcher.register(Commands.literal("discord").executes(this::run));    
}

**Comment by IzzelAliz** [comment]
Please test with latest build.

Also I would recommend using RegisterCommandsEvent.

**Comment by Bennyboy1695** [comment]
This fixes the issue. Thank you
