### ISSUE TITLE
开启op权限后，客户端自动断联

### ISSUE THREAD

**Issue by markusxu** [IzzelAliz/Arclight#295]
### 我正在运行

* **Arclight** [1.16-1.018] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [版本] 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

* **操作系统** [名称+版本]
ubuntu 18.04 LTS
  

* **插件列表** 
无
* **Mod 列表** 
[17:13:11] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List:
• minecraft forge-1.16.5-36.1.4-server.jar : minecraft (1.16.5) - 1
• mods_folder 3.02_农夫乐事_FarmersDelight-1.16.5-0.4.3.jar : farmersdelight (1.16.5-0.4.3) - 1
• mods_folder 7.03_垃圾桶_TrashSlot_1.16.3-12.2.1.jar : trashslot (12.2.1) - 1
• mods_folder 2.01_生物群系拓展_BiomesOPlenty-1.16.5-13.1.0.471-universal.jar : biomesoplenty (1.16.5-13.1.0.471) - 1
• mods_folder 5.02_自动钓鱼_Autofish-0.9.2-forge-mc1.16.4.jar : autofish (0.9.2) - 1
• mods_folder 3.03_简单农业_simplefarming-1.16.5-1.3.7.jar : simplefarming (1.16.4-1.3.7) - 1
• mods_folder 1.06_平滑加载_smoothboot-forge-1.16.4-1.2.2.jar : smoothboot (1.16.4-1.2.2) - 1
• mods_folder 2.06.1_海洋前置_abnormals_core-1.16.5-3.1.1.jar : abnormals_core (3.1.1) - 1
• mods_folder 7.09_伤害显示_TextDamageIndicators-1.16.3-2.0.1.jar : textdamageindicators (2.0.1) - 1
• mods_folder 2.06_海洋升级_upgrade_aquatic-1.16.5-3.1.0.jar : upgrade_aquatic (3.1.0) - 1
• mods_folder 5.04_边拿边走_InvMove-1.16.3-0.4.6.jar : invmove (0.4.6) - 1
• mods_folder 3.01_机械动力_create-mc1.16.5_v0.3.1c.jar : create (mc1.16.5_v0.3.1c+151) - 1
• mods_folder 2.03_更好洞穴_BetterCaves-Forge-1.16.4-1.1.2.jar : bettercaves (1.16.4-1.1.2) - 1
• mods_folder 7.02_小地图_Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar : xaerominimap (21.10.0.3) - 1
• mods_folder 3.04_传送石碑_Waystones_1.16.5-7.6.2.jar : waystones (7.6.2) - 1
• mods_folder 4.04.1_篝火前置.jar : collective (2.25) - 1
• mods_folder 2.02_地形拓展_TerraForged-1.16.5-0.2.10.jar : terraforged (0.2.10) - 1
• mods_folder 7.01_世界地图_XaerosWorldMap_1.14.1_Forge_1.16.5.jar : xaeroworldmap (1.14.1) - 1
• mods_folder 6.03_多态合成_polymorph-forge-1.16.5-0.24.jar : polymorph (1.16.5-0.24) - 1
• mods_folder 0.01_夸克前置_AutoRegLib-1.6-49.jar : autoreglib (1.6-49) - 1
• mods_folder 4.02_储物抽屉_StorageDrawers-1.16.3-8.2.2.jar : storagedrawers (8.2.2) - 1
• mods_folder 7.04_通用拼音搜索_JustEnoughCharacters-1.16.4-4.1.6.jar : jecharacters (4.1.6) - 1
• mods_folder 2.03.1_洞穴前置_YungsApi-1.16.4-Forge-6.jar : yungsapi (1.16.4-Forge-6) - 1
• mods_folder 2.09_晚安梦境(维度)_good-nights-sleep-1.16.5-1.2.14.jar : good_nights_sleep (1.2.14) - 1
• mods_folder 2.04_更好要塞_BetterStrongholds-1.16.4-1.1.jar : betterstrongholds (1.16.4-1.1) - 1
• mods_folder 1.07_区块预加载_Chunk Pregenerator-V1.16-3.0.5.jar : chunkpregen (V1.16-3.0.5) - 1
• mods_folder 6.02_生物群系ID修复_biomeidfixer-1.16.5-1.0.1.s4.jar : biomeidfixer (1.16.5-1.0.1.s4) - 1
• mods_folder 4.01_家具_cfm-7.0.0pre21-1.16.3.jar : cfm (7.0.0-pre21) - 1
• mods_folder 1.02_内存优化_ferritecore-2.0.4-forge.jar : ferritecore (2.0.4) - 1
• mods_folder 5.04.1_边拿边走前置_cloth-config-4.11.19-forge.jar : cloth-config (4.11.19) - 1
• arclight server.jar : arclight (1.16.5-1.0.18-32d233f) - 1
• mods_folder 5.03_搬东西_carryon-1.16.5-1.15.5.15.jar : carryon (1.15.5.15) - 1
• mods_folder 2.07_深谙之园(维度)_The_Undergarden-1.16.5-0.5.2.jar : undergarden (0.5.2) - 1
• mods_folder 5.06_农田不再被踩坏.jar : tramplestopper (2.4.9+mc-1.16.5) - 1
• mods_folder 2.08_神秘群系_MysticsBiomes-1.16.4-1.0.6.jar : mysticsbiomes (1.16.4-1.0.6) - 1
• mods_folder 5.01_砍树_FallingTree-1.16.5-2.11.4.jar : fallingtree (2.11.4) - 1
• maven_libs forge-1.16.5-36.1.4-universal.jar : forge (36.1.4) - 1
• mods_folder 0.01_夸克_Quark-r2.4-312.jar : quark (r2.4-312) - 1
• mods_folder 3.05.1_附魔前置_cofh_core-1.16.4-1.2.1.jar : cofh_core (1.2.1) - 1
• mods_folder 3.05_更多附魔_ensorcellation-1.16.4-1.2.0.jar : ensorcellation (1.2.0) - 1
• mods_folder 3.07_水产养殖2_Aquaculture-1.16.5-2.1.19.jar : aquaculture (1.16.5-2.1.19) - 1
• mods_folder 4.03_各种装饰_supplementaries-1.16.5-0.13.0.jar : supplementaries (1.16.5-0.13.0) - 1
• mods_folder 2.05_更好末地_betterendforge-1.16.4-1.6.0.jar : betterendforge (1.16.4-1.6.0) - 1
• mods_folder 4.04_治疗篝火.jar : healingcampfire (3.2) - 1
• mods_folder 2.10_地牢诞生_dungeonsarise1.16.5-1.2.72a.jar : dungeons_arise (1.2.72a) - 1
• mods_folder 6.01_群系生成修复_chocolate-1.3.0-1.16.4.jar : chocolate (1.3.0-1.16.4) - 1
• mods_folder 3.06_更好的进度_BetterAdvancements-1.16.4-0.1.0.104.jar : betteradvancements (0.1.0.104) - 1
• mods_folder 1.05_MOD加载优化_out_of_sight-1.16.4-1.0.1.jar : out_of_sight (1.16.4-1.0.1) - 1

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 玩家登陆服务器

2. 服务器端输入 op <玩家名字>

3. 玩家自动断联

4. 玩家再次登陆后，重复出现相同问题

5.  服务器端输入 deop <玩家名字>

6. 恢复正常登陆

 

**可在 Forge 复现** [是/否]

**可在 Spigot 复现** [是/否]

### 报错信息
客户端：
![2R L(RK 3DJ99{F`) 0@L5](https://user-images.githubusercontent.com/41555190/121771381-98e13000-cba1-11eb-9bd6-540a90481cb0.png)

[错误日志]

**Comment by IzzelAliz** [comment]
日志发上来，包括客户端的

**Comment by markusxu** [comment]
服务器：
[server_latest.log](https://github.com/IzzelAliz/Arclight/files/6642045/server_latest.log)

客户端：
[client_latest.log](https://github.com/IzzelAliz/Arclight/files/6642044/client_latest.log)

**Comment by IzzelAliz** [comment]
没看到报错，你的客户端的日志可能传错了，被踢出来之后把客户端关掉，传 debug.log

**Comment by markusxu** [comment]
复现错误的时候，我发现是由于我的一个mod导致的

区块预加载：Chunk Pregenerator-V1.16-3.0.5

禁用该mod后，可以正常赋予OP权限。

之前的一些log需要稍等，我需要再次复现一遍

**Comment by PA733** [comment]
服务端加载Chunk Pregenerator后，op需要在客户端也安装Chunk Pregenerator才能正常进入服务器。
这不是服务端问题
