### ISSUE TITLE
ERROR  Feature placement

### ISSUE THREAD

**Issue by RedCarl** [IzzelAliz/Arclight#299]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.19-abf9928]

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [java version "16.0.1" 2021-04-20]

* **操作系统** [CentOS Linux release 7.9.2009 (Core)]

* **插件列表**
LuckPerms, SkinsRestorer, EnchantmentBook, PlaceholderAPI, UltimateAutoRestart, Vault, ProtocolLib, DeluxeChat, Shopkeepers, AuthMe, MysqlPlayerDataBridge, CMILib, CMI

* **Mod 列表**
• minecraft forge-1.16.5-36.1.24-server.jar : minecraft (1.16.5) - 1
• mods_folder TConstruct-1.16.5-3.0.4.197.jar : tconstruct (3.0.4.197) - 1
• mods_folder mana-and-artifice-1.3.0.6.jar : mana-and-artifice (1.3.0.6) - 1
• mods_folder pamhc2trees-1.16.3-1.0.1.jar : pamhc2trees (1.0.1) - 1
• mods_folder MekanismAdditions-1.16.5-10.0.21.448.jar : mekanismadditions (10.0.21) - 1
• mods_folder MekanismDefense-1.16.5-10.0.21.448.jar : mekanismdefense (10.0.21) - 1
• mods_folder pamhc2crops-1.16.3-1.0.2.jar : pamhc2crops (version) - 1
• mods_folder AoA3-3.5.2-1.16.5.jar : aoa3 (3.5.2) - 1
• mods_folder AdvancedRocketry-1.16.5-2.0.0-12-universal.jar : advancedrocketry (1.16.5-2.0.0-12) - 1
• mods_folder Botania-1.16.5-416.jar : botania (1.16.5-416) - 1
• mods_folder ChineseWorkshop-1.16.3-3.2.1.jar : chineseworkshop (3.2.1) - 1
• mods_folder Kiwi-1.16.5-3.5.1.jar : kiwi (3.5.1) - 1
• mods_folder pamhc2foodextended-1.16.3-1.0.2.jar : pamhc2foodextended (version) - 1
• mods_folder Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
• mods_folder curios-forge-1.16.5-4.0.5.2.jar : curios (1.16.5-4.0.5.2) - 1
• mods_folder Patchouli-1.16.4-51.jar : patchouli (1.16.4-51) - 1
• mods_folder Mantle-1.16.5-1.6.109.jar : mantle (1.6.109) - 1
• mods_folder create-mc1.16.5_v0.3.1c.jar : create (mc1.16.5_v0.3.1c+151) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.2.jar : pamhc2foodcore (version) - 1
• mods_folder citadel-1.7.1-1.16.5.jar : citadel (1.7.1) - 1
• mods_folder appliedenergistics2-8.3.1.jar : appliedenergistics2 (8.3.1) - 1
• mods_folder TravelersBackpack-1.16.5-5.4.2.jar : travelersbackpack (5.4.2) - 1
• mods_folder structurize-0.13.177-ALPHA-universal.jar : structurize (0.13.177-ALPHA) - 1
• mods_folder worldedit-mod-7.2.5-dist.jar : worldedit (7.2.5+57d5ac9) - 1
• mods_folder minecolonies-0.14.215-ALPHA-universal.jar : minecolonies (0.14.215-ALPHA) - 1
• mods_folder MekanismTools-1.16.5-10.0.21.448.jar : mekanismtools (10.0.21) - 1
• mods_folder starlight-forge-1.0.0-RC2-1.16.5.jar : starlight (1.0.0-RC2) - 1
• mods_folder LibVulpes-1.16.5-1.0.2-25-universal.jar : libvulpes (1.16.5-1.0.2-25) - 1
• mods_folder cfm-7.0.0pre21-1.16.3.jar : cfm (7.0.0-pre21) - 1
• mods_folder outvoted-1.16.5-1.2.4.jar : outvoted (1.2.4) - 1
• mods_folder iceandfire-2.1.7-1.16.5.jar : iceandfire (2.1.7-1.16.5) - 1
• mods_folder MekanismGenerators-1.16.5-10.0.21.448.jar : mekanismgenerators (10.0.21) - 1
• arclight arclight-forge-1.16-1.0.19.jar : arclight (1.16.5-1.0.19-abf9928) - 1
• maven_libs forge-1.16.5-36.1.24-universal.jar : forge (36.1.24) - 1
• mods_folder cofh_core-1.16.4-1.2.1.jar : cofh_core (1.2.1) - 1
• mods_folder thermal_foundation-1.16.4-1.2.0.jar : thermal (1.2.0) - 1
• mods_folder thermal_innovation-1.16.4-1.2.0.jar : thermal_innovation (1.2.0) - 1
• mods_folder thermal_cultivation-1.16.4-1.2.0.jar : thermal_cultivation (1.2.0) - 1
• mods_folder thermal_expansion-1.16.4-1.2.0.jar : thermal_expansion (1.2.0) - 1
• mods_folder thermal_locomotion-1.16.4-1.2.0.jar : thermal_locomotion (1.2.0) - 1
• mods_folder geckolib-forge-1.16.5-3.0.41.jar : geckolib3 (3.0.41) - 1
• mods_folder dungeonsarise1.16.5-1.2.68a-HF.jar : dungeons_arise (1.2.68a) - 1

### 错误描述

https://paste.ubuntu.com/p/pbPCkWkfjm/

### 重现步骤

目前无法重现此崩溃，偶尔出现.

### 报错信息

https://paste.ubuntu.com/p/pbPCkWkfjm/

**Comment by timi137137** [comment]
地图加载错误，请排除地图文件丢失或损坏

**Comment by RedCarl** [comment]
能正常运行，重新启动即可，所以地图应该是没问题的

**Comment by timi137137** [comment]
> 能正常运行，重新启动即可，所以地图应该是没问题的

java.lang.RuntimeException: We are asking a region for a chunk out of bound | 1359214 -1875000

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/122544103-0b995200-d05f-11eb-9325-532040462755.png)
https://bugs.mojang.com/browse/MC-125134 也说了是文件有问题

**Comment by timi137137** [comment]
Sean, you should probably check your hardware / Windows installation if you get a BSOD from Minecraft crashes.

Maybe Minecraft has made a backup of your world before loading it, check your .minecraft/backups folder.

**Comment by RedCarl** [comment]
内存问题,已经知道了
