### ISSUE TITLE
Arclight 1.15.2 server crash

### ISSUE THREAD

**Issue by RisingInIris2017** [IzzelAliz/Arclight#30]
## Arclight version
arclight-1.15.2-1.0.3-f179b02
## Operating System
Windows Server 2016 (amd64) version 10.0
## Java Version
1.8.0_131, Oracle Corporation
## Java VM Version
Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
## Crash report
https://paste.ubuntu.com/p/Y9BxXhYPNN/

服务端是运行后崩溃的。
我不能确定是否是 Arclight 自身的问题，
希望能得到您的帮助，非常感谢！

**Comment by IzzelAliz** [comment]
与 Apotheosis 该 mod 不兼容
