### ISSUE TITLE
arclight核心于模组forgery不兼容

### ISSUE THREAD

**Issue by zijiren233** [IzzelAliz/Arclight#305]
* **Arclight**  1.16.5.*.19 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** [是/否]
是
* **你确认所有插件都已更新至对应版本** 是
* **Java** 14.0.2
* 只要安装forgery这个模组就无法启动

**Comment by IzzelAliz** [comment]
啥都不说，谜语人是吧

**Comment by zijiren233** [comment]
直接就启动不了，怎么就谜语人了，崩溃报告都没有生成。让我怎么说才不是谜语人，反馈个不兼容还谜语人了。。。

IzzelAliz ***@***.***> 于 2021年6月22日周二 15:41写道：
