### ISSUE TITLE
ae打开后无法放置东西

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#307]
### 我正在运行

* **Arclight** [arclight-1.15.2-1.0.19] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_291] 

* **操作系统** [Linux centos 7.4]

  

* **插件列表** 
插件 (30): AdvancedBan, AutoUnloadChunk, BetterRTP, BlueMap, BossCooling, ChatManager, ClearEntity, CMI, CMILib, ConsoleSpamFix, CoreProtect, Floatingmarket, IllegalStack, LaggRemover, LuckPerms, MiniMOTD, Multiverse-Core, NoSpawnChunks, NotBoom, OverallGamerule, PlaceholderAPI, Plan, PlugMan, ProtocolLib, Residence, SAML, SpeedSystem, TAB, Vault, XConomy
* **Mod 列表** 
Mod List: 
• mods_folder [星辉魔法] astralsorcery-1.16-1.16.5-1.13.11.jar : astralsorcery (1.16.5-1.13.11) - 1
• mods_folder TrashSlot_1.16.3-12.2.1.jar : trashslot (12.2.1) - 1
• mods_folder [下界传送门修正] NetherPortalFix_1.16.3-7.2.1.jar : netherportalfix (7.2.1) - 1
• mods_folder [潘马斯农场2 - 树木] pamhc2trees-1.16.3-1.0.1.jar : pamhc2trees (1.0.1) - 1
• mods_folder [虚无世界] AoA3-3.5.2-1.16.5.jar : aoa3 (3.5.2) - 1
• mods_folder xlpackets-1.1.jar : xlpackets (1.1) - 1
• mods_folder [API][JEI物品管理器] jei-1.16.5-7.7.0.104.jar : jei (7.7.0.104) - 1
• mods_folder JustEnoughCalculation-1.16.5-3.6.6.jar : jecalculation (3.6.6) - 1
• mods_folder [拔刀剑] SlashBlade-1.16-0.0.9.jar : slashblade (0.0.9) - 1
• mods_folder [中式工坊] ChineseWorkshop-1.16.3-3.2.1.jar : chineseworkshop (3.2.1) - 1
• mods_folder [Kiwi] Kiwi-1.16.5-3.5.1.jar : kiwi (3.5.1) - 1
• mods_folder [通用机械] Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
• mods_folder modnametooltip_1.16.2-1.15.0.jar : modnametooltip (1.15.0) - 1
• mods_folder invtweaks-1.16.4-1.0.1.jar : invtweaks (1.16.4-1.0.1) - 1
• mods_folder [机械动力]reate-mc1.16.5_v0.3.1c.jar : create (mc1.16.5_v0.3.1c+151) - 1
• mods_folder FastSuite-1.16.4-1.0.2.jar : fastsuite (1.0.2) - 1
• mods_folder Controlling-7.0.0.15.jar : controlling (7.0.0.15) - 1
• mods_folder [连接材质] CTM-MC1.16.1-1.1.2.6.jar : ctm (MC1.16.1-1.1.2.6) - 1
• mods_folder Placebo-1.16.4-4.4.2.jar : placebo (4.4.2) - 1
• mods_folder citadel-1.6.2.jar : citadel (1.6.2) - 1
• mods_folder [应用能源2]appliedenergistics2-8.4.0.jar : appliedenergistics2 (8.4.0) - 1
• mods_folder [装饰方块] decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder ColouredTooltips-1.16.5-11.0.2.jar : colouredtooltips (11.0.2) - 1
• mods_folder Bookshelf-1.16.5-10.0.8.jar : bookshelf (10.0.8) - 1
• mods_folder Tips-1.16.5-4.0.8.jar : tips (4.0.8) - 1
• mods_folder biomeidfixer-1.16.5-1.0.1.s4.jar : biomeidfixer (1.16.5-1.0.1.s4) - 1
• mods_folder [拔刀附属]山樱之刃Yamazakura-1.16.4-r1.jar : yamazakura (1.1) - 1
• mods_folder randompatches-2.4.4-forge.jar : randompatches (2.4.4-forge) - 1
• mods_folder lazydfu-0.1.3.jar : lazydfu (0.1.3) - 1
• mods_folder buildinggadgets-1.16.5-3.8.0.jar : buildinggadgets (3.8.0) - 1
• mods_folder starlight-forge-1.0.0-RC2-AeiouCreatePatch_3.jar : starlight (1.0.0-RC2) - 1
• mods_folder [冰火传说 ／ 冰与火之歌] iceandfire-2.1.5-1.16.4.jar : iceandfire (2.1.5-1.16.4) - 1
• mods_folder [通用机械发电机] MekanismGenerators-1.16.5-10.0.21.448.jar : mekanismgenerators (10.0.21) - 1
• mods_folder [背包宠物] inventorypets-1.16.5-2.0.14.jar : inventorypets (2.0.14) - 1
• mods_folder [拔刀附属]ex_blades-1.16-1.1.jar : ex_blades (1.1) - 1
• mods_folder [动态视距] dynviewdist-1.9.jar : dynview (1.8) - 1
• mods_folder [搬箱] carryon-1.16.5-1.15.3.13.jar : carryon (1.15.3.13) - 1
• mods_folder [Just Enough Resources] JustEnoughResources-1.16.4-0.12.0.109.jar : jeresources (0.12.0.109) - 1
• mods_folder [沉浸原油] ImmersivePetroleum-1.16.5-3.2.0-3.jar : immersivepetroleum (3.2.0-3) - 1
• maven_libs forge-1.16.5-36.1.24-universal.jar : forge (36.1.24) - 1
• mods_folder recipebuffers-2.1.jar : recipebuffers (2.1) - 1
• mods_folder [暮色森林] twilightforest-1.16.5-4.0.490-universal.jar : twilightforest (NONE) - 1
• mods_folder betterendforge-1.16.4-1.6.0.jar : betterendforge (1.16.4-1.6.0) - 1
• mods_folder [动态环境／动态环绕] DynamicSurroundings-1.16.4-4.0.4.2.jar : dsurround (1.16.4-4.0.4.2) - 4
• mods_folder [更多箱子] ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1
• minecraft forge-1.16.5-36.1.24-server.jar : minecraft (1.16.5) - 1
• mods_folder [匠魂] TConstruct-1.16.5-3.0.4.171.jar : tconstruct (3.0.4.171) - 1
• mods_folder [附魔描述] EnchantmentDescriptions-1.16.5-7.0.8.jar : enchdesc (7.0.8) - 1
• mods_folder MouseTweaks-2.14-mc1.16.2.jar : mousetweaks (2.14) - 1
• mods_folder [沉浸工程] ImmersiveEngineering-1.16.5-4.2.4-134.jar : immersiveengineering (1.16.5-4.2.4-134) - 1
• mods_folder [超多生物群系] BiomesOPlenty-1.16.5-13.1.0.471-universal.jar : biomesoplenty (1.16.5-13.1.0.471) - 1
• mods_folder valkyrielib-1.16.5-3.0.8.0.jar : valkyrielib (1.16.5-3.0.8.0) - 1
• mods_folder envirocore-1.16.5-3.0.8.0.jar : envirocore (1.16.5-3.0.8.0) - 1
• mods_folder [环境科技] envirotech-1.16.5-3.0.8.0.jar : envirotech (1.16.5-3.0.8.0) - 1
• mods_folder simplechunkloaders-1.16.5-1.0.8.0.jar : simplechunkloaders (NONE) - 1
• mods_folder [潘马斯农场2 - 作物] pamhc2crops-1.16.3-1.0.2.jar : pamhc2crops (version) - 1
• mods_folder [盔甲韧性显示] toughnessbar-6.1.jar : toughnessbar (6.1) - 1
• mods_folder smoothboot-forge-1.16.4-1.2.2.jar : smoothboot (1.16.4-1.2.2) - 1
• mods_folder Botania-1.16.5-416.jar : botania (1.16.5-416) - 1
• mods_folder [潘马斯农场2 - 食物拓展] pamhc2foodextended-1.16.3-1.0.2.jar : pamhc2foodextended (version) - 1
• mods_folder [JEI扩展] jeiintegration_1.16.5-7.0.1.15.jar : jeiintegration (7.0.1.15) - 1
• mods_folder [Curios API] curios-forge-1.16.5-4.0.5.1.jar : curios (1.16.5-4.0.5.1) - 1
• mods_folder Patchouli-1.16.4-51.jar : patchouli (1.16.4-51) - 1
• mods_folder [地幔] Mantle-1.16.5-1.6.103.jar : mantle (1.6.103) - 1
• mods_folder [Just A Ore Processing Compatibility Attempt] JAOPCA-1.16.5-3.4.0.9.jar : jaopca (3.4.0.9) - 1
• mods_folder ftb-backups-2.1.1.6.jar : ftbbackups (2.1.1.6) - 1
• mods_folder collective-1.16.5-2.26.jar : collective (2.26) - 1
• mods_folder [潘马斯农场2 - 食物核心] pamhc2foodcore-1.16.3-1.0.2.jar : pamhc2foodcore (version) - 1
• mods_folder [箱子搜索栏] searchablechests-1.16-1.5.4.jar : searchablechests (1.16-1.5.4) - 1
• mods_folder [工作台性能优化] FastWorkbench-1.16.4-4.5.1.jar : fastbench (4.5.1) - 1
• mods_folder StorageDrawers-1.16.3-8.2.2.jar : storagedrawers (8.2.2) - 1
• mods_folder OreExcavation-1.8.157.jar : oreexcavation (1.8.157) - 1
• mods_folder [通量网络] FluxNetworks-1.16.5-6.1.7.12.jar : fluxnetworks (6.1.7.12) - 1
• mods_folder [加速火把] torcherino-13.0.3+1.16.3.jar : torcherino (13.0.3) - 1
• mods_folder JustEnoughCharacters-1.16.4-4.1.6.jar : jecharacters (4.1.6) - 1
• mods_folder elevatorid-1.16.5-1.7.13.jar : elevatorid (1.16.5-1.7.13) - 1
• mods_folder [区块预生成器] Chunk Pregenerator-V1.16-3.0.5.jar : chunkpregen (V1.16-3.0.5) - 1
• mods_folder [结构化] structurize-0.13.177-ALPHA-universal.jar : structurize (0.13.177-ALPHA) - 1
• mods_folder buildersaddition-1.16.5-20210421a.jar : buildersaddition (1.16.5-20210421a) - 1
• mods_folder constructionwand-1.16.5-2.2.jar : constructionwand (1.16.5-2.2) - 1
• mods_folder [熔炉性能优化] FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
• mods_folder [模拟殖民地] minecolonies-0.14.215-ALPHA-universal.jar : minecolonies (0.14.215-ALPHA) - 1
• mods_folder furniture-7.0.0-pre19-1.16.3.jar : cfm (7.0.0-pre19) - 1
• mods_folder architectury-1.12.150-forge.jar : architectury (1.12.150) - 1
• mods_folder ftb-gui-library-1605.2.1.41-forge.jar : ftbguilibrary (1605.2.1.41) - 1
• mods_folder ferritecore-2.0.4-forge.jar : ferritecore (2.0.4) - 1
• mods_folder [AI改进] AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder observerlib-1.16.5-1.5.2.jar : observerlib (1.16.5-1.5.2) - 1
• mods_folder cloth-config-4.11.26-forge.jar : cloth-config (4.11.26) - 1
• mods_folder [耐久信息显示] durabilityviewer-1.16.4-forge35.0.7-1.10.jar : durabilityviewer (1.16.4-forge35.0.7-1.10) - 1
• arclight server.jar : arclight (1.16.5-1.0.19-abf9928) - 1
• mods_folder [经典状态条] classicbar-4.1.0-1.16.5.jar : classicbar (4.1.0-1.16.5) - 1
• mods_folder [树叶快速腐烂] FastLeafDecay-v25.jar : fastleafdecay (v25) - 1
• mods_folder [雕凿工艺] chiselsandbits-0.3.4-RELEASE.jar : chiselsandbits (NONE) - 1
• mods_folder [护甲上限突破] overloadedarmorbar-5.1.0.jar : overloadedarmorbar (5.1.0) - 1
• mods_folder OpenLoader-1.16.5-9.0.2.jar : openloader (9.0.2) - 1
• mods_folder deuf-1.16.4-1.1.jar : deuf (1.16.4-1.1) - 1

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 AE

2. 进入服务器后 搭建AE

3. 放入东西后无法显示

 
链接：https://pan.baidu.com/s/1wcheUTN09ycifB8L0UhGrw 提取码：jxzh

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[后台无任何报错]

**Comment by ghost** [comment]
问题描述补充:
把ae正常搭建之后，把东西可以放进去，但是不可以显示，也不可以拿出来，也不可以进行合成，但是可以通过输出接口输出
arcligt版本更正
arclight-1.16.5-1.0.19

**Comment by timi137137** [comment]
好家伙，怎么听起来有点耳熟

**Comment by ghost** [comment]
插件mod补充链接
之前那个是客户端
链接：https://pan.baidu.com/s/1mnvCONmhIlD7DA8YzZgQAw 
提取码：1234
