### ISSUE TITLE
ElementalCraft incompatible (i think based off logs, unsure)

### ISSUE THREAD

**Issue by Xplodin** [IzzelAliz/Arclight#311]
### I am running

* **Arclight** [1.16.5.1.0.19] 

* **This is the latest development version** [Y/N, because ___]

* **Java** [ 1.8.0_282] 

* **Operating System** [linux ubuntu 18.04]

  

* **N/A** 

TNP Limitless 3. 369 mods. 1.10.6
Crashes instantly with performant removed as well

### Description

Critical injection failure: Variable modifier method 

### Step to reproduce

1. Install TNP and update arclight to use latest forge jar by renaming the new one to old one in faq
2. Boot arclight
3. witness crash that seems to be from elemental craft

https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3350339 

**Reproducible in Forge** `NOPE`

**Reproducible in Spigot** NOPE

### Logs

[ERROR LOG]

**Comment by IzzelAliz** [comment]
Your log link is invalid, please upload to github gist or ubuntu paste.

**Comment by Xplodin** [comment]
Sorry about that. No idea why it invalidated.
https://gist.github.com/Xplodin/cec400f2603ef1759094b911a863efb0
