### ISSUE TITLE
ProgressiveBosses崩溃

### ISSUE THREAD

**Issue by nainiu233** [IzzelAliz/Arclight#316]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.20-SNAPSHOT-dd92ceb] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [build 16.0.1+9-24] 

* **操作系统** [windows 10 21H1 19043.1052]

  

* **插件列表** 
无插件
* **Mod 列表** 
ProgressiveBosses-Beta-3.1.1-mc1.16.5
InsaneLib-1.1.0-mc1.16.5

### 错误描述

启动崩溃
### 重现步骤

1. 安装模组后启动服务器

### OneDrive
https://1drv.ms/u/s!Al_-L17sT3U9hfMaNrIaq13BEBt5-g?e=H8hxpc

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/8WJNfpF3FX/

**Comment by timi137137** [comment]
你需要去他们的github上反馈这个问题，这个问题出在他们的mixin(看不懂没关系告诉原因而已w
