### ISSUE TITLE
虚无世界无法召唤boss

### ISSUE THREAD

**Issue by Qiuscraft** [IzzelAliz/Arclight#320]
### 我正在运行

* **Arclight** arclight-1.16.5-1.0.19-abf9928 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是（虚无世界mod版本为3.5.2，其他的插件和mod均为最新版本）

* **Java** 16.0.1 

* **操作系统** Windows Server 2016

  

* **插件列表** 
Plugins (1): SkinsRestorer
* **Mod 列表** 
[19:35:35] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List:
• minecraft forge-1.16.5-36.1.24-server.jar : minecraft (1.16.5) - 1
• mods_folder TConstruct-1.16.5-3.0.4.197.jar : tconstruct (3.0.4.197) - 1
• mods_folder FastFurnace-1.16.4-4.4.0.jar : fastfurnace (4.4.0) - 1
• mods_folder SpartanWeaponry-1.16.4-2.1.0-beta-4.jar : spartanweaponry (2.1.0 beta 4) - 1
• mods_folder ironfurnaces-1.16.5-2.6.8.jar : ironfurnaces (2.6.8) - 1
• mods_folder Apotheosis-1.16.4-4.6.1.jar : apotheosis (4.6.1) - 1
• mods_folder ferritecore-2.0.5-forge.jar : ferritecore (2.0.5) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder AoA3-3.5.2-1.16.5.jar : aoa3 (3.5.2) - 1
• arclight arclight-forge-1.16-1.0.19.jar : arclight (1.16.5-1.0.19-abf9928) - 1
• maven_libs forge-1.16.5-36.1.24-universal.jar : forge (36.1.24) - 1
• mods_folder recipebuffers-2.1.jar : recipebuffers (2.1) - 1
• mods_folder twilightforest-1.16.5-4.0.490-universal.jar : twilightforest (NONE) - 1
• mods_folder supplementaries-1.16.5-0.14.3.jar : supplementaries (1.16.5-0.14.3) - 1
• mods_folder Mantle-1.16.5-1.6.109.jar : mantle (1.6.109) - 1
• mods_folder Croptopia-1.16.4-FORGE-1.4.2.jar : croptopia (1.4.2) - 1
• mods_folder selene-1.16.5-1.3.jar : selene (1.16.5-1.0) - 1
• mods_folder ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1
• mods_folder FastWorkbench-1.16.4-4.5.1.jar : fastbench (4.5.1) - 1
• mods_folder corpse-1.16.5-1.0.5.jar : corpse (1.16.5-1.0.5) - 1
• mods_folder Placebo-1.16.4-4.5.0.jar : placebo (4.5.0) - 1
• mods_folder TravelersBackpack-1.16.5-5.4.2.jar : travelersbackpack (5.4.2) - 1
• mods_folder OreExcavation-1.8.157.jar : oreexcavation (1.8.157) - 1

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息
在forge官服（forge-1.16.5-36.1.24）中，仅安装虚无世界3.5.2版本，扔出物品“巨怪人偶”，十秒后该物品将消失并生成boss“粉碎”
而在arclight-1.16.5-1.0.19-abf9928中，仅安装虚无世界3.5.2版本，扔出物品“巨怪人偶”，十秒后该物品将消失而没有生成boss“粉碎”

### 重现步骤

1. 安装 虚无世界3.5.2版本（最新版虚无世界无法在多人游戏中使用，因此安装该版本）

2. 进入服务器后，在创造模式中拿出物品“巨怪人偶”

3. 将该物品直接按Q丢到地面上，十秒后该物品将消失，若是forge官服会生成boss“粉碎”，而arclight则不会

 
https://1drv.ms/u/s!AoSzv18XWNqvgdEnJ4jDYD_hkm6xzQ?e=jhCdnD

**可在 Forge 复现** 是
在forge官服下可以生成boss而arclight不能

**可在 Spigot 复现** 否

### 报错信息
无任何报错信息

[错误日志]

**Comment by Qiuscraft** [comment]
补充：
  Java16.0.1无法运行forge官服，因此我使用jdk1.8.0_291来运行forge官服，在forge官服中可以正常生成boss。
  而在arclight-1.16.5-1.0.19-abf9928中，无论是Java16.0.1还是jdk1.8.0_291，均无法生成boss

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/124920214-ac10df80-e029-11eb-87b5-027b5b7cb03a.png)
请使用最新构建

**Comment by Qiuscraft** [comment]
> ![image](https://user-images.githubusercontent.com/36812439/124920214-ac10df80-e029-11eb-87b5-027b5b7cb03a.png)
> 请使用最新构建

是最新的了呀 我正在使用arclight-1.16.5-1.0.19-abf9928

**Comment by timi137137** [comment]
> > ![image](https://user-images.githubusercontent.com/36812439/124920214-ac10df80-e029-11eb-87b5-027b5b7cb03a.png)
> > 请使用最新构建
> 
> 是最新的了呀 我正在使用arclight-1.16.5-1.0.19-abf9928

最新构建不等于最新版本QWQ

**Comment by Qiuscraft** [comment]
> > > ![image](https://user-images.githubusercontent.com/36812439/124920214-ac10df80-e029-11eb-87b5-027b5b7cb03a.png)
> > > 请使用最新构建
> > 
> > 
> > 是最新的了呀 我正在使用arclight-1.16.5-1.0.19-abf9928
> 
> 最新构建不等于最新版本QWQ

明白

**Comment by Qiuscraft** [comment]
arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de仍然存在该问题

**Comment by Qiuscraft** [comment]
一个奇怪的现象：我在本地测试的时候，arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de无法召唤boss，当我将arclight-1.16.5-1.0.20-SNAPSHOT-9dbe8de上传到服务器上，服务器的玩家们却说可以召唤boss了，我去服务器里尝试也确实如此。最新构建应该是可以正常召唤boss了，可能我在本地测试的时候昏头了用的还是老版本。
