### ISSUE TITLE
基于TABOOLIB的插件好像都无法正常加载

### ISSUE THREAD

**Issue by nainiu233** [IzzelAliz/Arclight#321]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.20-SNAPSHOT-dd92ceb] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [build 16.0.1+9-24] 

* **操作系统** [windows 10 21H1 19043.1052]

  

* **插件列表** 
AttributePlus,AttributeInventory, ProtocolLib, TabooLib5, TrMenu
* **Mod 列表** 
无

### 错误描述

TrMenu AttributePlus无法正常加载 [甚至/plugins 没有输出AttributePlus]

### 重现步骤

1. 安装 TrMenu AttributePlus ProtocolLib
2. 加载完成后使用指令提示未知

### onedrive
https://1drv.ms/u/s!Al_-L17sT3U9hfcfnG3bMBdBnDu3gw?e=XcNhNn

 

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
https://paste.ubuntu.com/p/8K3f6GTKzq/

**Comment by IzzelAliz** [comment]
那你不要用 jdk16
