### ISSUE TITLE
客户端连接服务器会导致崩溃

### ISSUE THREAD

**Issue by 2651084156** [IzzelAliz/Arclight#325]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.19.jar和arclight-forge-1.16.5-1.0.20-SNAPSHOT.jar] 

* **你确认这是最新版吗** [后面一个是

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [无插件]

* **Java** [1.8.0_291-b10] 

* **操作系统** [window+版本]

* **插件列表** 无插件]

* **Mod 列表** 
* [09:44:15] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List:
• mods_folder consecration-forge-1.16.5-4.0.0.5.jar : consecration (1.16.5-4.0.0.5) - 1
• mods_folder IntegratedTerminals-1.16.5-1.2.4.jar : integratedterminals (1.2.4) - 2
• mods_folder planttech2-0.02.29.jar : planttech2 (0.02.29) - 1
• mods_folder mcw-windows-1.0.3-mc1.16.5.jar : mcwwindows (1.0.3) - 1
• mods_folder BetterCaves-Forge-1.16.4-1.1.2.jar : bettercaves (1.16.4-1.1.2) - 1
• mods_folder ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar : forgeendertech (7.1.0.0) - 1
• mods_folder CTM-MC1.16.1-1.1.2.6.jar : ctm (MC1.16.1-1.1.2.6) - 1
• mods_folder artisanworktables-2.0.1.jar : artisanworktables (2.0.1) - 1
• mods_folder YungsApi-1.16.4-Forge-6.jar : yungsapi (1.16.4-Forge-6) - 1
• mods_folder premium-wood-1.16.4-1.3.4.jar : premium_wood (1.3.4) - 1
• mods_folder Powah-1.16.5-2.3.16.jar : powah (2.3.16) - 1
• mods_folder randompatches-2.4.4-forge.jar : randompatches (2.4.4-forge) - 1
• mods_folder Morpheus-1.16.5-4.2.70.jar : morpheus (4.2.70) - 1
• mods_folder speedyhoppers-1.16.4-1.jar : speedyhoppers (1.16.4-1) - 1
• mods_folder SnowRealMagic-1.16.4-2.5.7.jar : snowrealmagic (2.5.7) - 1
• mods_folder JustEnoughResources-1.16.3-0.12.0.100.jar : jeresources (0.12.0.100) - 1
• mods_folder shetiphiancore-1.16-3.8.5.jar : shetiphiancore (3.8.5) - 1
• mods_folder integrated_proxy-1.16-1.0.16.jar : integrated_proxy (1.0.16) - 1
• mods_folder PattysMoreStuff-Stable-1.16.4-1.3.2.jar : pattysmorestuff (1.3.2) - 1
• mods_folder SlideShow-0.4.3.jar : slide_show (0.4.3) - 1
• mods_folder betterendforge-1.16.4-1.6.0.jar : betterendforge (1.16.4-1.6.0) - 1
• mods_folder industrial-foregoing-1.16.5-3.2.14.2-8.jar : industrialforegoing (3.2.14.2) - 1
• mods_folder 生物群系BiomesOPlenty-1.16.5-13.1.0.480-universal.jar : biomesoplenty (1.16.5-13.1.0.480) - 1
• mods_folder ModularVoiceChat-BETA-MC1.16.5-1.0.jar : modularvc (BETA-MC1.16.5-1.0) - 1
• mods_folder Botania-1.16.5-416.jar : botania (1.16.5-416) - 1
• mods_folder 分析spark-forge.jar : spark (1.6.0) - 1
• mods_folder curios-forge-1.16.5-4.0.5.2.jar : curios (1.16.5-4.0.5.2) - 1
• mods_folder advgenerators-0.10.1.11-mc1.16.5.jar : advgenerators (0.10.1.11) - 1
• mods_folder Nuclear+Science-1.16.5-0.3.0-0.jar : nuclearscience (1.16.5-0.3.0-0) - 1
• mods_folder worldedit-mod-7.2.5-dist.jar : worldedit (7.2.5+57d5ac9) - 1
• mods_folder campfire_overhaul-1.16.5-1.0.4.1.jar : campfire_overhaul (1.0.4.1) - 1
• mods_folder cfm-7.0.0pre22-1.16.3.jar : cfm (7.0.0-pre22) - 1
• mods_folder mcw-furniture-2.0.1-mc1.16.5.jar : mcwfurnitures (2.0.1) - 1
• mods_folder cloth-config-4.11.26-forge.jar : cloth-config (4.11.26) - 1
• mods_folder AdChimneys-1.16.4-6.0.11.0-build.0144.jar : adchimneys (6.0.11.0) - 1
• mods_folder CodeChickenLib-1.16.5-4.0.2.427-universal.jar : codechickenlib (4.0.2.427) - 1
• mods_folder BetterMineshafts-Forge-1.16.4-2.0.4.jar : bettermineshafts (1.16.4-2.0.4) - 1
• mods_folder geckolib-forge-1.16.5-3.0.41.jar : geckolib3 (3.0.41) - 1
• mods_folder minecoprocessors-1.16.5-1.0.5-b1.jar : minecoprocessors (1.0.5-b1) - 1
• mods_folder Kiwi-1.16.5-3.5.1.jar : kiwi (3.5.1) - 1
• mods_folder mcef-1.16.5-2.11.jar : mcef (2.11) - 1
• mods_folder woot-1.16.5-1.0.8.0.jar : woot (1.16.5-1.0.8.0) - 1
• mods_folder jei-1.16.5-7.7.0.107.jar : jei (7.7.0.107) - 1
• mods_folder Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
• mods_folder bdlib-1.17.1.11-mc1.16.5.jar : bdlib (1.17.1.11) - 1
• mods_folder PassableFoliage-1.16.5-2.2.1.jar : passablefoliage (2.2.1) - 1
• mods_folder shutupexperimentalsettings-1.0.3.jar : shutupexperimentalsettings (1.0.3) - 1
• mods_folder catjammies-1.1.0.jar : catjammies (NONE) - 1
• mods_folder LibX-1.16.3-1.0.76.jar : libx (1.16.3-1.0.76) - 1
• mods_folder cursedearth-3.2.jar : cursedearth (3.2) - 1
• mods_folder compactmachines-4.0.0-beta.2.jar : compactmachines (4.0.0-beta.2) - 1
• mods_folder athenaeum-2.0.0.jar : athenaeum (NONE) - 1
• mods_folder alib-1.16.4-1.jar : alib (1.16.4-1) - 1
• mods_folder 关照starlight-forge-1.0.0-RC2-1.16.5.jar : starlight (1.0.0-RC2) - 1
• mods_folder outvoted-1.16.5-1.2.4.jar : outvoted (1.2.4) - 1
• mods_folder 个人修改Electrodynamics.jar : electrodynamics (1.16.5-0.4.0-1) - 1
• mojangdark_mod_jar mojangdark-1.16.5-1.0.2.jar : mojangdark (1.0.2) - 1
• mods_folder ImmersivePetroleum-1.16.5-3.3.0-4.jar : immersivepetroleum (3.3.0-4) - 1
• maven_libs forge-1.16.5-36.1.24-universal.jar : forge (36.1.24) - 1
• mods_folder DynamicSurroundings-1.16.4-4.0.4.2.jar : dsurround (1.16.4-4.0.4.2) - 4
• mods_folder 地牢改配置dungeonsarise1.16.5-1.2.68a-HF.jar : dungeons_arise (1.2.68a) - 1
• mods_folder MythicBotany-1.16.4-1.3.15.jar : mythicbotany (1.16.4-1.3.15) - 1
• mods_folder IntegratedCrafting-1.16.5-1.0.15.jar : integratedcrafting (1.0.15) - 1
• mods_folder alchemistry-1.16.5-1.jar : alchemistry (1.16.5-1) - 1
• mods_folder ZeroCore2-1.16.4-2.0.21.jar : zerocore (1.16.4-2.0.21) - 1
• minecraft forge-1.16.5-36.1.24-server.jar : minecraft (1.16.5) - 1
• mods_folder cofh_core-1.16.4-1.2.1.jar : cofh_core (1.2.1) - 1
• mods_folder thermal_foundation-1.16.4-1.2.0.jar : thermal (1.2.0) - 1
• mods_folder thermal_innovation-1.16.4-1.2.0.jar : thermal_innovation (1.2.0) - 1
• mods_folder thermal_locomotion-1.16.4-1.2.0.jar : thermal_locomotion (1.2.0) - 1
• mods_folder Flopper-1.16.5-1.0.7.jar : flopper (1.0.7) - 1
• mods_folder Psi+1.16-94.jar : psi (1.16-94) - 1
• mods_folder ImmersiveEngineering-1.16.5-5.0.0-135.jar : immersiveengineering (1.16.5-5.0.0-135) - 1
• mods_folder ClassicalArt-1.16.3+-1.1.0.jar : classicalart (1.1.0) - 1
• mods_folder piggybanks-1.16.5-1.0.4.jar : piggybanks (1.16.5-1.0.3) - 1
• mods_folder CrimsonNBTTags.jar : crimsonnbt (1.1.6) - 1
• mods_folder ceilingtorch-1.16.5-v1.13.jar : ceilingtorch (v1.13) - 1
• mods_folder SimpleLogin-1.16-1.1.1.jar : simplelogin (1.1.1) - 1
• mods_folder Mantle-1.16.5-1.6.109.jar : mantle (1.6.109) - 1
• mods_folder IntegratedDynamics-1.16.5-1.8.5.jar : integrateddynamics (1.8.5) - 2
• mods_folder integratednbt-1.16.4-1.4.2.jar : integratednbt (version) - 1
• mods_folder ftb-backups-2.1.1.6.jar : ftbbackups (2.1.1.6) - 1
• mods_folder thermal_cultivation-1.16.4-1.2.0.jar : thermal_cultivation (1.2.0) - 1
• mods_folder SecureExplosion-1.16.5-1.0.jar : secureexplosion (1.0) - 1
• mods_folder polymorph-forge-1.16.5-0.25.jar : polymorph (1.16.5-0.25) - 1
• mods_folder 好东西PiTweaks-1.16.5-1.3.2.jar : pitweaks (1.16.5-1.3.2) - 1
• mods_folder IngameIME-forge-1.16.5-remapped-1.6.1.jar : ingameime (1.6.1) - 1
• mods_folder WorldEdit-CUI-FE3-1.16.5-3.0.9.jar : worldeditcuife3 (3.0.9) - 1
• mods_folder WorldHandler-1.16.5-2.12.5.jar : worldhandler (1.16.5-2.12.5) - 1
• mods_folder occultism-1.16.5-1.6.2.jar : occultism (1.16.5-1.6.2) - 1
• mods_folder PizzaCraft-1.16.5-3.0.5.jar : pizzacraft (3.0.5) - 1
• mods_folder terraqueous-1.16-1.7.15.jar : terraqueous (1.7.15) - 3
• mods_folder magipsi-1.16.4-2.0.0.0.jar : magipsi (1.16.4-2.0.0.0) - 1
• mods_folder morered-1.16.5-2.1.1.0.jar : morered (2.1.1.0) - 1
• mods_folder MagicMirror-1.16.5-0.0.9.466.jar : magic_mirror (1.16.5-0.0.9.466) - 1
• mods_folder CyclopsCore-1.16.5-1.11.7.jar : cyclopscore (1.11.7) - 1
• mods_folder 热带世界Tropicraft-9.0.0-beta+54.jar : tropicraft (9.0.0-beta+54) - 1
• mods_folder aiotbotania-1.16.5-1.7.0.jar : aiotbotania (1.7.0) - 1
• mods_folder Wyrmroost-1.16.3-1.2.11.jar : wyrmroost (1.16.3-1.2.11) - 1
• mods_folder deadlyendphantoms-1.16.4-3.0.0.jar : deadlyendphantoms (3.0.0) - 1
• mods_folder rsgauges-1.16.4-1.2.10.jar : rsgauges (1.2.10) - 1
• mods_folder 自动建造mightyarchitect-mc1.16.3_v0.5.jar : mightyarchitect (0.5) - 1
• mods_folder potionsmaster-0.2.0-1.16.5-36.0.52.jar : potionsmaster (0.2.0-1.16.5-36.0.52) - 1
• mods_folder Bookshelf-1.16.5-10.1.11.jar : bookshelf (10.1.11) - 1
• mods_folder DarkUtilities-1.16.5-8.0.10.jar : darkutils (8.0.10) - 1
• mods_folder BetterDrowning-1.16.5-2.0.2.jar : betterdrowning (2.0.2) - 1
• mods_folder mcw-doors-1.0.3-mc1.16.5.jar : mcwdoors (1.0.3) - 1
• mods_folder MekanismGenerators-1.16.5-10.0.21.448.jar : mekanismgenerators (10.0.21) - 1
• mods_folder XNetGases-1.16.5-2.2.6.jar : xnetgases (2.2.6) - 1
• mods_folder twilightforest-1.16.5-4.0.490-universal.jar : twilightforest (NONE) - 1
• mods_folder FinalKobold-1.16-1.0.0.jar : fk (1.16-1.0.0) - 1
• mods_folder spatialharvesters_forge_1.16.5-0.11.10.jar : spatialharvesters (0.11.10) - 1
• mods_folder mob_grinding_utils-1.16.5-0.4.23.jar : mob_grinding_utils (1.16.5-0.4.23) - 1
• mods_folder cuneiform-1.16.3-1.2.5.jar : cuneiform (1.16.3-1.2.5) - 1
• mods_folder mcw-bridges-1.0.6-mc1.16.5.jar : mcwbridges (1.0.6) - 1
• mods_folder endertanks-1.16-1.9.5.jar : endertanks (1.9.5) - 1
• mods_folder CommonCapabilities-1.16.5-2.7.0.jar : commoncapabilities (2.7.0) - 1
• mods_folder AmbientSounds_v3.1.9_mc1.16.5.jar : ambientsounds (3.0.3) - 1
• mods_folder AdPoles-1.16.4-5.0.5.0-build.0146.jar : adpoles (5.0.5.0) - 1
• mods_folder projectvibrantjourneys-1.16.5-3.1.0.jar : projectvibrantjourneys (1.16.5-3.1.0) - 1
• mods_folder MekanismAdditions-1.16.5-10.0.21.448.jar : mekanismadditions (10.0.21) - 1
• mods_folder EndRemastered-R36.jar : endrem (1.16.3) - 1
• mods_folder valkyrielib-1.16.5-3.0.9.0.jar : valkyrielib (1.16.5-3.0.9.0) - 1
• mods_folder envirocore-1.16.5-3.0.9.0.jar : envirocore (1.16.5-3.0.9.0) - 1
• mods_folder envirotech-1.16.5-3.0.9.1.jar : envirotech (1.16.5-3.0.9.1) - 1
• mods_folder Lollipop-1.16.5-3.2.9.jar : lollipop (3.2.9) - 1
• mods_folder drawerfps-1.9.jar : drawerfps (1.9) - 1
• mods_folder artisantools-2.1.0.jar : artisantools (2.1.0-1-g9462e4e) - 1
• mods_folder TrackAPI-1.16.4-forge-1.2.1.jar : trackapi (1.2) - 1
• mods_folder Bountiful-1.16.4-3.3.1.jar : bountiful (1.16.4-3.3.1) - 1
• mods_folder dpanvil-1.16.5-1.2.2.jar : dpanvil (1.16.5-1.2.2) - 1
• mods_folder Patchouli-1.16.4-53.jar : patchouli (1.16.4-53) - 1
• mods_folder ars_nouveau-1.16.5-1.18.11.jar : ars_nouveau (1.18.11) - 1
• mods_folder time-in-a-bottle-1.1.0.jar : tiab (1.1.0) - 1
• mods_folder thermal_expansion-1.16.4-1.2.0.jar : thermal_expansion (1.2.0) - 1
• mods_folder IntegratedTunnels-1.16.5-1.8.3.jar : integratedtunnels (1.8.3) - 2
• mods_folder elevatorid-1.16.5-1.7.13.jar : elevatorid (1.16.5-1.7.13) - 1
• mods_folder BetterStrongholds-1.16.4-1.1.jar : betterstrongholds (1.16.4-1.1) - 1
• mods_folder MekanismTools-1.16.5-10.0.21.448.jar : mekanismtools (10.0.21) - 1
• mods_folder SpartanWeaponry-1.16.4-2.1.0-beta-4.jar : spartanweaponry (2.1.0 beta 4) - 1
• mods_folder architectury-1.19.27-forge.jar : architectury (1.19.27) - 1
• mods_folder bambooeverything-1.16.5-1.0.0-forge.jar : bambooeverything (1.0.0) - 1
• mods_folder ftb-library-forge-1605.3.1-build.48.jar : ftblibrary (1605.3.1-build.48) - 1
• mods_folder ftb-gui-library-1605.2.1.41-forge.jar : ftbguilibrary (1605.2.1.41) - 1
• mods_folder ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar : immersiverailroading (1.16.4-forge-1.8.0) - 1
• mods_folder UniversalModCore-1.16.4-forge-1.0.1.jar : universalmodcore (1.0.1) - 1
• mods_folder moreoverlays-1.18.14-mc1.16.5.jar : moreoverlays (1.18.14-mc1.16.5) - 1
• mods_folder ExtremeReactors2-1.16.4-2.0.23.jar : bigreactors (1.16.4-2.0.23) - 1
• mods_folder productivebees-1.16.5-0.6.9.16.jar : productivebees (1.16.5-0.6.9.16) - 1
• mods_folder DragonSurvival-1.16.5-0.0.34.jar : dragonsurvival (1.16.5-0.0.34) - 1
• mods_folder 时间wwta-1.16-2.0.jar : wwta (1.16-2.0) - 1
• mods_folder rhino-1605.1.1-build.23.jar : rhino (1605.1.1-build.23) - 1
• mods_folder kubejs-forge-1605.3.11-build.31.jar : kubejs (1605.3.11-build.31) - 1
• mods_folder Shrines-1.16.5-1.8.1.jar : shrines (1.16.5-1.8.1) - 1
• mods_folder abnormals_core-1.16.5-3.2.0.jar : abnormals_core (3.2.0) - 1
• mods_folder environmental-1.16.5-1.0.0.jar : environmental (1.0.0) - 1
• mods_folder upgrade_aquatic-1.16.5-3.1.0.jar : upgrade_aquatic (3.1.0) - 1
• mods_folder endergetic-1.16.4-3.0.0.jar : endergetic (3.0.0) - 1
• mods_folder neapolitan-1.16.5-2.1.0.jar : neapolitan (2.1.0) - 1
• mods_folder savageandravage-1.16.5-3.1.0.jar : savageandravage (3.1.0) - 1
• mods_folder autumnity-1.16.5-2.1.1.jar : autumnity (2.1.1) - 1
• mods_folder allurement-1.16.5-1.2.0.jar : allurement (1.2.0) - 1
• mods_folder buzzier_bees-1.16.5-3.0.1.jar : buzzier_bees (3.0.1) - 1
• mods_folder terraincognita-1.16.3-1.6.4.2.jar : terraincognita (1.16.3-1.6.4.2) - 1
• mods_folder ae2extras-1.3-1.16.5.jar : ae2extras (1.3-1.16.5) - 1
• mods_folder ensorcellation-1.16.4-1.2.0.jar : ensorcellation (1.2.0) - 1
• mods_folder goldenhopper-1.2.0-1.16.3.jar : goldenhopper (1.2.0) - 1
• mods_folder NeverNeededOrWanted-1.16.5-1.0.9a.jar : nnow (1.16.5-1.0.9a) - 1
• mods_folder journeymap-1.16.5-5.7.2beta18.jar : journeymap (5.7.2beta18) - 1
• mods_folder appliedenergistics2-8.4.0.jar : appliedenergistics2 (8.4.0) - 1
• mods_folder lazierae2-1.16.5-1.1.4.jar : lazierae2 (1.1.4) - 1
• mods_folder OuterEnd-0.2.13.jar : outer_end (0.2.9) - 1
• mods_folder decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder Coins-1.16.5-6.0.2.jar : coins (6.0.2) - 1
• mods_folder mcjtylib-1.16-5.0.19.jar : mcjtylib (1.16-5.0.19) - 1
• mods_folder rftoolsbase-1.16-2.0.10.jar : rftoolsbase (1.16-2.0.10) - 1
• mods_folder xnet-1.16-3.0.13.jar : xnet (1.16-3.0.13) - 1
• mods_folder rftoolsdim-1.16-7.0.9-beta.jar : rftoolsdim (1.16-7.0.9-beta) - 1
• mods_folder rftoolspower-1.16-3.0.8.jar : rftoolspower (1.16-3.0.8) - 1
• mods_folder rftoolsbuilder-1.16-3.0.17.jar : rftoolsbuilder (1.16-3.0.17) - 1
• mods_folder rftoolsstorage-1.16-2.0.12.jar : rftoolsstorage (1.16-2.0.12) - 1
• mods_folder rftoolscontrol-1.16-4.0.10.jar : rftoolscontrol (1.16-4.0.10) - 1
• mods_folder mapperbase-1.16.5-2.4.0.0.jar : mapperbase (1.16.5-2.4.0.0) - 1
• mods_folder embellishcraft-1.16.5-3.4.0.0.jar : embellishcraft (1.16.5-3.4.0.0) - 1
• mods_folder roadstuff-1.16.5-4.3.0.jar : roadstuff (1.16.5-4.3.0) - 1
• mods_folder mahoutsukai-1.16.5-v1.31.29.jar : mahoutsukai (1.16.5-v1.31.29) - 1
• mods_folder traverse-1.16.4-0.4.3.8.jar : traverse (1.16.4-0.4.3.8) - 1
• mods_folder EnderStorage-1.16.5-2.8.0.168-universal.jar : enderstorage (2.8.0.168) - 1
• mods_folder ultra_amplified_dimension-1.16.5-9.2.1-forge.jar : ultra_amplified_dimension (1.16.5-9.2.1-forge) - 1
• mods_folder TConstruct-1.16.5-3.0.4.197.jar : tconstruct (3.0.4.197) - 1
• mods_folder rftoolsutility-1.16-3.0.26.jar : rftoolsutility (1.16-3.0.26) - 1
• mods_folder openbackup-1.16.x-1.1.1.jar : openbackup (1.16.x-1.1.1) - 1
• mods_folder Inspirations-1.16.5-1.2.3.37.jar : inspirations (1.2.3.37) - 1
• mods_folder titanium-1.16.5-3.2.8.4-10.jar : titanium (3.2.8.4) - 1
• mods_folder mana-and-artifice-1.3.0.6.jar : mana-and-artifice (1.3.0.6) - 1
• mods_folder Abundance-1.16.5-1.0.5.jar : abundance (1.16.5-1.0.5) - 1
• mods_folder Jade-1.16.4-2.7.1.jar : jade (2.7.1) - 2
• mods_folder EnderRift-1.16.5-2.2.11.jar : enderrift (2.2.11) - 1
• mods_folder WAWLA-1.16.5-8.0.1.jar : wawla (8.0.1) - 1
• mods_folder AzureDoom-Chunk-Loader-1.16.4-1.0.0.jar : chunk (1.16.4-1.0.0) - 1
• mods_folder CreativeCore_v2.2.0_mc1.16.5.jar : creativecore (2.0.0) - 1
• mods_folder atmospheric-1.16.5-3.1.0.jar : atmospheric (3.1.0) - 1
• mods_folder chemlib-1.16.4-1.jar : chemlib (1.16.4-1) - 1
• mods_folder bpm-1.0.2.71.jar : bpm (1.0.2.71) - 1
• mods_folder StorageDrawers-1.16.3-8.2.2.jar : storagedrawers (8.2.2) - 1
• mods_folder FluxNetworks-1.16.5-6.1.7.12.jar : fluxnetworks (6.1.7.12) - 1
• mods_folder JustEnoughCharacters-1.16.4-4.2.0.jar : jecharacters (4.2.0) - 1
• mods_folder ScreenshotToClipboard-1.15.1-1.0.5.jar : screenshotclipboard (1.15.1-1.0.5) - 1
• mods_folder Assembly+Line-1.16.5-0.2.0-0.jar : assemblyline (1.16.5-0.2.0-0) - 1
• mods_folder ferritecore-2.0.5-forge.jar : ferritecore (2.0.5) - 1
• mods_folder engineersdecor-1.16.4-1.1.13.jar : engineersdecor (1.1.13) - 1
• mods_folder Chisel-MC1.16.5-2.0.0-alpha.3.jar : chisel (MC1.16.5-2.0.0-alpha.3) - 1
• mods_folder moredragoneggs-1.4.jar : moredragoneggs (1.4) - 1
• arclight arclight-forge-1.16.5-1.0.20-SNAPSHOT.jar : arclight (1.16.5-1.0.20-SNAPSHOT-47c1884) - 1
• mods_folder modular-routers-1.16.5-7.4.0-55.jar : modularrouters (task ':jar' property 'archiveVersion') - 1
• mods_folder enhancedcelestials-1.0.4-1.16.4.jar : enhancedcelestials (1.0.4-1.16.4) - 1
• mods_folder botanicalmachinery-1.16.4-0.4.1.jar : botanicalmachinery (0.4.1) - 1
• mods_folder OpenLoader-1.16.5-9.0.3.jar : openloader (9.0.3) - 1

### 错误描述
客户端连接服务器会导致服务器崩溃（第一次不会崩会显示
![屏幕截图 2021-07-18 100823](https://user-images.githubusercontent.com/69307837/126053703-d90a83d3-817d-40a5-8c95-5fba1f7f5996.png) 或
![屏幕截图 2021-07-18 101742](https://user-images.githubusercontent.com/69307837/126053706-1b1a7526-f746-44d3-93e0-5b7e6fd05f3d.png)

第2次尝试加入才会崩）
重置地图后第一次有概率进去然后就被踢出并显示这个
![屏幕截图 2021-07-18 101742](https://user-images.githubusercontent.com/69307837/126053724-1caa1caf-d6fb-4e47-a5c2-d920c1790ea4.png)

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤
重启服务器以后
删除地图用客户端加入服务器第一次后台一堆报错第二次直接崩服
已多次尝试

 
https://wh5vh-my.sharepoint.com/:u:/g/personal/mwhxz_ip_ci/EYuRlVHBLIBHjwPYnIe4JOcBxjrNRwEfvrPLa_te_fpblA?e=1eIExk
服务端和客户端文件

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]
[crash-reports20.zip](https://github.com/IzzelAliz/Arclight/files/6835561/crash-reports20.zip)
这个是最新版本的
[crash-reports19_2.zip](https://github.com/IzzelAliz/Arclight/files/6835562/crash-reports19_2.zip)
这个github上最新发布版本的

**Comment by IzzelAliz** [comment]
请二分找出哪个 mod 导致此问题

**Comment by 2651084156** [comment]
> 
> 
> 请二分找出哪个 mod 导致此问题

分到最后没有找到触发崩溃的mod发现个新的问题


https://user-images.githubusercontent.com/69307837/126062224-63d4d31d-b172-42ac-a414-94475e2d424e.mp4

如视频
这是新log
[logsn.zip](https://github.com/IzzelAliz/Arclight/files/6835943/logsn.zip)


mod：

• minecraft forge-1.16.5-36.1.24-server.jar : minecraft (1.16.5) - 1
• mods_folder 热带世界Tropicraft-9.0.0-beta+54.jar : tropicraft (9.0.0-beta+54) - 1
• mods_folder titanium-1.16.5-3.2.8.4-10.jar : titanium (3.2.8.4) - 1
• mods_folder 生物群系BiomesOPlenty-1.16.5-13.1.0.480-universal.jar : biomesoplenty (1.16.5-13.1.0.480) - 1
• mods_folder Wyrmroost-1.16.3-1.2.11.jar : wyrmroost (1.16.3-1.2.11) - 1
• mods_folder woot-1.16.5-1.0.8.0.jar : woot (1.16.5-1.0.8.0) - 1
• mods_folder valkyrielib-1.16.5-3.0.9.0.jar : valkyrielib (1.16.5-3.0.9.0) - 1
• mods_folder ModularVoiceChat-BETA-MC1.16.5-1.0.jar : modularvc (BETA-MC1.16.5-1.0) - 1
• mods_folder 分析spark-forge.jar : spark (1.6.0) - 1
• mods_folder TrackAPI-1.16.4-forge-1.2.1.jar : trackapi (1.2) - 1
• mods_folder 好东西PiTweaks-1.16.5-1.3.2.jar : pitweaks (1.16.5-1.3.2) - 1
• mods_folder time-in-a-bottle-1.1.0.jar : tiab (1.1.0) - 1
• mods_folder Nuclear+Science-1.16.5-0.3.0-0.jar : nuclearscience (1.16.5-0.3.0-0) - 1
• mods_folder YungsApi-1.16.4-Forge-6.jar : yungsapi (1.16.4-Forge-6) - 1
• mods_folder 自动建造mightyarchitect-mc1.16.3_v0.5.jar : mightyarchitect (0.5) - 1
• mods_folder WorldEdit-CUI-FE3-1.16.5-3.0.9.jar : worldeditcuife3 (3.0.9) - 1
• mods_folder worldedit-mod-7.2.5-dist.jar : worldedit (7.2.5+57d5ac9) - 1
• mods_folder WorldHandler-1.16.5-2.12.5.jar : worldhandler (1.16.5-2.12.5) - 1
• mods_folder 关照starlight-forge-1.0.0-RC2-1.16.5.jar : starlight (1.0.0-RC2) - 1
• mods_folder 个人修改Electrodynamics.jar : electrodynamics (1.16.5-0.4.0-1) - 1
• arclight arclight-forge-1.16.5-1.0.20-SNAPSHOT.jar : arclight (1.16.5-1.0.20-SNAPSHOT-47c1884) - 1
• mods_folder modular-routers-1.16.5-7.4.0-55.jar : modularrouters (task ':jar' property 'archiveVersion') - 1
• mods_folder traverse-1.16.4-0.4.3.8.jar : traverse (1.16.4-0.4.3.8) - 1
• maven_libs forge-1.16.5-36.1.24-universal.jar : forge (36.1.24) - 1
• mods_folder ultra_amplified_dimension-1.16.5-9.2.1-forge.jar : ultra_amplified_dimension (1.16.5-9.2.1-forge) - 1
• mods_folder twilightforest-1.16.5-4.0.490-universal.jar : twilightforest (NONE) - 1
• mods_folder mob_grinding_utils-1.16.5-0.4.23.jar : mob_grinding_utils (1.16.5-0.4.23) - 1
• mods_folder 时间wwta-1.16-2.0.jar : wwta (1.16-2.0) - 1
• mods_folder 地牢改配置dungeonsarise1.16.5-1.2.68a-HF.jar : dungeons_arise (1.2.68a) - 1
• mods_folder UniversalModCore-1.16.4-forge-1.0.1.jar : universalmodcore (1.0.1) - 1
• mods_folder ZeroCore2-1.16.4-2.0.21.jar : zerocore (1.16.4-2.0.21) - 1

**Comment by IzzelAliz** [comment]
这是一个问题，请二分

**Comment by 2651084156** [comment]
> 
> 
> 这是一个问题，请二分

PiTweaks-1.16.5-1.3.2.jar

这个mod吃东西导致的上面的问题
[debug.log](https://github.com/IzzelAliz/Arclight/files/6836044/debug.log)

**Comment by 2651084156** [comment]
![图片](https://user-images.githubusercontent.com/69307837/126065010-e29127d9-fdd3-4535-96a3-1c40fbc62060.png)

崩溃没有出现了但是退出重进还是会有这个问题

> 
> 
> 这是一个问题，请二分
