### ISSUE TITLE
服务器选择界面报错

### ISSUE THREAD

**Issue by Rcrafte22** [IzzelAliz/Arclight#328]
### 我正在运行

* **Arclight** [arclight-forge-1.16.5-1.0.20-SNAPSHOT.jar] 

* **你确认这是最新版吗** [是，我刚刚下载的]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [java version "16.0.1"] 

* **操作系统** [Windows11]

* **插件列表** 
未安装插件
* **Mod 列表** 
Dynamic Lights
I18nUpdateMod
### 错误描述
当客户端安装这两个mod的其中一个，在多人游戏界面就会出现以下错误，但仍能正常进入服务器
![error](https://user-images.githubusercontent.com/39120466/126432930-952c4f31-4ec1-4863-a6c5-efc3becdeed2.png)

### 重现步骤

1. 安装 Dynamic Lights和I18nUpdateMod其中的任意一个即可复现

https://1drv.ms/u/s!AhvCxyczvfSik31W6-Nw9DMq2PT8?e=cTmwFz 

**可在 Forge 复现** [是]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

无错误日志

**Comment by 3269199948** [comment]
这是单机MOD导致的吧？

**Comment by Rcrafte22** [comment]
> 这是单机MOD导致的吧？

嗯，但是使用别的单机mod比如小地图时就不会显示兼容问题

**Comment by IzzelAliz** [comment]
又不是不能进
