### ISSUE TITLE
1.15-放逐之路-CrafttoExile-Dissonance-2.11.0c频繁出现全服玩家掉线

### ISSUE THREAD

**Issue by kvroha** [IzzelAliz/Arclight#332]
### 我正在运行

* **Arclight** [arclight-1.15.2-1.0.19-6d639e7] 

* **你确认这是最新版吗** [是，因为构建网站下载]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [build 1.8.0_271-b09] 

* **操作系统** [Windows server 2019 Datacenter]

  

* **插件列表** 
* Plugins (2):
*  LagAssist
* LaggRemover
* **Mod 列表** 
 Mod List: 
• mods_folder Tropicraft-8.1.0-beta+34.jar : tropicraft (8.1.0-beta+34) - 1
• mods_folder supermartijn642configlib-1.0.7-mc1.15.jar : supermartijn642configlib (1.0.7) - 1
• mods_folder NetherPortalFix_1.15.2-6.0.2.jar : netherportalfix (6.0.2) - 1
• mods_folder areas_1.15.2-2.2.jar : areas (2.2) - 1
• mods_folder simplemagnets-1.1.2-mc1.15.jar : simplemagnets (1.1.2) - 1
• mods_folder PGA-1.15.2-1.1.1.1.jar : publicguiannouncement (1.1.1.1) - 1
• mods_folder incontrol-1.15-4.0.8.jar : incontrol (1.15-4.0.8) - 1
• mods_folder pitg-1.15.2-1.4.1.jar : pitg (1.15.2-1.4.1) - 1
• mods_folder BetterCaves-1.15.2-1.0.jar : bettercaves (1.15.2-1.0) - 1
• mods_folder InitialInventory-5.0.1.5.jar : initialinventory (5.0.1.5) - 1
• mods_folder XaerosWorldMap_1.14.5_Forge_1.15.2.jar : xaeroworldmap (1.14.5) - 1
• mods_folder CookingForBlockheads_1.15.2-8.0.3.jar : cookingforblockheads (8.0.3) - 1
• mods_folder structurescompass-1.15.2-1.1.0.jar : structurescompass (1.15.2-1.1.0) - 1
• mods_folder Placebo-1.15.2-3.1.1.jar : placebo (3.1.1) - 1
• mods_folder dankstorage-2.6.jar : dankstorage (2.6) - 1
• mods_folder ftb-gui-library-1.0.0.14.jar : ftbguilibrary (1.0.0.14) - 1
• mods_folder WitherSkeletonTweaks-1.15.2-4.0.2.jar : wstweaks (4.0.2) - 1
• mods_folder Bookshelf-1.15.2-5.6.40.jar : bookshelf (5.6.40) - 1
• mods_folder u_team_core-1.15.2-3.0.2.169.jar : uteamcore (3.0.2.169) - 1
• mods_folder randompatches-1.15.2-1.22.1.1.jar : randompatches (1.15.2-1.22.1.1) - 1
• mods_folder Apotheosis-1.15.2-3.3.8.jar : apotheosis (3.3.8) - 1
• mods_folder Morpheus-1.15.2-4.2.50.jar : morpheus (version) - 1
• mods_folder Hwyla-forge-1.10.8-B72_1.15.2.jar : waila (version) - 1
• mods_folder ctecu-1.0.7.jar : ctecu (1.15.2-1.0.7) - 1
• mods_folder dynviewdist-1.5.jar : dynview (1.5) - 1
• mods_folder JustEnoughResources-1.15.2-0.10.1.77.jar : jeresources (0.10.1.77) - 1
• mods_folder mysticallib-1.15.2-2.0.1.jar : mysticallib (1.15.2-2.0.1) - 1
• mods_folder w2w-1.15.2-0.0.4.0.jar : w2w (NONE) - 1
• mods_folder structure-gel-api-1.15.2-1.1.0.jar : structure_gel (1.1.0) - 1
• mods_folder mcw-bridges-1.0.5-mc1.15.2.jar : mcwbridges (1.0.5) - 1
• mods_folder dwmh-1.15.2-4.0.0.jar : dwmh (NONE) - 1
• mods_folder bettermobgriefinggamerule-1.15.2-8.0.1.jar : bettermobgriefinggamerule (1.15.2-8.0.1) - 1
• mods_folder useful_backpacks-1.15.2-1.10.3.77.jar : usefulbackpacks (1.10.3.77) - 1
• mods_folder repurposedstructures-1.15.2-1.7.2.jar : repurposed_structures (1.15.2-1.7.2) - 1
• mods_folder betterspawnercontrol_1.15.2-1.3.jar : betterspawnercontrol (1.3) - 1
• mods_folder Ping-1.15.2-1.6.4.jar : ping (1.15.2-1.6.4) - 1
• mods_folder ToolStats-1.15.2-1.0.2.jar : toolstats (1.0.2) - 1
• mods_folder phosphor-forge-mc1.15.2-0.5.2+build.4.jar : phosphor (0.5.2+build.4) - 1
• mods_folder valhelsia_structures-15.0.3a.jar : valhelsia_structures (15.0.3a) - 1
• mods_folder dungeons-plus-1.15.2-1.0.2.jar : dungeons_plus (1.0.2) - 1
• mods_folder mining_dimension-1.15.2-1.0.6.jar : mining_dimension (1.15.2-1.0.6) - 1
• mods_folder AzureRPGItems 1.15.2-1.3.3.jar : azurerpgitems (1.1.0) - 1
• mods_folder supermartijn642corelib-1.0.5-mc1.15.jar : supermartijn642corelib (1.0.5) - 1
• mods_folder thutperms-1.15.2-3.0.6.jar : thutperms (3.0.6) - 1
• mods_folder simplefarming-1.15.2-1.3.4.jar : simplefarming (1.15.1-1.3.4) - 1
• mods_folder corpsecomplex-FORGE-1.15.2-2.0-beta12.jar : corpsecomplex (FORGE-1.15.2-2.0-beta12) - 1
• mods_folder lycanitesmobs-1.15.2-2.2.3.2.jar : lycanitesmobs (1.15.2-2.2.3.2) - 1
• mods_folder TelePass-1.15.2-1.1.1.jar : telepass (1.1.1) - 1
• mods_folder gaiadimension-1.15.2-1.2.3.jar : gaiadimension (1.2.3) - 1
• mods_folder curios-FORGE-1.15.2-2.0.2.7.jar : curios (FORGE-1.15.2-2.0.2.7) - 1
• mods_folder Patchouli-1.15.2-1.2-35.jar : patchouli (1.15.2-1.2-35) - 1
• mods_folder leap-1.15.2-1.0.1.jar : leap (1.0.1) - 1
• mods_folder collective-1.15.2-2.26.jar : collective (2.26) - 1
• mods_folder SpawnInVillage-1.15.2-1.2.jar : spawnvillage (1.2) - 1
• mods_folder EndReborn+[0.6.2].jar : endreborn (0.6.2) - 1
• mods_folder libnonymous-1.15.2-1.1.1.5.jar : libnonymous (1.1.1.5) - 1
• mods_folder RiddleChests-1.1.0.1.jar : riddlechests (1.1.0.1) - 1
• mods_folder worldedit-forge-mc1.15.2-7.1.0.jar : worldedit (7.1.0;48cc31c) - 1
• mods_folder furniture-7.0.0-pre16-1.15.1.jar : cfm (7.0.0-pre16) - 1
• mods_folder curiouselytra-FORGE-1.15.2-2.0.jar : curiouselytra (FORGE-1.15.2-2.0) - 1
• mods_folder mcw-furniture-2.0.1-mc1.15.2.jar : mcwfurnitures (2.0.1) - 1
• mods_folder globalxp-1.15.2-v1.4.15.jar : globalxp (v1.4.15) - 1
• mods_folder productivebees-1.15.2-0.6.9.3.jar : productivebees (1.15.2-0.6.9.3) - 1
• mods_folder the_bumblezone-1.15.2-1.3.10.jar : the_bumblezone (1.15.2-1.3.10) - 1
• mods_folder speedyladders-1.15.2-1.jar : speedyladders (1.15.2-1) - 1
• mods_folder FastLeafDecay-v22.1.jar : fastleafdecay (v22.1) - 1
• mods_folder BetterMineshaftsForge-1.15.2-1.3.2.jar : bettermineshafts (1.15.2-1.3.2) - 1
• mods_folder geckolib-forge-1.15.2-3.0.33.jar : geckolib3 (3.0.33) - 1
• mods_folder Kiwi-1.15.2-2.8.5.jar : kiwi (2.8.5) - 1
• mods_folder TrashSlot_1.15.2-11.0.0.jar : trashslot (11.0.0) - 1
• mods_folder mining-helmet-1.15.2-1.0.9.jar : mining_helmet (1.0.9) - 1
• mods_folder CalemiUtils-1.15.2-1.1.5-MC1.15.2.jar : calemiutils (1.15.2-1.1.5) - 1
• mods_folder item-filters-2.2.0.15.jar : itemfilters (2.2.0.15) - 1
• mods_folder Mine+and+Slash-1.15.2-3.11.5.jar : mmorpg (3.11.5) - 1
• mods_folder Abnormals-Core-1.15.2-1.0.6.jar : abnormals_core (1.0.6) - 1
• mods_folder Buzzier-Bees-1.15.2-1.5.2.jar : buzzierbees (1.5.2) - 1
• mods_folder caelus-FORGE-1.15.2-2.0-beta4.jar : caelus (FORGE-1.15.2-2.0-beta4) - 1
• mods_folder Upgrade-Aquatic-1.15.2-1.7.1.jar : upgrade_aquatic (1.7.1) - 1
• mods_folder create-mc1.15.2_v0.3.1a.jar : create (mc1.15.2_v0.3.1a+478) - 1
• mods_folder Waystones_1.15.2-6.0.2.jar : waystones (6.0.2) - 1
• mods_folder copypaste-1.5.jar : copypaste (1.5) - 1
• mods_folder Clumps-5.0.2.8.jar : clumps (5.0.2.8) - 1
• mods_folder NastyMobs-1.15.1-1.0.0.8.jar : nasty (1.0.0.8) - 1
• mods_folder NaturesCompass-1.15.2-1.8.5.jar : naturescompass (1.15.2-1.8.5) - 1
• mods_folder good-nights-sleep-1.15.2-1.0.3.jar : goodnightsleep (1.0.3) - 1
• mods_folder DungeonCrawl-1.15.2-2.2.4.jar : dungeoncrawl (2.2.4) - 1
• mods_folder betteranimalsplus-1.15.2-10.2.0.jar : betteranimalsplus (10.2.0) - 1
• mods_folder FarmingForBlockheads_1.15.2-6.1.5.jar : farmingforblockheads (6.1.5) - 1
• mods_folder cte_uniques-0.11.jar : cte_uniques (1.0.0) - 1
• mods_folder outvoted-1.15.2-1.2.1-rc1.jar : outvoted (1.2.1-rc1) - 1
• mods_folder mapperbase-1.15.2-1.1.1.0.jar : mapperbase (1.15.2-1.1.1.0) - 1
• mods_folder embellishcraft-1.15.2-2.2.1.0.jar : embellishcraft (1.15.2-2.2.1.0) - 1
• mods_folder JEITweaker-1.15.2-1.0.1.3.jar : jeitweaker (1.0.1.3) - 1
• mods_folder traverse-1.15.2-3.2.0.jar : traverse (1.15.2-3.2.0) - 1
• mods_folder CraftTweaker-1.15.2-6.0.0.45.jar : crafttweaker (6.0.0.45) - 1
• mods_folder Swamp-Expansion-1.15.2-1.7.3.jar : swampexpansion (NONE) - 1
• maven_libs forge-1.15.2-31.2.48-universal.jar : forge (31.2.48) - 1
• mods_folder Atum-1.15.2-2.1.12.jar : atum (1.15.2-2.1.12) - 1
• mods_folder Bountiful-1.15.2-3.1.2.jar : bountiful (1.15.2-3.1.2) - 1
• mods_folder ironchest-1.15.2-10.0.3.jar : ironchest (1.15.2-10.0.1) - 1
• mods_folder dungeonsarise1.15.2-1.2.72b.jar : dungeons_arise (1.2.72b) - 1
• mods_folder RottenCreatures-1.15.2-0.9.7.jar : rotten_creatures (0.9.7) - 1
• minecraft forge-1.15.2-31.2.48-server.jar : minecraft (1.15.2) - 1
• mods_folder The-Endergetic-Expansion-1.15.2-v1.3.2.jar : endergetic (1.3.2) - 1
• mods_folder logprot-1.15.1-1.2.jar : logprot (1.2) - 1
• mods_folder DrawersTooltip-1.15.2-1.1.0.jar : draweringredient (1.1.0) - 1
• mods_folder swingthroughgrass-1.15.2-1.4.1.jar : swingthroughgrass (1.15.2-1.4.1) - 1
• mods_folder pandoras_creatures-1.15.2-1.0.1.jar : pandoras_creatures (1.15.2-1.0.1) - 1
• mods_folder ToolBelt-1.15.2-1.14.2.jar : toolbelt (1.14.2) - 1
• mods_folder Ma-Chat-1.15.2-3.1.0.jar : ma-chat (1.15.2-3.1.0) - 1
• mods_folder ImmersiveEngineering-1.15.2-4.1.1-125.jar : immersiveengineering (1.15.2-4.1.1-125) - 1
• mods_folder overworld_mirror-1.15.2-1.4.1.16.jar : overworldmirror (1.4.1.16) - 1
• mods_folder quiver-1.2-1.15.2.jar : quiver (1.2-1.15.2) - 1
• mods_folder towers_of_the_wild-1.15.2-1.2.0.jar : towers_of_the_wild (1.15.2-1.2.0) - 1
• mods_folder Atmospheric-1.15.2-1.4.1.jar : atmospheric (1.4.1) - 1
• mods_folder dimdungeons-1.072-forge-1.15.2.jar : dimdungeons (1.15.2-1.072) - 1
• mods_folder Xaeros_Minimap_21.12.5_Forge_1.15.2.jar : xaerominimap (21.12.5) - 1
• mods_folder pamhc2foodcore-1.15.2-1.1.0.jar : pamhc2foodcore (version) - 1
• mods_folder ftb-backups-2.1.0.2.jar : ftbbackups (2.1.0.2) - 1
• mods_folder FastWorkbench-1.15.2-3.1.1.jar : fastbench (3.1.1) - 1
• mods_folder autumnity-1.3.3-1.15.2.jar : autumnity (1.3.3) - 1
• mods_folder polymorph-FORGE-1.15.2-0.10.jar : polymorph (FORGE-1.15.2-0.10) - 1
• mods_folder AutoRegLib-1.5-40.jar : autoreglib (1.5-40) - 1
• mods_folder Quark-r2.1-245.jar : quark (r2.1-245) - 1
• mods_folder StorageDrawers-1.15.2-7.0.3.jar : storagedrawers (1.15.2-7.0.3) - 1
• mods_folder midnight-0.5.11.jar : midnight (0.5.11) - 1
• mods_folder TerraForged-1.15.2-0.1.3.jar : terraforged (0.1.3) - 1
• mods_folder jei-1.15.2-6.0.3.16.jar : jei (6.0.3.16) - 1
• mods_folder ftb-quests-1502.0.2.252.jar : ftbquests (1502.0.2.252) - 1
• mods_folder structurize-0.13.109-ALPHA-universal.jar : structurize (0.13.109-ALPHA) - 1
• mods_folder vinecollector-1.15.2-1.0.0.jar : vinecollector (1.15.2-1.0.0) - 1
• mods_folder minecolonies-0.13.645-RELEASE-universal.jar : minecolonies (0.13.645-RELEASE) - 1
• mods_folder FastFurnace-1.15.1-3.0.0.jar : fastfurnace (3.0.0) - 1
• mods_folder AppleSkin-mc1.15.2-forge-1.0.14.jar : appleskin (1.0.14) - 1
• mods_folder solcarrot-1.15.2-1.9.7.jar : solcarrot (1.15.2-1.9.7) - 1
• arclight arclight-forge-1.15-1.0.19.jar : arclight (1.15.2-1.0.19-6d639e7) - 1
• mods_folder Aquaculture-1.15.2-2.0.23.jar : aquaculture (1.15.2-2.0.23) - 1
• mods_folder CosmeticArmorReworked-1.15.2-v3a.jar : cosmeticarmorreworked (1.15.2-v3a) - 1
• mods_folder step-1.15.2-1.0.3.jar : step (1.0.3) - 1
• mods_folder AnimalWeaponsAndArmor-1.15.2-1.0.1.jar : awaa (1.0.1) - 1
• mods_folder OpenLoader-1.15.2-4.0.5.jar : openloader (4.0.5) - 1
• mods_folder EnderMail-1.15.2-1.1.3.jar : endermail (1.15.2-1.1.3) - 1
• mods_folder ExtendedNetherBackport-1.15.2-Beta-4.3.2.jar : extendednether (4.3.2) - 1
• mods_folder createaddition-1.15.2-20210226a.jar : createaddition (1.15.2-20210226a) - 1

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息
服务端运行过程中，频繁出现全服玩家掉线事件。
在纯forge端中未出现此故障。
已尝试删除背包整理模组，故障依然存在。

### 重现步骤

1. 安装Arclight 1.15服务端。

2.解压Craft to Exile服务端，（除config/fml.toml以外，同名文件全跳过），并删除performant模组。

3. 运行中频繁发生抽风踢人，全玩家掉线

 
服务端压缩包: https://www.curseforge.com/minecraft/modpacks/crafttoexiledissonance/download/3385644

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[完整版log: https://paste.ubuntu.com/p/Gr7989Qbbd/
掉线前后节选: https://paste.ubuntu.com/p/MBZypdf5rY/]

**Comment by Taskeren** [comment]
看起来像这个问题
TelepathicGrunt/Bumblezone#23

**Comment by IzzelAliz** [comment]
1.15 已经不再支持
