### ISSUE TITLE
1.16.5植物魔法采花袋吞物品

### ISSUE THREAD

**Issue by xiaodoubiOvO** [IzzelAliz/Arclight#333]
### 我正在运行

* **Arclight** [arclight-1.16.5-1.0.20-368b0cb] 

* **你确认这是最新版吗** [是，因为构建网站下载]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [16.0.2] 

* **操作系统** [windows server 2016 standard+1607]

  

* **插件列表** 
Plugins (6): Vault, GroupManager, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsChat
* **Mod 列表** 
Mod List:
• minecraft forge-1.16.5-36.1.62-server.jar : minecraft (1.16.5) - 1
• mods_folder [枪械-附属包]additional-guns-0.1.0-1.16.4.jar : additionalguns (0.1.0) - 1
• mods_folder [硬核复活]HardcoreRevival_1.16.5-5.2.1.jar : hardcorerevival (5.2.1) - 1
• mods_folder [枪械-前置]obfuscate-0.6.2-1.16.3.jar : obfuscate (0.6.2) - 1
• mods_folder [星辉魔法]astralsorcery-1.16-1.16.5-1.13.12.jar : astralsorcery (1.16.5-1.13.12) - 1
• mods_folder [墓碑]tombstone-1.16-6.4.7.jar : tombstone (6.4.7) - 1
• mods_folder [枪械]cgm-1.0.1-1.16.3.jar : cgm (1.0.1) - 1
• mods_folder [星辉魔法-前置]observerlib-1.16.5-1.5.3.jar : observerlib (1.16.5-1.5.3) - 1
• arclight arclight-forge-1.16.5-1.0.20-SNAPSHOT.jar : arclight (1.16.5-1.0.20-SNAPSHOT-d43280c) - 1
• mods_folder [植物魔法]Botania-1.16.5-419.jar : botania (1.16.5-419) - 1
• mods_folder [枪械-附属包]timeless_and_classic_4.0.0_RELEASE.jar : timeless_and_classic (0.3) - 1
• mods_folder [通用机械]Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
• maven_libs forge-1.16.5-36.1.62-universal.jar : forge (36.1.62) - 1
• mods_folder [机械动力-前置]flywheel-1.16-0.1.1.jar : flywheel (1.16-0.1.1) - 1
• mods_folder [星辉魔法-前置]curios-forge-1.16.5-4.0.5.2.jar : curios (1.16.5-4.0.5.2) - 1
• mods_folder [植物魔法-前置]帕秋莉手册Patchouli-1.16.4-53.1.jar : patchouli (1.16.4-53.1) - 1
• mods_folder [机械动力]create-mc1.16.5_v0.3.2b.jar : create (v0.3.2b for 1.16.5) - 1
• mods_folder [史诗格斗]EpicFightMod-1.16.5-4.1.6.jar : epicfight (4.1.6) - 1
• mods_folder [AE2]appliedenergistics2-8.4.0.jar : appliedenergistics2 (8.4.0) - 1

### 错误描述

神秘花放进采花袋，关闭采花袋gui再打开，放进去的花都消失不见了。测试过只装植物魔法问题还是存在，在Forge端和单人里没这个问题

### 重现步骤

1. 安装 植物魔法
2. 进入服务器后 拿出采花袋和一些神秘花（不要高神秘花）
3. 手持采花袋右键打开gui，把神秘花放进去
4. 关闭gui再打开
5. 放进去的花都不见了

 
https://1drv.ms/u/s!AjnVhXITdFcskjYP4eSXrEwY6cdL?e=Tnpekn

**可在 Forge 复现** [是/否]
Forge端和单人无问题

**可在 Spigot 复现** [是/否]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/fswtrH7bhC/

**Comment by Murisa-dev** [comment]
值得一提的是，这个问题对于植物魔法的饰品盒子也存在，这边的处理方式就是ban掉物品（

**Comment by ahdg6** [comment]
AM3 储存法术的书也可复现，应该不是mod的问题

**Comment by IzzelAliz** [comment]
Please test this in latest dev build to see if this is fixed.

**Comment by xiaodoubiOvO** [comment]
您好，测试了最新版 问题还是存在

运行版本 arclight-1.16.5-1.0.22-SNAPSHOT-7c63a9e
构建日期 2021-12-14 08:29:47

最新mod：https://1drv.ms/u/s!AjnVhXITdFcslFE6kkCAH7c0k0xT?e=SEXvL2
