### ISSUE TITLE
Create mod v0.3.2b Crash server

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#337]
### I am running

* **Arclight** [1.16/1.0.20: Release 1.0.20] 

* **This is the latest development version** [N]

* **Java** [11] 

* **Operating System** [unbuntu 20]

  

* **Plugins:** **Nope**

* **Mods:** **Create mod**

### Step to reproduce

1. Install mod v0.3.2b: https://www.curseforge.com/minecraft/mc-mods/create and https://www.curseforge.com/minecraft/mc-mods/flywheel
2. Start server

 

**Reproducible in Forge** [Y]

**Reproducible in Spigot** [N]

### Logs

[ERROR LOG]
https://paste.ubuntu.com/p/kGXBGwC3CH/

**Comment by XionioXMaster** [comment]
if you install mod 1 in the queue you can fix this problem, if you use it in an existing build it can cause problems, i noticed it in other mods as well. I think you can close this thread

**Comment by XionioXMaster** [comment]
Delete mod **random patch** **fix** this problem
![image](https://user-images.githubusercontent.com/86433158/127558314-201bd7b9-3091-4b37-a7fb-84855b62a6f9.png)

**Comment by ahdg6** [comment]
another way to crash server: Throw minecraft:books into Create:schematicannon
https://paste.ubuntu.com/p/FqGZ7TdXsQ/
