### ISSUE TITLE
[1.16.5] Mekanism（通用机械）工厂类机器（多输出slot）双击输出slot时无法正确聚集所有输出物，并在后台报错

### ISSUE THREAD

**Issue by CitrusSin** [IzzelAliz/Arclight#342]
### 我正在运行

* **Arclight** arclight-1.16.5-1.0.21-SNAPSHOT-4b3b01c 

* **你确认这是最新版吗** [是/否，因为___]
是，从https://ci.appveyor.com/project/IzzelAliz/arclight-16 下载的，下载时还是1小时前构建的

* **你确认所有Mod都安装了依赖** [是/否]
是

* **你确认所有插件都已更新至对应版本** [是/否]
是（实际上并无安装插件）

* **Java** [版本] 
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

* **操作系统** [名称+版本]
Microsoft Windows 10 专业版
版本号                    20H2
操作系统内部版本 19042.1110

  

* **插件列表** 
无插件

* **Mod 列表** 
[22:52:12] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List:
• minecraft forge-1.16.5-36.2.0-server.jar : minecraft (1.16.5) - 1
• mods_folder Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
• maven_libs forge-1.16.5-36.2.0-universal.jar : forge (36.2.0) - 1
• arclight arclight-forge-1.16.5-1.0.20.jar : arclight (1.16.5-1.0.20-368b0cb) - 1

### 错误描述

mod中多输出槽的机器，当所有输出槽均为同类物品时，使用鼠标左键双击会抛出异常，且合并物品的功能无法正常执行

### 重现步骤

1. 启动服务端arclight-1.16.5-1.0.20-368b0cb，安装mod：[Mekanism-1.16.5-10.0.21.448.jar](https://micrafast.lanzoui.com/iIbMrrywzve)（仅此一个）

2. 在服务器内放置一终极熔炼工厂，在其邻位放置一创造能量立方，右击终极熔炼工厂，点一下左侧“S”按钮打开自动分类

3. 在上方红色输入槽中放入一组或更多圆石

4. 等待所有的圆石都被烧炼成为石头（所有的输出槽都有石头了也可以继续），双击其中一输出槽并放入背包，可观察到物品数量异常

5. 此时看到服务器控制台，可发现报错（IndexOutOfBoundsException）

 
https://micrafast.lanzoui.com/iIbMrrywzve （onedrive上不去，蓝奏云凑合凑合）

**可在 Forge 复现** [是/否]
否，使用仅安装Forge 36.2.2，唯一mod Mekanism-1.16.5-10.0.21.448 的客户端于单人游戏无法复现，使用mohist（另外一个hybrid server）也无法复现

**可在 Spigot 复现** [是/否]
否（与spigot无关）

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/rwVktP4W7f/

**Comment by CitrusSin** [comment]
麻了 等好久了 这波先用构建的最新版试了 还是能复现 便更新一下issue
没法双击拿所有东西真的好难受的！！

**Comment by Mr-Ao-Dragon** [comment]
> 麻了 等好久了 这波先用构建的最新版试了 还是能复现 便更新一下issue
> 没法双击拿所有东西真的好难受的！！

试试鼠标手势吧，暂时规避下

**Comment by IzzelAliz** [comment]
Please test this in latest dev build to see if this is fixed.

**Comment by IzzelAliz** [comment]
This is still relevant.
