### ISSUE TITLE
[1.16.5] Flan mod crash server

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#345]
### I am running

* **Arclight** [1.16/1.0.20: Release 1.0.20] 

* **This is the latest development version** [N]

* **Java** [11] 

* **Operating System** [unbuntu 20]

  

* **Plugins:** **Lagassist**

* **Mods:** **Flan mod**

### Step to reproduce

1. Install mod: https://www.curseforge.com/minecraft/mc-mods/flan-forge/files/3395505
2. Start server, done.

 

**Reproducible in Forge** [Y]

**Reproducible in Spigot** [N]

### Logs

[ERROR LOG]
https://paste.ubuntu.com/p/KMyDs7MT5D/ - Crash Console
https://paste.ubuntu.com/p/zvWznfJRnx/  - Crash-report

**Comment by IzzelAliz** [comment]
Report to flan dev.
