### ISSUE TITLE
Incompatible with Variant16x

### ISSUE THREAD

**Issue by Xplodin** [IzzelAliz/Arclight#347]
### I am running

* **Arclight** [1.16.5-1.0.21-SNAPSHOT-4b3b01c] 

* **This is the latest development version** [Y]

* **Java** [1.8] 

* **Operating System** [Windows 10]

  

* **Plugins** 
NONE
* **Mods** 
TNP Limitless 3, 300+ mods. 1.7.10 version of modpack (NOT MC 1.7.10) 

### Step to reproduce
Boot server with performant and NotEnoughCrashes removed (crashes with these two)
1. Install TNP Limitless 3
2. Boot with arclight on either forge version (supplied and arclights forge)
3. crash mixin

 
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3

**Reproducible in Forge** [Y/N]
N

**Reproducible in Spigot** [Y/N]
N
### Logs
https://gist.github.com/Xplodin/5edbcd2f7e53ac108867fe70efda853a
[ERROR LOG]

**Comment by IzzelAliz** [comment]
There isn't anything meaningful in your logs. Please provide valid log file.

**Comment by Xplodin** [comment]
[latest.log](https://github.com/IzzelAliz/Arclight/files/6971621/latest.log)
[debug.log](https://github.com/IzzelAliz/Arclight/files/6971623/debug.log)


here are two recent logs I took on the latest snapshot while running 1.10.8 of the modpack

**Comment by Xplodin** [comment]
Tested the newest update with java 16
https://gist.github.com/Xplodin/326febc332cef35a39fe51ba5d99c326

Incompatibility with variant16x something with mixins

**Comment by IzzelAliz** [comment]
The mod uses Overwrite mixins thus cannot fix on our side. Contact their dev if possible.
