### ISSUE TITLE
CreativeManager can not be loaded on Arclight

### ISSUE THREAD

**Issue by ahdg6** [IzzelAliz/Arclight#349]
### I am running

* **Arclight** [1.16.5-1.0.21-SNAPSHOT] 

* **This is the latest development version** [Y]

* **Java** [adopt-hotspot_11] 

* **Operating System** [CentOS]

  

* **Plugins** 
CreativeManager
* **Mods** 

### Description

Install CreativeManager on Arclight but do not work.
It's a open-source plugin:https://github.com/K0bus/CreativeManager

### Step to reproduce

1. Install CreativeManager
2. Run Server
3. CreativeManager can not be loaded

**Reproducible in Forge** [No]

**Reproducible in Spigot** [No]

### Logs

[ERROR LOG](https://paste.ubuntu.com/p/9H4wkzg3Wd/)

**Comment by IzzelAliz** [comment]
Guess this is not related to us. Go ask their dev.

**Comment by K0bus** [comment]
Solved in last CreativeManager version.

https://www.spigotmc.org/resources/%E2%9A%A1-creativemanager-%E2%9A%A1-customizable-complete-control.75097/update?update=417119
