### ISSUE TITLE
java.lang.IllegalArgumentException: Slot 50 greater than inventory slot count

### ISSUE THREAD

**Issue by ahdg6** [IzzelAliz/Arclight#360]
### I am running

* **Arclight** [1.16.5-1.0.21-SNAPSHOT] 

* **This is the latest development version** [Yes]

* **Java** [adopt_hotspot-11] 

* **Operating System** [CentOS 7]

* **Plugins** 
Any plugin that access inventory
* **Mods** 
Traveler's backpacks

### Description

If you install any plugin that try to access inventory when Traveler's backpacks installed, you will suffering from console spam.

### Step to reproduce

1. Install Traveler's backpacks

 

**Reproducible in Forge** [No]

**Reproducible in Spigot** [No]

### Logs

[ERROR LOG](https://paste.ubuntu.com/p/CDqz75Wfx3/)

**Comment by Xplodin** [comment]
I also get this error with EliteLootBox on spigot with arclight.
Doesnt really break anything but is quite annoying

**Comment by josephtarbit** [comment]
This also occurs with Applied Energetics' various ME terminals. I assume this is to do with Arclight wrapping containers to support Bukkit's container system.

**Comment by ahdg6** [comment]
.

**Comment by IzzelAliz** [comment]
Please test this in latest dev build to see if this is fixed.

**Comment by IzzelAliz** [comment]
This is still relevant.

**Comment by GnomoMuitoLoco** [comment]
I'm having this problem, was there any solution found?
