### ISSUE TITLE
关闭正版验证无法进入服务器

### ISSUE THREAD

**Issue by MesuDevastator** [IzzelAliz/Arclight#366]
### 我正在运行

* **Arclight** arclight-1.17.1-1.0.0-SNAPSHOT-9e7575a 

* **你确认这是最新版吗** 是，当前日期是2021/8/28，这是在页面上最新成功的构建版本

* **你确认所有Mod都安装了依赖** 是，客户端和服务端均未安装Mod

* **你确认所有插件都已更新至对应版本** 是，服务端未安装插件

* **Java** java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing) 

* **操作系统** Windows 10 1809

  

* **插件列表** 
未安装插件
* **Mod 列表** 
未安装Mod

### 错误描述

在 server.properties 中关闭正版验证后使用客户端进入服务器会引发内部错误

### 重现步骤

1. 使用启动参数 "java -Xms6G -Xmx6G --show-version -XX:+UseZGC -jar arclight-forge-1.17.1-1.0.0-SNAPSHOT.jar nogui" 启动服务器，server.properties中online-mode=false

2. 使用客户端进入服务器（Minecraft 1.17.1, Forge 37.0.45, MCP 20210706.113038）

3. 遇到内部错误：Internal Exception: java.lang.IllegalAccessError: class net.minecraft.server.network.ServerLoginPacketListenerImpl$1Handler$e867bc289e2c4a569985fe3683cfb8ad tried to access private field net.minecraft.server.network.ServerLoginPacketListenerImpl.f_10014_ (net.minecraft.server.network.ServerLoginPacketListenerImpl$1Handler$e867bc289e2c4a569985fe3683cfb8ad and net.minecraft.server.network.ServerLoginPacketListenerImpl are in module minecraft@1.17.1 of loader 'TRANSFORMER' @3206174f), (Type net.minecraft.server.network.ServerLoginPacketListenerImpl$1Handler$e867bc289e2c4a569985fe3683cfb8ad (loader: 'TRANSFORMER' @3206174f) is not a nest member of type net.minecraft.server.network.ServerLoginPacketListenerImpl (loader: 'TRANSFORMER' @3206174f): current type is not listed as a nest member)

https://1drv.ms/u/s!ApIZUltIX_c-kUBSLBOF984fPZ2n?e=GpIlGX

**可在 Forge 复现** 否

**可在 Spigot 复现** 否

### 报错信息

https://paste.ubuntu.com/p/4NDrTqq2MP/

**Comment by IzzelAliz** [comment]
上游依赖问题，等他们出正式版
