### ISSUE TITLE
核心与服务端不在同一目录的问题

### ISSUE THREAD

**Issue by 0XPYEX0** [IzzelAliz/Arclight#37]
如题，服务端与核心不在同一目录下，即工作目录与核心目录不同。
在以上情况启动服务器后，核心目录中已有Forge与Minecraft原版核心，但Arclight只检查工作目录中是否存在这两个核心，故此需要在工作目录再次放入前置核心。

**Comment by IzzelAliz** [comment]
我觉得没什么问题
