### ISSUE TITLE
自定义构建Arclight 1.16.5的forge时mapping下载出错！

### ISSUE THREAD

**Issue by Hypocisy** [IzzelAliz/Arclight#370]
### 我正在运行

* **Arclight** arclight-1.16.5-SNAPSHOT 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** 只是构建arclight

* **你确认所有插件都已更新至对应版本** [是/否]

* **Java** [版本] 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
* **操作系统** [名称+版本]
Microsoft Windows [版本 10.0.19043.1165]
  
None
* **插件列表** 
None
* **Mod 列表** 
None

### 错误描述
自定义构建Arc版本出错：
报错1：https://paste.ubuntu.com/p/JD26qzVgdS/
报错2：https://paste.ubuntu.com/p/kknFqQMw83/
forge的mapping 地址改了，从原来的 time+mcversion,变成了 mcversion+time.时间戳,导致无法下载mapping。
所以构建失败，但我修改build.gradle为以下内容时：
![image](https://user-images.githubusercontent.com/43266516/132127402-b09d646a-fb96-4674-b6d1-4b7c3b0d14ac.png)
发生报错2，请修复此bug，非常感谢！
测试链接：
https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_config/1.16.3-20201025/mcp_config-20201025-1.16.3.zip
https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_config/1.16.3-20201025.185957/mcp_config-1.16.3-20201025.185957.zip

### 重现步骤

1. 打开IntelliJ IDEA Community Edition 2021.1.2 x64并从Arclight远程仓库克隆。

2. 更改/build.gradle 的 forgeVersion 为 36.2.4

3. ./build.gradle build，然后出现报错https://paste.ubuntu.com/p/JD26qzVgdS/ ，打开提示中的url发现是404.

 

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

**Comment by IzzelAliz** [comment]
我只知道我的机器和两个构建服务器都能正常构建，建议你检查自己的网络

**Comment by Hypocisy** [comment]
> 我只知道我的机器和两个构建服务器都能正常构建，建议你检查自己的网络

你本地有缓存，我是重新构建的，现在已经没法构建了
![image](https://user-images.githubusercontent.com/43266516/132159091-9bd6072a-36e1-4d1f-b0bb-7f41553bf985.png)

**Comment by timi137137** [comment]
> > 我只知道我的机器和两个构建服务器都能正常构建，建议你检查自己的网络
> 
> 
> 
> 你本地有缓存，我是重新构建的，现在已经没法构建了
> 
> ![image](https://user-images.githubusercontent.com/43266516/132159091-9bd6072a-36e1-4d1f-b0bb-7f41553bf985.png)
> 
> 

请复制一下链接发到这里，我本地无环境尝试下载？

**Comment by Hypocisy** [comment]
> > > 我只知道我的机器和两个构建服务器都能正常构建，建议你检查自己的网络
> > 
> > 
> > 你本地有缓存，我是重新构建的，现在已经没法构建了
> > ![image](https://user-images.githubusercontent.com/43266516/132159091-9bd6072a-36e1-4d1f-b0bb-7f41553bf985.png)
> 
> 请复制一下链接发到这里，我本地无环境尝试下载？

请问是哪个链接，如果是图里的链接那么是以下:
https://files.minecraftforge.net/maven/net/minecraft/mappings_snapshot/20210215-1.16.3/mappings_snapshot-20210215-1.16.3.zip
如果是Arclight，那么请使用: 
git clone https://github.com/IzzelAliz/Arclight

**Comment by IzzelAliz** [comment]
mcp config 和 mcp mapping 是两个东西

https://maven.izzel.io/releases/de/oceanlabs/mcp/mcp_snapshot/20210215-1.16.3

构建使用的 mcp 是我自己托管的

**Comment by Hypocisy** [comment]
> mcp config 和 mcp mapping 是两个东西

明白了，请问为什么构建不了呢？

**Comment by IzzelAliz** [comment]
建议你检查自己的网络

**Comment by Hypocisy** [comment]
> 建议你检查自己的网络

好的，感谢帮助！
