### ISSUE TITLE
Reset of bed spawnpoint after first respawn on bed

### ISSUE THREAD

**Issue by Archer-Dante** [IzzelAliz/Arclight#376]
### I am running

* **Arclight** 1.0.20 

* **This is the latest development version** [N]

* **Java** 1.8.0_301 

* **Operating System** Windows 10 ver 2004 build. 19041.264

* **Plugins** 
no plugins

* **Mods** 
no mods

### Description
After saving new spawnpoint on bed and 1 respawn, any next respawns goes to the world spawn point instead of bed (reset of saved spawn point?)

### Step to reproduce

1. Run server
2. Set new spawnpoint on bed
3. /kill
4. Get respawn on bed
5. /kill
6. Get respawn on world spawn, no more bed on any next death too

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

### Logs

https://pastebin.com/fVyC4nHf

**Comment by Hikk0o** [comment]
How to fix it? (On my server)

**Comment by QJL9** [comment]
Same thing happend on my server，I have to click the bed to reset the spawnpoint.
