### ISSUE TITLE
bungeecord 无法跳转到服务器

### ISSUE THREAD

**Issue by Crazy-li-wed** [IzzelAliz/Arclight#38]
Waterfall版本366
我用的: arclight-forge-1.15-1.0.3
报错[22:38:00] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: /127.0.0.1:57259 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

**Comment by IzzelAliz** [comment]
高版本 Forge 不支持 BC

相关 issue https://github.com/PaperMC/Waterfall/issues/450
