### ISSUE TITLE
Bountiful Baubles error

### ISSUE THREAD

**Issue by Lucasmellof** [IzzelAliz/Arclight#380]
### I am running

* **Arclight** arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed

* **This is the latest development version** Y

* **Java** OpenJDK Runtime Environment (build 16.0.2+7-67)

* **Operating System**  Ubuntu 20.04.2 LTS x86_64

* **Plugins** None

* **Mods** 
-- bountifulbaubles-1.16.5-0.1.0-forge
-- curios-forge-1.16.5-4.0.5.3

### Description

Mixin error.

### Step to reproduce

1. Install Curios and BountifulBaubles.
2. Run Arclight.

**Reproducible in Forge** N

**Reproducible in Spigot** N

### Logs

[ERROR LOG]

https://paste.ubuntu.com/p/8qzHPwmVJx/

**Comment by IzzelAliz** [comment]
Their dev seems resolved this somehow, so closing this.
