### ISSUE TITLE
Simply-Seasons mod载入问题

### ISSUE THREAD

**Issue by yeyaodada** [IzzelAliz/Arclight#386]
### 我正在运行
* **Arclight** [版本] 
arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed
* **你确认这是最新版吗** [是/否，因为___]
是

* **你确认所有Mod都安装了依赖** [是/否]
是

* **你确认所有插件都已更新至对应版本** [是/否]

是
* **Java** [版本] 
java16
* **操作系统** [名称+版本]

  
Simply-Seasons-1.16.5-1.0.17
* **插件列表** 
不是插件的问题

* **Mod 列表** 
 Simply-Seasons-1.16.5-1.0.16

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 在服务器内装入Simply-Seasons mod后

2. 启动服务器

 

**可在 Forge 复现** [是/否]
这个是mod载入时的问题吧

**可在 Spigot 复现** [是/否]
否

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/cMsStz55Rc/

**Comment by IzzelAliz** [comment]
无法修复，请报给该 mod 作者看他有没有想法修。
