### ISSUE TITLE
[1.16.5][集成动力]IntegratedDynamics-1.16.5-1.10.0 导致服务器崩溃

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#387]
### 我正在运行

* **Arclight** [版本] 
arclight-forge-1.16.5-1.0.21-SNAPSHOT
* **你确认这是最新版吗** [是/否，因为___]

是
* **你确认所有Mod都安装了依赖** [是/否]
是
* **你确认所有插件都已更新至对应版本** [是/否]

是
* **Java** [版本] 
* openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)
* **操作系统** [名称+版本]
Linux Centos7
  

* **插件列表** 
Plugins (52): BossCooling, InventoryRollbackPlus, ChunkHeat, PlaceholderAPI, PlugMan, ConsoleSpamFix, NotBoom, ServerChat, metb, NBTAPI, SIWorldProtection, LightAPI, CoreProtect, MiniMOTD, LuckPerms, ClearItem, CrazyAuctionsPlus, spark, LoneLibs, ProtocolLib, NBTalk, AutoUnloadChunk, Uniporter, LiteSignIn, Minepacks, MultiLogin, CowSuperJoin, Mcrmb, Vault, MiaoChat, McrmbBuyCommand, LWC, Marriage, VipSystem, BossShopPro, ConvenientSale, YukiNoaAPI, AdvancedBan, XConomy, Multiverse-Core, LWCTrust, Plan, TAB, NekoMaid, QuickShop, ItemsAdder, CMILib, CMI, MobFarmManager, TabooLib5, TrMenu, Residence
* **Mod 列表** 
打不开崩溃x

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 [集成动力]IntegratedDynamics-1.16.5-1.10.0

2. 打开就崩溃

 

**可在 Forge 复现** [是/否]
否

**可在 Spigot 复现** [是/否]
不是插件
### 报错信息

[错误日志]

**Comment by ghost** [comment]
崩溃报告没发出去 https://paste.ubuntu.com/p/gDS3DHDwj2/

**Comment by sheng-ri** [comment]
请更新模组
https://github.com/CyclopsMC/IntegratedDynamics/issues/1093

**Comment by sheng-ri** [comment]
请更新模组
https://github.com/CyclopsMC/IntegratedDynamics/issues/1093
https://github.com/CyclopsMC/IntegratedDynamics/commit/89423078ee661c23357828c769394d5dc367702e
