### ISSUE TITLE
worldedit-bukkit-7.2.5-dist无法加载

### ISSUE THREAD

**Issue by 3269199948** [IzzelAliz/Arclight#390]
### 我正在运行

* **Arclight** [版本] arclight-forge-1.16.5-1.0.20

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [版本] 1.8

* **操作系统** [Win10]

  

* **插件列表** MiniMOTD, LuckPerms, PlaceholderAPI, MythicLib, SpringAround, Vault, Multiverse-Core, ProtocolLib, WorldEdit, DeluxeMenus, EpicCraftingsPlus, AuthMe, TAB, WorldGuard, Citizens, Shopkeepers, Quests, MMOItems, CommandNPC, BetterRTP, CMILib, CMI, CMIEInjector

* **Mod 列表** 
*  minecraft forge-1.16.5-36.2.0-server.jar : minecraft (1.16.5) - 1
• mods_folder [mod][围火无怪]nohostilesaroundcampfire_1.16.5-3.3.jar : nohostilesaroundcampfire (3.3) - 1
• mods_folder [mod][超多生物群系]BiomesOPlenty-1.16.5-13.1.0.482-universal.jar : biomesoplenty (1.16.5-13.1.0.482) - 1
• mods_folder [mod][Macaw的屋顶]mcw-roofs-2.0.1-mc1.16.5-4.jar : mcwroofs (2.0.1) - 1
• mods_folder [mod][FTB Ranks]ftb-ranks-1604.1.1.11.jar : ftbranks (1604.1.1.11) - 1
• mods_folder [mod][家具]cfm-7.0.0pre22-1.16.3.jar : cfm (7.0.0-pre22) - 1
• mods_folder [mod][FTB前置]architectury-1.10.138-forge.jar : architectury (1.10.138) - 1
• mods_folder [mod][FTB前置]ftb-gui-library-1605.2.1.41-forge.jar : ftbguilibrary (1605.2.1.41) - 1
• mods_folder [mod][皮肤]CustomSkinLoader_Forge-14.13-SNAPSHOT-278.jar : customskinloader (14.13-SNAPSHOT-278) - 1
• mods_folder [mod][虚无世界3]AoA3-3.5.4-1.16.5.jar : aoa3 (3.5.4) - 1
• mods_folder [mod][前置]cloth-config-4.11.26-forge.jar : cloth-config (4.11.26) - 1
• mods_folder [mod][JEI物品管理器]jei-1.16.5-7.7.1.111.jar : jei (7.7.1.111) - 1
• arclight arclight-forge-1.16.5-1.0.20.jar : arclight (1.16.5-1.0.20-368b0cb) - 1
• mods_folder [mod][自然环境前置]abnormals_core-1.16.5-3.2.0.jar : abnormals_core (3.2.0) - 1
• mods_folder [mod][自然环境]environmental-1.16.5-1.0.0.jar : environmental (1.0.0) - 1
• mods_folder [mod][FTB-Teams]ftb-teams-1604.1.0.16-forge.jar : ftbteams (1604.1.0.16) - 1
• mods_folder [mod][FTB Chunks]ftb-chunks-1605.2.3-build.75.jar : ftbchunks (1605.2.3-build.75) - 1
• maven_libs forge-1.16.5-36.2.0-universal.jar : forge (36.2.0) - 1
• mods_folder [mod][经典状态条]classicbar-4.0.1-1.16.3.jar : classicbar (4.0.1-1.16.3) - 1
• mods_folder [mod][动态的树]DynamicTrees-1.16.5-0.10.0-Beta25.jar : dynamictrees (1.16.5-0.10.0-Beta25) - 1
• mods_folder [mod][动态的树-BOP扩展]DynamicTreesBOP-1.16.5-2.0.6.jar : dtbop (1.16.5-2.0.6) - 1
• mods_folder [mod][篝火前置]collective-1.16.5-2.25.jar : collective (2.25) - 1
• mods_folder [mod][治愈营火]healingcampfire_1.16.5-3.2.jar : healingcampfire (3.2) - 1
• mods_folder [mod][动态环绕]DynamicSurroundings-1.16.4-4.0.4.2.jar : dsurround (1.16.4-4.0.4.2) - 4
• mods_folder [mod][旅行者背包]TravelersBackpack-1.16.5-5.4.3.jar : travelersbackpack (5.4.3) - 1

### 错误描述

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装worldedit

2. 查看控制台

3.https://paste.ubuntu.com/p/kWW4CRrhF9/

 

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[https://paste.ubuntu.com/p/kWW4CRrhF9/]

**Comment by IzzelAliz** [comment]
https://github.com/ArclightPowered/patcher

**Comment by 3269199948** [comment]
> https://github.com/ArclightPowered/patcher

啥意思哦 大佬
