### ISSUE TITLE
Arclight ComputerCraft incompatibility when behind a Lightfall Proxy

### ISSUE THREAD

**Issue by Rishum-P** [IzzelAliz/Arclight#392]
### I am running

* **Arclight** [arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed] 

* **This is the latest development version** [Y]

* **Java** [OpenJDK v1.8.0 Build 265] 

* **Operating System** [Windows 10 (Also tested on CentOS 7)]

* **Plugins** None

* **Mods** CC-Tweaked (1.16.5) - Build 1.98.2

### Description

When Arclight is behind a Lightfall Proxy (Latest) it produces the following error on player join: 

![image](https://user-images.githubusercontent.com/21267720/137593297-831d3e5d-3682-4527-8cb2-318a9ecc376f.png)

The following error is displayed in the client-side log: 
`[16:24:07] [Netty Client IO #1/ERROR]: Could not deserialize arclight:wrapped`

I have posted this bug report here (opposed to Lightfall repo) as it's likely an issue in the following Arclight code, when Computercraft arguments are being serialised: https://github.com/IzzelAliz/Arclight/blob/1.16/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/command/arguments/ArgumentTypesMixin.java

This error does not happen when it is run on Arclight alone, only when Arclight is behind a lightfall proxy.

### Step to reproduce

1. Run an Arclight server behind a lightfall proxy
2. Install Computercraft (And Lightfall-Client, on the client)
3. Player will be unable to join the server

The logs have been produced on a test server I made for this bug, as it's reproducible on its own without any other mods/plugins.

**Reproducible in Forge:** N

**Reproducible in Spigot:** N

### Logs

Client Log: https://pastebin.com/RsBh29qr
Arclight Log: https://pastebin.com/RWXLmX5k
Lightfall Log: https://pastebin.com/0GNKHvZc

**Comment by LuZWCHA** [comment]
The same issue with the latest build of  arclinght and lightfall.The log files print the same content as Ridhum-P's provided logs.

**Comment by IzzelAliz** [comment]
You are possibly running an outdated lightfall, try update.

**Comment by Rishum-P** [comment]
Still incompatible with latest Lightfall build however the following error is now shown on the proxy:

`io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No provider for argument computercraft:computers`

Issue still only occurs when behind a Lightfall proxy.

**Comment by IzzelAliz** [comment]
You need to enable bungee in spigot.yml.

**Comment by Rishum-P** [comment]
My bad forgot to re-enable it on my test instance. With enabled though it still gives the same error as initially (Malformed JSON) with the same: `Could not deserialize arclight:wrapped` in client-side log.
