### ISSUE TITLE
[Bug Report]: Arclight crash on startup under pterodactyl 1.5.3

### ISSUE THREAD

**Issue by BreizhHardware** [IzzelAliz/Arclight#396]
### Arclight Version

arclight-forge-1.16.5-1.0.20

### Are you running the latest development version?

Yes

### Java Version | Operating System

Java_11

### The Name and Version of Related Mod/Plugins

Mods:
adaptive_performance_tweaks 
Adorn 
AmbientSounds
AppleSkin
Ballistix
Bette Zoom
Chisel
Clumps
Cooking For Blockheads
Create
Create addon
Create stuff additions
Electrodynamics
 ExtraArmor
Jei
MasterfulMachinery
Mekanism (Generatior, Additions and Tools)
Refined Sotrage
Vehicle mod   Plugins: No one

### Description

When the server start he said Fail to launch Arclight
[2021-11-01-1.log](https://github.com/IzzelAliz/Arclight/files/7454725/2021-11-01-1.log)
.

### Step to reproduce

1. Install a server in a pterodatyl panel 2. start the server

### Reproducible in Forge

No

### Reproducible in Spigot

No

### Logs

Logs link
[2021-11-01-1.log](https://github.com/IzzelAliz/Arclight/files/7454755/2021-11-01-1.log)

**Comment by IzzelAliz** [comment]
Remove performant.
