### ISSUE TITLE
First Aid 兼容性问题

### ISSUE THREAD

**Issue by PA733** [IzzelAliz/Arclight#40]
### 我正在运行

* **Arclight** arclight-1.16-1.0.7-SNAPSHOT、arclight-1.15-1.0.7（由于未知原因，我本地运行的时候当前版本显示为null，在这里我放出了程序文件名）（上述两个文件名代表在两个版本中，均出现了此问题）
 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** build 1.8.0_261-b12 

* **操作系统** windows server 2016、ubuntu:focal(20.04)、ubuntu 20.10均已测试

* **插件列表** 
无
* **Mod 列表** 
[FirstAid](https://www.curseforge.com/minecraft/mc-mods/first-aid)

### 错误描述
首先，我只装载了一个forge mod。
_first aid，一个让Minecraft的医疗系统更加接近于现实的模组。
添加了这个模组你的头、手、脚以及身体等，都有各自的健康值。
在身体各部分受伤时，你应该采取正确的方式去治疗，比如绷带、石膏或者吗啡来使你恢复正常；并且当你状态不佳时你会有很高的概率引发更多不良的Buff。_（来自[mcmod介绍](https://www.mcmod.cn/class/916.html)）
当我使用目录下的arclight-forge-1.16-1.0.7-SNAPSHOT.jar（对于1.15.2，我使用arclight-forge-1.15-1.0.7.jar）启动服务端时，程序会崩溃。
当我使用目录下的forge-1.16.2-33.0.22.jar（对于1.15.2，我使用forge-1.15.2-31.2.30.jar）启动程序时，程序可以正常运行，mod可以正常加载。

### 重现步骤

1. 在mod目录下装载 [FirstAid 1.9.3.1](https://www.curseforge.com/minecraft/mc-mods/first-aid/download/3045732)（对于1.15.2，我使用[FirstAid 1.8.2](https://www.curseforge.com/minecraft/mc-mods/first-aid/download/2999358)）
2. 使用arclight-forge-1.16-1.0.7-SNAPSHOT.jar（对于1.15.2，我使用arclight-forge-1.15-1.0.7.jar）启动服务端

**可在 Forge 复现** 否

**可在 Spigot 复现** 否

**可在 Arclight 复现** 是

### 报错信息

[错误日志]

[latest.log](https://paste.ubuntu.com/p/fzhX79ZxVx/)
[latest.log](https://github.com/IzzelAliz/Arclight/files/5148217/latest.log)

**Comment by PA733** [comment]
看到了更新，非常感谢修复，但是我注意到并没有编译通过。
同时，希望下一次编译加上1.15的支持，谢谢。
因为比较急（这个mod很重要），希望尽快处理。
非常感谢

**Comment by PA733** [comment]
哦对了，版本号显示null是我的问题吗？
如果不是，下个版本顺便也修复下呗
(｀・ω・´)

**Comment by IzzelAliz** [comment]
版本号显示我不知道什么问题...
