### ISSUE TITLE
1.17.1-1.0.1 not launching.

### ISSUE THREAD

**Issue by notsatvrn** [IzzelAliz/Arclight#405]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.17.1-1.0.1

### OS & Java versions

OS: Arch Linux, Java: openjdk version "17.0.1" 2021-10-19

### Plugins and Mods

```raw
Cant run, will not start.
```

### Description

The server will not start. It fails to load even before mods or plugins begin loading, with a ClassNotFoundException error.

### Step to reproduce

1. Install Arclight 1.17.1 1.0.1.
2. Launch.
3. Profit?

### Logs

https://pastebin.com/ci496Tmn

**Comment by joaoespanhol** [comment]
same problem #404
