### ISSUE TITLE
1.14/1.15 ExceptionInInitializerError calling at java.lang.reflect.Field.getGenericType for Item.ister

### ISSUE THREAD

**Issue by bergerkiller** [IzzelAliz/Arclight#41]
### I am running

* **Arclight** arclight-1.15.2-1.0.7-ee37072 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

* **This is the latest development version** Y

* **Java** jre1.8.0_201

* **Operating System** Windows 7

* **Plugins** BKCommonLib https://ci.mg-dev.eu/job/BKCommonLib/890/

* **Mods** None

### Description

While initializing BKCommonLib it's trying to interpret the server environment by reading the classes and declared fields inside those classes. During initialization it retrieves the (generic) field type of the Field. This fails (and only on Arclight, works fine on Magma/Mohist/spigot).

If I had to make a guess, my guess is that a method is contained inside Item which uses a Class only available on the Client. I don't think the server should be using the ItemStackTileEntityRenderer class.

This involves some field in _net.minecraft.item.Item_:
<pre>
private final java.util.function.Supplier ister;
</pre>
I assume the problematic type is contained in the generic description for whatever that Supplier supplies.

### Step to reproduce

1. Install BKCommonLib
2. Boot up
3. Errors (theres other errors, Im making a separate issue ticket for those)

**Reproducible in Forge** N

**Reproducible in Spigot** N

### Logs
https://paste.traincarts.net/oxokinubun.xml

<pre>
java.lang.TypeNotPresentException: Type net.minecraft.client.renderer.tileentity.ItemStackTileEntityRenderer not present
</pre>

**Comment by IzzelAliz** [comment]
Fixed in 365c2e851402ac4718506c3c8ffef8997f2e2ef4
