### ISSUE TITLE
Plugins are using a modded dimension for npc placement, homes, warps, etc 

### ISSUE THREAD

**Issue by Vinton08** [IzzelAliz/Arclight#414]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.21

### OS & Java versions

Java Version is 11.0.11

### Plugins and Mods

```raw
Plugins:
WorldGuard
ExplosionRegen
WorldEdit
WorldBorder
Vault
TradeSystem
Towny
SiegeWar
LuckPerms
InventoryRollback
EssentialsX
EconomyShopGUI Premium
CraftEnhance
CoreProtect
Citizens
Chairs
BanItem

Mods:
Abyssal Depths
Aquaculture 
Attribute Fix
Biomes O Plenty
CraftZone
Dynmap
Immersive Engineering 
Matchlock Guns
Odd Water Mobs
Spartan Weaponry
Tropicraft
Better Animals Plus
Chaos Awakens
GeckoLib
Small Ships 

```

### Description

Plugins are using a modded dimension for npc placement, homes, warps, etc 
All plugins will use the dimension
This has happened with several mods, so it isn’t specific to the mods or plugins

### Step to reproduce

Steps to reproduce:
Get a plugin like EssentialsX or Citizens that uses coordinates for homes, npc placement, etc, and a mod with other dimensions like CraftZone (it might take more than one mod to reproduce)
Put down a home, npc, warp etc. In the main world
Restart the server

### Logs

https://paste.ubuntu.com/p/zq6rHv3SMy/

**Comment by ItzPear** [comment]
Also having this problem.
