### ISSUE TITLE
stop没有传入插件

### ISSUE THREAD

**Issue by Smolder3955** [IzzelAliz/Arclight#415]
使用mcsmanager面板，关闭命令为stop，点击关服后无法退出，只能强制结束进程
![F8F2AABC6DE9C009528D7064C3446F37](https://user-images.githubusercontent.com/39408740/145674075-11b73ed5-a437-4ad2-b1d1-b6e779863228.jpg)

**Comment by Mike5357** [comment]
Also experiencing this issue, where shutting down the server gets stuck when using "stop"

**Comment by Navoei** [comment]
Same I also had this issue, seems to not happen newer versions.
