### ISSUE TITLE
Color parsing in chat not working.

### ISSUE THREAD

**Issue by Neovitalism** [IzzelAliz/Arclight#416]
This suddenly started happening after a reboot, where all hex codes only use the last number in the code as a default colour number. It was working fine previously. Essentials and TAB read it correctly in their messages/tab, but not messages in chat. I've tried 1.0.20, 1.0.21, and 1.0.22, all give the same thing. Moving the exact same plugins and files aside from ArclightPatcher to a spigot server did not reproduce. Removing ArclightPatcher and worldedit, this issue still continues.
![image](https://user-images.githubusercontent.com/70066544/145681464-dd234b6b-92f1-4bde-a5df-3de98ddc3d0e.png)

**Comment by timi137137** [comment]
use template
