### ISSUE TITLE
Colour codes not parsing in chat

### ISSUE THREAD

**Issue by Neovitalism** [IzzelAliz/Arclight#417]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.21-12996b7

### OS & Java versions

Apologies, the host does not show what OS they use other than Linux. Java 16 (Apologies, host does not provide better information and cannot run this in console)

### Plugins and Mods

```raw
Plugins:
ArclightPatcher
LuckPerms
Vault
PlaceholderAPI
WorldEdit
EssentialsX
EssentialsX Chat
TAB
PlugmanX

Mods:
None
```

### Description

All hex codes only use the last number in the code as a default colour number. It was working fine previously. Essentials and TAB read it correctly in their messages/tab, but not messages in chat. I've tried release 1.0.20, 1.0.21, and dev 1.0.22, all give the same thing.
![image](https://user-images.githubusercontent.com/70066544/145682329-05d4ee77-bc13-40ee-87e6-ba1218d21699.png)

### Step to reproduce

1. Install and run arclight for 1.16.5.

2. Download EssentialsX, EssentialsX Chat, and LuckPerms.

3. Give yourself * permission (to make it easier, tested: was not a permission problem)

4. Give yourself a nickname using hex colours. I.E. /nick &#40444BT&#444950e&#494D55s&#4D525At

5. Reboot the server.

### Logs

N/A

**Comment by Mike5357** [comment]
Can confirm this issue as well; At first I thought it was Essentials Chat breaking but it doesnt work without it either. Hex codes work in things such as broadcasts and MOTD's but basic chat messages are displayed incorrectly:
![image](https://user-images.githubusercontent.com/12630858/145688281-c2b975e1-509b-4a51-8acc-d0030cc7ee83.png)
