### ISSUE TITLE
HeadDatabase v4.14.1 disable itself when triggered asynchronously

### ISSUE THREAD

**Issue by jahangir6969** [IzzelAliz/Arclight#420]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.21-12996b7 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### OS & Java versions

os: ubuntu 20.04 java: 8 211

### Plugins and Mods

```raw
LuckPerms, BuildersUtilities, ArmorStandTools, BlocksHub, PlugMan, spark, Vault, Multiverse-Core, FastAsyncWorldEdit (WorldEdit), DiscordSRV, VoxelSniper, BKCommonLib, goBrush, Arceon, goPaint, HeadDatabase, CoreProtect, VarLight, CMILib, LightCleaner, CMI
```

### Description

When running the command for headbatabase. the plugin itself disable itself. EG: headdatabase:hdb open pokekhan animals

### Step to reproduce

install the plugin run the command in description watch console disable the command and error out. 

### Logs

https://pastebin.com/kMMG5WAU

**Comment by IzzelAliz** [comment]
Not us.
