### ISSUE TITLE
FartherViewDistance plugin error for startup

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#421]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [x] unable to reproduce in Spigot
- [x] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0-SNAPSHOT

### OS & Java versions

OS: Win 10. Java 17

### Plugins and Mods

```raw
https://www.spigotmc.org/threads/fartherviewdistance.468241/
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
```

### Description

This plugin is extremely useful for the server, but alas, it cannot run on versions 1.16-1.18.1 of Arclight, I hope for you, I also hasten to inform you! After fixing the error, see if it works correctly on the server, you can read about its work from the links above.

### Step to reproduce

1 Install ProtocoLib 1.18+
2 FartherViewDistance 8.4.10
3 Look the console

4 If you manage to fix the error at startup, log into the server and see if the chunks are displayed correctly! But before that you need

- Server under spigot (bukkit), plugin's config.yml server-tick-max-generate-amount to 0 and read-server-loaded-chunk to false

### Logs

https://gist.github.com/XionioXMaster/b85008bdb2e123c79d5dcb6688db87d4

**Comment by DonorKrovi** [comment]
same, pls fix this

**Comment by DonorKrovi** [comment]
Deprecated, plugin no longer uses ProtocolLib
