### ISSUE TITLE
使用墓碑mod不生成死亡报告，这是一个arclight才会出现的错误

### ISSUE THREAD

**Issue by xlive2233** [IzzelAliz/Arclight#422]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.0-SNAPSHOT-908f646

### OS & Java versions

java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

系统：windows Server 2019 x64

### Plugins and Mods

插件: WhiteList, CustomSleeping
模组:
• minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1
• minecraft forge-1.18.1-39.0.0-universal.jar : forge (39.0.0) - 1
• mods_folder CosmeticArmorReworked-1.18.1-v1.jar : cosmeticarmorreworked (1.18.1-v1) - 1
• mods_folder 墓碑gravestone-1.18.1-1.0.0.jar : gravestone (1.18.1-1.0.0) - 1
• mods_folder cfm-7.0.0-pre27-mc1.18.1.jar : cfm (7.0.0-pre27) - 1
• arclight arclight-1.18.1-1.0.0-SNAPSHOT-908f646.jar : arclight (1.18.1-1.0.0-SNAPSHOT-908f646) - 1

### Description

使用墓碑mod死亡后不生成死亡报告，也没有在日志里显示错误，

这个错误从arclight forge1.16就已经出现，死亡报告是记录死亡后生成的墓碑坐标及其他信息。
经测试这个错误不会在原版forge或者其他插件+模组端出现。复现该bug的端文件已经放置迅雷网盘，请测试
链接：https://pan.xunlei.com/s/VMqqhih3obnIHubA9nNNoH3HA1 提取码：zcs9 

### Step to reproduce

1.正常启动游戏
2.玩家进入游戏死亡后即可复现

### Logs

https://pastebin.ubuntu.com/p/K8qYhQWhH9/

### Server pack link (Optional)

链接：https://pan.xunlei.com/s/VMqqhih3obnIHubA9nNNoH3HA1 提取码：zcs9

**Comment by timi137137** [comment]
要不你再去测试一次，别退出进入那么多次，我没看见关键log（可能我是个瞎子）

**Comment by xlive2233** [comment]
> 要不你再去测试一次，别退出多次，我没看见关键日志（可能我是个瞎子）

抱歉，我刚才尝试在游戏里死亡了一次，但是在后台日志界面甚至没有看到任何相关记录，但是这个错误的确只在arclight端存在。

**Comment by timi137137** [comment]
> > 要不你再去测试一次，别退出多次，我没看见关键日志（可能我是个瞎子）
> 
> 抱歉，我刚才尝试在游戏里死亡了一次，但是在后台日志界面甚至没有看到任何相关记录，但是这个错误的确只在arclight端存在。

内个啥，没log死无对证啊，这只能看另一位作者有没有头绪了(
