### ISSUE TITLE
1.18.1上无法保存告示牌上的文字数据

### ISSUE THREAD

**Issue by xlive2233** [IzzelAliz/Arclight#423]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.0-SNAPSHOT-8acc90b8

### OS & Java versions

java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing) 系统：windows server x64

### Plugins and Mods

```raw
*minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1

• minecraft forge-1.18.1-39.0.0-universal.jar : forge (39.0.0) - 1
• mods_folder CosmeticArmorReworked-1.18.1-v1.jar : cosmeticarmorreworked (1.18.1-v1) - 1
• mods_folder 墓碑gravestone-1.18.1-1.0.0.jar : gravestone (1.18.1-1.0.0) - 1
• mods_folder cfm-7.0.0-pre27-mc1.18.1.jar : cfm (7.0.0-pre27) - 1
• arclight arclight-1.18.1-1.0.0-SNAPSHOT-8acc90b.jar : arclight (1.18.1-1.0.0-SNAPSHOT-8acc90b) - 1


### Description

告示牌上的文字无法保存，在告示牌写入文字后，切换世界或者退出游戏再进去就消失了，变成了空白的告示牌。

### Step to reproduce

1.进入服务器
2.放置告示牌写入文字
3.退出游戏再进入
查看告示牌文字消失

### Logs


[latest.log](https://github.com/IzzelAliz/Arclight/files/7716576/latest.log)



### Server pack link (Optional)

无

**Comment by IzzelAliz** [comment]
我 他 妈 不 知 道 什 么 是 墓 碑 皮 肤 家 具

**Comment by xlive2233** [comment]
> 我他妈不知道道什么是墓碑碑皮肤家具

抱歉，已经更新
