### ISSUE TITLE
机械动力和模组维度bug

### ISSUE THREAD

**Issue by Smolder3955** [IzzelAliz/Arclight#426]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22.jar

### OS & Java versions

openjdk version "16.0.2" 2021-07-20 OpenJDK Runtime Environment Zulu16.32+15-CA (build 16.0.2+7) OpenJDK 64-Bit Server VM Zulu16.32+15-CA (build 16.0.2+7, mixed mode, sharing)

### Plugins and Mods

```raw
插件: 无，下面链接压缩包内附log和Mod
```

### Description

* 使用机械动力的动力锯砍伐树木不会将掉落的物品存入箱子
* 如果不使用为模组维度创建符号链接 symlink-world=true 在模组维度下线再上线会回到主世界

### Logs

下面链接压缩包内附

### Server pack link (Optional)

https://1drv.ms/u/s!AkdhFBZPYtwmoFyLahLJtBD6Cxl2?e=ZPY43Z

**Comment by timi137137** [comment]
不接受内附log或mod，如果不上传并填写将被close

**Comment by Smolder3955** [comment]
> 不接受内附log或mod，如果不上传并填写将被close

https://pastebin.mozilla.org/eaS7mCpd

debug日志 https://1drv.ms/u/s!AkdhFBZPYtwmoF1BurIv2tdhgecR?e=eFOfQ1
