### ISSUE TITLE
WorldEdit Bukkit 1.18.1 not working with Arclight 1.18.1

### ISSUE THREAD

**Issue by Navoei** [IzzelAliz/Arclight#427]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0-SNAPSHOT [1.18-25]

### OS & Java versions

OS: Linuxmint Java: 17.0.1

### Plugins and Mods

```raw
Mods:
• minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1
• mods_folder voicechat-forge-1.18.1-2.1.22.jar : voicechat (1.18.1-2.1.22) - 1
• minecraft forge-1.18.1-39.0.0-universal.jar : forge (39.0.0) - 1
• mods_folder soundphysics-forge-1.18.1-1.0.3.jar : sound_physics_remastered (1.18.1-1.0.3) - 1
• mods_folder appleskin-forge-mc1.18-2.2.0.jar : appleskin (2.2.0) - 1
• arclight arclight-1.18.1-1.0.0-SNAPSHOT-1912d07.jar : arclight (1.18.1-1.0.0-SNAPSHOT-1912d07) - 1
Plugins:
CustomHelpMessage, LuckPerms, InventoryRollbackPlus, ChatMessenger, PlaceholderAPI, Spicord, SetSpawn, HolographicDisplays, CustomRules, InvSeePlusPlus, ConsoleSpamFix, ProtocolLib, AnvilColor, SimpleTpa, SkinsRestorer, RHLeafDecay, HorseTpWithMe, Vault, MyHome, MelonDamageLib, WorldEdit, MineableSpawners, AdvancedBan, BanAnnouncer, WorldGuard, GSit, ChatEx, SuperVanish, GriefPrevention, CoreProtect, CustomJoinMessages, DiscordSRV, TabList, BetterRTP, PlugManX (PlugMan)
```

### Description

WorldEdit loads fine and no errors are printed in console. It is only when attempting to edit blocks that the issue comes up. When editing blocks I get the message "Editing on unsupported versions is disabled." No edits are made to the terrain.

### Step to reproduce

1. Install WorldEdit
2. Attempt to edit an area via //wand

### Logs

No errors are printed in console.

**Comment by IzzelAliz** [comment]
Have you read FAQ?

**Comment by Navoei** [comment]
Yes. I installed the patch for worldedit but it did not work. I forgot to mention it.

**Comment by timi137137** [comment]
Hey, do you know if you should look for similar questions in the closed questions? This question has been answered many times

**Comment by Navoei** [comment]
Well, I read and did what the FAQ said, but the patcher loader hasnt been updated. It currently does not support the latest version of world edit.

**Comment by HotoRas** [comment]
Same issue on #524, but I made it clearer than yours (use minimal plugins and mods) that there's only one or two reasons left to think.
