### ISSUE TITLE
[1.16.5]请求更新Forge版本

### ISSUE THREAD

**Issue by EnterFor** [IzzelAliz/Arclight#430]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22-SNAPSHOT

### OS & Java versions

Windows Server 2019  Java Version: 1.8.0_312, BellSoft

### Plugins and Mods

```raw
模拟殖民地
```

### Description

Forge版本过低，殖民地mod载入失败

### Logs

https://paste.ubuntu.com/p/ScRXbgDqbF/

**Comment by FReEzZzi** [comment]
```
Details:
	Mod File: [模拟殖民地]minecolonies-1.16.5-1.0.311-BETA.jar
	Failure message: Mod minecolonies requires forge 36.2.20 or above
		Currently, forge is 36.2.19

```

**Comment by Taskeren** [comment]
https://github.com/IzzelAliz/Arclight/wiki/FAQ

#### I want to use a custom Forge version

You need to download the installer at https://files.minecraftforge.net and install server in the server folder. If you are in a headless environment, you can run java -jar installer.jar --installServer path/to/server. After installing forge you need to rename the new forge-<mc>-<ver>.jar to the default one.

Custom forge may bring you extra incompatibility, try with caution.
