### ISSUE TITLE
Server Crash in 1.18.1 Arclight

### ISSUE THREAD

**Issue by Navoei** [IzzelAliz/Arclight#433]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0-SNAPSHOT [1.18-28]

### OS & Java versions

OS: Linuxmint Java: 17.0.1

### Plugins and Mods

```raw
No mods or plugins are present.
```

### Description

When opening a horse's inventory after taming it, the server crashes. 

### Step to reproduce

1. Spawn a horse.
2. Tame it.
3. Open its inventory. 

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/7781432/latest.log)

**Comment by muriplz** [comment]
happens without opening its inventory too, you just have to wait some seconds. While taming it it wont happen.
