### ISSUE TITLE
mod无法加载导致服务器启动崩溃

### ISSUE THREAD

**Issue by xlive2233** [IzzelAliz/Arclight#434]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.0-SNAPSHOT-0ede4c88

### OS & Java versions

系统：windows server 2019    java： java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### Plugins and Mods

```raw
Plugins (1): WhiteList
 Mod List:
• minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1
• minecraft forge-1.18.1-39.0.0-universal.jar : forge (39.0.0) - 1
• mods_folder EasierSleeping-1.18.1-2.1.0.jar : easier_sleeping (2.1.0) - 1
• mods_folder CosmeticArmorReworked-1.18.1-v1.jar : cosmeticarmorreworked (1.18.1-v1) - 1
• mods_folder 墓碑gravestone-1.18.1-1.0.0.jar : gravestone (1.18.1-1.0.0) - 1
• mods_folder cfm-7.0.0-pre27-mc1.18.1.jar : cfm (7.0.0-pre27) - 1
• mods_folder 服务端优化ferritecore-4.0.0-forge.jar : ferritecore (4.0.0) - 1
• arclight arclight-1.18.1-1.0.0-SNAPSHOT-0ede4c88.jar : arclight (1.18.1-1.0.0-SNAPSHOT-0ede4c88) - 1
```

### Description

无法加载mod：+Wildfire+Female+Gender+Mod-2.8.1.jar
服务器启动崩溃

### Step to reproduce

1.启动服务器
2.崩溃

### Logs

[2021-12-28-1.log](https://github.com/IzzelAliz/Arclight/files/7784881/2021-12-28-1.log)

**Comment by timi137137** [comment]
这个log啥信息都没有，无能为力

**Comment by xlive2233** [comment]
> 这个日志啥信息都没有，无启用力

已重新编辑

**Comment by IzzelAliz** [comment]
报给模组作者

**Comment by xlive2233** [comment]
> 报给模组作者

已经报告了，但是在原版forge是运行正常的

**Comment by xlive2233** [comment]
> 报给模组作者

![Screenshot_2021-12-31-10-28-47-028_com discord](https://user-images.githubusercontent.com/28977537/147799678-f2d651cf-b873-452b-bb95-75d41774a47d.jpg)
![Screenshot_2021-12-31-10-23-06-291_com sogou translator](https://user-images.githubusercontent.com/28977537/147799680-5fdd7c04-d5b2-4dbe-bdfe-91b1d62e9857.jpg)
我已经反馈了原作者，这是他们的原话，还请看一下。
