### ISSUE TITLE
TriggerReactor 报错

### ISSUE THREAD

**Issue by galoti** [IzzelAliz/Arclight#440]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.22-SNAPSHOT-7c63a9e

### OS & Java versions

java version "1.8.0_311" Java(TM) SE Runtime Environment (build 1.8.0_311-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

### Plugins and Mods

```raw
TriggerReactor-3.2.5, Vault v1.7.3-b131
```

### Description

TriggerReactor crashes server

### Step to reproduce

1. Add TriggerReactor to plugins folder
2. Start the server

### Logs

https://paste.ubuntu.com/p/c2NpyX859d/

**Comment by IzzelAliz** [comment]
Fixed in d11631c6563527848ec3d6696f79f93307fb4f19.
