### ISSUE TITLE
CoreProtect无法启用

### ISSUE THREAD

**Issue by nenglizuida** [IzzelAliz/Arclight#441]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0

### OS & Java versions

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Microsoft-28056 (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Microsoft-28056 (build 17.0.1+12-LTS, mixed mode, sharing)

### Plugins and Mods

```raw
CoreProtect, CoreProtect-Clear
```

### Description

CoreProtect 20.3 在最新的螺核上无法正常启动
以测试Spigot能正常启动和使用

### Step to reproduce

把 CoreProtect 20.3 放进plugins
启动

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/7797425/latest.log)

**Comment by IzzelAliz** [comment]
与 #429 重复
