### ISSUE TITLE
bskyblock 报错

### ISSUE THREAD

**Issue by nenglizuida** [IzzelAliz/Arclight#444]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0

### OS & Java versions

openjdk 版本 "17.0.1" 2021-10-19 LTS OpenJDK 运行时环境 Microsoft-28056 (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Microsoft-28056 (build 17.0.1+12-LTS, 混合模式，分享）

### Plugins and Mods

```raw
BentoBox(和它的子插件)
```

### Description

世界文件未正常生成

### Step to reproduce

请直接下载服务器包

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/7797445/latest.log)

### Server pack link (Optional)

https://cloud.vlssu.com/s/qmqTy

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by nenglizuida** [comment]
> 请测试是否修复

经过测试 并且更新至最新版 BentoBox不报错了 BSkyBlock还在报错
