### ISSUE TITLE
[1.18] Create mod Schematicannon crash 

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#447]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.0-9830723

### OS & Java versions

Windows 10 java version "17.0.1" 2021-10-19 LTS

### Plugins and Mods

```raw
create mod 1.18.1 - 0.4.b
flywheel forge 1.18 - 0.5.0a
jei 1.18.1 - 9.2.1.69
-----------------
No plugins
```

### Description

The schematicannon crashes the server as soon as its activated. It shoots blocks and places them in the world depending on a .nbt file saved on ".minecraft/schematics" folder. It needs to take the items from a chest or a "create:creative_crate".

### Step to reproduce

1. Take create:schematic_and_quill
2. select 2 corners to create a 3D volume with some create mod blocks inside
3. Click the Volume with the crosshair and save it as an .nbt file
4. Place an create:schematic_table, and use a create:empty_schematic to select the .nbt file
5. Place the newly created create:schematic inside a create:schematicannon 
6. Press the play button

### Logs

https://pastebin.com/ShUwWLGp

**Comment by muriplz** [comment]
Also happens when you make a deployer move as a contraption using as filter the create:schematic. https://pastebin.com/RdAf3xDc (same setup)

**Comment by XionioXMaster** [comment]
mod side

**Comment by ghost** [comment]
This Bug in my server is right!
这真的是个bug，而且还没办法修
