### ISSUE TITLE
[1.16] Arclight does not stop correctly with plugin/Mod "WorldEdit"

### ISSUE THREAD

**Issue by HotoRas** [IzzelAliz/Arclight#448]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.22-SNAPSHOT-7c63a9e

### OS & Java versions

OS: Windows 11 Home (ko-KR), Java Oracle JDK version "17" 2021-09-14 LTS(build 17+35-LTS-2724)

### Plugins and Mods

```raw
Plugins (3): ArclightPatcher, WorldEdit, Multiverse-Core
 Mod List:
• minecraft forge-1.16.5-36.2.19-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.2.19-universal.jar : forge (36.2.19) - 1
• mods_folder flashnpcs-1.1.2.jar : flashnpcs (1.1.2) - 1
• arclight server.jar : arclight (1.16.5-1.0.22-SNAPSHOT-7c63a9e) - 1

----------Reproducable only with WorldEdit(MOD/PLUGIN)----------
```

### Description

With launched with plugin "WorldEdit", the server do not stop properly.
(Reproduced with no applied mod/plugin other than WorldEdit)
It says something is still online even after the `stop` command called on console, and it's forced to be shut down.

When `restart` is called, it doesn't shut down and just launch one more instance: the newly launched one cannot serve `latest.log`.

*Detailed Setup of Mine*
>Boot File:
>```bat
>@echo off
>title Archight Minecraft Server [1.16.5] on mc.jdh5968.pe.kr
>
>setlocal
>:restart
>java -Xms1G -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar "server.jar" nogui
>
>pause
>:end
>exit
>```
>Arclight JAR file: `server.jar`
>Forge Version: Default served with Arclight
>Others: Served with `latest.log`

### Step to reproduce

1. Launch Arclight with one of these setted up:
- in `/mods`, place `worldedit_forge` in correct version
- in `/plugin`, place the latest `worldedit_bukkit`

2. Type `stop` on console
3. Check `latest.log` and you'll see the error.

Or:

2. Type `restart` on console (the restart script should be set up before launch)
3. The former server console keeps launched (If new one launched, it says the log file is using)

### Logs

Log(Updating Arclight to Latest GitHub Action Build & Reset Server File(other than settings, mods, plugin)) uploaded to GitHub: [latest.log](https://github.com/IzzelAliz/Arclight/files/7859250/latest.log)

**Comment by ShunL12324** [comment]
not sure if we have the same issue, I'm using arclight on Linux with `screen`, using the command "stop" cannot quit the screen session properly.

**Comment by HotoRas** [comment]
+Additions:

Did not test on Forge because the version for Forge 1.16.5 is NOT up to date(plugin one is later), but it happened on Forge builds too.

Additional test log is submitted: it has plugin-by-plugin folder removed.

Additional Test Result: by-plugin, **same bootup batch file**
>Multiverse-Core: Not Happened
>ArclightPatcher: Not Happened
>WorldEdit: Error

**Comment by HotoRas** [comment]
> not sure if we have the same issue, I'm using arclight on Linux with `screen`, using the command "stop" cannot quit the screen session properly.

Please check out if you're using the latest build of Arclight. Lately they've got updated about enforcing session.
(Former that update I had to exit the session with `CONTROL+C` keybind, which is used to kill session.)

**Comment by timi137137** [comment]
see faq

**Comment by muriplz** [comment]
the last line on latest.log happens to me too, but I dont use world edit
