### ISSUE TITLE
FirstAid 安装后玩家死亡后重生按键失效

### ISSUE THREAD

**Issue by PA733** [IzzelAliz/Arclight#45]
### 我正在运行

* **Arclight** null（雾）（actions 第#148号构建版本）（ 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** [1.8.0_261] 

* **操作系统** win server 2019

* **插件列表** 
ebackup-1.1.3.jar
EntityTrackerFixer.jar
PluginManager.jar
QuickSleep.jar
VillagerOptimiser-1.1.4.jar

* **Mod 列表** 
firstaid-1.8.2.jar

### 错误描述

在最新构建的archlight中，我加载了firstaid 1.8.2
在游戏过程中，我发现玩家死亡后重生按键失效（按了没反应）
跟上次一样，使用archlight启动时会有此bug，使用目录下的forge启动时，没有此bug

### 重现步骤

1. 安装 firstaid 1.8.2
2. 进入服务器后 /kill
3. 尝试点击重生按键

**可在 Forge 复现** 否

**可在 Spigot 复现** 否

**可在 archlight 复现** 是

### 报错信息
此处附上服务端 debug日志-debug.log、latest日志-latest.log（我觉得这没啥用，因为在latest.log中没有观察到任何明显错误）、客户端运行时日志-client.log:
[latest.log](https://paste.ubuntu.com/p/pCdpg6w69n/)
[debug.log](https://paste.ubuntu.com/p/Ztpm7nbvcZ/)
[cilent.log](https://paste.ubuntu.com/p/ZMMncfCz73/)

**Comment by IzzelAliz** [comment]
actions 的构建产物不是拿来给你们用的，那个是测试 commit/pr 编译是否能通过的

去 appveyor 下载

**Comment by PA733** [comment]
> actions 的构建产物不是拿来给你们用的，那个是测试 commit/pr 编译是否能通过的
> 
> 去 appveyor 下载

准确来说，在#137号构建（appveyor对应1.15-172）后所有版本都会出现此问题。
