### ISSUE TITLE
Cannot get the latest dev build of Arclight

### ISSUE THREAD

**Issue by ShunL12324** [IzzelAliz/Arclight#451]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.21

### OS & Java versions

Ubuntu 20, open jdk 17

### Plugins and Mods

```raw
None
```

### Description

Cannot find a way to get the latest dev build since the `https://ci.appveyor.com/project/IzzelAliz/arclight-16` only keep the built files for up to one month. The latest version of arclight for 1.16.5 on the Github release page is 1.0.21 but I'm looking for the 1.0.22 version.

**Comment by timi137137** [comment]
compile it yourself
build it yourself

**Comment by ShunL12324** [comment]
> compile it yourself build it yourself

Yes, I could do that, but it is not the right way to solve the problem.

**Comment by timi137137** [comment]
you can go to actions get latest dev
