### ISSUE TITLE
Cancelling PlayerPortalEvent does not work anymore

### ISSUE THREAD

**Issue by bergerkiller** [IzzelAliz/Arclight#455]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.21-12996b7

### OS & Java versions

jre1.8.0_201

### Plugins and Mods

```raw
No mods. BKCommonLib and MyWorlds.
```

### Description

There was an issue that taking a nether portal causes a 'loading world' screen that never went away. After debugging the plugin further I found that MyWorlds cancelled the PlayerPortalEvent Bukkit event, yet the server teleported the player anyway. This causes a strange, glitched state.

### Step to reproduce

1. Install MyWorlds https://ci.mg-dev.eu/job/MyWorlds/109/
2. Install BKCL https://ci.mg-dev.eu/job/BKCommonLib/1216/
3. Place a portal sign next to a nether portal like so:
[portal]
myportal
INVALID

4. 'INVALID' doesnt exist so myworlds actively cancels the teleport, by cancelling the event. Player gets stuck on loading world screen.

### Simple reproducing code
Put in an event listener:
```
            @EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
            public void onPlayerPortal(PlayerPortalEvent event) {
                event.setCancelled(true);
            }
```

### Logs

There's no errors or warnings logged when this happens.

**Comment by IzzelAliz** [comment]
This is an upstream bug caused by forge patch to teleporter. Will do a temp fix.
