### ISSUE TITLE
[1.18] Crash for Ticking Entity

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#461]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.1-SNAPSHOT-408a327

### OS & Java versions

Windows 11 Java 17.0.1

### Plugins and Mods

```raw
LuckPerms, GriefDefender, Essentials

Mods: Create mod 0.4d , jei-1.18.1-9.2.1.69
```

### Description

These crashes have all been random, but once it happens, the player wont be able to load the chunk again, or server will crash again. It has happened to 3 people since I updated Arclight, that's why I think it has to do with 1.0.1 - SNAPSHOT

### Step to reproduce

Since it's been happening to some players with no direct cause, I don't know how to reproduce it

### Logs

https://pastebin.com/xfUmRibd

**Comment by IzzelAliz** [comment]
Duplicate with #470.
