### ISSUE TITLE
使用邮件Mod(Contact——往来)包裹传输Lore物品服务端会崩溃

### ISSUE THREAD

**Issue by HaruakiSakura** [IzzelAliz/Arclight#462]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.1-SNAPSHOT-b78d3af4

### OS & Java versions

系统:Windows 11 专业版21H2 java:openjdk version "17.0.1" 2021-10-19

### Plugins and Mods

```raw
[21:58:50 INFO] [Console]: Plugins (26): QiQWhiteList, LuckPerms, LiteItemShow, ServerMonitor, GiveItem, PlaceholderAPI, HiveChecker, DungeonPlus, Boom, ProtocolLib, LiteInvitation, Orebfuscator, Ath, CommandWhitelist, Vault, Prism, MyCommand, ProtocolStringReplacer, AngelChest, Essentials, CMILib, LWC, Residence, EssentialsChat, RandomSpawnPlus, EssentialsSpawn
[21:59:15 INFO]: Mod List:
• minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1
• mods_folder [MOD屏蔽村民交易^]Customvillagertrades-1.18_V13.jar : customvillagertrades (1.18 v13) - 1
• minecraft forge-1.18.1-39.0.59-universal.jar : forge (39.0.59) - 1
• mods_folder [MOD-邮政^]Contact-Forge-1.18-1.0.0-Alpha.jar : contact (1.0.0-Alpha) - 1
• mods_folder [MOD-前置^]SilveroakOutpost-Forge-1.18-1.0.9-Alpha.jar : silveroakoutpost (1.0.9-Alpha) - 1
• arclight arclight-1.18.1-1.0.1-SNAPSHOT-b78d3af4.jar : arclight (1.18.1-1.0.1-SNAPSHOT-b78d3af4) - 1
```

### Description

使用邮政MOD里的包装纸 打包一个有Lore的物品 
使用邮筒送至任意玩家 
玩家绑定的邮箱显示收到后 服务端直接崩溃

### Logs

debug.log
https://paste.ubuntu.com/p/gXYZHBGCKT/
latest.log
https://paste.ubuntu.com/p/btZBfZYYjN/

**Comment by stevefan1999-personal** [comment]
`java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'`
問題所在

**Comment by IzzelAliz** [comment]
不是我的问题，联系 Mod 开发者修复。
