### ISSUE TITLE
1.18.1 上无效的占位符

### ISSUE THREAD

**Issue by nnn950711** [IzzelAliz/Arclight#463]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.1-SNAPSHOT-b78d3af4

### OS & Java versions

Windows 11 / Eclipse Adoptium [ JDK-17.0.1.12-hotspot ]

### Plugins and Mods

```raw
Plugins (6): EpicPluginLib, PlayMoreSounds, PlaceholderAPI, ProtocolLib, Triton, PlugManX (PlugMan)

 Mod List:
• minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1
• mods_folder MouseTweaks-forge-mc1.18-2.21-滑鼠調整.jar : mousetweaks (2.21) - 1
• mods_folder flywheel-forge-1.18-0.6.0-前置.jar : flywheel (1.18-0.6.0) - 1
• mods_folder Jade-1.18-4.1.2.jar : jade (4.1.2) - 2
• minecraft forge-1.18.1-39.0.59-universal.jar : forge (39.0.59) - 1
• mods_folder create-mc1.18.1_v0.4d-機械動力.jar : create (0.4d) - 1
• arclight arclight-1.18.1-1.0.1-SNAPSHOT-b78d3af4.jar : arclight (1.18.1-1.0.1-SNAPSHOT-b78d3af4) - 1
• mods_folder jei-1.18.1-9.2.3.78-合成表.jar : jei (9.2.3.78) - 1
```

### Description

物品上翻譯的佔位符無效, 在正常的情況下應該顯示出來 (在 Arclight 上無效)
![2022-01-27_23 54 43](https://user-images.githubusercontent.com/41001774/151394971-f59f89af-159c-41ba-b5e8-715e3316e815.png)

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/7951842/latest.log)

**Comment by IzzelAliz** [comment]
你的翻译功能是什么插件提供的呢？

**Comment by nnn950711** [comment]
> 你的翻译功能是什么插件提供的呢？

Triton

https://www.spigotmc.org/resources/triton-translate-your-server.30331/
