### ISSUE TITLE
[1.16.5]模组Lightmans currency导致服务端无法启动

### ISSUE THREAD

**Issue by StarchierOrb** [IzzelAliz/Arclight#465]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.22-SNAPSHOT-47444d37

### OS & Java versions

OS：Windows 11，Java："11.0.11" 2021-04-20 LTS

### Plugins and Mods

```raw
插件：无
模组：lightmanscurrency-1.16.4-1.0.2.6
```

### Description

lightmanscurrency模组在服务端启动时报错崩溃，forge官服可以正常启动

### Step to reproduce

1.安装lightmanscurrency模组
2.启动服务器

### Logs

崩溃报告：https://paste.ubuntu.com/p/dT985q5zZS/
日志：https://paste.ubuntu.com/p/smJDdwQQMq/

**Comment by IzzelAliz** [comment]
Fixed in 8f90a71.
