### ISSUE TITLE
[1.16.5]使用jdk17 会导致Authme运行异常、登录限制无效、玩家不需要通过登录即可游玩

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#474]
### I have confirmed that ...
1.16暂不建议使用jdk17
使用jdk11或16 authme一切正常
不存在以下问题。
- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22-SNAPSHOT-c98b3cb5

### OS & Java versions

windows10、java：Alibaba_Dragonwell_17.0.1.0.1+12_x86_windows

### Plugins and Mods

```raw
插件：Authme、ProtocolLib、Vault
```

### Description

Authem插件正常载入，无任何报错，但会“形同虚设”
玩家不需要登录即可正常游玩，不需要通过登录也可以正常执行命令、进行移动
控制台无任何报错（这是最奇怪的）

### Step to reproduce

1、安装Authme、ProtocolLib、Vault
2、启动服务器
3、Authme提示载入成功
4、进入服务器，不需要登录，仍然可以正常破坏、输入命令，登录限制没有生效。

**Comment by timi137137** [comment]
1.16.5不推荐java17，请使用16 或 11
