### ISSUE TITLE
[1.16.5] EssentialX插件无法使用

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#476]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22-SNAPSHOT-c98b3cb5

### OS & Java versions

windows10、java：Alibaba_Dragonwell_17.0.1.0.1+12_x86_windows

### Plugins and Mods

```raw
插件：EssentialsX-2.19.2、EssentialsXAntiBuild-2.19.2、EssentialsXChat-2.19.2、EssentialsXSpawn-2.19.2、
ProtocolLib、Vault
```

### Description

插件载入正常，无任何报错
1、在控制台中输入/ess，能够正常使用相关命令（/ess  reload /kill等都可以正常使用）
2、**但当在游戏内输入/ess时无反应且控制台输出报错**
3、ess的其他命令、如：/tpa、、/spawn均无法正常使用

### Step to reproduce

1、安装ess插件
2、与ess相关的所有命令无法正常使用，输入命令后不执行且无反应，控制台输出报错

### Logs

完整日志：https://paste.ubuntu.com/p/49HhvdyCRf/
debuglog：https://paste.ubuntu.com/p/H4hzFkYhXp/
死亡时的报错：https://paste.ubuntu.com/p/ThwT3dDsrN/
游戏内输入命令时的报错：https://paste.ubuntu.com/p/DWdHSYVPMq/
关闭服务器时的报错：https://paste.ubuntu.com/p/ZjbpkzBmYV/

**Comment by ahdg6** [comment]
不要在 1.16 使用 java17
