### ISSUE TITLE
[1.16.x] Java 17 support & WorldEdit/FAWE

### ISSUE THREAD

**Issue by reiyooki** [IzzelAliz/Arclight#479]
As of the writing of this ticket, WorldEdit/FAWE no longer pushes/supports versions which support Java versions lower than HotSpot 17. It may still be possible to find them in their Jenkins with enough searching, but will become increasingly difficult as time goes by. This also leaves users stuck using potentially buggy releases of WorldEdit/FAWE or other plugins that require Java 17, which could result in more problems.

It would be wonderful if Arclight could natively support Java 17 and WorldEdit/FAWE itself (rather than requiring the patcher plugin) to mitigate this issue. From my understanding there should be few to no breaking changes between JDK 16 and 17.

**Comment by ahdg6** [comment]
Please do not try to use java17 on 1.16, it will break many plugins(essentials, authme and so on), just compile WorldEdit/FAWE in jdk11 by yourself.
