### ISSUE TITLE
worldedit do not work

### ISSUE THREAD

**Issue by Xray0318** [IzzelAliz/Arclight#486]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.1-SNAPSHOT

### OS & Java versions

windows 10  java 17

### Plugins and Mods

```raw
worldedit
```

### Description

worldedit do not work 
I already installed the pather plugin

**Comment by timi137137** [comment]
see FAQ

**Comment by HotoRas** [comment]
> ### Plugins and Mods
> ```
> worldedit
> ```
> 
> ### Description
> worldedit do not work I already installed the pather plugin

Load with the ArclightPatcher
If it doesn't work please re-open the issue(if you can't make a new issue) with `latest.log`
