### ISSUE TITLE
[1.18.1]参照WIKI中的FAQ升级Forge版本后无法运行服务器

### ISSUE THREAD

**Issue by 981867644** [IzzelAliz/Arclight#492]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.1-1.0.0.jar

### OS & Java versions

win10 java version "17.0.1" 2021-10-19 LTS

### Plugins and Mods

```raw
无
```

### Description

在forge官网上下载了forge-1.18.1-39.0.59-installer.jar安装包

安装server，选中服务端为路径，无报错正常安装

首先测试run.bat测试forge是否正确安装
测试完毕，无异常

按wiki提到的方法，将libraries\net\minecraftforge\forge中1.18.1-39.0.0里的unix_args.txt和win_args.txt，替换成外面新的1.18.1-39.0.59里的俩个文件。

运行start.bat，报错

### Step to reproduce

在forge官网上下载了forge-1.18.1-39.0.59-installer.jar安装包

安装server，选中服务端为路径，无报错正常安装

首先测试run.bat测试forge是否正确安装
测试完毕，无异常

按wiki提到的方法，将libraries\net\minecraftforge\forge中1.18.1-39.0.0里的unix_args.txt和win_args.txt，替换成外面新的1.18.1-39.0.59里的俩个文件。

运行start.bat，报错

### Logs

（先是闪退前的控制面板输出）
[latest.log](https://github.com/IzzelAliz/Arclight/files/8078365/latest.log)
（闪退后的crash文件）
[crash-2022-02-16_16.18.49-fml.txt](https://github.com/IzzelAliz/Arclight/files/8078133/crash-2022-02-16_16.18.49-fml.txt)

**Comment by IzzelAliz** [comment]
你可以用快照

**Comment by 981867644** [comment]
> 你可以用快照

快照指的是Forge的快照还是arclight-forge-1.18.1-1.0.0-SNAPSHOT.jar这个服务端快照？

**Comment by 981867644** [comment]
> 你可以用快照

大佬，已经试过你说的快照。服务端替换后按原步骤重复依旧报错，在替换Forge版本尝试测试时发现问题所在。39.0.0和39.0.1均可以运行，39.0.46以上则不行。从报错日志上看，arclight试图寻找Froge的jar包里的
`net/minecraftforge/server/permission/IPermissionHandler`接口
但在0.46以上，这个接口的路径已经变成了
`net/minecraftforge/server/permission/handler/IPermissionHandler`
请问如何修改这个路径？求指示

**Comment by 981867644** [comment]
> 你可以用快照

感谢大佬提示，现在找到你说的快照了，藏的有点深。已经用arclight-forge-1.18.1-1.0.1-SNAPSHOT构建服务器，默认就是39.0.59了。大佬辛苦了
