### ISSUE TITLE
插件QuickShop和模组TrashSlot存在物品复制漏洞

### ISSUE THREAD

**Issue by qyl27** [IzzelAliz/Arclight#505]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.1-1.0.1-SNAPSHOT-eb2922c5

### OS & Java versions

Windows Server 2019 openjdk version "17.0.1" 2021-10-19

### Plugins and Mods

```raw
插件：QuickShop
模组：TrashSlot
```

### Description

当QuickShop和TrashSlot同时使用时，打开QS的物品预览，对预览物品按Delete，可以转移预览窗口中的物品到垃圾桶格子里面，随后打开其他物品栏界面时，垃圾桶格子里面的东西还在。故这是个物品复制漏洞。

**Comment by IzzelAliz** [comment]
模组作者自行实现了一套移动物品代码，无法修复

如果作者写成把物品移动到垃圾格子那就能处理
