### ISSUE TITLE
RPGitem-reload插件问题（技能无法使用）

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#516]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.0.23-SNAPSHOT-fb643059-321

### OS & Java versions

windows10 x64、java：openjdk16_x64_windows

### Plugins and Mods

```raw
RPGItems-mc1.16.4-3.8-27-release（本体）
NyaaCore-mc1.16.4-8.0.21-shadowed（前置）
LangUtils-mc1.16.1-2.4.3（前置）
Vault1.7.3（前置）
RPGProject-1.3-beta（游戏内编辑器）

下载：https://app.tmp.link/index.html?tmpui_page=/room&mrid=6226e709e56e8
（包含已添加技能的rpgitem物品配置文件）
原贴：https://github.com/NyaaCat/RPGItems-reloaded
```

### Description

关于rpgitem还有一个技能兼容性的问题
为rpgitem添加技能后，无论是左键还是右键触发技能效果均无效，后台抛出错误：
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer

### Step to reproduce

1、开启服务器
2、安装插件
3、输入/RPGitem create 技能测试物品  -创建物品
4、输入/rpgui 技能测试物品  -进入编辑界面为rpgitem添加技能
5、释放技能时无效、后台报错

### Logs

https://paste.ubuntu.com/p/JV8W2RKsp5/

[latest.log]
https://paste.fastmirror.net/?b00938c38f49ac50#7fraiEiZRWRDKpcUfQ65Ywh1F8r5oDaFjLFfuqYiHKwJ

[debug.log]
https://paste.fastmirror.net/?3a6df4c9d5c06365#BTd85BitSsCVkhQfnutDUfSUgS2zyj7ywwSGqVTh5rAp

### Server pack link (Optional)

https://app.tmp.link/index.html?tmpui_page=/room&mrid=6226e709e56e8

**Comment by IzzelAliz** [comment]
请提供完整日志

**Comment by luoxiawuchen** [comment]
> 请提供完整日志

[latest.log]
https://paste.fastmirror.net/?b00938c38f49ac50#7fraiEiZRWRDKpcUfQ65Ywh1F8r5oDaFjLFfuqYiHKwJ

[debug.log]
https://paste.fastmirror.net/?3a6df4c9d5c06365#BTd85BitSsCVkhQfnutDUfSUgS2zyj7ywwSGqVTh5rAp

**Comment by IzzelAliz** [comment]
加上 `–illegal-access=permit` 参数，并且告诉插件作者升级
