### ISSUE TITLE
[FEATURE REQUEST] Option to disable Bukkit permission handler

### ISSUE THREAD

**Issue by VirusBLITZ** [IzzelAliz/Arclight#518]
The Bukkit permission handler breaks all mod-generated commands that don't support permission plugins.

Other server softwares like Magma have already implemented this into their config files, would be nice to have this option here too. :)

Thanks in advance!

**Comment by josephtarbit** [comment]
Arclight has its own Forge permission handler implementation which allows mods to integrate with Bukkit permission handlers so this shouldn’t be a problem as far as I’m aware.

**Comment by VirusBLITZ** [comment]
> Arclight has its own Forge permission handler implementation which allows mods to integrate with Bukkit permission handlers so this shouldn’t be a problem as far as I’m aware.

Doesn't this mean that mods still have to support permission configuration?
In my case the mod uses the vanilla permission tiers...
@Sm0keySa1m0n

**Comment by josephtarbit** [comment]
Vanilla permission tiers should still work as usual (there's only two - normal and OP). Mods should really be using the Forge permission API though.

**Comment by VirusBLITZ** [comment]
This is what a non-op player sees when trying to run a mod's command...
![2022-03-13_14 22 45](https://user-images.githubusercontent.com/58221423/158061486-2af711b3-feb1-4ff0-87e2-6bd2f8b21e8b.png)

**Comment by ahdg6** [comment]
all mod generated command will start with minecraft.xxx in bukkit, just add that to your permission group is OK.

**Comment by VirusBLITZ** [comment]
@ahdg6 How do I know what the name of the permission is?
Is there a way to list all commands and their permissions?

**Comment by ahdg6** [comment]
If you happen to use Luckperms then just use /lp verbose for testing.
For example, Assuming I'm using FTBTeam, then I should give player permission `minecraft.command.ftbteams`

**Comment by VirusBLITZ** [comment]
You're a life saver, this worked :)
thanks!
