### ISSUE TITLE
[CRASH] Unable to start Arclight with Sneaky Magic installed

### ISSUE THREAD

**Issue by SirOMGitsYOU** [IzzelAliz/Arclight#520]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.23-SNAPSHOT

### OS & Java versions

java version "11.0.12" 2021-07-20 LTS

### Plugins and Mods

```raw
Forge Mods:

SneakyMagic-v1.3.2-1.16.5.jar

No plugins
```

### Description

When starting my modpack with all mods including sneakymagic you crash upon launch 

### Step to reproduce

1. download arclight
2. install sneaky magic
3. run server
4. crash

### Logs

Latest.log https://pastebin.com/raw/nyBMYN9r

Debug.log https://pastebin.com/raw/CcrGyZ1W

**Comment by timi137137** [comment]
You need to filter out the most mods yourself, otherwise your problem won't be dealt with

**Comment by SirOMGitsYOU** [comment]
> You need to filter out the most mods yourself, otherwise your problem won't be dealt with

Updated, i just thought you needed a full export of all mods but it happens soley with this mod even with no other mods present sorry for the confusion

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/158164189-5219bea7-2cf3-4e70-8c18-ae61aafc307a.png)

**Comment by SirOMGitsYOU** [comment]
> ![image](https://user-images.githubusercontent.com/36812439/158164189-5219bea7-2cf3-4e70-8c18-ae61aafc307a.png)

idk why it has expired so quickly, i have added pastebin links instead

**Comment by SirOMGitsYOU** [comment]
would there be an eta on this getting fixed?

**Comment by timi137137** [comment]
If the problem is relatively simple, it will be faster, please wait patiently
