### ISSUE TITLE
[BUG] Plugins Not Working

### ISSUE THREAD

**Issue by SirOMGitsYOU** [IzzelAliz/Arclight#521]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.23-SNAPSHOT

### OS & Java versions

Java 11

### Plugins and Mods

```raw
Plugins (20): DiscordServerConsole, MiniMOTD, ArclightPatcher, LuckPerms, PlaceholderAPI, BuycraftX, Vault, ProtocolLib, WorldEdit, DecentHolograms, Essentials, LiteBans, EssentialsSpawn, WorldGuard, CoreProtect, Citizens, Skript, DiscordSRV, BetterRTP, SIR
```

### Description

When using the above plugins are loaded only "Essentials" seems to load with a green light, (Please see the picture below) I can see the plugins are generating the /<plugin_name> but then none of the commands is running seemingly generating an error message. 

![image](https://user-images.githubusercontent.com/20475516/159100967-f43bab8c-aa33-410b-ba0f-3cc141080258.png)

### Step to reproduce

1. install arclight
2. install the aforementioned plugins
3. not work

### Logs

Debug.log - https://paste.vcnet.work/JHwxRDizs3
Latest.log - https://paste.vcnet.work/X2twIFjf03

### Server pack link (Optional)

n/a

**Comment by IzzelAliz** [comment]
Maybe some mod randomly overwrite the api call to enable plugins. Please find this mod.

**Comment by SirOMGitsYOU** [comment]
> Maybe some mod randomly overwrite the api call to enable plugins. Please find this mod.

I'm not sure it is a random mod as I'm not able to get this to happen with LoliServer, Mohist or Magma only occurs when using Arclight.
