### ISSUE TITLE
[1.18.1] WorldEdit with Arclight Patcher does not work

### ISSUE THREAD

**Issue by HotoRas** [IzzelAliz/Arclight#524]
### Note after closing

This issue happened from Arclight for 1.17.1, 1.18.1, and 1.18.2.   
If you're using Arclight 1.17.1 as your server software, you should download VeroFess's binary as patcher.   
If it's 1.18+, you can either use VeroFess's one, or one attatched to my issue-closing comment.   
You don't need to install the newly patched Arclight Patcher if you're still using Arclight 1.16.5.

### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Additional requirements I've made:

- [x] I've read the FAQ

### Arclight version

arclight-1.18.1-1.0.1-e2655bb

### OS & Java versions

 openjdk version "17" 2021-09-14 LTS OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS) OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)

### Plugins and Mods

```raw
> plugins
[19:46:26 INFO] [Console]: Plugins (2): ArclightPatcher, WorldEdit
> forge mods
[19:46:28 INFO]: Mod List:
• minecraft server-1.18.1-20211210.034407-srg.jar : minecraft (1.18.1) - 1
• minecraft forge-1.18.1-39.1.2-universal.jar : forge (39.1.2) - 1
• arclight arclight-1.18.1-1.0.1-e2655bb.jar : arclight (1.18.1-1.0.1-e2655bb) - 1
>
```

### Description

On FAQ, IF ArclightPatcher(Plugin) is installed WorldEdit should work, but it doesn't work entirely on Arc 1.18 with latest WE.

On bootup:
![image](https://user-images.githubusercontent.com/34373595/159158689-a4fe01e6-ad13-4834-96fd-c3d08ac350e7.png)

On editing:
![image](https://user-images.githubusercontent.com/34373595/159158598-db192d62-2dcf-48a2-b035-e112b8a7881d.png)

### Step to reproduce

1. Install Arclight with Forge Installer in the same directory(since Arclight 1.18.1 is deprecated(*or not*) and they doesn't serve the forge installer with arc: caused an http error in my pc lol)
2. Put the latest WorldEdit-Bukkit and ArclightPatcher Loader plugins into `plugins` directory.
3. Boot the server. WE will stop operating when the server starts. (They don't be shown as RED ![image](https://user-images.githubusercontent.com/34373595/159158671-146f24d5-8fae-4d54-b661-da5aa0b51823.png) but they still throws an error)

### Logs

[forge-1.18.1-39.1.2-installer.jar.log](https://github.com/IzzelAliz/Arclight/files/8311039/forge-1.18.1-39.1.2-installer.jar.log) for the Forge Installer Log
[latest.log](https://github.com/IzzelAliz/Arclight/files/8311053/latest.log) for the Arclight Fallback Log
[mclo.gs PasteBin](https://mclo.gs/my7D1gr) for the Arclight Fallback Log with analizer(published).

**Comment by HotoRas** [comment]
The log file is directly uploaded through GitHub, so they won't expire. (However you maybe should analyze the log- so I posted the snaps too)

Triage:
> 1. Arclight Server doesn't serve Forge 1.18.1 installer JAR (HTTP 404 File Not Found). Copying the Forge Installer JAR from Arclight Redist ZIP and renaming to requested one fixed that.
> 2. Maybe you've noticed the ArclightPatcher Loader and WorldEdit both just loads and seems to be invalid. WARN by c.s.w.b.WorldEditPlugin should not be shown on the bootup log if ArclightPatcher fetches the WE successfully.
> 3. Not captured, but ArclightPatcher tries to load the libraries up to 1.16.5. Maybe updating the Patcher to 1.18 should work.

**Comment by HotoRas** [comment]
This is for updating this not to being marked as Stale.
### Additional task done before posting
- [x] Minimized the plugins and/or mods to work
- [x] Server installation is empty before launch, without mods/plugins that have tested
- [ ] ~~[WorldEdit] WE4Forge workload tested, and they just works: however their permissions doesn't load on Spigot-side.~~   
~~Tested with bukkit permission setup file. Is there other way to modify the perm settings?~~   
Found `permissons.yml` don't but just combines the perms. Lemme check with LuckPerms and then update this.

**Comment by VeroFess** [comment]
This is due to a [misjudgment](https://github.com/EngineHub/WorldEdit/blob/14ecf9320cc59b81147a12adaa13e2df1007c20a/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/adapter/Refraction.java#L40) in WorldEdit.

In Arclight environment, IS_MOJANG_MAPPED should be TRUE.

Since I lack the necessary knowledge to write a  worldedit patch, and I don't think the bug should be reported to WorldEdit, my solution for now is simply to make IS_MOJANG_MAPPED always TRUE.

If anyone needs the compiled file, it's here.

[worldedit-bukkit-7.2.11-SNAPSHOT-Patched.jar.zip](https://github.com/IzzelAliz/Arclight/files/8541974/worldedit-bukkit-7.2.11-SNAPSHOT-Patched.jar.zip)

**Comment by VeroFess** [comment]
Fixed at https://github.com/VeroFess/Arclight-Plugin-Patcher/commit/9ac70846ce0a6314ddb467110b0c815a5ed5eb51

If anyone needs the compiled file, it's here.

[patcher-loader-1.0.0.jar.zip](https://github.com/IzzelAliz/Arclight/files/8542459/patcher-loader-1.0.0.jar.zip)

You need to manually remove "{$ServerRoot}\\.arclight\patcher\definition.jar" for the update to take effect.

**Comment by HotoRas** [comment]
> Fixed at [VeroFess/Arclight-Plugin-Patcher@9ac7084](https://github.com/VeroFess/Arclight-Plugin-Patcher/commit/9ac70846ce0a6314ddb467110b0c815a5ed5eb51)

Attempting to build `arclight` in `1.18.1-forge-39.1.2` with latest code so I can check with 1.18.1-forge plugins&mods.
Already done with your version of `arclightpatcher`

**Comment by HotoRas** [comment]
Closing: fixed with updated Arclight Patcher.
[latest.log](https://github.com/IzzelAliz/Arclight/files/8546264/latest.log)
..with NO error `not fully supported`.
![image](https://user-images.githubusercontent.com/34373595/164879026-fa389cf1-7990-43d3-9750-bfd7554746ee.png)

To fix: grab the code from [here](https://github.com/VeroFess/Arclight-Plugin-Patcher), do `gradlew build`, grab jar file at `patcher-loader/build/libs`, stop the server, place it to your server's `plugins` folder, remove `.arclight/patcher` directory (you don't need to remove the entire `.arclight` directory) and then boot it all over again.

Here's the remapped patcher from source to update it to `1.18.1`: [patcher-loader-1.0.0.zip](https://github.com/IzzelAliz/Arclight/files/8546272/patcher-loader-1.0.0.zip)

**Comment by HotoRas** [comment]
Add: Here's the pre-built binary for Arclight Patcher for those for recent Arclight builds.
[1.18.1 edition](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/releases/tag/1.0.0-1.18.1) if you're using Arclight as 1.18.1.
[1.18.2 edition](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/releases/tag/1.0.0-1.18.2) if you're using Arclight as [1.18,1.19) (down to 1.18 and up to 1.18.2).
[1.19.1 edition(Bumped version)](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/releases/tag/1.0.1-1.19.1-hotfix) if you're using Arclight as 1.19.1. Didn't check if this works on [1.18,1.19), but it should NEVER work on 1.17.1 with Java 16 or up to 1.16.5 with any version of JAVA.
Check out [this](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/tree/master/README.md) for installation AND build instructions.

**Comment by timi137137** [comment]
@JeonDohyeon Maybe you could point to [patcher](https://github.com/ArclightPowered/patcher) ?

**Comment by HotoRas** [comment]
> @JeonDohyeon Maybe you could point to [patcher](https://github.com/ArclightPowered/patcher) ?

Um guys want the prebuilt ones but the thing on [patcher](https://github.com/ArclightPowered/patcher) doesn't work with latest plugin,
and from the code in [patcher](https://github.com/ArclightPowered/patcher) it'll not work on 1.17 or later.
Um and the README.md is literally *empty*.
OK I'll make a pull request containing all of the [changes](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/compare/1.0.0...1.0.1-1.19.1).

**Comment by timi137137** [comment]
> > @JeonDohyeon Maybe you could point to [patcher](https://github.com/ArclightPowered/patcher) ?
> 
> Um guys want the prebuilt ones but the thing on [patcher](https://github.com/ArclightPowered/patcher) doesn't work with latest plugin, and from the code in [patcher](https://github.com/ArclightPowered/patcher) it'll not work on 1.17 or later. Um and the README.md is literally _empty_. OK I'll make a pull request containing all of the [changes](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/compare/1.0.0...1.0.1-1.19.1).

hh, We are investigating the feasibility of built-in Patcher, so we don't manage this library at the moment, you can open another branch for temporary use

**Comment by HotoRas** [comment]
> > > @JeonDohyeon Maybe you could point to [patcher](https://github.com/ArclightPowered/patcher) ?
> > 
> > 
> > Um guys want the prebuilt ones but the thing on [patcher](https://github.com/ArclightPowered/patcher) doesn't work with latest plugin, and from the code in [patcher](https://github.com/ArclightPowered/patcher) it'll not work on 1.17 or later. Um and the README.md is literally _empty_. OK I'll make a pull request containing all of the [changes](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/compare/1.0.0...1.0.1-1.19.1).
> 
> hh, We are investigating the feasibility of built-in Patcher, so we don't manage this library at the moment, you can open another branch for temporary use

Got it, but I gonna still open it anyway since there's so many asks updating the repo. (Fixes issue 3, 5, 7 on patcher)

**Comment by timi137137** [comment]
> > > > @JeonDohyeon Maybe you could point to [patcher](https://github.com/ArclightPowered/patcher) ?
> > > 
> > > 
> > > Um guys want the prebuilt ones but the thing on [patcher](https://github.com/ArclightPowered/patcher) doesn't work with latest plugin, and from the code in [patcher](https://github.com/ArclightPowered/patcher) it'll not work on 1.17 or later. Um and the README.md is literally _empty_. OK I'll make a pull request containing all of the [changes](https://github.com/GooruemOnline/Arclight-Plugin-Patcher/compare/1.0.0...1.0.1-1.19.1).
> > 
> > 
> > hh, We are investigating the feasibility of built-in Patcher, so we don't manage this library at the moment, you can open another branch for temporary use
> 
> Got it, but I gonna still open it anyway since there's so many asks updating the repo. (Fixes issue 3, 5, 7 on patcher)

OK， not problem

**Comment by HotoRas** [comment]
Update: the old repo is removed, and I've moved the code to [here](https://github.com/JeonDohyeon/arclightpatcher-worldedit). Since of it, the prebuilt binary has also removed.
This is already announced on Discord, but maybe I should announce it here too, so I'm writing this comment.

Note that since of the next release for 1.18 and up, this plugin is not required because it's already included in the code.
This repo is preserved to keep support to discontinued builds of Arclight.

For 1.16, you can still use the build by VeroFess up here.

**Comment by HotoRas** [comment]
Update: I built a final build of the patcher. This is from my repository, which will NOT be managed anymore.
[**1.16.5** release](https://github.com/JeonDohyeon/arclightpatcher-worldedit/releases/tag/v1.0.1-1.16.5)
[**1.18.2** release](https://github.com/JeonDohyeon/arclightpatcher-worldedit/releases/tag/v1.0.1-1.18.2)

Left task:
- [x] Build the pre-built jar package with `./gradlew clean build jar`
- [x] Archive the repository
