### ISSUE TITLE
gradlew build构建后在build目录下找不到任何arclight的jar文件

### ISSUE THREAD

**Issue by heipiao233** [IzzelAliz/Arclight#526]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Code

### OS & Java versions

openjdk version "17.0.2" 2022-01-18 LTS

### Plugins and Mods

```raw
/
```

### Description

gradlew build构建后在build目录下找不到任何arclight的jar文件

### Step to reproduce

1.克隆源码
2.运行./gradlew build
3.打开build目录

**Comment by timi137137** [comment]
查看wiki https://github.com/IzzelAliz/Arclight/wiki/Contributing#for-developers
并检测是否有报错，没有任何详细步骤或图片无法处理。

**Comment by heipiao233** [comment]
没有任何报错，jar文件只出现于子项目下

**Comment by timi137137** [comment]
使用此命令打包 ./gradlew build collect 然后jar在build\libs下
