### ISSUE TITLE
SaberFactions spamming the console whenever anything is interacted with using modded items.

### ISSUE THREAD

**Issue by ItzPear** [IzzelAliz/Arclight#527]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0,22

### OS & Java versions

I do not have access to the OS, Java Version: RedHat 8u312

### Plugins and Mods

```raw
Plugins (15): ForcePack, InventoryRollback, LuckPerms, CraftEnhance, SimpleRename, WorldBorder, Vault, WorldEdit, Essentials, WorldGuard, CoreProtect, Factions, TradeSystem, BanItem, GSit

• mods_folder Dynmap-3.3.2-forge-1.16.5.jar : dynmap (3.3.2-696) - 1
• mods_folder Craftable+Horse+Armour++Saddle-1.16.5-1.7--Forge.jar : craftablehorsearmour (1.7) - 1
• mods_folder smallships-1.16.5-1.10.1.jar : smallships (1.10.1) - 1
• mods_folder smallships-1.16.5-1.10.1.jar : smallships (1.10.1) - 1
• mods_folder Dynmap-3.3.2-forge-1.16.5.jar : dynmap (3.3.2-696) - 1
• mods_folder Craftable+Horse+Armour++Saddle-1.16.5-1.7--Forge.jar : craftablehorsearmour (1.7) - 1
• mods_folder wolveswitharmor-1.1.0-1.16.2.jar : wolveswitharmor (1.1.0) - 1
• maven_libs forge-1.16.5-36.2.26-universal.jar : forge (36.2.26) - 1
• mods_folder wolveswitharmor-1.1.0-1.16.2.jar : wolveswitharmor (1.1.0) - 1
• mods_folder SpartanShields-1.16.5-2.1.2.jar : spartanshields (2.1.2) - 1
• mods_folder SpartanWeaponry-1.16.4-2.1.0-beta-4.jar : spartanweaponry (2.1.0 beta 4) - 1
• maven_libs forge-1.16.5-36.2.26-universal.jar : forge (36.2.26) - 1
• mods_folder BetterHorseArmor-1.16.3-1.0.1.1.jar : betterhorsearmor (1.16.3-1.0.1.1) - 1
• mods_folder SpartanShields-1.16.5-2.1.2.jar : spartanshields (2.1.2) - 1
• arclight arclight-forge-1.16.5-1.0.22.jar : arclight (1.16.5-1.0.22-3ca639a6) - 1
• mods_folder BetterHorseArmor-1.16.3-1.0.1.1.jar : betterhorsearmor (1.16.3-1.0.1.1) - 1
• mods_folder SpartanWeaponry-1.16.4-2.1.0-beta-4.jar : spartanweaponry (2.1.0 beta 4) - 1
• arclight arclight-forge-1.16.5-1.0.22.jar : arclight (1.16.5-1.0.22-3ca639a6) - 1
```

### Description

On arclight-1.16.5-1.0,22. whenever you interact with anything other then a block with SaberFactions installed using a modded item, it spams the console with 

[18:58:24] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to Factions v1.6.9.5-3.0.1-RC
org.bukkit.event.EventException: null

and them more information about classloading or something along the lines of that.
This allows the bypass of permissions that would normally work involving the opening of chests, doors, trapdoors, and more inside other players claimed faction territory.

### Step to reproduce

1. Install Arclight as usual for 1.16
2. Put SaberFactions into the plugins folder
3. Use any mod that adds items
4. Make a faction and claim somewhere
5. Place a door
6. Open the door while holding a modded item and the console will be spammed (This also allows people to bypass other faction permissions to steal from chests, open doors, etc.)
7. The console will start spewing errors.

### Logs

https://paste.ubuntu.com/p/2DrdhbxYFJ/

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/arnadcraft

**Comment by HotoRas** [comment]
Java version of yours is RedHat 8u312, checked in the logs.

**Comment by ItzPear** [comment]
I updated it.
