### ISSUE TITLE
1.18.2 沙子重力异常或碰撞箱异常

### ISSUE THREAD

**Issue by xlive2233** [IzzelAliz/Arclight#529]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 arclight-1.18.2-1.0.2-SNAPSHOT-5fba8c1

### OS & Java versions

系统：windows server 2019 java： java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### Plugins and Mods

```raw
Plugins (1): WhiteList

[09:59:05 INFO]: Mod List:
• minecraft server-1.18.2-20220228.144236-srg.jar : minecraft (1.18.2) - 1
• mods_folder 背包useful_backpacks-1.18.2-1.12.1.93.jar : usefulbackpacks (1.12.1.93) - 1
• mods_folder 更好的服务器兼容性显示BetterCompatibilityChecker-1.1.13-build.25+mc1.18.2.jar : bcc (1.1.13-build.25+mc1.18.2) - 1
• mods_folder SkinnedCarts-1.18.2-1.1.1动物矿车.jar : skinnedcarts (1.1.1) - 1
• mods_folder 箱子expandedstorage-7.3.11+1.18.2.jar : expandedstorage (7.3.11) - 1
• mods_folder 简单睡觉EasierSleeping-1.18.2-2.1.0.jar : easier_sleeping (2.1.0) - 1
• mods_folder 背包前置u_team_core-1.18.2-4.0.0.204.jar : uteamcore (4.0.0.204) - 1
• mods_folder Jade-1.18.2-5.0.1.jar : jade (5.0.1) - 2
• mods_folder 家具cfm-7.0.0-pre29-1.18.2.jar : cfm (7.0.0-pre29) - 1
• mods_folder ferritecore-4.2.0-forge.jar : ferritecore (4.2.0) - 1
• arclight arclight-1.18.2-1.0.2-SNAPSHOT-5fba8c1.jar : arclight (1.18.2-1.0.2-SNAPSHOT-5fba8c1) - 1
• mods_folder jei-1.18.2-9.5.3.143.jar : jei (9.5.2.136) - 1
• mods_folder 箱子前置ninjaphenix-container-library-1.3.0+1.18-forge.jar : ninjaphenix_container_lib (1.3.0) - 1
• minecraft forge-1.18.2-40.0.24-universal.jar : forge (40.0.24) - 1
• mods_folder 飞行前置古玩api curios-forge-1.18.2-5.0.6.3.jar : curios (1.18.2-5.0.6.3) - 1
• mods_folder 飞行戒指angelring-1.18.2-1.5.0.jar : angelring (1.5.0) - 1
• mods_folder 隐藏盔甲CosmeticArmorReworked-1.18.2-v1.jar : cosmeticarmorreworked (1.18.2-v1) - 1
• mods_folder 墓碑gravestone-1.18.2-1.0.1.jar : gravestone (1.18.2-1.0.1) - 1
```

### Description

混泥土粉末复制机/刷沙机无法正常使用。
该问题在原版，forge，spigot未出现
已排除刷沙机本身问题。 无特殊日志显示相关错误

### Step to reproduce

1.启动游戏进入服务器，在混泥土粉末复制机/刷沙机放置需要刷的混泥土粉末
2.打开刷沙机开关，无法正常工作。

### Logs

https://paste.ubuntu.com/p/XWfhDQ5SCh/

### Server pack link (Optional)

arclight错误视频：https://xlive2233.lanzouj.com/iOOEK024bv0j
forge原版视频：
https://xlive2233.lanzouj.com/itC6q024dtqf

**Comment by 848244210** [comment]
猜测可能是沙子混泥土粉末的动量变低了，就是同样的粘液块弹射，弹不到那么远了，不知道是不是因为服务端引用了paper的库。

**Comment by xlive2233** [comment]
请求修复

**Comment by IzzelAliz** [comment]
在 03aa8d5f4b99ce21ef417f5e265cf29ab0ea1486 中修复
