### ISSUE TITLE
Farther View Distance plugin 9.1.2 Kindly take a look! [1.18.2]

### ISSUE THREAD

**Issue by DonorKrovi** [IzzelAliz/Arclight#531]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.2-SNAPSHOT

### OS & Java versions

17 java

### Plugins and Mods

```raw
[21:03:32 INFO] [Console]: Plugins (18): LuckPerms, PistonMOTD, FartherViewDistance, Vault, MobHeads, ProtocolLib, Chatty, Citizens, iShop, Pl-Hide-Pro, AntiCombatLog, TabList, InteractionVisualizer, eco, EcoSkills, EcoEnchants, CMILib, CMI

[21:04:05 INFO]: Mod List: 
? minecraft server-1.18.2-20220228.144236-srg.jar : minecraft (1.18.2) - 1
? mods_folder smoothchunk-1.18.1-1.6.jar : smoothchunk (1.18.1-1.6) - 1
? mods_folder lazydfu-1.0-1.18.jar : lazydfu (0.1.3) - 1
? mods_folder starlight-1.0.2+forge.546ae87.jar : starlight (1.0.2+forge.83663de) - 1
? mods_folder ferritecore-4.2.0-forge.jar : ferritecore (4.2.0) - 1
? mods_folder AI-Improvements-1.18-0.4.0.jar : aiimprovements (0.4.0) - 1
? arclight arclight-1.18.2-1.0.2-SNAPSHOT-7e71fd1.jar : arclight (1.18.2-1.0.2-SNAPSHOT-7e71fd1) - 1
? mods_folder mia-login.jar : simplelogin (1.3.1) - 1
? minecraft forge-1.18.2-40.0.12-universal.jar : forge (40.0.12) - 1
? mods_folder selene-1.18.2-1.14.1.jar : selene (1.18.2-1.14.1) - 1
? mods_folder supplementaries-1.18.2-1.3.2.jar : supplementaries (1.18.2-1.3.2) - 1
? mods_folder citadel-1.11.1-1.18.2.jar : citadel (1.11.1) - 1
? mods_folder locallooks-1.2.1-1.18.2.jar : locallooks (1.2.1) - 1
? mods_folder alexsmobs-1.17.5.jar : alexsmobs (1.17.5) - 1
```

### Description

This plugin should draw already visited chunks of players but it does not work correctly on your core, it is very useful and can well optimize the server for playing with a large number of players

### Step to reproduce

Install Farther View Distance plugin

Join server and see console warn
Exit server and set 
- Server under spigot (bukkit), plugin's config.yml **server-tick-max-generate-amount** to **0** and **read-server-loaded-chunk** to **false**
- Minecraft version updated, need use --forceUpgrade in startup script

### Logs

https://paste.loliidc.cn/?d57b7fd8b334bf09#4AXoNXH48wGNnHAmLHi92jSgoFdafSGfyhWhgTBHvm2a

**Comment by IzzelAliz** [comment]
This plugin uses a Paper specific minecraft internal (PalettedContainer.codec with an additional parameter) therefore cannot be fixed on our side.

You can inform the developer of this plugin that it is not able to use in Spigot.
