### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by heipiao233** [IzzelAliz/Arclight#535]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.2-SNAPSHOT-5fba8c1e

### Java 版本 | 操作系统

openjdk version "17.0.2" 2022-01-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

启动后崩溃（未弹出gui）

### 报错信息

[日志](https://paste.ubuntu.com/p/d2Z4c255wB/)

**Comment by timi137137** [comment]
请尝试清空所有文件，然后重新安装再试

**Comment by heipiao233** [comment]
解决了👍

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年3月29日 13:58
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [IzzelAliz/Arclight] 无法启动 (Issue #535)


请尝试清空所有文件，然后重新安装再试
