### ISSUE TITLE
Update forge lol

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#537]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.2-SNAPSHOT

### OS & Java versions

OS: Win 10. Java 17

### Plugins and Mods

```raw
Forge
```

### Description

Update

**Comment by timi137137** [comment]
pls read FAQ
