### ISSUE TITLE
archlight 1.15 performant模组无法加载

### ISSUE THREAD

**Issue by PA733** [IzzelAliz/Arclight#54]
### 我正在运行

* **Arclight** [arclight-1.15.2-1.0.9-SNAPSHOT-ce1dd81]（ohhhh终于显示版本号了）

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** [1.8.0_261]

* **操作系统** [windows server 2019 datacenter]

* **插件列表** 
无

* **Mod 列表** 
MixinBootstrap-1.0.3
performant-1.15-3.11

### 错误描述

开服过程中崩溃

### 重现步骤

1. 装载mod后开服

**可在 Forge 复现** 否

**可在 Spigot 复现** 否

### 报错信息

[latest.log](https://paste.ubuntu.com/p/sDvv97DdjB/)

**Comment by IzzelAliz** [comment]
暂时不考虑对优化模组的兼容
