### ISSUE TITLE
[1.16.5-1.0.22] Forge permissions aren't listened

### ISSUE THREAD

**Issue by Rasgnarok** [IzzelAliz/Arclight#540]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22.jar

### OS & Java versions

jdk-15.0.2_linux-x64, CentOS

### Plugins and Mods

```raw
N/A
```

### Description

Forge mod commands are not registering Spigot-side. Luckperms is unable to distribute permissions, and commands are not registered without OP.

### Step to reproduce

TEST 1
1. Install arclight-forge-1.16.5-1.0.22.jar, LuckPerms-Bukkit-5.4.9.jar and worldedit-mod-7.2.5-dist.jar.
2. Run `/lp user YOURNAME perm set *` or `/lp user YOURNAME perm set worldedit`.
3. Run `//wand`.
EXPECTED: Forge's WE wooden_axe appears in hand with chat command feedback.
RESULT: Command not recognized.

-----

TEST 2
1. Install arclight-forge-1.16.5-1.0.22.jar, LuckPerms-Bukkit-5.4.9.jar and worldedit-mod-7.2.5-dist.jar.
2. Run `/op YOURNAME`.
3. Run `//wand`.
EXPECTED: Forge's WE wooden_axe appears in hand with chat command feedback.
RESULT: Forge's WE wooden_axe appears in hand with chat command feedback.

### Logs

N/A

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/161339428-e5963d93-c6ba-49de-9275-375de86e9b97.png)
It's really that simple

**Comment by IzzelAliz** [comment]
Can you test again with `/lp verbose`?

**Comment by Rasgnarok** [comment]
Closing,  https://github.com/EngineHub/WorldEdit/blob/archive/1.16.5/worldedit-forge/src/main/java/com/sk89q/worldedit/forge/ForgePermissionsProvider.java#L40.
