### ISSUE TITLE
libsdisguises plugin crshers server 1.18.2

### ISSUE THREAD

**Issue by tindin** [IzzelAliz/Arclight#542]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.2

### OS & Java versions

java 17

### Plugins and Mods

```raw
LuckPerms, AggressiveAnimals, PlaceholderAPI, DeadSouls, HolographicDisplays, ProtocolLib, NoMobLag, sleep-most, SwingThroughGrass, NBTAPI, Vault, dynmap, WorldEdit, Chunky, Essentials, Towny, EmployMe, WorldGuard, TownyChat, DiscordSRV, EssentialsChat, GSit, ChestShop, ChestShop-towny, CMILib, MythicLib, Jobs, BetonQuest, MythicMobs, MMOCore, ModelEngine
```

### Description

with libsdisguises installed when you go up to a mob that has been scripted with it it crashes

### Step to reproduce

run server with a LibsDisguises mob

### Logs

https://pastebin.com/TUPgJntT

**Comment by timi137137** [comment]
i can't find libsdisguises in Plugins and Mods List,i can't find libsdisguises in  log too

**Comment by tindin** [comment]
thats because it toke it out so i could run the server.

**Comment by timi137137** [comment]
Are you kidding me? How am I supposed to find out what the problem is if you don't run it??

**Comment by tindin** [comment]
the log is with it in

**Comment by timi137137** [comment]
i can't find it

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/162118288-3d8c0898-2502-49ba-aff8-5d2e2646b044.png)

**Comment by tindin** [comment]
ok i'll go redo it sorry for the trouble
