### ISSUE TITLE
libsdisguises plugin crshers server 1.18.2

### ISSUE THREAD

**Issue by tindin** [IzzelAliz/Arclight#543]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.2

### OS & Java versions

java 17

### Plugins and Mods

```raw
LuckPerms, AggressiveAnimals, PlaceholderAPI, DeadSouls, HolographicDisplays, ProtocolLib, LibsDisguises, NoMobLag, sleep-most, SwingThroughGrass, NBTAPI, Vault, dynmap, WorldEdit, Chunky, Essentials, Towny, EmployMe, WorldGuard, TownyChat, DiscordSRV, EssentialsChat, GSit, ChestShop, ChestShop-towny, CMILib, MythicLib, Jobs, BetonQuest, MythicMobs, MMOCore, ModelEngine
```

### Description

with LibsDisguises installed when you go up to a mob that has been scripted with it it crashes

### Step to reproduce

run server with LibsDisguises and go to a mob that has it coded to be disguised

### Logs

https://pastebin.com/gM4jMbG2

**Comment by SunnyMenkov** [comment]
also LibsDisguises don't work on 1.16
