### ISSUE TITLE
模组：OpenTerrainGenerator（开放地形生成器）不兼容，启动后服务端崩溃

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#545]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.23-SNAPSHOT-02418595

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
[开放地形生成器]OpenTerrainGenerator-1.16.5-0.1.10.jar

相关链接：
mc百科：https://www.mcmod.cn/class/1397.html
curseforge：https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator
```

### 错误描述

（OTG）OpenTerrainGenerator是一个可以自定义世界地形、结构的生成器模组

安装最新版本启动服务器，服务器关闭，弹出崩溃报告

### 复现步骤

1、安装OTG
2、启动服务端
3、服务端崩溃

### 报错信息

崩溃日志：
https://paste.ubuntu.com/p/g77BmYffJr/

latest.log：
https://paste.ubuntu.com/p/CK5SshCQsR/

debug.log：
https://paste.ubuntu.com/p/9M5kMV5wMT/

**Comment by timi137137** [comment]
能否试试在1.18能否复现

**Comment by luoxiawuchen** [comment]
> 能否试试在1.18能否复现

好，我会一同测试，不过OTG1.18还处在不稳定的开发版本（而且是1.18.1）

**Comment by luoxiawuchen** [comment]
> 能否试试在1.18能否复现

无法启动，但不是弧光的问题，1.18.1模组无法用于1.18.2版本

**Comment by timi137137** [comment]
> > 能否试试在1.18能否复现
> 
> 无法启动，但不是弧光的问题，1.18.1模组无法用于1.18.2版本

好的没问题
