### ISSUE TITLE
1.18.2 - 龙蛋无法交互

### ISSUE THREAD

**Issue by Jissee** [IzzelAliz/Arclight#546]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.3-SNAPSHOT-03aa8d5f

### Java 版本 | 操作系统

java version "17.0.1" 2021-10-19 LTS Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39) Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing); Windows Server 2019 Datacenter

### 相关 Mod/插件 的名称及版本

```raw
无模组
无插件
```

### 错误描述

在游戏中无法右单击交互龙蛋，使之移动到他处。但是用活塞等方法可以移动。

### 复现步骤

1.下载最新版本的服务端，运行并填写eula；
2.客户端连接服务端后使用命令/give <玩家> dragon_egg，并放在地上；
3.右单击龙蛋，龙蛋没有交互反应，服务端有错误提示，但没有崩溃；
4.服务端没有安装任何模组或插件，并且在纯模组和纯插件服务端中测试均没有发生此问题。

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/8448440/latest.log)

**Comment by TIT-0** [comment]
我也出现了同样的问题，但当使用run.sh脚本启动服务端时，与龙蛋的交互一切正常。
使用java -jar arclight-forge-<mc>-<version>.jar nogui命令启动服务端时，就会出现这个错误。
希望能提供到一些解决的思路。
