### ISSUE TITLE
[1.16.5] CustomNPC inventories not functional 

### ISSUE THREAD

**Issue by GodMorduk** [IzzelAliz/Arclight#549]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.22-3ca639a6

### OS & Java versions

Java 11, doesn't seem to be related

### Plugins and Mods

Others mods are doesn't seem to matter, it works with full modpack in singleplayer, but doesn't work in multiplayer with Arclight.

edit: Tested it on a clean client with only customnpc and server only with arclight and customnpc, and issue remains, so its purely a arclight-only issue.

### Description

Everything in CustomNPC related to inventories are not working. You cannot open tab with NPC's inventory or edit bank/trader role properties. 

tested with 1.16.5 snaphot and result was same

### Step to reproduce

1. Install Arclight.
2. Install CustomNPCs-1.16.5.20220330snapshot.jar (latest from Noppes discord server)
3. Spawn a NPC using npc wand
4. Right-click NPC with that wand, get into NPC menu
5. Try to open inventory tab - nothing happens. In singleplayer it does open NPC inventory. 

### Logs

Nothing, really. But there is related (as it seems) info in customnpc-latest
https://pastebin.com/RH1PDqH0

**Comment by timi137137** [comment]
well, i need full log,maybe you can upload?

**Comment by GodMorduk** [comment]
Send logs to IzzelAliz discord PM with his permission.

**Comment by timi137137** [comment]
We do not accept PM in any form

**Comment by timi137137** [comment]
Non-github bug reports will not necessarily be handled

**Comment by GodMorduk** [comment]
Well, fine, I cleaned most of private info, here you go:

here is something interesting I found with verbose, might be the case. It happens then I click on NPC inventory tab
https://pastebin.com/LaMT7Si7

there is full debug.log of an empty server (only Arclight + CustomNPC)
https://pastebin.com/8j7NnBb4

If there is anything else I can provide, please name it.
