### ISSUE TITLE
死亡掉落问题

### ISSUE THREAD

**Issue by chiakge** [IzzelAliz/Arclight#55]
### 我正在运行

* **Arclight** [arclight-1.15.2-1.0.11-SNAPSHOT-ca83918] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [jre 261] 

* **操作系统** [Debian9]

* **插件列表** 
无
* **Mod 列表** 
墓碑GraveStone

### 错误描述
死亡后，不生成墓碑，类似mod均不可以正常工作

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

**Comment by PA733** [comment]
补充
类似的插件比如deathchest也不起作用

**Comment by IzzelAliz** [comment]
请测试问题是否解决

**Comment by PA733** [comment]
deathchest虽然已能生成箱子，但是箱子内没有任何掉落物（换句话来说，玩家的掉落物在死亡后消失了）
此处所指的deathchest可在
https://www.spigotmc.org/resources/deathchest.75186/
下载
