### ISSUE TITLE
citizens插件出现严重报错，导致崩服

### ISSUE THREAD

**Issue by thenobleofdragon** [IzzelAliz/Arclight#550]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [ ] 已为所有插件及模组安装依赖
- [ ] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.1-1.0.1

### Java 版本 | 操作系统

java17

### 相关 Mod/插件 的名称及版本

```raw
插件：Citizens-2.0.29-b2461；ProtocolLib-4.7.0
```

### 错误描述

加载citizens插件后，服务器加载
时出现关于NMS的错误提示，显示无法找到相应方法和字段。如下图所示。在创建npc后（/npc create 1）.出现大段报错，随后服务器崩溃
![相关图片](https://user-images.githubusercontent.com/103400314/162662805-77e50894-5e1b-4cb5-bc7f-5cc95cc5ce9d.png)
。

### 复现步骤

1安装citizens2
2进入服务器创建npc（/npc create 1）
3服务器崩溃

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/8460927/latest.log)

**Comment by VeroFess** [comment]
这里有一些临时的修补措施，不过很显然，我并不能在这里放出一个收费插件的成品，所以我提供了被修补过的类文件，你需要将它们覆盖到购买的jar中。

如果想知道我具体修改了什么，压缩包里同时包含了patch文件。

-----

Here are some temporary fixes. It is clear that I can't attach the plugin that needs pay, so I provides some patched class file, you need to overwrite them to the purchased JAR.

If you want to know what I have modified, the Patch file is also included in the compressed package.

-----

[Citizens_Temporary_Patch.zip](https://github.com/IzzelAliz/Arclight/files/8549197/Citizens_Temporary_Patch.zip)

**Comment by VeroFess** [comment]
Thanks to the Citizens authors for allowing me to create a fork and distribute the jar file. try https://github.com/VeroFess/Citizens2-For-Arclight/releases

**Comment by thenobleofdragon** [comment]
thanks for your help
