### ISSUE TITLE
[1.16.5] Roadrunner Incompatibility

### ISSUE THREAD

**Issue by SunnyMenkov** [IzzelAliz/Arclight#554]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22.jar

### OS & Java versions

11.0.12

### Plugins and Mods

```raw
Roadrunner
0 plugins
```

### Description

Server doesn't launch with Roadrunner installed.
Without it, everything is ok.
Also, on the Roadrunner page i read that it works if world is new, but not with old world https://github.com/MaxNeedsSnacks/roadrunner/issues/20

### Step to reproduce

1. Install Roadrunner https://www.curseforge.com/minecraft/mc-mods/roadrunner
2. Install Arclight
3. Launch server
4. crash!

### Logs

[crash-2022-04-13_20.33.14-server.txt](https://github.com/IzzelAliz/Arclight/files/8484951/crash-2022-04-13_20.33.14-server.txt)
[2022-04-13-1.log](https://github.com/IzzelAliz/Arclight/files/8484975/2022-04-13-1.log)

**Comment by Rishum-P** [comment]
In your RoadRunner config folder edit rules.properties and add:
```
mixin.ai.goal=false
mixin.collections=false
mixin.ai.poi.fast_retrieval=false
mixin.ai.nearby_entity_tracking.goals=false
mixin.ai.task=false
```
Disabling these on my network has fixed any issues with running RoadRunner. It might work for you.

If it doesnt, you can also try (via some trial an error) disabling certain rules till you find which one is causing the issue: https://github.com/MaxNeedsSnacks/roadrunner/wiki/Configuration-Files

**Comment by IzzelAliz** [comment]
This kind of optimization mods are not supported.
