### ISSUE TITLE
Forge Update to 40.0.44

### ISSUE THREAD

**Issue by fantahund** [IzzelAliz/Arclight#555]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2

### OS & Java versions

Linux

### Plugins and Mods

```raw
---
```

### Description

Pls Update forge to Version 40.0.44 i need this version for a mod ^^

**Comment by fantahund** [comment]
So at least 40.0.44 the current 40.0.52 probably makes more sense :D

**Comment by GodMorduk** [comment]
![image](https://user-images.githubusercontent.com/22483969/163468850-ad41bc12-b777-4b35-bc41-19f551f8196e.png)

https://github.com/IzzelAliz/Arclight/wiki/FAQ

There is info in FAQ how can you use a custom version.

**Comment by fantahund** [comment]
ohh ok thx ^^

**Comment by fantahund** [comment]
Actually, I'm not that stupid when it comes to this kind of thing. And I have also asked someone else. But with me the forge version is overwritten again and again with the 40.0.12. :(

**Comment by HotoRas** [comment]
Maybe you should "replace" the jar file, with setting up the name of the jar with same as default what Arclight uses.

**Comment by fantahund** [comment]
None of it worked. Have me now built the server itself with the right Forge version. But thanks for the effort ^
