### ISSUE TITLE
[1.16.5] Vulcan + Arclight NPE on player death respawn

### ISSUE THREAD

**Issue by Rasgnarok** [IzzelAliz/Arclight#556]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22.jar

### OS & Java versions

CentOS, jdk-11.0.13

### Plugins and Mods

```raw
arclight, forge 36.2.26, vulcan
```

### Description

NPE

### Step to reproduce

1. Install Vulcan-2.6.3.jar
2. /kill Rasgnarok (or die normally)
3. Expected: normal post-death respawn. Result: player stuck on respawn point in 3rd person, unable to use chat. Client can't reconnect if disconnected from that state.

### Logs

![image](https://user-images.githubusercontent.com/18584380/163691843-4d5e0cfd-b055-49e0-b766-9c423bc15d4a.png)

**Comment by timi137137** [comment]
Please upload files instead of screenshots

**Comment by IzzelAliz** [comment]
Already fixed in b6fca26e6303eb9966446949edfaf3da57a26de1
