### ISSUE TITLE
不兼容重置trchat的自定义聊天信息框

### ISSUE THREAD

**Issue by SpicyFishOuO** [IzzelAliz/Arclight#557]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.23-SNAPSHOT-4b9ed1db

### Java 版本 | 操作系统

系统 windows 10  java version "16.0.1" 2021-04-20 Java(TM) SE Runtime Environment (build 16.0.1+9-24) Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
Mod List:
• minecraft forge-1.16.5-36.2.26-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.2.26-universal.jar : forge (36.2.26) - 1
• arclight arclight-forge-1.16.5-1.0.23-SNAPSHOT.jar : arclight (1.16.5-1.0.23-SNAPSHOT-4b9ed1db) - 1
Plugins (10): Yum, LuckPerms, Vault, PlaceholderAPI, ProtocolLib, TrChat, PlayerParticles, PlayerTitle,
```

### 错误描述

不兼容重置的trchat自定义前缀的聊天信息框
只有%player_name%的可以显示其他的都不显示/不兼容
以下是
在arclight运行的截图
https://sm.ms/image/sJNv91iTerHxl8j
https://sm.ms/image/sIVwYpFe5cqvkjQ
第二张图已经移到world的位置了截图显示不出赖
以下是在paper运行的截图
https://sm.ms/image/MjUH6ixsADCQFto

### 复现步骤

1.安装插件以及前置
2.开服
3.打字以后鼠标移动到 world 跟 玩家名上
只有玩家名聊天信息框 world上面不显示
4.换成paper端就正常显示了

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/8501157/latest.log)

### 复现用压缩包下载链接(可选)

https://pan.baidu.com/s/1w9WNqC4kfl_9sX9DIHY84Q?pwd=10y8  提取码：10y8

**Comment by timi137137** [comment]
请尝试1.18中是否能复现该问题

**Comment by SpicyFishOuO** [comment]
> 请尝试1.18中是否能复现该问题

已测试，还是一样不显示聊天框信息展示
视频网盘：
链接：https://pan.baidu.com/s/1lmTkKnfilsRGD30h1Z74xw?pwd=xbg0 
提取码：xbg0

**Comment by IzzelAliz** [comment]
反正修好了

**Comment by SpicyFishOuO** [comment]
然而并不是arclight修复的，是trchat修复版的作者修复的，trchat-2.0.0-PRE-5版本于三天前发布修复了该BUG，而且是在我没有反馈给他过这个问题的情况下！
