### ISSUE TITLE
java17.0.2版本无法启动，但是17.0.1版本可以

### ISSUE THREAD

**Issue by NullFlower** [IzzelAliz/Arclight#560]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.21

### OS & Java versions

windows10 java17.0.2

### Plugins and Mods

```raw
没有任何
```

### Description

17.0.2无法启动，17.0.1可以

### Step to reproduce

使用java17.0.2启动服务端即可

### Logs

[2022-04-18-6.log](https://github.com/IzzelAliz/Arclight/files/8503725/2022-04-18-6.log)

**Comment by timi137137** [comment]
MC官方推荐以及Arclight推荐使用的java是 java 16，java17中运行出现问题将不会处理
