### ISSUE TITLE
1.16 Quark Oddities backpack crafting bug

### ISSUE THREAD

**Issue by SunnyMenkov** [IzzelAliz/Arclight#561]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.22.jar

### OS & Java versions

1.8.0_311

### Plugins and Mods

```raw
Quark
Quark Oddities
0 plugins
```

### Description

Quark backpack breaks inventory 2x2 crafting.
Crafting doesn't work, and things are destroyed, works fine without arclight

https://user-images.githubusercontent.com/51756078/163788861-fee5af85-355f-4623-be79-71642bd00c38.mp4

### Step to reproduce

1. Install quark, quark oddities
2. Equip backpack
3. 2x2 Crafting doesn't work, and things are destroye

https://user-images.githubusercontent.com/51756078/163788736-3c1c610b-991b-41b5-9d6d-60486e5440cb.mp4

d

**Comment by IzzelAliz** [comment]
Please test this on latest dev build.

**Comment by SunnyMenkov** [comment]
> Please test this on latest dev build.

where i can find it?

**Comment by SpicyFishOuO** [comment]
> 

构建站（开发版本）
1.18 [https://ci.appveyor.com/project/IzzelAliz/arclight-18/build/artifacts](https://www.mcbbs.net/plugin.php?id=link_redirect&target=https%3A%2F%2Fci.appveyor.com%2Fproject%2FIzzelAliz%2Farclight-18%2Fbuild%2Fartifacts)
1.16 [https://ci.appveyor.com/project/ ... -16/build/artifacts](https://www.mcbbs.net/plugin.php?id=link_redirect&target=https%3A%2F%2Fci.appveyor.com%2Fproject%2FIzzelAliz%2Farclight-16%2Fbuild%2Fartifacts)

**Comment by zVfrc** [comment]
arclight-forge-1.18.2-1.0.3-SNAPSHOT.jar 

+ Quark-3.2-349.jar
+ QuarkOddities-1.18.jar
+ AutoRegLib-1.7-53.jar

work good!
(did not check for 1.16)

**Comment by SunnyMenkov** [comment]
tried on dev build, the problem is still there.
