### ISSUE TITLE
[Platform Request] Fabric Loader

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [IzzelAliz/Arclight#562]
Heya, Arclight seems like a cool project, and I'm wondering if a Fabric platform would be made for it? As Fabric is quite a big modding platform now, but it lacks heavily in terms of serverside mod alternatives.

I have considered using [Cardboard](https://cardboardpowered.org/) before, but it is quite flimsy and not the best implementation at all

Thanks for reading the issue!

**Comment by heipiao233** [comment]
I am writing a mod: https://github.com/PillowMC/Pillow. It will make Quilt compatible with Forge. Not implemented yet.

**I'm going to start my summer vacation tomorrow. I finished the last exam of this school year today.**

**Comment by heipiao233** [comment]
> I am writing a mod: https://github.com/PillowMC/Pillow. It will make Quilt compatible with Forge. Not implemented yet.
> 
> **I'm going to start my summer vacation tomorrow. I finished the last exam of this school year today.**

That means I have enough time to complete this mod.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
> I am writing a mod: https://github.com/PillowMC/Pillow. It will make Quilt compatible with Forge. Not implemented yet.
> 
> **I'm going to start my summer vacation tomorrow. I finished the last exam of this school year today.**

Oh i just saw this now, this would be epic!!
