### ISSUE TITLE
生物进入下界传送门后会消失，不能正常传送

### ISSUE THREAD

**Issue by Konjacor** [IzzelAliz/Arclight#565]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.2-dd338d5a

### Java 版本 | 操作系统

操作系统win10 java版本 java 17.0.2 2022-01-18 LTS Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

生物进入下界传送门后会消失，无论在主世界还是下界，生物都不能正常传送到对应世界中

### 复现步骤

去掉所有插件和mod，问题依然存在

### 报错信息

无

**Comment by IzzelAliz** [comment]
已在 03aa8d5f4b99ce21ef417f5e265cf29ab0ea1486 修复
