### ISSUE TITLE
forge版本过低无法启动服务器

### ISSUE THREAD

**Issue by yinglanxing** [IzzelAliz/Arclight#567]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.2

### Java 版本 | 操作系统

Windows 10 ltsc   java version "17.0.3" 2022-04-19 LTS Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111) Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
Mekanism-1.18.2-10.2.0.459
```

### 错误描述

forge版本过低

### 复现步骤

安装Mekanism-1.18.2-10.2.0.459抛出forge版本过低
无法启动服务器
请求更新forge版本

### 报错信息

https://paste.fastmirror.net/?eb86f3395c936e19#EjAxHjRagJoPpNsmWNZpoZc9nn5k3XsJkD2j4D4pkwY6

### 复现用压缩包下载链接(可选)

https://www.curseforge.com/minecraft/mc-mods/mekanism

**Comment by tindin** [comment]
mekanism needs forge-1.18.2-40.0.44

**Comment by yinglanxing** [comment]
> mekanism needs forge-1.18.2-40.0.44
All right......
I have temporarily solved the problem by manually upgrading the forge

**Comment by timi137137** [comment]
试试最新构建

**Comment by yinglanxing** [comment]
> 试试最新构建

已经解决了，可以关闭iss了
