### ISSUE TITLE
相同的問題, 翻譯佔位符依然無效

### ISSUE THREAD

**Issue by nnn950711** [IzzelAliz/Arclight#568]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.3-SNAPSHOT-c7a17ba3

### Java 版本 | 操作系统

Windows 11 / Eclipse Adoptium [ JDK-17.0.1.12-hotspot ]

### 相关 Mod/插件 的名称及版本

```raw
Triton-3.7.3 | PlaceholderAPI-2.11.1 | ProtocolLib
```

### 错误描述

聊天室的訊息以及容器標題是可以翻譯, 但運用在物品上會變成僅顯示佔位符
![2022-04-25_11 03 18](https://user-images.githubusercontent.com/41001774/165014595-af27bcd9-7dd8-4af7-80fb-b65e202f673f.png)

### 复现步骤

1. 使用 自構建最新版的 Triton (https://github.com/tritonmc/Triton) [作者已將插件開源並允許自構建, 只是並不會去解決自構建使用者的問題 "因為原本是屬於付費插件"] ""已有將該插件的設置項 language-creation: items: allow-in-inventory 設置為 true""
2. 安裝 PlaceholderAPI 與 ProtocolLib
3. 翻譯插件的物品

**Comment by nnn950711** [comment]
順帶一提關於以 ProtocolLib 為依賴的插件, 主要插件被加載後服務器經過一段時間會變得很卡甚至直接卡崩潰. (可以使用ProtocolStringReplacer 來舉例相關問題)

**Comment by timi137137** [comment]
这个问题收到了也可以复现，会安排修复。请耐心等待

**Comment by IzzelAliz** [comment]
请测试在 999b9bb30eef647be2966811a061235aac579556 后是否修复

**Comment by nnn950711** [comment]
> 请测试在 [999b9bb](https://github.com/IzzelAliz/Arclight/commit/999b9bb30eef647be2966811a061235aac579556) 后是否修复

沒有修復

**Comment by IzzelAliz** [comment]
请测试是否已经修复

**Comment by nnn950711** [comment]
> 请测试是否已经修复

沒有
