### ISSUE TITLE
Pehkui-3.2.0+1.18.2-forge crashing 

### ISSUE THREAD

**Issue by tindin** [IzzelAliz/Arclight#569]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.2 and arclight-forge-1.18.2-1.0.3-SNAPSHOT

### OS & Java versions

java 17

### Plugins and Mods

```raw
no plugins

forge-1.18.2-40.0.47  --needed version 

caelus-forge-1.18.1-3.0.0.2
Origins-1.18.2-1.4.1.1-unified
Pehkui-3.2.0+1.18.2-forge
bucolicorigins-3.1[FORGE]
cloth-config-6.2.57-forge
```

### Description

crash on start up with listed mods

runs normal with just forge server/cleint
 arclight starts fine on forge-1.18.2-40.0.47 with out mods

### Step to reproduce

install mods 
start server
crash

### Logs

https://pastebin.com/ZFYcQD3N

**Comment by timi137137** [comment]
this problem for the mod Pehkui, you should report to mod author. and, have a small problem, in log, i can see you system language maybe have problem ,maybe you want fix it

**Comment by ClockwerkKaiser** [comment]
I was going to report the same issue, However, I searched first and found this. 

Unfortunately, it seem the pehkui dev closed the hybrid server crash issue after the magma devs figured out their own fix for it, as seen here: [Hybrid server Crash](https://github.com/Virtuoel/Pehkui/issues/283#)
