### ISSUE TITLE
两个及以上玩家进入服务器将导致村民/潜影贝被移除

### ISSUE THREAD

**Issue by kirisameYuii** [IzzelAliz/Arclight#576]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.3

### OS & Java versions

java 17

### Plugins and Mods

```raw
无插件及模组。
```

### Description

当单人进入游戏时，村民可以正常生成，当第二个玩家进入服务器时，村民会凭空消失

### Step to reproduce

1.正常开启服务器
2./locate 任意一个村庄，村民正常生成并活动
3.第二名玩家进入服务器，村民凭空删除/消失

在1.0.2版本中测试无此问题。
### Logs

后台无任何报错。

**Comment by IzzelAliz** [comment]
无法复现
