### ISSUE TITLE
[1.18.2] Skript Does Not Recognize Mod Items/Blocks

### ISSUE THREAD

**Issue by HotoRas** [IzzelAliz/Arclight#577]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.3 (Release)

### OS & Java versions

Windows 10 Home | Java 17.0.1 HOTSPOT

### Plugins and Mods

```raw
[Tested]
plugins (1): Skript
mods:
- BiomesOPlenty-1.18.2-16.0.0.109-universal.jar
- TerraBlender-forge-1.18.2-1.1.0.99.jar
```

### Description

The Spigot plugin `Skript` throws "invalid minecraft id" for modded items/blocks like
```raw
[Server thread/INFO] [Console/]: [Skript] Minecraft id biomesoplenty:white_sand is not valid
```
and they doesn't load it as items in Skript.
Formally I issued this to Skript git, and the reply was:
[`Arclight is not supported, it's not a fork of spigot/paper as well`](https://github.com/SkriptLang/Skript/issues/4678#issuecomment-1073043589).

### Step to reproduce

1. Install Arclight 1.18.2.<br>TIP: You can reproduce this bug at the range of the version `1.17+`.
2. Install plugin `Skript`. You can get them on their [github](https://github.com/SkriptLang/Skript/releases).
3. Install forge mods *containing* items and/or blocks.<br>TIP: You should install dependencies too to load the mods you installed.
4. Launch the server and check the log.

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/8595405/latest.log)

**Comment by IzzelAliz** [comment]
Their developer chose to not accept non vanilla items/blocks.

**Comment by HotoRas** [comment]
[Custom Skript Build](https://github.com/JeonDohyeon/Skript/releases/tag/dev37c2_arclight-related-patch)
No one wills to have it loaded SO I did. Should rewrite the sk script for modded ones (for now), but this fetch still can load mods' stuffs registered through Arclight.
