### ISSUE TITLE
command upgrade world as in spigot is there anything similar on arclight 1.18.2?

### ISSUE THREAD

**Issue by CyberFIowey** [IzzelAliz/Arclight#581]
--forceUpgrade
![19975043_aa82964bc157e9e161a3d6c882d0352a](https://user-images.githubusercontent.com/66869211/166412328-989fa5f4-6540-4a10-8331-a93396e51ba2.png)

**Comment by timi137137** [comment]
Please read the FAQ and use the template to ask questions
