### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by silverfox0000** [IzzelAliz/Arclight#582]
Can you implement an velocity modern forwarding? Velocity has [pull request](https://github.com/PaperMC/Velocity/pull/690) of forge
supporting higher 1.12+ versions

**Comment by timi137137** [comment]
Please read the FAQ and use the template to ask questions

**Comment by IzzelAliz** [comment]
I'm aware of what Velocity guys have done. To my understanding their work is not likely to be accepted by Forge at the moment.

On Arclight/lightfall side we will port/implement **after Forge merged** their pull. From what they've said there will port it to bungeecord and in best case we don't need to do anything and lightfall is hopefully go end of life.
