### ISSUE TITLE
1.18.2史诗战斗修改后的末影龙导致进入末地崩溃

### ISSUE THREAD

**Issue by wushen233** [IzzelAliz/Arclight#583]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.4-SNAPSHOT

### Java 版本 | 操作系统

系统：Windows 10 Java：openjdk version "17.0.3"

### 相关 Mod/插件 的名称及版本

```raw
EpicFight-18.1.12-beta
```

### 错误描述

进入末地后服务器崩溃，这个问题后面我询问了下史诗战斗的作者，他说是末影龙的ai导致的。

### 复现步骤

安装EpicFight模组，进入服务器后进入末地就会触发

### 报错信息

debug：https://paste.ubuntu.com/p/yPyrgZZ5FN/
latest：https://paste.ubuntu.com/p/kx3Rk6nTJV/

**Comment by timi137137** [comment]
这个问题跟 #580 有什么不一样么？如果没有或一天内不回复将被关闭

**Comment by wushen233** [comment]
> 这个问题跟 #580 有什么不一样么？如果没有或一天内不回复将被关闭

一样的，但是我测试过最新构建没有修复，我已经问过开发者了他说让我再报，他会修

**Comment by sandtechnology** [comment]
看了一下 epicfight实现这个东西的方式是动态返回了自己的Phase 选择了直接修改getPhase的方式 所以不能提前注册（草：

https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36

所以应该需要动态根据获取到的结果进行注册

**Comment by wushen233** [comment]
> 看了一下 epicfight实现这个东西的方式是动态返回了自己的Phase 选择了直接修改getPhase的方式 所以不能提前注册（草：
> 
> https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36
> 
> 所以应该需要动态根据获取到的结果进行注册

所以能解决吗？需不需要我去联系下史诗战斗的作者。

**Comment by sandtechnology** [comment]
> > 看了一下 epicfight实现这个东西的方式是动态返回了自己的Phase 选择了直接修改getPhase的方式 所以不能提前注册（草：
> > https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36
> > 所以应该需要动态根据获取到的结果进行注册
> 
> 所以能解决吗？需不需要我去联系下史诗战斗的作者。

看走眼了 实际上是直接替换了phase的实现：https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83

解决的话应该是可以的 但是在这种情况下应该是要重新定义下Phase的名称 而bukkit内是写死的根据index确定
应该需要写个craftbukkit的CraftEnderDragon的 Mixin

**Comment by wushen233** [comment]
> > > 看了一下 epicfight实现这个东西的方式是动态返回了自己的Phase 选择了直接修改getPhase的方式 所以不能提前注册（草：
> > > https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36
> > > 所以应该需要动态根据获取到的结果进行注册
> > 
> > 
> > 所以能解决吗？需不需要我去联系下史诗战斗的作者。
> 
> 看走眼了 实际上是直接替换了phase的实现：https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83
> 
> 解决的话应该是可以的 但是在这种情况下应该是要重新定义下Phase的名称 而bukkit内是写死的根据index确定 应该需要写个craftbukkit的CraftEnderDragon的 Mixin

那就麻烦了

**Comment by timi137137** [comment]
> > > 看了一下 epicfight实现这个东西的方式是动态返回了自己的Phase 选择了直接修改getPhase的方式 所以不能提前注册（草：
> > > https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36
> > > 所以应该需要动态根据获取到的结果进行注册
> > 
> > 
> > 所以能解决吗？需不需要我去联系下史诗战斗的作者。
> 
> 看走眼了 实际上是直接替换了phase的实现：https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83
> 
> 解决的话应该是可以的 但是在这种情况下应该是要重新定义下Phase的名称 而bukkit内是写死的根据index确定 应该需要写个craftbukkit的CraftEnderDragon的 Mixin

欢迎PR(x

**Comment by sandtechnology** [comment]
> > > > 看了一下 epicfight实现这个东西的方式是动态返回了自己的Phase 选择了直接修改getPhase的方式 所以不能提前注册（草：
> > > > https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36
> > > > 所以应该需要动态根据获取到的结果进行注册
> > > 
> > > 
> > > 所以能解决吗？需不需要我去联系下史诗战斗的作者。
> > 
> > 
> > 看走眼了 实际上是直接替换了phase的实现：https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83
> > 解决的话应该是可以的 但是在这种情况下应该是要重新定义下Phase的名称 而bukkit内是写死的根据index确定 应该需要写个craftbukkit的CraftEnderDragon的 Mixin
> 
> 欢迎PR(x

P了（

**Comment by wushen233** [comment]
> > > > > 看看epicfight这个东西的方式是直接修改了动态返回了自己的Phase实现选择了getPhase的方式所以不能提前注册（草：
> > > > > [https ://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/ java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36)
> > > > > 所以应该需要根据动态获取到的结果进行注册
> > > > 
> > > > 
> > > > 所以需要战斗吗？
> > > 
> > > 
> > > 看走眼了：f是直接替换了阶段的[实现.java#L69-L83](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83)解决方案
> > > 应该是可以的 但是在这种情况下应该是要​​重新定义下阶段的名称，而 bukkit 里面是写死的根据索引确定 应该需要写一个craftbukkit 的CraftEnderDragon 的 Mixin
> > 
> > 
> > 欢迎PR(x
> 
> P了（

感谢大佬！哇！为了这个崩溃问题，我等了一个多月了，等一波更新。终于可以弄服务器了！非常感谢！

**Comment by sandtechnology** [comment]
> > > > > > 看看epicfight这个东西的方式是直接修改了动态返回了自己的Phase实现选择了getPhase的方式所以不能提前注册（草：
> > > > > > [https ://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/ java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36)
> > > > > > 所以应该需要根据动态获取到的结果进行注册
> > > > > 
> > > > > 
> > > > > 所以需要战斗吗？
> > > > 
> > > > 
> > > > 看走眼了：f是直接替换了阶段的[实现.java#L69-L83](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83)解决方案
> > > > 应该是可以的 但是在这种情况下应该是要​​重新定义下阶段的名称，而 bukkit 里面是写死的根据索引确定 应该需要写一个craftbukkit 的CraftEnderDragon 的 Mixin
> > > 
> > > 
> > > 欢迎PR(x
> > 
> > 
> > P了（
> 
> 感谢大佬！哇！为了这个崩溃问题，我等了一个多月了，等一波更新。终于可以弄服务器了！非常感谢！

https://github.com/IzzelAliz/Arclight/suites/7096461754/artifacts/280826781
可以下这个试试

**Comment by wushen233** [comment]
> > > > > > > 看看epicfight这个东西的方式是直接修改了动态返回了自己的Phase实现了getPhase的方式所以不能提前注册（草：
> > > > > > > [https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/ java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36)
> > > > > > > 所以应该需要根据动态获取到的结果进行注册
> > > > > > 
> > > > > > 
> > > > > > 所以需要战斗吗？
> > > > > 
> > > > > 
> > > > > 看走眼了：f是直接替换了阶段的[实现.java#L69-L83](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83)解决方案
> > > > > 应该是可以的 但是在这种情况下应该是要​​重新定义下阶段的名称，而bukkit里面是写死的根据索引确定应该需要写一个craftbukkit 的CraftEnderDragon 的Mixin
> > > > 
> > > > 
> > > > 欢迎PR(x
> > > 
> > > 
> > > P了（
> > 
> > 
> > 感谢大佬！哇！为了这个崩溃的问题，我等了一个多月了，等一波更新。终于可以弄服务器了！非常感谢！
> 
> https://github.com/IzzelAliz/Arclight/suites/7096461754/artifacts/280826781 可以下这个试试

ok我试试

**Comment by wushen233** [comment]
> > > > > > > > 看看epicfight这个东西的方式是直接修改了动态返回了自己的Phase实现了getPhase的方式所以不能提前注册（草：
> > > > > > > > [https ://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java /yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/PhaseManagerPatch.java#L17-L36)
> > > > > > > > 所以应该需要根据动态获取到的结果进行注册
> > > > > > > 
> > > > > > > 
> > > > > > > 所以需要战斗吗？
> > > > > > 
> > > > > > 
> > > > > > 看走眼了：f是直接替换了阶段的[实现.java#L69-L83](https://github.com/Yesssssman/epicfightmod/blob/bcab592aabce588e9b121ff764e44c0cf8ac2342/src/main/java/yesman/epicfight/world/capabilities/entitypatch/boss/enderdragon/EnderDragonPatch.java#L69-L83)解决方案
> > > > > > 应该是可以的但是在这种情况下应该是要​​重新定义下阶段的名称，而bukkit里面是写死的根据索引确定应该需要写一个craftbukkit 的CraftEnderDragon 的Mixin
> > > > > 
> > > > > 
> > > > > 欢迎PR(x
> > > > 
> > > > 
> > > > P了（
> > > 
> > > 
> > > 感谢大佬！哇！为了这次崩溃的问题，我等了一个多月了，等一波更新。终于可以弄服务器了！非常感谢！
> > 
> > 
> > https://github.com/IzzelAliz/Arclight/suites/7096461754/artifacts/280826781可以下这个试试
> 
> 好吧我试试

ok了！我刚刚测试了，没问题了，不会崩溃了！感谢！

**Comment by ghost** [comment]
这个问题我依稀记得1.16.5也有

**Comment by wushen233** [comment]
> 这个我依稀记得 1.16.5 也有

并没有，1.16.5我没遇到，1.18.2这个是因为作者更新了末影龙的动画。1.16.5的末影龙还是原版的动画和AI。

**Comment by ghost** [comment]
> > 这个我依稀记得 1.16.5 也有
> 
> 并没有，1.16.5我没遇到，1.18.2这个是因为作者更新了末影龙的动画。1.16.5的末影龙还是原版的动画和AI。

1.16.5之前有一个末影人的问题，玩家打末影人就会全服掉线

**Comment by wushen233** [comment]
> > > 这个我依稀记得 1.16.5 也有
> > 
> > 
> > 并没有，1.16.5 我没遇到，1.18.2 这个是因为作者了末影龙的动画。1.16.5 的末影龙还是原版的动画和 AI。
> 
> 1.16.5 有一个末影人的问题，玩家打末影人之前一直全服掉线

末影人这个我知道，我也给作者反馈了。我记得已经修复了。

**Comment by sandtechnology** [comment]
所以说这么久过去了好像还是没解决的样子（

**Comment by wushen233** [comment]
> 所以说这么久过去了好象还是没有解决的样子（
其实解决了啊，后面有老哥发了个修复的分支，不清楚官方后面有没有合并进去。

**Comment by sandtechnology** [comment]
> > 所以说这么久过去了好象还是没有解决的样子（
> > 其实解决了啊，后面有老哥发了个修复的分支，不清楚官方后面有没有合并进去。

作者就是我啊草（

**Comment by wushen233** [comment]
> > > 所以说这么久过去了好象还是没有解决的样子（其实际
> > > 解决了啊，后面有老哥发了个修改的支持，不清楚官方后面有合租。
> 
> 作者就是我啊草（

哈哈哈我刚刚才发现就是你，md时间太久了。忘记了，官方没合并你的修复？

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/209680804-3533ce36-000a-4822-a083-f29a45d5af48.png)
(?

**Comment by sandtechnology** [comment]
> > > > 所以说这么久过去了好象还是没有解决的样子（其实际
> > > > 解决了啊，后面有老哥发了个修改的支持，不清楚官方后面有合租。
> > 
> > 
> > 作者就是我啊草（
> 
> 哈哈哈我刚刚才发现就是你，md时间太久了。忘记了，官方没合并你的修复？

海螺说后续会想个通用的方法去修这个 目前确实有其他enum会遇见这个问题
不过后面兴许是忘记了 我现在重开了个PR

**Comment by wushen233** [comment]
> > > > > 所以说这么久过去了好象还是没有解决的样子（其实际
> > > > > 解决了啊，后面有老哥发了个修改的支持，不清楚官方后面有合适的。
> > > 
> > > 
> > > 作者就是我啊草（
> > 
> > 
> > 哈哈哈我刚发现就是你，md时间太久了。忘记了，官方没有和你的修复？
> 
> 海螺说以后会想用的方法去修改这个 目前确实有其他枚举会遇到这个问题 不过面兴许是忘记了 我现在重新开放了

ok

**Comment by chunye666** [comment]
我看好像还没更新这个修复，自制了个数据包临时缓解一下（后果就是末影龙变回原版了）
链接: https://pan.baidu.com/s/1KNn1pl4YR-heKGRFYYhWzg?pwd=cb2i 提取码: cb2i 
放到服务器根目录下datapack文件夹即可
版本1.18.2

**Comment by wushen233** [comment]
> 我看好像还没更新这个修复，自制了个数据包临时缓解一下（后果就是末影龙变回原版了） 链接: https://pan.baidu.com/s/1KNn1pl4YR-heKGRFYYhWzg?pwd=cb2i 提取码: cb2i 放到服务器根目录下datapack文件夹即可 版本1.18.2

等上面老哥的修复合并进去吧，他之前编译的版本我测试过，没问题。你这个是治标不治本，而且把末影龙变回原版就没意思了
