### ISSUE TITLE
安装外置登录后插件失效

### ISSUE THREAD

**Issue by YivanLiu** [IzzelAliz/Arclight#585]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.16.5-1.0.23

### Java 版本 | 操作系统

系统：Windows 10 家庭中文版，java version "16.0.2" 2021-07-20

### 相关 Mod/插件 的名称及版本

```raw
单独用MultiVerse和BanItem插件测试，均发生此问题
```

### 错误描述

安装外置登录后，安装的所有插件失效，但外置登录功能可以正常使用。

### 复现步骤

1. 将外置登录安装文件authlib-injector-1.1.27-5ef5f8e.jar放入服务器文件夹
2. 将插件放入plugins文件夹
3. 启动文件写入
JAVA -Xms4096M -Xmx4096M -javaagent:authlib-injector-1.1.27-5ef5f8e.jar=https://littleskin.cn/api/yggdrasil -jar arclight-forge-1.16.5-1.0.23.jar -nogui
4. 启动服务器

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/8657106/latest.log)

**Comment by IzzelAliz** [comment]
更新 authlib injector
