### ISSUE TITLE
模组：questsadditions不兼容 启动后服务端崩溃

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#587]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.23-daa3c8bb（最新）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
[FTB任务附加]questsadditions-1.16-1.3.1
https://www.mcmod.cn/class/5709.html

以下是前置：
[FTB前置]architectury-1.28.48
[FTB前置]ftb-library-forge-1605.3.4-build.90
[FTB任务]ftb-quests-forge-1605.3.6-build.98
[FTB物品过滤器]item-filters-forge-1605.2.5-build.9
[FTB组队]ftb-teams-forge-1605.2.3-build.40
```

### 错误描述

安装 questsadditions 后崩溃

只安装相关前置不崩溃
纯forge端没有这个问题，无法复现

### 复现步骤

1、安装 questsadditions
2、启动服务器
3、服务器崩溃

### 报错信息

https://paste.ubuntu.com/p/q3MnmwSN3R/

**Comment by Bi-an-NEI** [comment]
我遇到相同问题
