### ISSUE TITLE
求教为什么我的服务器核心启动不了？

### ISSUE THREAD

**Issue by LiaoShuaiAcount** [IzzelAliz/Arclight#590]
![error](https://user-images.githubusercontent.com/49898458/169012017-f4b56004-76ce-4fa4-b28e-7b024a7516a3.png)

我启动的时候报错，服务器是  ubuntu云服务器，
服务器上的java版本是 jdk18
启动命令是 java -jar arclight-forge-1.18.2-1.0.4.jar

**Comment by timi137137** [comment]
请阅读FAQ
