### ISSUE TITLE
[1.18] Create mod contraptions wipe out chests

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#592]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.5-SNAPSHOT-51a9d2a

### OS & Java versions

Java 17 

### Plugins and Mods

```raw
-Create mod 0.4.1
```

### Description

When a chest with items becomes part of a moving contraption, all items get deleted when it comes back on block-form. It does not happen with barrels or shulkerboxes, only with chests.

### Step to reproduce

1. Glue together some blocks and a chest
2. place items inside the chest
3. move the blocks+chest with a mechanical piston
4. stop the piston
5. open chest again
6. Doing the same with the barrel will not wipe out the items

**Comment by muriplz** [comment]
it's also a bug on mohist. IDK what more info I could give, since there is no logs or anything. Doing what i've said on the Steps to reproduce on a local server is enough to see the error.

**Comment by IzzelAliz** [comment]
Please check if it is fixed after 31bb3bbeccb4dc0db832f79dc41c50c91fa233d1

**Comment by muriplz** [comment]
The problem still persists on 运行版本 arclight-1.18.2-1.0.5-SNAPSHOT-31bb3bb
