### ISSUE TITLE
踩踏仙人掌后崩服

### ISSUE THREAD

**Issue by Hazi7** [IzzelAliz/Arclight#6]
https://paste.ubuntu.com/p/mXPdVxthqH/

核心版本：群文件的

补：打僵尸什么的一样崩

**Comment by IzzelAliz** [comment]
提供一下打僵尸的报错

**Comment by Hazi7** [comment]
> 提供一下打僵尸的报错

https://paste.ubuntu.com/p/4qr88KwFH2/

**Comment by IzzelAliz** [comment]
已修复
