### ISSUE TITLE
[1.18.2] Only forge installed

### ISSUE THREAD

**Issue by jelebruh** [IzzelAliz/Arclight#600]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.0.4

### OS & Java versions

Ubuntu 20.04, Java 17.0.3

### Plugins and Mods

```raw
.
```

### Description

After `java -jar arclight-...jar` and start server /plugins folder not created, installed only forge without spigot

### Step to reproduce

1. Install Arclight
2. Start server

**Comment by timi137137** [comment]
I can't understand your question

**Comment by jelebruh** [comment]
> I can't understand your question

Bukkit not working, only forge

**Comment by timi137137** [comment]
> > I can't understand your question
> 
> Bukkit not working, only forge

you should submit full version and more info
