### ISSUE TITLE
No death messages when Pixelmon installed

### ISSUE THREAD

**Issue by Mike5357** [IzzelAliz/Arclight#601]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.23-SNAPSHOT-2dda792d

### OS & Java versions

Java 11.0.12

### Plugins and Mods

```raw
Mods: Pixelmon 9.0.0
Plugins: None
```

### Description

When Pixelmon is installed on an Arclight server, death messages no longer appear in chat.
Arclight itself is showing death messages when no mods are installed, but adding Pixelmon stops them from appearing. This issue also seems to be present in Mohist.
On a pure Forge server however, death messages with Pixelmon installed send fine.

It appears the death event might not be firing correctly at all, as even plugins such as DiscordSRV do not get notified of the death occurring. 

I'm not sure whether this is an issue on Pixelmons side or Arclight(& Mohist)'s side so I'm just reporting this to both; Heres the ticket I submitted to them for reference: https://pixelmonmod.com/tracker.php?p=2&t=17886

### Step to reproduce

1. Boot up a fresh Arclight server
2. Install the Pixelmon mod
3. Login and die (I switched to Creative, flew into the air, and then switched to Survival so I fell to my death.)
4. See that no death message is posted in chat.

### Logs

No errors are reported in the logs- and neither is the players death.

**Comment by danorris709** [comment]
This was a Pixelmon issue, which we've resolved. This can be closed :)
