### ISSUE TITLE
[1.18.2] Bukkit not working (#600 2)

### ISSUE THREAD

**Issue by jelebruh** [IzzelAliz/Arclight#602]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.0.4

### OS & Java versions

Ubuntu 20.04 ARM, Java 17.0.3

### Plugins and Mods

```raw
.
```

### Description

When I install arc by `java -jar arclight-40.1.0-1.0.4-installer.jar nogui` and start server /plugins not created, if I create this folder - this not working

### Step to reproduce

1. install arc
2. start server

**Comment by HotoRas** [comment]
Run JAR you used to install the server to run server, that will launch Arclight correctly.
The generated bat/sh file will launch Forge server, not Arclight.

.. *Is there anyone who can post this to FAQ?*

**Comment by timi137137** [comment]
> Run JAR you used to install the server to run server, that will launch Arclight correctly. The generated bat/sh file will launch Forge server, not Arclight.
> 
> .. _Is there anyone who can post this to FAQ?_

OK wait some times
