### ISSUE TITLE
[1.18.2] 工业先锋玩家将肉汤注射剂放入饰品栏后服务器崩溃

### ISSUE THREAD

**Issue by Nothingness-Void** [IzzelAliz/Arclight#608]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.4-f6937a3c

### Java 版本 | 操作系统

系统：Windows server 2019 JAVA版本：18.0.1.1

### 相关 Mod/插件 的名称及版本

```raw
[工业先锋] industrial-foregoing-1.18.2-3.3.1.0-2.jar : industrialforegoing (3.3.1.0)
```

### 错误描述

饰品栏装备肉汤注射器的玩家导致的实体错误

### 复现步骤

玩家将肉汤注射剂[工业先锋]拿在手上时正常

放入饰品栏后服务器崩溃

再次启动服务器后同一个玩家进入服务器依然会崩溃

在playerdata中删除该玩家的背包后 该玩家再次进入则服务器正常运行

### 报错信息

崩溃报告：https://paste.fastmirror.net/?ed81cbbb00c292ee#BDd7ZUsGFLvPauW7vKhNEFqVnqBrDAudwDokfQgA1dxX

日志
[2022-06-12-5.log](https://github.com/IzzelAliz/Arclight/files/8885484/2022-06-12-5.log)
：

**Comment by IzzelAliz** [comment]
你确定不可在 Forge 复现？
