### ISSUE TITLE
[1.16.5]海龟蛋在下界无法正常吸引僵尸猪灵的仇恨

### ISSUE THREAD

**Issue by water-mi** [IzzelAliz/Arclight#617]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.23-daa3c8bb

### Java 版本 | 操作系统

Ubuntu Oracle Java8

### 相关 Mod/插件 的名称及版本

```raw
排除了模组和插件的问题
```

### 错误描述

在主世界和末地中海龟蛋可以僵尸猪灵的仇恨，而在下界中无法吸引
![image](https://user-images.githubusercontent.com/43495286/174865119-1a3e942b-6cbe-4129-b799-a59173154018.png)
![image](https://user-images.githubusercontent.com/43495286/174865383-f1011dff-e7c1-4277-9dc3-368dad5c9a94.png)
![image](https://user-images.githubusercontent.com/43495286/174864907-d1fff72a-af81-4d23-be7a-e65aacd5d75a.png)
下界基岩上层僵尸猪灵塔需要用到海龟蛋吸引仇恨（即使是在基岩下层也无法吸引）
![image](https://user-images.githubusercontent.com/43495286/174865521-478f8cc4-9681-4c6b-8778-18088b6c7a7f.png)

### 复现步骤

1.进入下界后随便找一个地方（有足够高的空间），放下海龟蛋，在旁边刷一群僵尸猪灵，观察是否有向海龟蛋聚集（应该没有）
2.在主世界/末地重复类似操作，会观察到有向海龟蛋聚集

**Comment by CKylinMC** [comment]
~~1.18.2 (构建 [0a235737](https://github.com/IzzelAliz/Arclight/commit/0a235737a548826763374ebb49ec67f4c1fe0990)) 也有这个问题。~~

经过再次排查发现不是Arclight的问题。

*似乎是使用过ClearLag插件后，哪怕全部插件模组都移除，原本存档的下界都不能恢复正常。主世界不影响，通过多世界插件创建的新的下界类型的世界不受影响。*

**Comment by axuanran** [comment]
> 1.18.2 (构建 [0a235737](https://github.com/IzzelAliz/Arclight/commit/0a235737a548826763374ebb49ec67f4c1fe0990)) 也有这个问题。

https://github.com/MinecraftForge/MinecraftForge/pull/9250
在此上游pr中已对1.18.2进行修复，不清楚是否已经合并
如果没合的话.....开个新的issue（？

**Comment by CKylinMC** [comment]
> > 1.18.2 (构建 [0a235737](https://github.com/IzzelAliz/Arclight/commit/0a235737a548826763374ebb49ec67f4c1fe0990)) 也有这个问题。
> 
> [MinecraftForge/MinecraftForge#9250](https://github.com/MinecraftForge/MinecraftForge/pull/9250) 在此上游pr中已对1.18.2进行修复，不清楚是否已经合并 如果没合的话.....开个新的issue（？

再次排查之后发现似乎是其他插件直接影响了存档导致哪怕移除所有插件模组之后都不能正确运行，应该不是Arclight的问题。
