### ISSUE TITLE
[功能请求] 在使用 /reload 时不重载插件

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#621]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-SNAPSHOT-4da88ff4（最新）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
希望能提供一个选项：
在使用/reload时 屏蔽plugins插件的重载
毕竟使用 /reload 主要是为了重载数据包，或者重载kubejs或CraftTweaker等这类自定义配方的脚本文件
插件通常都自带了reload命令或可以使用plugmanx等工具替代
```

### 错误描述

无

### 复现步骤

无

### 报错信息

无

**Comment by IzzelAliz** [comment]
用 /minecraft:reload
