### ISSUE TITLE
[1.16.5] 一个错误警告（似乎影响不大） Mixin apply failed mixins.arclight.impl.forge.optimization.stream.json

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#622]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-SNAPSHOT-4da88ff4（最新）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

无

### 复现步骤

1、启动服务器
2、出现警告

### 报错信息

错误信息：
https://paste.ubuntu.com/p/hV7pgTcHNB/

**Comment by IzzelAliz** [comment]
你要是从 actions 下载的那就换成去 appveyor 下载

**Comment by luoxiawuchen** [comment]
> 你要是从 actions 下载的那就换成去 appveyor 下载

好，不过一直都是在appveyor下载的，actions反倒没用过
