### ISSUE TITLE
Flying around the end generated with Oh the Biomes you go causes an ArrayIndexOutOfBoundsException Chunk crash

### ISSUE THREAD

**Issue by nicholasrobertm** [IzzelAliz/Arclight#627]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.24-SNAPSHOT-dcfa4ab9

### OS & Java versions

OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

### Plugins and Mods

```raw
Pixelmon (mod)
```

### Description

Server randomly crashed due to the error mentioned in the log

### Step to reproduce

Unknown, happens randomly with nothing seemingly causing it

### Logs

https://pastebin.com/DDUerJGb

**Comment by nicholasrobertm** [comment]
Update: As far as I can tell this is only happening with the end dimension.

**Comment by nicholasrobertm** [comment]
Have updated this with further clarification, this only happens when flying around the end with the Oh the Biomes you Go mod installed, when the end is generated with it's generation.

**Comment by IzzelAliz** [comment]
Fixed in #738.
