### ISSUE TITLE
[1.16.5]机械动力模组收割机无法采集到箱子BUG

### ISSUE THREAD

**Issue by SpicyFishOuO** [IzzelAliz/Arclight#630]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [ ] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-SNAPSHOT-4da88ff4

### Java 版本 | 操作系统

系统 windows 10  java version "16.0.1" 2021-04-20 Java(TM) SE Runtime Environment (build 16.0.1+9-24) Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
Mod List: 
? minecraft forge-1.16.5-36.2.26-server.jar : minecraft (1.16.5) - 1
? maven_libs forge-1.16.5-36.2.26-universal.jar : forge (36.2.26) - 1
? mods_folder [前置飞轮-机械动力]flywheel-1.16-0.2.5.jar : flywheel (1.16-0.2.5) - 1
? mods_folder [机械动力]create-mc1.16.5_v0.3.2g.jar : create (v0.3.2g) - 1
? mods_folder [前置]architectury-1.31.59.jar : architectury (1.31.59) - 1
? mods_folder [JEI前置]ftb-library-forge-1605.3.4-build90.jar : ftblibrary (1605.3.4-build.90) - 1
? mods_folder [JEI物品管理器]jei-1.16.5-7.7.1.152.jar : jei (7.7.1.152) - 1
? arclight arclight-forge-1.16.5-1.0.24-SNAPSHOT.jar : arclight (1.16.5-1.0.24-SNAPSHOT-4da88ff4) - 1
```

### 错误描述

机械动力1.16.5最终版本在
arclight-forge-1.16.5-1.0.24-SNAPSHOT
arclight-forge-1.16.5-1.0.23
测试均复现此BUG
————————
机械动力的动力收割机用强力胶沾了箱子并不会把作物收集到箱子中而是全部消失了！
在forge端中并未发生这样的情况
我已经把forge跟arclight服务端打包上传了，还有演示视频还请作者大大看一下，谢谢。

### 复现步骤

1.安装模组
2.进入服务器摆放收割机设施
3.开始装置收割
4.无法将作物收集到箱子里并且作物全部消失。

### 报错信息

[2022-06-28-2.log.gz](https://github.com/IzzelAliz/Arclight/files/8999992/2022-06-28-2.log.gz)
[2022-06-28-3.log.gz](https://github.com/IzzelAliz/Arclight/files/8999993/2022-06-28-3.log.gz)

### 复现用压缩包下载链接(可选)

https://1drv.ms/u/s!Av82vVYHi3IpliNUEsC0qHE4dCNA?e=8b0ooC

**Comment by mlus-asuka** [comment]
acctually the problem existed for 1 years ago during 1.16.5 to 1.18.2
