### ISSUE TITLE
[1.16.5]安装了自定义NPCmod后，物品会增加空tag【tag:{}】，导致相同物品无法叠加

### ISSUE THREAD

**Issue by StarryNightNue** [IzzelAliz/Arclight#636]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.16.5-1.0.24-SNAPSHOT

### Java 版本 | 操作系统

系统：windows10，游戏使用Java：Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)，服务器使用Java：Java 16.0.1.0

### 相关 Mod/插件 的名称及版本

```raw
C[自定义NPC]CustomNPCs-1.16.5.20220622snapshot
```

### 错误描述

1.安装最新版自定义NPC后，在玩家打开诸如“熔炉”、“箱子”、“漏斗”等**有格子**的UI界面时，会出现新的空tag，使用【IBE editor】查看无法叠加的物品当前拥有的nbt标签，会发现末尾增加了一个空标签【tag:{}】。

2.在我向mod作者反馈后，于【CustomNPCs-1.16.5.20220622snapshot】这个6月22号的snapshot版修复了单人游戏BUG。但是将这个最新版的自定义NPCmod装到服务器里，发现空tag的BUG在服务器依旧存在，不关闭游戏的情况下进单人存档发现问题消失，再次进入服务器问题又出现了。

3.对此我单独使用1.16.5最新版的arclight核心进行开服，只安装【自定义NPC】与【IBE editor】，新建服务器世界，发现问题依旧存在。

自定义NPC作者noppes的discord：[https://discord.com/channels/151785576557707264/233668264440496128](url)

### 复现步骤

1.安装【CustomNPCs-1.16.5.20220622snapshot】与【IBE editor】，可选安装【MouseTweaks】

2.进入服务器后，打开背包，拿出4x9个【石头】，**单独**填满包括快捷栏的背包

3.在只打开自身背包的情况下，鼠标左键拿起并放下【石头】，发现可以随便堆叠，且每次拿起与放下时查看nbt标签，会发现无变化；

4.在打开熔炉等带有格子的UI界面的情况下，拿起【石头】前查看一次nbt标签，放下【石头】后查看一次NBT标签，会发现有些【石头】的nbt标签在末尾增加了一个【tag:{}】空标签，**若拿起并放下后发现无nbt变化，可以尝试拿起并放到另一格空位，多次挪动，观察nbt变化**

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/9030805/latest.log)

**Comment by StarryNightNue** [comment]
希望作者大大能帮忙看看是哪里出现了问题，因为这个mod对我的服务器而言真的很重要qwq......Arclight也是我选择的众多服务器核心之中出现的最少mod与插件兼容性问题，也是最稳定极少崩服的核心了，再次劳烦您！！！

**Comment by sandtechnology** [comment]
这个问题在纯 Forge 服务器上存在吗？

**Comment by StarryNightNue** [comment]
> 这个问题在纯 Forge 服务器上存在吗？

啊不好意思，回复迟了，单人forge以及纯forge服务器上也不存在这个问题
mod作者在7月7日更新到CustomNPCs-1.16.5.20220707snapshot了，对Arclight的服务器同步更新该mod后，发现这个问题依旧存在

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by StarryNightNue** [comment]
> 请测试是否修复

**新版本的arclight在背包挪动物品的时候不会再出现空tag的情况了！！非常感谢您能在百忙之中抽出时间修复bug！辛苦了！**

只是目前还有一个小问题，在【熔炉】、【高炉】、【烟熏炉】烧制的过程中：
①如果不点开容器，则【烧制完成的物品】会正常叠加；
②如果烧制途中点开容器，则只会烧制一个物品，后续【正在烧制的物品】不会再叠加到【烧制完成的物品】上；
直到把无法叠加的【烧制完成的物品】拿走并关闭物品栏，才会重新回到情况①

我以为这个问题也是受空tag影响，所以当时只反馈了空tag的问题，十分抱歉！如果您能在空闲的时候找到原因并修复的话，就没有任何问题啦！不用急着修复，优先级可以靠后些，生活第一！再次对您表示感谢！！QWQ

**Comment by IzzelAliz** [comment]
转移至 #689
