### ISSUE TITLE
Threads not properly shutting down

### ISSUE THREAD

**Issue by zThana** [IzzelAliz/Arclight#638]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.24-SNAPSHOT-759a3fd5

### OS & Java versions

OS: Ubuntu 5.4.0-120-generic; Java: OpenJDK 1.8.0_312

### Plugins and Mods

```raw
Irrelevant
```

### Description

Any plugin having any threads will not properly shut down when stopping the server.

### Step to reproduce

Get any plugin with a permanently running runnable (bStats for example), then stop the server.

### Logs

Rest of the logs are irrelevant:
[Exit Thread/WARN] [Arclight/]: 8 threads not shutting down correctly, force exiting

**Comment by 5ur3z** [comment]
我也遇到了同样问题
每次关服都会有几个区块不能正确卸载

**Comment by IzzelAliz** [comment]
This is not a problem here. The WARN level is misleading.

**Comment by 5ur3z** [comment]
ok thanks a lot

**Comment by zThana** [comment]
It freezes console before shutting down, it must have at least some impact
