### ISSUE TITLE
多世界创建崩溃/世界假死

### ISSUE THREAD

**Issue by yonghenglunhui** [IzzelAliz/Arclight#64]
### 我正在运行

* **Arclight** [版本] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** ["1.8.0_202"] 

* **操作系统** [Win10 18363]

* **插件列表** 
Multiverse-Core-4.2.2

* **Mod 列表** 
无

### 错误描述
第一次开服，使用的是4.1.0的MV，创建世界，崩溃，
崩溃报告：https://paste.ubuntu.com/p/S7n6d7C2yG/
再次开服，更换了4.2.2的MV，创建世界成功，但是进入后无法破坏东西，生物不会移动无法被攻击，掉落物无法拾取，区块正常加载。我用另一个号进入世界后发现实际上第一个号停在原地并不能动。
尝试了数个世界管理插件，无果。

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 xxx
2. 进入服务器后 xxxx
3. ....

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

https://paste.ubuntu.com/p/pszFwnBDxR/

**Comment by IzzelAliz** [comment]
请验证是否修复

**Comment by yonghenglunhui** [comment]
> 请验证是否修复

用最新版本测试了一下，首次创建世界仍然会出现同样问题，但是重启服务器后已创建的世界即可恢复正常

**Comment by yonghenglunhui** [comment]
> 请验证是否修复

再测试了一下，那些重启后正常的世界，会出现游戏规则更改无效（比如火焰蔓延关了还是会蔓延），死亡东西直接消失，生物事件不会触发（比如僵尸白天不会燃烧），以及Bossshop的菜单界面会在这些世界卡假物品（比如背包里有一个钻石，丢掉后，打开菜单，丢掉的钻石会回原位，地上的还在）
日志：
https://paste.ubuntu.com/p/y57rPrSrWZ/

**Comment by IzzelAliz** [comment]
请验证是否修复

**Comment by yonghenglunhui** [comment]
> 请验证是否修复

规则死亡什么的都正常了，还是有菜单界面卡背包假物品的问题，遇到两种情况：
比如背包有一些东西，打开一次菜单再关闭，在创建的世界死亡后，东西还在背包，丢掉东西，此时再打开菜单，会显示这些东西，点一下会全消失，但是按Q可以丢出去变成真正的物品。（这一种情况遇到的比较少）
另一种是不丢东西，打开菜单东西消失，再点一下空格子会出来。（遇到较多）

还没来得及试试其他的情况和菜单插件，服崩了....崩溃报告：
https://paste.ubuntu.com/p/6nJHcjCN3n/

**Comment by IzzelAliz** [comment]
这个崩溃的话，你最好把整个世界删除重新创建一个，文件已经损坏了

**Comment by yonghenglunhui** [comment]
> 这个崩溃的话，你最好把整个世界删除重新创建一个，文件已经损坏了

emmm目前为止还没再遇到这个崩溃的情况，测试了一下菜单的问题，用ChestCommands也是同样的状况，而且在原版的世界死亡也有几率出现菜单界面卡物品的情况。
日志：https://paste.ubuntu.com/p/HN9q765ZBp/

**Comment by IzzelAliz** [comment]
请验证是否修复菜单相关问题

**Comment by yonghenglunhui** [comment]
> 请验证是否修复菜单相关问题

测试了一下，目前没遇到问题了，感谢
