### ISSUE TITLE
Incompatibility with Radon & Radium

### ISSUE THREAD

**Issue by bl4d3tv** [IzzelAliz/Arclight#645]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.6-SNAPSHOT-7128c9d

### OS & Java versions

OS: Windows 11, Java: openjdk version "17.0.3" 2022-04-19

### Plugins and Mods

```raw
Radium v0.7.10 and/or Radon v0.8.1
```

### Description

[Radium ](https://www.curseforge.com/minecraft/mc-mods/radium-reforged) and [Radon](https://www.curseforge.com/minecraft/mc-mods/radon) are ports of popular Fabric optimization mods.
When preparing the level "world", the server stops with a _FATAL_ when trying to apply a certain mixin.

I tried with multiple Forge versions and with other hybrid forge-bukkit software and encountered the same issue. This does NOT happen with regular Forge.

### Step to reproduce

1. Install either Radon or Radium (or both at the same time)
2. Start the server
3. Wait until the server tries to prepare/load the world
4. The server throws a _FATAL_.

### Only Radium enabled
Logs: https://pastebin.com/iXmYESJL
Crash report: https://pastebin.com/RrcpEbwX

### Only Radon enabled
Logs: https://pastebin.com/1EJdDKnZ
Crash report: https://pastebin.com/6gVpK7Qg

**Comment by IzzelAliz** [comment]
Optimization mods are out of consideration.
