### ISSUE TITLE
[1.16.5]魔法艺术3的破坏挖掘法术可以破坏方块但是不掉方块

### ISSUE THREAD

**Issue by haozaizai1** [IzzelAliz/Arclight#646]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [ ] 已为所有插件及模组安装依赖
- [ ] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.16.5-1.0.24-SNAPSHOT

### Java 版本 | 操作系统

java11

### 相关 Mod/插件 的名称及版本

```raw
1
```

### 错误描述

魔法艺术3的破坏挖掘方块可以破坏方块但是不会掉落方块

### 复现步骤

1

### 报错信息

1

### 复现用压缩包下载链接(可选)

1

**Comment by haozaizai1** [comment]
已经在cat端和螺端共同测试 cat端可以螺端不行

**Comment by timi137137** [comment]
等你学会好好填表再说
