### ISSUE TITLE
发生在ArclightSpecialRecipe转化为CookingRecipe时出现ClassCastException

### ISSUE THREAD

**Issue by Viola-Siemens** [IzzelAliz/Arclight#651]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.5

### OS & Java versions

os: windows, java: 18.0.1

### Plugins and Mods

```raw
插件：在没有安装任何插件时可以发生。
模组：绿宝石工艺v3.2（及其前置TerraBlender v1.1.0.99及以上）。
下载链接：https://www.mcmod.cn/download/6322.html、https://www.curseforge.com/minecraft/mc-mods/terrablender/files
请不要下载EC v3.3，因为绿宝石工艺v3.3为了兼容Arclight已经修改了继承链和实现方法，但我相信不止有这一个模组采用这种继承方法，因此希望您能够修改这一bug。
```

### Description

英语不好就用汉语描述了。
如果模组中添加一种熔炉方块，其Block继承了AbstractFurnaceBlock（见[GlassKilnBlock](https://github.com/Viola-Siemens/EmeraldCraftMod/blob/Forge-1.18.2_3.1/src/main/java/com/hexagram2021/emeraldcraft/common/blocks/workstation/GlassKilnBlock.java)），BlockEntity（也即你们或许更熟悉的TileEntity这个名字）继承了AbstractFurnaceBlockEntity（见[GlassKilnBlockEntity](https://github.com/Viola-Siemens/EmeraldCraftMod/blob/Forge-1.18.2_3.1/src/main/java/com/hexagram2021/emeraldcraft/common/blocks/entity/GlassKilnBlockEntity.java)），Recipe也继承了AbstractCookingRecipe（见[GlassKilnRecipe](https://github.com/Viola-Siemens/EmeraldCraftMod/blob/Forge-1.18.2_3.1/src/main/java/com/hexagram2021/emeraldcraft/common/crafting/GlassKilnRecipe.java)），是非常规范的封装。

而如果此时在Arclight服务器中使用这个新熔炉方块进行烧炼物品，会引起反复服务器崩溃，因此这个bug对arclight服务器是及其致命的。

### Step to reproduce

1. 首先安装Arclight对应版本，无需添加插件，安装绿宝石工艺v3.2（注意不要安装v3.3）和TerraBlender≥v1.0.99。
2. 运行服务器并使用客户端连接并进入世界。
3. 使用玻璃窑（注册名为emeraldcraft: glass_kiln）烧炼玻璃（和熔炉一样，上面放置任意沙子，下面放置任意染料如木炭）即可引起崩溃。
4. 再次进入服务器后仍然崩溃，错误报告相似。

使用forge、spigot等并不能重现这一问题。

个人推测的解决方法：在进行强制类型转换前增加instanceof判断。

非常喜欢您开发的Arclight，希望能早日改进这一bug，让服务器更稳定、支持更多模组的使用！

### Logs

https://paste.ubuntu.com/p/HR9kCqrHZq/plain/

**Comment by IzzelAliz** [comment]
下次有问题可以先报给我而不是先报给Mod作者

哦你就是作者啊，那没事了，可以喊用户直接报给我

**Comment by CornWorld** [comment]
实际上就是他用的时候把服务器崩了 lol
