### ISSUE TITLE
Lib's Disguises issue

### ISSUE THREAD

**Issue by Ajneb97** [IzzelAliz/Arclight#654]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.5

### OS & Java versions

Windows 11, java 17.0.2

### Plugins and Mods

```raw
Mods: None
Plugins: MythicMobs, ProtocolLib, Lib's Disguises
```

### Description

When I put the plugin Lib's Disguises to an Arclight server, players won't be able to do anything. They can't drop items, they can't see the tab, the skin is not renderer, anything. The server still runs, it seems the chat is the only thing working. When I remove Lib's Diguises, everything starts working correctly again. The console doesn't throw any errors.

I am looking a solution for this, since I require to create mobs using MythicMobs and Lib's Disguises.

### Step to reproduce

1. Just join the game with these plugins installed.

**Comment by IzzelAliz** [comment]
Can you reproduce this with latest dev build?
