### ISSUE TITLE
[1.18] Minecord won't load

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#656]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.6-SNAPSHOT-9508543

### OS & Java versions

Windows 11, java 17.0.2

### Plugins and Mods

```raw
Minecord
```

### Description

Minecord plugin does not load

### Step to reproduce

1. Install Minecord and start the server

### Logs

https://pastebin.com/Xs7XMYQe

**Comment by timi137137** [comment]
you need report to mod author, seems to be mod problem
