### ISSUE TITLE
[1.18] Donkeys wipe out their items on chest

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#657]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.6-SNAPSHOT-9508543

### OS & Java versions

Windows 11, java 17.0.2

### Plugins and Mods

```raw
none
```

### Description

When you put items on a donkey's chest, they wipe out after you dismount from the donkey

### Step to reproduce

1. Spawn a donkey and become best friends forever
2. Click the donkey with a chest
3. get in the donkey and open its inventory
4. Put some items in it
5. Dismount from the donkey and mount again

**Comment by muriplz** [comment]
They do drop the items when killed though. If you fill the inventory lots of times and you kill it, it drops all the items that you are introducing

**Comment by EricApostal** [comment]
This sounds similar to my own report, #658 . I wonder if something funky is going on with how chests work in general.

**Comment by muriplz** [comment]
yeah it might, your issue can have a workaround using barrels if you didnt know. I also have same issue as yours posted

**Comment by timi137137** [comment]
link #658
