### ISSUE TITLE
[1.16.5] Incompatibility with Blue Skies

### ISSUE THREAD

**Issue by Shybella** [IzzelAliz/Arclight#659]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.24-SNAPSHOT

### OS & Java versions

Windows Server 2019

### Plugins and Mods

```raw
BetterMC 1.16.5 - v57.5
GriefDefender 2.2.1 Bukkit
Luckperms
```

### Description

Blue Skies mod seems to break something in Arclight. Plugins like GriefDefender will not work and Essentialsx will give an error when running the command '/gc'

### Step to reproduce

1. Install BetterMC 1.16.5 or blue_skies-1.16.5-1.1.3 from Curseforge.
2. Install Arclight
3. Install 2.2.1 GriefDefender bukkit
4. Attempt to create a claim

### Logs

[2022-07-19-2.log](https://github.com/IzzelAliz/Arclight/files/9155386/2022-07-19-2.log)
[debug-1.log](https://github.com/IzzelAliz/Arclight/files/9155387/debug-1.log)

### Server pack link (Optional)

(https://www.curseforge.com/minecraft/modpacks/better-mc-modpack/files/3871784)

**Comment by timi137137** [comment]
`java.lang.RuntimeException: StructurePiece "net.minecraft.world.gen.feature.structure.MineshaftPieces$Room": "net.minecraft.world.gen.feature.structure.IStructurePieceType$$Lambda$2346/200871160@41b8e985" missing ID Mapping, Modder see MapGenStructureIO` maybe problem is here

**Comment by IzzelAliz** [comment]
This mod seems not properly registering their dimensions and structures. Ask their devs.
