### ISSUE TITLE
[1.18.X] 神化（Apotheosis）模组修改铁砧维修等级上限的mixin冲突

### ISSUE THREAD

**Issue by yanang007** [IzzelAliz/Arclight#663]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.6-SNAPSHOT-7128c9d8

### Java 版本 | 操作系统

openjdk 17 | Windows 10

### 相关 Mod/插件 的名称及版本

```raw
plugins:
 
mods:
Apotheosis-1.18.2-5.3.6
Placebo-1.18.2-6.4.1
```

### 错误描述

Apotheosis通过在AnvilMenu里面替代所有的值为40的int常量来修改铁砧的维修等级上限[AnvilMenuMixin.java](https://github.com/Shadows-of-Fire/Apotheosis/blob/5dd04d6f1e209a52a452382e81e8be39ff930e22/src/main/java/shadows/apotheosis/mixin/AnvilMenuMixin.java#L9-L17)
```
@Mixin(AnvilMenu.class)
public class AnvilMenuMixin {

	@ModifyConstant(method = "createResult()V", constant = @Constant(intValue = 40))
	public int apoth_removeLevelCap(int old) {
		return Integer.MAX_VALUE;
	}

}
```
这似乎与arclight的hook冲突了，似乎替换不了这里的常量
https://github.com/IzzelAliz/Arclight/blob/76530963d9e5abdbbe2e291e14e8c6f7d8f94a9d/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/world/inventory/RepairContainerMixin.java#L27-L38

我目前的workaround是在自己的fork中将maximumRepairCost改高，确认问题可以临时解决，因此优先级不是非常高。

### 复现步骤

1. 安装Apotheosis及其前置Placebo，参考#626的方法移除冲突mixin
2. 启动服务器
3. 进入游戏，在铁砧上任意附魔一个物品直到经验消耗超过39级
4. 即使经验足够，也无法继续附魔，放进待附魔物品和附魔书后会短暂出现附魔预览和等级消耗，然后立刻消失

期望行为：可以继续附魔，允许消耗39级以上的经验进行附魔

### 报错信息

https://paste.ubuntu.com/p/Vnk6Y9p3xV/

**Comment by timi137137** [comment]
欢迎pr
