### ISSUE TITLE
创世神插件无法正常运行，以及地皮插件！！！！！

### ISSUE THREAD

**Issue by alili2022** [IzzelAliz/Arclight#672]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

1.18.2

### Java 版本 | 操作系统

18

### 相关 Mod/插件 的名称及版本

```raw
Plugins (33): LuckPerms, CrazyAuctionsPlus, LaggRemover, ProtocolLib, NoSpawnChunks, AllMusic, BanItem, QiMengBindQQ, SIWorldProtection, Vault, PoetryGame, WorldEdit, PlaceholderAPI, IridiumSkyblock, AdvancedBan, LocketteX, NeverLag, PlotSquared, PlayerPoints, Multiverse-Core, TrMenu, Citizens, JetsPrisonCells, TAB, AncientGates, ItemJoin, DemonMarket, PlayerKits, MiaoChat, CMILib, CMI, Residence, PlayerRace
```

### 错误描述

不兼容地皮插件PlotSquared
创世神插件这些插件都是最新版！！

### 复现步骤

正常安装地皮插件以及地皮插件依赖的创世神插件

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/9227811/latest.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/9227811/latest.log)

**Comment by timi137137** [comment]
去看FAQ

**Comment by alili2022** [comment]
我用过常见问题里的那个啊，没有效果还是用不了创世神...
