### ISSUE TITLE
1.19.1 客户端进入服务器提示Invalid payload REGISTER

### ISSUE THREAD

**Issue by LingYily** [IzzelAliz/Arclight#673]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.1-1.0.0-SNAPSHOT-bfd9c1c3

### Java 版本 | 操作系统

17

### 相关 Mod/插件 的名称及版本

```raw
无任何插件与mod
```

### 错误描述

客户端在加载forge的情况下无法进入服务器
提示Invalid payload REGISTER
在不加载forge的情况下则可以进入

### 复现步骤

安装最新版arclight 客户端forge版本为42.0.0
搭建好服务端后直接进入

### 报错信息

[报错信息.txt](https://github.com/IzzelAliz/Arclight/files/9234300/default.txt)

### 复现用压缩包下载链接(可选)

无

**Comment by timi137137** [comment]
？要不要那么快啊，这才发布多久(
