### ISSUE TITLE
群峦传说 次时代 （1.18.2）中的起火器在服务器中无法长按右键点火，但是本地中可以。

### ISSUE THREAD

**Issue by xlxyvergil** [IzzelAliz/Arclight#676]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [ ] 已为所有插件及模组安装依赖
- [ ] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.6.jar

### Java 版本 | 操作系统

java17

### 相关 Mod/插件 的名称及版本

```raw
mod：TerraFirmaCraft-Forge-1.18.2-2.0.32-alpha.jar
```

### 错误描述

群峦传说 次时代 （1.18.2）中的起火器在服务器中无法长按右键点火，但是本地中可以。
群峦官方issues回复 We do not support using custom server software, as they tend and have in the past caused issues with TFC mechanics. Unless you can reproduce with a clean Forge install there's not much we can do. You may have luck reporting the issue to the server software team.

### 复现步骤

1.服务器中安装 群峦传说 次时代mod
2.客户端内获得起火器（创造或者制作出来都行）
3.长按右键，无法生效

### 报错信息

无报错

**Comment by heipiao233** [comment]
no stale
