### ISSUE TITLE
1.16.3版本合成物不可见

### ISSUE THREAD

**Issue by C5bb** [IzzelAliz/Arclight#68]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.7] 

* **你确认这是最新版吗** [是_]

### 错误描述

1.进入服务器 按E打开个人合成 合成物品 放置一个木头 你会发现一点反应都没有，点击结果栏,木板就到你手里了.  合成好的物品是隐形且不可见的,
此图是多人模式下场景
https://uploader.shimo.im/f/RxuZmH1Pq2nH8tM1.png!thumbnail

**可在 Forge 复现** [是]

**Comment by IzzelAliz** [comment]
无法复现，可以尝试用最新构建测试一下
