### ISSUE TITLE
Chat is broken/invisible in 1.18.2 with certain common plugins

### ISSUE THREAD

**Issue by ecoterrorist** [IzzelAliz/Arclight#683]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.7-SNAPSHOT-c78fe148

### OS & Java versions

Windows 10, Java 18.0.2

### Plugins and Mods

```raw
Plugins (4): Vault, PlaceholderAPI, ProtocolLib, InteractiveChat

Mod List:
• minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1
• minecraft forge-1.18.2-40.1.59-universal.jar : forge (40.1.59) - 1
• arclight arclight-1.18.2-1.0.7-SNAPSHOT-c78fe148.jar : arclight (1.18.2-1.0.7-SNAPSHOT-c78fe148) - 1
```

### Description

Chat is completely invisible in-game. All in-game chat settings are normal/default (opacity, size, etc). This ONLY happens when these 4 plugins are used together. My unprofessional guess is that ProtocolLib is the problem, although when used _alone_ ProtocolLib seems to be working fine and chat is normal.

To reproduce, simply run a clean arclight 1.18.2 server (either latest release OR latest dev build) with these 4 basic plugins listed and you will be unable to see chat in-game.

### Step to reproduce

1. Install latest available versions of Vault, ProtocolLib, PlaceholderAPI, and InteractiveChat on a clean Arclight 1.18.2 server
[plugins.zip](https://github.com/IzzelAliz/Arclight/files/9275661/plugins.zip)
2. Open game, send a message or run a command.
3. Observe whether or not chat is visible

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/9275664/latest.log)

**Comment by IzzelAliz** [comment]
Please check if this is fixed.

**Comment by Trampa3** [comment]
no solucionado para mi
