### ISSUE TITLE
创世神和地皮插件无法正常使用！！！！

### ISSUE THREAD

**Issue by alili2022** [IzzelAliz/Arclight#684]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

1.18.2

### Java 版本 | 操作系统

18

### 相关 Mod/插件 的名称及版本

```raw
LuckPerms, CrazyAuctionsPlus, LaggRemover, ProtocolLib, ArclightPatcher, NoSpawnChunks, AllMusic, BanItem, QiMengBindQQ, SIWorldProtection, Vault, PoetryGame, WorldEdit, PlaceholderAPI, AdvancedBan, LocketteX, PlotSquared, PlayerPoints, Multiverse-Core, TrMenu, Citizens, JetsPrisonCells, TAB, AncientGates, ItemJoin, DemonMarket, PlayerKits, MiaoChat, CMILib, CMI, Residence, PlayerRace
```

### 错误描述

创世神插件无法正常工作，导致需要创世神插件作为前置的插件均无法正常运行！！！！！
WIKI的常见问题的解决方法尝试过了！不行！！！！！！！！！！！

### 复现步骤

我看过了FQA，里面说下载patcher-load并安装插件，我安装了但是创世神还是无法正常运行！，于是我下载了对应的源。重新编译导出了，还是无法正常运转！

**Comment by heipiao233** [comment]
Use https://github.com/ArclightPowered/patcher

**Comment by mlus-asuka** [comment]
确实用不了。会说版本不支持
