### ISSUE TITLE
[1.18 Vanilla Bug] /kill @e[distance=<amount>] Does not work

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#685]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.6-SNAPSHOT-9508543

### OS & Java versions

Windows 11, java 17.0.2

### Plugins and Mods

```raw
No mods
No plugins
```

### Description

distance attibute on /kill command does not work properly. The output is always "No entity found"

### Step to reproduce

1. spawn an entity on an enclosed area
2. get close and do /kill @e[distance=20]

**Comment by Shybella** [comment]
Try this `/minecraft:kill @e[type=minecraft:pig, distance=..10]`

So, `/minecraft:kill @e[type=distance=..20]`

include the two periods

**Comment by muriplz** [comment]
By using the two periods works. Thank you 👍
