### ISSUE TITLE
[1.16.5]安装CustomNPC 后 熔炉/高炉/烟熏炉 煅烧物品 产物无法被正常堆叠

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#689]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-SNAPSHOT（最新）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
CustomNPCs-1.16.5.20220728snapshot（最新版本）
```

### 错误描述

安装CustomNpc（自定义NPC）后

使用 熔炉/高炉/烟熏炉 等煅烧物品时
当容器里煅烧出产物时，打开容器，产物无法被继续正常产出；取出容器内的产物到背包，可以被继续正常产出/叠加

例如：用铁矿煅烧铁锭，在熔炉产出槽位里已经有5个铁锭的情况下，打开熔炉，新的铁锭无法被产出，怎么烧都一直保持5个，取出熔炉的铁锭，放进背包，新的铁锭可以被正常地堆叠和产出

当产物无法被正常叠加时，原矿不会消失，但是燃料会被持续消耗

### 复现步骤

1、安装CustomNPC
2、使用 熔炉/高炉/烟熏炉 煅烧
3、熔炉内有产物时，打开熔炉，不取出里面的产物
4、后续无法产出新的产物，无法堆叠（产物还是原来的数量）
5、取出熔炉内的产物，熔炉工作恢复正常（高炉/烟熏炉同理）

**Comment by qyl27** [comment]
请测试此问题是否在最新的构建中被修复

**Comment by luoxiawuchen** [comment]
> 请测试此问题是否在最新的构建中被修复

此问题已修复，感谢

另请问 355构建以后是不需要在plugins安装创世神补丁了吗？
[1.16-355](https://ci.appveyor.com/project/IzzelAliz/arclight-16/builds/44771179)

嗯，确实如此，已自行测试，补丁生效，创世神正常运行，谢谢。
