### ISSUE TITLE
[1.18.2]Authme 和 ProtocolLib 会导致看不见物品

### ISSUE THREAD

**Issue by wcz0** [IzzelAliz/Arclight#691]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [x] unable to reproduce in Spigot
- [ ] unable to reproduce in Forge

### Arclight version

1.18.2-1.0.6

### OS & Java versions

OS: ubuntu20 JDK: openjdk-17.0.4

### Plugins and Mods

```raw
LuckPerms, OpenInv, BlockLocker, PlaceholderAPI, MessageAnnouncer, ProtocolLib, SkinsRestorer, DeluxeTags, PistonMOTD, EasyBackupCore, AntiBuild, EpicPluginLib, NBTAPI, JustOneMorePlus, Vault, PlayMoreSounds, WorldEdit, TogglePvp, IllegalStack, EasyBackup, WorldGuard, ItemEdit, Multiverse-Core, Citizens, DeathMessages, TAB, ParticleHats, CoreProtect, WorldEditSelectionVisualizer, RedLimiter, AuthMe, CMILib, LiteBans, CMI, EntityDetection, MobFarmManager, Residence, FastLogin, TradeMe, PlugManX (PlugMan)
```

### Description

Authme 和 ProtocolLib 一起用会导致看不见物品
两者单独使用没有问题
spigot端上没有这个问题
Using Authme and ProtocolLib together will cause items to be invisible, 
there is no problem with using them separately.
No problem on the Spigot

**Comment by bendeguzbagi** [comment]
I also have an issue with ProtocolLib. If I put it with ChatControl Red i don't have ingame chat at all.

**Comment by IzzelAliz** [comment]
请测试是否已经修复

**Comment by wcz0** [comment]
> 请测试是否已经修复

没有修复, 测试版本 1.18-162

**Comment by wcz0** [comment]
最新测试版本已修复
