### ISSUE TITLE
与PlotSquared 6 兼容问题，创建地皮世界时报错（插件依赖WorldEdit但已经安装最新patch且WE已经可以正常使用）

### ISSUE THREAD

**Issue by 213LD** [IzzelAliz/Arclight#694]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.7-SNAPSHOT-c78fe148

### Java 版本 | 操作系统

系统:windows server 2019 Java: openjdk version "17.0.4" 2022-07-19 LTS

### 相关 Mod/插件 的名称及版本

```raw
可能相关插件:ArclightPatcher, WorldEdit, PlotSquared, Multiverse-Core
相关MOD:WorldEdit
```

### 错误描述

在安装了最新版的worldEdit(7.2.12)，最新付费版的PlotSquared v6(6.9.4)，还有按照FAQ安装了专用patch(1.0.0-1.18.2)后，经测试WorldEdit插件已经可以正常使用，但在按照plotsquared v6 wiki试图创建地皮世界(/plotme setup ->/plotme setup PlotSquared ->/plotme setup normal )时报错，无法正常创建地皮世界，报错内容为方便查阅，从latest.log中提取了我个人认为可能比较重要的插件自己报错的部分如下
[208月2022 13:27:16.910] [Server thread/ERROR] [STDERR/]: com.plotsquared.google.ProvisionException: Unable to provision, see the following errors:

1) [Guice/NullInjectedIntoNonNullable]: null returned by binding at HybridPlotWorldFactory.create()
 but the 2nd parameter of HybridPlotWorld.<init>(HybridPlotWorld.java:101) is not @Nullable
  at HybridPlotWorldFactory.create(HybridPlotWorldFactory.java:1)
  at HybridPlotWorld.<init>(HybridPlotWorld.java:101)
      \_ for 2nd parameter
  while locating HybridPlotWorld annotated with @UniqueAnnotations$Internal(1)

Learn more:
  https://github.com/google/guice/wiki/NULL_INJECTED_INTO_NON_NULLABLE

1 error

Full classname legend:

HybridPlotWorld:            "com.plotsquared.core.generator.HybridPlotWorld"
HybridPlotWorldFactory:     "com.plotsquared.core.inject.factory.HybridPlotWorldFactory"
UniqueAnnotations$Internal: "com.plotsquared.google.internal.UniqueAnnotations$Internal"

End of classname legend:

### 复现步骤

1.安装最新版PlotmeSquared(付费版6.9.4)

2.进入服务器创建地皮世界:
   /plotme setup

   /plotme setup PlotSquared

   /plotme setup normal

3.提示报错

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/9386291/latest.log)

**Comment by 213LD** [comment]
抱歉issue可能和#684重复，但对方没有提供任何有用信息，遂新开了一个issue，附上了复现过程，插件环境和完整log，因为插件付费性质，晚上会打包服务端上传供开发者测试!

**Comment by timi137137** [comment]
patcher这边在讨论是否合并到主分支中，因此目前相关问题请看 #524 其他同类问题一概关闭不做回复
