### ISSUE TITLE
ars nouveau console spam

### ISSUE THREAD

**Issue by ThirtyTwelveNor** [IzzelAliz/Arclight#695]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.6-7e754e7e

### OS & Java versions

Ubuntu 20.04.4 linux 5.4.0-124-generic x86_64 java version 17.0.2+8-86

### Plugins and Mods

```raw
ars_nouveau-1.18.2-2.7.4.jar
```

### Description

console getting spammed with
[Arclight]: No owner for inventory com.hollingsworth.arsnouveau.common.block.tile.ArcanePedestalTile@**_random uuid_**/class com.hollingsworth.arsnouveau.common.block.tile.ArcanePedestalTile

![image](https://user-images.githubusercontent.com/25280511/186009318-e8d15b0a-9db5-4a02-a5e3-0dd71a70e584.png)

### Step to reproduce

1. install ArsNouveau
2. place down the most basic thing you need to be able to use this mod(arcane pedestal)
3. look at console

**Comment by timi137137** [comment]
there's nothing we can do, because the problem is ArsNouveau
