### ISSUE TITLE
[1.18.2] ChatControl Red does not start.

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#696]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.6-SNAPSHOT

### OS & Java versions

OS: Ubuntu 20.04 Java: openjdk 17.0.4 2022-07-19

### Plugins and Mods

```raw
Mods: None
Plugins: ChatControlRed, LuckPerms, PlaceholderAPI, ProtocolLib, Vault
```

### Description

I tried to start archlight 1.18 server with ChatControl Red but the plugin is does not start. I have all the required dependencies.

### Step to reproduce

1. Setup basic arclight server
2. Install dependencies
3. Install ChatControlRed (i can provide .jar)
4. Start server

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/9409519/latest.log)

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/186231947-48bd4dd4-a90d-46f8-9beb-18f64696b41b.png)
this problem is for ChatControlRed
