### ISSUE TITLE
[1.18.2] Griefdefender sneak while placing bypasses claims.

### ISSUE THREAD

**Issue by Shybella** [IzzelAliz/Arclight#700]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2 - 1.0.7

### OS & Java versions

OpenJDK 17

### Plugins and Mods

```raw
Griefdefender 2.2.1
LuckPerms
```

### Description

Sneaking while placing should be blocked however the event is not detected by Griefdefender and thus allowing the block to be placed. However placing a block without sneaking does prevent the block from being placed. 

### Logs

https://griefdefender.github.io/debug/?iprmv9F249

**Comment by Shybella** [comment]
This is caused by Quarks ReachAround feature

**Comment by heipiao233** [comment]
An error occurred whilst loading.

**Comment by heipiao233** [comment]
I can't reproduce.
![2022-11-08_17 15 14](https://user-images.githubusercontent.com/81846300/200524673-b9c04a71-4b66-48b9-a57d-050fc9feaec6.png)
Are you sure all plugins and mods are up to date? I'm using GriefDefender 2.2.5. Please try again with that version. And are you using any Forge mods?

**Comment by heipiao233** [comment]
Can reproduce.

**Comment by heipiao233** [comment]
It looks like Quark's fault.

**Comment by heipiao233** [comment]
In fact, ReachAround can bypass all the permission checking mods and plugins.

**Comment by Shybella** [comment]
Yes, this is all quarks problem. Not Arclight, should have closed this.
Thank you.

**Comment by heipiao233** [comment]
Quark#3950 fixed this in 1.19.2.

**Comment by heipiao233** [comment]
I wrote a mod that fixes this bug: https://modrinth.com/mod/fix-quark-3951. Install that and try again.

**Comment by Shybella** [comment]
This is awesome, thank you
