### ISSUE TITLE
CC-Modded makes CC-Tweaked output weird symbols on its displays. | Unplayable 

### ISSUE THREAD

**Issue by Zardexd** [IzzelAliz/Arclight#701]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Version arclight-1.18.2-1.0.6-7e754e7e Build Date 2022-07-28 14:36:31

### OS & Java versions

Windows 11 x64 Java: Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86) 2022-01-18 LTS

### Plugins and Mods

```raw
[22:25:04 INFO]: Mod List:
• minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1
• minecraft forge-1.18.2-40.1.59-universal.jar : forge (40.1.59) - 1
• mods_folder advancedperipherals-1.18.2-0.7.16b.jar : advancedperipherals (0.7.16b) - 1
• mods_folder cc-tweaked-1.18.2-1.100.9.jar : computercraft (1.100.9) - 1
• arclight arclight-1.18.2-1.0.6-7e754e7e.jar : arclight (1.18.2-1.0.6-7e754e7e) - 1

[21:55:44 INFO] [Console]: Plugins (0):
```
**cc-modded-1.18.2-1.100.4.jar is in folder but its not displayed for some reason.**

### Description

CC:Tweaked computers output weird symbols on their displays when CC:Modded is installed.
Advancedperipherals-1.18.2-0.7.16b.jar doesn't affect this behavior.

![2022-08-25_21 49 26](https://user-images.githubusercontent.com/40138317/186751707-d1aa698a-6efc-4cf9-9017-ac5024cecfed.png)
![2022-08-25_22 22 03](https://user-images.githubusercontent.com/40138317/186751712-936be722-0993-48b3-9d90-5f23bbdfdacb.png)
![2022-08-25_22 23 02](https://user-images.githubusercontent.com/40138317/186751714-fe701a55-68f7-4a38-b7c3-6badcc67e8e6.png)

https://www.curseforge.com/minecraft/mc-mods/cc-modded
https://www.curseforge.com/minecraft/mc-mods/cc-tweaked

### Step to reproduce

1. Install CC:Tweaked with cc-modded-1.18.2-1.100.4.jar
2. Join the game
3. Open any computer-block or attach displays to it. 

### Logs

https://pastebin.com/zGLFicMA

**Comment by Zardexd** [comment]
Seems like mod isn't even loaded properly, i don't see any thing being added, its not in the /forge mods lists and the only thing it does it makes display's go crazy, also as i remember this mod allowed you to paint your computers to a different colors so it changed their appearance and console i guess as well, so thats where symbols come from i suppose, they meant to be a workaround to apply colors. ( My theory )

**Comment by IzzelAliz** [comment]
Please provide full debug.log.

**Comment by Zardexd** [comment]
> Please provide full debug.log.

My bad, for some reason thought i attached debug.log but actually i didn't. 
https://pastebin.com/i7KpzceR
