### ISSUE TITLE
[1.18.2] ChatControl Red works, but no ingame chat when ProtocolLib installed

### ISSUE THREAD

**Issue by ghost** [IzzelAliz/Arclight#704]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.6

### OS & Java versions

OS: macOS 12.5.1 Java: openjdk 17.0.4 2022-07-19

### Plugins and Mods

```raw
Plugins:
 - Vault
 - ProtocolLib
 - ChatControl Red
```

### Description

**Update: I found out, ProtocolLib causes the no ingame chat issue. The plugin works without it but the remove chat message with click requires it.**

### Step to reproduce

1. Install the provided serverpack.
2. Run the server.

### Logs

[debug.log](https://github.com/IzzelAliz/Arclight/files/9439461/debug.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/9439462/latest.log)

### Server pack link (Optional)

https://drive.google.com/file/d/1x9sfJw18blMHVKB4F8AShFSBH1kViXVD/view?usp=sharing

**Comment by IzzelAliz** [comment]
Duplicate with #683.
