### ISSUE TITLE
[1.18.2]安装以下mod服务器无法启动

### ISSUE THREAD

**Issue by SkyIce0229** [IzzelAliz/Arclight#706]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.6-7e754e7e

### Java 版本 | 操作系统

win10 x64 java18

### 相关 Mod/插件 的名称及版本

```raw
apathy-1.18.2-forge-2.4
minetogether-forge-1.18.2-5.2.7
radium-0.7.10
```

### 错误描述

安装上述mod都会导致服务器无法启动

### 复现步骤

1.安装其中一个mod，2.启动服务器

### 报错信息

https://paste.ubuntu.com/p/wrrDyzgdYS/

**Comment by IzzelAliz** [comment]
那就不要用 jdk18
