### ISSUE TITLE
server crashed at starting with create 0.5.0d

### ISSUE THREAD

**Issue by dg981001** [IzzelAliz/Arclight#707]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7-SNAPSHOT-d0abf77

### OS & Java versions

OS:Windows 11 java:java 17.0.4.1 2022-08-18 LTS

### Plugins and Mods

```raw
plugins:
ServerBackup, ArclightPatcher, LuckPerms, BlueMap, UberEnchant, Essentials, InvSeePlusPlus, EssentialsSpawn, EssentialsChat, BlueMapOfflinePlayerMarkers

mods:
flywheel-0.6.5
create-0.5.0d
```

### Description

arclight bukkit doesn't work with create mod 0.5.0d

I can't understand why it is happened becaused of my lack of knowledge of java.
So, just describe simple situation.

Yes, bukkit just crashing with create mod 0.5.0d

It works with pure forge server.
But, not working with arclight bukkit

I was tried with forge 40.1.69 and 40.1.73, 40.1.74 

### Step to reproduce

1. install create - 0.5.0d (https://www.curseforge.com/minecraft/mc-mods/create/files/3934676) with flywheel 0.6.5 (https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3934664)
2. just run server using arclight bukkit 

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/9474942/latest.log)
[crash-2022-09-02_13.45.29-fml.txt](https://github.com/IzzelAliz/Arclight/files/9474943/crash-2022-09-02_13.45.29-fml.txt)
[debug.log](https://github.com/IzzelAliz/Arclight/files/9474944/debug.log)

**Comment by IzzelAliz** [comment]
You have a mod "toofast", remove it.

**Comment by LK-LAB** [comment]
toofast mod? I didn't contain that mod.

Maybe I upload other log files.

please check this files.

Thanks.

[crash-2022-09-02_21.44.51-fml.txt](https://github.com/IzzelAliz/Arclight/files/9477958/crash-2022-09-02_21.44.51-fml.txt)
[debug.log](https://github.com/IzzelAliz/Arclight/files/9477959/debug.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/9477960/latest.log)

**Comment by dg981001** [comment]
> ### I have confirmed that ...
> * [x]  Arclight is up to date
> * [x]  all dependencies are installed
> * [x]  all plugins and mods are up to date
> * [x]  unable to reproduce in Spigot
> * [x]  unable to reproduce in Forge
> 
> ### Arclight version
> arclight-forge-1.18.2-1.0.7-SNAPSHOT-d0abf77
> 
> ### OS & Java versions
> OS:Windows 11 java:java 17.0.4.1 2022-08-18 LTS
> 
> ### Plugins and Mods
> ```
> plugins:
> ServerBackup, ArclightPatcher, LuckPerms, BlueMap, UberEnchant, Essentials, InvSeePlusPlus, EssentialsSpawn, EssentialsChat, BlueMapOfflinePlayerMarkers
> 
> mods:
> flywheel-0.6.5
> create-0.5.0d
> ```
> 
> ### Description
> arclight bukkit doesn't work with create mod 0.5.0d
> 
> I can't understand why it is happened becaused of my lack of knowledge of java. So, just describe simple situation.
> 
> Yes, bukkit just crashing with create mod 0.5.0d
> 
> It works with pure forge server. But, not working with arclight bukkit
> 
> I was tried with forge 40.1.69 and 40.1.73, 40.1.74
> 
> ### Step to reproduce
> 1. install create - 0.5.0d (https://www.curseforge.com/minecraft/mc-mods/create/files/3934676) with flywheel 0.6.5 (https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3934664)
> 2. just run server using arclight bukkit
> 
> ### Logs
> [latest.log](https://github.com/IzzelAliz/Arclight/files/9474942/latest.log) [crash-2022-09-02_13.45.29-fml.txt](https://github.com/IzzelAliz/Arclight/files/9474943/crash-2022-09-02_13.45.29-fml.txt) [debug.log](https://github.com/IzzelAliz/Arclight/files/9474944/debug.log)
> 
> ### Server pack link (Optional)
> _No response_



> You have a mod "toofast", remove it.

toofast mod? I didn't contain that mod.

Maybe I upload other log files.

please check this files.

Thanks.

[crash-2022-09-02_21.44.51-fml.txt](https://github.com/IzzelAliz/Arclight/files/9477958/crash-2022-09-02_21.44.51-fml.txt)
[debug.log](https://github.com/IzzelAliz/Arclight/files/9477959/debug.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/9477960/latest.log)
