### ISSUE TITLE
1.16.3-1.0.8與Apotheosis不兼容

### ISSUE THREAD

**Issue by Edel-Lilies** [IzzelAliz/Arclight#71]
### 我正在运行

* **Arclight** [arclight-1.16.3-1.0.8] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [否]

* **Java** [15.0.1 or AdoptOpenJDK15.0.1+9] 

* **操作系统** [Windows10 2004]

* **插件列表** 

* **Mod 列表** Apotheosis-1.16.3-4.4.1     Placebo-1.16.3-4.3.3      

### 重现步骤

1. 安装 Apotheosis-1.16.3-4.4.1     Placebo-1.16.3-4.3.3      
2. 进入服务器后 自動創建世界
3. 停留在14% 服務器窗口消失但並沒有Crash

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[https://paste.ubuntu.com/p/yQNBds6NsD/]

**Comment by IzzelAliz** [comment]
請提供日誌

**Comment by Edel-Lilies** [comment]
[latest.log](https://github.com/IzzelAliz/Arclight/files/5485988/latest.log)
