### ISSUE TITLE
 Arclight 1.0.6 / Forge 40.1.76 / Mod: pollen-forge-1.4.9+1.18.2: Error processing class java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0

### ISSUE THREAD

**Issue by Shuro** [IzzelAliz/Arclight#710]
We got some Problems with Arclight 1.0.6, Forge 40.1.76 and pollen-forge-1.4.9+1.18.2.

Looks like a mixin error.  Hard to tell where the error is, if it is with forge, arclight or pollen.

Server log till error, server continues to run. 
https://mclo.gs/q3zWq61

**Comment by IzzelAliz** [comment]
Use latest dev.
