### ISSUE TITLE
Crash when using arclight on bukkit load [1.18.2]

### ISSUE THREAD

**Issue by Xplodin** [IzzelAliz/Arclight#711]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2-1.0.7-SNAPSHOT-7d2418fe

### OS & Java versions

ubuntu 18.04 java 17

### Plugins and Mods

```raw
Mods: ATM7 - 0.4.30
plugins: CMI CMILIB LUCKPERMS MOBMONEY SHOPS POWERBOARD VAULT XCONOMY
```

### Description

It worked before but now its stuck crashing when its loading bukkit

### Step to reproduce

install arclight
switch forge to .74
run with bukkit perms forward setting reverse??
was honestly trying to get bukkits perms on forge since luckperms can be ran as a forge mod

### Logs

https://paste.ubuntu.com/p/c6wTmDTpy6/

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3970086

**Comment by Xplodin** [comment]
nevermind about the perms thing it still crashes regardless

**Comment by IzzelAliz** [comment]
Please test if it is fixed.

**Comment by Xplodin** [comment]
It was something with libraries apparently. I somehow messed up the forge installation, reinstalled arclight, installed custom forge, and everything works now. 

Actually redact that. It was the latest version that broke. I thought it was libraries but i installed a earlier version as well

**Comment by Xplodin** [comment]
It is fixed. ty!
