### ISSUE TITLE
[Question] Does Arclight impact server Performance?

### ISSUE THREAD

**Issue by BelgianDev** [IzzelAliz/Arclight#713]

**Comment by heipiao233** [comment]
Maybe yes, see [mixins.arclight.impl.forge.optimization.json](https://github.com/IzzelAliz/Arclight/blob/1.19/arclight-common/src/main/resources/mixins.arclight.impl.forge.optimization.json)

**Comment by IzzelAliz** [comment]
Ask question in discussion or discord server, this is not a forum asking for support.
