### ISSUE TITLE
[1.18.2] Optimization question 

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#714]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7-SNAPSHOT.jar

### OS & Java versions

17 windows server 2020

### Plugins and Mods

```raw
-
```

### Description

The server is extremely unstable with a large amount of online, this is perhaps its main disadvantage! How do you like the idea to use Magma optimization or implement something of your own

**Comment by IzzelAliz** [comment]
Provide performance profile results before asking for support.
