### ISSUE TITLE
Performance issues with Villagers

### ISSUE THREAD

**Issue by Shybella** [IzzelAliz/Arclight#719]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2 - 1.0.7

### OS & Java versions

OpenJDK 17

### Plugins and Mods

```raw
BetterMC 1.18.2
Griefdefender
Luckperms
Spark
```

### Description

Villagers when attempting to sleep in beds: https://spark.lucko.me/DoQN3yxPBy

I changed POI in the Arclight config for villagers but still seeing bad performance from POI from villagers, 
https://prnt.sc/usFg1I9gV0yu

Spark: https://spark.lucko.me/HXXbIVS5Of

The report above is with just a couple villagers in a custom villager pen with beds near by, picture: https://prnt.sc/30MMBjfVNLvG

This can become a huge performance impact when 20ish people are online, is there anything that can be done to improve the performance of villagers? 

Thanks.

**Comment by XionioXMaster** [comment]
In fact, due to collision, your server will start to lag at 20-30 mobs in 1 point

**Comment by Shybella** [comment]
Nah, I can have 300 mobs up at a cost of 5-7MS tickloop. Collisions can be a issue though but that doesn't seem to be the main impact.

Villagers however is a different story.

**Comment by XionioXMaster** [comment]
> Nah, I can have 300 mobs up at a cost of 5-7MS tickloop. Collisions can be a issue though but that doesn't seem to be the main impact.
> 
> Villagers however is a different story.

https://www.spigotmc.org/resources/antivillagerlag.102949/ try it
Or https://www.curseforge.com/minecraft/mc-mods/perviaminvenire

**Comment by Shybella** [comment]
Tried antivillagerlag, did not solve the problem in a decent way, still occurs, I opened a report about it on their git a week or two ago.

perviaminvenire only works on pathfinding and in spark that isn't the cause of performance issues. I tried it however and did not notice any improvements, however with Minecolonies it does seem to work very well.

**Comment by XionioXMaster** [comment]
> Tried antivillagerlag, did not solve the problem in a decent way, still occurs, I opened a report about it on their git a week or two ago.
> 
> perviaminvenire only works on pathfinding and in spark that isn't the cause of performance issues. I tried it however and did not notice any improvements, however with Minecolonies it does seem to work very well.

Open spigot.yml and set       tick-inactive-villagers: **false** I'm not sure if this will help but very useful for servers

**Comment by Shybella** [comment]
> > Tried antivillagerlag, did not solve the problem in a decent way, still occurs, I opened a report about it on their git a week or two ago.
> > perviaminvenire only works on pathfinding and in spark that isn't the cause of performance issues. I tried it however and did not notice any improvements, however with Minecolonies it does seem to work very well.
> 
> Open spigot.yml and set tick-inactive-villagers: **false** I'm not sure if this will help but very useful for servers

Already set to false, also lowered spawning to reduce impact, it did improve things just by a small margin.

**Comment by Shybella** [comment]
I also changed villager POI to 20 in arclight.confg just to test and did not notice any improvement.

**Comment by Shybella** [comment]
You also can't have perviaminvenire server side only, it must be installed on the client too.

**Comment by XionioXMaster** [comment]
> You also can't have perviaminvenire server side only, it must be installed on the client too.

I know but I don't understand why

**Comment by IzzelAliz** [comment]
Please test with latest dev build.

**Comment by DonorKrovi** [comment]
Good! TPS 20!

**Comment by Shybella** [comment]
This is resolved, thank you.
