### ISSUE TITLE
Debugify 1.11.0 Forge 1.18.2 Errors for startup

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#720]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7-SNAPSHOT.jar

### OS & Java versions

17 windows server 2020

### Plugins and Mods

```raw
Plugins (15): MiniMOTD, LuckPerms, FartherViewDistance, HolographicDisplays, Vault, F3Name, ProtocolLib, Chatty, PlayerKits, TCPShield, CMILib, ChatBubbles, Pl-Hide-Pro, TAB, CMI

Mods: debugify-1.11.0-forge-1.18.2.jar only!
```

### Description

When starting the server, you can find an error, while the mod seems to work, I'm not sure about this but thought I'd let you know.

### Step to reproduce

Put mod and start server

### Logs

https://pastebin.com/yUN9x0LJ

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/190903294-470f1840-4a9c-405b-ac0c-236e3b4b354b.png)
hummm,i can't see error startup by debugify
