### ISSUE TITLE
无法使用刷怪蛋生成怪物

### ISSUE THREAD

**Issue by ZeroJoK114514** [IzzelAliz/Arclight#725]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [ ] 已为所有插件及模组安装依赖
- [ ] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-SNAPSHOT-65b545e

### Java 版本 | 操作系统

jdk-17 windows server

### 相关 Mod/插件 的名称及版本

```raw
无任何插件和模组
```

### 错误描述

使用服务器默认配置并进入服务器后
不能自然生成所有怪物，用刷怪蛋右键放置也不能生成

### 复现步骤

1.下载最新构建的Arclight服务端
2.使用Java17启动
3.进入服务器
4.选择任意怪物刷怪蛋，右键地面

### 报错信息

无报错

**Comment by IzzelAliz** [comment]
请检查是否修复
