### ISSUE TITLE
[1.16.5] #725补充，构建版本349及以上无法生成任何实体，无论是自然生成还是人为召唤

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#727]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-353（最新）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
未添加任何mod/插件
排除mod或插件影响
```

### 错误描述

这其实是对问题#725的补充
更新构建版本至349以上（包括349）
Fix shadow field type mismatch (https://github.com/IzzelAliz/Arclight/issues/622)
世界无法生成实体（任何类型，不限于怪物）
1、无法使用/summo 召唤
2、无法使用刷怪蛋生成
3、无法自然生成
4、已确定地图未开启和平模式

### 复现步骤

1、启动服务器
2、发现地图中不存在任何实体
3、召唤实体无效，但未出现错误警告

### 报错信息

无报错信息

**Comment by IzzelAliz** [comment]
请检查是否修复

**Comment by luoxiawuchen** [comment]
> 请检查是否修复

已修复，感谢
