### ISSUE TITLE
[1.18.2] Plhide Pro 2.5.5 Stopped working correctly on the latest Dev version

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#728]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7-SNAPSHOT.jar [1.18-160]

### OS & Java versions

17 windows server 2020

### Plugins and Mods

```raw
[20:40:03 INFO] [Console]: Plugins (15): MiniMOTD, LuckPerms, FartherViewDistance, HolographicDisplays, Vault, F3Name, ProtocolLib, Chatty, PlayerKits, TCPShield, CMILib, ChatBubbles, Pl-Hide-Pro, TAB, CMI

[20:40:14 INFO]: Mod List:
• minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1
• minecraft forge-1.18.2-40.1.80-universal.jar : forge (40.1.80) - 1
• arclight arclight-1.18.2-1.0.7-SNAPSHOT-b038f4d2.jar : arclight (1.18.2-1.0.7-SNAPSHOT-b038f4d2) - 1
>
```

### Description

I used this version before
https://ci.appveyor.com/project/IzzelAliz/arclight-18/builds/44672477

Maybe I'm wrong and she's a little older

The plugin should only output specified TAB commands to chat, but on the latest version [1.18-153] it no longer detects commands on the server! But they can be entered. I can provide you a plugin if you send me a message on discord, it costs money and I don't want it to be leaked

!♠ჯἶõῆἶõჯ♠#9523 **[I'm on the Arclight Discord channel]**

![image](https://user-images.githubusercontent.com/86433158/189731979-222b96b0-2a9b-4f61-949b-7d1e58b842ca.png)

P.S also after reloading the plugin there is an error, **/plhide reload**

### Step to reproduce

Add permission **plhide.group.default**

Now only commands that are in the config list should be in the chat

### Logs

https://mcpaste.com/8e3a236e832bc6f0c1ea15f58fdfd907

Full log: https://mcpaste.com/9052fd16f0623f9b0ff23f67c0964ebc

**Comment by IzzelAliz** [comment]
Ask plugin dev for a fix.
