### ISSUE TITLE
Aurora插件无法正确工作，iConomy插件无法工作

### ISSUE THREAD

**Issue by GavinArkell** [IzzelAliz/Arclight#731]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14

### Java 版本 | 操作系统

系统：Windows Server 2019 64bit，Java版本：dragonwell-17.0.4.0.4+8-GA

### 相关 Mod/插件 的名称及版本

```raw
Plugins (10): 
iConomy, 
Vault, 
LightAPI, 
Aurora, 
FinalEconomy,
LagAssist, 
Vegas, 
CMILib, 
AureliumSkills, 
Residence

• minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1
• mods_folder earth-F-穿草攻击 cleancut-mc1.18.2-4.0-forge.jar : cleancut (4.0) - 1
• mods_folder 兼容性检查-BetterCompatibilityChecker-1.1.14-build.26+mc1.18.2.jar : bcc (1.1.14-build.26+mc1.18.2) - 1
• mods_folder NEI-Top检测器-theoneprobe-1.18-5.1.0.jar : theoneprobe (1.18-5.1.0) - 1
• mods_folder 快速加载-Fastload-Reforged-1.1.6+1.18.2.jar : fastload (1.1.6+1.18.2) - 1
• mods_folder 树叶快速掉落-RapidLeafDecay-1.18.2-2.0.0.jar : rapid_leaf_decay (2.0.0) - 1
• mods_folder 更好的动作-player-animation-lib-forge-0.3.5.jar : playeranimator (0.3.5) - 1
• mods_folder NEI-jei-1.18.2-9.7.1.232.jar : jei (9.7.1.232) - 1
• mods_folder 视觉工作台-VisualWorkbench-v3.3.0-1.18.2-Forge.jar : visualworkbench (3.3.0) - 1
• mods_folder 物品高亮-Highlighter-1.18.1-1.1.2.jar : highlighter (1.1.2) - 1
• mods_folder Iceberg-1.18.2-1.0.44.jar : iceberg (1.0.44) - 1
• mods_folder 传送石碑-waystones-forge-1.18.2-10.1.0.jar : waystones (10.1.0) - 1
• mods_folder 旅行地图-journeymap-1.18.2-5.8.5-forge.jar : journeymap (5.8.5) - 1
• mods_folder 跳过栅栏-jumpoverfences-1.18-1.0.1.jar : jumpoverfences (1.18-1.0.1) - 1
• mods_folder 拼音搜索-jecharacters-1.18.2-4.3.5.jar : jecharacters (1.18.2-4.3.5) - 1
• mods_folder 物品边框-ItemBorders-1.18.1-1.1.5.jar : itemborders (1.1.5) - 1
• mods_folder 怪物远视-farsightedmobs-forge-1.1-1.18.jar : farsightedmobs (1.1) - 1
• mods_folder 背包整理-InventoryProfilesNext-forge-1.18.2-1.3.8.jar : inventoryprofilesnext (1.3.8) - 1
• mods_folder 星光-starlight-1.0.2+forge.546ae87.jar : starlight (1.0.2+forge.83663de) - 1
• mods_folder 动态难度-dynamic_player_progression_and_player_difficulty_1.18.2-0.8.0.jar : dynamic_player_progression_and_player_difficulty (0.8.0) - 1
• mods_folder 传送石碑-balm-3.1.0+0.jar : balm (3.1.0+0) - 1
• arclight arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14.jar : arclight (1.18.2-1.0.7-SNAPSHOT-c78fe14) - 1
• mods_folder 视觉工作台-PuzzlesLib-v3.3.5-1.18.2-Forge.jar : puzzleslib (3.3.5) - 1
• mods_folder 增强天体-Enhanced_Celestials-forge-1.18.2-2.0.7.jar : enhancedcelestials (2.0.7) - 1
• mods_folder cloth-config-6.4.90-forge.jar : cloth_config (6.4.90) - 1
• mods_folder 更好的动作-bettercombat-forge-1.2.0+1.18.2.jar : bettercombat (1.2.0+1.18.2) - 1
• minecraft forge-1.18.2-40.1.74-universal.jar : forge (40.1.74) - 1
• mods_folder 时间暂停-ReadyPlayerFun-1.18-1.4.1.8.jar : readyplayerfun (1.18-1.4.1.8) - 1
• mods_folder 旅行地图-MapFrontiers-1.18.2-2.3.4.jar : mapfrontiers (1.18.2-2.3.4) - 1
• mods_folder Ping-ServerTabInfo-1.18.2-1.3.5.jar : servertabinfo (1.3.5) - 1
• mods_folder 装备比较-EquipmentCompare-1.18.1-1.2.12.jar : equipmentcompare (1.2.12) - 1
```

### 错误描述

安装Aurora插件后可以正常启动服务器，但看不到粒子效果，在确认版本和前置插件无误的情况下，咨询了插件作者，日志文件发过去后，对方建议检查一下开服软件，并告知以下相关信息

原文如下：

Optic_Fusion1 — 今天01:08
errr, what server software are you using?
run /version

Arkell Gavin — 今天01:11
"Arclight", a software that supports both Forge and Spigot
This server is running Arclight version arclight-1.18.2-1.0.7-SNAPSHOT-c78fe14 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
Checking version, please wait...
Unknown version, custom build?

Optic_Fusion1 — 今天01:11
Well, Arclight's missing stuff that's needed

Arkell Gavin — 今天01:14
What is this missing thing? I can send issues to the author if you like

Optic_Fusion1 — 今天01:16
Important classes.

The iConomy plugin also doesn't load because Arclight is missing the org.bukkit.Server.getServerName() method's missing
as for LightAPI java.lang.RuntimeException: (NoSuchFieldException) theLightEngine
tldr; Arclight doesn't support spigot or paper classes properly

### 复现步骤

安装Aurora插件，安装前置LightAPI插件，运行服务器，进服后看不到粒子效果。

使用插件相关命令也没有任何反应

命令说明如下：

aurora toggle <on/off>
[aurora.command.toggle]
Toggle client-side ambient particle effects
/aurora reload
[aurora.command.reload]
Reload all plugin configs and particle files
/aurora status
[aurora.command.status]
View information on enabled particles in the server
/aurora fixlighting [radius]
[aurora.command.fixlighting]
Update and refresh lighting on [radius] nearby chunks

### 报错信息

[AMPLOG 2022-09-14 00-00-00.log](https://github.com/IzzelAliz/Arclight/files/9568724/AMPLOG.2022-09-14.00-00-00.log)

### 复现用压缩包下载链接(可选)

无

**Comment by nhtpr** [comment]
很抱歉，我发现它和starlight mod冲突，去掉就好了，辛苦关闭这个issus
