### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by TuZiz** [IzzelAliz/Arclight#739]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2

### OS & Java versions

java17

### Plugins and Mods

```raw
ItemsAdder
```

### Description

使用ItemsAdder后玩家假死

### Step to reproduce

使用ItemsAdder后玩家假死 

### Logs

使用ItemsAdder后玩家假死

### Server pack link (Optional)

使用ItemsAdder后玩家假死

**Comment by timi137137** [comment]
？
