### ISSUE TITLE
1.15.2 不加载插件

### ISSUE THREAD

**Issue by ddaodan** [IzzelAliz/Arclight#74]
### 我正在运行

* **Arclight** arclight-1.15.2-1.0.13-2d7c41b 

* **你确认这是最新版吗** 是

* **你确认所有Mod都安装了依赖** 是

* **你确认所有插件都已更新至对应版本** 是

* **Java** java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode) 

* **操作系统** Windows server 2016

* **插件列表** 
输入 /plugins 指令：
Plugins: (0)
实际安装的插件列表：
![image](https://user-images.githubusercontent.com/40017293/98819389-c200dd00-2467-11eb-8eae-3013bb3df7dd.png)

* **Mod 列表** 
Mod列表：? minecraft forge-1.15.2-31.2.45-server.jar : minecraft (1.15.2) - 1\n? mods_folder [星辉魔法]astralsorcery-1.15.2-1.12.11.jar : astralsorcery (1.15.2-1.12.11) - 1\n? mods_folder [墓碑]tombstone-4.5.6.jar : tombstone (4.5.6) - 1\n? mods_folder structurize-0.13.94-ALPHA-universal.jar : structurize (0.13.94-ALPHA) - 1\n? mods_folder [超多生物群系]BiomesOPlenty-1.15.2-10.0.0.366-universal.jar : biomesoplenty (1.15.2-10.0.0.366) - 1\n? mods_folder [模拟殖民地]minecolonies-0.13.436-RELEASE-universal.jar : minecolonies (0.13.436-RELEASE) - 1\n? mods_folder [家具]furniture-7.0.0-pre16-1.15.1.jar : cfm (7.0.0-pre16) - 1\n? mods_folder observerlib-1.15.2-1.3.1.jar : observerlib (1.15.2-1.3.1) - 1\n? mods_folder [挖矿与砍杀]Mine and Slash-1.15.2-3.7.9.jar : mmorpg (3.7.9) - 1\n? mods_folder [自动汉化更新]i18nupdatemod-1.15-1.16-1.0.0.jar : i18nupdate (NONE) - 1\n? arclight arclight-forge-1.15-1.0.13.jar : arclight (1.15.2-1.0.13-2d7c41b) - 1\n? mods_folder [更真实的钓鱼]fishingreal-1.2.jar : fishingreal (1.2) - 1\n? mods_folder [通用机械]Mekanism-1.15.2-9.10.9.422.jar : mekanism (9.10.9) - 1\n? maven_libs forge-1.15.2-31.2.45-universal.jar : forge (31.2.45) - 1\n? mods_folder curios-FORGE-1.15.2-2.0.2.6.jar : curios (FORGE-1.15.2-2.0.2.6) - 1\n? mods_folder [帕秋莉手册]Patchouli-1.15.2-1.2-35.jar : patchouli (1.15.2-1.2-35) - 1\n? mods_folder citadel-1.1.11.jar : citadel (1.1.11) - 1\n? mods_folder [冰与火之歌]iceandfire-2.1.0-1.15.2.jar : iceandfire (2.0.3-1.15.2) - 1

### 错误描述

开服后不加载插件

### 重现步骤

1. 安装了服务器需要的部分插件
2. 进入服务器后，查询不到插件的指令，输入插件的指令提示未知的命令
3. 查看logs，发现加载插件的时候报错

**可在 Forge 复现** 否

**可在 Spigot 复现** 否

### 报错信息

https://paste.ubuntu.com/p/bkYJgTZFK4/

**Comment by IzzelAliz** [comment]
因为你下了个烂的插件 `BanItem_with_NBT_v3.2.5.jar`
