### ISSUE TITLE
玩家死亡后不能移动和打开背包

### ISSUE THREAD

**Issue by TuZiz** [IzzelAliz/Arclight#740]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [x] 已为所有插件及模组安装依赖
- [x] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.7-SNAPSHOT

### Java 版本 | 操作系统

win2012 java17

### 相关 Mod/插件 的名称及版本

```raw
LightAPI-Bukkit-5.3.0
LoneLibs
ItemsAdder_3.2.3i
ProtocolLib
```

### 错误描述

给服务器装ItemsAdder_3.2.3i及前置后玩家假死 重生后可以交互 但是不能移动和打开背包

### 复现步骤

d

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/9597528/latest.log)

**Comment by IzzelAliz** [comment]
在 3ebd71a152a42361b6424d5f367c9c851bd09792 修复
