### ISSUE TITLE
[1.18.2] Crash on Startup with ATM7

### ISSUE THREAD

**Issue by dhkatz** [IzzelAliz/Arclight#741]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.7-SNAPSHOT-90ed5201

### OS & Java versions

OS: Ubuntu 22.04 x64 Java: openjdk version "18.0.2.1" 2022-08-18

### Plugins and Mods

```raw
No plugins.

The list of mods which ATM7 depends on can be found in the server pack below or here: https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/relations/dependencies

/forge mods was only printing like 20 of the mods
```

### Description

Whenever launching the server it will crash almost immediately. I attached the latest log but it tried to restart several times showing a different error each time, so I included a previous.txt file as well.

I confirmed that a forge server works fine by itself, and I can launch a spigot server by itself (just empty obviously)

### Step to reproduce

1. Install All the Mods 7 Server
2. Attempt to launch with Arclight

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/9602426/latest.log)

[previous.txt](https://github.com/IzzelAliz/Arclight/files/9602428/previous.txt)

### Server pack link (Optional)

https://mediafiles.forgecdn.net/files/3995/913/ATM7-0.4.32-server.zip

**Comment by junny2233** [comment]
Hello, I had the same issues the only thing I did was remove the Apotheosis mod from the server side only.

try that and let me know if that work for you as well

https://junny2233.link/yDwTdwH <--- screenshoot 


PD: can't really tell if this is gonna affect anything in the pack when it comes to progression. I'm playing on a server with friends and no issue so far

**Comment by dhkatz** [comment]
> Hello, I had the same issues the only thing I did was remove the Apotheosis mod from the server side only.
> 
> try that and let me know if that work for you as well
> 
> https://junny2233.link/yDwTdwH <--- screenshoot
> 
> PD: can't really tell if this is gonna affect anything in the pack when it comes to progression. I'm playing on a server with friends and no issue so far

This will stop all existing socketed armor and such to not work I assume?

Also, if anyone can commet why Apotheosis might be conflicting with Arclight I'd gladly make an issue report on the Apotheosis github

**Comment by Xplodin** [comment]
delete the apotheosis mixin LivingEntityMixin from the mod jars mixins.refmap

It works pretty well without that mixin

**Comment by junny2233** [comment]
> 

and I can do this by editing the actual mod and recreating it from the GitHub repo?

**Comment by Xplodin** [comment]
No need to use repo, just open jar in winrar 7zip etc and open the txt file for the mixins and delete LivingEntityMixin and save. Should boot without errors

**Comment by junny2233** [comment]
thank you that really work perfectly!

**Comment by dhkatz** [comment]
> No need to use repo, just open jar in winrar 7zip etc and open the txt file for the mixins and delete LivingEntityMixin and save. Should boot without errors

Can this be done on the server side only?

**Comment by Xplodin** [comment]
> > No need to use repo, just open jar in winrar 7zip etc and open the txt file for the mixins and delete LivingEntityMixin and save. Should boot without errors
> 
> Can this be done on the server side only?

yes
