### ISSUE TITLE
1.14.4 多世界插件bug,Multiverse-Core

### ISSUE THREAD

**Issue by ZHD99** [IzzelAliz/Arclight#75]
### 我正在运行

* **Arclight** [版本:arclight-forge-1.14-1.0.6] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [版本: 1.8.0_131] 

* **操作系统** [名称+版本:Windows10+1909]

* **插件列表** 
 Plugins (1): Multiverse-Core
* **Mod 列表** 
Mod List: 
• minecraft forge-1.14.4-28.2.0-server.jar : minecraft (1.14.4) - 1
• maven_libs forge-1.14.4-28.2.0-universal.jar : forge (28.2.0) - 1
• arclight arclight-forge-1.14-1.0.6.jar : arclight (1.14.4-1.0.6-5106498) - 1

### 错误描述
各个多世界插件[Multiverse-Core]无法前往新创建地图或已存在地图无法传送

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 Multiverse-Core 
2. 创建地图，成功后 :( 
3. 输入命令/mv tp ，前往新地图出现错误提示:试图执行该命今时出现意外错误
4. 控制台报错，聊天栏无法发送信息

**可在 Forge 复现** [是]

**可在 Spigot 复现** [是]
### 报错信息

[错误日志]
https://paste.ubuntu.com/p/4KWSvHqrgp/

**Comment by IzzelAliz** [comment]
1.14 不受支持
