### ISSUE TITLE
[1.18.2]  plugins VillagerOverhaul

### ISSUE THREAD

**Issue by XionioXMaster** [IzzelAliz/Arclight#755]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7-SNAPSHOT.jar

### OS & Java versions

windows server 2020

### Plugins and Mods

```raw
Plugins (13): MiniMOTD, VillagerOverhaul, LuckPerms, HolographicDisplays, Vault, F3Name, ProtocolLib, Chatty, TCPShield, CMILib, ChatBubbles, TAB, CMI
```

### Description

This occurs when generating a village.

### Step to reproduce

This occurs when generating a village, but sometimes.
Presumably when creating a librarian

### Logs

https://mcpaste.com/eaf048e2430aaa70e34edffc6723956b - VillagerOverhaul

**Comment by IzzelAliz** [comment]
Fixed in 201bb159.
