### ISSUE TITLE
GSit does not work in arclight 1.19.2

### ISSUE THREAD

**Issue by Bln3** [IzzelAliz/Arclight#757]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.0-SNAPSHOT

### OS & Java versions

openjdk version "17.0.4.1" 

### Plugins and Mods

```raw
GSit
```

### Description

The plugin works in normal spigot 1.19.2 with no errors. In arclight 1.19.2 it spews a bunch of errors in the console on start up and some commands do not work and post errors in the console.

### Step to reproduce

1. Install GSit 
2. Put GSit in the plugins folder
3. Start the server
4. Watch the errors in the console come in

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/9659803/latest.log)

**Comment by Bln3** [comment]
There was a release 1.2.7 but that doesnt work either

**Comment by IzzelAliz** [comment]
This plugin is not compatible with Spigot.
