### ISSUE TITLE
Gravit Launcher

### ISSUE THREAD

**Issue by SqdGoodlol** [IzzelAliz/Arclight#765]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [ ] unable to reproduce in Spigot
- [ ] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.24.jar

### OS & Java versions

Win 11

### Plugins and Mods

```raw
-
```

### Description

I can’t connect the launcher to the server in serverwaper, I set it to the core and when generating the batch file I open it, but it crashes
  "address": "ws://localhost:9274/api",
  "serverName": "Goldenbaton",
  "autoloadLibraries": false,
  "classpath": [],
  "classLoaderConfig": "SYSTEM_ARGS",
  "mainclass": "io.izzel.arclight.server.Launcher",
  "args": [],
  "oauthExpireTime": 0,
  "extendedTokens": {
    "checkServer": "*token*"
  },
  "env": "STD",
  "moduleConf": {
    "modules": [],
    "modulePath": [],
    "mainModule": "",
    "exports": {},
    "opens": {},
    "reads": {}
  }
}

### Step to reproduce

1. Create a basic launcher
2.Try to connect the server to the waper server

### Logs

строка:1 знак:49
+ "C:\Program Files\Java\jdk-17.0.2\bin\java.exe" -cp ServerWrapper.jar ...
+                                                 ~~~
Непредвиденная лексема "-cp" в выражении или операторе.
строка:1 знак:53
+ ... ram Files\Java\jdk-17.0.2\bin\java.exe" -cp ServerWrapper.jar;arcligh ...
+                                                 ~~~~~~~~~~~~~~~~~
Непредвиденная лексема "ServerWrapper.jar" в выражении или операторе.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

### Server pack link (Optional)

-

**Comment by DonorKrovi** [comment]
ору

**Comment by IzzelAliz** [comment]
This is fixed in 1.18 and later, backport to 1.16 is not considered.
