### ISSUE TITLE
Arclight Server Issue with Biome Mods [1.19.2]

### ISSUE THREAD

**Issue by iristeaa** [IzzelAliz/Arclight#773]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.19.2

### OS & Java versions

unsure: console wont work.

### Plugins and Mods

```raw
alexsmobs-1.20.1.jar
AmbientSounds_FORGE_v5.2.5_mc1.19.2.jar
another_furniture-forge-2.0.3-1.19.2.jar
Bookshelf-Forge-1.19.2-16.1.5 (1).jar
Chimes-1.1.4-1.19.jar
citadel-1.12.12-1.19.jar
cloth-config-6.4.90-forge.jar
Clumps-forge-1.19.2-9.0.0+11.jar
CreativeCore_FORGE_v2.8.6_mc1.19.2.jar
cullleaves-2.3.4.jar
FallingTree-1.19.2-3.10.0.jar
FastLeafDecay-30.jar
gravestone-1.19.2-1.0.1.jar
jei-1.19.2-forge-11.3.0.262.jar
mcw-fences-1.0.6-mc1.19.2.jar
mcw-paintings-1.0.4-mc1.19.2.jar
mcwfencesbyg-1.19.2-1.0.jar
modmenu-4.0.6.jar
NaturesCompass-1.19.2-1.9.7-forge.jar
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.6.jar	
sophisticatedbackpacks-1.19.2-3.18.29.719.jar
sophisticatedcore-1.19.2-0.5.13.134.jar
TerraBlender-forge-1.19.2-2.0.1.127.jar
voicechat-forge-1.19.2-2.3.10.jar
Waila-1.7.1_1.11.2 (1).jar
Xaeros_Minimap_22.15.1_Forge_1.19.1.jar
```

### Description

Hello!,

I've been trying to make a modded smp server for about the past month now. Working very hard to slowly piece everything together. The website, discord, server itself, modpack, etc.

I've been trying to run an Arclight 1.19.2 server (I know its unstable lol but I have a vision for my server!). It's important to me that I have mods installed (which is the base of the gameplay) and some light plugins.

My main issue is- I cannot for the life of me to get any sort of biomes mods to work (Oh the biomes you'll go, Biomes o plenty, etc.). The server just perpetually refreshes. This mod is super important to me because I see my server having a very diverse landscape with new materials to build with. None of the other mods are as important to me.

I've tried going through each and every mod and the only mods that seem to be the problem are the biomes mods. I try on forge and paper as well and these mods just don't seem to want to work.

I also want to add that it was working at two points- I was with a different server host and it was working fine but they didn't offer arclight so I switched to a different one. When I started the server on the new host with arclight it was perfect, but I was missing all the config files. The developers fixed it, and ever since then it hasn't been working unfortunately. I've tried resetting all the server files and deleting the config files and nothing is working.

I don't mind as much switching to forge or something that's not a hybrid-type server, as plugins aren't that important to me. It would just be nice to have.

I'm very new to minecraft server hosting and it's probably just user error. The server hosting staff isn't proving to be super helpful unfortunately. They're trying their best though!

I just need some help and maybe if other people could help me brainstorm ideas that would be awesome! If anyone has any solutions or tips that would be super helpful!
![screenshot for forum](https://user-images.githubusercontent.com/111699809/196017601-896fc1dc-2e16-4a6e-bb2c-305f098432cf.png)

**Comment by iristeaa** [comment]
I forgot to add that I don't have any plugins currently installed.

**Comment by IzzelAliz** [comment]
Any logs?
