### ISSUE TITLE
最新版本各种扫地大妈无法运行

### ISSUE THREAD

**Issue by yaoxiaosa** [IzzelAliz/Arclight#78]
### 我正在运行

* **Arclight** [arclight-1.16.3-1.0.9-SNAPSHOT-3caea59] 

* **你确认这是最新版吗** [是，因为是昨天刚更新的]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_131] 

* **操作系统** [Linux (amd64) version 5.8.9-1.el7.elrepo.x86_64]

* **插件列表** 
SpigotPing, AdvancedCleaner, VillagerLobotomizatorNator, Yum, UltimateTimber, WorldBorder, Vault, FullMoon, LaggRemover, ZMusic, UltiEconomy, LockettePro, LCGShop
* **Mod 列表** 
 minecraft forge-1.16.3-34.1.25-server.jar : minecraft (1.16.3) - 1
• mods_folder 工业先锋.jar : industrialforegoing (3.1.1) - 1
• mods_folder FarmersDelight-1.16.3-0.2.3.jar : farmersdelight (1.16.3-0.2.3) - 1
• mods_folder 工业先锋前置.jar : titanium (3.1.0) - 1
• mods_folder 沉浸工业.jar : immersiveengineering (1.16.3-4.1.1-127) - 1
• mods_folder mana-and-artifice-1.0.8.6.jar : mana-and-artifice (1.0.8.6) - 1
• mods_folder Lollipop-1.16.3-3.2.2波瓦前置.jar : lollipop (3.2.2) - 1
• mods_folder 万用皮肤补丁.jar : customskinloader (14.13-SNAPSHOT-190) - 1
• mods_folder JEI.jar : jei (7.3.2.29) - 1
• mods_folder 通用机械.jar : mekanism (10.0.15) - 1
• mods_folder curios-forge-1.16.3-4.0.2.0.jar : curios (1.16.3-4.0.2.0) - 1
• mods_folder 植物魔法.jar : botania (1.16.3-409) - 1
• mods_folder 帕秋莉手则.jar : patchouli (1.16.2-45) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.1.jar : cookingforblockheads (9.2.1) - 1
• mods_folder AE2.jar : appliedenergistics2 (8.1.0-beta.2) - 1
• mods_folder FluxNetworks-1.16.3-6.0.1.4.jar : fluxnetworks (1.16.3-6.0.1.4) - 1
• mods_folder 波瓦科技.jar : powah (2.3.4) - 1
• mods_folder 烟花苦力怕.jar : creeperconfetti (3.4) - 1
• mods_folder 简易飞机.jar : simpleplanes (1.16.3-3.2.0.1) - 1
• mods_folder MekanismGenerators-1.16.3-10.0.15.441.jar : mekanismgenerators (10.0.15) - 1
• arclight server.jar : arclight (1.16.3-1.0.9-SNAPSHOT-3caea59) - 1
• mods_folder Ma-Essentials-1.16.3-3.4.0.jar : maessentials (1.16.3-3.4.0) - 1
• maven_libs forge-1.16.3-34.1.25-universal.jar : forge (34.1.25) - 1
• mods_folder plonk-1.16.3-9.0.2.jar : plonk (9.0.2) - 1
• mods_folder 豆腐craft.jar : tofucraft (1.16.3-0.1.4.2) - 1
• mods_folder 更多箱子.jar : ironchest (1.16.3-11.2.6) - 1

### 错误描述
服务器中任何扫地插件无法扫地，已经测试过clearlag，AdvancedCleaner，WClearDrop，ClearEntity，NeverLag等，均无法进行扫除

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装任何适合版本的扫地插件
2. 进入服务器后掉落物无法扫除
3. ....

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

https://paste.ubuntu.com/p/QD5Qnxfvyz/

**Comment by yaoxiaosa** [comment]
可在 Spigot 复现 [是]

**Comment by IzzelAliz** [comment]
已经修复
