### ISSUE TITLE
[1.16-1.19] Mypet宠物插件不兼容，无法使用

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#780]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.25-SNAPSHOT-d40d014a（370）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
MyPet-3.12-SNAPSHOT-B1718
https://github.com/MyPetORG/MyPet/releases
```

### 错误描述

开服时，插件启动失败，无法正常使用
Error occurred while enabling MyPet v3.12 (Is it up to date?)
java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.

### 复现步骤

1、安装插件
2、启动服务器
3、插件载入失败，报错

### 报错信息

latest.log
https://paste.ubuntu.com/p/d5tyBDkMwH/

debug.log
https://paste.ubuntu.com/p/nsmTVzr7rJ/

**Comment by heipiao233** [comment]
老bug了，MyPet使用了NMS的注册功能，而此时Forge已将注册表冻结。或许无解。

**Comment by luoxiawuchen** [comment]
> 老bug了，MyPet使用了NMS的注册功能，而此时Forge已将注册表冻结。或许无解。

噢噢 原来如此 谢谢解答

**Comment by heipiao233** [comment]
有解。
