### ISSUE TITLE
[1.16-1.19] Residence插件，在地狱和末地创建领地，重启后领地消失

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#781]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.25-SNAPSHOT-d40d014a（370）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
CMILib（前置）
Residence
```

### 错误描述

emmm，严格来说这是个有些尴尬的问题，但应该不算bug..
arclight的世界（存档）文件结构的特殊性与Residence存储文件生成共同导致的结果。

arclight的下界、末地，世界ID为 world/DIM1 和 world/DIM-1
1、Residence插件在创建领地时，领地信息被存储于 Plugins\Residence\Save\Worlds\res_世界名.yml
2、由于下界为 world/DIM1 ，则应该生成名为 res_world/DIM1.yml 文件
3、在windows的文件名中不允许出现"/"符号
4、于是插件将领地存储于tmp_res_world文件夹中
5、于是服务器重启后，领地消失
6、该问题应该仅存在于win系统

不知能否让世界名被读取为DIM1而不是world/DIM1？ 或使用与spigot相同的存档文件结构呢？

### 复现步骤

1、安装插件、启动服务器
2、在下界或末地圈地，领地被正常创建
3、重启服务器后，已创建的领地消失

### 报错信息

无

**Comment by IzzelAliz** [comment]
可以启用 symlink-world https://github.com/IzzelAliz/Arclight/wiki/World-Symlink
