### ISSUE TITLE
1.19 Applied Energistics failure

### ISSUE THREAD

**Issue by SoulOfHope** [IzzelAliz/Arclight#785]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.0-SNAPSHOT-4145c11a

### OS & Java versions

All I could get was Java 17

### Plugins and Mods

```raw
GeyserMC - Plugin (throws up its own problems that are being fixed) 
Floodgate (Geyser Dep) - Plugin
Applied Energistics - Mod (believed cause)
```

### Description

Throws missing dependency error forge (AE2 runs latest forge compatibility) and proceeds to crash

### Step to reproduce

Install AE2

Run Server (any other plugins or mods don't affect the outcome) 

Error

### Logs

https://pastebin.com/raw/DXH6yGTE

**Comment by IzzelAliz** [comment]
Outdated forge. Wait for us or update yourself.
