### ISSUE TITLE
MagicSpells Plugin Incompatibility 1.16.5

### ISSUE THREAD

**Issue by Sorax5** [IzzelAliz/Arclight#787]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.24-551ec3ff

### OS & Java versions

OS: Windows 11 , java:openjdk version "17.0.4.1" 2022-08-12

### Plugins and Mods

```raw
Only MagicSpells-4.0-Beta-9

No mods
```

### Description

MagicSpells is a plugin that allows you to create spells with YML files.
Github : https://github.com/TheComputerGeek2/MagicSpells

The latest 1.16.5 version of MagicSpells is Beta-9.

There are really a lot of types of spells and some don't work on Arclight (I couldn't tell you exactly).

If you need I can provide you some spells that I have and that make me bugs in the console.
In this case contact me on discord (SoraxDubbing#7755)

I tested this plugin on other software like Mohist or simply Paper (which is its base platform).

From some bugs I have the impression that the plugin uses functions of Paper that are not implemented in Arclight.

### Step to reproduce

1. Install MagicSpells Plugin
2. Add spells in the configuration file of the plugin
3. issue the command /c "spell name". the name of the spell being defined in the YML file 

### Logs

https://paste.ubuntu.com/p/QKWMZxP8K9/

**Comment by IzzelAliz** [comment]
`getNearbyLivingEntities` is a Paper provided API, which means your plugin do not support Spigot.
