### ISSUE TITLE
McMMO Support

### ISSUE THREAD

**Issue by Shybella** [IzzelAliz/Arclight#788]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2 - 1.0.7

### OS & Java versions

Windows Server 2019

### Plugins and Mods

```raw
BetterMC 1.18.2 (Latest)
```

### Description

McMMO recipe handler fails iterating through recipes.

Stack: https://paste.gg/p/anonymous/c6b8ed1bdb3544a5ba4f8dc9d71f6987

### Step to reproduce

1. Install McMMO.jar (I can provide this in discord PMs)
2. Install immersive weathering (https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge/files/4021620)
3. Start server

### Logs

https://paste.gg/p/anonymous/c6b8ed1bdb3544a5ba4f8dc9d71f6987

**Comment by heipiao233** [comment]
If you install immersive_weathering only will this bug still exists? If no mods?

**Comment by Shybella** [comment]
This also occurs with Oreberries mod and UnusualEnd, does not occur with no mods. 

Will occur with any of those mods installed.

**Comment by Shybella** [comment]
Resolved, thank you!

**Comment by Shybella** [comment]
Can this be added to 1.19.2/1.19.3

**Comment by Shybella** [comment]
This issue has sprung back up under 1.19.2

Log: https://pastebin.com/raw/mvM53E8m

**Comment by Shybella** [comment]
Log: https://[pastebin.com/raw/uJ2ugU0A](https://pastebin.com/raw/uJ2ugU0A)
