### ISSUE TITLE
Permission Node not being respond to appropriately. 

### ISSUE THREAD

**Issue by Barnse** [IzzelAliz/Arclight#789]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.24.jar

### OS & Java versions

Java 1.8.0_292

OS: CentOS 8 Stream / Rocky Linux 8

### Plugins and Mods

```raw
Plugins
___
EssentialsX-2.20.0-dev+15-20011b9.jar 
EssentialsXChat-2.20.0-dev+15-20011b9.jar
LuckPerms-Bukkit-5.4.52.jar, Vault.jar

Mods
___
BetterPokeBroadcaster-Forge-1.1.3-1.16.5.jar
byg-1.3.5.jar
ExplorersCompass-1.16.5-1.1.2-forge.jar
jei-1.16.5-7.7.1.152.jar
journeymap-1.16.5-5.8.5p6.jar
konkrete_forge_1.3.3_MC_1.16.2-1.16.5.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
Pixelmon-1.16.5-9.0.11-universal.jar
```

### Description

I've setup permissions on my server to allow users to use various commands.

Pixelmon permission nodes usually follow the format pxielmon.command.<command> however due to using Arclight these permission nodes need to be formatted as **minecraft**.command.<command> instead.

As an example the permission node `minecraft.command.endbattle` allows the user to end a battle if they find themselves stuck in a battle. This works with no problems. 

However these permission nodes:

-minecraft.checkspawns.legendary
-minecraft.checkspawns.normal
-minecraft.command.checkspawns

When used by a user are being given a "You must be an OP or have permission to perform this action." error. This shouldn't be the case as the user has the permission to use these commands as specified within the LuckPerms permission groups. 

I've also posted this issue on the pixelmon tracker encase it is an issue with them instead. I do not believe LuckPerms to be at fault here as the error being printed to users is not one from LuckPerms or the typical minecraft command deny string of text. 

### Step to reproduce

1. Install the same files as described above.
2. Setup permission nodes outlined in the description.
3. Attempt to perform the command `/checkspawns` or `/checkspawns legendary` as a non-operator user.

**Comment by IzzelAliz** [comment]
You can enable verbose mode in LP(`/lp verbose on`) and see what exactly permission your plugin/mod is asking for.

This is not considered a bug.
