### ISSUE TITLE
1.18.2 Gravit Launcher authlib

### ISSUE THREAD

**Issue by SqdGoodlol** [IzzelAliz/Arclight#791]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.7-SNAPSHOT

### OS & Java versions

Win 11 Java 17

### Plugins and Mods

```raw
-
```

### Description

problem with authlib

### Step to reproduce

1. Create launcher
2. connect ServerWapper
3. start server then close it
4. java -jar ServerWrapper.jar installAuthlib https://mirror.gravit.pro/5.2.x/compat/authlib/3/LauncherAuthlib3 
5. start its crash

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/9893159/latest.log)

### Server pack link (Optional)

no

**Comment by SqdGoodlol** [comment]
Maybe this will help
[securejarhandler (1).zip](https://github.com/IzzelAliz/Arclight/files/9893161/securejarhandler.1.zip)

**Comment by IzzelAliz** [comment]
Report to Gravit Launcher dev.
