### ISSUE TITLE
[1.18.2]重启服务器或重载插件时会导致用mv插件生成的世界地形混乱

### ISSUE THREAD

**Issue by McAZero** [IzzelAliz/Arclight#795]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [x] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.7-SNAPSHOT-1f312fa

### Java 版本 | 操作系统

系统: Windows10 | openjdk version "17.0.5" 2022-10-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
Multiverse-Core-4.3.1.jar
```

### 错误描述

重启服务器或重载插件时会导致用mv插件生成的世界地形混乱。
如果有模组支持如暮色森林或者原版世界、地狱和末地未出现。
在purpur1182上未出现此问题
![image](https://user-images.githubusercontent.com/52328924/199357721-fae8fe0c-3e3d-41ca-9010-7f3e79054dde.png)
![image](https://user-images.githubusercontent.com/52328924/199357765-9deffddb-f99d-45b6-84ff-31c3d01dda47.png)
![image](https://user-images.githubusercontent.com/52328924/199357809-7cbc8137-65fb-41ae-84bd-947bfc27074b.png)

### 复现步骤

重启服务器或重载插件时

### 报错信息

无报错

### 复现用压缩包下载链接(可选)

null

**Comment by IzzelAliz** [comment]
你开了 world symlink 吗 https://github.com/IzzelAliz/Arclight/wiki/World-Symlink

**Comment by McAZero** [comment]
> 你开了 world symlink 吗 https://github.com/IzzelAliz/Arclight/wiki/World-Symlink

symlink-world=true 这条在哪个文件中查看

**Comment by McAZero** [comment]
> 你开了 world symlink 吗 https://github.com/IzzelAliz/Arclight/wiki/World-Symlink
开启了 还是会有这个问题

![image](https://user-images.githubusercontent.com/52328924/200565207-f407af60-423b-404d-bbcb-15f6dc42d4db.png)
![image](https://user-images.githubusercontent.com/52328924/200565978-ac2fb7cf-e341-4c80-9d54-8b34f44de0f4.png)
![image](https://user-images.githubusercontent.com/52328924/200568767-3362ec71-f56d-48f2-a361-0dd6c9dbc856.png)
![image](https://user-images.githubusercontent.com/52328924/200565275-20006440-e761-41cd-9614-d1490660e849.png)

**Comment by McAZero** [comment]
> 你开了 world symlink 吗 https://github.com/IzzelAliz/Arclight/wiki/World-Symlink

问题是模组世界反而不会出现这种问题，是mv插件生成的才会，开启了还是一样

**Comment by McAZero** [comment]
最新版本仍然出现此问题
![G8VP_D(U2T$% 28N99C RFV](https://user-images.githubusercontent.com/52328924/222877698-403a6408-086a-4d89-8968-e0d98e135ce0.png)
![)458PC Q(}KZ1$N5FDB(91W](https://user-images.githubusercontent.com/52328924/222877703-687bfea5-6d76-48ee-a9e1-70c3dcb961f7.png)
![){KMX XN$PUEOEJ}EP K(FN](https://user-images.githubusercontent.com/52328924/222877705-185e4dc9-b614-4f4d-88f4-9c8b395a51f2.png)
![2)V71 K~$F _WJ{Q}OET3@7](https://user-images.githubusercontent.com/52328924/222877711-aeab99be-88c3-403d-a61b-2bf250db2dae.png)
![WSEUP56BDL8V0`S@43SG`0C](https://user-images.githubusercontent.com/52328924/222877714-7f66fa35-1095-4a55-b26d-87561ea05fbc.png)
