### ISSUE TITLE
好多个问题

### ISSUE THREAD

**Issue by Hazi7** [IzzelAliz/Arclight#8]
1.空岛插件无效且报错
https://paste.ubuntu.com/p/QVFqVgKvkW/
https://paste.ubuntu.com/p/7Q2T8dsmtn/

2.Combatpets宠物移动报错?
https://paste.ubuntu.com/p/kQBwRT367b/

3.加mod有问题，forge版本没错，本来是就在群里发的那张图，然后您发的新版本是
 
 This server has mods that require Forge to be installed on the client
Contact your server admin for more details

4.Jetminions精灵工作异常
https://paste.ubuntu.com/p/B68FRVfpcy/

5.淘宝库
https://paste.ubuntu.com/p/qQCJz8xcnS/

**Comment by IzzelAliz** [comment]
2 过会儿修
5 已知问题，之后单独做兼容
别的都修了
