### ISSUE TITLE
使用ServerTap与CirnoBot联络核心崩溃

### ISSUE THREAD

**Issue by Heacter233** [IzzelAliz/Arclight#800]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.7-40114eb5

### Java 版本 | 操作系统

系统：Windows 10 java version "17.0.2"

### 相关 Mod/插件 的名称及版本

```raw
ServerTap-0.4.0
```

### 错误描述

为避免有其他Mod及插件干扰单独安装插件ServerTap-0.4.0用来MC服务器与CirnoBot连接。服务器正常启动在CirnoBot未与MC服务器联系时无问题，但CirnoBot与MC服务器链接服务器时报错卡死。已在paper Spigot纯净服务器端同版本测试能正常链接使用。
日志无法记录崩溃报错文本，已手动复制全部服务器日志记录。
ServerTap-0.4.0 releases：[连接](https://github.com/phybros/servertap/releases)
CirnoBot 文档：https://biaoju.site/cirnobot/

### 复现步骤

1.安装ServerTap插件
2.启动服务器
3.配置ServerTap与CirnoBot
4.重启服务器
5.启动CirnoBot链接服务器
6.服务器卡死按Enter服务器循环报错

### 报错信息

[Uploading latest.log…]()

### 复现用压缩包下载链接(可选)

https://github.com/phybros/servertap/releases/download/v0.4.0/ServerTap-0.4.0.jar

**Comment by Heacter233** [comment]
[latest.log](https://github.com/IzzelAliz/Arclight/files/9934117/latest.log)

**Comment by IzzelAliz** [comment]
你可以在卡住的时候等一段时间按下 ctrl+break 复制输出的内容

**Comment by Heacter233** [comment]
"VM Thread" os_prio=2 cpu=109.38ms elapsed=133.01s tid=0x000001c4dc930560 nid=0x5710 runnable

"GC Thread#0" os_prio=2 cpu=1812.50ms elapsed=133.40s tid=0x000001c4ba7913c0 nid=0x49e0 runnable

"GC Thread#1" os_prio=2 cpu=1750.00ms elapsed=133.39s tid=0x000001c4ba7abbb0 nid=0x2f6c runnable

"GC Thread#2" os_prio=2 cpu=1781.25ms elapsed=133.39s tid=0x000001c4ba7ac4b0 nid=0x23d0 runnable

"GC Thread#3" os_prio=2 cpu=1468.75ms elapsed=126.71s tid=0x000001c4dff96290 nid=0x381c runnable

"G1 Main Marker" os_prio=2 cpu=0.00ms elapsed=133.40s tid=0x000001c4ba7970a0 nid=0x5600 runnable

"G1 Conc#0" os_prio=2 cpu=2593.75ms elapsed=133.40s tid=0x000001c4ba798160 nid=0x30b0 runnable

"G1 Refine#0" os_prio=2 cpu=1234.38ms elapsed=133.03s tid=0x000001c4ba81d4e0 nid=0x4920 runnable

"G1 Refine#1" os_prio=2 cpu=203.12ms elapsed=119.29s tid=0x000001c4df31a470 nid=0x870 runnable

"G1 Refine#2" os_prio=2 cpu=171.88ms elapsed=115.57s tid=0x000001c4e44b80d0 nid=0x4170 runnable

"G1 Refine#3" os_prio=2 cpu=125.00ms elapsed=112.78s tid=0x000001c4e44ba350 nid=0x4598 runnable

"G1 Service" os_prio=2 cpu=0.00ms elapsed=133.03s tid=0x000001c4dc924010 nid=0x2b60 runnable

"VM Periodic Task Thread" os_prio=2 cpu=78.12ms elapsed=132.99s tid=0x000001c4dccc5ba0 nid=0x1648 waiting on condition

JNI global refs: 34, weak refs: 45

Heap
 garbage-first heap   total 3072000K, used 2007132K [0x0000000706000000, 0x0000000800000000)
  region size 8192K, 134 young (1097728K), 1 survivors (8192K)
 Metaspace       used 129859K, committed 131264K, reserved 1163264K
  class space    used 18123K, committed 18752K, reserved 1048576K

**Comment by IzzelAliz** [comment]
复制完整放到 paste 网站去，不要直接贴出来

**Comment by Heacter233** [comment]
> 复制完整放到 paste 网站去，不要直接贴出来
已复制全部ctrl+break后的输出
https://paste.ubuntu.com/p/Sp8XtQfWHm/
