### ISSUE TITLE
Don't start with a few mods

### ISSUE THREAD

**Issue by ZarkxWorld** [IzzelAliz/Arclight#801]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.19.2-1.0.0

### OS & Java versions

java 17

### Plugins and Mods

```raw
CorailTombstone
ProjectMMO
Strawgolem (forge)
morevillagers
```

### Description

Server doesn't start with this mods

### Step to reproduce

1. install server
2. add mods
3. press start button
4. doesn't start

**Comment by IzzelAliz** [comment]
logs?
