### ISSUE TITLE
Canary mod compatibility

### ISSUE THREAD

**Issue by whereareiam** [IzzelAliz/Arclight#802]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.0-7f496130

### OS & Java versions

OS: Windows 11, Java: 17.0.5 2022-10-18 LTS

### Plugins and Mods

```raw
canary-mc1.19.2-0.0.9
```

### Description

Hello, after installing the mod, it gives an error at startup, I tried to disable all functions in the mod's config, it also gave an error. Tested both on windows and debian. I would like to see support for this mod, because it can add a lot of performance.

### Step to reproduce

1. Install a clean server
2. Add mod
3. Restart the server

### Logs

https://pastebin.com/hGZMuLqu

**Comment by LLjo** [comment]
He's not currently supporting performance mods, I've gotten it to work with 1.19.2 with some functions of canary enabled

**Comment by whereareiam** [comment]
Can you show me what you turned on and off?

**Comment by LLjo** [comment]
Sorry, I removed it due to 1.18 felt more stable. But I would suggest just turning off all functions then enabling one after another. Be sure to disable those functions shown in the canary code as well

**Comment by IzzelAliz** [comment]
Compatibility with performance mods is not considered.
