### ISSUE TITLE
破坏方块无掉落物

### ISSUE THREAD

**Issue by kxkl2077** [IzzelAliz/Arclight#804]

**Comment by mlus-asuka** [comment]
我开的1.18服也有类似的问题，开了一段时间以后。类似三叉戟打紫颂花，催熟向日葵之类的操作会没有掉落物品，而且还是时有时无的。我测试了之后发现跟插件没有关系。可能是有区块实体限制之类的机制，因为找不出具体原因实在不知道怎么提交Issue。但是原版forge是没有问题的

**Comment by timi137137** [comment]
虽然你说的对，但是这不是你不按规定的借口
