### ISSUE TITLE
Server Crash fmlserver - mixin PLUGINSERVICE Minecraft 1.16.5

### ISSUE THREAD

**Issue by MamohoReloaded** [IzzelAliz/Arclight#810]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.24.jar

### OS & Java versions

???????? Java ?? ???? 11.0.16.1 ???? 17 ???? Java ???????

### Plugins and Mods

```raw
Mod List: 
		forge-1.16.5-36.2.39-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-2.16.1.jar                           |FramedBlocks                  |framedblocks                  |2.16.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		arclight-forge-1.16.5-1.0.24.jar                  |Arclight Mod                  |arclight                      |1.16.5-1.0.24-551ec3|DONE      |Manifest: NOSIGNATURE
```

### Description

just run a server with your latest version of your minecraft server 1.16.5, without plugins go to curseforge and install FramedBlocks mod on your latest version for forge.

link: https://www.curseforge.com/minecraft/mc-mods/framedblocks

### Step to reproduce

once you have started everything, simply enter the created world using LocalHost as ip look for the mod section in creative, choose any block of the mod and place the block, the server will automatically crash.

### Logs

https://paste.ubuntu.com/p/4SDdSRmBsP/

**Comment by IzzelAliz** [comment]
This is not an Arclight issue. You can report to framedblocks dev.
