### ISSUE TITLE
Client can't connect to server - Citizens + Biomes you go - Arclight 1.18.2

### ISSUE THREAD

**Issue by doarlock** [IzzelAliz/Arclight#813]
I made a modpack using biomes o plenty and Biomes you go together beside with citizens plugin
I'm using the lastest Arlight 1.18.2 realease

The problem occurs when a client try to connect to the server with the right mods and forge version... and when he/she does it this happens:

![image](https://user-images.githubusercontent.com/63677994/201869716-271954e1-f1a6-4c65-9833-ecc2c7d520ae.png)
![image](https://user-images.githubusercontent.com/63677994/201870358-b6b28fdf-16ae-41c1-b127-05f1649736f3.png)
![image](https://user-images.githubusercontent.com/63677994/201870405-e196f2f7-55d3-4d8c-aedc-50c77d1726e1.png)

On client prints the line 'Datos de el/la jugador(a) no válidos' while on server console prints 'Couldn't place player in world'
I will leave the last console and client log files on the issue

[latest.log](https://github.com/IzzelAliz/Arclight/files/10010743/latest.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/10010752/latest.log)

Regards!

**Comment by IzzelAliz** [comment]
See #823.
