### ISSUE TITLE
应用能源2线缆无法放置

### ISSUE THREAD

**Issue by Sha-Pao** [IzzelAliz/Arclight#82]
### 我正在运行

* **Arclight** [arclight-forge-1.16-1.0.9-SNAPSHOT] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **Mod 列表** 
minecraft forge-1.16.3-34.1.25-server.jar：minecraft（1.16.3）-1
•mods_folder [建筑_铁路] mcw-bridges-1.0.4-mc1.16.3.jar：mcwbridges（1.0.4） -1
•mods_folder [天赋树] GokiStats-1.16.3-1.2.12.jar：gokistats（1.2.12）-1
•mods_folder [地牢战利品袋子] randomloot-2.1.7.jar：randomloot（2.1.7）- 1
•mods_folder [魔法工艺3] mana-and-artifice-1.0.8.6.jar：mana-and-artifice（1.0.8.6）-1
•mods_folder [沉浸工程] ImmersiveEngineering-1.16.3-4.1.1-127。 jar：沉浸式工程（1.16.3-4.1.1-127）-1
•mods_folder [结构轮廓] BBOutlineReloaded-2.4-1.16.3-forge.jar：bbor（2.4-1.16.3）-1
•mods_folder [jei物品管理器]
jei-1.16.3-7.6.0.51.jar：jei（7.6.0.50 ）-1 •mods_folder [旷野高塔] towers_of_the_wild-1.16.3-2.0.1.jar：towers_of_the_wild（1.16.3-2.0.1 ）-1
•mods_folder [属性修复] AttributeFix-1.16.3-8.0.2.jar：attributefix（8.0.2）-1
•mods_folder [魔术师] the-conjurer-1.16.3-1.0.13.jar：conjurer_illager（1.0。 13）-1
•mods_folder [哥布林商人] goblintraders-1.2.2-1.16.3.jar：妖精交易者（1.2.2）-1
•mods_folder [通用机械mek] Mekanism-1.16.3-10.0.15.441.jar ：mekanism（10.0.15）-1
•mods_folder [仅客户端] [jei扩展jein] jeiintegration_1.16.3-6.0.0.8.jar：jeiintegration（6.0.0.8）-1
•mods_folder [前缀] [饰品栏] curios -forge-1.16.3-4.0.2.0.jar：古玩（1.16.3-4.0.2.0）-1
•mods_folder [植物魔法] Botania-1.16.3-408.jar：botania（1.16.3-408）- 1
•mods_folder [帕秋莉手册] Patchouli-1.16.2-45.jar：广patch香（1.16.2-45）-1
•mods_folder [传送石碑] Waystones_1.16.3-7.3.0.jar：waystones（7.3.0 ）-1
•mods_folder [懒人厨房] CookingForBlockheads_1.16.3-9.2.1.jar：cookingforblockheads（9.2.1）-1
•mods_folder [消除合成冲突] polymorph-forge-1.16.3-0.15.jar：polymorph（1.16.3- 0.15）-1
•mods_folder [应用能源2] applied energystics2-8.1.0-beta.2.jar：apply energystics2（8.1.0-beta.2）-1
•mods_folder [夸克支持库] AutoRegLib-1.6-46.jar： autoreglib（1.6-46）-1
•mods_folder [药王之王] potionsmaster-0.1.24-1.16.3-34.1.42.jar：potionsmaster（0.1.24）-1
•mods_folder [载具前置] obfuscate- 0.5.0-1.16.3.jar：混淆（0.5.0）-1
•mods_folder [载具] vehicle-mod-0.45.1-1.16.3.jar：车辆（0.45.1）-1
•mods_folder [前置] [结构化] structurize-0.13.96-ALPHA-universal.jar：structurize（0.13.96-ALPHA）-1
•mods_folder [神秘遗物] EnigmaticLegacy-2.9.0.jar：enigmaticlegacy（2.9.0）-1
•mods_folder [模拟殖民地] minecolonies-0.13.437-RELEASE-universal.jar：minecolonies（0.13.437-RELEASE）-1
•mods_folder [mek工具] MekanismTools-1.16.3-10.0.15.441.jar：mekanismtools（10.0.15）-1
•mods_folder [目标] [道路] mapperbase-1.16.3-2.1.0.1.jar：mapperbase（1.16 .3-2.1.0.1）-1
•mods_folder [道路] roadstuff-1.16.3-4.1.0.jar：roadstuff（1.16.3-4.1.0）-1
•mods_folder [仅服务端] [ai改进] AI -Improvements-1.16.2-0.3.0.jar：aiimprovements（0.3.0）-1
•mods_folder [mek发电机] MekanismGenerators-1.16.3-10.0.15.441.jar：mekanismgenerators（10.0.15）-1
•mods_folder [迫真蔚蓝] walljump-forge-1.16.3-1.3.6.jar：walljump（1.16.3-1.3.6）-1
•arclight arclight-forge-1.16-1.0.9-SNAPSHOT.jar：arclight（1.16.3-1.0.9-SNAPSHOT-3caea59）-1
•maven_libs forge-1.16.3-34.1.25-universal.jar：forge（ 34.1.25）-1
•mods_folder [夸克] Quark-r2.4-271.jar：夸克（r2.4-271）-1
•mods_folder [前缀] [cofh核心] cofh_core-1.16.3-1.0.2 .jar：cofh_core（1.0.2）-1
•mods_folder [热力基础] thermal-1.16.3-1.0.1.jar：thermals（1.0.1）-1
•mods_folder [热力扩展_热力革新] thermal_innovation-1.16。 3-1.0.0.jar：thermal_innovation（1.0.0）-1
•mods_folder [热力扩展_万象] ensorcellation-1.16.3-1.0.2.jar：ensorcellation（1.0.2）-1
•mods_folder [热力膨胀5 ] thermal_expansion-1.16.3-1.0.1.jar：thermal_expansion（1.0.1）-1
•mods_folder [时装盔甲] CosmeticArmorReworked-1.16.3-v1.jar：Cosmeticarmorreworked（1.16.3-v1）-1
•mods_folder [废弃矿井生成优化] BetterMineshaftsForge-1.16.2-1.0.1.jar：bettermineshafts（1.16.2-1.0.1）-1
•mods_folder [魔术师主体] structure-gel-api-1.16.3- 1.6.0.jar：structure_gel（1.6.0）-1
•mods_folder [循环] Cyclic-1.16.3-0.8.3.jar：循环（1.16.3-0.8.3）-1

### 错误描述

1)世界中无法放置AE2中的各种线缆，右键后会听到玻璃破碎的声音，但手中的物品不会减少。
后台会抛出错误，但是服务端不会崩溃。
2)除此之外在安装夸克模组后，原版的附魔台放置后不会消耗，但地图上会放置一个附魔台，可以正常使用，但无法被破坏，只能通过/fill指令清除。
 同样后台也会抛出错误，服务端不崩溃。

**可在 Forge 复现** [是]

### 报错信息

[对于问题1:https://paste.ubuntu.com/p/tPSyb5G52d/
对于问题2:https://paste.ubuntu.com/p/6JSyfY2qQW/]

**Comment by IzzelAliz** [comment]
请用最新构建检查第一个问题，第二个暂时无法修复

**Comment by Sha-Pao** [comment]
> 请用最新构建检查第一个问题，第二个暂时无法修复

最新的构建似乎是1.16.4...出现bug的服务端是1.16.3的3caea594....

**Comment by IzzelAliz** [comment]
一样的

**Comment by Sha-Pao** [comment]
> 一样的

也就是说我可以用1.16.3的客户端进装了1.16.3模组的1.16.4的服务端吗- -感觉不行呢
