### ISSUE TITLE
[1.18] Create mod toolbox error

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#820]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.7-SNAPSHOT-90ed520

### OS & Java versions

java 17

### Plugins and Mods

```raw
Create 0.5.0e
```

### Description

The toolbox is like a different shulker from  Create mod. You can also access things with Alt key if you are close enough. It gives errors sometimes and spams what I pasted in the logs

### Logs

https://pastebin.com/4crfnu56

**Comment by muriplz** [comment]
This happens when people put a minecart contraption on item form inside a toolbox, it becomes unusable

**Comment by IzzelAliz** [comment]
This tells some network packet is too large, which is not related to Arclight. You should report to Create dev or try to upgrade to their latest version.
