### ISSUE TITLE
[1.16] Error (and disconnects) while loading in chunks

### ISSUE THREAD

**Issue by zThana** [IzzelAliz/Arclight#821]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb

### OS & Java versions

OS: Ubuntu 5.4.0-120-generic; Java: OpenJDK 1.8.0_352

### Plugins and Mods

```raw
Forge, Arclight, Pixelmon
```

### Description

While loading in chunks from a newly imported world, console would often print the error below and sometimes disconnect the player.

### Step to reproduce

1. Import a new world
2. Fly around to load in new chunks

### Logs

https://pastebin.com/AE9pqmMW

**Comment by IzzelAliz** [comment]
Run a force upgrade on something like Spigot before you import it into Arclight.
