### ISSUE TITLE
Remove Hunger issue

### ISSUE THREAD

**Issue by DoZysGuy** [IzzelAliz/Arclight#826]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.24

### OS & Java versions

OS: Windows 11 and tested on Debian 4.19.181-1 too, with java 11.0.14 for Windows and 11.0.16 for Debian.

### Plugins and Mods

```raw
Multiverse-Core-4.3.1.jar
```

### Description

It's impossible to remove hunger with /mvm set hunger false or a config on Marcely's Bedwars plugin "hunger: false".
Hunger just continue to decrease.

I tested and it's working on spigot server.

### Step to reproduce

1. Install Multiverse core on a arclight-forge 1.16.5 server setup.
2. Use /mvm set hunger false.
3. Use /mv info 2 to see "player get hungry: false".
4. And run to see the hunger bar decrease.

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/10112020/latest.log)

**Comment by SnowBlitzz** [comment]
same issue if you go into /god using any plugin where its supposed to stop your hunger from depleting
https://github.com/Zrips/CMI/issues/7763
I don't think this should be closed just yet
