### ISSUE TITLE
Only delete the fml tag.

### ISSUE THREAD

**Issue by Fedes10** [IzzelAliz/Arclight#827]
Only delete the fml tag.

_Originally posted by @heipiao233 in https://github.com/IzzelAliz/Arclight/issues/822#issuecomment-1328802794_

I tried what you told me, plus I did it in the two worlds that the server has and it still doesn't work. I don't understand why it doesn't work. Could the error be hidden in the console? It's just that I've been checking it and I don't see anything abnormal and maybe it can't be seen with the naked eye. I honestly don't know what else to do

**Comment by heipiao233** [comment]
Please don't post it in a new issue.
