### ISSUE TITLE
插件用到getbiome的会报location为null的错误

### ISSUE THREAD

**Issue by gundami** [IzzelAliz/Arclight#829]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.2-1.0.1-SNAPSHOT-7359fd2

### Java 版本 | 操作系统

opensuse 15.3 | OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.4.0.4+8-GA (build 17.0.4+8, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
Civs
RandomSpawnPlusPlus
```

### 错误描述

以及后台一直刷location的报错，RandomSpawnPlusPlus是我自己写的插件，用到location的地方一样报错

### 复现步骤

1. 安装civs插件
2. 进入游戏
4. 后台刷巨大多报错

### 报错信息

https://paste.ubuntu.com/p/YJpxRQBgnx/

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by gundami** [comment]
已经修复，非常感谢
