### ISSUE TITLE
[1.18.2] unable to run arclight on pebblehost

### ISSUE THREAD

**Issue by xemnes** [IzzelAliz/Arclight#830]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

 arclight-forge-1.18.2-1.0.7

### OS & Java versions

unsure, this is pebblehost, a hosting service

### Plugins and Mods

```raw
plugins:
voxelsniper
essentials

mods:
https://pastebin.com/q77wAnHU
```

### Description

i setup my server with arclight on my computer, everything ran fine, i created a bat with `java -jar arclight-forge-1.18.2-1.0.7.jar` and ran it and let it install. did my tests, made sure everything was stable and working correctly
i proceeded to purchase pebblehost and upload my server
added the arclight jar to their launcher (i cannot use my own bat files, pebblehost deletes these automatically from the server)
i ran the server on pebblehost, it seemed to boot, until i found out it was just vanilla forge, running /plugins says unknown command. arclight doesnt seem to run at all even though ive pointed pebblehost to use the arclight jar.

whats even weirder is, when i run the arclight jar, the jar filesize becomes 1bytes
i uploaded it again just to be sure, ran it again, the jar becomes 1bytes again, which doesnt make sense at all.

is there a reason for this weird behaviour when using arclight with pebblehost, is there a fix?

### Step to reproduce

1 setup arclight on local computer
2 upload to pebblehost
3 add arclight jar to the pebblehost config
4 run the server

### Logs

https://pastebin.com/9129thzw

**Comment by heipiao233** [comment]
Maybe pebblehost doesn't trust Arclight and they don't know whether Arclight is a malware or not.

**Comment by heipiao233** [comment]
Use VPS instead of panel servers like pebblehost may fix this, but that is more expensive.

**Comment by xemnes** [comment]
i dont think its down to malware, but simply due to how arclight is run. i have spoken to pebblehost and they said they dont support the method of which arclight is booted. i went for pebblehost because it was cheap, theres no way i can afford a vps when the cheaper alternative works just as well.
magma works on pebblehost just fine, the problem with magma is that it doesnt support the forge version of worldedit and its important that it does since this is a creative server. so i opted to use arclight which does support worldedit, but it doesnt work with pebblehost.
im mainly just hoping for a working workaround to this issue.

**Comment by IzzelAliz** [comment]
Ask your hosting provider for support. Launching Arclight is nothing different from launching a spigot server, which should be support by all hosting services.

**Comment by xemnes** [comment]
great... so im stuck. time to see if i can get a refund on pebblehost then.
