### ISSUE TITLE
arclight崩溃

### ISSUE THREAD

**Issue by shizegame** [IzzelAliz/Arclight#832]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.7-40114eb5

### Java 版本 | 操作系统

系统:Windows Server 2019,Java:java version "19.0.1" 2022-10-18

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

使用mcsmanager开服，接着跑了好多代码，最后显示Fail to launch Arclight.

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/10192944/latest.log)

**Comment by IzzelAliz** [comment]
不支持 Java 19
