### ISSUE TITLE
Crashes with EarthMobs installed

### ISSUE THREAD

**Issue by gousisme** [IzzelAliz/Arclight#833]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1

### OS & Java versions

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Plugins and Mods

```raw
• mods_folder EarthMobs-1.19.2-4.1.0.jar : earthmobs (4.1.0) - 1
```

### Description

There's something about the conflicting mixin of the pig

### Step to reproduce

1. Install Earth Mobs mod
2. Server crashes on start

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/10196596/latest.log)

**Comment by gousisme** [comment]
Also, the same thing happens with Immersive Armors mod too

**Comment by DANTEARCONTE** [comment]
the earth mobs 3.5.2 works well, i was using the 4.1.0, the problem is the zombified pig, i dont know why... so i change to old version and i lost duck, wither wolf and zombified pig, but is working, i made an issue post in mod github, ill hope someone can find the problem, here or there...
