### ISSUE TITLE
工业矿物不在1.19.2生成

### ISSUE THREAD

**Issue by Eustiya** [IzzelAliz/Arclight#834]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1-SNAPSHOT

### Java 版本 | 操作系统

win2020 jdk-18.0.1.1

### 相关 Mod/插件 的名称及版本

```raw
[19:17:09 INFO]: Mod List:
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• minecraft forge-1.19.2-43.1.55-universal.jar : forge (43.1.55) - 1
• mods_folder industrialcraft-2-2.9.21+ex119-1.19.2-forge.jar : ic2 (2.9.21+ex119) - 1
• arclight arclight-1.19.2-1.0.1-SNAPSHOT-b8adaaba.jar : arclight (1.19.2-1.0.1-SNAPSHOT-b8adaaba) - 1
• mods_folder appliedenergistics2-forge-12.9.1.jar : ae2 (12.9.1) - 1

Plugins (2): Mizzen, Multiverse-Core
```

### 错误描述

工业矿物不在1.19.2生成，另外安装了AE2mod

### 报错信息

 [debug.log](https://github.com/IzzelAliz/Arclight/files/10199946/debug.log)

如果需要mod，我在这里提供。
[mod.zip](https://github.com/IzzelAliz/Arclight/files/10199953/mod.zip)

### 复现用压缩包下载链接(可选)

https://github.com/IzzelAliz/Arclight/files/10199953/mod.zip

**Comment by appleLPG** [comment]
这个版本工业完成度低 没有添加矿石生成

**Comment by Eustiya** [comment]
> 这个版本工业完成度低 没有添加矿石生成

是有更新的版本吗
