### ISSUE TITLE
生态附魔 附魔内容及描述无法显示

### ISSUE THREAD

**Issue by appleLPG** [IzzelAliz/Arclight#835]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1

### Java 版本 | 操作系统

windows11 x64 openjdk 17.0.5 x64

### 相关 Mod/插件 的名称及版本

```raw
eco-6.47.0-all
EcoEnchants v9.14.0
ProtocolLib
```

### 错误描述

生态附魔名称及描述不显示 附魔功能可以正常使用

### 复现步骤

1.安装生态附魔及前置
2.进入服务器输入/ecoenchants gui
3.附魔书无附魔名称及描述

**Comment by timi137137** [comment]
盲猜是ProtocolLib又又又出问题了（待测试）

**Comment by appleLPG** [comment]
今天试了一下，已被修复
