### ISSUE TITLE
1.182 群峦mod无法使用打火器

### ISSUE THREAD

**Issue by Re-Aqest** [IzzelAliz/Arclight#836]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

 arclight-1.18.2-1.0.7-40114eb5

### Java 版本 | 操作系统

java version "17.0.2" 2022-01-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
https://github.com/TerraFirmaCraft/TerraFirmaCraft/releases
最新版本TerraFirmaCraft 1.18.x-2.2.2
```

### 错误描述

无法使用起火器  拿在手里和普通木棍一样
https://s2.loli.net/2022/12/11/85WGZY6R2VMUSB4.png

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by Re-Aqest** [comment]
> 请测试是否修改

已经可以使用了 感谢
