### ISSUE TITLE
最新版本Zmusic，Allmusic等音乐插件无法使用

### ISSUE THREAD

**Issue by yaoxiaosa** [IzzelAliz/Arclight#84]
### 我正在运行

* **Arclight** [arclight-1.16.4-1.0.9-2b18bb8] 

* **你确认这是最新版吗** [是，因为我查看过QWQ]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_131] 

* **操作系统** [Linux (amd64) version 5.8.9-1.el7.elrepo.x86_64]]

* **插件列表** 
MiniMOTD, AntiExplosion, Chunky, SAML, PlaceholderAPI, VillagerOptimiser, UltimateTimber, PlayerRider, LaggRemover, ProtocolLib, CratesLottery, SpigotPing, DisableAI, AdvancedCleaner, Yum, AntiCraft, Forward, Vault, DaeFase, AuthMe, ZMusic, UltiEconomy, LockettePro, Residence, LCGShop, NexEngine, GoldenChallenges

* **Mod 列表** 
• minecraft forge-1.16.4-35.1.4-server.jar : minecraft (1.16.4) - 1
• mods_folder 工业先锋.jar : industrialforegoing (3.2.2) - 1
• mods_folder FarmersDelight-1.16.3-0.2.3.jar : farmersdelight (1.16.3-0.2.3) - 1
• mods_folder 工业先锋前置.jar : titanium (3.2.1) - 1
• mods_folder 沉浸工业.jar : immersiveengineering (1.16.3-4.1.1-127) - 1
• mods_folder mana-and-artifice-1.0.8.6.jar : mana-and-artifice (1.0.8.6) - 1
• mods_folder 生物工厂.jar : woot (1.16.3-1.0.0.2) - 1
• mods_folder Lollipop-1.16.3-3.2.2波瓦前置.jar : lollipop (3.2.2) - 1
• mods_folder 万用皮肤补丁.jar : customskinloader (14.13-SNAPSHOT-190) - 1
• mods_folder JEI.jar : jei (7.3.2.29) - 1
• mods_folder 简单农场.jar : simplefarming (1.16.4-1.3.5) - 1
• mods_folder 通用机械.jar : mekanism (10.0.15) - 1
• mods_folder curios-forge-1.16.3-4.0.2.0.jar : curios (1.16.3-4.0.2.0) - 1
• mods_folder 植物魔法.jar : botania (1.16.3-409) - 1
• mods_folder Patchouli-1.16.2-47.jar : patchouli (1.16.2-47) - 1
• mods_folder CookingForBlockheads_1.16.3-9.2.1.jar : cookingforblockheads (9.2.1) - 1
• mods_folder AE2.jar : appliedenergistics2 (8.1.0-beta.2) - 1
• mods_folder FluxNetworks-1.16.3-6.0.1.4.jar : fluxnetworks (1.16.3-6.0.1.4) - 1
• mods_folder 波瓦科技.jar : powah (2.3.4) - 1
• mods_folder 烹饪锅.jar : crockpot (1.1.3-release) - 1
• mods_folder worldedit-forge-mc1.16.3-7.2.0-dist.jar : worldedit (7.2.0+a51fa43) - 1
• mods_folder 简易飞机.jar : simpleplanes (1.16.3-3.2.0.1) - 1
• mods_folder 强化boss.jar : progressivebosses (2.1.8) - 1
• mods_folder MekanismGenerators-1.16.3-10.0.15.441.jar : mekanismgenerators (10.0.15) - 1
• arclight server.jar : arclight (1.16.4-1.0.9-2b18bb8) - 1
• mods_folder Ma-Essentials-1.16.3-3.4.0.jar : maessentials (1.16.3-3.4.0) - 1
• maven_libs forge-1.16.4-35.1.4-universal.jar : forge (35.1.4) - 1
• mods_folder plonk-1.16.3-9.0.2.jar : plonk (9.0.2) - 1
• mods_folder 豆腐craft.jar : tofucraft (1.16.3-0.1.4.2) - 1
• mods_folder 更多箱子.jar : ironchest (1.16.3-11.2.6) - 1

### 错误描述

正常安装ALLmusic或者Zmusic相对应的插件，下载相对应的模组，没有声音，询问作者得知不是插件问题QWQ

### 重现步骤

1. 安装Zmusic或者Allmusic插件，客户端安装相对应模组
2. 进入服务器后显示字幕但是没有声音
3. ....

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

**Comment by IzzelAliz** [comment]
请用最新版本测试

**Comment by yaoxiaosa** [comment]
测试过了，并不可以使用

**Comment by yaoxiaosa** [comment]
🥺空端测试，不能使用🥺🥺🥺

**Comment by yaoxiaosa** [comment]
spigot进行空端测试，可正常使用

**Comment by yaoxiaosa** [comment]
bukkit空端测试，不能使用
🥺🥺🥺🥺呜呜呜呜呜

**Comment by yaoxiaosa** [comment]
颜色佬更新了Allmusic的bukkit版本，bukkit空端测试可以使用，arclight空端测试不能使用

**Comment by Coloryr** [comment]
经检查是插件信道部分出现问题
测试版本`arclight-forge-1.16-1.0.10`，插件`AllMusic-2.8.0-all`

**Comment by IzzelAliz** [comment]
插件问题，没有注册 channel

**Comment by Coloryr** [comment]
https://github.com/HeartAge/AllMusic_P/blob/6ea391cc9daf93b1c4e94cd73ad81ce8aef4e712/src/main/java/Color_yr/AllMusic/AllMusicBukkit.java#L60
这不是注册了吗

**Comment by IzzelAliz** [comment]
我的意思是，客户端没有向服务器报告有这个 channel，要么你研究怎么把他发过去（REGISTRY 包），要么你反射玩家的 channels 自己加上

**Comment by Coloryr** [comment]
这不是forge做的事情吗，为何我插件要这样搞。
Spigot和Craftbukkit都能用，就你这个用不了，我插件注册的都注册了，[Mod](https://github.com/HeartAge/AllMusic_M/blob/6cc058a95d725a92679190e63ca52041ac22e5bd/src/main/java/Color_yr/AllMusic/AllMusic.java#L54)那部分也是

**Comment by IzzelAliz** [comment]
~~事实就是 forge 客户端不会给 forge 服务端注册服务端没有的 channel，你得自己想办法~~

算了我想办法，你大概也不想修
