### ISSUE TITLE
[1.19.2] Questions | Client mods/Velocity

### ISSUE THREAD

**Issue by artiser10** [IzzelAliz/Arclight#841]
Hello there! 
• I have a problem using client mods. The server does not connect players who have client mods installed, which are not (and cannot be) on the server.

• Also, would like to ask about the approximate timing of the organization of the velocity proxy with servers on the Arclight core? Are there any alternative proxies at the moment?

Thank for any help!

**Comment by heipiao233** [comment]
Use lightfall
