### ISSUE TITLE
[1.16.5] MmoCore not working

### ISSUE THREAD

**Issue by iSoulEs** [IzzelAliz/Arclight#843]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9

### OS & Java versions

OS: Windows 11 x64, Java: openjdk version "16.0.2" 2021-07-20

### Plugins and Mods

```raw
Plugins (3): MythicLib version 1.4.1 , MMOCore Premium - Version 1.10.2 , MMOItems Premium 6.8.2 

Mod List:
• minecraft forge-1.16.5-36.2.39-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.2.39-universal.jar : forge (36.2.39) - 1
• arclight server.jar : arclight (1.16.5-1.0.25-SNAPSHOT-aeef36e9) - 1
```

### Description

mmocore plugin should run correctly, but is disabled by console error
 type:   /mmocore    and it should show all the commands
 

### Step to reproduce

1- Run the server.
2- Stop and paste the plugins in the plugins folder
3- Run the server again
3- You will get the problem in the console 

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/10251076/latest.log)
server.
2- Stop and paste the plugins in the plugins folder
3- Run the server again
3- You will get the problem in the console 

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/10251076/latest.log)

### Server pack link (Optional)

**Comment by Ygaul** [comment]
Same problem in arclight 1.18.2 last dev (1.0.8)-1666e998

**Comment by demonsaurio** [comment]
same problem in that version

**Comment by timi137137** [comment]
maybe, the problem for plugin? 
![image](https://user-images.githubusercontent.com/36812439/208250272-6999f39a-92f7-464a-bb5e-e5eb15f74f09.png)

**Comment by Ygaul** [comment]
> maybe, the problem for plugin? ![image](https://user-images.githubusercontent.com/36812439/208250272-6999f39a-92f7-464a-bb5e-e5eb15f74f09.png)

works fine in purpur or paper. only happens in arclight

**Comment by iSoulEs** [comment]
> maybe, the problem for plugin? ![image](https://user-images.githubusercontent.com/36812439/208250272-6999f39a-92f7-464a-bb5e-e5eb15f74f09.png)

It seems to be a compatibility error between the module and arclight. using the same plugins and another loader (paper or purple) its works fine
logs with paper 1.16.5 last dev (same java):
[latest.log](https://github.com/IzzelAliz/Arclight/files/10252161/latest.log)

**Comment by iSoulEs** [comment]
![image](https://user-images.githubusercontent.com/83812194/208251996-a78f5d8a-b3e3-489c-b0d1-c7fc428f5e3d.png)

**Comment by demonsaurio** [comment]
magma and mohist same problem, i think is a incompatibility with hybrids

**Comment by Eibsnaits** [comment]
We 'have the same problem in our server with this version

**Comment by timi137137** [comment]
emmm, i'm sorry.   i can't help more, because in log file.    only can see the mmocore use a something that doesn't exist, maybe in paper that exist.  but in arclight that doesn't exist. i can't get to the root of the problem. that's the problem
![image](https://user-images.githubusercontent.com/36812439/208735119-a6880b63-e097-469c-9d37-164a9787da89.png)
*postscript：we only can see mmocore error for enable method

**Comment by iSoulEs** [comment]
> emmm, i'm sorry. i can't help more, because in log file. only can see the mmocore use a something that doesn't exist, maybe in paper that exist. but in arclight that doesn't exist. i can't get to the root of the problem. that's the problem ![image](https://user-images.githubusercontent.com/36812439/208735119-a6880b63-e097-469c-9d37-164a9787da89.png) *postscript：we only can see mmocore error for enable method

I asked mmocore if they would fix the error so that it works on hybrids but they do not provide support
the mmocore 1.9.4 works in arclight but the latest mmocore 1.11 dont works in arclight 
Will there be a plugin fix?
like mmocore-arclight.jar 
looking in the mmocore files it seems to be a line error inside the .jar but since I know little about the code I am unable to fix it so that it works in arclight

**Comment by iSoulEs** [comment]
@timi137137 can you install this library in arclight 1.16.5? i think this fix the problem.

`javax.inject:javax.inject:1`

**Comment by Xorbah** [comment]
@timi137137 The user above me is right. Magma fixed this issue by adding it to their source. The link for proof is here https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/merge_requests/174

**Comment by timi137137** [comment]
@Xorbah Thank you for confirming that
Therefore, it is impossible to add unused dependencies in the arclight, so we have to let mmocore solve it itself
