### ISSUE TITLE
[1.18.2] Do not generate structure（世界不生成结构）

### ISSUE THREAD

**Issue by Misaka2298** [IzzelAliz/Arclight#844]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [x] 不可在 Forge 复现

### Arclight 版本

1.0.7

### Java 版本 | 操作系统

jdk18.0.1.1 | Windows11

### 相关 Mod/插件 的名称及版本

```raw
plugin:Multiverse-Core
```

### 错误描述
(中文)
不管是用多世界插件生成还是用数据包生成世界，都没有结构刷出来
如果我使用/locate去找结构，服务端会闪退
arclight.conf里面的symlink-world已经true了
我感觉问题出在这个报错上https://i.postimg.cc/nL1ykhG5/6-YAXQ-RYA5-L-7-EQLM.jpg
救一下求求，被这个问题困扰一个月了

(English ver.)
(I used the Baidu Translate)
Whether you use Multiverse-Core to generate the world or data package to generate dimensions,They have no structure (such as villages).
If I use /locate to try to find the structure, the server will flash back

symlink-world in arclight.conf has been changed to true

I think this problem may be related to this error: https://i.postimg.cc/nL1ykhG5/6-YAXQ-RYA5-L-7-EQLM.jpg

Please help me. I have been troubled by this problem for a month

### 复现步骤
（中文）
1.开服
2.使用指令：/mv create 世界名 normal （创建一个世界
3.进入世界
4.到处飞但没找着村庄
5.如果我使用/locate minecraft:plain_vilage（也有可能是village_plain，记不清了)找村庄的话服务器会闪退

(English ver.)
1.Start the server
2.Use command: “/mv create worldname normal”to create a world
3.Enter the world
4.Look everywhere, but no structure is found
5.If I use command:"/locate minecraft:plain_village"(This may be “village_plain”, I can't remember it clearly)，The server will flash back

### 报错信息

https://paste.fastmirror.net/?4f1e0db98c4b3eb1#ECEmJgS67gmjLmnqMT2UZSVspyvkxuoV4dCnH6GabxRX

### 复现用压缩包下载链接(可选)

https://1drv.ms/u/s!AoYx-pGIVLdOhBrHNSGh39i62GHc?e=soglLb

**Comment by Misaka2298** [comment]
I checked the wiki of Multiverse Core and found this sentence. I think it is useful
"Despite being able to do all this, do note that Multiverse-Core does not create worlds itself, it simply makes calls to the Bukkit-API to create the worlds."

So I think the problem is Bukkit API?

**Comment by Misaka2298** [comment]
等下，Arclight的作者是中国人？
草，那我为什么要翻译（

**Comment by heipiao233** [comment]
> 等下，Arclight的作者是中国人？ 草，那我为什么要翻译（

是的
