### ISSUE TITLE
[1.16.5] 不兼容 TabooLib（module-configuration模块）

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#848]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.25-SNAPSHOT（373最新）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
示例插件：Pouvoir（或其他使用了最新版TabooLib的插件）（TabooLib 版本6.0.9-111以上）

Pouvoir是一个脚本插件，也是一个系列插件的前置库
插件链接：https://www.mcbbs.net/thread-1221977-1-1.html
```

### 错误描述

弧光不兼容最新版TabooLib的module-configuration，
使用最新版TabooLib作为依赖编译的插件，均无法在弧光正常载入。

Could not load 'plugins\Pouvoir-1.5.2-58.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Bad type on operand stack
Reason:
    Type 'java/lang/Object' (current frame, stack[4]) is not assignable to 'org/yaml/snakeyaml_1_32/nodes/Node'

TabooLib 6.0.9-111 版本以后开始出现兼容问题
GIthub链接：https://github.com/TabooLib/taboolib/commit/d9186f68a6b0caa3e1ea61e06e2151ddece372ee

使用JDK16-17均出现以上问题
在spigot不存在此问题，无法复现

### 复现步骤

1、安装以最新TabooLib作为依赖库开发的插件，如：Pouvoir
2、启动服务器，相关插件载入失败，并报错

### 报错信息

**截取报错部分：**
https://paste.ubuntu.com/p/HbjjZCp9Zq/

**完整latest.log**
https://paste.ubuntu.com/p/JmTvVJYXMq/

**完整debug.log**
https://paste.ubuntu.com/p/MVxdTt3TTk/

**Comment by timi137137** [comment]
能把log补全吗，不看断头log

**Comment by luoxiawuchen** [comment]
> 能把log补全吗，不看断头log

噢噢，抱歉，已修改，已在正文补齐。

**完整latest.log**
https://paste.ubuntu.com/p/JmTvVJYXMq/

**完整debug.log**
https://paste.ubuntu.com/p/MVxdTt3TTk/

**Comment by luoxiawuchen** [comment]
> 能把log补全吗，不看断头log

请问新提交的log齐全吗？是否仍有遗漏？
没有问题的话可以移除 Need More Info | 需要更多信息 并添加对应新标签吗？谢谢！

**Comment by IzzelAliz** [comment]
请测试是否修复

**Comment by luoxiawuchen** [comment]
> 请测试是否修复

ok已修复
