### ISSUE TITLE
[1.19.2] Prefab中的挖掘机（bulldozer）在使用后无掉落物

### ISSUE THREAD

**Issue by Mad-Kang** [IzzelAliz/Arclight#849]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1

### Java 版本 | 操作系统

win10 x64 java version "17.0.2" 2022-01-18 LTS Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86) Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
Mod：[预制建筑]prefab-1.9.2.4
Mod链接：https://www.mcmod.cn/class/1373.html
```

### 错误描述

prefab模组中的挖掘机（bulldozer）在使用后无掉落物
挖掘机（bulldozer）功能：挖掘16x16的区域，并生成此区域的物品掉落在地面。

客户端单人模式中使用挖掘机可以正常掉落挖掘区域的掉落物。 
arclight-forge-1.19.2-1.0.1服务端的run.bat启动服务器后，使用挖掘机，可以正常掉落挖掘区域的掉落物。但无法使用插件。

### 复现步骤

1.安装prefab至服务端mod文件夹及客户端mod文件夹下。
2.启动服务器。
3.启动客户端。
4.进入多人游戏进入服务器，设置OP并改为创造模式。
5.拿出挖掘机（bulldozer），用三倍压缩石头在铁毡上充能后，对准地面右键使用。
6.16x16的区域清除，但无掉落物。

**Comment by heipiao233** [comment]
装了哪些插件

**Comment by Mad-Kang** [comment]
> 装了哪些插件
Multiverse-Core-4.3.1
EssentialsX-2.19.7
Valt-1.7.3
EssentialsXGroupManager
Multiverse-Portals-4.2.1
