### ISSUE TITLE
[1.18.2]Forge版本过低导致无法启动服务器

### ISSUE THREAD

**Issue by MossCG** [IzzelAliz/Arclight#856]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.18.2-1.0.8-SNAPSHOT

### Java 版本 | 操作系统

Windows 10

### 相关 Mod/插件 的名称及版本

```raw
TravelersBackpack-1.18.2-7.1.19
ImmersiveEngineering-1.18.2-8.3.0-155
```

### 错误描述

ImmersiveEngineering-1.18.2-8.3.0-155 此模组需要forge40.1.86及以上
希望能更新一份forge 40.1.87的1.18.2  Arclight

实测在客户端环境下 40.1.80无法启动游戏 40.1.87可以正常启动

### 复现步骤

1.安装ImmersiveEngineering-1.18.2-8.3.0-155
2.启动服务器
3.boom

### 报错信息

https://paste.ubuntu.com/p/5ZgJtNSqrj/

**Comment by Misaka2298** [comment]
![image](https://user-images.githubusercontent.com/99007518/209285472-2a372e40-751d-4b5a-a6e2-e1d3dbbba908.png)

**Comment by MossCG** [comment]
> ![image](https://user-images.githubusercontent.com/99007518/209285472-2a372e40-751d-4b5a-a6e2-e1d3dbbba908.png)

感谢 已解决 自行修改了arclight的jar里头的installer.json为40.1.87的版本
