### ISSUE TITLE
Stoneblock 3 incompatible with latest update 1.18.2 worked on previous versions

### ISSUE THREAD

**Issue by MystifiedSky** [IzzelAliz/Arclight#858]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.8-SNAPSHOT

### OS & Java versions

Windows 10 java 19

### Plugins and Mods

```raw
https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3
```

### Description

Server crashes near instantly after starting the server.

### Step to reproduce

1. Install ftb stoneblock 3 latest update (worked on previous versions)
2. install arclight
3. run start.bat using arclight.jar

### Logs

I have the latest log at the top then debug below it https://paste.ubuntu.com/p/tghwY3D3Xd/

### Server pack link (Optional)

https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3

**Comment by heipiao233** [comment]
Some mod in this modpack needs java 19 instead of java 17

**Comment by MystifiedSky** [comment]
> Some mod in this modpack needs java 19 instead of java 17

thats my bad I am running java 19 I didnt actually check just thought
