### ISSUE TITLE
incompatible forge mod- questsadditions

### ISSUE THREAD

**Issue by haithem2459** [IzzelAliz/Arclight#861]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

questsadditions-1.19.2-1.4.1

### OS & Java versions

java 17 windows

### Plugins and Mods

```raw
na
```

### Description

mod is incompatible

### Step to reproduce

added and launched

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/10298301/latest.log)

**Comment by IzzelAliz** [comment]
Fixed in bf99715e
