### ISSUE TITLE
Velocity support?

### ISSUE THREAD

**Issue by nothendev** [IzzelAliz/Arclight#863]
I have read the FAQ and I know that lightfall is recommended, but, if I do not want to switch to lightfall (it is being or already is EOL'd), what options do I have?

I am running a fork of [Magmafoundation/Velocity](https://git.magmafoundation.org/Magmafoundation/Velocity) at branch modern-forge-rewrite as my proxy.

**Comment by IzzelAliz** [comment]
So you announced the death of lightfall.
