### ISSUE TITLE
[1.16.5] Incompatibility with Star Worm Equestrian Mod

### ISSUE THREAD

**Issue by Minecraftine** [IzzelAliz/Arclight#868]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Arclight version arclight-1.16.5-1.0.24-551ec3ff (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### OS & Java versions

java version "1.8.0_311" Java(TM) SE Runtime Environment (build 1.8.0_311-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

### Plugins and Mods

```raw
minecraft forge-1.16.5-36.2.39-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.2.39-universal.jar : forge (36.2.39) - 1
• mods_folder geckolib-forge-1.16.5-3.0.106.jar : geckolib3 (3.0.106) - 1
• mods_folder swem-1.16.5-0.5.3.3.jar : swem (1.16.5-0.5.3.3) - 1
• mods_folder player-animation-lib-forge-0.4.0+1.16.5.jar : playeranimator (0.4.0+1.16.5) - 1
• arclight arclight-forge-1.16.5-1.0.24.jar : arclight (1.16.5-1.0.24-551ec3ff) - 1
```

### Description

Arclight is incompatible with Star Worm Equestrian Mod. The server can run, but when we put tack on a horse and right-click on it to ride it, the server stops responding and crashes.

### Step to reproduce

1. In creative mode, type 'SWEM Horse', take the spawn egg.
2. Right-click on the ground to make it appear.
3. Click on it to tame it like a vanilla horse.
4. When it is tamed, open the creative tab and type 'bridle'.
5. Take any bridle.
6. Right-click on the horse.
7. When it has the bridle on, right-click on it again to ride it.
8. The server will stop responding.

### Logs

https://gist.github.com/Minecraftine/800ae5f8d6b5a8eaabcb29058325cdac

**Comment by MythicalMontie** [comment]
Unfortunately I am also having this issue....
