### ISSUE TITLE
[1.15] 当上次下线地点在未加载的世界时下次上线会在主世界出生

### ISSUE THREAD

**Issue by sandtechnology** [IzzelAliz/Arclight#87]
### 我正在运行

* **Arclight** [arclight-1.15.2-1.0.14-SNAPSHOT-9cbb72b] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [1.8.0_271-b09] 

* **操作系统** [Window10 2009]

* **插件列表** 
无

* **Mod 列表** 
• minecraft forge-1.15.2-31.2.45-server.jar : minecraft (1.15.2) - 1
• maven_libs forge-1.15.2-31.2.45-universal.jar : forge (31.2.45) - 1
• arclight arclight-forge-1.15-1.0.14-SNAPSHOT.jar : arclight (1.15.2-1.0.14-SNAPSHOT-9cbb72b) - 1

### 错误描述

当上次下线地点在未加载的世界时下次上线会在主世界出生

### 重现步骤

1. 进入服务器后进入地狱并下线
2. 等待后台提示世界卸载
3. 再次上线，出生在主世界
4. 使用 /forceload 命令强制加载地狱区块防止卸载，并再次重复上述步骤，无法重现

**可在 Forge 复现** [否，显然不是forge问题]

**可在 Spigot 复现** [否，显然不是spigot问题]

### 报错信息

[无]

**Comment by IzzelAliz** [comment]
可在 spigot 复现
