### ISSUE TITLE
与Create的动态结构座椅不兼容！

### ISSUE THREAD

**Issue by QWXL** [IzzelAliz/Arclight#870]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.7-40114eb5

### Java 版本 | 操作系统

系统：Windows11 JAVA:OpenJDK 64-Bit Server VM Zulu18.32+13-CA (build 18.0.2.1+1, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
create-1.18.2-0.5.0.e
flywheel-forge-1.18.2-0.6.5
```

### 错误描述

在机械动力mod的动态结构（使用活塞，起重机，动力轴承或列车站来创造一个动态结构，我推荐使用动力轴承，他是最简单实现动态结构的方块，但不够明显。使用列车站创造一个带天花板的火车是最明显的）上放置坐垫，激活动态结构并坐在坐垫上，当你按下Shift的时候，下坐垫的位置会位移。（如果你坐在什么东西下面，则你会弹到动态结构上方）

### 复现步骤

1.安装Create-1.18.2-0.5.0e和flywheel-forge-1.18.2-0.6.5
2.启动服务器
3.启动客户端
4.进入服务器
5.建造任意动态结构（旋转，起重机，活塞，火车结构皆可）
6.在动态结构上放置坐垫
7.构建动态结构并坐在坐垫上
8.按Shift下坐垫

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/10308766/latest.log)

**Comment by QWXL** [comment]
经测试，#716下给出的解决方案无效

**Comment by happyhin** [comment]
arclight-forge-1.19.2-1.0.1.jar 版本也有同样的问题

**Comment by QWXL** [comment]
@IzzelAliz

**Comment by Curitis-TK** [comment]
arclight-forge-1.18.2-1.0.9.jar 版本有相同问题

**Comment by QWXL** [comment]
@IzzelAliz

**Comment by QWXL** [comment]
create 0.5.1c  Arclight 1.18.2 1.0.9 问题依旧

**Comment by QWXL** [comment]
受不了了，自己修！
https://www.mcmod.cn/class/12218.html
