### ISSUE TITLE
PlotSquared 报错

### ISSUE THREAD

**Issue by 3269199948** [IzzelAliz/Arclight#871]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1.jar

### Java 版本 | 操作系统

java version "17.0.3.1" 2022-04-22 LTS Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6) Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
Plugins (13): MiniMOTD, LuckPerms, WorldEdit, EClean, PlaceholderAPI, TAB, PlotSquared, Multiverse-Core, ProtocolLib, WorldGuard, DeluxeMenus, CMILib, CMI

Mod List:
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• mods_folder [mod][华夏文明2]chinacraft-2.0.9.jar : chinacraft (2.0.9) - 1
• mods_folder [mod][BOP前置]TerraBlender-forge-1.19.2-2.0.1.130.jar : terrablender (2.0.1.130) - 1
• mods_folder [mod][围火无怪]nohostilesaroundcampfire_1.19.2-4.5.jar : nohostilesaroundcampfire (4.5) - 1
• mods_folder [mod][警卫村民]guardvillagers-1.19.2-1.5.2.jar : guardvillagers (1.19.2-1.5.2) - 1
• mods_folder [mod][BOP]BiomesOPlenty-1.19.2-17.1.2.492.jar : biomesoplenty (17.1.2.492) - 1
• mods_folder [mod][FTB前置]architectury-6.4.62-forge.jar : architectury (6.4.62) - 1
• mods_folder [mod][FTB前置]ftb-library-forge-1902.3.11-build.166.jar : ftblibrary (1902.3.11-build.166) - 1
• mods_folder [mod][皮肤]CustomSkinLoader_ForgeActive-14.15-SNAPSHOT-355.jar : customskinloader (14.15-SNAPSHOT-355) - 1
• mods_folder [mod][下届扩展]bygonenether-1.2.1-1.19.x.jar : bygonenether (1.2.1) - 1
• arclight arclight-1.19.2-1.0.1-0550c6cd.jar : arclight (1.19.2-1.0.1-0550c6cd) - 1
• mods_folder [mod][放大化下界]Amplified_Nether_v1.2.jar : amplified_nether (0.0NONE) - 1
• mods_folder [mod][JEI物品管理器]jei-1.19.2-forge-11.4.0.290.jar : jei (11.4.0.290) - 1
• mods_folder [mod][FTB Teams]ftb-teams-forge-1902.2.11-build.87.jar : ftbteams (1902.2.11-build.87) - 1
• mods_folder [mod][FTB Chunks]ftb-chunks-forge-1902.3.14-build.218.jar : ftbchunks (1902.3.14-build.218) - 1
• minecraft forge-1.19.2-43.2.0-universal.jar : forge (43.2.0) - 1
• mods_folder [mod][经典状态条]classicbar-1.19.2-6.1.1.jar : classicbar (1.19.2-6.1.1) - 1
• mods_folder [mod][帕秋莉手册]Patchouli-1.19.2-77.jar : patchouli (1.19.2-77) - 1
• mods_folder [mod][治愈营火]healingcampfire_1.19.2-3.9.jar : healingcampfire (3.9) - 1
• mods_folder [mod][围火无怪前置]collective-1.19.2-5.25.jar : collective (5.25) - 1
• mods_folder [mod][旅行者背包]TravelersBackpack-1.19.2-8.2.10.jar : travelersbackpack (8.2.10) - 1
```

### 错误描述

不需要添加MOD，这与mod无关

添加：PlotSquared，worldedit-bukkit，worldguard-bukkit插件即可，如果有漏掉的前置补上去即可，只要让PlotSquared能运行起来就行

### 复现步骤

1.进入服务器，给OP权限
2.输入：
/plot setup
/plot setup PlotSquared
/plot setup normal

后台报错，正常应该是控制台提示进行下一步操作

### 报错信息

https://paste.ubuntu.com/p/smxNvp8Cyf/

**Comment by 3269199948** [comment]
再补充一个，使用模板命令生成地皮世界的时候，只会生成普通的世界而不是地皮世界，没有报错，反正就是没效果
/plot template import test1 town

town（城镇模板）bridge（桥梁模板）skyblock（空岛模板）

**Comment by MossCG** [comment]
同问，此问题在arclight-1.18.2-1.0.8-SNAPSHOT-0a235737同样出现 报错相同，但是我的地皮世界直接生成了一个啥也没有的空世界
创世神版本 worldedit-bukkit-7.2.12-SNAPSHOT-dist
WG 版本worldguard-bukkit-7.0.7-dist

我直接套用了我在原版（Paper）的1.18.2版本服务器上的WorldEdit和PlotSquared配置文件，生成世界的时候会报错

**Comment by 3269199948** [comment]
> 同问，此问题在arclight-1.18.2-1.0.8-SNAPSHOT-0a235737同样出现 报错相同，但是我的地皮世界直接生成了一个啥也没有的空世界 创世神版本 worldedit-bukkit-7.2.12-SNAPSHOT-dist WG 版本worldguard-bukkit-7.0.7-dist
> 
> 我直接套用了我在原版（Paper）的1.18.2版本服务器上的WorldEdit和PlotSquared配置文件，生成世界的时候会报错

PlotSquared-Bukkit-6.7.0-Premium版本能用，但是也只能用常规方式生成，生成之后地皮权限失效，可以随意破坏地皮

**Comment by SakuranaRanbom** [comment]
> > 同问，此问题在arclight-1.18.2-1.0.8-SNAPSHOT-0a235737同样出现 报错相同，但是我的地皮世界直接生成了一个啥也没有的空世界 创世神版本 worldedit-bukkit-7.2.12-SNAPSHOT-dist WG 版本worldguard-bukkit-7.0.7-dist
> > 我直接套用了我在原版（Paper）的1.18.2版本服务器上的WorldEdit和PlotSquared配置文件，生成世界的时候会报错
> 
> PlotSquared-Bukkit-6.7.0-Premium版本能用，但是也只能用常规方式生成，生成之后地皮权限失效，可以随意破坏地皮

PlotSquared-Bukkit-6.11.0-Premium 在1.18.2 LTS arclight中可以通过setup 正常生成+使用，地皮权限也是正常的

**Comment by 718890563** [comment]
[18:16:56 ERROR]: Error occurred while enabling PlotSquared v7.3.6-Premium (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerSignOpenEvent
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
        at com.plotsquared.google.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48) ~[plotsquared-bukkit-7.3.6-Premium.jar:?]
        at com.plotsquared.google.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:813) ~[plotsquared-bukkit-7.3.6-Premium.jar:?]
        at com.plotsquared.google.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:732) ~[plotsquared-bukkit-7.3.6-Premium.jar:?]
        at com.plotsquared.google.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:432) ~[plotsquared-bukkit-7.3.6-Premium.jar:?]|
       为什么会这样
