### ISSUE TITLE
[1.16.5] Arclight-1.16.5-373构建 蜜蜂行为异常，无法正常产蜜

### ISSUE THREAD

**Issue by luoxiawuchen** [IzzelAliz/Arclight#875]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

Arclight-1.16.5-373（最新）

### Java 版本 | 操作系统

windows10 x64、java：openjdk16_x64_windows

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

373构建对蜜蜂的性能进行了改进，但同时蜜蜂在采蜜进入蜂巢后将不再产蜜，一直停滞
退回到372版本后没有触发此问题
相关提交：[perf(common): stop bees aging inside hives (#763)](https://github.com/IzzelAliz/Arclight/actions/runs/3402955340)

**Comment by IzzelAliz** [comment]
回滚了(509cb95373cd88cb5df7ce818fc58413f28a3273)。

@danorris709 Can you take a look into related bee ai breaking?
