### ISSUE TITLE
arclight1.18.2在加入旅行者背包后无法启动

### ISSUE THREAD

**Issue by C1-000** [IzzelAliz/Arclight#880]
### 请确认您已完成以下几件事

- [x] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.18.2-1.0.7-40114eb5

### Java 版本 | 操作系统

系统:CentOS7.9 X64 JAVA:openjdk17

### 相关 Mod/插件 的名称及版本

```raw
旅行者背包Traveler's Backpack
```

### 错误描述

在加入旅行者背包（一个背包MOD，无前置）后无法启动服务端，提示Missing mandatory dependencies: forge

### 复现步骤

1.启动
2.启动成功
3.关闭
2.加入旅行者背包(Traveler's Backpack)MOD
3.启动
4.启动失败

### 报错信息

[latest (1).log](https://github.com/IzzelAliz/Arclight/files/10334961/latest.1.log)

**Comment by chunye666** [comment]
是不是forge版本的问题，我头两天组端的时候也是，客户端使用跟服务端一样的40.1.80，然后旅行者背包不服了（启动不了），提示需要40.1.94版本，感觉是这个问题

**Comment by C1-000** [comment]
我的客户端是40.1.86能用

**Comment by sileence114** [comment]
就是forge版本的问题，可以拿forge-installer生成的run启动脚本运行纯forge服务器看下，有些mod要求较高版本的forge（譬如我的问题是最新版的匠魂TConstruct-1.18.2-3.6.3.111，要求forge版本是40.1.88，而现在arclight-forge-1.18.2-1.0.8的forge安装的版本是40.1.80）

forge运行会报错告诉你哪个mod依赖缺失，而arclight没报哪个mod的问题。。。

> 是不是forge版本的问题，我头两天组端的时候也是，客户端使用跟服务端一样的40.1.80，然后旅行者背包不服了（启动不了），提示需要40.1.94版本，感觉是这个问题

> 我的客户端是40.1.86能用

**Comment by IzzelAliz** [comment]
你需要更新 forge
