### ISSUE TITLE
[1.19.2]服务器无法启动

### ISSUE THREAD

**Issue by JellyBubb1e** [IzzelAliz/Arclight#882]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1.jar

### Java 版本 | 操作系统

系统：Windows 11 21H2|java version "18.0.1.1" 2022-04-22

### 相关 Mod/插件 的名称及版本

```raw
immersive_armors-1.5.2+1.19.2-forge
```

### 错误描述

与沉浸式盔甲不兼容。导致无法启动服务器。

### 复现步骤

1.将 immersive_armors 拖入mods文件夹
2.启动服务器

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/10341648/latest.log)

**Comment by timi137137** [comment]
link #698
