### ISSUE TITLE
[1.19.2]Allmusic 无法使用

### ISSUE THREAD

**Issue by JellyBubb1e** [IzzelAliz/Arclight#883]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.2-1.0.1.jar

### Java 版本 | 操作系统

系统：Windows 11 21H2|java version "18.0.1.1" 2022-04-22

### 相关 Mod/插件 的名称及版本

```raw
AllMusic-2.17.1-all.jar
```

### 错误描述

music search 指令无法使用。

### 复现步骤

1.将allmusic插件放入plugins文件夹
2.启动服务器

### 报错信息

[latest.log](https://github.com/IzzelAliz/Arclight/files/10341819/latest.log)

**Comment by Kotori0629** [comment]
装Vault没

**Comment by JellyBubb1e** [comment]
> 

未加。
后加了，也无用。而且也没挂钩。
[latest.log](https://github.com/IzzelAliz/Arclight/files/10343707/latest.log)

**Comment by Coloryr** [comment]
2.17.2修了，你升级试试

**Comment by JellyBubb1e** [comment]
> 2.17.2修了，你升级试试

OK了
