### ISSUE TITLE
纯净服务端加载区块时的崩溃问题

### ISSUE THREAD

**Issue by Uni1O1** [IzzelAliz/Arclight#893]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.19.3-1.0.2-SNAPSHOT-516d4917

### Java 版本 | 操作系统

Win10 19044.2364 x64 丨JDK-17.0.5

### 相关 Mod/插件 的名称及版本

```raw
已经排除过，和MOD插件无关
```

### 错误描述

内存尝试过2000MB,3000MB,5000MB,6000MB，Java尝试过JDK17和19，尝试过重置世界和整个服务器
服务器都可以正常启动，在出生点小范围以内可以正常活动没有影响，在离开一段距离（创造模式飞行大约一分钟路程）后区块几乎无法加载，所有玩家立刻掉线，服务器崩溃，或者处于玩家无法进入，控制台完全卡住，只能用任务管理器关闭的状态

### 复现步骤

1.启动服务器
2.进入服务器（一切正常，使用/gc查看内存占用正常
3.向远离出生点的地方移动加载区块
4.崩服

### 报错信息

[crash-2023-01-14_22.10.50-server.txt](https://github.com/IzzelAliz/Arclight/files/10417873/crash-2023-01-14_22.10.50-server.txt)
[crash-2023-01-14_22.17.55-server.txt](https://github.com/IzzelAliz/Arclight/files/10417889/crash-2023-01-14_22.17.55-server.txt)

### 复现用压缩包下载链接(可选)

无

**Comment by Uni1O1** [comment]
测试了三个种子，貌似只有在特地的地形会崩服，初步判断是村民导致的问题

**Comment by Uni1O1** [comment]
又单独测试了村民，在正常区块放下村民以后立刻崩服

**Comment by heipiao233** [comment]
貌似是有人把mixin写错了

**Comment by heipiao233** [comment]
这个类根本没有返回byte的方法，何来`"desc=/B$/"`？
其实只要把B改成Z就好了。
