### ISSUE TITLE
Adventure API

### ISSUE THREAD

**Issue by GeorgeV220** [IzzelAliz/Arclight#895]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1.jar

### OS & Java versions

Java 17 Pterodactyl container ghcr.io/pterodactyl/yolks:java_17

### Plugins and Mods

```raw
SkinOverlay (my own plugin)
```

### Description

Is there a chance to add the adventure api?

### Logs

https://mclo.gs/v4OxiJI#L151

**Comment by IzzelAliz** [comment]
Adventure support is part of the Paper stuff. See #47.
