### ISSUE TITLE
Arclight Mod - Missing

### ISSUE THREAD

**Issue by Edel-Lilies** [IzzelAliz/Arclight#90]
### 我正在运  Version arclight-1.16.4-1.0.9-SNAPSHOT-c050ec7

* **Arclight** [版本] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)] 

* **操作系统** [Windows10 2004]

* **插件列表** 
[箱子登入X]LoginBoxSss 2.9
* **Mod 列表** 
 mods_folder DungeonsMod-1.16.3-1.1.2.jar : dungeonsmod (1.16.3-1.1.2) - 1
• mods_folder astralsorcery-1.16.4-1.13.1.jar : astralsorcery (1.16.4-1.13.1) - 1
• mods_folder NetherPortalFix_1.16.3-7.2.1.jar : netherportalfix (7.2.1) - 1
• mods_folder beenfo-1.16.4-forge35.0.7-1.2.jar : beenfo (1.16.4-forge35.0.7-1.2) - 1
• mods_folder AdditionalBanners-1.16.4-5.0.2.jar : additionalbanners (5.0.2) - 1
• mods_folder mcw-windows-1.0.2-mc1.16.4.jar : mcwwindows (1.0.2) - 1
• mods_folder rsgauges-1.16.4-1.2.6-b1.jar : rsgauges (1.2.6-b1) - 1
• mods_folder BetterCaves-1.16.3-1.0.5.jar : bettercaves (1.16.3-1.0.5) - 1
• mods_folder XaerosWorldMap_1.11.3_Forge_1.16.4.jar : xaeroworldmap (1.11.3) - 1
• mods_folder Controlling-7.0.0.11.jar : controlling (7.0.0.11) - 1
• mods_folder Placebo-1.16.3-4.3.3.jar : placebo (4.3.3) - 1
• mods_folder Bookshelf-1.16.4-9.1.9.jar : bookshelf (9.1.9) - 1
• mods_folder simpleplanes-1.16.3-3.2.0.2.jar : simpleplanes (1.16.3-3.2.0.2) - 1
• mods_folder ProgressiveBosses-2.2.0-mc1.16.x.jar : progressivebosses (2.2.0) - 1
• mods_folder Hwyla-forge-1.10.11-B78_1.16.2.jar : waila (1.10.11-B78_1.16.2) - 1
• mods_folder carryon-1.16.3-1.15.1.7.jar : carryon (1.15.1.7) - 1
• mods_folder JustEnoughResources-1.16.3-0.12.0.100.jar : jeresources (0.12.0.100) - 1
• mods_folder absentbydesign-1.16.3-1.1.1.jar : absentbydesign (1.16.3-1.1.1) - 1
• mods_folder structure-gel-api-1.16.4-1.7.0.jar : structure_gel (1.7.0) - 1
• mods_folder mcw-bridges-1.0.4-mc1.16.4.jar : mcwbridges (1.0.4) - 1
• mods_folder delicateanddainty-0.1.4-1.16.4.jar : delicateanddainty (0.1.4-1.16.4) - 1
• mods_folder repurposed_structures-1.16.4-2.3.0.jar : repurposed_structures (1.16.4-2.3.0) - 1
• mods_folder ToolStats-1.16.4-5.0.1.jar : toolstats (5.0.1) - 1
• mods_folder valhelsia_structures-16.0.5.jar : valhelsia_structures (16.0.5) - 1
• mods_folder dungeons-plus-1.16.4-1.1.0.jar : dungeons_plus (1.1.0) - 1
• mods_folder masonry-1.16.3-0.3.6.jar : masonry (NONE) - 1
• mods_folder simplefarming-1.16.4-1.3.5.jar : simplefarming (1.16.4-1.3.5) - 1
• mods_folder fairylights-4.0.2-1.16.4.jar : fairylights (4.0.2) - 1
• mods_folder curios-forge-1.16.4-4.0.2.1.jar : curios (1.16.4-4.0.2.1) - 1
• mods_folder Botania-1.16.3-409.jar : botania (1.16.3-409) - 1
• mods_folder Patchouli-1.16.2-47.jar : patchouli (1.16.2-47) - 1
• mods_folder collective-1.16.4-1.53.jar : collective (1.53) - 1
• mods_folder extlights-3.1.jar : extlights (3.1) - 1
• mods_folder neoncraft-2.1.jar : neoncraft (2.1) - 1
• mods_folder Runelic-1.16.4-6.0.2.jar : runelic (6.0.2) - 1
• mods_folder furniture-7.0.0-pre19-1.16.3.jar : cfm (7.0.0-pre19) - 1
• mods_folder AI-Improvements-1.16.2-0.3.0.jar : aiimprovements (0.3.0) - 1
• mods_folder observerlib-1.16.4-1.4.3.jar : observerlib (1.16.4-1.4.3) - 1
• mods_folder the_bumblezone-1.16.4-2.2.5.jar : the_bumblezone (1.16.4-2.2.5) - 1
• mods_folder charm-forge-1.16.4-2.1.1-hotfix3.jar : charm (2.1.1) - 1
• mods_folder classicbar-4.0.1-1.16.3.jar : classicbar (4.0.1-1.16.3) - 1
• mods_folder FastLeafDecay-v25.jar : fastleafdecay (v25) - 1
• mods_folder BetterMineshafts-Forge-1.16.3-1.1.jar : bettermineshafts (1.16.3-1.1) - 1
• mods_folder forge-1.16.4-geckolib-3.0.0-beta.10.jar : geckolib3 (3.0.0-beta.10) - 1
• mods_folder DarkPaintings-1.16.4-5.0.2.jar : darkpaintings (5.0.2) - 1
• mods_folder forgeautofish-1.0.6-1.16.4.jar : forgeautofish (1.0.6) - 1
• mods_folder TrashSlot_1.16.3-12.2.1.jar : trashslot (12.2.1) - 1
• mods_folder torchslabmod-1.16.3_v1.6.18.jar : torchslabmod (1.6.18) - 1
• mods_folder mining-helmet-1.16.4-2.0.0.jar : mining_helmet (2.0.0) - 1
• mods_folder CustomSkinLoader_Forge-14.13-SNAPSHOT-199.jar : customskinloader (14.13-SNAPSHOT-199) - 1
• mods_folder giantspawn_1.16.4-2.2.jar : giantspawn (2.2) - 1
• mods_folder jei-1.16.4-7.6.0.58.jar : jei (7.6.0.58) - 1
• mods_folder breedablekr_1.16.4-1.2.jar : breedablekr (1.2) - 1
• mods_folder the-conjurer-1.16.4-1.0.13.jar : conjurer_illager (1.0.13) - 1
• mods_folder justmobheads_1.16.4-3.7.jar : justmobheads (3.7) - 1
• mods_folder goblintraders-1.2.2-1.16.3.jar : goblintraders (1.2.2) - 1
• mods_folder reap-1.16.4-1.0.2.jar : reap (1.16.4-1.0.2) - 1
• mods_folder comforts-forge-1.16.4-4.0.0.2.jar : comforts (1.16.4-4.0.0.2) - 1
• mods_folder NaturesCompass-1.16.3-1.8.5.jar : naturescompass (1.16.3-1.8.5) - 1
• mods_folder framedcompactdrawers-1.16-2.1.2.jar : framedcompactdrawers (1.16-2.1.2) - 1
• mods_folder SkinnedCarts-1.16.2-1.1.1.jar : skinnedcarts (1.1.1) - 1
• mods_folder FarmingForBlockheads_1.16.3-7.2.1.jar : farmingforblockheads (7.2.1) - 1
• mods_folder outvoted-1.16.3-b0.4.1.jar : outvoted (1.16.3-b0.4.1) - 1
• mods_folder bedspreads-forge-1.16.4-5.1.0.1.jar : bedspreads (1.16.4-5.1.0.1) - 1
• mods_folder additional_lights-1.16.4-2.1.3.jar : additional_lights (2.1.3) - 1
• mods_folder mahoutsukai-1.16.4-v1.25.6.jar : mahoutsukai (1.16.4-v1.25.6) - 1
• mods_folder environmentalcreepers-forge-1.16.3-1.6.0.jar : environmentalcreepers (1.6.0) - 1
• maven_libs forge-1.16.4-35.1.4-universal.jar : forge (35.1.4) - 1
• mods_folder Waddles-1.16.4-0.8.11.jar : waddles (1.16.4-0.8.11) - 1
• mods_folder More+Crafting+Tables.Forge.1.16.4.jar : mctb (1.16.4 - 1.0.0 ) - 1
• mods_folder scuba-gear-1.16.4-1.0.1.jar : scuba_gear (1.0.1) - 1
• mods_folder immersiveposts-1.16.3-3.0.0.jar : immersiveposts (3.0.0) - 1
• minecraft forge-1.16.4-35.1.4-server.jar : minecraft (1.16.4) - 1
• mods_folder EnchantmentDescriptions-1.16.4-6.0.2.jar : enchdesc (6.0.2) - 1
• mods_folder swingthroughgrass-1.16.4-1.5.3.jar : swingthroughgrass (1.16.4-1.5.3) - 1
• mods_folder MouseTweaks-2.13-mc1.16.2.jar : mousetweaks (2.13) - 1
• mods_folder modenforcer-1.16.4-1.0.1.jar : modenforcer (1.16.4-1.0.1) - 1
• mods_folder ToolBelt-1.16.3-1.15.2.jar : toolbelt (1.15.2) - 1
• mods_folder ImmersiveEngineering (1.16.4-4.1.1-128) - 1
• mods_folder movingelevators-1.2.27-mc1.16.4.jar : movingelevators (1.2.27) - 1
• mods_folder storage_overhaul-1.16.4-1.0.2.jar : storage_overhaul (1.16.4-1.0.2) - 1
• mods_folder ironfences_1.16.4-1.0.0.jar : ironfences (1.0.0) - 1
• mods_folder astikorcarts-1.16.4-1.1.0.jar : astikorcarts (1.1.0) - 1
• mods_folder car-1.16.4-1.0.5.jar : car (1.16.4-1.0.5) - 1
• mods_folder justplayerheads_1.16.4-1.4.jar : justplayerheads (1.4) - 1
• mods_folder Mantle-1.16.4-1.6.43.jar : mantle (1.6.43) - 1
• mods_folder Inspirations-1.16.3-1.2.1.24.jar : inspirations (1.2.1) - 1
• mods_folder Xaeros_Minimap_20.28.1_Forge_1.16.4.jar : xaerominimap (20.28.1) - 1
• mods_folder pamhc2foodcore-1.16.3-1.0.0.jar : pamhc2foodcore (version) - 1
• mods_folder FastWorkbench-1.16.3-4.4.1.jar : fastbench (4.4.1) - 1
• mods_folder polymorph-forge-1.16.3-0.16.jar : polymorph (1.16.3-0.16) - 1
• mods_folder AutoRegLib-1.6-46.jar : autoreglib (1.6-46) - 1
• mods_folder Quark-r2.4-276.jar : quark (r2.4-276) - 1
• mods_folder Apotheosis-1.16.3-4.4.1.jar : apotheosis (4.4.1) - 1
• mods_folder StorageDrawers-1.16.3-8.2.1.jar : storagedrawers (8.2.1) - 1
• mods_folder sit-1.16.2-v1.3.jar : sit (v1.3) - 1
• mods_folder earthmobsmod-1.16.4-0.1.2-Beta.jar : earthmobsmod (1.16.4-0.1.2-Beta) - 1
• mods_folder JustEnoughCharacters-1.16.3-4.1.2.jar : jecharacters (4.1.2) - 1
• mods_folder backpacked-1.7.0-1.16.3.jar : backpacked (1.7.0) - 1
• mods_folder backpacker-1.1.0-1.16.3.jar : backpacker (1.1.0) - 1
• mods_folder lanterncolors-1.16.3-2.1.1.jar : lanterncolors (1.16.2-2.1.1) - 1
• mods_folder hunterillager-1.16.4-1.1.4.jar : hunterillager (1.16.4-1.1.4) - 1
• mods_folder moredragoneggs-1.4.jar : moredragoneggs (1.4) - 1
• mods_folder durabilityviewer-1.16.4-forge35.0.7-1.9.jar : durabilityviewer (1.16.4-forge35.0.7-1.9) - 1
• arclight arclight-forge-1.16-1.0.9-SNAPSHOT.jar : arclight (1.16.4-1.0.9-SNAPSHOT-c050ec7) - 1
• mods_folder smallernp_1.16.4-1.4.jar : smallernp (1.4) - 1
• mods_folder byg-1.1.5.jar : byg (1.1.5) - 1
• mods_folder Aquaculture-1.16.4-2.1.6.jar : aquaculture (1.16.4-2.1.6) - 1
• mods_folder CosmeticArmorReworked-1.16.4-v1.jar : cosmeticarmorreworked (1.16.4-v1) - 1
• mods_folder EnderMail-1.16.3-1.1.5.jar : endermail (1.16.3-1.1.5) - 1

### 错误描述
連接服務器,提示Arclight Mod - Missing

叙述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息

### 重现步骤

1. 安装 以上
2. 連接服务器
3. 提示Arclight Mod - Missing

**可在 Forge 复现** [否]

**可在 Spigot 复现** [否]

### 报错信息

[错误日志]

**Comment by Edel-Lilies** [comment]
[latest.log](https://github.com/IzzelAliz/Arclight/files/5610073/latest.log)

**Comment by IzzelAliz** [comment]
无法复现，请确认空端能否复现，如果不能，请二分找出可复现的模组

**Comment by Edel-Lilies** [comment]
空端和少量mod下不會出現此問題,我正在測試mod

**Comment by Edel-Lilies** [comment]
新版本不會出現此問題
