### ISSUE TITLE
Crash on hit specific mobs of Alex's Mobs

### ISSUE THREAD

**Issue by Caapri** [IzzelAliz/Arclight#905]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1

### OS & Java versions

openjdk 17.0.5 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Plugins and Mods

```raw
Plugins: None
Mods:
- alexsmobs-1.21.1
- citadel-2.1.1-1.19 (Alex'x Mobs dependency)
```

### Description

In the server, when i hit some mobs of Alex's Mobs like Cachalot or Giant Squid the server kicks me out and i receive the following error in the server console and the client:

```
[Netty Server IO #2/WARN] [Implementer/ASYNC_CATCHER]: Async chunk entity get
[Netty Server IO #2/WARN] [Implementer/ASYNC_CATCHER]: Async chunk entity get
[Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: <user> lost connection: Internal Exception: java.lang.IllegalStateException: EntityDamageEvent cannot be triggered asynchronously from another thread.
[Server thread/INFO] [minecraft/MinecraftServer]: <user> left the game
```

I don't know if there are more mobs of this mod where this error happens, i only tested with these both, maybe there are more affected. As other idea, these mobs has a lot of life, i don't know if it's related.

I confirmed that it's happening because of Arclight. Without arclight this error doesn't happen.

### Step to reproduce

1. Install Alex's Mobs mod with Citadel as dependency (latest version of both).
2. With the client, enter to the Arclight Server.
3. Hit cachalot or giant squid of Alex's Mobs (maybe there are more affected?).
4. The server get you out with the error described above.

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/10509464/latest.log)

**Comment by IzzelAliz** [comment]
Please provide your debug.log.

**Comment by Caapri** [comment]
Hello @IzzelAliz,

Here is the debug.log with the error:
[debug.log](https://github.com/IzzelAliz/Arclight/files/10528726/debug.log)

**Comment by Jaeyong1114** [comment]
I'm having the same problem, did you solve it?

**Comment by Jaeyong1114** [comment]
I'm having the same problem, did you solve it?

**Comment by ProjectSky** [comment]
ver 1.19.3 has same issues

**Comment by IzzelAliz** [comment]
This should be reported to alex mob developer with these information:

The `MessageHurtMultipart` packet is handled on netty thread.
