### ISSUE TITLE
[1.16.5]Apotheosis神话mod Boss生成(?)异常

### ISSUE THREAD

**Issue by Maklith** [IzzelAliz/Arclight#906]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.16.5-1.0.24

### Java 版本 | 操作系统

系统 windows server 2022 ,Java java 11.0.9 2020-10-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

### 相关 Mod/插件 的名称及版本

```raw
Apotheosis-1.16.5-4.8.9A0
```

### 错误描述

Description: Ticking block entity
java.lang.NullPointerException: Ticking block entity
shadows.apotheosis.deadly.objects.BossSpawnerBlock
{apotheosis:boss_spawner}此方块异常

### 复现步骤

1. 启动服务器加载地图后就报错

### 报错信息

[crash-2023-01-27_21.34.26-server.txt](https://github.com/IzzelAliz/Arclight/files/10519562/crash-2023-01-27_21.34.26-server.txt)

### 复现用压缩包下载链接(可选)

https://1drv.ms/u/s!AlMLwZtbDX-D4UaFEDQeHD6zqrDh?e=Uq0FEl

**Comment by IzzelAliz** [comment]
你可以试试把 roadrunner 去掉

**Comment by Maklith** [comment]
> 你可以试试把 roadrunner 去掉

去掉后正常,还有一个问题NATURESAURA_FIELD_CREATOR破坏的方块没有掉落物https://www.mcmod.cn/item/161888.html
 已确认这个问题与插件无关,我需要重新开一个issues吗

**Comment by Maklith** [comment]
#912
