### ISSUE TITLE
[1.16.5] worldIn.getGameRules().getBoolean(GameRules.DO_TILE_DROPS),永远为false

### ISSUE THREAD

**Issue by Maklith** [IzzelAliz/Arclight#912]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.16.5-1.0.24

### Java 版本 | 操作系统

Windows server 2022 Java 11.0.9 2020-10-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

### 相关 Mod/插件 的名称及版本

```raw
NaturesAura-34.3自然灵气
```

### 错误描述

Block.spawnAsEntity(this.world, pos, stack);方法是无效的(版本1.16.5)
导致自然灵气立场生成器破坏方块无掉落物,具体代码位置见下图,已确认pos, stack变量与预期值相符(this.world未测试)
自然灵气开源地址https://github.com/Ellpeck/NaturesAura
![image](https://user-images.githubusercontent.com/42534870/215326410-b04aebf0-0769-4e00-b3be-9697a9b46793.png)

### 复现步骤

灵气立场生成器在Arclight端中与预期行为不符即无掉落物生成

### 报错信息

无

**Comment by Maklith** [comment]
已确认问题worldIn.getGameRules().getBoolean(GameRules.DO_TILE_DROPS),GameRules.
GameRules.DO_TILE_DROPS规则设置无效,即使为ture,通过方法worldIn.getGameRules().getBoolean(GameRules.DO_TILE_DROPS),永远为false.

**Comment by IzzelAliz** [comment]
那么，你这个 world 是主世界吗

**Comment by Maklith** [comment]
> 那么，你这个 world 是主世界吗

肯定是主世界,但是这个世界规则和哪个世界并没有关系

**Comment by Maklith** [comment]
原本的方法受GameRules.DO_TILE_DROPS限制,
![image](https://user-images.githubusercontent.com/42534870/216255806-5328701a-bdfd-4624-a3bc-2aae4d0422ad.png)
去掉这个就正常了
![image](https://user-images.githubusercontent.com/42534870/216255899-de1b69c1-49b4-4806-92a2-752bee43640d.png)

**Comment by sandtechnology** [comment]
我觉得你应该自己检查一下gamerule是不是正常的 这里调用的方法和forge有关系 但是和arclight无关
