### ISSUE TITLE
Update Jar Java to 17

### ISSUE THREAD

**Issue by Ryozo1** [IzzelAliz/Arclight#913]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.16.5

### OS & Java versions

8

### Plugins and Mods

```raw
They are many mods and plugins
```

### Description

My server dont work and when I contante with costumer service they told me this
It appears that Arclight requires a newer version of Java. Please try using Custom Jar Java 17 instead of a regular Custom Jar.

How can I fix this problem? 🌹

**Comment by HIX4123** [comment]
Just try to install Java 17. I bet your MC Version is 1.18 or more.

https://www.oracle.com/java/technologies/downloads/#java17

**Comment by Ryozo1** [comment]
How can I update Java on my server?

**Comment by IzzelAliz** [comment]
1.16 do support Java 8.
