### ISSUE TITLE
Server Crash? Can't Install Arclight Libraries!

### ISSUE THREAD

**Issue by HIX4123** [IzzelAliz/Arclight#915]
### I have confirmed that ...

- [x] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.1-0550c6cd

### OS & Java versions

OS: Oracle-Linux-9.0-aarch64-2022.12.16-0, Java: java version "17.0.5" 2022-10-18

### Plugins and Mods

```raw
Nothing!!
```

### Description

When I installed the arclight-forge-1.19.2-1.0.1.jar file and made the first run to install the libraries, it was interrupted while installing the library with the following error message:

input
`$ java -Xmx6G -Xms6G -jar arclight-forge-1.19.2-1.0.1.jar`

output

> Downloading missing libraries ...
> java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.19.2-43.2.0/forge-1.19.2-43.2.0-installer.jar
> java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.19.2-43.2.0/forge-1.19.2-43.2.0-installer.jar
>         at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:50)
>         at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:25)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
>         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Fail to launch Arclight.

In first time I thought It was my fault, because in my guess my setting of Oracle VM was wrong. But I found it didn't work in my local machine, which has worked before about one week.

I think it has a problem in Arclight file-passing server because what I had installed in last week still works well. or maybe in Forge server. I'll try to copy forge-1.19.2-43.2.0-installer.jar from my existing server to new one, and say how it would be gone.

### Step to reproduce

1. Install jar file(Horn/1.0.1, Dec 9, 2022) in https://github.com/IzzelAliz/Arclight/releases.

2.  `java -Xmx6G -Xms6G -jar arclight-forge-1.19.2-1.0.1.jar`

3. BAMMMMM

### Logs

No Log Files. This is initiating problem.

**Comment by HIX4123** [comment]
And new problem!

Error message after installing forge.jar manually (I used sudo this time, not before)

> Downloading missing libraries ...
> Downloaded forge-1.19.2-43.2.0-installer.jar
> java.lang.RuntimeException: Failed net.minecraft:server:1.19.2-20220805.130853:mappings@txt
>   (1) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/mappings_server.1.19.2.txt
>   (2) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/mappings_server.1.19.2.txt
>   (3) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/1.19.2-20220805.130853/server-1.19.2-20220805.130853-mappings.txt
> java.lang.RuntimeException: Failed net.minecraft:server:1.19.2-20220805.130853:mappings@txt
>   (1) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/mappings_server.1.19.2.txt
>   (2) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/mappings_server.1.19.2.txt
>   (3) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/1.19.2-20220805.130853/server-1.19.2-20220805.130853-mappings.txt
> java.lang.RuntimeException: Failed net.minecraft:server:1.19.2-20220805.130853:mappings@txt
>   (1) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/mappings_server.1.19.2.txt
>   (2) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/mappings_server.1.19.2.txt
>   (3) java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraft/server/1.19.2-20220805.130853/server-1.19.2-20220805.130853-mappings.txt
>         at io.izzel.arclight.forgeinstaller.MavenDownloader.get(MavenDownloader.java:57)
>         at io.izzel.arclight.forgeinstaller.MavenDownloader.get(MavenDownloader.java:11)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
>         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Fail to launch Arclight.

Maybe this is completely problem of https://arclight.mcxk.net.

**Comment by trevorgolden** [comment]
I am having the same issue, have you had any luck?

**Comment by HIX4123** [comment]
Not yet, I think I can use Arclight if I copy all the libraries from my local machine having already downloaded them, but not trying.

I'm freshman to Oracle cloud, VM, and Linux, so I don't know even uploading my local file to onlineVM.:)
And maybe it must contains other server's data.

I think it deserves to label 'Fatal'.

**Comment by HIX4123** [comment]
Closed in mistake

**Comment by 0Lynk** [comment]
我有同样的问题。

**Comment by IzzelAliz** [comment]
CDN is down, just wait.

**Comment by IzzelAliz** [comment]
Server is up now.

**Comment by HIX4123** [comment]
Um, I think not yet.
Same way, same fail

**Comment by HIX4123** [comment]
Same problem yet! I think this thread has to be reopened
