### ISSUE TITLE
My server is currently crashing

### ISSUE THREAD

**Issue by Ryozo1** [IzzelAliz/Arclight#916]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.16.5

### OS & Java versions

I Dont known 

### Plugins and Mods

```raw
No mod
```

### Description

My server is currently crashing on startup as it is attempting to download files from a server owned by Arclight, however this server cannot be reached.

**Comment by HIX4123** [comment]
Owner says server was reopened some hours ago but I still have same problem too
