### ISSUE TITLE
Pixelmon server crashing when battle starts

### ISSUE THREAD

**Issue by UnknownVariables-here** [IzzelAliz/Arclight#918]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.24-551ec3ff

### OS & Java versions

OS: Windows 10 x64 Java: IBM Semeru(OpenJ9) 17

### Plugins and Mods

```raw
Plugins (0):
Mod List:
• minecraft forge-1.16.5-36.2.39-server.jar : minecraft (1.16.5) - 1
• maven_libs forge-1.16.5-36.2.39-universal.jar : forge (36.2.39) - 1
• mods_folder Pixelmon-1.16.5-9.1.2-universal.jar : pixelmon (9.1.2) - 4
• arclight arclight-forge-1.16.5-1.0.24.jar : arclight (1.16.5-1.0.24-551ec3ff) - 1
```

### Description

Hi, So I've been trying to setup a Arclight 1.16.5 server with Pixelmon Reforged 9.1.2 (Latest version) I used the most recent 1.16.5 Arclight release I could find on the github and I'm using the recommended java and I've set the server to use 6GB of RAM, the server launches well but when I join the server and a battle occurs the server crashes. Attached is the crashlog 

### Step to reproduce

1 Setup Arclight server
2 Add Pixelmon
3 Join the server
4 Start a battle

### Logs

[crash-2023-01-31_19.25.39-server.txt](https://github.com/IzzelAliz/Arclight/files/10552163/crash-2023-01-31_19.25.39-server.txt)

**Comment by IzzelAliz** [comment]
This is likely to be a pixelmon error. Report to their devs.
