### ISSUE TITLE
Library download error

### ISSUE THREAD

**Issue by HIX4123** [IzzelAliz/Arclight#919]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.1-0550c6cd

### OS & Java versions

OS : Oracle-Linux-9.0-aarch64-2022.12.16-0   Java : java version "17.0.5" 2022-10-18 LTS

### Plugins and Mods

```raw
nothing
```

### Description

> Downloading missing libraries ...
> java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.19.2-43.2.0/forge-1.19.2-43.2.0-installer.jar
> java.lang.RuntimeException: Timeout https://arclight.mcxk.net/net/minecraftforge/forge/1.19.2-43.2.0/forge-1.19.2-43.2.0-installer.jar
>         at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:50)
>         at io.izzel.arclight.forgeinstaller.FileDownloader.get(FileDownloader.java:25)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
>         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
>         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
>         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
>         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
>         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Fail to launch Arclight.

Unlike yesterday(https://github.com/IzzelAliz/Arclight/issues/915), now my local machine works.

### Step to reproduce

1. Make Oracle VM instance (Location:south KR north Chuncheon <-- I think this is ths cause)

2. I used PUTTY, anyway connect VM console anyway.

3. $wget https://github.com/IzzelAliz/Arclight/releases/download/horn%2F1.0.1/arclight-forge-1.19.2-1.0.1.jar

4. $java -Xmx6G -Xms6G -jar arclight-forge-1.19.2-1.0.1.jar nogui

### Logs

No log file

**Comment by ElRicki** [comment]
same here

**Comment by ElRicki** [comment]
I have the same problem

**Comment by ElRicki** [comment]
@IzzelAliz

**Comment by HIX4123** [comment]
Can somebody having proxy use it in VM to test if it works?
