### ISSUE TITLE
[1.16.5]严重报错，进服无限通讯加密

### ISSUE THREAD

**Issue by QianMo0721** [IzzelAliz/Arclight#920]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.24-551ec3ff

### Java 版本 | 操作系统

openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)
### 相关 Mod/插件 的名称及版本

```raw
插件
AFKPlus, AFKPlusPrefix, AdvancedBan, AdvancedNMotd, BlockLocker, CheatTerminatorX, Chunky, Citizens, ClearEntity, CoreProtect, DieMessage, Economy, FlyWithFood, GSit, Hat, HolographicDisplays, IllegalStack, Images, Ip2region, JoinMessagePlus, LiteSignIn, LiteTeleport, LuckPerms, NewPlayer, OmiVanish, OpenInv, PlaceholderAPI, PlayerParticles, PlayerPoints, PlayerTitle, PluginReloader, ProtocolLib, PvPToggle, QuickShop, ServerUtils, TAB, UltimateAntiBot, Vault, WorldEdit, WorldGuard, WorldGuardGUI, XiaoMingMinecraft and ZMusic
模组
• minecraft forge-1.16.5-36.2.39-server.jar : minecraft (1.16.5) - 1
• mods_folder [匠魂] TConstruct-1.16.5-3.3.4.335.jar : tconstruct (3.3.4.335) - 1
• mods_folder [Cracker的凋灵风暴] witherstormmod-1.16.5-1.0.2.4.jar : witherstormmod (1.0.2.4) - 1
• mods_folder obfuscate-0.6.3-1.16.5.jar : obfuscate (0.6.3) - 1
• mods_folder car-1.16.5-1.0.17.jar : car (1.16.5-1.0.17) - 1
• maven_libs forge-1.16.5-36.2.39-universal.jar : forge (36.2.39) - 1
• mods_folder tac-r-0.2.1.1-1.16.5.jar : tac (0.2.0) - 1
• mods_folder [暮色森林] twilightforest-1.16.5-4.0.870-universal.jar : twilightforest (NONE) - 1
• mods_folder [帕秋莉手册] Patchouli-1.16.4-53.3.jar : patchouli (1.16.4-53.3) - 1
• mods_folder [地幔] Mantle-1.16.5-1.6.157.jar : mantle (1.6.157) - 1
• arclight MuseMC.jar : arclight (1.16.5-1.0.24-551ec3ff) - 1
```

### 错误描述

客户端进入服务器就无限通讯加密，客户端日志倒没有报错，服务器那里报了一个严重错误，使用的是外置登录，前几天还好好的
我怀疑是Mojang的服务器出了问题或把我的IP屏蔽了，我觉得不大可能莫名其妙突然有一天进不去了
![image](https://user-images.githubusercontent.com/98728586/216517474-d6d6a8ab-cca6-4e54-af13-a72cd9f30250.png)

### 复现步骤

1.服务器突然关闭
2.再次进入服务器时无限通讯加密卡这不动

### 报错信息

客户端日志
[latest.log](https://github.com/IzzelAliz/Arclight/files/10575731/latest.log)
服务器日志
[latest.log](https://github.com/IzzelAliz/Arclight/files/10575735/latest.log)

**Comment by IzzelAliz** [comment]
这个显然不是我的问题，你应该看下你的外置登录或者你的网
