### ISSUE TITLE
Launch issue with Arclight 1.18.2 1.0.8

### ISSUE THREAD

**Issue by trevorgolden** [IzzelAliz/Arclight#924]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.8

### OS & Java versions

Ubuntu 20.04 LTS Server

### Plugins and Mods

```raw
Unable to get a list of mods via console, mods can be found at https://www.technicpack.net/modpack/blastgaming.1955882/mods
```

### Description

server begins to launch, following which it says "Fail to launch arclight"

### Step to reproduce

Install Arclight 1.18.2 1.0.8

don't profit :(

### Logs

https://haste.blastgamingmc.com/lekevujoqo.md

**Comment by IzzelAliz** [comment]
```
[net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: forge, forge, forge, forge
```

You should get your forge upgraded.
