### ISSUE TITLE
[1.18] Create: Slice and Dice crash upon load

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#929]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.18.2-1.0.9-SNAPSHOT-e0b6dda

### OS & Java versions

java version "17.0.1" 2021-10-19 LTS Windows 11

### Plugins and Mods

```raw
- Create 0.5.0i
- Farmer's Delight 1.2
- Create Slice & Dice 1.1.0
```

### Description

crash upon starting the server

### Step to reproduce

1. install all mods
2. try to start the server

### Logs

https://pastebin.com/dB1WwzgM

**Comment by heipiao233** [comment]
Not installed Kotlin For Forge?

**Comment by muriplz** [comment]
Yes sorry! I realized this mistake but I also tried with it without luck! I 'll make sure again though

**Comment by muriplz** [comment]
Confirmed it was an issue on my side! sorry!
