### ISSUE TITLE
Server Crash caused by villager trading

### ISSUE THREAD

**Issue by Subtrahxnd** [IzzelAliz/Arclight#930]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9

### OS & Java versions

Java 11.0.13

### Plugins and Mods

```raw
Pixelmon-Reforged 9.1.2
```

### Description

Sometimes when a player trades with a villager for emeralds, the server crashes.

### Logs

https://pastebin.com/zuBP8J3z

**Comment by IzzelAliz** [comment]
I can't reproduce this.

**Comment by IzzelAliz** [comment]
If you can try to reproduce this with Java 14 or higher it will give a somewhat more helpful error message.

**Comment by Subtrahxnd** [comment]
I can`t unfortunately, as Pixelmon is not compatible with java 14. Sorry if I can do anything else let me know.
