### ISSUE TITLE
Plugins issue

### ISSUE THREAD

**Issue by Laminatik** [IzzelAliz/Arclight#931]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

GreatHorn/1.0.2

### OS & Java versions

Java 17.0.6, Ubuntu 20

### Plugins and Mods

```raw
Plugins:
Coreprotect
```

### Description

Coreprotect doesn't log who set fire
Paper example:
![image](https://user-images.githubusercontent.com/59961520/220689783-4709076b-a15c-483b-b202-b2d35f3d5d22.png)
when I use Arclight it doesn't log the player
![image](https://user-images.githubusercontent.com/59961520/220690338-ce7b7347-ede0-411d-9400-6b61373c7929.png)

### Step to reproduce

Install plugin Coreprotect
Start server

**Comment by IzzelAliz** [comment]
How do you set fire?

**Comment by Laminatik** [comment]
by Flint and Steel
