### ISSUE TITLE
1.16.5猫端宝可梦插件在螺端上无法使用

### ISSUE THREAD

**Issue by Baikele** [IzzelAliz/Arclight#933]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

1.0.24

### Java 版本 | 操作系统

Winserver2016,java: 11.0.15.1

### 相关 Mod/插件 的名称及版本

```raw
无法处理forgeeventv2
```

### 错误描述

无法处理forgeeventv2

### 复现步骤

安装一个猫端的宝可梦插件

**Comment by IzzelAliz** [comment]
？？？？？干我屁事

**Comment by Baikele** [comment]
> ？？？？？干我屁事

我是想吧猫端的插件移植到螺端上啊，
