### ISSUE TITLE
[不兼容]加載Model-Engine插件後,攻擊新Model生物伺服器會斷線

### ISSUE THREAD

**Issue by y511634a** [IzzelAliz/Arclight#935]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.3-1.0.3-SNAPSHOT

### Java 版本 | 操作系统

java version "17.0.6" 2023-01-17 LTS

### 相关 Mod/插件 的名称及版本

```raw
Model-Engine-R3.1.5.jar
MythicMobs-5.2.1.jar
```

### 错误描述

加載Model後攻擊新Model生物會斷線
(己測試Spigot1.19.3.jar不會斷線)
(所以肯定是Arelight不兼容)

### 复现步骤

加載Model後攻擊新Model生物會斷線
(己測試Spigot1.19.3.jar不會斷線)
(所以肯定是Arelight不兼容)

**Comment by IzzelAliz** [comment]
1.19.4 已修复
