### ISSUE TITLE
1.19世界种子固定的相关问题。

### ISSUE THREAD

**Issue by PengLx** [IzzelAliz/Arclight#938]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-forge-1.19.3-1.0.2

### Java 版本 | 操作系统

Windows openjdk 17.0.1

### 相关 Mod/插件 的名称及版本

```raw
None
此Bug为 Arclight 未实现特定的Spigot Patch引起
```

### 错误描述

在我的世界1.19的版本更新中，世界种子被固定在存档文件中，无论是在fabric forge 还是原版内容。所有世界的种子均为存档种子，即使利用 Mod 创建更多维度 其种子也是同样的。这导致了在fabric forge arclight 服务器下 所有新创建的世界几乎使用同一个雕刻函数。（因为种子一致）。也就是说世界的生成几乎是一模一样的。在Spigot下，有Patch修复了改问题。
希望能修复该问题，恢复新建世界随机性。

如在Arclight下 mv create worldname normal -s 随便
使生成的世界与主世界完全一致。
在Spigot下无此问题。

补充：
实际测试在1.18的arclight中 使用seed指令查到的种子是不一致的，但是利用mv生成的世界其随机性具备，查询mv 的worlds文件含有其自己的种子。

在1.19的 arclight中 生成世界不再具备随机性。且mv 的 worlds文件下 种子都与主世界相同了

（该问题应该是在1.19 mojang 的更新中引入的， 此前未研究过mod服的世界生成机制。不过看相关评述， 在此之前似乎并没有此问题）

### 复现步骤

不重要了

### 报错信息

无

**Comment by PengLx** [comment]
补充说明，Arclight 在1.19中使用import 即 导入世界时， 由于被导入的世界含有level.dat文件 其种子工作正常。
那么问题应该是在Bukkit中 创建世界的方法 无法正确的将种子文件写入新世界的level.dat文件。导致世界种子全部相同。

**Comment by RaymondChang1204** [comment]
你用的mv是啥版本

**Comment by PengLx** [comment]
> 你用的mv是啥版本

Spigot上的最新版。不仅是MV 我自己插件利用Bukkit的WorldCreator也无法实现种子的问题。
