### ISSUE TITLE
怎么让依赖Arclight的插件监听Forge事件？

### ISSUE THREAD

**Issue by YuaZer** [IzzelAliz/Arclight#942]
Arclight有为bukkit提供一个监听Forge事件的方法吗？我想让插件监听Forge的事件，比如宝可梦模组的事件

**Comment by heipiao233** [comment]
api/Arclight.java at master ・ ArclightPowered/api ・ GitHub<https://github.com/ArclightPowered/api/blob/master/src/main/java/io/izzel/arclight/api/Arclight.java#L23>
