### ISSUE TITLE
1.19.2 BUG IC2 CLassic + Essentials/CMI/CMI Lib

### ISSUE THREAD

**Issue by MrJorman** [IzzelAliz/Arclight#944]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.1-0550c6cd

### OS & Java versions

Windows 10, Java 17 (BellSoft)

### Plugins and Mods

```raw
Plugins: CMI Lib or Essentials X
Mods: IC2 Classic
```

### Description

1. ic2:mininglaser does not work properly, after breaking blocks they do not drop out.
2. Nano and Quantum Armor are ignored and can even be pierced by a wooden sword, and this bug appears when I add the CMI Lib or Essentials plugin. I turned off all the functions there, but nothing helped. Need a fix.

### Logs

no logs.

**Comment by MrJorman** [comment]
IC2 Classic: https://www.curseforge.com/minecraft/mc-mods/ic2-classic?sort=releasetype
CMI: 
CMI Lib: https://www.spigotmc.org/resources/cmilib.87610/

**Comment by MrJorman** [comment]
Please fixxx ))

**Comment by MrJorman** [comment]
**I will also add that /effect glowing does not work completely on servers, and also the /vanish command does not hide the player.**

**Comment by Sa1ZeR** [comment]
+1 Nano and quantum armor are ignored, how fix it?

**Comment by MrJorman** [comment]
no fixed.
