### ISSUE TITLE
Unable to build Project

### ISSUE THREAD

**Issue by burdoto** [IzzelAliz/Arclight#951]
Hi,
When trying to build the GreatHorn branch (and with the 1.19 branch too) in IntelliJ, I cannot get beyond two problems;
`java.lang.IllegalStateException: Cannot mutate content repository descriptor 'BUNDELED_608894262(file:/C:/Users/burdo/.gradle/caches/forge_gradle/bundled_deobf_repo)' after repository has been used`
and
`groovy.lang.MissingPropertyException: Could not get unknown property 'reobfJar' for task`

The build always fails with two causes, and I can't seem to find out the problem. Running `gradlew remapSpigotJar` as described [here](https://github.com/IzzelAliz/Arclight/wiki/Contributing#for-developers) yields the same results.
Looking at the configuration for the `arclight-common` module yielded no help either.

[This is the output stacktrace](https://paste.kescher.at/?eba26020c5b459cc#FtS4oMdTaDRUFeJSV7iLzP59vB34R2ktjitVZVntstpe) of importing the project to IntelliJ.
I had to use a paste service because its too long.

**Comment by basaigh** [comment]
I have the same issue.

**Comment by brunyman** [comment]
Yes, same, but looks like it affects all versions

**Comment by brunyman** [comment]
Any fix for this issue?

**Comment by IzzelAliz** [comment]
This is fixed.
