### ISSUE TITLE
Quest Additons Incompatability 1.19.2

### ISSUE THREAD

**Issue by Talan67** [IzzelAliz/Arclight#952]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1

### OS & Java versions

java version "17.0.1" 2021-10-19 LTS

### Plugins and Mods

```raw
architectury-6.5.69-forge
ftb-library-forge-1902.3.15-build.188
ftb-quests-forge-1902.4.9-build.195
ftb-teams-forge-1902.2.12-build.95
item-filters-forge-1902.2.9-build.46
questsadditions-1.19.2-1.4.0
```

### Description

Quest additons causes a crash on Arclight. I looked through old issues on the github and a similar issue happened with 1.18.2 on Arclight and the same mod. I suspect it might be the same issue, where there is a mixin conflict.

### Step to reproduce

1. Install FTB mods and Quest Additons

2. Launch Arclight Server

3. Crash

4. Surprised Pikachu face

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/11069823/latest.log)

**Comment by IzzelAliz** [comment]
1.19.2 is no longer supported. This is fixed in 1.19.3.
