### ISSUE TITLE
Essential x

### ISSUE THREAD

**Issue by Wartax** [IzzelAliz/Arclight#953]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1.jar

### OS & Java versions

java 17

### Plugins and Mods

```raw
Plugins :
-essentialx

mods: 
-cobblemon
-achitectury
```

### Description

essentialx remove command on my mods it's not caused my mods. Do u have an issue ?

### Step to reproduce

1. install essential x
2. run my server
3. connect 
4. type command of my mod
5. no reponse of the command
6. restart and remove essential
7. the command is good

### Logs

i d'ont have logs

**Comment by Wartax** [comment]
Thanks

**Comment by IzzelAliz** [comment]
You did a very good job on describing your problem that nearly no useful information was provided.

What is your command? If it's a naming conflict, your can use "forge:your_command" for mod commands.
