### ISSUE TITLE
ServerHangWatchdog crash mization.json:activationrange.EntityMixin_ActivationRange

### ISSUE THREAD

**Issue by poqdavid** [IzzelAliz/Arclight#954]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb

### OS & Java versions

OS: Ubuntu 22.04.2 LTS x64 Java: OpenJDK 64-Bit Temurin-11.0.16.1+1

### Plugins and Mods

```raw
Plugins (33): LuckPerms, SurvivalInvisiframes, PlaceholderAPI, spark, WorldBorder, DeluxeMentions, HolographicDisplays, Anvil, VoxelSniper, Battlelog, RandomTeleport, BoostingElytra, UltraEconomy, Chunky, Vault, WorldEdit, Essentials, EverNifeCore, CommandCost, GriefDefender, HeadDatabase, PixelmonEconomyBridge, DiscordSRV, EssentialsChat, DeluxeMenus, TAB, DiscordSRV-Staff-Chat, EssentialsSpawn, CoreProtect, GCore, VotingPlugin, Plan, CustomCommands

Mod List: 
• minecraft forge-1.16.5-36.2.39-server.jar : minecraft (1.16.5) - 1
• mods_folder LypakaUtils-1.16.5-0.0.6-Java8.jar : lypakautils (1.16.5-0.0.6) - 1
• mods_folder EnvySTS-Forge-2.0.1-1.16.5.jar : envysts (2.0.1) - 1
• mods_folder GooeyLibs-2-1165.jar : gooeylibs2 (2.3.2) - 1
• mods_folder simplygts-1.1.4.jar : simplygts (1.1.4) - 1
• mods_folder BlueMap-3.12-forge-1.16.5.jar : bluemap (3.12) - 1
• mods_folder lastlegend-1.0.jar : lastlegend (1.0) - 1
• mods_folder jei-1.16.5-7.7.1.152.jar : jei (7.7.1.152) - 1
• mods_folder EnvySpecs-Forge-1.0.1-1.16.5.jar : envyspecs (1.0.1) - 1
• mods_folder PixelmonOverlay-Forge-1.0.1-1.16.5.jar : pixelmonoverlay (1.0.1) - 1
• mods_folder showpokemon-1.0.2.jar : showpokemon (1.0.2) - 1
• mods_folder PokeRemoval-Forge-2.0.3-1.16.5.jar : pokeremoval (2.0.3) - 1
• mods_folder BetterPokeBroadcaster-Forge-1.1.6-1.16.5.jar : betterpokebroadcaster (1.1.6) - 1
• mods_folder journeymap-1.16.5-5.8.5p6.jar : journeymap (5.8.5p6) - 1
• mods_folder DaycareExtras-1.0.jar : daycareextras (1.0) - 1
• mods_folder Atlantis-1.16.5-6.2.0-all.jar : atlantis (6.2.0) - 1
• mods_folder ForgePlaceholderAPI-Forge-2.0.4-1.16.5.jar : forgeplaceholderapi (2.0.4) - 1
• mods_folder BetterBreeding-1.0.5.jar : betterbreeding (1.0.5) - 1
• mods_folder UltimaQuests-1.3.6_1.jar : ultimaquests (NONE) - 1
• mods_folder releasehistory-1.0.jar : releasehistory (1.0) - 1
• mods_folder BetterCommandItems-1.16.5-1.1.0.jar : bettercommanditems (1.16.5-1.1.0) - 1
• mods_folder Pikaboo-1.16.5-1.1.0.jar : pikaboo (NONE) - 1
• mods_folder moveskillpermissions-1.0.jar : moveskillpermissions (1.0) - 1
• arclight arclight-forge-1.16.5-1.0.25-SNAPSHOT.jar : arclight (1.16.5-1.0.24-SNAPSHOT-8d0dfe40) - 1
• mods_folder WonderTrade-Forge-6.3.1-1.16.5.jar : wondertrade (6.3.1) - 1
• mods_folder cable-libs-1.3.1.jar : cablelibs (NONE) - 1
• maven_libs forge-1.16.5-36.2.39-universal.jar : forge (36.2.39) - 1
• mods_folder pixelfix-1.0.5.jar : pixelfix (1.0.5) - 1
• mods_folder pixelmonaura-1.0.2.jar : pixelmonaura (1.0.2) - 1
• mods_folder shopkeeperlogger-1.0.jar : shopkeeperlogger (1.0) - 1
• mods_folder UltimaPixelmon-1.1.4.jar : ultimapixelmon (NONE) - 1
• mods_folder evivcommand-1.0.jar : evivcommand (1.0) - 1
• mods_folder TrainerCommands-1.16.5-2.6.0.jar : trainercommands (1.16.5-2.6.0) - 1
• mods_folder Pixelmon-1.16.5-9.1.3-server.jar : pixelmon (9.1.3) - 4
• mods_folder byg-1.3.6.jar : byg (1.3.4) - 1
• mods_folder AquaGyms-1.16.5-3.3.6-universal.jar : aquagyms (3.3.6) - 1
```

### Description

TPS shouldn't take 3min after there are 30+ players on the server for a while

### Step to reproduce

Well there isn't a step really just a normal Pixelmon sever with 30+ players
And then server just hangs and crashes

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/11080873/latest.log)
[crash-2023-03-26_19.59.57-server.txt](https://github.com/IzzelAliz/Arclight/files/11080879/crash-2023-03-26_19.59.57-server.txt)

**Comment by poqdavid** [comment]
Sorry for adding all of the plugins/mods but since I am not 100% sure if this is caused by a plugin or not I am going to send it all

**Comment by IzzelAliz** [comment]
This is simply a tick took too long. Unless you provide something like a spark report or I cannot help.

**Comment by poqdavid** [comment]
> This is simply a tick took too long. Unless you provide something like a spark report or I cannot help.

How should I do that cause when that happens server just hangs for a really long time and it doesn't respond to any commands
So I set the watchdog to crash the server after 3min if it didn't recover 
When I lowered the view-distance it did help a bit but it's not totally gone

**Comment by IzzelAliz** [comment]
You can use `jstack` several times if you sure you are experiencing the 3 min.

**Comment by poqdavid** [comment]
> You can use `jstack` several times if you sure you are experiencing the 3 min.

So once the server gets stuck I use `jstack` and generate a Java thread dump and that should provide us with the information needed to figure out this situation, awesome just to let you know this might take some time as this situation doesn't always happen, but I will reply with the dump as soon as I get it thanks.

**Comment by poqdavid** [comment]
@IzzelAliz here [jstack_thread_dmp.zip](https://github.com/IzzelAliz/Arclight/files/11265412/jstack_thread_dmp.zip) I managed to get a few thread dumps I hope it helps
Also if you don't like zip file I can send them individually too

**Comment by IzzelAliz** [comment]
None of these reports show any helpful information. I can only make a guess that, some player is moving so fast or moving into a not loaded chunk.

**Comment by poqdavid** [comment]
> None of these reports show any helpful information. I can only make a guess that, some player is moving so fast or moving into a not loaded chunk.

Oh ok thanks for looking into this
