### ISSUE TITLE
[1.19.2] Itemsadder packet issue

### ISSUE THREAD

**Issue by VOrlando520** [IzzelAliz/Arclight#956]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.19.2-1.0.1-0550c6cd

### OS & Java versions

OS: Debian 11 Java: Java17

### Plugins and Mods

```raw
Plugins: LuckPerms, VoidGen, Chunky, PlaceholderAPI, CobblemonPlaceholder, ChunkyBorder, BuycraftX, ServersNPC, Votifier, LoneLibs, ConsoleSpamFix, VoteParty, ProtocolLib, mcMMO, NBTAPI, Vault, ServerListPlus, StaffPlusPlus, WorldEdit, AnnouncerPlus, HeadDatabase, Multiverse-Core, DiscordSRV, AlonsoTags, TAB, BiomeCompass, CyberWorldReset, CMILib, StaffPlusPlusDiscord, Jobs, CMI, ItemsAdder, VotingPlugin, EpicBackpacks, DeluxeMenus, AdvancedCrates, FancyWaystones, ShopGUIPlus, CosmeticsCore, Rankup, CommandPanels, Quests, ShopGUIPlus-SellGUI, GriefDefender, Graves


Mods:
• minecraft server-1.19.2-20220805.130853-srg.jar : minecraft (1.19.2) - 1
• mods_folder smoothchunk-1.19.1-2.0.jar : smoothchunk (1.19.1-2.0) - 1
• JarInJar kffmod-3.11.0.jar : kotlinforforge (3.11.0) - 1
• minecraft forge-1.19.2-43.2.0-universal.jar : forge (43.2.0) - 1
• mods_folder NoChatReports-FORGE-1.19.2-v1.5.1.jar : nochatreports (1.19.2-v1.5.1) - 1
• mods_folder Xaeros_Minimap_23.3.1_Forge_1.19.1.jar : xaerominimap (23.3.1) - 1
• mods_folder konkrete_forge_1.6.0_MC_1.19-1.19.2.jar : konkrete (1.6.0) - 1
• mods_folder CobblemonExtras-forge-1.0.1+1.19.2.jar : cobblemonextras (1.0.1+1.19.2) - 1
• mods_folder architectury-6.5.69-forge.jar : architectury (6.5.69) - 1
• mods_folder Cobblemon-Broadcast-1.5.19045.jar : cobblemonbroadcast (1.5.19045) - 1
• mods_folder Cobblemon-forge-1.3.0+1.19.2.jar : cobblemon (1.3.0+1.19.2-SNAPSHOT) - 1
• arclight arclight-1.19.2-1.0.1-0550c6cd.jar : arclight (1.19.2-1.0.1-0550c6cd) - 1
```

### Description

Packets are not being sent or interacting with certain methods that are either not there or are private hence the

`[ItemsAdder] Unhandled exception occurred in onPacketReceiving(PacketEvent) for ItemsAdder
java.lang.IllegalAccessError: class ia.m.hZ tried to access method 'void org.bukkit.event.player.PlayerEvent.<init>(org.bukkit.entity.Player, boolean)' (ia.m.hZ is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader`

### Step to reproduce

1. install itemsadder
2. use any of their item packs and interact with them (anything that adds models or rank images)
3. the error will appear in console

### Logs

https://pastebin.com/BTZyL7vA

**Comment by IzzelAliz** [comment]
Report to itemsadder author.
