### ISSUE TITLE
World Spawn Chunks don't always load when spawning in

### ISSUE THREAD

**Issue by OakLoaf** [IzzelAliz/Arclight#957]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.8.jar

### OS & Java versions

Java 18

### Plugins and Mods

```raw
Mods:
• mods_folder journeymap-1.18.2-5.9.4-forge.jar : journeymap (5.9.4) - 1
• minecraft forge-1.18.2-40.2.0-universal.jar : forge (40.2.0) - 1
• minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1
• mods_folder TerraBlender-forge-1.18.2-1.2.0.126.jar : terrablender (1.2.0.126) - 1
• mods_folder flywheel-forge-1.18.2-0.6.8.jar : flywheel (0.6.8.a) - 1
• mods_folder create-1.18.2-0.5.0.jar : create (0.5.0.i) - 1
• arclight arclight-1.18.2-1.0.8-e80a33d2.jar : arclight (1.18.2-1.0.8-e80a33d2) - 1
• mods_folder Oh_The_Biomes_You_ll_Go-forge-1.18.2-1.4.7.jar : byg (1.4) - 1
• mods_folder WATERCoRE-1.3.1-B-QFIX.jar : watercore (1.3.1-B-QFIX) - 1
• mods_folder DynamicTrees-1.18.2-0.11.0-Beta6.jar : dynamictrees (1.18.2-0.11.0-Beta6) - 1
```

### Description

When loading into the server sometimes the world spawn chunks don't load and can cause the client to get stuck on "Loading terrain" I found that manually we can just teleport the player away and they will then be able to see the world properly. However the spawn chunks still continue to not load in, even if leaving and returning.

From what I've seen so far this has only happened to players who have disconnected in the spawn chunks

This only started happening after moving to arclight

### Step to reproduce

1. Disconnect in the spawn chunks
2. Reconnect

### Logs

There are no relevant logs

**Comment by IzzelAliz** [comment]
Can you reproduce without mods?
