### ISSUE TITLE
SkinRestore pluggin and TravelersBackpack mod incompatibility

### ISSUE THREAD

**Issue by garayco** [IzzelAliz/Arclight#959]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [ ] unable to reproduce in Spigot
- [ ] unable to reproduce in Forge

### Arclight version

GreatHorn/1.0.2

### OS & Java versions

Java 17

### Plugins and Mods

```raw
[19:41:47 INFO] [Console]: Plugins (1): SkinsRestorer

[19:42:00 INFO]: Mod List:
• minecraft server-1.19.3-20221207.122022-srg.jar : minecraft (1.19.3) - 1
• minecraft forge-1.19.3-44.1.8-universal.jar : forge (44.1.8) - 1
• arclight arclight-1.19.3-1.0.2-98f5a183.jar : arclight (1.19.3-1.0.2-98f5a183) - 1
• mods_folder TravelersBackpack-1.19.3-8.3.4.jar : travelersbackpack (8.3.4) - 1
```

### Description

When the skins its updated, the back mod crash and the back disappear. SkinsRestorer plugin has the option to disabled the skin updated when a player join the game. I'm  just desactivate this to solve the problem, but if you change the skin in the game the bug is reproduced and the player need to disconnect and connect again. 

### Step to reproduce

1. join the game with DisableOnJoinSkins: true
2. use a back
3. change your skin

**Comment by IzzelAliz** [comment]
This cannot be fixed in Arclight.
