### ISSUE TITLE
Incompatibility 1.19.2

### ISSUE THREAD

**Issue by xXjojojXx** [IzzelAliz/Arclight#967]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1

### OS & Java versions

Windows Server 2019 Java 18

### Plugins and Mods

```raw
https://www.curseforge.com/minecraft/modpacks/xx-unlimited-sky-xx/files/4482603
```

### Description

Create with the modpack server

### Step to reproduce

after creating the server as soon as you start it you get this error server does not start either

### Logs

[debug.log](https://github.com/IzzelAliz/Arclight/files/11225834/debug.log)
[latest.log](https://github.com/IzzelAliz/Arclight/files/11225835/latest.log)

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/xx-unlimited-sky-xx/files/4482603

**Comment by Decent60** [comment]
Not really an incompatibility. You have mods written on newer Forge than what ArcLight was using. Upgrade your forge and it should work.

**Comment by xXjojojXx** [comment]
[latest.log](https://github.com/IzzelAliz/Arclight/files/11238977/latest.log)
[debug.log](https://github.com/IzzelAliz/Arclight/files/11238978/debug.log)


set JAVA_MCSS="C:\Program Files\Eclipse Adoptium\jdk-18.0.2.101-hotspot\bin\java.exe"
@echo off
%JAVA_MCSS% @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.2.8/win_args.txt nogui %*
