### ISSUE TITLE
Stoneblock 3 v1.6.1 fails to launch due to out of data forge with Arclight

### ISSUE THREAD

**Issue by trevorgolden** [IzzelAliz/Arclight#968]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.18.2-1.0.8

### OS & Java versions

OS Alpine Linux, Ubuntu, and Debian (Tried all 3) java version is java 17

### Plugins and Mods

```raw
Check FTB's site for stoneblock 3 mods, it wont load so I cant exactly get you a list. 
No plugins
```

### Description

Server fails to launch upon startup. 

### Step to reproduce

Install SB3 server 1.6.1 
Install latest arclight release
Fail to launch due to arclight shipping with dependencies for Forge 40.1.80 opposed to 40.2.1/40.2.0

### Logs

https://hastebin.skyra.pw/iyekuwowak.prolog

### Server pack link (Optional)

https://feed-the-beast.com/modpacks/server-files

**Comment by Shybella** [comment]
Update Forge, Arclight has this option. Not a bug.
