### ISSUE TITLE
[1.18] Item Lookup Lag

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#972]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

Version arclight-1.18.2-1.0.9-SNAPSHOT-216cf6b

### OS & Java versions

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04) OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)

### Plugins and Mods

```raw
Plugins (23): LuckPerms, BlueMap, WorldEdit, NetherCoords, Chunky, AxCommandHider, CleanPing, Lootin, AFKPlus, spark, MOTD, GriefDefender, RenewableSponges, ChunkyBorder, ComandosDeComunicacion, Votifier, Stuff, ConsoleSpamFix, GDHooks, AntiTNTDupe, CoreProtect, VotingPlugin, Telepost

Mods: Create mod, Create Steam n' Rails, Create: Slice & Dice, Farmer's Delight, Sophisticated Backpacks, Voice Chat, XL Packets, Connectivity
```

### Description

During many months of my server's lifetime, there has been a lag issue regarding **Item Lookup** in modded inventories:

The issue is in Create mod contraptions, item vaults and belts, and also in the backpacks from the sophisticated storage mod

The issue does not seem to be the modded ways of outputting items, as hoppers also lag, even if the inventory is empty.

It seems to be only in inventories with weird slot amounts of weird max stack amount

Other modded inventories that have the usual 27 slots work lagless

### Step to reproduce

1. Open a server with the Create mod
2. Make a lot of 3x3x8 vaults that contain Smart Chutes or Funnels outputting items from them
3. take a profiler with spark

### Logs

There is serveral:

- Outputting below Mechanical Belts: https://spark.lucko.me/2tcALhtOqm
- Using chutes in Vaults/backpacks/below belts: https://spark.lucko.me/ArzzL6IFde
- Contraption with large inventory outputting items: (To be done)

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/kryeit-official

**Comment by IzzelAliz** [comment]
I don't think your spark profile shows any kind of lag that is related to Arclight.

**Comment by muriplz** [comment]
I'll investigate this with time, as I've moved to a good PC and this doesn't seem to happen anymore. It may have been due to my hardware. Closing for now. <3
