### ISSUE TITLE
Crash 1.16.5 - Enigmatica 6 - Astral Sorcery

### ISSUE THREAD

**Issue by Gaetann18** [IzzelAliz/Arclight#974]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.16.5-1.0.24.jar

### OS & Java versions

Try java 11 java 16 and java 17 same error

### Plugins and Mods

```raw
No plugins 
mods list : https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v2.4.0/serverstarter-2.4.0.jar
```

### Description

I have a crash that seems to be due to arstral sorcery

### Step to reproduce

Lunch server with arclight

### Logs

Crash report : https://pastebin.com/cWaGsZCR
Logs : https://pastes.io/yqdios0prv

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/enigmatica6

**Comment by IzzelAliz** [comment]
You are using optimization mods.
