### ISSUE TITLE
Arclight 1.16.5 在高版本 Java 环境下无法启用插件

### ISSUE THREAD

**Issue by SNWCreations** [IzzelAliz/Arclight#978]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-1.16.5-1.0.23-daa3c8bb

### Java 版本 | 操作系统

Java: Oracle JRE 17, 操作系统: 未知，可能是某个 GNU/Linux 发行版

### 相关 Mod/插件 的名称及版本

```raw
WarnOnMove (我的自制插件，仅使用了 Bukkit API)
```

### 错误描述

我的插件无法被启用，从报错日志可以看出是服务端调用 Unsafe 时出现了问题(很显然，我们都知道，自 Java 9 开始，这些内部库已经不可用)，我的插件没有抛出异常。

注意: 此错误不是由我报告的，是我的客户报告的，我只拿到了报错日志。

### 复现步骤

1. 安装我的插件
2. 启动服务器
3. 插件启用失败

### 报错信息

https://paste.fastmirror.net/?59610fd15f52694a#AHKwSFmMr6sPHAk6Us5v6T1w6My22AhX7pPNyAfPTCss

**Comment by SNWCreations** [comment]
抱歉，我注意到 1.0.24 版本，但是从更新日志未看出与此有关的修复。

**Comment by IzzelAliz** [comment]
你为什么不更新呢？

**Comment by SNWCreations** [comment]
已使用最新 SNAPSHOT 测试，无问题。
再次为我的打扰感到抱歉！
