### ISSUE TITLE
Horn with Forge 43.2.8 1.19.2(I know its not maintained)

### ISSUE THREAD

**Issue by maxiking913** [IzzelAliz/Arclight#980]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1

### OS & Java versions

zulu17.42.19-ca-jdk17.0.7-win_x64 | zulu19.32.13-ca-jdk19.0.2-win_x64

### Plugins and Mods

```raw
Reason: Many Modpacks are on 1.19.2 and now require the 43.2.8 since its a half recommended version
```

### Description

As title says. is there a way to make Horn(1.19.2) to Forge 43.2.8 ? it works up to 43.2.4 but further it crashes.

Greetings

**Comment by BorelBH** [comment]
vai sair atualização de compatibilidade para o forge 43.2.8?

**Comment by maxiking913** [comment]
idk what you wrote bro but its only going up to 43.2.4. 43.2.10 would be cool
