### ISSUE TITLE
1.19.4 no plugins folder

### ISSUE THREAD

**Issue by boutchhh** [IzzelAliz/Arclight#981]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

1.19.4 the latest

### OS & Java versions

the latest

### Plugins and Mods

```raw
no one
```

### Description

when i start the run.bat no plugin folder is created

**Comment by maxiking913** [comment]
dont start the run bat. read faq
