### ISSUE TITLE
[1.18.2 SNAPSHOT] Mobs (including hostiles) ignore you completely

### ISSUE THREAD

**Issue by lambor590** [IzzelAliz/Arclight#986]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.18.2-1.0.9-SNAPSHOT-216cf6b

### OS & Java versions

OS: Debian 11, Java: OpenJDK 17.0.7

### Plugins and Mods

```raw
No plugins.
No mods.
```

### Description

Well, mobs completely ignore you, including hostile mobs.

I tried hitting a mob, but still, it's like I'm a ghost lol.

I tried with an enderman, a zombie and a skeleton. No one reacted with my presence and even hitting them.

And I also tried with a lot of mods that add mobs, and they react the same way, if that can be called a reaction.

### Step to reproduce

Nothing, any mob doesn't hit you or react by anything you do.

### Logs

No logs, no errors or warnings in the console.

**Comment by eddyam2689** [comment]
The same thing happened to me with this version, they told me to use the releases version, specifically I used arclight-forge-1.18.2-1.0.8.jar and the error that the mobs ignored me was already corrected.

**Comment by lambor590** [comment]
The reason of this problem is because of [this](https://github.com/IzzelAliz/Arclight/commit/16a5f7413f8a09072b5cd46944fe0f1163118193) commit. Something is not working right on the event on which the mobs set you as their target.

I am using the snapshot version because I have a lot of mods that require a more recent version of Forge than 40.1.80.
Specifically, I have 180 mods on the server and 201 on the client. So an issue like this is a big problem for me. But the main problem I have is the Forge version, otherwise I would use the release version of Arclight.
