### ISSUE TITLE
[1.16.5] NoClassDefFoundError: ItemStackTileEntityRenderer 

### ISSUE THREAD

**Issue by iSoulEs** [IzzelAliz/Arclight#989]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.25-SNAPSHOT-695f936

### OS & Java versions

OS: Windows 10  JAVA: java jdk "16.0.2" 

### Plugins and Mods

```raw
Plugins (0):
 Mod List: armourersworkshop-forge-1.16.5-2.0.0-dev.179
```

### Description

As soon as you install it and start the server you will get the error `java.lang.NoClassDefFoundError:` `org/lwjgl/BufferUtils`
I managed to fix the error just by adding the necessary libraries.
https://github.com/iSoulEs/Arclight/commit/e2f2c58ab94d251d2e4c5f0ff50fd00b94df025b
you can test it in action build in the repo

Second error:

`java.lang.NoClassDefFoundError:` `net/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer`

Once the previous problem has been solved, this appears and checking the files said missing file is found, I thought it could be something from the mixin. but i dont know about it

### Step to reproduce

1. install the mod armourersworkshop-forge-1.16.5-2.0.0-dev.179 
2. run the server
3. Error
[armourersworkshop-forge-1.16.5-2.0.0-dev.179.zip](https://github.com/IzzelAliz/Arclight/files/11471916/armourersworkshop-forge-1.16.5-2.0.0-dev.179.zip)

### Logs

**First Error** 
 `java.lang.NoClassDefFoundError:` `org/lwjgl/BufferUtils`
logs:
https://pastebin.com/WnbypYfa

**Second error:**
`java.lang.NoClassDefFoundError:` `net/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer`
logs:
https://pastebin.com/07yJQ5B1

**Comment by IzzelAliz** [comment]
This is likely a mod issue and you probably need to report to their devs.

**Comment by iSoulEs** [comment]
> This is likely a mod issue and you probably need to report to their devs.

fixed BufferUtil in the mod but Arclight says...
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer

**Comment by iSoulEs** [comment]
[armourersworkshop-forge-1.16.5-2.0.0-dev.181.zip](https://github.com/IzzelAliz/Arclight/files/11640445/armourersworkshop-forge-1.16.5-2.0.0-dev.181.zip)
 its a mod bug?

**Comment by iSoulEs** [comment]
fixed! in armourers beta 21
