### ISSUE TITLE
Armor stand UUID bug

### ISSUE THREAD

**Issue by Dum4G** [IzzelAliz/Arclight#99]
### I am running

* **Arclight** 1.16-1.0.10 

* **This is the latest development version** [Y]

* **Java** 8 

* **Operating System** Windows, Linux on a host?

* **Plugins** Clean install

* **Mods** Clean install

### Description

Armor stand is functioning as usual, interacts with liquids and burns but it can't be destroyed even in creative mode. Console shows this warning:

`[Server thread/WARN] [net.minecraft.world.server.ServerWorld/]: Trying to add entity with duplicated UUID 0c913cdb-ad26-406d-bcf6-571a53f3f313. Existing minecraft:armor_stand#302, new: minecraft:armor_stand#302`

### Step to reproduce

1. Place armor stand
2. Try to destroy

**Reproducible in Forge** [N]

**Reproducible in Spigot** [N]

### Logs

[ERROR LOG](https://gist.github.com/Dum4G/d24c759f77fa79c7f8788bfef26e867a)

**Comment by IzzelAliz** [comment]
The warning is a vanilla bug https://bugs.mojang.com/browse/MC-196638 and should affect nothing.

Still looking into the removing code logic.
