### ISSUE TITLE
[1.16.5] [MineColonies] Entity Activation Range or need something similar

### ISSUE THREAD

**Issue by ntavi** [IzzelAliz/Arclight#990]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.16.5-1.0.24

### OS & Java versions

OS: Ubuntu 20 Java: openjdk version 8

### Plugins and Mods

```raw
Minecolonies 1.16.5 Version 1.0.978

Forge Version: 36.2.39
```

### Description

Hello. I have a mod that called "MineColonies". If you are in a certain range, your Civillians will do anything (work). If you exceed this range, the Civillians are starting to kinda "freeze" because of the minecraft's entity activation range. A way to fix that is to change the value of that into spigot.yml but in arclight it doesn't seem to work.

I tried it on another forge/spigot hybrid, Mohist and it works perfectly, but it got some other bugs that it didn't let me enjoy my gameplay.

Is there any other solution for this activation range?

More info:
- I tried to have clean arclight install with only that mod installed but I had the same issue

### Step to reproduce

1) Be close to a Civilian , they will do anything(work , move , etc)

2) Move out of that activation Range they will start to move VERY slowly or no moving at all

**Comment by PiTTl** [comment]
Hi
we had the same problem with 1.19.2. with mohist it was enough to adjust the activation range, unfortunately not with arclight. so I tried around for hours and it seems to have worked with the tracking range. I also set "others" and "misc" high because I don't know which one is for the colonists: (we have very large colonies)
entity tracking range:
       player: 48
       animal: 48
       monsters: 48
       mix: 999320
       other: 9996490
Luckily we don't have lags with only 4GB of RAM.

we are on arclight-1.19.2-1.0.1

**Comment by ntavi** [comment]
Nope.. Saddly it doesn't work even I put some trillions in there

**Comment by PiTTl** [comment]
sorry it didn't work for you. maybe it's because of our different minecraft version. It would be nice if this could be adjusted more easily

**Comment by ntavi** [comment]
After some ages I tried some values in there and worked.

For some reason it needs "Animal Entity Range" to be high. Anyway.. I post here my settings in case someone needs help

In spigot.yml


    entity-activation-range:
      animals: 512
      monsters: 32
      raiders: 32
      misc: 5120
      tick-inactive-villagers: true
    entity-tracking-range:
      players: 5120
      animals: 512
      monsters: 48
      misc: 5120
      other: 5120
      
      Thanks for anyone who tried to help me.
