### ISSUE TITLE
DistanceManagerMixin.removeAllTicketsFor causes a ConcurrentModificationException

### ISSUE THREAD

**Issue by davo899** [IzzelAliz/Arclight#993]
public <T> void removeAllTicketsFor(TicketType<T> ticketType, int ticketLevel, T ticketIdentifier) { 
         Ticket<T> target = new Ticket<>(ticketType, ticketLevel, ticketIdentifier); 
         Iterator<Long2ObjectMap.Entry<SortedArraySet<Ticket<?>>>> iterator = this.tickets.long2ObjectEntrySet().fastIterator(); 
         while (iterator.hasNext()) { 
             Long2ObjectMap.Entry<SortedArraySet<Ticket<?>>> entry = iterator.next(); 
             SortedArraySet<Ticket<?>> tickets = entry.getValue(); 
             if (tickets.remove(target)) { 
                 this.ticketTracker.update(entry.getLongKey(), getTicketLevelAt(tickets), false); 
                 if (tickets.isEmpty()) { 
                     iterator.remove(); 
                 } 
             } 
         } 
     }

**Comment by davo899** [comment]
This extract calls tickets.remove() inside a loop over the iterator for tickets, which will always throw a ConcurrentModificationException.

**Comment by IzzelAliz** [comment]
It won't.
