### ISSUE TITLE
[1.19.2] CREATE mod need forge version 43.2.3

### ISSUE THREAD

**Issue by Bammcool2011** [IzzelAliz/Arclight#994]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-forge-1.19.2-1.0.1

### OS & Java versions

build 17.0.7+7-Ubuntu-0ubuntu122.04.2

### Plugins and Mods

```raw
create-1.19.2-0.5.1.a
```

### Description

I have tried to use a custom Forge version on the FAQ page. However, when I replaced all the .txt files in .net/minecraftforge/forge..., and then started the server, it installed the old version. Now, I have no idea what to do. It would be great if you could help me resolve this issue.

https://imgur.com/a/5ujigDo

**Comment by kpetom** [comment]
Can you solve it?
